#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final DFT energy',
      rel_tolerance = 1.0e-8)

f.add(string = 'E_disp',
      abs_tolerance = 1.0e-6)

f.add(from_string = 'Final geometry (xyz format; angstrom)',
      num_lines = 16,
      abs_tolerance = 1.0e-5)

f.add(from_string = 'Interatomic separations (in Angstrom):',
      num_lines = 16,
      abs_tolerance = 1.0e-5)

test.run(['dft_disp_d3.dal'], ['CH4-dimer_STO-3G.mol'], {'out': f})

sys.exit(test.return_code)
