#!/bin/sh
#

info='
   mp2srlda_ener_nosym
   --------------
   Molecule:         Be2 
   Wave Function:    MP2-srLDA no frozen core / cc-pVDZ 
   Test Purpose:     Check MP2-srLDA energy 
'

#######################################################################
#  MOLECULE INPUT
#######################################################################
molecule='BASIS
cc-pVDZ
Be2

    1    0
        4.    2
Be1    0.0000000000000000  0.0000000000000000  -2.10000
Be2    0.0000000000000000  0.0000000000000000  2.10000
'

#######################################################################
#  DALTON INPUT
#######################################################################

dalton='**DALTON INPUT
.RUN WAVE
**WAVE FUNCTIONS
.HFSRDFT
.MP2
.SRFUN
SRXLDA SRCLDA
*SCF INPUT
.THRESHOLD
1.d-6
.DOUBLY OCCUPIED
4
*ORBITAL INPUT
.MOSTART
 H1DIAG
.NOSUPSYM
**INTEGRALS
.NOSUP
*TWOINT
.DOSRIN
.ERF
0.4
**END OF INPUT
'
#######################################################################




#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################

test='
check_mp2srdft_energy MP2 -28.9305930897 5e-7'                    

. ./functions || { echo "'functions' library not found." ; exit 1; }
check_gen_input "$0" "$info" "$molecule" "$dalton" "$test"


#######################################################################
