#define dsign sign
#define dabs abs
#define dsqrt sqrt
#define dexp exp
#define dreal real
#define dimag imag
#define dmod mod
#define dlog10 log10
#define dlog log
#define dcos cos
#define dacos acos
#define dsin sin

#define drotg srotg
#define drotmg srotmg
#define drot srot
#define drotm srotm
#define dswap sswap
#define dscal sscal
#define dcopy scopy
#define daxpy saxpy
#define ddot sdot
#define ddotu sdotu
#define ddotc sdotc
#define ddsdot sdsdot
#define dnrm2 snrm2
#define dasum sasum
#define didamax sidamax
#define dgemv sgemv
#define dgbmv sgbmv
#define dhbmv shbmv
#define dhpmv shpmv
#define dsymv ssymv
#define dsbmv ssbmv
#define dspmv sspmv
#define dtrmv strmv
#define dtbmv stbmv
#define dtpmv stpmv
#define dtrsv strsv
#define dtbsv stbsv
#define dtpsv stpsv
#define dger sger
#define dgeru sgeru
#define dgerc sgerc
#define dher sher
#define dhpr shpr
#define dher2 sher2
#define dhpr2 shpr2
#define dsyr ssyr
#define dspr sspr
#define dsyr2 ssyr2
#define dspr2 sspr2
#define dgemm sgemm
#define dsymm ssymm
#define dhemm shemm
#define dsyrkherk ssyrkherk
#define dsyr2k ssyr2k
#define dher2k sher2k
#define dtrmm strmm
#define dtrsm strsm

#define dbdsdc sbdsdc
#define dbdsqr sbdsqr
#define dcsum1 scsum1
#define ddisna sdisna
#define dgbbrd sgbbrd
#define dgbcon sgbcon
#define dgbequ sgbequ
#define dgbequb sgbequb
#define dgbrfs sgbrfs
#define dgbrfsx sgbrfsx
#define dgbsv sgbsv
#define dgbsvx sgbsvx
#define dgbsvxx sgbsvxx
#define dgbtf2 sgbtf2
#define dgbtrf sgbtrf
#define dgbtrs sgbtrs
#define dgebak sgebak
#define dgebal sgebal
#define dgebd2 sgebd2
#define dgebrd sgebrd
#define dgecon sgecon
#define dgeequ sgeequ
#define dgeequb sgeequb
#define dgees sgees
#define dgeesx sgeesx
#define dgeev sgeev
#define dgeevx sgeevx
#define dgegs sgegs
#define dgegv sgegv
#define dgehd2 sgehd2
#define dgehrd sgehrd
#define dgejsv sgejsv
#define dgelq2 sgelq2
#define dgelqf sgelqf
#define dgels sgels
#define dgelsd sgelsd
#define dgelss sgelss
#define dgelsx sgelsx
#define dgelsy sgelsy
#define dgeql2 sgeql2
#define dgeqlf sgeqlf
#define dgeqp3 sgeqp3
#define dgeqpf sgeqpf
#define dgeqr2 sgeqr2
#define dgeqrf sgeqrf
#define dgerfs sgerfs
#define dgerfsx sgerfsx
#define dgerq2 sgerq2
#define dgerqf sgerqf
#define dgesc2 sgesc2
#define dgesdd sgesdd
#define dgesv sgesv
#define dgesvd sgesvd
#define dgesvj sgesvj
#define dgesvx sgesvx
#define dgesvxx sgesvxx
#define dgetc2 sgetc2
#define dgetf2 sgetf2
#define dgetrf sgetrf
#define dgetri sgetri
#define dgetrs sgetrs
#define dggbak sggbak
#define dggbal sggbal
#define dgges sgges
#define dggesx sggesx
#define dggev sggev
#define dggevx sggevx
#define dggglm sggglm
#define dgghrd sgghrd
#define dgglse sgglse
#define dggqrf sggqrf
#define dggrqf sggrqf
#define dggsvd sggsvd
#define dggsvp sggsvp
#define dgsvj0 sgsvj0
#define dgsvj1 sgsvj1
#define dgtcon sgtcon
#define dgtrfs sgtrfs
#define dgtsv sgtsv
#define dgtsvx sgtsvx
#define dgttrf sgttrf
#define dgttrs sgttrs
#define dgtts2 sgtts2
#define dhgeqz shgeqz
#define dhsein shsein
#define dhseqr shseqr
#define disnan sisnan
#define dlabad slabad
#define dlabrd slabrd
#define dlacn2 slacn2
#define dlacon slacon
#define dlacpy slacpy
#define dladiv sladiv
#define dlae2 slae2
#define dlaebz slaebz
#define dlaed0 slaed0
#define dlaed1 slaed1
#define dlaed2 slaed2
#define dlaed3 slaed3
#define dlaed4 slaed4
#define dlaed5 slaed5
#define dlaed6 slaed6
#define dlaed7 slaed7
#define dlaed8 slaed8
#define dlaed9 slaed9
#define dlaeda slaeda
#define dlaein slaein
#define dlaev2 slaev2
#define dlaexc slaexc
#define dlag2 slag2
#define dlag2d slag2d
#define dla_gbamv sla_gbamv
#define dla_gbrcond sla_gbrcond
#define dla_gbrfsx_extended sla_gbrfsx_extended
#define dla_gbrpvgrw sla_gbrpvgrw
#define dla_geamv sla_geamv
#define dla_gercond sla_gercond
#define dla_gerfsx_extended sla_gerfsx_extended
#define dlags2 slags2
#define dlagtf slagtf
#define dlagtm slagtm
#define dlagts slagts
#define dlagv2 slagv2
#define dlahqr slahqr
#define dlahr2 slahr2
#define dlahrd slahrd
#define dlaic1 slaic1
#define dlaisnan slaisnan
#define dla_lin_berr sla_lin_berr
#define dlaln2 slaln2
#define dlals0 slals0
#define dlalsa slalsa
#define dlalsd slalsd
#define dlamch slamch
#define dlamrg slamrg
#define dlaneg slaneg
#define dlangb slangb
#define dlange slange
#define dlangt slangt
#define dlanhs slanhs
#define dlansb slansb
#define dlansf slansf
#define dlansp slansp
#define dlanst slanst
#define dlansy slansy
#define dlantb slantb
#define dlantp slantp
#define dlantr slantr
#define dlanv2 slanv2
#define dlapll slapll
#define dlapmt slapmt
#define dla_porcond sla_porcond
#define dla_porfsx_extended sla_porfsx_extended
#define dla_porpvgrw sla_porpvgrw
#define dlapy2 slapy2
#define dlapy3 slapy3
#define dlaqgb slaqgb
#define dlaqge slaqge
#define dlaqp2 slaqp2
#define dlaqps slaqps
#define dlaqr0 slaqr0
#define dlaqr1 slaqr1
#define dlaqr2 slaqr2
#define dlaqr3 slaqr3
#define dlaqr4 slaqr4
#define dlaqr5 slaqr5
#define dlaqsb slaqsb
#define dlaqsp slaqsp
#define dlaqsy slaqsy
#define dlaqtr slaqtr
#define dlar1v slar1v
#define dlar2v slar2v
#define dlarf slarf
#define dlarfb slarfb
#define dlarfg slarfg
#define dlarfp slarfp
#define dlarft slarft
#define dlarfx slarfx
#define dlargv slargv
#define dlarnv slarnv
#define dla_rpvgrw sla_rpvgrw
#define dlarra slarra
#define dlarrb slarrb
#define dlarrc slarrc
#define dlarrd slarrd
#define dlarre slarre
#define dlarrf slarrf
#define dlarrj slarrj
#define dlarrk slarrk
#define dlarrr slarrr
#define dlarrv slarrv
#define dlarscl2 slarscl2
#define dlartg slartg
#define dlartv slartv
#define dlaruv slaruv
#define dlarz slarz
#define dlarzb slarzb
#define dlarzt slarzt
#define dlas2 slas2
#define dlascl2 slascl2
#define dlascl slascl
#define dlasd0 slasd0
#define dlasd1 slasd1
#define dlasd2 slasd2
#define dlasd3 slasd3
#define dlasd4 slasd4
#define dlasd5 slasd5
#define dlasd6 slasd6
#define dlasd7 slasd7
#define dlasd8 slasd8
#define dlasd9 slasd9
#define dlasda slasda
#define dlasdq slasdq
#define dlasdt slasdt
#define dlaset slaset
#define dlasq1 slasq1
#define dlasq2 slasq2
#define dlasq3 slasq3
#define dlasq4 slasq4
#define dlasq5 slasq5
#define dlasq6 slasq6
#define dlasr slasr
#define dlasrt slasrt
#define dlassq slassq
#define dlasv2 slasv2
#define dlaswp slaswp
#define dlasy2 slasy2
#define dla_syamv sla_syamv
#define dlasyf slasyf
#define dla_syrcond sla_syrcond
#define dla_syrfsx_extended sla_syrfsx_extended
#define dla_syrpvgrw sla_syrpvgrw
#define dlatbs slatbs
#define dlatdf slatdf
#define dlatps slatps
#define dlatrd slatrd
#define dlatrs slatrs
#define dlatrz slatrz
#define dlatzm slatzm
#define dlauu2 slauu2
#define dlauum slauum
#define dla_wwaddw sla_wwaddw
#define dlazq3 slazq3
#define dlazq4 slazq4
#define dopgtr sopgtr
#define dopmtr sopmtr
#define dorg2l sorg2l
#define dorg2r sorg2r
#define dorgbr sorgbr
#define dorghr sorghr
#define dorgl2 sorgl2
#define dorglq sorglq
#define dorgql sorgql
#define dorgqr sorgqr
#define dorgr2 sorgr2
#define dorgrq sorgrq
#define dorgtr sorgtr
#define dorm2l sorm2l
#define dorm2r sorm2r
#define dormbr sormbr
#define dormhr sormhr
#define dorml2 sorml2
#define dormlq sormlq
#define dormql sormql
#define dormqr sormqr
#define dormr2 sormr2
#define dormr3 sormr3
#define dormrq sormrq
#define dormrz sormrz
#define dormtr sormtr
#define dpbcon spbcon
#define dpbequ spbequ
#define dpbrfs spbrfs
#define dpbstf spbstf
#define dpbsv spbsv
#define dpbsvx spbsvx
#define dpbtf2 spbtf2
#define dpbtrf spbtrf
#define dpbtrs spbtrs
#define dpftrf spftrf
#define dpftri spftri
#define dpftrs spftrs
#define dpocon spocon
#define dpoequ spoequ
#define dpoequb spoequb
#define dporfs sporfs
#define dporfsx sporfsx
#define dposv sposv
#define dposvx sposvx
#define dposvxx sposvxx
#define dpotf2 spotf2
#define dpotrf spotrf
#define dpotri spotri
#define dpotrs spotrs
#define dppcon sppcon
#define dppequ sppequ
#define dpprfs spprfs
#define dppsv sppsv
#define dppsvx sppsvx
#define dpptrf spptrf
#define dpptri spptri
#define dpptrs spptrs
#define dpstf2 spstf2
#define dpstrf spstrf
#define dptcon sptcon
#define dpteqr spteqr
#define dptrfs sptrfs
#define dptsv sptsv
#define dptsvx sptsvx
#define dpttrf spttrf
#define dpttrs spttrs
#define dptts2 sptts2
#define dqueleton squeleton
#define drscl srscl
#define dsbev ssbev
#define dsbevd ssbevd
#define dsbevx ssbevx
#define dsbgst ssbgst
#define dsbgv ssbgv
#define dsbgvd ssbgvd
#define dsbgvx ssbgvx
#define dsbtrd ssbtrd
#define dsfrk ssfrk
#define dspcon sspcon
#define dspev sspev
#define dspevd sspevd
#define dspevx sspevx
#define dspgst sspgst
#define dspgv sspgv
#define dspgvd sspgvd
#define dspgvx sspgvx
#define dsprfs ssprfs
#define dspsv sspsv
#define dspsvx sspsvx
#define dsptrd ssptrd
#define dsptrf ssptrf
#define dsptri ssptri
#define dsptrs ssptrs
#define dstebz sstebz
#define dstedc sstedc
#define dstegr sstegr
#define dstein sstein
#define dstemr sstemr
#define dsteqr ssteqr
#define dsterf ssterf
#define dstev sstev
#define dstevd sstevd
#define dstevr sstevr
#define dstevx sstevx
#define dsycon ssycon
#define dsyequb ssyequb
#define dsyev ssyev
#define dsyevd ssyevd
#define dsyevr ssyevr
#define dsyevx ssyevx
#define dsygs2 ssygs2
#define dsygst ssygst
#define dsygv ssygv
#define dsygvd ssygvd
#define dsygvx ssygvx
#define dsyrfs ssyrfs
#define dsyrfsx ssyrfsx
#define dsysv ssysv
#define dsysvx ssysvx
#define dsysvxx ssysvxx
#define dsytd2 ssytd2
#define dsytf2 ssytf2
#define dsytrd ssytrd
#define dsytrf ssytrf
#define dsytri ssytri
#define dsytrs ssytrs
#define dtbcon stbcon
#define dtbrfs stbrfs
#define dtbtrs stbtrs
#define dtfsm stfsm
#define dtftri stftri
#define dtfttp stfttp
#define dtfttr stfttr
#define dtgevc stgevc
#define dtgex2 stgex2
#define dtgexc stgexc
#define dtgsen stgsen
#define dtgsja stgsja
#define dtgsna stgsna
#define dtgsy2 stgsy2
#define dtgsyl stgsyl
#define dtpcon stpcon
#define dtprfs stprfs
#define dtptri stptri
#define dtptrs stptrs
#define dtpttf stpttf
#define dtpttr stpttr
#define dtrcon strcon
#define dtrevc strevc
#define dtrexc strexc
#define dtrrfs strrfs
#define dtrsen strsen
#define dtrsna strsna
#define dtrsyl strsyl
#define dtrti2 strti2
#define dtrtri strtri
#define dtrtrs strtrs
#define dtrttf strttf
#define dtrttp strttp
#define dtzrqf stzrqf
#define dtzrzf stzrzf


#define DSIGN SIGN
#define DABS ABS
#define DSQRT SQRT
#define DEXP exp
#define DREAL real
#define DIMAG imag
#define DMOD mod
#define DLOG10 log10
#define DLOG log
#define DCOS cos
#define DACOS acos
#define DSIN sin

#define DROTG SROTG
#define DROTMG SROTMG
#define DROT SROT
#define DROTM SROTM
#define DSWAP SSWAP
#define DSCAL SSCAL
#define DCOPY SCOPY
#define DAXPY SAXPY
#define DDOT SDOT
#define DDOTU SDOTU
#define DDOTC SDOTC
#define DDSDOT SDSDOT
#define DNRM2 SNRM2
#define DASUM SASUM
#define DIDAMAX SIDAMAX
#define DGEMV SGEMV
#define DGBMV SGBMV
#define DHBMV SHBMV
#define DHPMV SHPMV
#define DSYMV SSYMV
#define DSBMV SSBMV
#define DSPMV SSPMV
#define DTRMV STRMV
#define DTBMV STBMV
#define DTPMV STPMV
#define DTRSV STRSV
#define DTBSV STBSV
#define DTPSV STPSV
#define DGER SGER
#define DGERU SGERU
#define DGERC SGERC
#define DHER SHER
#define DHPR SHPR
#define DHER2 SHER2
#define DHPR2 SHPR2
#define DSYR SSYR
#define DSPR SSPR
#define DSYR2 SSYR2
#define DSPR2 SSPR2
#define DGEMM SGEMM
#define DSYMM SSYMM
#define DHEMM SHEMM
#define DSYRKHERK SSYRKHERK
#define DSYR2K SSYR2K
#define DHER2K SHER2K
#define DTRMM STRMM
#define DTRSM STRSM

#define DBDSDC SBDSDC
#define DBDSQR SBDSQR
#define DCSUM1 SCSUM1
#define DDISNA SDISNA
#define DGBBRD SGBBRD
#define DGBCON SGBCON
#define DGBEQU SGBEQU
#define DGBEQUB SGBEQUB
#define DGBRFS SGBRFS
#define DGBRFSX SGBRFSX
#define DGBSV SGBSV
#define DGBSVX SGBSVX
#define DGBSVXX SGBSVXX
#define DGBTF2 SGBTF2
#define DGBTRF SGBTRF
#define DGBTRS SGBTRS
#define DGEBAK SGEBAK
#define DGEBAL SGEBAL
#define DGEBD2 SGEBD2
#define DGEBRD SGEBRD
#define DGECON SGECON
#define DGEEQU SGEEQU
#define DGEEQUB SGEEQUB
#define DGEES SGEES
#define DGEESX SGEESX
#define DGEEV SGEEV
#define DGEEVX SGEEVX
#define DGEGS SGEGS
#define DGEGV SGEGV
#define DGEHD2 SGEHD2
#define DGEHRD SGEHRD
#define DGEJSV SGEJSV
#define DGELQ2 SGELQ2
#define DGELQF SGELQF
#define DGELS SGELS
#define DGELSD SGELSD
#define DGELSS SGELSS
#define DGELSX SGELSX
#define DGELSY SGELSY
#define DGEQL2 SGEQL2
#define DGEQLF SGEQLF
#define DGEQP3 SGEQP3
#define DGEQPF SGEQPF
#define DGEQR2 SGEQR2
#define DGEQRF SGEQRF
#define DGERFS SGERFS
#define DGERFSX SGERFSX
#define DGERQ2 SGERQ2
#define DGERQF SGERQF
#define DGESC2 SGESC2
#define DGESDD SGESDD
#define DGESV SGESV
#define DGESVD SGESVD
#define DGESVJ SGESVJ
#define DGESVX SGESVX
#define DGESVXX SGESVXX
#define DGETC2 SGETC2
#define DGETF2 SGETF2
#define DGETRF SGETRF
#define DGETRI SGETRI
#define DGETRS SGETRS
#define DGGBAK SGGBAK
#define DGGBAL SGGBAL
#define DGGES SGGES
#define DGGESX SGGESX
#define DGGEV SGGEV
#define DGGEVX SGGEVX
#define DGGGLM SGGGLM
#define DGGHRD SGGHRD
#define DGGLSE SGGLSE
#define DGGQRF SGGQRF
#define DGGRQF SGGRQF
#define DGGSVD SGGSVD
#define DGGSVP SGGSVP
#define DGSVJ0 SGSVJ0
#define DGSVJ1 SGSVJ1
#define DGTCON SGTCON
#define DGTRFS SGTRFS
#define DGTSV SGTSV
#define DGTSVX SGTSVX
#define DGTTRF SGTTRF
#define DGTTRS SGTTRS
#define DGTTS2 SGTTS2
#define DHGEQZ SHGEQZ
#define DHSEIN SHSEIN
#define DHSEQR SHSEQR
#define DISNAN SISNAN
#define DLABAD SLABAD
#define DLABRD SLABRD
#define DLACN2 SLACN2
#define DLACON SLACON
#define DLACPY SLACPY
#define DLADIV SLADIV
#define DLAE2 SLAE2
#define DLAEBZ SLAEBZ
#define DLAED0 SLAED0
#define DLAED1 SLAED1
#define DLAED2 SLAED2
#define DLAED3 SLAED3
#define DLAED4 SLAED4
#define DLAED5 SLAED5
#define DLAED6 SLAED6
#define DLAED7 SLAED7
#define DLAED8 SLAED8
#define DLAED9 SLAED9
#define DLAEDA SLAEDA
#define DLAEIN SLAEIN
#define DLAEV2 SLAEV2
#define DLAEXC SLAEXC
#define DLAG2 SLAG2
#define DLAG2D SLAG2D
#define DLA_GBAMV SLA_GBAMV
#define DLA_GBRCOND SLA_GBRCOND
#define DLA_GBRFSX_EXTENDED SLA_GBRFSX_EXTENDED
#define DLA_GBRPVGRW SLA_GBRPVGRW
#define DLA_GEAMV SLA_GEAMV
#define DLA_GERCOND SLA_GERCOND
#define DLA_GERFSX_EXTENDED SLA_GERFSX_EXTENDED
#define DLAGS2 SLAGS2
#define DLAGTF SLAGTF
#define DLAGTM SLAGTM
#define DLAGTS SLAGTS
#define DLAGV2 SLAGV2
#define DLAHQR SLAHQR
#define DLAHR2 SLAHR2
#define DLAHRD SLAHRD
#define DLAIC1 SLAIC1
#define DLAISNAN SLAISNAN
#define DLA_LIN_BERR SLA_LIN_BERR
#define DLALN2 SLALN2
#define DLALS0 SLALS0
#define DLALSA SLALSA
#define DLALSD SLALSD
#define DLAMCH SLAMCH
#define DLAMRG SLAMRG
#define DLANEG SLANEG
#define DLANGB SLANGB
#define DLANGE SLANGE
#define DLANGT SLANGT
#define DLANHS SLANHS
#define DLANSB SLANSB
#define DLANSF SLANSF
#define DLANSP SLANSP
#define DLANST SLANST
#define DLANSY SLANSY
#define DLANTB SLANTB
#define DLANTP SLANTP
#define DLANTR SLANTR
#define DLANV2 SLANV2
#define DLAPLL SLAPLL
#define DLAPMT SLAPMT
#define DLA_PORCOND SLA_PORCOND
#define DLA_PORFSX_EXTENDED SLA_PORFSX_EXTENDED
#define DLA_PORPVGRW SLA_PORPVGRW
#define DLAPY2 SLAPY2
#define DLAPY3 SLAPY3
#define DLAQGB SLAQGB
#define DLAQGE SLAQGE
#define DLAQP2 SLAQP2
#define DLAQPS SLAQPS
#define DLAQR0 SLAQR0
#define DLAQR1 SLAQR1
#define DLAQR2 SLAQR2
#define DLAQR3 SLAQR3
#define DLAQR4 SLAQR4
#define DLAQR5 SLAQR5
#define DLAQSB SLAQSB
#define DLAQSP SLAQSP
#define DLAQSY SLAQSY
#define DLAQTR SLAQTR
#define DLAR1V SLAR1V
#define DLAR2V SLAR2V
#define DLARF SLARF
#define DLARFB SLARFB
#define DLARFG SLARFG
#define DLARFP SLARFP
#define DLARFT SLARFT
#define DLARFX SLARFX
#define DLARGV SLARGV
#define DLARNV SLARNV
#define DLA_RPVGRW SLA_RPVGRW
#define DLARRA SLARRA
#define DLARRB SLARRB
#define DLARRC SLARRC
#define DLARRD SLARRD
#define DLARRE SLARRE
#define DLARRF SLARRF
#define DLARRJ SLARRJ
#define DLARRK SLARRK
#define DLARRR SLARRR
#define DLARRV SLARRV
#define DLARSCL2 SLARSCL2
#define DLARTG SLARTG
#define DLARTV SLARTV
#define DLARUV SLARUV
#define DLARZ SLARZ
#define DLARZB SLARZB
#define DLARZT SLARZT
#define DLAS2 SLAS2
#define DLASCL2 SLASCL2
#define DLASCL SLASCL
#define DLASD0 SLASD0
#define DLASD1 SLASD1
#define DLASD2 SLASD2
#define DLASD3 SLASD3
#define DLASD4 SLASD4
#define DLASD5 SLASD5
#define DLASD6 SLASD6
#define DLASD7 SLASD7
#define DLASD8 SLASD8
#define DLASD9 SLASD9
#define DLASDA SLASDA
#define DLASDQ SLASDQ
#define DLASDT SLASDT
#define DLASET SLASET
#define DLASQ1 SLASQ1
#define DLASQ2 SLASQ2
#define DLASQ3 SLASQ3
#define DLASQ4 SLASQ4
#define DLASQ5 SLASQ5
#define DLASQ6 SLASQ6
#define DLASR SLASR
#define DLASRT SLASRT
#define DLASSQ SLASSQ
#define DLASV2 SLASV2
#define DLASWP SLASWP
#define DLASY2 SLASY2
#define DLA_SYAMV SLA_SYAMV
#define DLASYF SLASYF
#define DLA_SYRCOND SLA_SYRCOND
#define DLA_SYRFSX_EXTENDED SLA_SYRFSX_EXTENDED
#define DLA_SYRPVGRW SLA_SYRPVGRW
#define DLATBS SLATBS
#define DLATDF SLATDF
#define DLATPS SLATPS
#define DLATRD SLATRD
#define DLATRS SLATRS
#define DLATRZ SLATRZ
#define DLATZM SLATZM
#define DLAUU2 SLAUU2
#define DLAUUM SLAUUM
#define DLA_WWADDW SLA_WWADDW
#define DLAZQ3 SLAZQ3
#define DLAZQ4 SLAZQ4
#define DOPGTR SOPGTR
#define DOPMTR SOPMTR
#define DORG2L SORG2L
#define DORG2R SORG2R
#define DORGBR SORGBR
#define DORGHR SORGHR
#define DORGL2 SORGL2
#define DORGLQ SORGLQ
#define DORGQL SORGQL
#define DORGQR SORGQR
#define DORGR2 SORGR2
#define DORGRQ SORGRQ
#define DORGTR SORGTR
#define DORM2L SORM2L
#define DORM2R SORM2R
#define DORMBR SORMBR
#define DORMHR SORMHR
#define DORML2 SORML2
#define DORMLQ SORMLQ
#define DORMQL SORMQL
#define DORMQR SORMQR
#define DORMR2 SORMR2
#define DORMR3 SORMR3
#define DORMRQ SORMRQ
#define DORMRZ SORMRZ
#define DORMTR SORMTR
#define DPBCON SPBCON
#define DPBEQU SPBEQU
#define DPBRFS SPBRFS
#define DPBSTF SPBSTF
#define DPBSV SPBSV
#define DPBSVX SPBSVX
#define DPBTF2 SPBTF2
#define DPBTRF SPBTRF
#define DPBTRS SPBTRS
#define DPFTRF SPFTRF
#define DPFTRI SPFTRI
#define DPFTRS SPFTRS
#define DPOCON SPOCON
#define DPOEQU SPOEQU
#define DPOEQUB SPOEQUB
#define DPORFS SPORFS
#define DPORFSX SPORFSX
#define DPOSV SPOSV
#define DPOSVX SPOSVX
#define DPOSVXX SPOSVXX
#define DPOTF2 SPOTF2
#define DPOTRF SPOTRF
#define DPOTRI SPOTRI
#define DPOTRS SPOTRS
#define DPPCON SPPCON
#define DPPEQU SPPEQU
#define DPPRFS SPPRFS
#define DPPSV SPPSV
#define DPPSVX SPPSVX
#define DPPTRF SPPTRF
#define DPPTRI SPPTRI
#define DPPTRS SPPTRS
#define DPSTF2 SPSTF2
#define DPSTRF SPSTRF
#define DPTCON SPTCON
#define DPTEQR SPTEQR
#define DPTRFS SPTRFS
#define DPTSV SPTSV
#define DPTSVX SPTSVX
#define DPTTRF SPTTRF
#define DPTTRS SPTTRS
#define DPTTS2 SPTTS2
#define DQUELETON SQUELETON
#define DRSCL SRSCL
#define DSBEV SSBEV
#define DSBEVD SSBEVD
#define DSBEVX SSBEVX
#define DSBGST SSBGST
#define DSBGV SSBGV
#define DSBGVD SSBGVD
#define DSBGVX SSBGVX
#define DSBTRD SSBTRD
#define DSFRK SSFRK
#define DSPCON SSPCON
#define DSPEV SSPEV
#define DSPEVD SSPEVD
#define DSPEVX SSPEVX
#define DSPGST SSPGST
#define DSPGV SSPGV
#define DSPGVD SSPGVD
#define DSPGVX SSPGVX
#define DSPRFS SSPRFS
#define DSPSV SSPSV
#define DSPSVX SSPSVX
#define DSPTRD SSPTRD
#define DSPTRF SSPTRF
#define DSPTRI SSPTRI
#define DSPTRS SSPTRS
#define DSTEBZ SSTEBZ
#define DSTEDC SSTEDC
#define DSTEGR SSTEGR
#define DSTEIN SSTEIN
#define DSTEMR SSTEMR
#define DSTEQR SSTEQR
#define DSTERF SSTERF
#define DSTEV SSTEV
#define DSTEVD SSTEVD
#define DSTEVR SSTEVR
#define DSTEVX SSTEVX
#define DSYCON SSYCON
#define DSYEQUB SSYEQUB
#define DSYEV SSYEV
#define DSYEVD SSYEVD
#define DSYEVR SSYEVR
#define DSYEVX SSYEVX
#define DSYGS2 SSYGS2
#define DSYGST SSYGST
#define DSYGV SSYGV
#define DSYGVD SSYGVD
#define DSYGVX SSYGVX
#define DSYRFS SSYRFS
#define DSYRFSX SSYRFSX
#define DSYSV SSYSV
#define DSYSVX SSYSVX
#define DSYSVXX SSYSVXX
#define DSYTD2 SSYTD2
#define DSYTF2 SSYTF2
#define DSYTRD SSYTRD
#define DSYTRF SSYTRF
#define DSYTRI SSYTRI
#define DSYTRS SSYTRS
#define DTBCON STBCON
#define DTBRFS STBRFS
#define DTBTRS STBTRS
#define DTFSM STFSM
#define DTFTRI STFTRI
#define DTFTTP STFTTP
#define DTFTTR STFTTR
#define DTGEVC STGEVC
#define DTGEX2 STGEX2
#define DTGEXC STGEXC
#define DTGSEN STGSEN
#define DTGSJA STGSJA
#define DTGSNA STGSNA
#define DTGSY2 STGSY2
#define DTGSYL STGSYL
#define DTPCON STPCON
#define DTPRFS STPRFS
#define DTPTRI STPTRI
#define DTPTRS STPTRS
#define DTPTTF STPTTF
#define DTPTTR STPTTR
#define DTRCON STRCON
#define DTREVC STREVC
#define DTREXC STREXC
#define DTRRFS STRRFS
#define DTRSEN STRSEN
#define DTRSNA STRSNA
#define DTRSYL STRSYL
#define DTRTI2 STRTI2
#define DTRTRI STRTRI
#define DTRTRS STRTRS
#define DTRTTF STRTTF
#define DTRTTP STRTTP
#define DTZRQF STZRQF
#define DTZRZF STZRZF
