#!/usr/bin/env python


import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(abs_tolerance = 1.0e-4,
      ignore_sign = True) # all lines

test.run(['molden.inp'], ['CH2O_3-21G.mol'],
         f={'molden.inp': f}, args='-get molden.inp')

sys.exit(test.return_code)
