#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'TEST STRING',
      rel_tolerance = 1.0e-7)

test.run(['cc3_HF_631G_pol.dal'], ['cc3_HF_631G_pol.mol'], f={'out': f})

sys.exit(test.return_code)
