#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(from_string = '  *** Computed FV vector ***',
      num_lines = 11,
      rel_tolerance = 1.0e-8)

f.add(from_string = '  *** Computed MQ vector ***',
      num_lines = 12,
      rel_tolerance = 1.0e-8)

f.add(from_string = '     QM/NP/MM calculation converged     :',
      num_lines = 7,
      rel_tolerance = 1.0e-8)

test.run(['qmcmm.dal'], ['qmcmm.mol'], f={'out': f}, args='-put POTENTIAL.INP')

sys.exit(test.return_code)
