########## Test description ########################
START DESCRIPTION
KEYWORDS: pcm dft water symmetry mcd bterm long
END DESCRIPTION

########## Check list ##############################
START CHECKLIST
enedft
tes
nuc
sym
cmass
omegab
Bterm
END CHECKLIST

########## DALTON.INP ##############################
START DALINP
**DALTON INPUT
.RUN WAVE FUNCTION
.RUN RESPONSE
*PCM
.NPCMMT
0
.EPS
 24.55
.RSOLV
 2.180
*PCMCAV
.AREATS
0.5
**WAVE FUNCTIONS
.DFT
B3LYP
*SCF INPUT
**RESPONSE
*QUADRATIC
.SINGLE RESIDUE
.MCDBTERM
.ROOTS
 4 4 4 4
*END OF INPUT
END DALINP

########## MOLECULE.INP ############################
START MOLINP
BASIS
aug-cc-pVDZ
magnet
nuova base
    2    2 X Y
        8.    1
O      0.0000000000  0.0000000000  -0.1258515023
        1.    1
H      0.0000000000  1.4523500000   0.9986773907
END MOLINP

########## Reference Output ########################
START REFOUT
 <<<<<<<<<< OUTPUT FROM GENERAL INPUT PROCESSING >>>>>>>>>>


 Default print level:        0

    Integral sections will be executed
    "Old" integral transformation used (limited to max 255 basis functions)
    Wave function sections will be executed
    Dynamic molecular property section will be executed

     -----------------------------------
     Input for PCM solvation calculation 
     -----------------------------------
     ICOMPCM =       0          SOLVNT=INPUT        EPS   = 24.5500     EPSINF=  0.0000
     RSOLV =  2.1800

     ICESPH =       0     NESFP =       0
     OMEGA = 40.0000     RET   =  0.2000     FRO   =  0.7000

     IPRPCM=       0

     NON-EQ = F     NEQRSP =F
 POLYG 60

     INPUT FOR CAVITY DEFINITION 
     ---------------------------
     ATOM         COORDINATES           RADIUS 

Starting in Integral Section -



    *************************************************************************
    ****************** Output from HERMIT input processing ******************
    *************************************************************************



    *************************************************************************
    ****************** Output from READIN input processing ******************
    *************************************************************************



  Title Cards
  -----------

  magnet                                                                  
  nuova base                                                              
  Used basis set file for basis set for elements with Z =   8 :
     "/home/luca/programs/dalton/basis/aug-cc-pVDZ"
  Used basis set file for basis set for elements with Z =   1 :
     "/home/luca/programs/dalton/basis/aug-cc-pVDZ"


  Symmetry Operations
  -------------------

  Symmetry operations: 2



                          SYMGRP:Point group information
                          ------------------------------

Point group: C2v

   * The point group was generated by:

      Reflection in the yz-plane
      Reflection in the xz-plane

   * Group multiplication table

        |  E   C2z  Oxz  Oyz
   -----+--------------------
     E  |  E 
    C2z | C2z   E 
    Oxz | Oxz  Oyz   E 
    Oyz | Oyz  Oxz  C2z   E 

   * Character table

        |  E   C2z  Oxz  Oyz
   -----+--------------------
    A1  |   1    1    1    1
    B1  |   1   -1    1   -1
    B2  |   1   -1   -1    1
    A2  |   1    1   -1   -1

   * Direct product table

        | A1   B1   B2   A2 
   -----+--------------------
    A1  | A1 
    B1  | B1   A1 
    B2  | B2   A2   A1 
    A2  | A2   B2   B1   A1 
 ********SPHERES IN SPHGEN************
 INDEX        X        Y         Z        R
   1    0.0000000000e+00    0.0000000000e+00   -1.2585150230e-01    1.5000000000e+00
   2    0.0000000000e+00    1.4523500000e+00    9.9867739070e-01    1.2000000000e+00
   3    0.0000000000e+00   -1.4523500000e+00    9.9867739070e-01    1.2000000000e+00


                                 Isotopic Masses
                                 ---------------

                           O          15.994915
                           H    1      1.007825
                           H    2      1.007825

                       Total mass:    18.010565 amu
                       Natural abundance:  99.730 %

 Center-of-mass coordinates (A):    0.000000    0.000000    0.000000


  Atoms and basis sets
  --------------------

  Number of atom types:     2
  Total number of atoms:    3

  Basis set used is "aug-cc-pVDZ" from the basis set library.

  label    atoms   charge   prim   cont     basis
  ----------------------------------------------------------------------
  O           1    8.0000    35    23      [10s5p2d|4s3p2d]                                   
  H           2    1.0000    11     9      [5s2p|3s2p]                                        
  ----------------------------------------------------------------------
  total:      3   10.0000    57    41
  ----------------------------------------------------------------------
  Spherical harmonic basis used.

  Threshold for integrals:  1.00e-15


  Cartesian Coordinates (a.u.)
  ----------------------------

  Total number of coordinates:    9
  O       :    1  x   0.0000000000   2  y   0.0000000000   3  z  -0.1258515023
  H   / 1 :    4  x   0.0000000000   5  y   1.4523500000   6  z   0.9986773907
  H   / 2 :    7  x   0.0000000000   8  y  -1.4523500000   9  z   0.9986773907


  Symmetry Coordinates
  --------------------

  Number of coordinates in each symmetry:    3   2   3   1

  Symmetry  A1  ( 1)

   1   O     z    3
   2   H     y    [  5  -   8 ]/2
   3   H     z    [  6  +   9 ]/2

  Symmetry  B1  ( 2)

   4   O     x    1
   5   H     x    [  4  +   7 ]/2

  Symmetry  B2  ( 3)

   6   O     y    2
   7   H     y    [  5  +   8 ]/2
   8   H     z    [  6  -   9 ]/2

  Symmetry  A2  ( 4)

   9   H     x    [  4  -   7 ]/2


   Interatomic separations (in Angstrom):
   --------------------------------------

            O           H    1      H    2
            ------      ------      ------
 O     :    0.000000
 H    1:    0.972000    0.000000
 H    2:    0.972000    1.537101    0.000000


  Max interatomic separation is    1.5371 Angstrom
  between atoms "H    2" and "H    1".


  Bond distances (Angstrom):
  --------------------------

                  atom 1     atom 2       distance
                  ------     ------       --------
  bond distance:  H    1     O            0.972000
  bond distance:  H    2     O            0.972000


  Bond angles (degrees):
  ----------------------

                  atom 1     atom 2     atom 3         angle
                  ------     ------     ------         -----
  bond angle:     H    1     O          H    2       104.500




 Principal moments of inertia (u*A**2) and principal axes
 --------------------------------------------------------

   IA       0.633889          0.000000    1.000000    0.000000
   IB       1.190584          0.000000    0.000000    1.000000
   IC       1.824473          1.000000    0.000000    0.000000


 Rotational constants
 --------------------

 The molecule is planar.

               A                   B                   C

         797267.3440         424480.0013         277000.0234 MHz
           26.593976           14.159129            9.239726 cm-1


  Nuclear repulsion energy :    9.055004525638


  Symmetry Orbitals
  -----------------

  Number of orbitals in each symmetry:              18   7  12   4


  Symmetry  A1 ( 1)

    1     O        1s         1
    2     O        1s         2
    3     O        1s         3
    4     O        1s         4
    5     O        2pz        7
    6     O        2pz       10
    7     O        2pz       13
    8     O        3d0       16
    9     O        3d2+      18
   10     O        3d0       21
   11     O        3d2+      23
   12     H        1s        24  +  25
   13     H        1s        26  +  27
   14     H        1s        28  +  29
   15     H        2py       32  -  33
   16     H        2pz       34  +  35
   17     H        2py       38  -  39
   18     H        2pz       40  +  41


  Symmetry  B1 ( 2)

   19     O        2px        5
   20     O        2px        8
   21     O        2px       11
   22     O        3d1+      17
   23     O        3d1+      22
   24     H        2px       30  +  31
   25     H        2px       36  +  37


  Symmetry  B2 ( 3)

   26     O        2py        6
   27     O        2py        9
   28     O        2py       12
   29     O        3d1-      15
   30     O        3d1-      20
   31     H        1s        24  -  25
   32     H        1s        26  -  27
   33     H        1s        28  -  29
   34     H        2py       32  +  33
   35     H        2pz       34  -  35
   36     H        2py       38  +  39
   37     H        2pz       40  -  41


  Symmetry  A2 ( 4)

   38     O        3d2-      14
   39     O        3d2-      19
   40     H        2px       30  -  31
   41     H        2px       36  -  37

  Symmetries of electric field:  B1 (2)  B2 (3)  A1 (1)

  Symmetries of magnetic field:  B2 (3)  B1 (2)  A2 (4)


     ************************************************************************
     ************************** Output from HERINT **************************
     ************************************************************************


 Number of two-electron integrals written:       91307 ( 24.6% )
 Megabytes written:                              1.051



 MEMORY USED TO GENERATE CAVITY =    432042


 Total number of spheres =    3
 Sphere             Center  (X,Y,Z) (A)               Radius (A)      Area (A^2)
   1    0.000000000    0.000000000   -0.066597747    1.800000000   24.581233228
   2    0.000000000    0.768550518    0.528477314    1.440000000   11.987539425
   3    0.000000000   -0.768550518    0.528477314    1.440000000   11.987539425

 Total number of tesserae =     152
 Surface area =   48.55631208 (A^2)    Cavity volume =   30.53397368 (A^3)

          THE SOLUTE IS ENCLOSED IN ONE CAVITY

 ..... DONE GENERATION CAVITY .....

 >>> Time used in PEDRAM is   0.10 seconds


  ..... DONE GENERATING -Q-  MATRIX .....
 >>>> Total CPU  time used in HERMIT:   0.12 seconds
 >>>> Total wall time used in HERMIT:   0.00 seconds

- End of Integral Section


Starting in Wave Function Section -


 *** Output from Huckel module :

     Using EWMO model:          F
     Using EHT  model:          T
     Number of Huckel orbitals each symmetry:    4    1    2    0

 Huckel EHT eigenvalues for symmetry :  1
          -20.808625      -2.112474      -0.679872       0.264008

 Huckel EHT eigenvalues for symmetry :  2
           -0.616200

 Huckel EHT eigenvalues for symmetry :  3
           -0.926303       0.099566

 **********************************************************************
 *SIRIUS* a direct, restricted step, second order MCSCF program       *
 **********************************************************************

 
     Date and time (Linux)  : Tue Nov 13 16:07:55 2007
     Host name              : platina                                 

 Title lines from integral program:
     magnet                                                                  
     nuova base                                                              

 Print level on unit LUPRI =   2 is   0
 Print level on unit LUW4  =   2 is   5

     Restricted, closed shell Kohn-Sham calculation.


     Time-dependent Kohn-Sham calculation (random phase approximation).


 Initial molecular orbitals are obtained according to
 ".MOSTART HUCKEL" input option.

     Wave function specification
     ============================
     Number of closed shell electrons         10
     Number of electrons in active shells      0
     Total charge of the molecule              0

     Number of active orbitals                 0
     Total number of orbitals                 41

     Spin multiplicity                         1
     Total number of symmetries                4
     Reference state symmetry                  1
 
     This is a DFT calculation of type: B3LYP
 Weighted mixed functional:
               HF exchange:    0.20000
                       VWN:    0.19000
                       LYP:    0.81000
                     Becke:    0.72000
                    Slater:    0.80000

     Orbital specifications
     ======================
     Abelian symmetry species           1   2   3   4
                                       --  --  --  --
     Total number of orbitals          18   7  12   4
     Number of basis functions         18   7  12   4

      ** Automatic occupation of RKS orbitals **
      -- Initial occupation of symmetries is determined from Huckel guess.                    
      -- Initial occupation of symmetries is : --

     Occupied SCF orbitals              3   1   1   0

     Maximum number of Fock   iterations      0
     Maximum number of DIIS   iterations     60
     Maximum number of QC-SCF iterations     60
     Threshold for SCF convergence     1.00e-06

          -------------------------------------
          ---- POLARISABLE CONTINUUM MODEL ----
          ----      UNIVERSITY OF PISA     ----
          -------------------------------------

 ESTIMATE OF NUCLEAR CHARGE        9.97104
 NUCLEAR APPARENT CHARGE  -9.59233
 THEORETICAL  -9.59267 NOT RENORMALIZED

 ..... DONE WITH INDUCED NUCLEAR CHARGES .....


 >>>>> DIIS optimization of Hartree-Fock <<<<<

 C1-DIIS algorithm; max error vectors =   10

 Automatic occupation of symmetries with  10 electrons.

 Iter     Total energy      Solvation energy  Error norm  Delta(E)    HF occupation
 ----------------------------------------------------------------------------------
 Radial Quadrature : LMG scheme
 Space partitioning: Original Becke partitioning
 Radial integration threshold: 1e-13
 Angular polynomials in range [15 35]
 Atom:    1*1 points=24126 compressed from 24126 (123 radial)
 Atom:    2*2 points=23198 compressed from 23238 ( 93 radial)
 Number of grid points:    47324 Grid generation time:       0.1 s
K-S electrons/energy :    9.99999963893958   -7.40267055255520 err:-.36e-06
   1  -76.0960993972     -1.000176258944e-02   3.47e+00  -7.61e+01    3  1  1  0
K-S electrons/energy :    9.99999967099838   -7.61229073815260 err:-.33e-06
   2  -76.3856340019     -8.037525120852e-03   8.09e-01  -2.90e-01    3  1  1  0
K-S electrons/energy :    9.99999967941060   -7.35507633275827 err:-.32e-06
   3  -76.3868224195     -6.961402581735e-03   7.94e-01  -1.19e-03    3  1  1  0
K-S electrons/energy :    9.99999967108957   -7.52243666474056 err:-.33e-06
   4  -76.4140555966     -9.834812675805e-03   1.67e-01  -2.72e-02    3  1  1  0
K-S electrons/energy :    9.99999967340935   -7.49475472362035 err:-.33e-06
   5  -76.4153542587     -8.895700470860e-03   8.31e-03  -1.30e-03    3  1  1  0
K-S electrons/energy :    9.99999967334500   -7.49578246707999 err:-.33e-06
   6  -76.4153573807     -8.935104995778e-03   7.31e-04  -3.12e-06    3  1  1  0
K-S electrons/energy :    9.99999967333832   -7.49592125334558 err:-.33e-06
   7  -76.4153574080     -8.936982209824e-03   3.85e-05  -2.73e-08    3  1  1  0
K-S electrons/energy :    9.99999967333863   -7.49591458368820 err:-.33e-06
   8  -76.4153574081     -8.936834411649e-03   1.75e-06  -1.06e-10    3  1  1  0
K-S electrons/energy :    9.99999967333863   -7.49591445093094 err:-.33e-06
   9  -76.4153574081     -8.936814278839e-03   1.59e-07  -2.35e-12    3  1  1  0
 DIIS converged in   9 iterations !


 *** SCF orbital energy analysis ***
    (incl. solvent contribution)

 Only the five lowest virtual orbital energies printed in each symmetry.

 Number of electrons :   10
 Orbital occupations :    3    1    1    0

 Sym       Kohn-Sham orbital energies

  1    -19.15770739    -1.01435582    -0.39866830    -0.01408857     0.10168960
         0.12975013     0.22734410     0.29590864

  2     -0.32191472     0.11216629     0.32696197     0.89445356     1.18997716
         1.84727002

  3     -0.52976372     0.03359655     0.16210902     0.17626516     0.45234852
         0.53245658

  4      0.28746054     0.95198394     1.75179832     3.31154185

    E(LUMO) :    -0.01408857 au (symmetry 1)
  - E(HOMO) :    -0.32191472 au (symmetry 2)
  ------------------------------------------
    gap     :     0.30782615 au

 >>> Writing SIRIFC interface file <<<


                    >>> FINAL RESULTS FROM SIRIUS <<<

     Spin multiplicity:           1
     Spatial symmetry:            1
     Total charge of molecule:    0

     SOLVATION MODEL: polarizable continuum model (PCM),
          dielectric constant =   24.550000

     Final DFT energy:            -76.415357408100
     Nuclear repulsion:             9.055004525638
     Electronic energy:           -85.461425119459

     Final gradient norm:           0.000000158934

 
     Date and time (Linux)  : Tue Nov 13 16:08:08 2007
     Host name              : platina                                 

     Molecular orbitals for symmetry species   1

 Orbital           1        2        3        4        5        6        7
   1 O   :1s     1.0039  -0.0038   0.0030  -0.0051  -0.0211  -0.0263   0.0153
   2 O   :1s     0.0196   0.8880  -0.3045  -0.2480  -0.1142  -0.4010   0.0275
   3 O   :1s    -0.0259  -0.1459  -0.1428  -0.1635   0.2592   0.0856  -0.2787
   4 O   :1s    -0.0101   0.0662  -0.1249  -0.5856   2.5842   2.8841  -5.1743
   5 O   :2pz    0.0024   0.1543   0.8088  -0.1633  -0.3669  -0.0882  -0.1706
   6 O   :2pz   -0.0041  -0.0863  -0.0713  -0.0312   0.0597   0.1777  -0.2268
   7 O   :2pz   -0.0016   0.0136   0.0562  -0.1547   1.6590  -0.3134  -0.9895
   8 O   :3d0    0.0000   0.0034   0.0143  -0.0024  -0.0127   0.0040  -0.0189
   9 O   :3d2+  -0.0003  -0.0075  -0.0025  -0.0010  -0.0011  -0.0045  -0.0232
  10 O   :3d0    0.0001  -0.0060   0.0105  -0.0031   0.0360  -0.0220   0.0433
  11 O   :3d2+   0.0007   0.0198   0.0149  -0.0039  -0.0294  -0.0409   0.0463
  12 H   :1s     0.0014   0.3561   0.3556   0.1015   0.0414   0.1795   0.2854
  13 H   :1s     0.0075  -0.2059  -0.1080   0.2451  -1.0633  -0.5017   2.5005
  14 H   :1s     0.0007  -0.0022   0.0076   0.5880  -0.5215  -0.8555   0.3987
  15 H   :2py    0.0004  -0.0362  -0.0262   0.0164   0.0312   0.0259  -0.0035
  16 H   :2pz    0.0004  -0.0209   0.0036   0.0093   0.0220   0.0125  -0.0292
  17 H   :2py   -0.0027   0.0041  -0.0034  -0.0028   0.2239   0.3528   0.2182
  18 H   :2pz   -0.0024   0.0069   0.0138   0.0031   0.0424   0.3642  -0.4154

 Orbital           8
   1 O   :1s     0.0027
   2 O   :1s    -0.0169
   3 O   :1s    -0.0526
   4 O   :1s     3.7689
   5 O   :2pz    0.3064
   6 O   :2pz    0.4950
   7 O   :2pz    1.7842
   8 O   :3d0   -0.0201
   9 O   :3d2+  -0.0091
  10 O   :3d0    0.0570
  11 O   :3d2+   0.0433
  12 H   :1s    -0.1345
  13 H   :1s    -1.8763
  14 H   :1s    -0.2776
  15 H   :2py    0.0364
  16 H   :2pz   -0.0111
  17 H   :2py    0.3978
  18 H   :2pz   -0.7071

     Molecular orbitals for symmetry species   2

 Orbital           1        2        3        4        5        6
   1 O   :2px    0.9200   0.3478   0.2547   0.4009  -1.3718  -0.0102
   2 O   :2px   -0.0003   0.0854   0.4494  -0.2818   2.2500   0.7666
   3 O   :2px    0.1036  -1.3570   1.1962   0.7867   0.1804  -0.1864
   4 O   :3d1+   0.0137   0.0142  -0.0202  -0.0079   0.0074  -0.0639
   5 O   :3d1+   0.0140  -0.0386   0.0186   1.0809   0.4711   0.6826
   6 H   :2px    0.0261  -0.0079  -0.0104   0.0163   0.0077  -0.9837
   7 H   :2px    0.0211   0.2204  -1.1551  -0.5751  -0.6413   0.1015

     Molecular orbitals for symmetry species   3

 Orbital           1        2        3        4        5        6
   1 O   :2py    0.7556  -0.2137  -0.4423  -0.2871   0.1884   0.5012
   2 O   :2py   -0.1959  -0.0672   0.2408  -0.1859   0.2110   1.1617
   3 O   :2py    0.0153  -0.4875   2.4030  -1.8182   2.3100   1.8733
   4 O   :3d1-   0.0249  -0.0010  -0.0005   0.0211   0.0187   0.0027
   5 O   :3d1-  -0.0461  -0.0042   0.0758  -0.0247  -0.0216  -0.0217
   6 H   :1s     0.6088   0.0232   0.0455   0.3756   0.0238  -0.4116
   7 H   :1s    -0.1713   0.4128  -1.5287   1.4368   0.2308  -6.6947
   8 H   :1s     0.0018   2.4695  -2.8936   0.5781  -1.0153  -1.3952
   9 H   :2py   -0.0214   0.0084   0.0391  -0.0134   0.0090  -0.0041
  10 H   :2pz   -0.0322   0.0094   0.0277   0.0081  -0.0037   0.0065
  11 H   :2py   -0.0232  -0.0485   0.4593   0.1814  -1.7886   3.1213
  12 H   :2pz   -0.0159  -0.0661   0.4761   0.1982   1.2465   1.4527

     Molecular orbitals for symmetry species   4

 Orbital           1        2        3        4
   1 O   :3d2-  -0.0339   0.0015  -0.0751   1.2046
   2 O   :3d2-   0.0636  -1.2230   0.8532  -0.7133
   3 H   :2px   -0.0123  -0.0394  -0.9406  -0.1224
   4 H   :2px   -1.0827   0.7806   0.1039   0.3307



 >>>> Total CPU  time used in SIRIUS :     12.71 seconds
 >>>> Total wall time used in SIRIUS :     13.00 seconds

 
     Date and time (Linux)  : Tue Nov 13 16:08:08 2007
     Host name              : platina                                 

- End of Wave Function Section



  This is output from RESPONSE  -  an MCSCF and SOPPA response property program
 ------------------------------------------------------------------------------



 <<<<<<<<<< OUTPUT FROM RESPONSE INPUT PROCESSING >>>>>>>>>>




 Quadratic Response single residue calculation
 ---------------------------------------------


 Spin of operator A , ISPINA=    0
 Spin of operator B , ISPINB=    0
 Spin of operator C , (Excitation energy) ISPINC=    0

  1 B-frequencies  0.000000e+00
 B of Magnetic Circular Dichroism requested    : MCDCAL =T

 Print level                                    : IPRSMO =    2
 Threshold for convergence in RSPPP             : THCPP  = 1.000e-03
 Maximum number of iterations in RSPPP          : MAXITP =   60
 Threshold for convergence in RSPLR             : THCLR  = 1.000e-03
 Maximum number of iterations in RSPLR          : MAXITL =   60
 Maximum iterations in optimal orbital algorithm: MAXITO =    5

    1 A OPERATORS OF SYMMETRY NO:    1 AND LABELS:

          ZDIPLEN 

    1 A OPERATORS OF SYMMETRY NO:    2 AND LABELS:

          XDIPLEN 

    1 A OPERATORS OF SYMMETRY NO:    3 AND LABELS:

          YDIPLEN 

    1 B OPERATORS OF SYMMETRY NO:    2 AND LABELS:

          YANGMOM 

    1 B OPERATORS OF SYMMETRY NO:    3 AND LABELS:

          XANGMOM 

    1 B OPERATORS OF SYMMETRY NO:    4 AND LABELS:

          ZANGMOM 


   SCF energy         :      -76.415357408100363
 -- inactive part     :      -85.461425119459420
 -- nuclear repulsion :        9.055004525637894


 Linear response excitations for quadratic response
 - symmetry of excitation operator    1
 - is the operator a triplet operator ?     F


 Perturbation symmetry.     KSYMOP:       1
 Perturbation spin symmetry.TRPLET:       F
 Orbital variables.         KZWOPT:      62
 Configuration variables.   KZCONF:       0
 Total number of variables. KZVAR :      62



 <<< EXCITATION ENERGIES AND TRANSITION MOMENT CALCULATION (MCTDHF) >>>

 Operator symmetry =  1; triplet =   F

 Electrons: 10.000000(-3.27e-07): LR-DFT*4 evaluation time:       3.1 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*4 evaluation time:       3.1 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*4 evaluation time:       3.1 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*3 evaluation time:       2.5 s

 *** THE REQUESTED    4 SOLUTION VECTORS CONVERGED

 Convergence of RSP solution vectors, threshold = 1.00e-03
 ---------------------------------------------------------------
 (dimension of paired reduced space:   30)
 RSP solution vector no.    1; norm of residual   2.56e-04
 RSP solution vector no.    2; norm of residual   3.94e-04
 RSP solution vector no.    3; norm of residual   4.10e-04
 RSP solution vector no.    4; norm of residual   1.87e-04

 *** RSPCTL MICROITERATIONS CONVERGED


 Linear response excitations for quadratic response
 - symmetry of excitation operator    2
 - is the operator a triplet operator ?     F


 Perturbation symmetry.     KSYMOP:       2
 Perturbation spin symmetry.TRPLET:       F
 Orbital variables.         KZWOPT:      37
 Configuration variables.   KZCONF:       0
 Total number of variables. KZVAR :      37



 <<< EXCITATION ENERGIES AND TRANSITION MOMENT CALCULATION (MCTDHF) >>>

 Operator symmetry =  2; triplet =   F

 Electrons: 10.000000(-3.27e-07): LR-DFT*4 evaluation time:       3.0 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*4 evaluation time:       3.0 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*4 evaluation time:       3.0 s

 *** THE REQUESTED    4 SOLUTION VECTORS CONVERGED

 Convergence of RSP solution vectors, threshold = 1.00e-03
 ---------------------------------------------------------------
 (dimension of paired reduced space:   24)
 RSP solution vector no.    1; norm of residual   1.21e-04
 RSP solution vector no.    2; norm of residual   3.61e-04
 RSP solution vector no.    3; norm of residual   6.31e-04
 RSP solution vector no.    4; norm of residual   7.95e-04

 *** RSPCTL MICROITERATIONS CONVERGED


 Linear response excitations for quadratic response
 - symmetry of excitation operator    3
 - is the operator a triplet operator ?     F


 Perturbation symmetry.     KSYMOP:       3
 Perturbation spin symmetry.TRPLET:       F
 Orbital variables.         KZWOPT:      52
 Configuration variables.   KZCONF:       0
 Total number of variables. KZVAR :      52



 <<< EXCITATION ENERGIES AND TRANSITION MOMENT CALCULATION (MCTDHF) >>>

 Operator symmetry =  3; triplet =   F

 Electrons: 10.000000(-3.27e-07): LR-DFT*4 evaluation time:       3.0 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*4 evaluation time:       3.1 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*4 evaluation time:       3.0 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*3 evaluation time:       2.5 s

 *** THE REQUESTED    4 SOLUTION VECTORS CONVERGED

 Convergence of RSP solution vectors, threshold = 1.00e-03
 ---------------------------------------------------------------
 (dimension of paired reduced space:   30)
 RSP solution vector no.    1; norm of residual   9.34e-05
 RSP solution vector no.    2; norm of residual   5.75e-05
 RSP solution vector no.    3; norm of residual   9.52e-05
 RSP solution vector no.    4; norm of residual   1.98e-04

 *** RSPCTL MICROITERATIONS CONVERGED


 Linear response excitations for quadratic response
 - symmetry of excitation operator    4
 - is the operator a triplet operator ?     F


 Perturbation symmetry.     KSYMOP:       4
 Perturbation spin symmetry.TRPLET:       F
 Orbital variables.         KZWOPT:      29
 Configuration variables.   KZCONF:       0
 Total number of variables. KZVAR :      29



 <<< EXCITATION ENERGIES AND TRANSITION MOMENT CALCULATION (MCTDHF) >>>

 Operator symmetry =  4; triplet =   F

 Electrons: 10.000000(-3.27e-07): LR-DFT*4 evaluation time:       2.9 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*4 evaluation time:       2.9 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*4 evaluation time:       2.9 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*1 evaluation time:       1.2 s

 *** THE REQUESTED    4 SOLUTION VECTORS CONVERGED

 Convergence of RSP solution vectors, threshold = 1.00e-03
 ---------------------------------------------------------------
 (dimension of paired reduced space:   26)
 RSP solution vector no.    1; norm of residual   1.89e-05
 RSP solution vector no.    2; norm of residual   3.28e-05
 RSP solution vector no.    3; norm of residual   4.14e-05
 RSP solution vector no.    4; norm of residual   1.08e-04

 *** RSPCTL MICROITERATIONS CONVERGED


 Linear response calculations for quadratic response
 - singlet property operator of symmetry    1


 Perturbation symmetry.     KSYMOP:       1
 Perturbation spin symmetry.TRPLET:       F
 Orbital variables.         KZWOPT:      62
 Configuration variables.   KZCONF:       0
 Total number of variables. KZVAR :      62


 QRLRVE -- linear response calculation for symmetry  1
 QRLRVE -- operator label : ZDIPLEN 
 QRLRVE -- frequencies :  0.260094  0.371728  0.408196  0.458800  0.394814
                          0.468683  0.512613  0.522952  0.316502  0.427812
                          0.443797  0.591276



 <<<  SOLVING SETS OF LINEAR EQUATIONS FOR LINEAR RESPONSE PROPERTIES >>>

 Operator symmetry =  1; triplet =   F

 Electrons: 10.000000(-3.27e-07): LR-DFT*12 evaluation time:       9.2 s

 GP * SOLUTION VECTOR AT FREQUENCY     0.37173 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     -3.53553793
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   23    0    1
 DETERMINANT OF REDUCED MATRIX IS -6.11 * 10 ** -1.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   23    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.40820 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS      5.11860564
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   22    0    2
 DETERMINANT OF REDUCED MATRIX IS  7.11 * 10 ** -2.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   22    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.45880 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     18.43474545
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   22    0    2
 DETERMINANT OF REDUCED MATRIX IS  3.00 * 10 ** -2.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   22    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.39481 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS      4.50455525
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   23    0    1
 DETERMINANT OF REDUCED MATRIX IS -1.05 * 10 ** -1.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   23    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.46868 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     27.66421221
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   22    0    2
 DETERMINANT OF REDUCED MATRIX IS  7.98 * 10 ** -3.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   22    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.51261 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS      2.45732141
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   20    0    4
 DETERMINANT OF REDUCED MATRIX IS  1.73 * 10 ** -2.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   20    0    4

 GP * SOLUTION VECTOR AT FREQUENCY     0.52295 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS      6.62658113
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   20    0    4
 DETERMINANT OF REDUCED MATRIX IS  1.52 * 10 ** -2.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   20    0    4

 GP * SOLUTION VECTOR AT FREQUENCY     0.42781 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS      9.27846260
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   22    0    2
 DETERMINANT OF REDUCED MATRIX IS  1.32 * 10 ** -1.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   22    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.44380 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     12.77956200
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   22    0    2
 DETERMINANT OF REDUCED MATRIX IS  8.38 * 10 ** -2.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   22    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.59128 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     -9.17992202
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   18    0    6
 DETERMINANT OF REDUCED MATRIX IS  1.68 * 10 ** -2.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   18    0    6
 Electrons: 10.000000(-3.27e-07): LR-DFT*12 evaluation time:       9.2 s

 GP * SOLUTION VECTOR AT FREQUENCY     0.37173 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     -3.14693934
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   47    0    1
 DETERMINANT OF REDUCED MATRIX IS -1.79 * 10 **  9.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   47    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.40820 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS      6.04561014
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   46    0    2
 DETERMINANT OF REDUCED MATRIX IS  2.72 * 10 **  8.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   46    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.45880 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     19.26482577
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   46    0    2
 DETERMINANT OF REDUCED MATRIX IS  2.43 * 10 **  7.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   46    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.39481 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS      5.79831081
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   47    0    1
 DETERMINANT OF REDUCED MATRIX IS -1.00 * 10 **  8.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   47    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.46868 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS   -201.21179309
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   45    0    3
 DETERMINANT OF REDUCED MATRIX IS -1.40 * 10 **  5.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   45    0    3

 GP * SOLUTION VECTOR AT FREQUENCY     0.51261 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS      5.73792866
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   44    0    4
 DETERMINANT OF REDUCED MATRIX IS  1.37 * 10 **  7.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   44    0    4

 GP * SOLUTION VECTOR AT FREQUENCY     0.52295 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS      9.47745212
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   44    0    4
 DETERMINANT OF REDUCED MATRIX IS  8.50 * 10 **  6.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   44    0    4

 GP * SOLUTION VECTOR AT FREQUENCY     0.42781 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS      9.69216460
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   46    0    2
 DETERMINANT OF REDUCED MATRIX IS  2.68 * 10 **  8.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   46    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.44380 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     13.11925677
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   46    0    2
 DETERMINANT OF REDUCED MATRIX IS  1.19 * 10 **  8.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   46    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.59128 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     14.81235715
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   42    0    6
 DETERMINANT OF REDUCED MATRIX IS  9.89 * 10 **  5.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   42    0    6
 Electrons: 10.000000(-3.27e-07): LR-DFT*12 evaluation time:       9.2 s

 GP * SOLUTION VECTOR AT FREQUENCY     0.37173 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS     -3.14664310
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   71    0    1
 DETERMINANT OF REDUCED MATRIX IS -1.56 * 10 ** 23.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   71    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.40820 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS      6.04688679
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   70    0    2
 DETERMINANT OF REDUCED MATRIX IS  2.03 * 10 ** 22.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   70    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.45880 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS     19.26600165
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   70    0    2
 DETERMINANT OF REDUCED MATRIX IS  1.42 * 10 ** 21.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   70    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.39481 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS      5.80595008
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   71    0    1
 DETERMINANT OF REDUCED MATRIX IS -7.89 * 10 ** 21.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   71    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.46868 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS   -170.34974750
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   69    0    3
 DETERMINANT OF REDUCED MATRIX IS -9.05 * 10 ** 18.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   69    0    3

 GP * SOLUTION VECTOR AT FREQUENCY     0.51261 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS      5.74187695
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   68    0    4
 DETERMINANT OF REDUCED MATRIX IS  5.98 * 10 ** 20.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   68    0    4

 GP * SOLUTION VECTOR AT FREQUENCY     0.52295 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS      9.48144575
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   68    0    4
 DETERMINANT OF REDUCED MATRIX IS  3.47 * 10 ** 20.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   68    0    4

 GP * SOLUTION VECTOR AT FREQUENCY     0.42781 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS      9.69269697
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   70    0    2
 DETERMINANT OF REDUCED MATRIX IS  1.83 * 10 ** 22.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   70    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.44380 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS     13.11953844
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   70    0    2
 DETERMINANT OF REDUCED MATRIX IS  7.56 * 10 ** 21.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   70    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.59128 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS     15.07398666
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   66    0    6
 DETERMINANT OF REDUCED MATRIX IS  2.45 * 10 ** 19.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   66    0    6

 *** THE REQUESTED   12 SOLUTION VECTORS CONVERGED

 Convergence of RSP solution vectors, threshold = 1.00e-03
 ---------------------------------------------------------------
 (dimension of paired reduced space:   72)
 RSP solution vector no.    1; norm of residual   2.53e-04
 RSP solution vector no.    2; norm of residual   3.54e-05
 RSP solution vector no.    3; norm of residual   1.87e-04
 RSP solution vector no.    4; norm of residual   6.19e-05
 RSP solution vector no.    5; norm of residual   1.54e-04
 RSP solution vector no.    6; norm of residual   2.86e-04
 RSP solution vector no.    7; norm of residual   2.22e-04
 RSP solution vector no.    8; norm of residual   2.47e-04
 RSP solution vector no.    9; norm of residual   1.33e-04
 RSP solution vector no.   10; norm of residual   1.41e-04
 RSP solution vector no.   11; norm of residual   8.76e-05
 RSP solution vector no.   12; norm of residual   3.80e-04

 *** RSPCTL MICROITERATIONS CONVERGED

 QRLRVE: SINGLET SOLUTION   LABEL   ZDIPLEN     FREQUENCY   0.260094e+00
 SYMMETRY    1

@QRLRVE:  << ZDIPLEN  ; ZDIPLEN  >> (   0.26009):     17.0603628722    

 QRLRVE: SINGLET SOLUTION   LABEL   ZDIPLEN     FREQUENCY   0.371728e+00
 SYMMETRY    1

@QRLRVE:  << ZDIPLEN  ; ZDIPLEN  >> (   0.37173):    -3.14664310391    

 QRLRVE: SINGLET SOLUTION   LABEL   ZDIPLEN     FREQUENCY   0.408196e+00
 SYMMETRY    1

@QRLRVE:  << ZDIPLEN  ; ZDIPLEN  >> (   0.40820):     6.04688678680    

 QRLRVE: SINGLET SOLUTION   LABEL   ZDIPLEN     FREQUENCY   0.458800e+00
 SYMMETRY    1

@QRLRVE:  << ZDIPLEN  ; ZDIPLEN  >> (   0.45880):     19.2660016471    

 QRLRVE: SINGLET SOLUTION   LABEL   ZDIPLEN     FREQUENCY   0.394814e+00
 SYMMETRY    1

@QRLRVE:  << ZDIPLEN  ; ZDIPLEN  >> (   0.39481):     5.80595007958    

 QRLRVE: SINGLET SOLUTION   LABEL   ZDIPLEN     FREQUENCY   0.468683e+00
 SYMMETRY    1

@QRLRVE:  << ZDIPLEN  ; ZDIPLEN  >> (   0.46868):    -170.349747504    

 QRLRVE: SINGLET SOLUTION   LABEL   ZDIPLEN     FREQUENCY   0.512613e+00
 SYMMETRY    1

@QRLRVE:  << ZDIPLEN  ; ZDIPLEN  >> (   0.51261):     5.74187694748    

 QRLRVE: SINGLET SOLUTION   LABEL   ZDIPLEN     FREQUENCY   0.522952e+00
 SYMMETRY    1

@QRLRVE:  << ZDIPLEN  ; ZDIPLEN  >> (   0.52295):     9.48144575349    

 QRLRVE: SINGLET SOLUTION   LABEL   ZDIPLEN     FREQUENCY   0.316502e+00
 SYMMETRY    1

@QRLRVE:  << ZDIPLEN  ; ZDIPLEN  >> (   0.31650):     37.5548916798    

 QRLRVE: SINGLET SOLUTION   LABEL   ZDIPLEN     FREQUENCY   0.427812e+00
 SYMMETRY    1

@QRLRVE:  << ZDIPLEN  ; ZDIPLEN  >> (   0.42781):     9.69269696855    

 QRLRVE: SINGLET SOLUTION   LABEL   ZDIPLEN     FREQUENCY   0.443797e+00
 SYMMETRY    1

@QRLRVE:  << ZDIPLEN  ; ZDIPLEN  >> (   0.44380):     13.1195384440    

 QRLRVE: SINGLET SOLUTION   LABEL   ZDIPLEN     FREQUENCY   0.591276e+00
 SYMMETRY    1

@QRLRVE:  << ZDIPLEN  ; ZDIPLEN  >> (   0.59128):     15.0739866574    


 Linear response calculations for quadratic response
 - singlet property operator of symmetry    2


 Perturbation symmetry.     KSYMOP:       2
 Perturbation spin symmetry.TRPLET:       F
 Orbital variables.         KZWOPT:      37
 Configuration variables.   KZCONF:       0
 Total number of variables. KZVAR :      37


 QRLRVE -- linear response calculation for symmetry  2
 QRLRVE -- operator label : XDIPLEN 
 QRLRVE -- frequencies :  0.397228  0.468548  0.483278  0.394814  0.468683
                          0.512613  0.522952  0.316502  0.427812  0.443797
                          0.591276  0.336845



 <<<  SOLVING SETS OF LINEAR EQUATIONS FOR LINEAR RESPONSE PROPERTIES >>>

 Operator symmetry =  2; triplet =   F

 Electrons: 10.000000(-3.27e-07): LR-DFT*12 evaluation time:       8.8 s

 GP * SOLUTION VECTOR AT FREQUENCY     0.39723 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     12.18015258
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   22    0    2
 DETERMINANT OF REDUCED MATRIX IS  1.68 * 10 ** -1.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   22    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.46855 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     22.87364733
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   20    0    4
 DETERMINANT OF REDUCED MATRIX IS  8.97 * 10 ** -2.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   20    0    4

 GP * SOLUTION VECTOR AT FREQUENCY     0.48328 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     60.08605353
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   20    0    4
 DETERMINANT OF REDUCED MATRIX IS  9.34 * 10 ** -2.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   20    0    4

 GP * SOLUTION VECTOR AT FREQUENCY     0.39481 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     11.62900063
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   22    0    2
 DETERMINANT OF REDUCED MATRIX IS  1.94 * 10 ** -1.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   22    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.46868 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     23.02762231
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   20    0    4
 DETERMINANT OF REDUCED MATRIX IS  9.06 * 10 ** -2.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   20    0    4

 GP * SOLUTION VECTOR AT FREQUENCY     0.51261 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     -5.36452315
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   19    0    5
 DETERMINANT OF REDUCED MATRIX IS -6.38 * 10 ** -1.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   19    0    5

 GP * SOLUTION VECTOR AT FREQUENCY     0.52295 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS      2.32026457
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   19    0    5
 DETERMINANT OF REDUCED MATRIX IS -9.82 * 10 ** -1.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   19    0    5

 GP * SOLUTION VECTOR AT FREQUENCY     0.31650 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS      2.91354992
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   23    0    1
 DETERMINANT OF REDUCED MATRIX IS -6.84 * 10 **  0.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   23    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.42781 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     12.60474411
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   21    0    3
 DETERMINANT OF REDUCED MATRIX IS -2.02 * 10 ** -1.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   21    0    3

 GP * SOLUTION VECTOR AT FREQUENCY     0.44380 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     16.72698042
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   21    0    3
 DETERMINANT OF REDUCED MATRIX IS -1.64 * 10 ** -1.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   21    0    3

 GP * SOLUTION VECTOR AT FREQUENCY     0.59128 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     -0.92803051
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   18    0    6
 DETERMINANT OF REDUCED MATRIX IS  9.13 * 10 **  0.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   18    0    6

 GP * SOLUTION VECTOR AT FREQUENCY     0.33685 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS      5.50725112
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   23    0    1
 DETERMINANT OF REDUCED MATRIX IS -3.38 * 10 **  0.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   23    0    1
 Electrons: 10.000000(-3.27e-07): LR-DFT*12 evaluation time:       8.8 s

 GP * SOLUTION VECTOR AT FREQUENCY     0.39723 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     12.26267363
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   46    0    2
 DETERMINANT OF REDUCED MATRIX IS  8.78 * 10 ** 11.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   46    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.46855 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     24.03924790
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   44    0    4
 DETERMINANT OF REDUCED MATRIX IS  3.47 * 10 ** 11.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   44    0    4

 GP * SOLUTION VECTOR AT FREQUENCY     0.48328 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     64.79450313
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   44    0    4
 DETERMINANT OF REDUCED MATRIX IS  3.08 * 10 ** 11.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   44    0    4

 GP * SOLUTION VECTOR AT FREQUENCY     0.39481 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     11.71762353
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   46    0    2
 DETERMINANT OF REDUCED MATRIX IS  1.04 * 10 ** 12.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   46    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.46868 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     24.19537155
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   44    0    4
 DETERMINANT OF REDUCED MATRIX IS  3.50 * 10 ** 11.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   44    0    4

 GP * SOLUTION VECTOR AT FREQUENCY     0.51261 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     -5.14130110
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   43    0    5
 DETERMINANT OF REDUCED MATRIX IS -1.83 * 10 ** 12.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   43    0    5

 GP * SOLUTION VECTOR AT FREQUENCY     0.52295 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS      2.55928230
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   43    0    5
 DETERMINANT OF REDUCED MATRIX IS -2.59 * 10 ** 12.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   43    0    5

 GP * SOLUTION VECTOR AT FREQUENCY     0.31650 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS      3.12675724
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   47    0    1
 DETERMINANT OF REDUCED MATRIX IS -5.21 * 10 ** 13.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   47    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.42781 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     13.06893168
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   45    0    3
 DETERMINANT OF REDUCED MATRIX IS -9.72 * 10 ** 11.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   45    0    3

 GP * SOLUTION VECTOR AT FREQUENCY     0.44380 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     17.18477025
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   45    0    3
 DETERMINANT OF REDUCED MATRIX IS -7.00 * 10 ** 11.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   45    0    3

 GP * SOLUTION VECTOR AT FREQUENCY     0.59128 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     -0.73130708
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   42    0    6
 DETERMINANT OF REDUCED MATRIX IS  1.39 * 10 ** 13.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   42    0    6

 GP * SOLUTION VECTOR AT FREQUENCY     0.33685 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS      5.67950842
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   47    0    1
 DETERMINANT OF REDUCED MATRIX IS -2.36 * 10 ** 13.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   47    0    1
 Electrons: 10.000000(-3.27e-07): LR-DFT*5 evaluation time:       3.5 s

 GP * SOLUTION VECTOR AT FREQUENCY     0.39723 AU
 AFTER   29 LINEAR TRANSFORMATIONS IS     12.26267975
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   56    0    2
 DETERMINANT OF REDUCED MATRIX IS  1.37 * 10 ** 20.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   56    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.46855 AU
 AFTER   29 LINEAR TRANSFORMATIONS IS     24.03931826
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   54    0    4
 DETERMINANT OF REDUCED MATRIX IS  5.16 * 10 ** 19.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   54    0    4

 GP * SOLUTION VECTOR AT FREQUENCY     0.48328 AU
 AFTER   29 LINEAR TRANSFORMATIONS IS     64.79474577
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   54    0    4
 DETERMINANT OF REDUCED MATRIX IS  4.53 * 10 ** 19.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   54    0    4

 GP * SOLUTION VECTOR AT FREQUENCY     0.39481 AU
 AFTER   29 LINEAR TRANSFORMATIONS IS     11.71762819
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   56    0    2
 DETERMINANT OF REDUCED MATRIX IS  1.63 * 10 ** 20.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   56    0    2

 GP * SOLUTION VECTOR AT FREQUENCY     0.46868 AU
 AFTER   29 LINEAR TRANSFORMATIONS IS     24.19544103
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   54    0    4
 DETERMINANT OF REDUCED MATRIX IS  5.21 * 10 ** 19.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   54    0    4

 GP * SOLUTION VECTOR AT FREQUENCY     0.51261 AU
 AFTER   29 LINEAR TRANSFORMATIONS IS     -5.14124294
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   53    0    5
 DETERMINANT OF REDUCED MATRIX IS -2.64 * 10 ** 20.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   53    0    5

 GP * SOLUTION VECTOR AT FREQUENCY     0.52295 AU
 AFTER   29 LINEAR TRANSFORMATIONS IS      2.55932646
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   53    0    5
 DETERMINANT OF REDUCED MATRIX IS -3.69 * 10 ** 20.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   53    0    5

 GP * SOLUTION VECTOR AT FREQUENCY     0.31650 AU
 AFTER   29 LINEAR TRANSFORMATIONS IS      3.12676969
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   57    0    1
 DETERMINANT OF REDUCED MATRIX IS -8.48 * 10 ** 21.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   57    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.42781 AU
 AFTER   29 LINEAR TRANSFORMATIONS IS     13.06895316
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   55    0    3
 DETERMINANT OF REDUCED MATRIX IS -1.49 * 10 ** 20.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   55    0    3

 GP * SOLUTION VECTOR AT FREQUENCY     0.44380 AU
 AFTER   29 LINEAR TRANSFORMATIONS IS     17.18479753
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   55    0    3
 DETERMINANT OF REDUCED MATRIX IS -1.06 * 10 ** 20.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   55    0    3

 GP * SOLUTION VECTOR AT FREQUENCY     0.59128 AU
 AFTER   29 LINEAR TRANSFORMATIONS IS     -0.73121312
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   52    0    6
 DETERMINANT OF REDUCED MATRIX IS  1.86 * 10 ** 21.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   52    0    6

 GP * SOLUTION VECTOR AT FREQUENCY     0.33685 AU
 AFTER   29 LINEAR TRANSFORMATIONS IS      5.67951709
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   57    0    1
 DETERMINANT OF REDUCED MATRIX IS -3.81 * 10 ** 21.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   57    0    1

 *** THE REQUESTED   12 SOLUTION VECTORS CONVERGED

 Convergence of RSP solution vectors, threshold = 1.00e-03
 ---------------------------------------------------------------
 (dimension of paired reduced space:   58)
 RSP solution vector no.    1; norm of residual   2.51e-05
 RSP solution vector no.    2; norm of residual   1.03e-05
 RSP solution vector no.    3; norm of residual   1.08e-05
 RSP solution vector no.    4; norm of residual   2.64e-05
 RSP solution vector no.    5; norm of residual   1.03e-05
 RSP solution vector no.    6; norm of residual   2.19e-05
 RSP solution vector no.    7; norm of residual   3.19e-05
 RSP solution vector no.    8; norm of residual   5.74e-05
 RSP solution vector no.    9; norm of residual   1.21e-05
 RSP solution vector no.   10; norm of residual   1.31e-05
 RSP solution vector no.   11; norm of residual   1.15e-05
 RSP solution vector no.   12; norm of residual   4.96e-05

 *** RSPCTL MICROITERATIONS CONVERGED

 QRLRVE: SINGLET SOLUTION   LABEL   XDIPLEN     FREQUENCY   0.397228e+00
 SYMMETRY    2

@QRLRVE:  << XDIPLEN  ; XDIPLEN  >> (   0.39723):     12.2626797506    

@QRLRVE:  << YANGMOM  ; XDIPLEN  >> (   0.39723):    0.434462869711    

 QRLRVE: SINGLET SOLUTION   LABEL   XDIPLEN     FREQUENCY   0.468548e+00
 SYMMETRY    2

@QRLRVE:  << XDIPLEN  ; XDIPLEN  >> (   0.46855):     24.0393182626    

@QRLRVE:  << YANGMOM  ; XDIPLEN  >> (   0.46855):    -3.38537731016    

 QRLRVE: SINGLET SOLUTION   LABEL   XDIPLEN     FREQUENCY   0.483278e+00
 SYMMETRY    2

@QRLRVE:  << XDIPLEN  ; XDIPLEN  >> (   0.48328):     64.7947457659    

@QRLRVE:  << YANGMOM  ; XDIPLEN  >> (   0.48328):    -10.6058746942    

 QRLRVE: SINGLET SOLUTION   LABEL   XDIPLEN     FREQUENCY   0.394814e+00
 SYMMETRY    2

@QRLRVE:  << XDIPLEN  ; XDIPLEN  >> (   0.39481):     11.7176281909    

@QRLRVE:  << YANGMOM  ; XDIPLEN  >> (   0.39481):    0.212453389769    

 QRLRVE: SINGLET SOLUTION   LABEL   XDIPLEN     FREQUENCY   0.468683e+00
 SYMMETRY    2

@QRLRVE:  << XDIPLEN  ; XDIPLEN  >> (   0.46868):     24.1954410308    

@QRLRVE:  << YANGMOM  ; XDIPLEN  >> (   0.46868):    -3.40754255478    

 QRLRVE: SINGLET SOLUTION   LABEL   XDIPLEN     FREQUENCY   0.512613e+00
 SYMMETRY    2

@QRLRVE:  << XDIPLEN  ; XDIPLEN  >> (   0.51261):    -5.14124294128    

@QRLRVE:  << YANGMOM  ; XDIPLEN  >> (   0.51261):     3.26376318835    

 QRLRVE: SINGLET SOLUTION   LABEL   XDIPLEN     FREQUENCY   0.522952e+00
 SYMMETRY    2

@QRLRVE:  << XDIPLEN  ; XDIPLEN  >> (   0.52295):     2.55932645817    

@QRLRVE:  << YANGMOM  ; XDIPLEN  >> (   0.52295):     2.13930214844    

 QRLRVE: SINGLET SOLUTION   LABEL   XDIPLEN     FREQUENCY   0.316502e+00
 SYMMETRY    2

@QRLRVE:  << XDIPLEN  ; XDIPLEN  >> (   0.31650):     3.12676968655    

@QRLRVE:  << YANGMOM  ; XDIPLEN  >> (   0.31650):   -0.914041371998    

 QRLRVE: SINGLET SOLUTION   LABEL   XDIPLEN     FREQUENCY   0.427812e+00
 SYMMETRY    2

@QRLRVE:  << XDIPLEN  ; XDIPLEN  >> (   0.42781):     13.0689531611    

@QRLRVE:  << YANGMOM  ; XDIPLEN  >> (   0.42781):    -1.89613572374    

 QRLRVE: SINGLET SOLUTION   LABEL   XDIPLEN     FREQUENCY   0.443797e+00
 SYMMETRY    2

@QRLRVE:  << XDIPLEN  ; XDIPLEN  >> (   0.44380):     17.1847975315    

@QRLRVE:  << YANGMOM  ; XDIPLEN  >> (   0.44380):    -1.97372938107    

 QRLRVE: SINGLET SOLUTION   LABEL   XDIPLEN     FREQUENCY   0.591276e+00
 SYMMETRY    2

@QRLRVE:  << XDIPLEN  ; XDIPLEN  >> (   0.59128):   -0.731213117038    

@QRLRVE:  << YANGMOM  ; XDIPLEN  >> (   0.59128):     2.57407724507    

 QRLRVE: SINGLET SOLUTION   LABEL   XDIPLEN     FREQUENCY   0.336845e+00
 SYMMETRY    2

@QRLRVE:  << XDIPLEN  ; XDIPLEN  >> (   0.33685):     5.67951708591    

@QRLRVE:  << YANGMOM  ; XDIPLEN  >> (   0.33685):   -0.683357159067    


 QRLRVE -- linear response calculation for symmetry  2
 QRLRVE -- operator label : YANGMOM 
 QRLRVE -- frequencies :  0.000000



 <<<  SOLVING SETS OF LINEAR EQUATIONS FOR LINEAR RESPONSE PROPERTIES >>>

 Operator symmetry =  2; triplet =   F

 Electrons: 10.000000(-3.27e-07): LR-DFT*1 evaluation time:       1.2 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*1 evaluation time:       1.2 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*1 evaluation time:       1.2 s

 *** THE REQUESTED    1 SOLUTION VECTORS CONVERGED

 Convergence of RSP solution vectors, threshold = 1.00e-03
 ---------------------------------------------------------------
 (dimension of paired reduced space:    6)
 RSP solution vector no.    1; norm of residual   5.03e-04

 *** RSPCTL MICROITERATIONS CONVERGED

 QRLRVE: SINGLET SOLUTION   LABEL   YANGMOM     FREQUENCY   0.000000e+00
 SYMMETRY    2

@QRLRVE:  << XDIPLEN  ; YANGMOM  >> (   0.00000):   -3.842607316866e-17

@QRLRVE:  << YANGMOM  ; YANGMOM  >> (   0.00000):    0.563437649493    


 Linear response calculations for quadratic response
 - singlet property operator of symmetry    3


 Perturbation symmetry.     KSYMOP:       3
 Perturbation spin symmetry.TRPLET:       F
 Orbital variables.         KZWOPT:      52
 Configuration variables.   KZCONF:       0
 Total number of variables. KZVAR :      52


 QRLRVE -- linear response calculation for symmetry  3
 QRLRVE -- operator label : YDIPLEN 
 QRLRVE -- frequencies :  0.408196  0.458800  0.316502  0.427812  0.443797
                          0.591276  0.336845  0.397228  0.468548  0.483278
                          0.260094  0.371728



 <<<  SOLVING SETS OF LINEAR EQUATIONS FOR LINEAR RESPONSE PROPERTIES >>>

 Operator symmetry =  3; triplet =   F

 Electrons: 10.000000(-3.27e-07): LR-DFT*12 evaluation time:       9.1 s

 GP * SOLUTION VECTOR AT FREQUENCY     0.40820 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     21.75077855
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   23    0    1
 DETERMINANT OF REDUCED MATRIX IS -1.58 * 10 **  0.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   23    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.45880 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     76.17942445
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   23    0    1
 DETERMINANT OF REDUCED MATRIX IS -1.46 * 10 ** -1.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   23    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.42781 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     30.36266666
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   23    0    1
 DETERMINANT OF REDUCED MATRIX IS -1.31 * 10 **  0.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   23    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.44380 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     41.34564297
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   23    0    1
 DETERMINANT OF REDUCED MATRIX IS -5.98 * 10 ** -1.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   23    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.59128 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     -9.65628491
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   18    0    6
 DETERMINANT OF REDUCED MATRIX IS  2.50 * 10 ** -2.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   18    0    6

 GP * SOLUTION VECTOR AT FREQUENCY     0.39723 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS     -2.35080363
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   23    0    1
 DETERMINANT OF REDUCED MATRIX IS -4.29 * 10 ** -1.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   23    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.46855 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS   1001.51274376
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   23    0    1
 DETERMINANT OF REDUCED MATRIX IS -5.09 * 10 ** -3.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   23    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.48328 AU
 AFTER   12 LINEAR TRANSFORMATIONS IS    -10.81240034
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   22    0    2
 DETERMINANT OF REDUCED MATRIX IS  4.85 * 10 ** -2.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   22    0    2
 Electrons: 10.000000(-3.27e-07): LR-DFT*12 evaluation time:       9.2 s

 GP * SOLUTION VECTOR AT FREQUENCY     0.40820 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     22.31201534
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   47    0    1
 DETERMINANT OF REDUCED MATRIX IS -1.45 * 10 ** 10.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   47    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.45880 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     79.48809314
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   47    0    1
 DETERMINANT OF REDUCED MATRIX IS -7.96 * 10 **  8.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   47    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.42781 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     31.08837706
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   47    0    1
 DETERMINANT OF REDUCED MATRIX IS -1.00 * 10 ** 10.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   47    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.44380 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     42.44844832
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   47    0    1
 DETERMINANT OF REDUCED MATRIX IS -3.90 * 10 **  9.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   47    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.59128 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     -7.37000604
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   42    0    6
 DETERMINANT OF REDUCED MATRIX IS  3.80 * 10 **  7.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   42    0    6

 GP * SOLUTION VECTOR AT FREQUENCY     0.39723 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS      0.71269960
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   47    0    1
 DETERMINANT OF REDUCED MATRIX IS -4.75 * 10 **  9.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   47    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.46855 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS   4167.77184955
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   47    0    1
 DETERMINANT OF REDUCED MATRIX IS -6.19 * 10 **  6.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   47    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.48328 AU
 AFTER   24 LINEAR TRANSFORMATIONS IS     -8.02540821
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   46    0    2
 DETERMINANT OF REDUCED MATRIX IS  2.17 * 10 **  8.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   46    0    2
 Electrons: 10.000000(-3.27e-07): LR-DFT*12 evaluation time:       9.1 s

 GP * SOLUTION VECTOR AT FREQUENCY     0.40820 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS     22.31247482
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   71    0    1
 DETERMINANT OF REDUCED MATRIX IS -1.04 * 10 ** 26.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   71    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.45880 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS     79.49019664
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   71    0    1
 DETERMINANT OF REDUCED MATRIX IS -4.67 * 10 ** 24.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   71    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.42781 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS     31.08884087
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   71    0    1
 DETERMINANT OF REDUCED MATRIX IS -6.67 * 10 ** 25.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   71    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.44380 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS     42.44911012
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   71    0    1
 DETERMINANT OF REDUCED MATRIX IS -2.44 * 10 ** 25.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   71    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.59128 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS     -7.36815645
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   66    0    6
 DETERMINANT OF REDUCED MATRIX IS  1.10 * 10 ** 23.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   66    0    6

 GP * SOLUTION VECTOR AT FREQUENCY     0.39723 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS      0.71547196
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   71    0    1
 DETERMINANT OF REDUCED MATRIX IS -3.54 * 10 ** 25.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   71    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.46855 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS   4177.55987306
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   71    0    1
 DETERMINANT OF REDUCED MATRIX IS -3.47 * 10 ** 22.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   71    0    1

 GP * SOLUTION VECTOR AT FREQUENCY     0.48328 AU
 AFTER   36 LINEAR TRANSFORMATIONS IS     -8.02321104
 INERTIA (POS,ZER,NEG) OF REDUCED MATRIX IS   70    0    2
 DETERMINANT OF REDUCED MATRIX IS  1.14 * 10 ** 24.0


 ***WARNING, negative eigenvalues in reduced matrix, inertia is   70    0    2

 *** THE REQUESTED   12 SOLUTION VECTORS CONVERGED

 Convergence of RSP solution vectors, threshold = 1.00e-03
 ---------------------------------------------------------------
 (dimension of paired reduced space:   72)
 RSP solution vector no.    1; norm of residual   2.34e-05
 RSP solution vector no.    2; norm of residual   1.78e-05
 RSP solution vector no.    3; norm of residual   5.21e-05
 RSP solution vector no.    4; norm of residual   2.98e-05
 RSP solution vector no.    5; norm of residual   2.49e-05
 RSP solution vector no.    6; norm of residual   1.78e-05
 RSP solution vector no.    7; norm of residual   4.87e-05
 RSP solution vector no.    8; norm of residual   8.65e-06
 RSP solution vector no.    9; norm of residual   1.54e-05
 RSP solution vector no.   10; norm of residual   2.57e-05
 RSP solution vector no.   11; norm of residual   5.86e-05
 RSP solution vector no.   12; norm of residual   3.69e-05

 *** RSPCTL MICROITERATIONS CONVERGED

 QRLRVE: SINGLET SOLUTION   LABEL   YDIPLEN     FREQUENCY   0.408196e+00
 SYMMETRY    3

@QRLRVE:  << YDIPLEN  ; YDIPLEN  >> (   0.40820):     22.3124748226    

@QRLRVE:  << XANGMOM  ; YDIPLEN  >> (   0.40820):   -0.340691813660    

 QRLRVE: SINGLET SOLUTION   LABEL   YDIPLEN     FREQUENCY   0.458800e+00
 SYMMETRY    3

@QRLRVE:  << YDIPLEN  ; YDIPLEN  >> (   0.45880):     79.4901966440    

@QRLRVE:  << XANGMOM  ; YDIPLEN  >> (   0.45880):    -3.76741598702    

 QRLRVE: SINGLET SOLUTION   LABEL   YDIPLEN     FREQUENCY   0.316502e+00
 SYMMETRY    3

@QRLRVE:  << YDIPLEN  ; YDIPLEN  >> (   0.31650):     17.4395669440    

@QRLRVE:  << XANGMOM  ; YDIPLEN  >> (   0.31650):    0.201007405464    

 QRLRVE: SINGLET SOLUTION   LABEL   YDIPLEN     FREQUENCY   0.427812e+00
 SYMMETRY    3

@QRLRVE:  << YDIPLEN  ; YDIPLEN  >> (   0.42781):     31.0888408655    

@QRLRVE:  << XANGMOM  ; YDIPLEN  >> (   0.42781):   -0.120822197053    

 QRLRVE: SINGLET SOLUTION   LABEL   YDIPLEN     FREQUENCY   0.443797e+00
 SYMMETRY    3

@QRLRVE:  << YDIPLEN  ; YDIPLEN  >> (   0.44380):     42.4491101183    

@QRLRVE:  << XANGMOM  ; YDIPLEN  >> (   0.44380):   -0.573390166408    

 QRLRVE: SINGLET SOLUTION   LABEL   YDIPLEN     FREQUENCY   0.591276e+00
 SYMMETRY    3

@QRLRVE:  << YDIPLEN  ; YDIPLEN  >> (   0.59128):    -7.36815645251    

@QRLRVE:  << XANGMOM  ; YDIPLEN  >> (   0.59128):    -8.96664357652    

 QRLRVE: SINGLET SOLUTION   LABEL   YDIPLEN     FREQUENCY   0.336845e+00
 SYMMETRY    3

@QRLRVE:  << YDIPLEN  ; YDIPLEN  >> (   0.33685):     18.8827848023    

@QRLRVE:  << XANGMOM  ; YDIPLEN  >> (   0.33685):    0.263552280570    

 QRLRVE: SINGLET SOLUTION   LABEL   YDIPLEN     FREQUENCY   0.397228e+00
 SYMMETRY    3

@QRLRVE:  << YDIPLEN  ; YDIPLEN  >> (   0.39723):    0.715471957088    

@QRLRVE:  << XANGMOM  ; YDIPLEN  >> (   0.39723):    -2.91008738478    

 QRLRVE: SINGLET SOLUTION   LABEL   YDIPLEN     FREQUENCY   0.468548e+00
 SYMMETRY    3

@QRLRVE:  << YDIPLEN  ; YDIPLEN  >> (   0.46855):     4177.55987306    

@QRLRVE:  << XANGMOM  ; YDIPLEN  >> (   0.46855):    -473.506725952    

 QRLRVE: SINGLET SOLUTION   LABEL   YDIPLEN     FREQUENCY   0.483278e+00
 SYMMETRY    3

@QRLRVE:  << YDIPLEN  ; YDIPLEN  >> (   0.48328):    -8.02321104166    

@QRLRVE:  << XANGMOM  ; YDIPLEN  >> (   0.48328):     9.57756599902    

 QRLRVE: SINGLET SOLUTION   LABEL   YDIPLEN     FREQUENCY   0.260094e+00
 SYMMETRY    3

@QRLRVE:  << YDIPLEN  ; YDIPLEN  >> (   0.26009):     14.9197135084    

@QRLRVE:  << XANGMOM  ; YDIPLEN  >> (   0.26009):    0.105489356354    

 QRLRVE: SINGLET SOLUTION   LABEL   YDIPLEN     FREQUENCY   0.371728e+00
 SYMMETRY    3

@QRLRVE:  << YDIPLEN  ; YDIPLEN  >> (   0.37173):     23.3127093662    

@QRLRVE:  << XANGMOM  ; YDIPLEN  >> (   0.37173):    0.520312070564    


 QRLRVE -- linear response calculation for symmetry  3
 QRLRVE -- operator label : XANGMOM 
 QRLRVE -- frequencies :  0.000000



 <<<  SOLVING SETS OF LINEAR EQUATIONS FOR LINEAR RESPONSE PROPERTIES >>>

 Operator symmetry =  3; triplet =   F

 Electrons: 10.000000(-3.27e-07): LR-DFT*1 evaluation time:       1.2 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*1 evaluation time:       1.2 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*1 evaluation time:       1.2 s

 *** THE REQUESTED    1 SOLUTION VECTORS CONVERGED

 Convergence of RSP solution vectors, threshold = 1.00e-03
 ---------------------------------------------------------------
 (dimension of paired reduced space:    6)
 RSP solution vector no.    1; norm of residual   1.74e-04

 *** RSPCTL MICROITERATIONS CONVERGED

 QRLRVE: SINGLET SOLUTION   LABEL   XANGMOM     FREQUENCY   0.000000e+00
 SYMMETRY    3

@QRLRVE:  << YDIPLEN  ; XANGMOM  >> (   0.00000):   -6.245700668720e-17

@QRLRVE:  << XANGMOM  ; XANGMOM  >> (   0.00000):     2.07779613424    


 Linear response calculations for quadratic response
 - singlet property operator of symmetry    4


 Perturbation symmetry.     KSYMOP:       4
 Perturbation spin symmetry.TRPLET:       F
 Orbital variables.         KZWOPT:      29
 Configuration variables.   KZCONF:       0
 Total number of variables. KZVAR :      29


 QRLRVE -- linear response calculation for symmetry  4
 QRLRVE -- operator label : ZANGMOM 
 QRLRVE -- frequencies :  0.000000



 <<<  SOLVING SETS OF LINEAR EQUATIONS FOR LINEAR RESPONSE PROPERTIES >>>

 Operator symmetry =  4; triplet =   F

 Electrons: 10.000000(-3.27e-07): LR-DFT*1 evaluation time:       1.2 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*1 evaluation time:       1.2 s
 Electrons: 10.000000(-3.27e-07): LR-DFT*1 evaluation time:       1.2 s

 *** THE REQUESTED    1 SOLUTION VECTORS CONVERGED

 Convergence of RSP solution vectors, threshold = 1.00e-03
 ---------------------------------------------------------------
 (dimension of paired reduced space:    6)
 RSP solution vector no.    1; norm of residual   1.44e-04

 *** RSPCTL MICROITERATIONS CONVERGED

 QRLRVE: SINGLET SOLUTION   LABEL   ZANGMOM     FREQUENCY   0.000000e+00
 SYMMETRY    4

@QRLRVE:  << ZANGMOM  ; ZANGMOM  >> (   0.00000):     1.14494106824    
 DFT-QR computed in a linearly-scaling fashion.

 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.7 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      XDIPLEN     2    0
 B operator label,  symmetry, spin:      YANGMOM     2    0
 Excited state no., symmetry, spin:             1    1    0

 omega B, excitation energy, moment :    0.000000    0.336845   -8.381613

 First order moment in a.u. for
 C operator label,  symmetry, spin:      ZDIPLEN     1    0
 Excited state no., symmetry, spin:             1    1    0
 Excitation energy in au,    moment :                0.336845   -0.737144

 B term contribution:              3.089228
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      XDIPLEN     2    0
 B operator label,  symmetry, spin:      YANGMOM     2    0
 Excited state no., symmetry, spin:             2    1    0

 omega B, excitation energy, moment :    0.000000    0.397228   -7.166795

 First order moment in a.u. for
 C operator label,  symmetry, spin:      ZDIPLEN     1    0
 Excited state no., symmetry, spin:             2    1    0
 Excitation energy in au,    moment :                0.397228   -0.067944

 B term contribution:              0.243469
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      XDIPLEN     2    0
 B operator label,  symmetry, spin:      YANGMOM     2    0
 Excited state no., symmetry, spin:             3    1    0

 omega B, excitation energy, moment :    0.000000    0.468548   -9.871271

 First order moment in a.u. for
 C operator label,  symmetry, spin:      ZDIPLEN     1    0
 Excited state no., symmetry, spin:             3    1    0
 Excitation energy in au,    moment :                0.468548   -0.162247

 B term contribution:              0.800794
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      XDIPLEN     2    0
 B operator label,  symmetry, spin:      YANGMOM     2    0
 Excited state no., symmetry, spin:             4    1    0

 omega B, excitation energy, moment :    0.000000    0.483278   -6.976226

 First order moment in a.u. for
 C operator label,  symmetry, spin:      ZDIPLEN     1    0
 Excited state no., symmetry, spin:             4    1    0
 Excitation energy in au,    moment :                0.483278   -0.457883

 B term contribution:              1.597149
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.7 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      YDIPLEN     3    0
 B operator label,  symmetry, spin:      XANGMOM     3    0
 Excited state no., symmetry, spin:             1    1    0

 omega B, excitation energy, moment :    0.000000    0.336845   -5.468479

 First order moment in a.u. for
 C operator label,  symmetry, spin:      ZDIPLEN     1    0
 Excited state no., symmetry, spin:             1    1    0
 Excitation energy in au,    moment :                0.336845   -0.737144

 B term contribution:              2.015529
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.7 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      YDIPLEN     3    0
 B operator label,  symmetry, spin:      XANGMOM     3    0
 Excited state no., symmetry, spin:             2    1    0

 omega B, excitation energy, moment :    0.000000    0.397228   10.999921

 First order moment in a.u. for
 C operator label,  symmetry, spin:      ZDIPLEN     1    0
 Excited state no., symmetry, spin:             2    1    0
 Excitation energy in au,    moment :                0.397228   -0.067944

 B term contribution:             -0.373687
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.7 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      YDIPLEN     3    0
 B operator label,  symmetry, spin:      XANGMOM     3    0
 Excited state no., symmetry, spin:             3    1    0

 omega B, excitation energy, moment :    0.000000    0.468548  449.691804

 First order moment in a.u. for
 C operator label,  symmetry, spin:      ZDIPLEN     1    0
 Excited state no., symmetry, spin:             3    1    0
 Excitation energy in au,    moment :                0.468548   -0.162247

 B term contribution:            -36.480655
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.7 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      YDIPLEN     3    0
 B operator label,  symmetry, spin:      XANGMOM     3    0
 Excited state no., symmetry, spin:             4    1    0

 omega B, excitation energy, moment :    0.000000    0.483278   -6.361957

 First order moment in a.u. for
 C operator label,  symmetry, spin:      ZDIPLEN     1    0
 Excited state no., symmetry, spin:             4    1    0
 Excitation energy in au,    moment :                0.483278   -0.457883

 B term contribution:              1.456517
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      ZDIPLEN     1    0
 B operator label,  symmetry, spin:      YANGMOM     2    0
 Excited state no., symmetry, spin:             1    2    0

 omega B, excitation energy, moment :    0.000000    0.260094   -9.238086

 First order moment in a.u. for
 C operator label,  symmetry, spin:      XDIPLEN     2    0
 Excited state no., symmetry, spin:             1    2    0
 Excitation energy in au,    moment :                0.260094   -0.651687

 B term contribution:              3.010172
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      ZDIPLEN     1    0
 B operator label,  symmetry, spin:      YANGMOM     2    0
 Excited state no., symmetry, spin:             2    2    0

 omega B, excitation energy, moment :    0.000000    0.371728   -1.045784

 First order moment in a.u. for
 C operator label,  symmetry, spin:      XDIPLEN     2    0
 Excited state no., symmetry, spin:             2    2    0
 Excitation energy in au,    moment :                0.371728    0.002162

 B term contribution:             -0.001131
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      ZDIPLEN     1    0
 B operator label,  symmetry, spin:      YANGMOM     2    0
 Excited state no., symmetry, spin:             3    2    0

 omega B, excitation energy, moment :    0.000000    0.408196    6.718618

 First order moment in a.u. for
 C operator label,  symmetry, spin:      XDIPLEN     2    0
 Excited state no., symmetry, spin:             3    2    0
 Excitation energy in au,    moment :                0.408196    0.141087

 B term contribution:              0.473953
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      ZDIPLEN     1    0
 B operator label,  symmetry, spin:      YANGMOM     2    0
 Excited state no., symmetry, spin:             4    2    0

 omega B, excitation energy, moment :    0.000000    0.458800   20.554722

 First order moment in a.u. for
 C operator label,  symmetry, spin:      XDIPLEN     2    0
 Excited state no., symmetry, spin:             4    2    0
 Excitation energy in au,    moment :                0.458800    0.157023

 B term contribution:              1.613785
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      YDIPLEN     3    0
 B operator label,  symmetry, spin:      ZANGMOM     4    0
 Excited state no., symmetry, spin:             1    2    0

 omega B, excitation energy, moment :    0.000000    0.260094    2.756296

 First order moment in a.u. for
 C operator label,  symmetry, spin:      XDIPLEN     2    0
 Excited state no., symmetry, spin:             1    2    0
 Excitation energy in au,    moment :                0.260094   -0.651687

 B term contribution:             -0.898122
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      YDIPLEN     3    0
 B operator label,  symmetry, spin:      ZANGMOM     4    0
 Excited state no., symmetry, spin:             2    2    0

 omega B, excitation energy, moment :    0.000000    0.371728    1.412016

 First order moment in a.u. for
 C operator label,  symmetry, spin:      XDIPLEN     2    0
 Excited state no., symmetry, spin:             2    2    0
 Excitation energy in au,    moment :                0.371728    0.002162

 B term contribution:              0.001526
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      YDIPLEN     3    0
 B operator label,  symmetry, spin:      ZANGMOM     4    0
 Excited state no., symmetry, spin:             3    2    0

 omega B, excitation energy, moment :    0.000000    0.408196   -0.155424

 First order moment in a.u. for
 C operator label,  symmetry, spin:      XDIPLEN     2    0
 Excited state no., symmetry, spin:             3    2    0
 Excitation energy in au,    moment :                0.408196    0.141087

 B term contribution:             -0.010964
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      YDIPLEN     3    0
 B operator label,  symmetry, spin:      ZANGMOM     4    0
 Excited state no., symmetry, spin:             4    2    0

 omega B, excitation energy, moment :    0.000000    0.458800   -7.028364

 First order moment in a.u. for
 C operator label,  symmetry, spin:      XDIPLEN     2    0
 Excited state no., symmetry, spin:             4    2    0
 Excitation energy in au,    moment :                0.458800    0.157023

 B term contribution:             -0.551808
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.7 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      ZDIPLEN     1    0
 B operator label,  symmetry, spin:      XANGMOM     3    0
 Excited state no., symmetry, spin:             1    3    0

 omega B, excitation energy, moment :    0.000000    0.394814   -3.141206

 First order moment in a.u. for
 C operator label,  symmetry, spin:      YDIPLEN     3    0
 Excited state no., symmetry, spin:             1    3    0
 Excitation energy in au,    moment :                0.394814   -0.238923

 B term contribution:              0.375252
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.7 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      ZDIPLEN     1    0
 B operator label,  symmetry, spin:      XANGMOM     3    0
 Excited state no., symmetry, spin:             2    3    0

 omega B, excitation energy, moment :    0.000000    0.468683  -92.103268

 First order moment in a.u. for
 C operator label,  symmetry, spin:      YDIPLEN     3    0
 Excited state no., symmetry, spin:             2    3    0
 Excitation energy in au,    moment :                0.468683    0.748664

 B term contribution:            -34.477189
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.7 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      ZDIPLEN     1    0
 B operator label,  symmetry, spin:      XANGMOM     3    0
 Excited state no., symmetry, spin:             3    3    0

 omega B, excitation energy, moment :    0.000000    0.512613    6.488796

 First order moment in a.u. for
 C operator label,  symmetry, spin:      YDIPLEN     3    0
 Excited state no., symmetry, spin:             3    3    0
 Excitation energy in au,    moment :                0.512613   -0.203752

 B term contribution:             -0.661053
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.7 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      ZDIPLEN     1    0
 B operator label,  symmetry, spin:      XANGMOM     3    0
 Excited state no., symmetry, spin:             4    3    0

 omega B, excitation energy, moment :    0.000000    0.522952   10.906978

 First order moment in a.u. for
 C operator label,  symmetry, spin:      YDIPLEN     3    0
 Excited state no., symmetry, spin:             4    3    0
 Excitation energy in au,    moment :                0.522952   -0.584102

 B term contribution:             -3.185396
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      XDIPLEN     2    0
 B operator label,  symmetry, spin:      ZANGMOM     4    0
 Excited state no., symmetry, spin:             1    3    0

 omega B, excitation energy, moment :    0.000000    0.394814    1.661200

 First order moment in a.u. for
 C operator label,  symmetry, spin:      YDIPLEN     3    0
 Excited state no., symmetry, spin:             1    3    0
 Excitation energy in au,    moment :                0.394814   -0.238923

 B term contribution:             -0.198449
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      XDIPLEN     2    0
 B operator label,  symmetry, spin:      ZANGMOM     4    0
 Excited state no., symmetry, spin:             2    3    0

 omega B, excitation energy, moment :    0.000000    0.468683   -2.145468

 First order moment in a.u. for
 C operator label,  symmetry, spin:      YDIPLEN     3    0
 Excited state no., symmetry, spin:             2    3    0
 Excitation energy in au,    moment :                0.468683    0.748664

 B term contribution:             -0.803117
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      XDIPLEN     2    0
 B operator label,  symmetry, spin:      ZANGMOM     4    0
 Excited state no., symmetry, spin:             3    3    0

 omega B, excitation energy, moment :    0.000000    0.512613   -6.314438

 First order moment in a.u. for
 C operator label,  symmetry, spin:      YDIPLEN     3    0
 Excited state no., symmetry, spin:             3    3    0
 Excitation energy in au,    moment :                0.512613   -0.203752

 B term contribution:              0.643290
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      XDIPLEN     2    0
 B operator label,  symmetry, spin:      ZANGMOM     4    0
 Excited state no., symmetry, spin:             4    3    0

 omega B, excitation energy, moment :    0.000000    0.522952   -5.720558

 First order moment in a.u. for
 C operator label,  symmetry, spin:      YDIPLEN     3    0
 Excited state no., symmetry, spin:             4    3    0
 Excitation energy in au,    moment :                0.522952   -0.584102

 B term contribution:              1.670696
 ------------------------------------------- 
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      YDIPLEN     3    0
 B operator label,  symmetry, spin:      YANGMOM     2    0
 Excited state no., symmetry, spin:             1    4    0

 omega B, excitation energy, moment :    0.000000    0.316502    2.981123
 No MCD for this SOMOM
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      YDIPLEN     3    0
 B operator label,  symmetry, spin:      YANGMOM     2    0
 Excited state no., symmetry, spin:             2    4    0

 omega B, excitation energy, moment :    0.000000    0.427812    2.398043
 No MCD for this SOMOM
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      YDIPLEN     3    0
 B operator label,  symmetry, spin:      YANGMOM     2    0
 Excited state no., symmetry, spin:             3    4    0

 omega B, excitation energy, moment :    0.000000    0.443797   -0.910133
 No MCD for this SOMOM
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      YDIPLEN     3    0
 B operator label,  symmetry, spin:      YANGMOM     2    0
 Excited state no., symmetry, spin:             4    4    0

 omega B, excitation energy, moment :    0.000000    0.591276  -28.982597
 No MCD for this SOMOM
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      XDIPLEN     2    0
 B operator label,  symmetry, spin:      XANGMOM     3    0
 Excited state no., symmetry, spin:             1    4    0

 omega B, excitation energy, moment :    0.000000    0.316502    2.274185
 No MCD for this SOMOM
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      XDIPLEN     2    0
 B operator label,  symmetry, spin:      XANGMOM     3    0
 Excited state no., symmetry, spin:             2    4    0

 omega B, excitation energy, moment :    0.000000    0.427812   -4.844419
 No MCD for this SOMOM
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      XDIPLEN     2    0
 B operator label,  symmetry, spin:      XANGMOM     3    0
 Excited state no., symmetry, spin:             3    4    0

 omega B, excitation energy, moment :    0.000000    0.443797   10.412326
 No MCD for this SOMOM
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      XDIPLEN     2    0
 B operator label,  symmetry, spin:      XANGMOM     3    0
 Excited state no., symmetry, spin:             4    4    0

 omega B, excitation energy, moment :    0.000000    0.591276   -1.273230
 No MCD for this SOMOM
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      ZDIPLEN     1    0
 B operator label,  symmetry, spin:      ZANGMOM     4    0
 Excited state no., symmetry, spin:             1    4    0

 omega B, excitation energy, moment :    0.000000    0.316502   -4.255232
 No MCD for this SOMOM
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      ZDIPLEN     1    0
 B operator label,  symmetry, spin:      ZANGMOM     4    0
 Excited state no., symmetry, spin:             2    4    0

 omega B, excitation energy, moment :    0.000000    0.427812    1.014526
 No MCD for this SOMOM
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      ZDIPLEN     1    0
 B operator label,  symmetry, spin:      ZANGMOM     4    0
 Excited state no., symmetry, spin:             3    4    0

 omega B, excitation energy, moment :    0.000000    0.443797   -0.417545
 No MCD for this SOMOM
 Electrons: 10.000000(-3.27e-07): QR-DFT/b evaluation time:       1.6 s


 Second order moment in a.u. for
 A operator label,  symmetry, spin:      ZDIPLEN     1    0
 B operator label,  symmetry, spin:      ZANGMOM     4    0
 Excited state no., symmetry, spin:             4    4    0

 omega B, excitation energy, moment :    0.000000    0.591276    7.985642
 No MCD for this SOMOM

 >>>> Total CPU  time used in RESPONSE:  4 minutes 10 seconds
 >>>> Total wall time used in RESPONSE:  4 minutes 13 seconds
 >>>> Total CPU  time used in DALTON:  4 minutes 23 seconds
 >>>> Total wall time used in DALTON:  4 minutes 26 seconds

 
     Date and time (Linux)  : Tue Nov 13 16:12:21 2007
     Host name              : platina                                 
END REFOUT

