#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > cc2_r12_aux_ne_gamma.info <<'%EOF%'
   cc2_r12_aux_ne_gamma
   ------------
   Molecule:         Ne in D2h
   Wave Function:    CC2-R12/B/1  cc-pVDZ/cc-pVDZ
   Test Purpose:     Test properties up to second hyperpolarizabilities (cubic response):
                     - for CC2-R12 (Ansatz 1B) 
%EOF%

#######################################################################
#  INTEGRAL INPUT
#######################################################################
cat > cc2_r12_aux_ne_gamma.mol <<'%EOF%'
INTGRL
Ne CC2-R12/A/1 aug-cc-pVDZ/aug-cc-pVDZ              
                                                                                
    2  0 3 X  Y  Z     .10D-14
 1     10.    1    3    4    3    2
Ne        .0000000000000      .0000000000000      .0000000000000
H   9    1
    17880.0000000000         .0007380000
     2683.0000000000         .0056770000
      611.5000000000         .0288830000
      173.5000000000         .1085400000
       56.6400000000         .2909070000
       20.4200000000         .4483240000
        7.8100000000         .2580260000
        1.6530000000         .0150630000
         .4869000000        -.0021000000
H   9    1
    17880.0000000000        -.0001720000
     2683.0000000000        -.0013570000
      611.5000000000        -.0067370000
      173.5000000000        -.0276630000
       56.6400000000        -.0762080000
       20.4200000000        -.1752270000
        7.8100000000        -.1070380000
        1.6530000000         .5670500000
         .4869000000         .5652160000
H   1    1
         .4869000000        1.0000000000
H   1    1
         .1230000000        1.0000000000
H   4    1
       28.3900000000         .0460870000
        6.2700000000         .2401810000
        1.6950000000         .5087440000
         .4317000000         .4556600000
H   1    1
         .4317000000        1.0000000000
H   1    1
         .1064000000        1.0000000000
H   1    1
        2.2020000000        1.0000000000
H   1    1
         .6310000000        1.0000000000
 2     10.    1    3    4    3    2
Ne        .0000000000000      .0000000000000      .0000000000000
H   9    1
    17880.0000000000         .0007380000
     2683.0000000000         .0056770000
      611.5000000000         .0288830000
      173.5000000000         .1085400000
       56.6400000000         .2909070000
       20.4200000000         .4483240000
        7.8100000000         .2580260000
        1.6530000000         .0150630000
         .4869000000        -.0021000000
H   9    1
    17880.0000000000        -.0001720000
     2683.0000000000        -.0013570000
      611.5000000000        -.0067370000
      173.5000000000        -.0276630000
       56.6400000000        -.0762080000
       20.4200000000        -.1752270000
        7.8100000000        -.1070380000
        1.6530000000         .5670500000
         .4869000000         .5652160000
H   1    1
         .4869000000        1.0000000000
H   1    1
         .1230000000        1.0000000000
H   4    1
       28.3900000000         .0460870000
        6.2700000000         .2401810000
        1.6950000000         .5087440000
         .4317000000         .4556600000
H   1    1
         .4317000000        1.0000000000
H   1    1
         .1064000000        1.0000000000
H   1    1
        2.2020000000        1.0000000000
H   1    1
         .6310000000        1.0000000000
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > cc2_r12_aux_ne_gamma.dal <<'%EOF%'
**DALTON INPUT
.RUN WAVE FUNCTION
.DIRECT
*MOLBAS
.R12AUX
**INTEGRALS
.R12
.DIPLEN
.SECMOM
**WAVE FUNCTION
.CC
*ORBITAL
.AO DEL
 1.0D-7
.MOSTART
 H1DIAG
*SCF INPUT
.THRESH
 1.0D-10
*CC INPUT
.CC2
.PRINT
 3 
.THRENR
 1.0D-14
.THRLEQ
 1.0D-14
.MAX IT
 100
*CCFOP
.NONREL
.OPERAT
XXSECMOM
*CCLR
.DIPOLE
*CCCR
.DIPOLE
*R12 INPUT
.NO HYB
.CC2
 1B
**END OF DALTON INPUT
%EOF%
#######################################################################


#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >cc2_r12_aux_ne_gamma.check
cat >>cc2_r12_aux_ne_gamma.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

#           Total SCF   energy:                  -128.4963497305 
#           Total MP2-R12/B energy:              -128.9905541705
#           Total CC2-R12/B energy:              -128.9912527718
#
#
#           XXSECMOM:   3.20792857
# 
#
#      +--------------------------------------------------------------+
#      !      FINAL CC2 RESULTS FOR THE SECOND-ORDER PROPERTIES       !
#      +--------------------------------------------------------------+
#  A operator                  B operator                     property 
#------------------------------------------------------------------------
# XDIPLEN  (unrel.)  0.0000   XDIPLEN  (unrel.)  0.0000      1.9651941    
# XDIPLEN  (unrel.)    -.-    YDIPLEN  (unrel.)    -.-          ---
# XDIPLEN  (unrel.)    -.-    ZDIPLEN  (unrel.)    -.-          ---
# YDIPLEN  (unrel.)    -.-    XDIPLEN  (unrel.)    -.-          ---
# YDIPLEN  (unrel.)  0.0000   YDIPLEN  (unrel.)  0.0000      1.9651941    
# YDIPLEN  (unrel.)    -.-    ZDIPLEN  (unrel.)    -.-          ---
# ZDIPLEN  (unrel.)    -.-    XDIPLEN  (unrel.)    -.-          ---
# ZDIPLEN  (unrel.)    -.-    YDIPLEN  (unrel.)    -.-          ---
# ZDIPLEN  (unrel.)  0.0000   ZDIPLEN  (unrel.)  0.0000      1.9651941    
#------------------------------------------------------------------------
#
#
#----------------------------------------------------------------------------+
#           FINAL CC2 RESULTS FOR THE SECOND HYPERPOLARIZABILITIES           !
#----------------------------------------------------------------------------+
# A operator        B operator        C operator        D operator           gamma
#-------------------------------------------------------------------------------------
#XDIPLEN  0.0000   XDIPLEN  0.0000   XDIPLEN  0.0000   XDIPLEN  0.0000     -29.077418    
#XDIPLEN    -.-    XDIPLEN    -.-    XDIPLEN    -.-    YDIPLEN    -.-          ---
#XDIPLEN    -.-    XDIPLEN    -.-    XDIPLEN    -.-    ZDIPLEN    -.-          ---
#XDIPLEN    -.-    XDIPLEN    -.-    YDIPLEN    -.-    XDIPLEN    -.-          ---
#XDIPLEN  0.0000   XDIPLEN  0.0000   YDIPLEN  0.0000   YDIPLEN  0.0000     -9.6924726    
#XDIPLEN    -.-    XDIPLEN    -.-    YDIPLEN    -.-    ZDIPLEN    -.-          ---
#XDIPLEN    -.-    XDIPLEN    -.-    ZDIPLEN    -.-    XDIPLEN    -.-          ---
#XDIPLEN    -.-    XDIPLEN    -.-    ZDIPLEN    -.-    YDIPLEN    -.-          ---
#XDIPLEN  0.0000   XDIPLEN  0.0000   ZDIPLEN  0.0000   ZDIPLEN  0.0000     -9.6924726    
#XDIPLEN    -.-    YDIPLEN    -.-    XDIPLEN    -.-    XDIPLEN    -.-          ---
#XDIPLEN  0.0000   YDIPLEN  0.0000   XDIPLEN  0.0000   YDIPLEN  0.0000     -9.6924726    
#XDIPLEN    -.-    YDIPLEN    -.-    XDIPLEN    -.-    ZDIPLEN    -.-          ---
#XDIPLEN  0.0000   YDIPLEN  0.0000   YDIPLEN  0.0000   XDIPLEN  0.0000     -9.6924726    
#XDIPLEN    -.-    YDIPLEN    -.-    YDIPLEN    -.-    YDIPLEN    -.-          ---
#XDIPLEN    -.-    YDIPLEN    -.-    YDIPLEN    -.-    ZDIPLEN    -.-          ---
#XDIPLEN    -.-    YDIPLEN    -.-    ZDIPLEN    -.-    XDIPLEN    -.-          ---
#XDIPLEN    -.-    YDIPLEN    -.-    ZDIPLEN    -.-    YDIPLEN    -.-          ---
#XDIPLEN    -.-    YDIPLEN    -.-    ZDIPLEN    -.-    ZDIPLEN    -.-          ---
#XDIPLEN    -.-    ZDIPLEN    -.-    XDIPLEN    -.-    XDIPLEN    -.-          ---
#XDIPLEN    -.-    ZDIPLEN    -.-    XDIPLEN    -.-    YDIPLEN    -.-          ---
#XDIPLEN  0.0000   ZDIPLEN  0.0000   XDIPLEN  0.0000   ZDIPLEN  0.0000     -9.6924726    
#XDIPLEN    -.-    ZDIPLEN    -.-    YDIPLEN    -.-    XDIPLEN    -.-          ---
#XDIPLEN    -.-    ZDIPLEN    -.-    YDIPLEN    -.-    YDIPLEN    -.-          ---
#XDIPLEN    -.-    ZDIPLEN    -.-    YDIPLEN    -.-    ZDIPLEN    -.-          ---
#XDIPLEN  0.0000   ZDIPLEN  0.0000   ZDIPLEN  0.0000   XDIPLEN  0.0000     -9.6924726    
#XDIPLEN    -.-    ZDIPLEN    -.-    ZDIPLEN    -.-    YDIPLEN    -.-          ---
#XDIPLEN    -.-    ZDIPLEN    -.-    ZDIPLEN    -.-    ZDIPLEN    -.-          ---
#YDIPLEN    -.-    XDIPLEN    -.-    XDIPLEN    -.-    XDIPLEN    -.-          ---
#YDIPLEN  0.0000   XDIPLEN  0.0000   XDIPLEN  0.0000   YDIPLEN  0.0000     -9.6924726    
#YDIPLEN    -.-    XDIPLEN    -.-    XDIPLEN    -.-    ZDIPLEN    -.-          ---
#YDIPLEN  0.0000   XDIPLEN  0.0000   YDIPLEN  0.0000   XDIPLEN  0.0000     -9.6924726    
#YDIPLEN    -.-    XDIPLEN    -.-    YDIPLEN    -.-    YDIPLEN    -.-          ---
#YDIPLEN    -.-    XDIPLEN    -.-    YDIPLEN    -.-    ZDIPLEN    -.-          ---
#YDIPLEN    -.-    XDIPLEN    -.-    ZDIPLEN    -.-    XDIPLEN    -.-          ---
#YDIPLEN    -.-    XDIPLEN    -.-    ZDIPLEN    -.-    YDIPLEN    -.-          ---
#YDIPLEN    -.-    XDIPLEN    -.-    ZDIPLEN    -.-    ZDIPLEN    -.-          ---
#YDIPLEN  0.0000   YDIPLEN  0.0000   XDIPLEN  0.0000   XDIPLEN  0.0000     -9.6924726    
#YDIPLEN    -.-    YDIPLEN    -.-    XDIPLEN    -.-    YDIPLEN    -.-          ---
#YDIPLEN    -.-    YDIPLEN    -.-    XDIPLEN    -.-    ZDIPLEN    -.-          ---
#YDIPLEN    -.-    YDIPLEN    -.-    YDIPLEN    -.-    XDIPLEN    -.-          ---
#YDIPLEN  0.0000   YDIPLEN  0.0000   YDIPLEN  0.0000   YDIPLEN  0.0000     -29.077418    
#YDIPLEN    -.-    YDIPLEN    -.-    YDIPLEN    -.-    ZDIPLEN    -.-          ---
#YDIPLEN    -.-    YDIPLEN    -.-    ZDIPLEN    -.-    XDIPLEN    -.-          ---
#YDIPLEN    -.-    YDIPLEN    -.-    ZDIPLEN    -.-    YDIPLEN    -.-          ---
#YDIPLEN  0.0000   YDIPLEN  0.0000   ZDIPLEN  0.0000   ZDIPLEN  0.0000     -9.6924726    
#YDIPLEN    -.-    ZDIPLEN    -.-    XDIPLEN    -.-    XDIPLEN    -.-          ---
#YDIPLEN    -.-    ZDIPLEN    -.-    XDIPLEN    -.-    YDIPLEN    -.-          ---
#YDIPLEN    -.-    ZDIPLEN    -.-    XDIPLEN    -.-    ZDIPLEN    -.-          ---
#YDIPLEN    -.-    ZDIPLEN    -.-    YDIPLEN    -.-    XDIPLEN    -.-          ---
#YDIPLEN    -.-    ZDIPLEN    -.-    YDIPLEN    -.-    YDIPLEN    -.-          ---
#YDIPLEN  0.0000   ZDIPLEN  0.0000   YDIPLEN  0.0000   ZDIPLEN  0.0000     -9.6924726    
#YDIPLEN    -.-    ZDIPLEN    -.-    ZDIPLEN    -.-    XDIPLEN    -.-          ---
#YDIPLEN  0.0000   ZDIPLEN  0.0000   ZDIPLEN  0.0000   YDIPLEN  0.0000     -9.6924726    
#YDIPLEN    -.-    ZDIPLEN    -.-    ZDIPLEN    -.-    ZDIPLEN    -.-          ---
#ZDIPLEN    -.-    XDIPLEN    -.-    XDIPLEN    -.-    XDIPLEN    -.-          ---
#ZDIPLEN    -.-    XDIPLEN    -.-    XDIPLEN    -.-    YDIPLEN    -.-          ---
#ZDIPLEN  0.0000   XDIPLEN  0.0000   XDIPLEN  0.0000   ZDIPLEN  0.0000     -9.6924726    
#ZDIPLEN    -.-    XDIPLEN    -.-    YDIPLEN    -.-    XDIPLEN    -.-          ---
#ZDIPLEN    -.-    XDIPLEN    -.-    YDIPLEN    -.-    YDIPLEN    -.-          ---
#ZDIPLEN    -.-    XDIPLEN    -.-    YDIPLEN    -.-    ZDIPLEN    -.-          ---
#ZDIPLEN  0.0000   XDIPLEN  0.0000   ZDIPLEN  0.0000   XDIPLEN  0.0000     -9.6924726    
#ZDIPLEN    -.-    XDIPLEN    -.-    ZDIPLEN    -.-    YDIPLEN    -.-          ---
#ZDIPLEN    -.-    XDIPLEN    -.-    ZDIPLEN    -.-    ZDIPLEN    -.-          ---
#ZDIPLEN    -.-    YDIPLEN    -.-    XDIPLEN    -.-    XDIPLEN    -.-          ---
#ZDIPLEN    -.-    YDIPLEN    -.-    XDIPLEN    -.-    YDIPLEN    -.-          ---
#ZDIPLEN    -.-    YDIPLEN    -.-    XDIPLEN    -.-    ZDIPLEN    -.-          ---
#ZDIPLEN    -.-    YDIPLEN    -.-    YDIPLEN    -.-    XDIPLEN    -.-          ---
#ZDIPLEN    -.-    YDIPLEN    -.-    YDIPLEN    -.-    YDIPLEN    -.-          ---
#ZDIPLEN  0.0000   YDIPLEN  0.0000   YDIPLEN  0.0000   ZDIPLEN  0.0000     -9.6924726    
#ZDIPLEN    -.-    YDIPLEN    -.-    ZDIPLEN    -.-    XDIPLEN    -.-          ---
#ZDIPLEN  0.0000   YDIPLEN  0.0000   ZDIPLEN  0.0000   YDIPLEN  0.0000     -9.6924726    
#ZDIPLEN    -.-    YDIPLEN    -.-    ZDIPLEN    -.-    ZDIPLEN    -.-          ---
#ZDIPLEN  0.0000   ZDIPLEN  0.0000   XDIPLEN  0.0000   XDIPLEN  0.0000     -9.6924726    
#ZDIPLEN    -.-    ZDIPLEN    -.-    XDIPLEN    -.-    YDIPLEN    -.-          ---
#ZDIPLEN    -.-    ZDIPLEN    -.-    XDIPLEN    -.-    ZDIPLEN    -.-          ---
#ZDIPLEN    -.-    ZDIPLEN    -.-    YDIPLEN    -.-    XDIPLEN    -.-          ---
#ZDIPLEN  0.0000   ZDIPLEN  0.0000   YDIPLEN  0.0000   YDIPLEN  0.0000     -9.6924726    
#ZDIPLEN    -.-    ZDIPLEN    -.-    YDIPLEN    -.-    ZDIPLEN    -.-          ---
#ZDIPLEN    -.-    ZDIPLEN    -.-    ZDIPLEN    -.-    XDIPLEN    -.-          ---
#ZDIPLEN    -.-    ZDIPLEN    -.-    ZDIPLEN    -.-    YDIPLEN    -.-          ---
#ZDIPLEN  0.0000   ZDIPLEN  0.0000   ZDIPLEN  0.0000   ZDIPLEN  0.0000     -29.077418    
#-------------------------------------------------------------------------------------
#--------------------------------------------------------------------------

CRIT1=`$GREP "Total CC2-R12/B energy: *\-128\.9912527718" $log | wc -l`
TEST[1]=`expr $CRIT1` 
CTRL[1]=2
ERROR[1]="CC2-R12/B ENERGY NOT CORRECT"

CRIT2=`$GREP "XXSECMOM: *3\.20792857" $log | wc -l`
TEST[2]=`expr $CRIT2`
CTRL[2]=1
ERROR[2]="CC2-R12/A FIRST ORDER PROPERTIES NOT CORRECT"

CRIT3=`$GREP "XDIPLEN .*1\.9651941" $log | wc -l`
CRIT4=`$GREP "YDIPLEN .*1\.9651941" $log | wc -l`
CRIT5=`$GREP "ZDIPLEN .*1\.9651941" $log | wc -l`
TEST[3]=`expr $CRIT3 + $CRIT4 + $CRIT5`
CTRL[3]=3
ERROR[3]="CC2-R12/A SECOND ORDER PROPERTIES NOT CORRECT"

CRIT6=`$GREP "XDIPLEN .*\-29\.077418" $log | wc -l`
CRIT7=`$GREP "YDIPLEN .*\-29\.077418" $log | wc -l`
CRIT8=`$GREP "ZDIPLEN .*\-29\.077418" $log | wc -l`
CRIT9=`$GREP "\-9\.6924726" $log | wc -l`
TEST[4]=`expr $CRIT6 + $CRIT7 + $CRIT8 +  $CRIT9`
CTRL[4]=21
ERROR[2]="CC2-R12/A SECOND HYPERPOLARIZABILITY  NOT CORRECT"

PASSED=1
for i in 1 2 3 4
do
   if [ ${TEST[i]} -lt ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi                
%EOF%
#######################################################################
