#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi

#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > cc2_r12_aux2_bh_a2.info <<'%EOF%'
   cc2_r12_aux2_bh_a2
   -----------
   Molecule:         BH 
   Wave Function:    CC2-R12/A2/B / AhlrichsVDZ + AhlrichsVTZ-Auxbasis
   Test Purpose:     Check CC2-R12/A2/B method with auxiliary basis 
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > cc2_r12_aux2_bh_a2.mol <<'%EOF%'
BASIS
Ahlrichs-VDZ Ahlrichs-VTZ
BH
                                                                            
    4    0            0.10D-14
 1      5.    1    3    3    2    1
B        0.0000000000000     0.0000000000000     0.0000000000000
 1      1.    1
H        0.0000000000000     0.0000000000000     2.3288983083247
 2      5.0   1
B        0.0000000000000     0.0000000000000     0.0000000000000
 2      1.0   1
H        0.0000000000000     0.0000000000000     2.3288983083247
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > cc2_r12_aux2_bh_a2.dal <<'%EOF%'

**DALTON INPUT
.RUN WAVE FUNCTION
.DIRECT
*MOLBAS
.R12AUX
**INTEGRALS
.R12
**WAVE FUNCTION
.CC
*ORBITAL INPUT
.NOSUPSYM
.MOSTART
 H1DIAG
*SCF INPUT
.THRESH
 1.0D-10
*CC INPUT
.CC2
.PRINT
 3 
.FREEZE
  1 0
.THRENR
 1.0D-12
.MAX IT
 300
*CCEXCI
.THREXC
 1.D-10
.NCCEXCI
 8 
*R12 INPUT
.NO HYB
#.R12XXL
#.NO B'
#.NO A'
#.NO A
#.NO 1
.CC2
 2B
**END OF DALTON INPUT
%EOF%

#######################################################################

 

#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >cc2_r12_aux2_bh_a2.check
cat >>cc2_r12_aux2_bh_a2.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi
#
#            Total SCF   energy:                   -24.8662249632
#            Total MP2-R12/B energy:               -24.9525912460
#            Total CC2-R12/B energy:               -24.9527467638
#
#    Total energies in Hartree:                                                 
#            1 ^1A        -25.0444147127                                        
#            2 ^1A        -24.9366998509                                        
#            3 ^1A        -24.6838915007                                        
#            4 ^1A        -24.6784211853                                        
#            5 ^1A        -24.6231778114                                        
#            6 ^1A        -24.5773634213                                        
#            7 ^1A        -24.5715648706                                        
#            8 ^1A        -24.5607397376                                        
#
CRIT1=`$GREP "Total MP2-R12/B energy: *-24.9525912460" $log | wc -l`
TEST[1]=`expr	$CRIT1`
CTRL[1]=2
ERROR[1]="MP2-R12/B ENERGY NOT CORRECT"
CRIT2=`$GREP "Total CC2-R12/B energy: *-24.9527467638" $log | wc -l`
TEST[2]=`expr	$CRIT2`
CTRL[2]=2
ERROR[2]="CC2-R12/B ENERGY NOT CORRECT"
#
CRIT3=`$GREP "1 \^1A *-25.04441471.." $log | wc -l`
TEST[3]=`expr	$CRIT3`
CTRL[3]=1
ERROR[3]="CC2-R12/B 1A1 EXCITATION ENERGY NOT CORRECT"
CRIT4=`$GREP "2 \^1A *-24.93669985.." $log | wc -l`
TEST[4]=`expr	$CRIT4`
CTRL[4]=1
ERROR[4]="CC2-R12/B 2A1 EXCITATION ENERGY NOT CORRECT"
CRIT5=`$GREP "3 \^1A *-24.68389150.." $log | wc -l`
TEST[5]=`expr	$CRIT5`
CTRL[5]=1
ERROR[5]="CC2-R12/B 3A1 EXCITATION ENERGY NOT CORRECT"
CRIT6=`$GREP "4 \^1A *-24.67842118.." $log | wc -l`
TEST[6]=`expr	$CRIT6`
CTRL[6]=1
ERROR[6]="CC2-R12/B 4A1 EXCITATION ENERGY NOT CORRECT"
CRIT7=`$GREP "5 \^1A *-24.62317781.." $log | wc -l`
TEST[7]=`expr   $CRIT7`
CTRL[7]=1
ERROR[7]="CC2-R12/B 5A1 EXCITATION ENERGY NOT CORRECT"
CRIT8=`$GREP "6 \^1A *-24.57736342.." $log | wc -l`
TEST[8]=`expr   $CRIT8`
CTRL[8]=1
ERROR[8]="CC2-R12/B 6A1 EXCITATION ENERGY NOT CORRECT"
CRIT9=`$GREP "7 \^1A *-24.57156487.." $log | wc -l`
TEST[9]=`expr   $CRIT9`
CTRL[9]=1
ERROR[9]="CC2-R12/B 7A1 EXCITATION ENERGY NOT CORRECT"
CRIT10=`$GREP "8 \^1A *-24.56073973.." $log | wc -l`
TEST[10]=`expr   $CRIT10`
CTRL[10]=1
ERROR[10]="CC2-R12/B 8A1 EXCITATION ENERGY NOT CORRECT"


PASSED=1
for i in 1 2 3 4 5 6 7 8 9 10  
do 
   if [ ${TEST[i]} -lt ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done 

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM 
  exit 1
fi

%EOF%
#######################################################################
