#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > cc_rsp_gamma2.info <<'%EOF%'
   cc_rsp_gamma2
   -------------
   Molecule:         HF in C2
   Wave Function:    CCSD / 6-31G**
   Test Purpose:     Second hyperpolarizability (cubic response):
                     - Parallel isotropic average (gamma_||) 
                     - A & B coefficients  (2. and 4. order disp.
                       coefficients)
                     - Explicitly use symmetry of linear molecules
%EOF%

#######################################################################
#  INTEGRAL INPUT
#######################################################################
cat > cc_rsp_gamma2.mol <<'%EOF%'
BASIS
6-31G**
Hydrogen flourid
small test basis
    2    1  Y  X      1.00D-15
        9.0   1    
F     0.0000000000000000  0.0000000000000000 1.76320000000000000      
        1.0   1
H     0.0000000000000000  0.0000000000000000 0.00000000000000000      
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > cc_rsp_gamma2.dal <<'%EOF%'
**DALTON INPUT
.RUN WAVE FUNCTIONS
**INTEGRAL
.DIPLEN
**WAVE FUNCTIONS
.TITLE
  second hyperpolarizability for the HF molecule
  for a CCS wavefunction compute:
  - parallel isotropic average (gamma_||) 
  - A & B coefficients  (2. and 4. order disp. coefficients)
  - use explicitly symmetry of linear molecules
.CC
*SCF INPUT 
.THRESH
 1.0d-12
*CC INPUT 
.CCSD
.THRENR
 1.0d-8
.THRLEQ
 1.0d-8
.MXLRV
 800
.MAXRED
 800
.PRINT
  1
*CCCR
.AVERAGE
GAMMA_PAR            
LINEAR
.STATIC
.DCKERR
  1
0.01
.THGFRE
  1
0.01
.DISPCF
  2
**END OF DALTON INPUT
%EOF%
#######################################################################

 

#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >cc_rsp_gamma2.check
cat >>cc_rsp_gamma2.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# SCF, MP2 and CCSD energies:
CRIT1=`$GREP "Final * HF energy:" $log | $GREP "\--100.008919(8|9)." | wc -l`
CRIT2=`$GREP "Total SCF   energy:                  \-100.008919(8|9)." $log | wc -l`
CRIT3=`$GREP "Total MP2   energy:                  \-100.193662(5|6)." $log | wc -l`
CRIT4=`$GREP "Total CCSD  energy:                  \-100.1977909." $log | wc -l`
TEST[1]=`expr $CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4` 
CTRL[1]=6
ERROR[1]="ENERGIES NOT CORRECT"

# CCSD gamma dispersion coefficients
# ZDIPLEN    ZDIPLEN    ZDIPLEN    ZDIPLEN        0    105.32914       105.32914       105.32914       105.32914
#                                                 2    5756.5661       2878.2830       1918.8554       959.42768    
# gamma_{||}                                      0    26.650035       26.650035       26.650035       26.650035
#                                                 2    1778.6517       889.32586       592.88391       296.44195  
# gamma_0   26.650035
# A         5.5617554   
CRIT1=`$GREP "0    105\.3291.       105\.3291.       105\.3291.       105\.3291." $log | wc -l`
CRIT2=`$GREP "2    5756\.566.       2878\.283.       1918\.855.       959\.427(5|6|7)." $log | wc -l`
CRIT3=`$GREP "0    26\.65003.       26\.65003.       26\.65003.       26\.65003." $log | wc -l`
CRIT4=`$GREP "2    1778\.65(1|2).       889\.32(5|6)..       592\.88(3|4)..       296\.44(19|20)." $log | wc -l`
CRIT5=`$GREP "gamma_0   26\.65003." $log | wc -l`
CRIT6=`$GREP "A         5\.56175(5|6)." $log | wc -l`
TEST[2]=`expr $CRIT1 \+ $CRIT2 \+ $CRIT3 + $CRIT4 \+ $CRIT5 \+ $CRIT6`
CTRL[2]=6
ERROR[2]="CCSD GAMMA DISPERSION COEFFICIENTS NOT CORRECT"

# CCSD freq.-dep. hyperpolarizabilities:
# ZDIPLEN  0.0000   ZDIPLEN  0.0000   ZDIPLEN  0.0000   ZDIPLEN  0.0000     -105.32914
#         -0.0100            0.0000            0.0000            0.0100     -105.42514
#         -0.0300            0.0100            0.0100            0.0100     -105.90675             
# gamma_||     0.0000      0.0000      0.0000      0.0000    -26.650035
#             -0.0100      0.0000      0.0000      0.0100    -26.679703
#             -0.0300      0.0100      0.0100      0.0100    -26.828720             
CRIT1=`$GREP "ZDIPLEN (\-0| \-|  | 0)\.[ 0]+ZDIPLEN  ( |0)\.[ 0]+ZDIPLEN (\-0| \-|  | 0)\.[ 0]+ZDIPLEN (\-0| \-|  | 0)\.[ 0]+ \-105\.3291(3|4)" $log | wc -l`
CRIT2=`$GREP "( \-|\-0)\.0100[ ]* ( |0)\.0000[ ]* ( |0)\.0000[ ]* ( |0)\.0100     \-105\.4251" $log | wc -l`
CRIT3=`$GREP "( \-|\-0)\.0300[ ]* ( |0)\.0100[ ]* ( |0)\.0100[ ]* ( |0)\.0100     \-105\.9067" $log | wc -l`
CRIT4=`$GREP "gamma_\|\| * (\-0|\-| |0)\.0000 * (\-0|\-| |0)\.0000 * (\-0|\-| |0)\.0000 * (\-0|\-| |0)\.0000 * \-26\.6500" $log | wc -l`
CRIT5=`$GREP "( \-|\-0)\.0100[ ]* ( |0)\.0000[ ]* ( |0)\.0000[ ]* ( |0)\.0100    \-26\.6797" $log | wc -l`
CRIT6=`$GREP "( \-|\-0)\.0300[ ]* ( |0)\.0100[ ]* ( |0)\.0100[ ]* ( |0)\.0100    \-26\.8287" $log | wc -l`
TEST[3]=`expr $CRIT1 \+ $CRIT2 \+ $CRIT3 + $CRIT4 \+ $CRIT5 \+ $CRIT6`
CTRL[3]=6
ERROR[3]="CCSD 2. HYPERPOLARIZABILITIES NOT CORRECT"


PASSED=1
for i in 1 2 3
do
   if [ ${TEST[i]} -lt ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi                
%EOF%
#######################################################################
