#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > choles_b3lyp_polar.info << '%EOF%'
   choles_b3lyp_polar
    ---------------
   Molecule:         HCN
   Wave Function:    B3LYP / aug-cc-pVDZ
   Test Purpose:     Cholesky B3LYP energy and polarizability
%EOF%

#######################################################################
#  INTEGRAL INPUT
#######################################################################
cat > choles_b3lyp_polar.mol << '%EOF%'
BASIS 
aug-cc-pVDZ
HCN 
aug-cc-pVDZ basis
    3    
        1.    1    
H   0.3   0.0    -1.0 
        7.    1    
N   0.3   0.0     1.5
        6.    1    
C   0.0   0.0     0.0
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > choles_b3lyp_polar.dal << '%EOF%'
**DALTON INPUT
.RUN PROPERTIES
.CHOLES
**CHOLES
.REDUCE
.SPANDI
  1.0d-3
.THRCOM
 1.0D-8
**WAVE FUNCTIONS
.DFT
 B3LYP
*SCF INP
.THRESH
 1.0D-8
**PROPERTIES
.POLARI
**END OF DALTON INPUT
%EOF%

#######################################################################



#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL > choles_b3lyp_polar.check
cat >> choles_b3lyp_polar.check << '%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# B3LYP energy
CRIT1=`$GREP "Final * DFT energy: * -92\.0988233" $log | wc -l`
TEST[1]=$CRIT1
CTRL[1]=1
ERROR[1]="B3LYP ENERGY NOT CORRECT"

# Dipole moment
CRIT1=`$GREP  "( |0)\.8784" $log | wc -l`
CRIT2=`$GREP  "( -|-0)\.87553" $log | wc -l`
CRIT3=`$GREP  "( -|-0)\.07136" $log | wc -l`
TEST[2]=`expr $CRIT1  \+ $CRIT2  \+ $CRIT3`
CTRL[2]=3
ERROR[2]="DIPOLE MOMENT NOT CORRECT"

# Polarizability
CRIT1=`$GREP Ex $log | $GREP "11.7238" | $GREP "( \-|-0).5222"  | $GREP "( |0).000000" | wc -l`
CRIT2=`$GREP Ey $log | $GREP "( \-|-0).5222" | $GREP "9.3365"  | $GREP "( |0).000000" | wc -l`
CRIT3=`$GREP Ez $log | $GREP "( |0).000000" | $GREP "( |0).000000"  | $GREP "8.5125" | wc -l`

TEST[3]=`expr $CRIT1  \+ $CRIT2  \+ $CRIT3`

CTRL[3]=3
ERROR[3]="POLARIZABILTY NOT CORRECT"


PASSED=1
for i in 1 2 3
do
   if [ ${TEST[i]} -lt ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
