#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > choles_hf_magnet.info << '%EOF%'
   choles_hf_magnet
    ---------------
   Molecule:         HCP
   Wave Function:    HF / Turbomole-TZP
   Test Purpose:     Cholesky HF energy and London magnetizability
%EOF%

#######################################################################
#  INTEGRAL INPUT
#######################################################################
cat > choles_hf_magnet.mol << '%EOF%'
BASIS
Turbomole-TZP
HCP Turbomole-TZP
......
    3  0           a  0.10E-14
        6.    1
C         0.0000000        0.00000000         0.000000
        1.    1
H         0.0000000        0.00000000        -1.0686323668
       15.    1
P         0.0000000        0.00000000         1.5421482850
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > choles_hf_magnet.dal << '%EOF%'
**DALTON INPUT
.RUN PROPERTIES
.CHOLES
**CHOLES
.REDUCE
.SPANDI
  1.0d-3
!.RSTDIA
!.RSTCHO
.THRCOM
 1.0D-8
**WAVE FUNCTIONS
.HF
**PROPERTIES
.MAGNET
**END OF DALTON INPUT
%EOF%

#######################################################################



#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL > choles_hf_magnet.check
cat >> choles_hf_magnet.check << '%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# HF energy
CRIT1=`$GREP "Final * HF energy: * -379\.1390408" $log | wc -l`
TEST[1]=$CRIT1
CTRL[1]=1
ERROR[1]="HF ENERGY NOT CORRECT"

# Dipole moment
CRIT1=`$GREP  "( -|-0)\.15588" $log | wc -l`
TEST[2]=$CRIT1
CTRL[2]=1
ERROR[2]="DIPOLE MOMENT NOT CORRECT"

# Magnetizabilities
CRIT1=`$GREP "Isotropic magnetizability\: * \-6\.48(47|48|49|50|51) " $log | wc -l`
CRIT2=`$GREP "Diamagnetic contribution\: * \-15\.735. " $log | wc -l`
CRIT3=`$GREP "Paramagnetic contribution\: * 9\.250. " $log | wc -l`
CRIT4=`$GREP "Anisotropy\: * \-1\.537. " $log | wc -l`

TEST[3]=`expr $CRIT1  \+ $CRIT2  \+ $CRIT3  \+ $CRIT4`

CTRL[3]=4
ERROR[3]="MAGNETIZABILITIES NOT CORRECT"


PASSED=1
for i in 1 2 3
do
   if [ ${TEST[i]} -lt ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
