#!/bin/sh

info="
   dft_qr_sym
   ------------------
   Molecule:         H2O
   Wave Functions:   DFT B3LYP / STO-3G
   Test Purpose:     DFT B3LYP hyperpolarizability test w/ symmetry.
"

molecule="BASIS
STO-3G
Water
STO-3G basis
    2    2  X  Z
        8.    1
O      .0000   -.2249  0.0000000000
        1.    1
H     1.4523    .8996   .0000000000
"

dalton="**DALTON INPUT
.RUN RESPONSE
.DIRECT
**INTEGRAL
.NOSUP
**WAVE FUNCTIONS
.DFT
 B3LYP
*SCF INPUT
.THRESHOLD
1e-12
*DFT INPUT
.GRID TYPE
LMG BLOCK
**RESPONSE
*QUADRATIC
.DIPLEN
.THCLR
1e-8
.FREQUENCIES
2
0 0.1
*END OF INPUT
"

test="
check_scf_energy DFT -75.278542863993 1e-12
check_hyperpolarizabilities 0.0 0.0 'Y;Y,Y' -4.28172472  1e-6
check_hyperpolarizabilities 0.1 0.0 'Y;Y,Y' -4.50854967  1e-6
check_hyperpolarizabilities 0.1 0.1 'Y;Y,Y' -5.03690753  1e-6
check_hyperpolarizabilities 0.0 0.0 'X;X,Y' -5.87935948  1e-6
check_hyperpolarizabilities 0.1 0.0 'X;X,Y' -6.06651683  1e-6
check_hyperpolarizabilities 0.0 0.1 'X;X,Y' -6.06942829  1e-6
check_hyperpolarizabilities 0.1 0.1 'X;X,Y' -6.47546566  1e-6
check_hyperpolarizabilities 0.0 0.0 'Z;Z,Y'  0.12917490  1e-6
check_hyperpolarizabilities 0.1 0.0 'Z;Z,Y'  0.12925650  1e-6
check_hyperpolarizabilities 0.0 0.1 'Z;Z,Y'  0.14390826  1e-6
check_hyperpolarizabilities 0.1 0.1 'Z;Z,Y'  0.14708422  1e-6
check_hyperpolarizabilities 0.1 0.0 'Y;X,X' -6.06942829  1e-6
check_hyperpolarizabilities 0.1 0.1 'Y;X,X' -6.50306813  1e-6
check_hyperpolarizabilities 0.1 0.0 'Y;Z,Z'  0.14390826  1e-6
check_hyperpolarizabilities 0.1 0.1 'Y;Z,Z'  0.19435677  1e-6
"

. ./functions || { echo "'functions' library not found." ; exit 1; }
check_gen_input "$0" "$info" "$molecule" "$dalton" "$test"
