#!/bin/sh


info='
   dft_optimize_sym
   ----------------
   Molecule:         H2O
   Wave Function:    DFT B3LYP / 6-31G*
   Test Purpose:     DFT B3LYP geometry optimization w/symmetry
'

molecule='BASIS
6-31G*
H2O
Symmetry
    2    
        8.    1        
O     0.0  0.0000000000 0.0
        1.    2    
H     1.430    0.0  0.8
H    -1.430    0.0  0.8
'

dalton='**DALTON INPUT
.OPTIMIZE
**WAVE FUNCTIONS
.DFT
 B3LYPGauss
**END OF INPUT
'

test='
check_scf_energy DFT -76.342046236607 1e-12

check_mol_gradient 1 "O     " 0.0  0.0           0.164201559 1e-5
check_mol_gradient 1 "H    1" 0.0 -0.1044292794 -0.082105466 1e-5
check_mol_gradient 1 "H    2" 0.0  0.1044292794 -0.082105466 1e-5
check_final_geometry "O     " 0  0      -0.30895       1e-5
check_final_geometry "H    1" 0  1.44138 0.82017       1e-5
check_final_geometry "H    2" 0 -1.44138 0.82017       1e-5

#check_optimization_step 0
#check_optimization_step 1

# Final energy
check_final_energy -76.369896 1e-10
'

. ./functions || { echo "'functions' library not found." ; exit 1; }

check_gen_input "$0" "$info" "$molecule" "$dalton" "$test"
