#!/bin/sh
info='
   dft_optimize_nosym
   ------------------
   Molecule:         H2O
   Wave Function:    DFT B3LYP / 6-31G*
   Test Purpose:     DFT B3LYP geometry optimization w/o symmetry
'

molecule='BASIS
6-31G*
H2O
No symmetry
    2    0
        8.    1        
O     0.0  0.0000000000 0.0
        1.    2    
H1    1.430    0.0  0.8
H2   -1.430    0.0  0.8
'

dalton='**DALTON INPUT
.OPTIMIZE
**WAVE FUNCTIONS
.DFT
 B3LYP
**END OF INPUT
'

test='
check_scf_energy DFT  -76.342046237254 1e-12

check_mol_gradient 1  "O     "   0.0000000000 0.0   0.1642078154 1e-5
check_mol_gradient 1  "H1    "  -0.1044292329 0.0  -0.0821055362 1e-5
check_mol_gradient 1  "H2    "   0.1044292329 0.0  -0.0821055362 1e-5

# Final geometry
check_final_geometry "O     "  0           0 -0.2194230514 1e-6
check_final_geometry "H1    "  1.441383715 0  0.9097115257 1e-6
check_final_geometry "H2    " -1.441383715 0  0.9097115257 1e-6

# Optimization steps
#check_optimization_step 0
#check_optimization_step 1

# Final energy
check_final_energy -76.369896 1e-7
'

. ./functions || { echo "'functions' library not found." ; exit 1; }
check_gen_input "$0" "$info" "$molecule" "$dalton" "$test"
