#!/bin/sh

. ./functions || { echo "'functions' library not found." ; exit 1; }

info="
   dft_qr_nosym
   ------------------
   Molecule:         H2O
   Wave Functions:   DFT LDA / aug-cc-pVDZ
   Test Purpose:     DFT LDA hyperpolarizability test w/o symmetry.
"

molecule="BASIS
aug-cc-pVDZ
Water
aug-cc-pVDZ basis
    2    0  X  Z
        8.    1
O      .0000   -.2249  0.0000000000
        1.    2
H    -1.4523    .8996   .0000000000
H     1.4523    .8996   .0000000000
"

dalton="**DALTON INPUT
.RUN RESPONSE
.DIRECT
**INTEGRAL
.NOSUP
**WAVE FUNCTIONS
.DFT
 LDA
*SCF INPUT
.THRESHOLD
1e-12
*DFT INPUT
.GRID TYPE
GC2 SSF
.RADINT
1e-10
**RESPONSE
*QUADRATIC
.DIPLEN
.THCLR
1e-8
.BFREQ
2
0 0.1
*END OF INPUT
"

test="
check_scf_energy DFT -75.881285947058 1e-10
check_hyperpolarizabilities 0.0 0.0 'X;Y,X' -20.11107907 1e-6
check_hyperpolarizabilities 0.0 0.0 'Y;X,X' -20.31063082 1e-6
check_hyperpolarizabilities 0.0 0.0 'Y;Y,Y'  -9.01605221 1e-6
check_hyperpolarizabilities 0.0 0.0 'Z;Z,Y'  -4.19045020 1e-6
check_hyperpolarizabilities 0.1 0.0 'X;X,Y' -22.47955542 1e-6
check_hyperpolarizabilities 0.1 0.0 'X;Y,X' -22.84664605 1e-6
check_hyperpolarizabilities 0.1 0.0 'Y;X,X' -23.12729758 1e-6
check_hyperpolarizabilities 0.1 0.0 'Y;Y,Y' -11.44896342 1e-6
check_hyperpolarizabilities 0.1 0.0 'Z;Y,Z'  -4.94277490 1e-6
check_hyperpolarizabilities 0.1 0.0 'Z;Z,Y' -12.86866510 1e-6
"

check_gen_input "$0" "$info" "$molecule" "$dalton" "$test"

