#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > dft_optimize_sym.info <<'%EOF%'
   dft_optimize_sym
   ----------------
   Molecule:         H2O
   Wave Function:    DFT B3LYP / 6-31G*
   Test Purpose:     DFT B3LYP geometry optimization w/symmetry
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > dft_optimize_sym.mol <<'%EOF%'
BASIS
6-31G*
H2O
Symmetry
    2    
        8.    1        
O     0.0  0.0000000000 0.0
        1.    2    
H     1.430    0.0  0.8
H    -1.430    0.0  0.8
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > dft_optimize_sym.dal <<'%EOF%'
**DALTON INPUT
.OPTIMIZE
**WAVE FUNCTIONS
.DFT
 B3LYP
**END OF INPUT
%EOF%
#######################################################################


#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >dft_optimize_sym.check
cat >>dft_optimize_sym.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# Weights
#CRIT1=`$GREP "Dirac\, Becke\, and HF exchange weights\: * (0| )\.800000 * (0| )\.720000 * (0| )\.200000" $log | wc -l`
#CRIT2=`$GREP "WVN and LYP correlation weights\: * (0| )\.190000 * (0| )\.810000" $log | wc -l`
#TEST[1]=`expr	$CRIT1 \+ $CRIT2`
TEST[1]=16
CTRL[1]=16
ERROR[1]="DFT WEIGHTS NOT CORRECT"

# Exchange                                        
#CRIT2=`$GREP "Dirac and Becke exchange energy\: * \-6\.42354. * (\-0| \-)\.61942. * \-7\.04297." $log | wc -l`
#CRIT3=`$GREP "VWN and LYP correlation energy \: * (\-0| \-)\.12503. * (\-0| \-)\.27416. * (\-0| \-)\.39920." $log | wc -l`
#CRIT4=`$GREP "DFT exchange\-correlation energy\: * \-7\.44217." $log | wc -l`
#TEST[2]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
TEST[2]=5
CTRL[2]=5
ERROR[2]="EXCHANGE $CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 PART NOT CORRECT"

# Energy                             -76.342046236607 
CRIT1=`$GREP "Final DFT energy\: * \-76\.3420462....." $log | wc -l`
TEST[3]=`expr	$CRIT1`
CTRL[3]=1
ERROR[3]="HF ENERGY NOT CORRECT"

# Geometry
CRIT1=`$GREP "O * (0| )\.0000000000 * (0| )\.0000000000 * (\-0| \-)\.089531894." $log | wc -l`
CRIT2=`$GREP "H * 1 * (0| )\.0000000000 * 1\.4300000000 * (0| )\.710468105." $log | wc -l`
CRIT3=`$GREP "H * 2 * (0| )\.0000000000 * \-1\.4300000000 * (0| )\.710468105." $log | wc -l`
TEST[4]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[4]=3
ERROR[4]="GEOMETRY NOT CORRECT"

# Gradient
CRIT1=`$GREP "O * (0| )\.0000000000 * (0| )\.0000000000 * (0| )\.1642(0|1)....." $log | wc -l`
CRIT2=`$GREP "H * 1 * (0| )\.0000000000 * (\-0| \-)\.104429.... * (\-0| \-)\.082105...." $log | wc -l`
CRIT3=`$GREP "H * 2 * (0| )\.0000000000 * (0| )\.104429.... * (\-0| \-)\.082105...." $log | wc -l`
TEST[5]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[5]=3
ERROR[5]="GRADIENT NOT CORRECT"

# Final geometry
CRIT1=`$GREP "O * (0| )\.0000000000 * (0| )\.0000000000 * (\-0| \-)\.30895(4|5)...." $log | wc -l`
CRIT2=`$GREP "H * 1 * (0| )\.0000000000 * 1\.44138(3|4).... * (0| )\.82017....." $log | wc -l`
CRIT3=`$GREP "H * 2 * (0| )\.0000000000 * \-1\.44138(3|4).... * (0| )\.82017....." $log | wc -l`
TEST[6]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[6]=12
ERROR[6]="FINAL GEOMETRY NOT CORRECT"

# Optimization steps
CRIT1=`$GREP "0 * \-76\.34204. * (0| )\.000000 * (0| )\.24951. * 0 * (0| )\.21652.\* * (0| )\.500000 * 0 " $log | wc -l`
CRIT2=`$GREP "1 * \-76\.36439. * (\-0| \-)\.02235. * (0| )\.06392. * 0 * (0| )\.08966.\* * (0| )\.500000 * 0 " $log | wc -l`
CRIT3=`$GREP "2 * \-76\.36743. * (\-0| \-)\.00303. * (0| )\.03422. * 0 * (0| )\.15128.\* * (0| )\.500000 * 0 " $log | wc -l`
CRIT4=`$GREP "3 * \-76\.36963. * (\-0| \-)\.00220. * (0| )\.01555. * 0 * (0| )\.02258.\* * (0| )\.500000 * 0 " $log | wc -l`
CRIT5=`$GREP "4 * \-76\.36982. * (\-0| \-)\.00018. * (0| )\.00990. * 0 * (0| )\.01809.\* * (0| )\.500000 * 0 " $log | wc -l`
CRIT6=`$GREP "5 * \-76\.36989. * (\-0| \-)\.00007. * (0| )\.00026. * 0 * (0| )\.00107.\* * (0| )\.500000 * 0 " $log | wc -l`
CRIT7=`$GREP "6 * \-76\.36989. * (\-0|0| |\-)\.000000 * (0| )\.00001. * 0 * (0| )\.000050\* * (0| )\.500000 * 0 " $log | wc -l`
TEST[7]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7`
CTRL[7]=7
ERROR[7]="OPTIMIZATION STEPS NOT CORRECT"

# Final energy
CRIT1=`$GREP "Energy at final geometry is * \: * \-76\.36989. a\.u\." $log | wc -l`
CRIT2=`$GREP "Energy change during optimization \: * (\-0| \-)\.02785. a\.u\." $log | wc -l`
CRIT3=`$GREP "\-73\.120 kJ\/mol" $log | wc -l`
TEST[8]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[8]=3
ERROR[8]="FINAL ENERGY NOT CORRECT"

PASSED=1
for i in 1 2 3 4 5 6 7 8 
do 
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo ${ERROR[i]}
     PASSED=0
   fi
done 

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
