#!/bin/sh

info='
   dft_lb94
   --------
   Molecule:         Ne
   Wave Function:    DFT LB94 / aug-cc-pVDZ
   Test Purpose:     LB94 functional test.
'

molecule='BASIS
aug-cc-pVTZ
CO2 cc-pVTZ or AhlrichsVDZ
--------
    1    3  X  Y  Z
       18.    1
He    .0000     .0000     .0000
'

dalton='**DALTON
.RUN PROPERTIES
**WAVE FUNCTIONS
.DFT
 lb94
*DFT INPUT
.RADINT
1e-7
*SCF INPUT
.NOQCSCF
.SHIFT
-0.3
**END OF 
'

test='
check_scf_energy DFT  -525.926546735059 1e-8
'

. ./functions || { echo "'functions' library not found." ; exit 1; }
check_gen_input "$0" "$info" "$molecule" "$dalton" "$test"
