#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -e /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -e /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > dft_optimize_nosym.info <<'%EOF%'
   dft_optimize_nosym
   ------------------
   Molecule:         H2O
   Wave Function:    DFT B3LYP / 6-31G*
   Test Purpose:     DFT B3LYP geometry optimization w/o symmetry
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > dft_optimize_nosym.mol <<'%EOF%'
BASIS
6-31G*
H2O
No symmetry
    2    0
        8.    1        
O     0.0  0.0000000000 0.0
        1.    2    
H1    1.430    0.0  0.8
H2   -1.430    0.0  0.8
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > dft_optimize_nosym.dal <<'%EOF%'
**DALTON INPUT
.OPTIMIZE
**INTEGRALS
.NOSUP
**WAVE FUNCTIONS
.HF
*HF INPUT
.B3LYP
*ORBITAL
.NOSUPSYM
*AUXILLIAR
.NOSUPMAT
*END OF INPUT
%EOF%
#######################################################################


#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >dft_optimize_nosym.check
cat >>dft_optimize_nosym.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# Weights
CRIT1=`$GREP "Dirac\, Becke\, and HF exchange weights\: * (0| )\.800000 * (0| )\.720000 * (0| )\.200000" $log | wc -l`
CRIT2=`$GREP "WVN and LYP correlation weights\: * (0| )\.190000 * (0| )\.810000" $log | wc -l`
TEST[1]=`expr	$CRIT1 \+ $CRIT2`
CTRL[1]=16
ERROR[1]="DFT WEIGHTS NOT CORRECT"

# Exchange    Number of electrons/abscissas:     10.0000002      0.15E-06         58980
CRIT1=`$GREP "Number of electrons\/abscissas\: *10\.000000. " $log | wc -l`
CRIT2=`$GREP "Dirac and Becke exchange energy\: * \-6\.42354. * (\-0| \-)\.61942. * \-7\.04297." $log | wc -l`
CRIT3=`$GREP "VWN and LYP correlation energy \: * (\-0| \-)\.12503. * (\-0| \-)\.27416. * (\-0| \-)\.39920." $log | wc -l`
CRIT4=`$GREP "DFT exchange\-correlation energy\: * \-7\.44217." $log | wc -l`
TEST[2]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
CTRL[2]=63
ERROR[2]="EXCHANGE PART NOT CORRECT"

# Energy     Final    HF energy:      -76.342046237254
CRIT1=`$GREP "Final * HF energy\: * \-76\.3420462....." $log | wc -l`
TEST[3]=`expr	$CRIT1`
CTRL[3]=1
ERROR[3]="HF ENERGY NOT CORRECT"

# Geometry
CRIT1=`$GREP "O * (0| )\.0000000000 * (0| )\.0000000000 * (0| )\.0000000000" $log | wc -l`
CRIT2=`$GREP "H1 * 1\.4300000000 * (0| )\.0000000000 * (0| )\.8000000000" $log | wc -l`
CRIT3=`$GREP "H2 * \-1\.4300000000 * (0| )\.0000000000 * (0| )\.8000000000" $log | wc -l`
TEST[4]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[4]=3
ERROR[4]="GEOMETRY NOT CORRECT"

# Gradient
# O          0.0000000000            0.0000000000            0.1642104624
# H1        -0.1044293602            0.0000000000           -0.0821055431
# H2         0.1044293602            0.0000000000           -0.0821055431
CRIT1=`$GREP "O * -?0?\.0000000000 * -?0?\.0000000000 * 0?\.164210...." $log | wc -l`
CRIT2=`$GREP "H1 * -0?\.1044293... * -?0?\.0000000000 * -0?\.082105...." $log | wc -l`
CRIT3=`$GREP "H2 * 0?\.1044293... * -?0?\.0000000000 * -0?\.082105...." $log | wc -l`
TEST[5]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[5]=3
ERROR[5]="GRADIENT NOT CORRECT"

# Final geometry
CRIT1=`$GREP "O * -?0?\.0000000000 * -?0?\.0000000000 * -0?\.219422..." $log | wc -l`
CRIT2=`$GREP "H1 * 1\.44138..... * -?0?\.0000000000 * (0| )\.909711...." $log | wc -l`
CRIT3=`$GREP "H2 * \-1\.44138..... * -?0?\.0000000000 * (0| )\.909711...." $log | wc -l`
TEST[6]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[6]=12
ERROR[6]="FINAL GEOMETRY NOT CORRECT"

# Optimization steps
CRIT1=`$GREP "0 * \-76\.342046 * (0| )\.000000 * (0| )\.249517 * 0 * (0| )\.216526\* * (0| )\.500000 * 0 " $log | wc -l`
CRIT2=`$GREP "1 * \-76\.364395 * (\-0| \-)\.022349 * (0| )\.063933 * 0 * (0| )\.089673\* * (0| )\.500000 * 0 " $log | wc -l`
CRIT3=`$GREP "2 * \-76\.367433 * (\-0| \-)\.003038 * (0| )\.034228 * 0 * (0| )\.151302\* * (0| )\.500000 * 0 " $log | wc -l`
CRIT4=`$GREP "3 * \-76\.369637 * (\-0| \-)\.002204 * (0| )\.015558 * 0 * (0| )\.022600\* * (0| )\.500000 * 0 " $log | wc -l`
CRIT5=`$GREP "4 * \-76\.369821 * (\-0| \-)\.000184 * (0| )\.009909 * 0 * (0| )\.018093\* * (0| )\.500000 * 0 " $log | wc -l`
CRIT6=`$GREP "5 * \-76\.369895 * (\-0| \-)\.000074 * (0| )\.000263 * 0 * (0| )\.001075\* * (0| )\.500000 * 0 " $log | wc -l`
CRIT7=`$GREP "6 * \-76\.369895 * (\-0|0| |\-)\.000000 * (0| )\.000012 * 0 * (0| )\.000050\* * (0| )\.500000 * 0 " $log | wc -l`
CRIT8=`$GREP "7 * \-76\.369895 * (\-0|0| |\-)\.000000 * (0| )\.000001 * 0 * (0| )\.000000\* * (0| )\.500000 * 0 " $log | wc -l`
TEST[7]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8`
CTRL[7]=8
ERROR[7]="OPTIMIZATION STEPS NOT CORRECT"

# Final energy
CRIT1=`$GREP "Energy at final geometry is * \: * \-76\.369895 a\.u\." $log | wc -l`
CRIT2=`$GREP "Energy change during optimization \: * (\-0| \-)\.027849 a\.u\." $log | wc -l`
CRIT3=`$GREP "\-73\.117 kJ\/mol" $log | wc -l`
TEST[8]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[8]=3
ERROR[8]="FINAL ENERGY NOT CORRECT"

PASSED=1
for i in 1 2 3 4 5 6 7 8 
do 
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo ${ERROR[i]}
     PASSED=0
   fi
done 

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM 
  exit 1
fi

%EOF%
#######################################################################
