#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > energy_douglaskroll.info <<'%EOF%'
   energy_douglaskroll
   -------------------
   Molecule:         N2
   Wave Function:    Hartree-Fock
   Test Purpose:     Check the construction and use of Douglas-Kroll
                     one-electron potential for the calculation of SCF
                     energies
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > energy_douglaskroll.mol <<'%EOF%'
BASIS
cc-pVDZ
N2 
 - used for Douglas-Kroll test
    1
        7.    2
N     0.0 0.0 1.01
N     0.0 0.0 -1.01
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > energy_douglaskroll.dal <<'%EOF%'
**DALTON INPUT
.RUN WAVE FUNCTION
.DOUGLAS-KROLL
**WAVE FUNCTION
.HF
**END OF INPUT
%EOF%
#######################################################################



#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >energy_douglaskroll.check
cat >>energy_douglaskroll.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi


# Hartree-Fock energy
CRIT1=`$GREP "Final * HF energy\: * \-109\.010031.....[0-9]" $log | wc -l`
TEST[1]=`expr	$CRIT1`
CTRL[1]=1
ERROR[1]="ENERGY NOT CORRECT"


PASSED=1
for i in 1
do
   if [ ${TEST[i]} -lt ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
