#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > geoopt_symbrk.info <<'%EOF%'
   geoopt_symbrk
   -------------
   Molecule:         H2O2
   Wave Function:    SCF / cc-pVDZ
   Test Purpose:     Geometry optimization (2nd order) with symmetry
                     breaking
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > geoopt_symbrk.mol <<'%EOF%'
BASIS
cc-pVDZ
Geometry optimization (2nd order) with automatic breaking of symmetry

Atomtypes=2 Angstrom Generators=2   X YZ
Atoms=1 Charge=8.0
O     0.0  0.73 0.0
Charge=1.0 Atoms=1
H     0.0 0.73 0.95
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > geoopt_symbrk.dal <<'%EOF%'
**DALTON INPUT
.OPTIMIZE
*OPTIMIZE
.2NDORDER
**WAVE FUNCTIONS
.HF
**PROPERTIES
.VIBANA
*END OF INPUT
%EOF%
#######################################################################



#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >geoopt_symbrk.check
cat >>geoopt_symbrk.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# Optimization setup
CRIT1=`$GREP "Default 2nd order method will be used\: * Newton method\." $log | wc -l`
CRIT2=`$GREP "Optimization will be performed in Cartesian coordinates\." $log | wc -l`
CRIT3=`$GREP "Trust region method will be used to control step \(default\)\." $log | wc -l`
CRIT4=`$GREP "2nd Order Geometry Optimization" $log | wc -l`
TEST[1]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
CTRL[1]=4
ERROR[1]="GEOMETRY OPTIMIZATION NOT SET UP CORRECTLY"

# Basis set
CRIT1=`$GREP "O * 2 * 8 * 26 * 14 * \[9s4p1d\|3s2p1d\]" $log | wc -l`
CRIT2=`$GREP "H * 2 * 1 * 7 * 5 * \[4s1p\|2s1p\]" $log | wc -l`
CRIT3=`$GREP "total\: * 4 * 18 * 66 * 38" $log | wc -l`
CRIT4=`$GREP "Spherical harmonic basis used\." $log | wc -l`
TEST[2]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
CTRL[2]=8
ERROR[2]="BASIS SET NOT READ CORRECTLY"

# Geometry
CRIT1=`$GREP "Coordinates are entered in Angstroms and converted to atomic units\." $log | wc -l`
CRIT2=`$GREP "1 * O * 1 * x * (\-0|\-|0| )\.0000000000" $log | wc -l`
CRIT3=`$GREP "2 * y * 1\.3795000778" $log | wc -l`
CRIT4=`$GREP "3 * z * (\-0|\-|0| )\.0000000000" $log | wc -l`
CRIT5=`$GREP "4 * O * 2 * x * (\-0|\-|0| )\.0000000000" $log | wc -l`
CRIT6=`$GREP "5 * y * \-1\.3795000778" $log | wc -l`
CRIT7=`$GREP "6 * z * (\-0|\-|0| )\.0000000000" $log | wc -l`
CRIT8=`$GREP "7 * H * 1 * x * (\-0|\-|0| )\.0000000000" $log | wc -l`
CRIT9=`$GREP "8 * y * 1\.3795000778" $log | wc -l`
CRIT10=`$GREP "9 * z * 1\.7952398272" $log | wc -l`
CRIT11=`$GREP "10 * H * 2 * x * (\-0|\-|0| )\.0000000000" $log | wc -l`
CRIT12=`$GREP "11 * y * \-1\.3795000778" $log | wc -l`
CRIT13=`$GREP "12 * z * \-1\.7952398272" $log | wc -l`
TEST[3]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10 \+ $CRIT11 \+ $CRIT12 \+ \
		$CRIT13`
CTRL[3]=13
ERROR[3]="GEOMETRY NOT READ CORRECTLY"

# Symmetry
CRIT1=`$GREP "Number of coordinates in each symmetry\: * 4 * 2 * 4 * 2" $log | wc -l`
CRIT2=`$GREP "Number of orbitals in each symmetry\: * 14 * 5 * 14 * 5" $log | wc -l`
TEST[4]=`expr	$CRIT1 \+ $CRIT2`
CTRL[4]=2
ERROR[4]="SYMMETRY NOT CORRECT"

# Initial energy
CRIT1=`$GREP "Final * HF energy\: * \-150\.7754934890[0-9][0-9]" $log | wc -l`
TEST[5]=`expr	$CRIT1`
CTRL[5]=1
ERROR[5]="INITIAL ENERGY NOT CORRECT"

# Initial gradient
CRIT1=`$GREP "O * y * (0| )\.0724025..[0-9]" $log | wc -l`
CRIT2=`$GREP "H * y * (\-0|\-)\.0545155..[0-9]" $log | wc -l`
CRIT3=`$GREP "H * z * (0| )\.00310(49|50)..[0-9]" $log | wc -l`
TEST[6]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[6]=3
ERROR[6]="INITIAL GRADIENT NOT CORRECT"

# Initial Hessian
CRIT1=`$GREP "O * y * 1\.13386[0-9]" $log | wc -l`
CRIT2=`$GREP "O * z * (0| )\.15633[0-9] * 1\.53453[0-9]" $log | wc -l`
CRIT3=`$GREP "H * y * (0| )\.03686[0-9] * (0| )\.21483[0-9] * (0| )\.19502[0-9]" $log | wc -l`
CRIT4=`$GREP "H * z * (\-0|\-)\.05467[0-9] * \-1\.20246[0-9] * (0| )\.0367(1|2)[0-9] * 1\.21073[0-9]" $log | wc -l`
CRIT5=`$GREP "O * x * (0| )\.00055[0-9]" $log | wc -l`
CRIT6=`$GREP "H * x * (\-0|\-)\.00055[0-9] * (0| )\.00055[0-9]" $log | wc -l`
CRIT7=`$GREP "O * y * (0| )\.14224[0-9]" $log | wc -l`
CRIT8=`$GREP "O * z * (0| )\.03460[0-9] * 1\.20889[0-9]" $log | wc -l`
CRIT9=`$GREP "H * y * (\-0|\-)\.14224[0-9] * (\-0|\-)\.03460[0-9] * (0| )\.14224[0-9]" $log | wc -l`
CRIT10=`$GREP "H * z * (\-0|\-)\.03460[0-9] * \-1\.20889[0-9] * (0| )\.03460[0-9] * 1\.20889[0-9]" $log | wc -l`
CRIT11=`$GREP "O * x * (0| )\.09373[0-9]" $log | wc -l`
CRIT12=`$GREP "H * x * (\-0|\-)\.04124[0-9] * (0| )\.00173[0-9]" $log | wc -l`
TEST[7]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10 \+ $CRIT11 \+ $CRIT12`
CTRL[7]=12
ERROR[7]="INITIAL HESSIAN NOT CORRECT"

# Initial step
CRIT1=`$GREP "O * 1 * (0| )\.0000000000 * 1\.299982...[0-9] * (0| )\.110122...[0-9]" $log | wc -l`
CRIT2=`$GREP "O * 2 * (0| )\.0000000000 * \-1\.299982...[0-9] * (\-0|\-)\.110122...[0-9]" $log | wc -l`
CRIT3=`$GREP "H * 1 * (0| )\.0000000000 * 1\.539243...[0-9] * 1\.893003...[0-9]" $log | wc -l`
CRIT4=`$GREP "H * 2 * (0| )\.0000000000 * \-1\.539243...[0-9] * \-1\.893003...[0-9]" $log | wc -l`
TEST[8]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
CTRL[8]=4
ERROR[8]="INITIAL STEP NOT CORRECT"

# Second iteration
CRIT1=`$GREP "Energy at this geometry is * \: * \-150\.784901" $log | wc -l`
CRIT2=`$GREP "Norm of gradient * \: * (0| )\.02745[0-9]" $log | wc -l`
CRIT3=`$GREP "Norm of step * \: * (0| )\.04548[0-9]" $log | wc -l`
TEST[9]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[9]=3
ERROR[9]="SECOND ITERATION NOT CORRECT"

# Third iteration
CRIT1=`$GREP "Energy at this geometry is * \: * \-150\.785410" $log | wc -l`
CRIT2=`$GREP "Norm of gradient * \: * (0| )\.00143[0-9]" $log | wc -l`
CRIT3=`$GREP "Norm of step * \: * (0| )\.00180[0-9]" $log | wc -l`
TEST[10]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[10]=3
ERROR[10]="THIRD ITERATION NOT CORRECT"

# Breaking of symmetry
CRIT1=`$GREP "Due to non\-zero index of total Hessian\, symmetry \# * 1" $log | wc -l`
CRIT2=`$GREP "has to be broken to minimize energy\!" $log | wc -l`
TEST[11]=`expr	$CRIT1 \+ $CRIT2`
CTRL[11]=2
ERROR[11]="SYMMETRY NOT BROKEN CORRECTLY"

# Symmetry determination
CRIT1=`$GREP "Symmetry class found\: C\(2\)" $log | wc -l`
CRIT2=`$GREP "The following element was found\: * XY" $log | wc -l`
CRIT3=`$GREP "Full group is\: * C\(2\)" $log | wc -l`
CRIT4=`$GREP "Represented as\: C2 " $log | wc -l`
TEST[12]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
CTRL[12]=4
ERROR[12]="SYMMETRY NOT DETERMINED CORRECT"

# New geometry
CRIT1=`$GREP "Total number of coordinates\: * 12" $log | wc -l`
CRIT2=`$GREP "1 * O * 1 * x * 1\.3231824[0-1][0-9][0-9]" $log | wc -l`
CRIT3=`$GREP "2 * y * (\-0|\-|0| )\.0000000000" $log | wc -l`
CRIT4=`$GREP "3 * z * (\-0|\-)\.029637135[0-9]" $log | wc -l`
CRIT5=`$GREP "4 * O * 2 * x * \-1\.3231824[0-1][0-9][0-9]" $log | wc -l`
CRIT6=`$GREP "5 * y * (\-0|\-|0| )\.0000000000" $log | wc -l`
CRIT7=`$GREP "6 * z * (\-0|\-)\.029637135[0-9]" $log | wc -l`
CRIT8=`$GREP "7 * H * 1 * x * 1\.6580685[7-9][0-9][0-9]" $log | wc -l`
CRIT9=`$GREP "8 * y * 1\.758533(29|30)[0-9][0-9]" $log | wc -l`
CRIT10=`$GREP "9 * z * (0| )\.470362865[0-9]" $log | wc -l`
CRIT11=`$GREP "10 * H * 2 * x * \-1\.6580685[7-9][0-9][0-9]" $log | wc -l`
CRIT12=`$GREP "11 * y * \-1\.758533(29|30)[0-9][0-9]" $log | wc -l`
CRIT13=`$GREP "12 * z * (0| )\.470362865[0-9]" $log | wc -l`
TEST[13]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10 \+ $CRIT11 \+ $CRIT12 \+ \
		$CRIT13`
CTRL[13]=14
ERROR[13]="SYMMETRY-BROKEN GEOMETRY NOT CORRECT"

# Final energy
CRIT1=`$GREP "Final * HF energy\: * \-150\.783313671[6-7][0-9][0-9]" $log | wc -l`
TEST[14]=`expr	$CRIT1`
CTRL[14]=1
ERROR[14]="FINAL ENERGY NOT CORRECT"

# Final geometry
CRIT1=`$GREP "O * 1 * 1\.31202071[0-9][0-9] * (0| )\.09887206[0-9][0-9] * (\-0|\-)\.24963092[0-9][0-9]" $log | wc -l`
CRIT2=`$GREP "O * 2 * \-1\.31202071[0-9][0-9] * (\-0|\-)\.09887206[0-9][0-9] * (\-0|\-)\.24963092[0-9][0-9]" $log | wc -l`
CRIT3=`$GREP "H * 1 * 1\.5833081(8|9)[0-9][0-9] * 1\.6000987[3-4][0-9][0-9] * (0| )\.69035665[0-9][0-9]" $log | wc -l`
CRIT4=`$GREP "H * 2 * \-1\.5833081(8|9)[0-9][0-9] * \-1\.6000987[3-4][0-9][0-9] * (0| )\.69035665[0-9][0-9]" $log | wc -l`
TEST[15]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
CTRL[15]=16
ERROR[15]="FINAL GEOMETRY NOT CORRECT"

# Final iteration
CRIT1=`$GREP "Energy at this geometry is * \: * \-150\.786767" $log | wc -l`
CRIT2=`$GREP "Norm of gradient * \: * (0| )\.00000[0-9]" $log | wc -l`
CRIT3=`$GREP "Norm of step * \: * (0| )\.00003[0-9]" $log | wc -l`
TEST[16]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[16]=4
ERROR[16]="FINAL ITERATION NOT CORRECT"

# Vibrational frequencies
CRIT1=`$GREP "1 * A * 4117\.48 * (0| )\.01876[0-9] * 31\.68[0-9] * (0| )\.749[0-9]" $log | wc -l`
CRIT2=`$GREP "3 * A * 1612\.01 * (0| )\.00734[0-9] * (0| )\.34[0-9] * (0| )\.008[0-9]" $log | wc -l`
CRIT3=`$GREP "5 * A * 1132\.59 * (0| )\.00516[0-9] * 1\.71[0-9] * (0| )\.040[0-9]" $log | wc -l`
CRIT4=`$GREP "6 * A * 377\.87 * (0| )\.00172[0-9] * 213\.24[0-9] * 5\.046[0-9]" $log | wc -l`
CRIT5=`$GREP "2 * B * 4114\.80 * (0| )\.01874[0-9] * 109\.60[0-9] * 2\.593[0-9]" $log | wc -l`
CRIT6=`$GREP "4 * B * 1469\.94 * (0| )\.00669[0-9] * 101\.19[0-9] * 2\.394[0-9]" $log | wc -l`
TEST[17]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6`
CTRL[17]=6
ERROR[17]="VIBRATIONAL FREQUENCIES NOT CORRECT"

# Geometry optimization
CRIT1=`$GREP "Geometry converged in * 10( |  )iterations\!" $log | wc -l`
CRIT2=`$GREP "Please note that symmetry was broken during this optimization\." $log | wc -l`
CRIT3=`$GREP "Energy at final geometry is * \: * \-150\.786767 a\.u\." $log | wc -l`
CRIT4=`$GREP "Energy change during optimization \: * (\-0|\-)\.011273 a\.u\." $log | wc -l`
TEST[18]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
CTRL[18]=4
ERROR[18]="GEOMETRY NOT CONVERGED CORRECTLY"

PASSED=1
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo ${ERROR[i]}
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
