#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > geoopt_constrain1a.info <<'%EOF%'
   geoopt_constrain1a
   ------------------
   Molecule:         C2H6
   Wave Function:    N/A
   Test Purpose:     Demonstrates a run were nothing but determination of
                     redundant internal coordinates is performed. This is
                     needed to get the coordinate numbers required for
                     constraints
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > geoopt_constrain1a.mol <<'%EOF%'
BASIS
STO-3G
Determination of redundant internal coordinates

Atomtypes=2
Charge=6.0 Atoms=2
C     0.0000000000        0.0000000000        1.7547876282             *
C     0.0000000000        0.0000000000       -1.7547876282             *
Charge=1.0 Atoms=6
H     1.6808445513        0.9704360937        2.4445545504             *
H    -1.6808445513        0.9704360937        2.4445545504             *
H     0.0000000000       -1.9408721894        2.4445545504             *
H     1.6808445513       -0.9704360937       -2.4445545504             *
H    -1.6808445513       -0.9704360937       -2.4445545504             *
H     0.0000000000        1.9408721894       -2.4445545504             *
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > geoopt_constrain1a.dal <<'%EOF%'
**DALTON INPUT
.OPTIMIZE
*OPTIMIZE
.FINDRE
**WAVE FUNCTION
.HF
**END OF DALTON INPUT
%EOF%
#######################################################################



#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >geoopt_constrain1a.check
cat >>geoopt_constrain1a.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# Determination
CRIT1=`$GREP "Determination of redundant internal will be performed\." $log | wc -l`
CRIT2=`$GREP "No optimization will be done\, other keywords will be ignored\!\!\!\!\!" $log | wc -l`
TEST[1]=`expr	$CRIT1 \+ $CRIT2`
CTRL[1]=2
ERROR[1]="INTERNAL COORDINATE DETERMINATION NOT SET UP CORRECTLY"

# Symmetry
CRIT1=`$GREP "Symmetry class found\: D\(3d\)" $log | wc -l`
CRIT2=`$GREP "The following elements were found\: * Z * XY" $log | wc -l`
TEST[2]=`expr	$CRIT1 \+ $CRIT2`
CTRL[2]=2
ERROR[2]="SYMMETRY NOT CORRECT"

# Geometry
CRIT1=`$GREP "1 * 6\.00000000 * (0| )\.92859362 * (\-0|\-|0| )\.00000000 * (\-0|\-|0| )\.00000000" $log | wc -l`
CRIT2=`$GREP "2 * 6\.00000000 * (\-0|\-)\.92859362 * (\-0|\-|0| )\.00000000 * (\-0|\-|0| )\.00000000" $log | wc -l`
CRIT3=`$GREP "3 * 1\.00000000 * 1\.29360255 * 1\.02706529 * (\-0|\-|0| )\.00000000" $log | wc -l`
CRIT4=`$GREP "4 * 1\.00000000 * \-1\.29360255 * \-1\.02706529 * (\-0|\-|0| )\.00000000" $log | wc -l`
CRIT5=`$GREP "5 * 1\.00000000 * 1\.29360255 * (\-0| \-)\.51353266 * (0| )\.88946467" $log | wc -l`
CRIT6=`$GREP "6 * 1\.00000000 * 1\.29360255 * (\-0| \-)\.51353266 * (\-0| \-)\.88946467" $log | wc -l`
CRIT7=`$GREP "7 * 1\.00000000 * \-1\.29360255 * (0| )\.51353266 * (0| )\.88946467" $log | wc -l`
CRIT8=`$GREP "8 * 1\.00000000 * \-1\.29360255 * (0| )\.51353266 * (\-0| \-)\.88946467" $log | wc -l`
TEST[3]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8`
CTRL[3]=8
ERROR[3]="GEOMETRY NOT READ CORRECTLY"

# Bonds
CRIT1=`$GREP "1 * Regular bond * 1 * 2 * 1\.85719 Ang\." $log | wc -l`
CRIT2=`$GREP "2 * Regular bond * 1 * 3 * 1\.09000 Ang\." $log | wc -l`
CRIT3=`$GREP "3 * Regular bond * 1 * 5 * 1\.09000 Ang\." $log | wc -l`
CRIT4=`$GREP "4 * Regular bond * 1 * 6 * 1\.09000 Ang\." $log | wc -l`
CRIT5=`$GREP "5 * Regular bond * 2 * 4 * 1\.09000 Ang\." $log | wc -l`
CRIT6=`$GREP "6 * Regular bond * 2 * 7 * 1\.09000 Ang\." $log | wc -l`
CRIT7=`$GREP "7 * Regular bond * 2 * 8 * 1\.09000 Ang\." $log | wc -l`
TEST[4]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7`
CTRL[4]=7
ERROR[4]="BONDS NOT DETERMINED CORRECTLY"

# Angles
CRIT1=`$GREP "14 * Regular angle * 2 * 1 * 3 * 109\.565 deg\." $log | wc -l`
CRIT2=`$GREP "15 * Regular angle * 2 * 1 * 5 * 109\.565 deg\." $log | wc -l`
CRIT3=`$GREP "16 * Regular angle * 2 * 1 * 6 * 109\.565 deg\." $log | wc -l`
CRIT4=`$GREP "17 * Regular angle * 3 * 1 * 5 * 109\.378 deg\." $log | wc -l`
CRIT5=`$GREP "18 * Regular angle * 3 * 1 * 6 * 109\.378 deg\." $log | wc -l`
CRIT6=`$GREP "19 * Regular angle * 5 * 1 * 6 * 109\.378 deg\." $log | wc -l`
CRIT7=`$GREP "20 * Regular angle * 1 * 2 * 4 * 109\.565 deg\." $log | wc -l`
CRIT8=`$GREP "21 * Regular angle * 1 * 2 * 7 * 109\.565 deg\." $log | wc -l`
CRIT9=`$GREP "22 * Regular angle * 1 * 2 * 8 * 109\.565 deg\." $log | wc -l`
CRIT10=`$GREP "23 * Regular angle * 4 * 2 * 7 * 109\.378 deg\." $log | wc -l`
CRIT11=`$GREP "24 * Regular angle * 4 * 2 * 8 * 109\.378 deg\." $log | wc -l`
CRIT12=`$GREP "25 * Regular angle * 7 * 2 * 8 * 109\.378 deg\." $log | wc -l`
TEST[5]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10 \+ $CRIT11 \+ $CRIT12`
CTRL[5]=12
ERROR[5]="ANGLES NOT DETERMINED CORRECTLY"

# Dihedral angles
CRIT1=`$GREP "26 * Dihedral angle * 3 * 1 * 2 * 4 * (\-| )180\.000 deg\." $log | wc -l`
CRIT2=`$GREP "27 * Dihedral angle * 3 * 1 * 2 * 7 * (\-| )60\.000 deg\." $log | wc -l`
CRIT3=`$GREP "28 * Dihedral angle * 3 * 1 * 2 * 8 * (\-| )60\.000 deg\." $log | wc -l`
CRIT4=`$GREP "29 * Dihedral angle * 4 * 2 * 1 * 5 * (\-| )60\.000 deg\." $log | wc -l`
CRIT5=`$GREP "30 * Dihedral angle * 4 * 2 * 1 * 6 * (\-| )60\.000 deg\." $log | wc -l`
CRIT6=`$GREP "31 * Dihedral angle * 5 * 1 * 2 * 7 * (\-| )60\.000 deg\." $log | wc -l`
CRIT7=`$GREP "32 * Dihedral angle * 5 * 1 * 2 * 8 * (\-| )180\.000 deg\." $log | wc -l`
CRIT8=`$GREP "33 * Dihedral angle * 6 * 1 * 2 * 7 * (\-| )180\.000 deg\." $log | wc -l`
CRIT9=`$GREP "34 * Dihedral angle * 6 * 1 * 2 * 8 * (\-| )60\.000 deg\." $log | wc -l`
TEST[6]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9`
CTRL[6]=9
ERROR[6]="DIHEDRAL ANGLES NOT DETERMINED CORRECTLY"

# Total number of coordinates
CRIT1=`$GREP "Total number of redundant internal coordinates\: * 34" $log | wc -l`
TEST[7]=`expr	$CRIT1`
CTRL[7]=1
ERROR[7]="TOTAL NUMBER OF INTERNAL COORDINATES NOT CORRECT"

# Other parts of Dalton
CRIT1=`$GREP "SIRIUS" $log | wc -l`
CRIT2=`$GREP "ABACUS" $log | wc -l`
TEST[8]=`expr	$CRIT1 \+ $CRIT2`
CTRL[8]=0
ERROR[8]="OTHER PARTS OF DALTON SHOULD NOT BE RUN"

PASSED=1
for i in 1 2 3 4 5 6 7 8
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo ${ERROR[i]}
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
