#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > geoopt_redintsad.info <<'%EOF%'
   geoopt_redintsad
   ----------------
   Molecule:         Acrolein
   Wave Function:    SCF / 3-21G
   Test Purpose:     Second order transition state optimization in redundant
                     internal coordinates. The partitioned rational function
                     method controls the steps and Baker's convergence
                     criteria are used
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > geoopt_redintsad.mol <<'%EOF%'
BASIS
3-21G
Locating the rotational transition state of acrolein

    3    0
        6.    3
C    -1.2039490098         .6299819763       -1.8443710751             *
C     1.2056120532         .0000000000        1.9839551839             *
C      .0666798969        -.9449729645        -.3221285864             *
        8.    1
O      .0000000000         .0000000000        3.9490688445             *
        1.    4
H    -2.0522570986        -.0738599558       -3.5620058833             *
H     3.1211832712         .7038419322        1.9619811778             *
H      .2424607776       -2.9181815653        -.8128813887             *
H    -1.3797298905        2.6031905771       -1.3536182728             *
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > geoopt_redintsad.dal <<'%EOF%'
**DALTON INPUT
.OPTIMIZE
*OPTIMIZE
.REDINT
.NEWTON
.SADDLE
.BAKER
.RF
**WAVE FUNCTION
.HF
**END OF DALTON INPUT
%EOF%
#######################################################################



#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >geoopt_redintsad.check
cat >>geoopt_redintsad.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# Geometry optimization
CRIT1=`$GREP "Saddle point optimization has been requested\." $log | wc -l`
CRIT2=`$GREP "2nd order Newton method will be used\." $log | wc -l`
CRIT3=`$GREP "Optimization will be performed in redundant internal coordinates\." $log | wc -l`
CRIT4=`$GREP "Partitioned rational function method will be used to control step\." $log | wc -l`
CRIT5=`$GREP "The eigenvector corresponding to the lowest eigenvalue is chosen" $log | wc -l`
CRIT6=`$GREP "as reaction mode \(default\)\." $log | wc -l`
CRIT7=`$GREP "Baker.s convergence criteria will be used\." $log | wc -l`
TEST[1]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7`
CTRL[1]=7
ERROR[1]="GEOMETRY OPTIMIZATION NOT SET UP CORRECTLY"

# Geometry
CRIT1=`$GREP "1 * x * \-1\.2039490098" $log | wc -l`
CRIT2=`$GREP "2 * y * (0| )\.6299819763" $log | wc -l`
CRIT3=`$GREP "3 * z * \-1\.8443710751" $log | wc -l`
CRIT4=`$GREP "4 * x * 1\.2056120532" $log | wc -l`
CRIT5=`$GREP "6 * z * 1\.9839551839" $log | wc -l`
CRIT6=`$GREP "7 * x * (0| )\.0666798969" $log | wc -l`
CRIT7=`$GREP "8 * y * (\-0|\-)\.9449729645" $log | wc -l`
CRIT8=`$GREP "9 * z * (\-0|\-)\.3221285864" $log | wc -l`
CRIT9=`$GREP "12 * z * 3\.9490688445" $log | wc -l`
CRIT10=`$GREP "13 * x * \-2\.0522570986" $log | wc -l`
CRIT11=`$GREP "14 * y * (\-0|\-)\.0738599558" $log | wc -l`
CRIT12=`$GREP "15 * z * \-3\.5620058833" $log | wc -l`
CRIT13=`$GREP "16 * x * 3\.1211832712" $log | wc -l`
CRIT14=`$GREP "17 * y * (0| )\.7038419322" $log | wc -l`
CRIT15=`$GREP "18 * z * 1\.9619811778" $log | wc -l`
CRIT16=`$GREP "19 * x * (0| )\.2424607776" $log | wc -l`
CRIT17=`$GREP "20 * y * \-2\.9181815653" $log | wc -l`
CRIT18=`$GREP "21 * z * (\-0|\-)\.8128813887" $log | wc -l`
CRIT19=`$GREP "22 * x * \-1\.3797298905" $log | wc -l`
CRIT20=`$GREP "23 * y * 2\.6031905771" $log | wc -l`
CRIT21=`$GREP "24 * z * \-1\.3536182728" $log | wc -l`
TEST[2]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10 \+ $CRIT11 \+ $CRIT12 \+ \
		$CRIT13 \+ $CRIT14 \+ $CRIT15 \+ $CRIT16 \+ $CRIT17 \+ $CRIT18 \+ \
		$CRIT19 \+ $CRIT20 \+ $CRIT21`
CTRL[2]=21
ERROR[2]="GEOMETRY NOT READ CORRECTLY"

# Initial energy
CRIT1=`$GREP "Final * HF energy\: * \-189\.67124158034[0-9]" $log | wc -l`
TEST[3]=`expr	$CRIT1`
CTRL[3]=1
ERROR[3]="INITIAL ENERGY NOT CORRECT"

# Initial gradient
CRIT1=`$GREP "C * (\-0|\-)\.0143048..[0-9] * (0| )\.0227127..[0-9] * (\-0|\-)\.0148754..[0-9]" $log | wc -l`
CRIT2=`$GREP "C * (0| )\.0118273..[0-9] * (0| )\.003797(0|1)..[0-9] * (\-0|\-)\.0396929..[0-9]" $log | wc -l`
CRIT3=`$GREP "C * (0| )\.0155055..[0-9] * (\-0|\-)\.0155993..[0-9] * (0| )\.0504785..[0-9]" $log | wc -l`
CRIT4=`$GREP "O * (\-0|\-)\.0125016..[0-9] * (\-0|\-)\.0047796..[0-9] * (0| )\.001867(2|3)..[0-9]" $log | wc -l`
CRIT5=`$GREP "H * (0| )\.0002015..[0-9] * (\-0|\-)\.0068442..[0-9] * (\-0|\-)\.0047773..[0-9]" $log | wc -l`
CRIT6=`$GREP "H * (\-0|\-)\.0015739..[0-9] * (0| )\.0004363..[0-9] * (0| )\.0050888..[0-9]" $log | wc -l`
CRIT7=`$GREP "H * (\-0|\-)\.0013919..[0-9] * (\-0|\-)\.003771...[0-9] * (\-0|\-)\.0041250..[0-9]" $log | wc -l`
CRIT8=`$GREP "H * (0| )\.0022378..[0-9] * (0| )\.004048...[0-9] * (0| )\.0060361..[0-9]" $log | wc -l`
TEST[4]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8`
CTRL[4]=8
ERROR[4]="INITIAL GRADIENT NOT CORRECT"

# Initial Hessian
CRIT1=`$GREP "C * z * (0| )\.29116[0-9] * (\-0|\-)\.00113[0-9] * (0| )\.64976[0-9]" $log | wc -l`
CRIT2=`$GREP "C * x * (\-0|\-)\.00357[0-9] * (\-0|\-)\.00820[0-9] * (\-0|\-)\.02632[0-9] * (0| )\.73827[0-9]" $log | wc -l`
CRIT3=`$GREP "C * y * (0| )\.01150[0-9] * (0| )\.01576[0-9] * (0| )\.02684[0-9] * (0| )\.12782[0-9] * (0| )\.32052[0-9]" $log | wc -l`
CRIT4=`$GREP "C * z * (\-0|\-)\.01906[0-9] * (\-0|\-)\.00649[0-9] * (\-0|\-)\.02724[0-9] * (\-0|\-)\.19605[0-9] * (0| )\.06939[0-9] * (0| )\.91553[0-9]" $log | wc -l`
CRIT5=`$GREP "C * x * (\-0|\-)\.20744[0-9] * (0| )\.14082[0-9] * (\-0|\-)\.15540[0-9] * (\-0|\-)\.14308[0-9] * (\-0|\-)\.03275[0-9] * (\-0|\-)\.08086[0-9]" $log | wc -l`
CRIT6=`$GREP "C * y * (0| )\.14419[0-9] * (\-0|\-)\.30154[0-9] * (0| )\.15204[0-9] * (\-0|\-)\.02575[0-9] * (\-0|\-)\.13543[0-9] * (\-0|\-)\.04868[0-9]" $log | wc -l`
CRIT7=`$GREP "C * z * (\-0|\-)\.15473[0-9] * (0| )\.14997[0-9] * (\-0|\-)\.28061[0-9] * (\-0|\-)\.07231[0-9] * (\-0|\-)\.05913[0-9] * (\-0|\-)\.21529[0-9]" $log | wc -l`
CRIT8=`$GREP "O * x * (\-0|\-)\.00027[0-9] * (0| )\.00121[0-9] * (0| )\.00103[0-9] * (\-0|\-)\.30087[0-9] * (\-0|\-)\.01174[0-9] * (0| )\.31179[0-9]" $log | wc -l`
CRIT9=`$GREP "H * y * (\-0|\-)\.04215[0-9] * (\-0|\-)\.10800[0-9] * (\-0|\-)\.09397[0-9] * (0| )\.00519[0-9] * (\-0|\-)\.00277[0-9] * (\-0|\-)\.00080[0-9]" $log | wc -l`
CRIT10=`$GREP "H * z * (\-0|\-)\.00595[0-9] * (0| )\.02572[0-9] * (0| )\.01197[0-9] * (0| )\.00272[0-9] * (\-0|\-)\.02914[0-9] * (\-0|\-)\.00033[0-9]" $log | wc -l`
CRIT11=`$GREP "O * x * (0| )\.02319[0-9] * (\-0|\-)\.00153[0-9] * (\-0|\-)\.00802[0-9] * (0| )\.30011[0-9]" $log | wc -l`
CRIT12=`$GREP "H * y * (0| )\.01439[0-9] * (0| )\.01168[0-9] * (0| )\.02516[0-9] * (\-0|\-)\.00114[0-9] * (0| )\.00030[0-9] * (0| )\.00063[0-9]" $log | wc -l`
CRIT13=`$GREP "H * z * (\-0|\-)\.02651[0-9] * (\-0|\-)\.01364[0-9] * (0| )\.00150[0-9] * (0| )\.05396[0-9] * (0| )\.01260[0-9] * (\-0|\-)\.00740[0-9]" $log | wc -l`
CRIT14=`$GREP "H * x * (0| )\.00711[0-9] * (0| )\.02222[0-9] * (0| )\.00197[0-9] * (0| )\.00054[0-9] * (0| )\.00107[0-9] * (0| )\.00219[0-9]" $log | wc -l`
CRIT15=`$GREP "H * y * (0| )\.00029[0-9] * (0| )\.00089[0-9] * (\-0|\-)\.00112[0-9] * (0| )\.11160[0-9] * (0| )\.06768[0-9]" $log | wc -l`
CRIT16=`$GREP "H * z * (0| )\.00513[0-9] * (0| )\.00104[0-9] * (\-0|\-)\.00168[0-9] * (\-0|\-)\.00204[0-9] * (0| )\.00095[0-9] * (\-0|\-)\.00157[0-9]" $log | wc -l`
CRIT17=`$GREP "H * x * (0| )\.00830[0-9] * (0| )\.00381[0-9] * (\-0|\-)\.00794[0-9] * (0| )\.04594[0-9]" $log | wc -l`
TEST[5]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10 \+ $CRIT11 \+ $CRIT12 \+ \
		$CRIT13 \+ $CRIT14 \+ $CRIT15 \+ $CRIT16 \+ $CRIT17`
CTRL[5]=17
ERROR[5]="INITIAL HESSIAN NOT CORRECT"

# Initial step
CRIT1=`$GREP "C * \-1\.19358....[0-9] * (0| )\.62065....[0-9] * \-1\.88079....[0-9]" $log | wc -l`
CRIT2=`$GREP "C * 1\.17026....[0-9] * (\-0|\-)\.01698....[0-9] * 2\.06888....[0-9]" $log | wc -l`
CRIT3=`$GREP "C * (0| )\.02930....[0-9] * (\-0|\-)\.89893....[0-9] * (\-0|\-)\.34580....[0-9]" $log | wc -l`
CRIT4=`$GREP "O * (0| )\.10630....[0-9] * (\-0|\-)\.0609.....[0-9] * 4\.09670....[0-9]" $log | wc -l`
CRIT5=`$GREP "H * \-2\.0205(7|8)....[0-9] * (\-0|\-)\.04836....[0-9] * \-3\.60617....[0-9]" $log | wc -l`
CRIT6=`$GREP "H * 3\.0962(5|6)....[0-9] * (0| )\.6827(3|4)....[0-9] * 1\.91315....[0-9]" $log | wc -l`
CRIT7=`$GREP "H * (0| )\.24153....[0-9] * \-2\.87487....[0-9] * (\-0|\-)\.77808....[0-9]" $log | wc -l`
CRIT8=`$GREP "H * \-1\.42951....[0-9] * 2\.59671....[0-9] * \-1\.46787....[0-9]" $log | wc -l`
TEST[6]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8`
CTRL[6]=8
ERROR[6]="INITIAL STEP NOT CORRECT"

# Second iteration
CRIT1=`$GREP "Energy at this geometry is * \: * \-189\.67565[0-9]" $log | wc -l`
CRIT2=`$GREP "Norm of gradient * \: * (0| )\.00910[0-9]" $log | wc -l`
CRIT3=`$GREP "Norm of step * \: * (0| )\.03338[0-9]" $log | wc -l`
TEST[7]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[7]=3
ERROR[7]="SECOND ITERATION NOT CORRECT"

# Third iteration
CRIT1=`$GREP "Norm of gradient * \: * (0| )\.00023[0-9]" $log | wc -l`
CRIT2=`$GREP "Norm of step * \: * (0| )\.00100[0-9]" $log | wc -l`
TEST[8]=`expr	$CRIT1 \+ $CRIT2`
CTRL[8]=2
ERROR[8]="THIRD ITERATION NOT CORRECT"

# Final geometry
CRIT1=`$GREP "C * \-1\.1997196..[0-9] * (0| )\.625386...[0-9] * \-1\.889697...[0-9]" $log | wc -l`
CRIT2=`$GREP "C * 1\.1692801..[0-9] * (\-0|\-)\.020677...[0-9] * 2\.086091...[0-9]" $log | wc -l`
CRIT3=`$GREP "C * (0| )\.017123(1|2)..[0-9] * (\-0|\-)\.889526...[0-9] * (\-0|\-)\.341969...[0-9]" $log | wc -l`
CRIT4=`$GREP "O * (0| )\.1323356..[0-9] * (\-0|\-)\.066713...[0-9] * 4\.121882...[0-9]" $log | wc -l`
CRIT5=`$GREP "H * \-2\.0028866..[0-9] * (\-0|\-)\.050094...[0-9] * \-3\.623843...[0-9]" $log | wc -l`
CRIT6=`$GREP "H * 3\.0944850..[0-9] * (0| )\.665795...[0-9] * 1\.908879...[0-9]" $log | wc -l`
CRIT7=`$GREP "H * (0| )\.242344(4|5)..[0-9] * \-2\.863159...[0-9] * (\-0|\-)\.772736...[0-9]" $log | wc -l`
CRIT8=`$GREP "H * \-1\.452962...[0-9] * 2\.598989...[0-9] * \-1\.488606...[0-9]" $log | wc -l`
TEST[9]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8`
CTRL[9]=32
ERROR[9]="FINAL GEOMETRY NOT CORRECT"

# Optimization converged
CRIT1=`$GREP "Geometry converged in * 4( |  )iterations\!" $log | wc -l`
CRIT2=`$GREP "Energy at final geometry is * \: * \-189\.67574[0-9] a\.u\." $log | wc -l`
CRIT3=`$GREP "Energy change during optimization \: * (\-0|\-)\.00449[0-9] a\.u\." $log | wc -l`
TEST[10]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[10]=3
ERROR[10]="GEOMETRY OPTIMIZATION NOT CONVERGED"

PASSED=1
for i in 1 2 3 4 5 6 7 8 9 10
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo ${ERROR[i]}
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
