#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > prop_spinspin2.info <<'%EOF%'
   prop_spinspin2
   --------------
   Molecule:         H2O
   Wave Function:    MCSCF (CAS)
   Test Purpose:     Spin-spin coupling constants calculating only the
                     normally most dominating contributions to the
                     isotropic and anisotropic coupling constants, namely
                     the FC-FC and FC-SD terms, thus only solving one
                     response equation
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > prop_spinspin2.mol <<'%EOF%'
INTGRL
Calculation of only the dominating contributions to the isotropic and
anisotropic coupling constants
    2    2  X  Y      1.0D-12
        8.    1    3    1    1    1
O      .0000000000 0.0        -.2249058930
   11    7
30664.503 .000214139
4573.2014 .001677982
1029.5524 .008881474
285.90474 .037281336
90.369653 .12518867
31.219578           1.0
11.607766                     1.0
4.5927595                               1.0
1.2711716                                         1.0
.47214017                                                   1.0
.17896534                                                             1.0
    7    6
78.702943 .004241602
18.409261 .029868457
5.7530835           1.0
2.1107114                     1.0
.83712087                               1.0
.33907630                                         1.0
.13226310                                                   1.0
    2    2
1.4       1.0
0.35                1.0
        1.    1    2    1    1    1
H1    1.4523499293        0.0  .8996235720
    6    4
68.1600   0.00255
10.2465   0.01938
2.34648   0.09280
0.673320            1.0
0.224660                      1.0
0.082217                                1.0
    2    2
1.3       1.0
0.33                1.0
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > prop_spinspin2.dal <<'%EOF%'
**DALTON INPUT
.RUN PROPERTIES
**WAVE FUNCTIONS
.HF
.MP2
.MCSCF
*SCF INPUT
.DOUBLY OCCUPIED
  3 1 1 0
*CONFIGURATION INPUT
.SPIN MULTIPLICITY
    1
.SYMMETRY
    1
.INACTIVE ORBITALS
  1  0  0  0
.ELECTRONS (active)
    8
.CAS SPACE
 4 2 2 0
*OPTIMIZATION
.MAX CI
   12
.ABSORPTION
 LEVEL 3
.OPTIMAL ORBITAL TRIAL VECTORS
**PROPERTIES
.SPIN-S
*LINRES
.MAX IT
   45
.THRESH
5.0D-5
*SPIN-S
.SDxFC
**END OF INPUT
%EOF%
#######################################################################



#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >prop_spinspin2.check
cat >>prop_spinspin2.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# Basis set
CRIT1=`$GREP "O * 1 * 8\.0000 * 42 * 35 * \[11s7p2d\|7s6p2d\]" $log | wc -l`
CRIT2=`$GREP "H1 * 2 * 1\.0000 * 12 * 10 * \[6s2p\|4s2p\]" $log | wc -l`
CRIT3=`$GREP "total\: * 3 * 10\.0000 * 66 * 55" $log | wc -l`
CRIT4=`$GREP "Spherical harmonic basis used\." $log | wc -l`
TEST[1]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
CTRL[1]=4
ERROR[1]="BASIS SET NOT READ CORRECTLY"

# Geometry
CRIT1=`$GREP "Total number of coordinates\: * 9" $log | wc -l`
CRIT2=`$GREP "1 * x * (0| )\.0000000000" $log | wc -l`
CRIT3=`$GREP "2 * y * (0| )\.0000000000" $log | wc -l`
CRIT4=`$GREP "3 * z * (\-0|\-)\.2249058930" $log | wc -l`
CRIT5=`$GREP "4 * x * 1\.4523499293" $log | wc -l`
CRIT6=`$GREP "5 * y * (0| )\.0000000000" $log | wc -l`
CRIT7=`$GREP "6 * z * (0| )\.8996235720" $log | wc -l`
CRIT8=`$GREP "7 * x * \-1\.4523499293" $log | wc -l`
CRIT9=`$GREP "8 * y * (0| )\.0000000000" $log | wc -l`
CRIT10=`$GREP "9 * z * (0| )\.8996235720" $log | wc -l`
TEST[2]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10`
CTRL[2]=10
ERROR[2]="GEOMETRY NOT READ CORRECTLY"

# Symmetry
CRIT1=`$GREP "Number of coordinates in each symmetry\: * 3 * 3 * 2 * 1" $log | wc -l`
CRIT2=`$GREP "Number of orbitals in each symmetry\: * 25 * 16 * 10 * 4" $log | wc -l`
TEST[3]=`expr	$CRIT1 \+ $CRIT2`
CTRL[3]=2
ERROR[3]="SYMMETRY NOT CORRECT"

# Energies
CRIT1=`$GREP "Hartree\-Fock total energy \: * \-76\.06188340" $log | wc -l`
CRIT2=`$GREP "\= MP2 second order energy \: * \-76\.3483987" $log | wc -l`
CRIT3=`$GREP "Final MCSCF energy\: * \-76\.19370395" $log | wc -l`
TEST[4]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[4]=3
ERROR[4]="ENERGIES NOT CORRECT"

# Spin-spin coupling
CRIT1=`$GREP "Isotropic coupling * \: * \-12\.8653 Hz" $log | wc -l`
CRIT2=`$GREP "Anisotropic coupling * \: * \-34\.0161 Hz" $log | wc -l`
CRIT3=`$GREP "Asymmetry * \: * (\-0|\-)\.0316" $log | wc -l`
CRIT4=`$GREP "S parameter * \: * 34\.0218 Hz" $log | wc -l`
CRIT5=`$GREP "A parameter * \: * (0| )\.6617 Hz" $log | wc -l`
CRIT6=`$GREP "Isotropic DSO contribution\: * \-6\.7673 Hz" $log | wc -l`
CRIT7=`$GREP "Isotropic PSO contribution\: * 7\.8265 Hz" $log | wc -l`
CRIT8=`$GREP "Isotropic SD contribution \: * (0| )\.0000 Hz" $log | wc -l`
CRIT9=`$GREP "Isotropic FC contribution \: * \-13\.9246 Hz" $log | wc -l`
TEST[5]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9`
CTRL[5]=9
ERROR[5]="SPIN-SPIN COUPLING NOT CORRECT"

PASSED=1
for i in 1 2 3 4 5
do
   if [ ${TEST[i]} -lt ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
