#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi
 

#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > prop_ctocd.info <<%EOF%
   prop_ctocd
   ----------
   Molecule:         H2O
   Wave Function:    SCF
   Test Purpose:     Calculation of CTOCD-DZ magnetizability and
	             shielding constants through ABACUS
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > prop_ctocd.mol <<%EOF%
INTGRL
Calculation of CTOCD-DZ magnetizability and shielding constants through ABACUS

c   2    2  X  Y      0.10D-15  0.10D-15
      8.00    1    3    6    5    1
O   0.00000             0.00000              0.1241444240
F  6    1
31195.6 0.00021
4669.38 0.001628
1062.62 0.00845
301.426 0.034191
98.5153 0.110311
35.4609 .269493
F  1    1
13.6179 .423545
F  1    1
5.38618 .283038
F  1    1
1.53873 .027484
F  1    1
.6055 -.005144
F  1    1
.22054 .00164
F  3    1
114.863 .002266
26.8767 0.017192
8.32077 0.075341
F  1    1
2.97237 .212775
F  1    1
1.12848 .370478
F  1    1
.4236 .398523
F  1    1
.15074 .184703
F  2    1
1.21879 .357851
.36102 .759561
      1.00    1    2    3    1
H   0.00000             1.43153              -0.985265576
F  3    1
33.865014 .006068
5.094788 0.045316
1.158786 0.202846
F  1    1
0.32584 0.503709
F  1    1
.102741 .383568
F  1    1
1.16 1.0
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > prop_ctocd.dal <<%EOF%
**DALTON INPUT
.RUN PROPERTIES
**WAVE FUNCTIONS
.HF
**PROPERTIES
.CTOCD
.MAGNET
.SHIELD
*END OF INPUT
%EOF%
#######################################################################



#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >prop_ctocd.check
cat >>prop_ctocd.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# Basis set
CRIT1=`$GREP "O * 1 * 8\.0000 * 44 * 27 * \[11s7p2d\|6s5p1d\]" $log | wc -l`
CRIT2=`$GREP "H * 2 * 1\.0000 * 8 * 6 * \[5s1p\|3s1p\]" $log | wc -l`
CRIT3=`$GREP "total\: * 3 * 10\.0000 * 60 * 39" $log | wc -l`
CRIT4=`$GREP "Cartesian basis used" $log | wc -l`
TEST[1]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
CTRL[1]=4
ERROR[1]="BASIS SET NOT READ CORRECTLY"

# Geometry
CRIT1=`$GREP "Total number of coordinates\: * 9" $log | wc -l`
CRIT2=`$GREP "1 * x * (0| )\.0000000000" $log | wc -l`
CRIT3=`$GREP "2 * y * (0| )\.0000000000" $log | wc -l`
CRIT4=`$GREP "3 * z * (0| )\.1241444240" $log | wc -l`
CRIT5=`$GREP "4 * x * (0| )\.0000000000" $log | wc -l`
CRIT6=`$GREP "5 * y * 1\.4315300000" $log | wc -l`
CRIT7=`$GREP "6 * z * (\-0|\-)\.9852655760" $log | wc -l`
CRIT8=`$GREP "7 * x * (0| )\.0000000000" $log | wc -l`
CRIT9=`$GREP "8 * y * \-1\.4315300000" $log | wc -l`
CRIT10=`$GREP "9 * z * (\-0|\-)\.9852655760" $log | wc -l`
TEST[2]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10`
CTRL[2]=10
ERROR[2]="GEOMETRY NOT READ CORRECTLY"

# Symmetry
CRIT1=`$GREP "Number of coordinates in each symmetry\: * 3 * 2 * 3 * 1" $log | wc -l`
CRIT2=`$GREP "Number of orbitals in each symmetry\: * 19 * 7 * 11 * 2" $log | wc -l`
TEST[3]=`expr	$CRIT1 \+ $CRIT2`
CTRL[3]=2
ERROR[3]="SYMMETRY NOT CORRECT"

# Energies
CRIT1=`$GREP "Final * HF energy\: * \-76\.060784218[0-9]" $log | wc -l`
TEST[4]=`expr	$CRIT1`
CTRL[4]=1
ERROR[4]="ENERGIES NOT CORRECT"

# Property calculation
CRIT1=`$GREP "Nuclear magnetic shieldings" $log | wc -l`
CRIT2=`$GREP "Magnetic susceptibilities" $log | wc -l`
CRIT3=`$GREP "Continuous Transformation of the Origin of the Current Density" $log | wc -l`
CRIT4=`$GREP "CTOCD\-DZ Magnetic susceptibilities" $log | wc -l`
CRIT5=`$GREP "CTOCD\-DZ Nuclear magnetic shieldings" $log | wc -l`
CRIT6=`$GREP "London orbitals are NOT used" $log | wc -l`
TEST[5]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ \
	        $CRIT6 ` 
CTRL[5]=8
ERROR[5]="CALCULATION OF PROPERTIES NOT SET UP CORRECTLY"

# CTOCD-DZ Magnetizabilities
CRIT1=`$GREP "Isotropic magnetizability\: * \-2\.399[0-9] * \-189\.355[0-9] * \-11\.403[0-9]" $log | wc -l`
CRIT2=`$GREP "Diamagnetic contribution\: * \-2\.663[0-9] * \-210\.161[0-9] * \-12\.656[0-9]" $log | wc -l`
CRIT3=`$GREP "Paramagnetic contribution\: * (0| )\.263[0-9] * 20\.806[0-9] * 1\.253[0-9]" $log | wc -l`
CRIT4=`$GREP "1st anisotropy\: * (\-0|\-)\.112[0-9] * \-8\.873[0-9] * (\-0|\-)\.534[0-9]" $log | wc -l`
CRIT5=`$GREP "2nd anisotropy\: * (0| )\.144[0-9] * 11\.415[0-9] * (0| )\.687[0-9]" $log | wc -l`
TEST[6]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5`
CTRL[6]=6
ERROR[6]="CTOCD-DZ MAGNETIZABILITIES NOT CORRECT"

# Total magnetizability tensor
CRIT1=`$GREP "Bx * \-2\.474593(3|4)...[0-9][0-9] * (\-0| \-| 0|  )\.000000000000 * (\-0| \-| 0|  )\.000000000000" $log | wc -l`
CRIT2=`$GREP "By * (\-0| \-| 0|  )\.000000000000 * \-2\.3031849(2|3)...[0-9] * (\-0| \-| 0|  )\.000000000000" $log | wc -l`
CRIT3=`$GREP "Bz * (\-0| \-| 0|  )\.000000000000 * (\-0| \-| 0|  )\.000000000000 * \-2\.42109(49|50)....[0-9]" $log | wc -l`
TEST[7]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[7]=3
ERROR[7]="TOTAL CTOCD-DZ MAGNETIZABILITY TENSOR NOT CORRECT"

# Diamagnetic magnetizability tensor
CRIT1=`$GREP "Bx * \-2\.912805(89|90)...[0-9] * (\-0| \-| 0|  )\.000000000000 * (\-0| \-| 0|  )\.000000000000" $log | wc -l`
CRIT2=`$GREP "By * (\-0| \-| 0|  )\.000000000000 * \-2\.42296273...[0-9] * (\-0| \-| 0|  )\.000000000000" $log | wc -l`
CRIT3=`$GREP "Bz * (\-0| \-| 0|  )\.000000000000 * (\-0| \-| 0|  )\.000000000000 * \-2\.65411279...[0-9]" $log | wc -l`
TEST[8]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[8]=3
ERROR[8]="CTOCD-DZ DIAMAGNETIC MAGNETIZABILITY TENSOR NOT CORRECT"

# Paramagnetic magnetizability tensor
CRIT1=`$GREP "Bx * (0| )\.438212(4|5)....[0-9] * (\-0| \-| 0|  )\.000000000000 * (\-0| \-| 0|  )\.000000000000" $log | wc -l`
CRIT2=`$GREP "By * (\-0| \-| 0|  )\.000000000000 * (0| )\.1197778(0|1)...[0-9] * (\-0| \-| 0|  )\.000000000000" $log | wc -l`
CRIT3=`$GREP "Bz * (\-0| \-| 0|  )\.000000000000 * (\-0| \-| 0|  )\.000000000000 * (0| )\.233017(79|80)...[0-9]" $log | wc -l`
TEST[9]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[9]=6
ERROR[9]="PARAMAGNETIC MAGNETIZABILITY TENSOR NOT CORRECT"

# Shielding tensors (symmetry coordinates)
CRIT1=`$GREP "O * y * 6\.2416037[0-9]" $log | wc -l`
CRIT2=`$GREP "H * y * 1\.2326366[0-9]" $log | wc -l`
CRIT3=`$GREP "H * z * (\-0|\-)\.4551983[0-9]" $log | wc -l`
CRIT4=`$GREP "O * x * 6\.3579385[0-9]" $log | wc -l`
CRIT5=`$GREP "H * x * (0| )\.4635252[0-9]" $log | wc -l`
CRIT6=`$GREP "O * z * 6\.3270632[0-9]" $log | wc -l`
CRIT7=`$GREP "H * y * (\-0|\-)\.6177392[0-9]" $log | wc -l`
CRIT8=`$GREP "H * z * (0| )\.7771551[0-9]" $log | wc -l`
TEST[10]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8`
CTRL[10]=16
ERROR[10]="CTOCD-DZ SHIELDING TENSORS IN SYMMETRY COORDINATES NOT CORRECT ${TEST[10]}"

# Chemical shielding for O
CRIT1=`$GREP "Shielding constant\: * 234\.194[0-9] ppm" $log | wc -l`
CRIT2=`$GREP "Anisotropy\: * 58\.475[0-9] ppm" $log | wc -l`
CRIT3=`$GREP "Asymmetry\: * (0| )\.088[0-9]" $log | wc -l`
CRIT4=`$GREP "S parameter\: * 58\.550[0-9] ppm" $log | wc -l`
TEST[11]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
CTRL[11]=8
ERROR[11]=" CTOCD-DZ CHEMICAL SHIELDING FOR OXYGEN NOT CORRECT"

# Total shielding tensor for O
CRIT1=`$GREP "O * x * 212\.9841...[0-9] * (0| )\.00000000 * (0| )\.00000000" $log | wc -l`
CRIT2=`$GREP "O * y * (0| )\.00000000 * 273\.1774...[0-9] * (0| )\.00000000" $log | wc -l`
CRIT3=`$GREP "O * z * (0| )\.00000000 * (0| )\.00000000 *  216\.4205...[0-9]" $log | wc -l`
TEST[12]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[12]=6
ERROR[12]="TOTAL CTOCD-DZ SHIELDING TENSOR FOR OXYGEN NOT CORRECT"

# Diamagnetic and paramagnetic contributions
CRIT1=`$GREP "Diamagnetic contribution\: *  337\.74212[0-9] * Paramagnetic\: * \-103\.5480(6|7)[0-9]" $log | wc -l`
TEST[13]=`expr	$CRIT1`
CTRL[13]=1
ERROR[13]="CTOCD-DZ DIAMAGNETIC AND PARAMAGNETIC CONTRIBUTIONS FOR OXYGEN, GAUGE ORIG ON ATOM, NOT CORRECT"

# Chemical shielding for H
CRIT1=`$GREP "Shielding constant\: * 28\.168[0-9] ppm" $log | wc -l`
CRIT2=`$GREP "Anisotropy\: * 16\.716[0-9] ppm" $log | wc -l`
CRIT3=`$GREP "Asymmetry\: * (0| )\.058[0-9]" $log | wc -l`
CRIT4=`$GREP "S parameter\: *  16\.725[0-9] ppm" $log | wc -l`
TEST[14]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5`
CTRL[14]=18
ERROR[14]="CTOCD-DZ CHEMICAL SHIELDING FOR HYDROGEN NOT CORRECT ${TEST[14]}"

# Total shielding tensor for H1 and H2
CRIT1=`$GREP "H * 1 x *  22\.2696...[0-9] * (0| )\.00000000 * (0| )\.00000000" $log | wc -l`
CRIT2=`$GREP "H * 1 y * (0| )\.00000000 * 34\.9920...[0-9] * \-8\.5077...[0-9]" $log | wc -l`
CRIT3=`$GREP "H * 1 z * (0| )\.00000000 * \-5\.9340...[0-9] *  27\.2424...[0-9]" $log | wc -l`
TEST[15]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[15]=6
ERROR[15]="TOTAL CTOCD-DZ SHIELDING TENSOR FOR HYDROGEN NOT CORRECT"

# Diamagnetic and paramagnetic contributions H1 and H2
CRIT1=`$GREP "Diamagnetic contribution\: * 94\.84330[0-9] * Paramagnetic\: * \-66\.67527[0-9]" $log | wc -l`
TEST[16]=`expr	$CRIT1`
CTRL[16]=2
ERROR[16]="CTOCD-DZ DIAMAGNETIC AND PARAMAGNETIC CONTRIBUTIONS FOR HYDROGEN NOT CORRECT"

# Diamagnetic and paramagnetic contributions O
CRIT1=`$GREP "Diamagnetic contribution\: * 335\.95579[0-9] * Paramagnetic\: * \-101\.76173[0-9]" $log | wc -l`
TEST[17]=`expr	$CRIT1`
CTRL[17]=1
ERROR[17]="CTOCD-DZ DIAMAGNETIC AND PARAMAGNETIC CONTRIBUTIONS FOR OXYGEN NOT CORRECT"

# Diamagnetic and paramagnetic contributions
CRIT1=`$GREP "Diamagnetic contribution\: * 21\.95124[0-9] * Paramagnetic\: * 6\.21678[0-9]" $log | wc -l`
TEST[18]=`expr	$CRIT1`
CTRL[18]=2
ERROR[18]="CTOCD-DZ DIAMAGNETIC AND PARAMAGNETIC CONTRIBUTIONS FOR HYDROGEN, GAUGE ORIG ON ATOM, NOT CORRECT"


PASSED=1
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
