#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -e /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -e /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > prop_nucquad.info <<'%EOF%'
   prop_nucquad
   ------------
   Molecule:         ClO2
   Wave Function:    MCSCF (CAS) / cc-pVTZ
   Test Purpose:     Nuclear quadrupole coupling constants
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > prop_nucquad.mol <<'%EOF%'
BASIS
cc-pVTZ
Calculation of nuclear quadrupole coupling constants

    2    2  X  Y      1.00D-15
      17.     1
Cl    0.00000    0.00000   1.0000
       8.     1
O1    0.00000    2.37360  -0.44317
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > prop_nucquad.dal <<'%EOF%'
**DALTON INPUT
.RUN PROPERTIES
**WAVE FUNCTIONS
.HF
.MCSCF
*HF INPUT
.HF OCCUPATION
 8 2 5 1
.OPEN SHELL
 2
*CONFIGURATION INPUT
.INACTIVE
 4 1 2 0
.CAS SPACE
 5 2 4 1
.ELECTRONS
 19
.SPIN MULTIPLICITY
 2
.SYMMETRY
 2
**PROPERTIES
.NQCC
*END OF
%EOF%
#######################################################################



#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >prop_nucquad.check
cat >>prop_nucquad.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# Molecular geometry
CRIT1=`$GREP "1 * Cl * x * (0| )\.0000000000" $log | wc -l`
CRIT2=`$GREP "2 * y * (0| )\.0000000000" $log | wc -l`
CRIT3=`$GREP "3 * z * 1\.0000000000" $log | wc -l`
CRIT4=`$GREP "4 * O1 * 1 * x * (0| )\.0000000000" $log | wc -l`
CRIT5=`$GREP "5 * y * 2\.3736000000" $log | wc -l`
CRIT6=`$GREP "6 * z * (\-0|\-)\.4431700000" $log | wc -l`
CRIT7=`$GREP "7 * O1 * 2 * x * (0| )\.0000000000" $log | wc -l`
CRIT8=`$GREP "8 * y * \-2\.3736000000" $log | wc -l`
CRIT9=`$GREP "9 * z * (\-0|\-)\.4431700000" $log | wc -l`
TEST[1]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9`
CTRL[1]=9
ERROR[1]="GEOMETRY NOT CORRECT"

# Symmetry
CRIT1=`$GREP "Number of coordinates in each symmetry\: * 3 * 2 * 3 * 1" $log | wc -l`
CRIT2=`$GREP "Number of orbitals in each symmetry\: * 35 * 18 * 28 * 13" $log | wc -l`
TEST[2]=`expr	$CRIT1 \+ $CRIT2`
CTRL[2]=2
ERROR[2]="SYMMETRY NOT CORRECT"

# Energy
CRIT1=`$GREP "Final MCSCF energy\: * \-609\.165589624(1|2)[0-9][0-9]" $log | wc -l`
TEST[3]=`expr	$CRIT1`
CTRL[3]=1
ERROR[3]="ENERGY NOT CORRECT"

# Cl quadropole coupling
CRIT1=`$GREP "Spin * \: * 1\.5 * Quadrupole moment\:\-\.08165000" $log | wc -l`
CRIT2=`$GREP "Cl * 35 * Vx \= * (\-0|\-)\.272182 * 5\.221780 * 1\.865422" $log | wc -l`
CRIT3=`$GREP "Cl * 35 * Vy \= * \-2\.394406 * 45\.936379 * 16\.410250" $log | wc -l`
CRIT4=`$GREP "Cl * 35 * Vz \= * 2\.666588 * \-51\.158159 * \-18\.275671" $log | wc -l`
CRIT5=`$GREP "Auxiliary value au * 1\/T * (0| )\.574136(D|E)\-02" $log | wc -l`
CRIT6=`$GREP "Spin * \: * 1\.5 * Quadrupole moment\:\-\.06435000" $log | wc -l`
CRIT7=`$GREP "Cl * 37 * Vx \= * (\-0|\-)\.272182 * 4\.115389 * 1\.470176" $log | wc -l`
CRIT8=`$GREP "Cl * 37 * Vy \= * \-2\.394406 * 36\.203380 * 12\.933246" $log | wc -l`
CRIT9=`$GREP "Cl * 37 * Vz \= * 2\.666588 * \-40\.318769 * \-14\.403422" $log | wc -l`
CRIT10=`$GREP "Asymmetry constant eta\: * (0| )\.795857" $log | wc -l`
CRIT11=`$GREP "Auxiliary value au * 1\/T * (0| )\.356615(D|E)\-02" $log | wc -l`
TEST[4]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10 \+ $CRIT11`
CTRL[4]=12
ERROR[4]="CL QUADROPOLE COUPLING NOT CORRECT"

# O quadropole coupling
CRIT1=`$GREP "Spin * \: * 2\.5 * Quadrupole moment\:\-\.02558000" $log | wc -l`
CRIT2=`$GREP "O1 * 1 17 * Vx \= * (\-0|\-)\.494792 * 2\.973894 * 1\.062390" $log | wc -l`
CRIT3=`$GREP "O1 * 1 17 * Vy \= * \-1\.185838 * 7\.127360 * 2\.546168" $log | wc -l`
CRIT4=`$GREP "O1 * 1 17 * Vz \= * 1\.680630 * \-10\.101254 * \-3\.608558" $log | wc -l`
CRIT5=`$GREP "O1 * 2 17 * Vx \= * (\-0|\-)\.494792 * 2\.973894 * 1\.062390" $log | wc -l`
CRIT6=`$GREP "O1 * 2 17 * Vy \= * \-1\.185838 * 7\.127360 * 2\.546168" $log | wc -l`
CRIT7=`$GREP "O1 * 2 17 * Vz \= * 1\.680630 * \-10\.101254 * \-3\.608558" $log | wc -l`
CRIT8=`$GREP "Asymmetry constant eta\: * (0| )\.411183" $log | wc -l`
CRIT9=`$GREP "Auxiliary value au * 1\/T * (0| )\.468562(D|E)\-04" $log | wc -l`
TEST[5]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9`
CTRL[5]=12
ERROR[5]="O QUADROPOLE COUPLING NOT CORRECT"

PASSED=1
for i in 1 2 3 4 5
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo ${ERROR[i]}
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
