#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > r12_fc_sym.info <<'%EOF%'
   r12_fc_sym
   ----------
   Molecule:         Nitrogen (N2)
   Wave Function:    MP2-R12 / cc-pVTZ w/frozen core
   Test Purpose:     Check R12 method with symmetry
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > r12_fc_sym.mol <<'%EOF%'
BASIS
cc-pVTZ
Direct MP2-R12 calculation using symmetry

    1    3  X  Y  Z
        7.    1
N      0.000000000000000   0.000000000000000   1.037572100000000       *
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > r12_fc_sym.dal <<'%EOF%'
**DALTON INPUT
.RUN WAVE FUNCTION
.DIRECT
**INTEGRALS
.R12
**WAVE FUNCTIONS
.CC
*SCF INPUT
.THRESHOLD
 1D-10
*CC INPUT
.MP2
.PRINT
 3
.FROIMP
 1 0 0 0 1 0 0 0 
 0 0 0 0 0 0 0 0
*ORBITALS
.MOSTART
 H1DIAG
**END OF DALTON INPUT
%EOF%

#######################################################################

 

#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >r12_fc_sym.check
cat >>r12_fc_sym.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi
#                       ! Original MP2-R12 method !
#             MP2-R12/A   correlation energy =   -0.403449906
#             MP2-R12/B   correlation energy =   -0.393864561
CRIT1=`$GREP "MP2-R12/B   correlation energy =   (-0| -)\.39386456" $log | wc -l`
TEST[1]=`expr	$CRIT1`
CTRL[1]=1
ERROR[1]="MP2-R12/B ENERGY NOT CORRECT"

PASSED=1
for i in 1 
do 
   if [ ${TEST[i]} -lt ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done 

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM 
  exit 1
fi

%EOF%
#######################################################################
