#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > rsp_soppa1excisymm.info <<'%EOF%'
   rsp_soppa1excisymm
   ------------------
   Molecule:         H2O
   Wave Function:    MP2 (SOPPA) / cc-pVDZ
   Test Purpose:     Singlet excitation energies. Symmetry
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > rsp_soppa1excisymm.mol <<'%EOF%'
BASIS
cc-pVDZ
SOPPA calculation of singlet excitation energies. Symmetry

    2    2  X  Z
        8.    1
O     0.0 -0.2249058930 0.0
        1.    1
H     1.45235 0.899623 0.0
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > rsp_soppa1excisymm.dal <<'%EOF%'
**DALTON INPUT
.RUN RESPONSE
**WAVE FUNCTION
.HF
.MP2
**RESPONSE
.NOITRA
.SOPPA
*LINEAR
.SINGLE RESIDUE
.DIPLEN
.ROOTS
 2 2 2 2
**END OF DALTON INPUT
%EOF%
#######################################################################



#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >rsp_soppa1excisymm.check
cat >>rsp_soppa1excisymm.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# Basis set
CRIT1=`$GREP "O * 1 * 8\.0000 * 26 * 14 * \[9s4p1d\|3s2p1d\]" $log | wc -l`
CRIT2=`$GREP "H * 2 * 1\.0000 * 7 * 5 * \[4s1p\|2s1p\]" $log | wc -l`
CRIT3=`$GREP "total\: * 3 * 10\.0000 * 40 * 24" $log | wc -l`
CRIT4=`$GREP "Spherical harmonic basis used\." $log | wc -l`
TEST[1]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
CTRL[1]=4
ERROR[1]="BASIS SET NOT READ CORRECTLY"

# Geometry
CRIT1=`$GREP "Total number of coordinates\: * 9" $log | wc -l`
CRIT2=`$GREP "1 * x * (0| )\.0000000000" $log | wc -l`
CRIT3=`$GREP "2 * y * (\-0|\-)\.2249058930" $log | wc -l`
CRIT4=`$GREP "3 * z * (0| )\.0000000000" $log | wc -l`
CRIT5=`$GREP "4 * x * 1\.4523500000" $log | wc -l`
CRIT6=`$GREP "5 * y * (0| )\.8996230000" $log | wc -l`
CRIT7=`$GREP "6 * z * (0| )\.0000000000" $log | wc -l`
CRIT8=`$GREP "7 * x * \-1\.4523500000" $log | wc -l`
CRIT9=`$GREP "8 * y * (0| )\.8996230000" $log | wc -l`
CRIT10=`$GREP "9 * z * (0| )\.0000000000" $log | wc -l`
TEST[2]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10`
CTRL[2]=10
ERROR[2]="GEOMETRY NOT READ CORRECTLY"

# Energies
CRIT1=`$GREP "Hartree\-Fock total energy \: * \-76\.025681483" $log | wc -l`
CRIT2=`$GREP "\= MP2 second order energy \: * \-76\.2306668" $log | wc -l`
TEST[3]=`expr	$CRIT1 \+ $CRIT2`
CTRL[3]=2
ERROR[3]="ENERGIES NOT CORRECT"

# Response setup
CRIT1=`$GREP "2 Excitation energies are calculated for symmetry no\. * [1-4]" $log | wc -l`
CRIT2=`$GREP "1 property residues are calculated with labels\:" $log | wc -l`
TEST[4]=`expr	$CRIT1 \+ $CRIT2`
CTRL[4]=7
ERROR[4]="RESPONSE CALCULATION NOT SET UP CORRECTLY"

# Transition moments
CRIT1=`$GREP "\@ *STATE NO\: * 1 \*TRANSITION MOMENT\: (\-0| \-| 0|  )\.61165... * \*ENERGY\(eV\)\: * 10\.39534" $log | wc -l`
CRIT2=`$GREP "\@ *STATE NO\: * 2 \*TRANSITION MOMENT\: (\-0| \-| 0|  )\.54007... * \*ENERGY\(eV\)\: * 17\.40219" $log | wc -l`
CRIT3=`$GREP "\@ *STATE NO\: * 1 \*TRANSITION MOMENT\: (\-0| \-| 0|  )\.50061... * \*ENERGY\(eV\)\: * 12\.46520" $log | wc -l`
CRIT4=`$GREP "\@ *STATE NO\: * 2 \*TRANSITION MOMENT\: (\-0| \-| 0|  )\.91781... * \*ENERGY\(eV\)\: * 14\.37195" $log | wc -l`
CRIT5=`$GREP "\@ *STATE NO\: * 1 \*TRANSITION MOMENT\: (\-0| \-| 0|  )\.36245... * \*ENERGY\(eV\)\: * 7\.75444[89]" $log | wc -l`
CRIT6=`$GREP "\@ *STATE NO\: * 2 \*TRANSITION MOMENT\: (\-0| \-| 0|  )\.34551... * \*ENERGY\(eV\)\: * 23\.02376" $log | wc -l`
TEST[5]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6`
CTRL[5]=6
ERROR[5]="TRANSITION MOMENTS NOT CORRECT"

# Sym 1 State 1
CRIT1=`$GREP "\@ *Excitation energy \: * (0| )\.382022" $log | wc -l`
CRIT2=`$GREP "\@ *Total energy \: * \-75\.643659" $log | wc -l`
CRIT3=`$GREP "\@ *SOPPA * p\-h * weight in excitation operator\: * 95\.22 \%" $log | wc -l`
CRIT4=`$GREP "\@ *SOPPA 2p\-2h weight in excitation operator\: * 4\.78 \%" $log | wc -l`
CRIT5=`$GREP "\@ *Oscillator strength \(LENGTH\) * \: * 9\.5282...[0-9](D|E)\-02" $log | wc -l`
CRIT6=`$GREP "Transition moment.* \: ( |\-)*0*\.61165" $log | wc -l`
TEST[6]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6`
CTRL[6]=6
ERROR[6]="STATE 1 (SYM 1) NOT CORRECT"

# Sym 1 State 2
CRIT1=`$GREP "\@ *Excitation energy \: * (0| )\.639518" $log | wc -l`
CRIT2=`$GREP "\@ *Total energy \: * \-75\.386163" $log | wc -l`
CRIT3=`$GREP "\@ *SOPPA * p\-h * weight in excitation operator\: * 95\.97 \%" $log | wc -l`
CRIT4=`$GREP "\@ *SOPPA 2p\-2h weight in excitation operator\: * 4\.03 \%" $log | wc -l`
CRIT5=`$GREP "\@ *Oscillator strength \(LENGTH\) * \: * (0| )\.124358" $log | wc -l`
CRIT6=`$GREP "Transition moment.* \: ( |\-)*0*\.54007" $log | wc -l`
TEST[7]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6`
CTRL[7]=6
ERROR[7]="STATE 2 (SYM 1) NOT CORRECT"

# Sym 2 State 1
CRIT1=`$GREP "\@ *Excitation energy \: * (0| )\.458087" $log | wc -l`
CRIT2=`$GREP "\@ *Total energy \: * \-75\.567594" $log | wc -l`
CRIT3=`$GREP "\@ *SOPPA * p\-h * weight in excitation operator\: * 95\.54 \%" $log | wc -l`
CRIT4=`$GREP "\@ *SOPPA 2p\-2h weight in excitation operator\: * 4\.46 \%" $log | wc -l`
CRIT5=`$GREP "\@ *Oscillator strength \(LENGTH\) * \: * 7\.6536...[0-9](D|E)\-02" $log | wc -l`
CRIT6=`$GREP "Transition moment.* \: \-*0*\.50061" $log | wc -l`
TEST[8]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6`
CTRL[8]=6
ERROR[8]="STATE 1 (SYM 2) NOT CORRECT"

# Sym 2 State 2
CRIT1=`$GREP "\@ *Excitation energy \: * (0| )\.528159" $log | wc -l`
CRIT2=`$GREP "\@ *Total energy \: * \-75\.497522" $log | wc -l`
CRIT3=`$GREP "\@ *SOPPA * p\-h * weight in excitation operator\: * 96\.55 \%" $log | wc -l`
CRIT4=`$GREP "\@ *SOPPA 2p\-2h weight in excitation operator\: * 3\.45 \%" $log | wc -l`
CRIT5=`$GREP "\@ *Oscillator strength \(LENGTH\) * \: * (0| )\.29660" $log | wc -l`
CRIT6=`$GREP "Transition moment.* \: \-*0*\.91781" $log | wc -l`
TEST[9]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6`
CTRL[9]=6
ERROR[9]="STATE 2 (SYM 2) NOT CORRECT"

# Sym 3 State 1
CRIT1=`$GREP "\@ *Excitation energy \: * (0| )\.284970" $log | wc -l`
CRIT2=`$GREP "\@ *Total energy \: * \-75\.740711" $log | wc -l`
CRIT3=`$GREP "\@ *SOPPA * p\-h * weight in excitation operator\: * 95\.26 \%" $log | wc -l`
CRIT4=`$GREP "\@ *SOPPA 2p\-2h weight in excitation operator\: * 4\.74 \%" $log | wc -l`
CRIT5=`$GREP "\@ *Oscillator strength \(LENGTH\) * \: * 2\.4958[0-9]*(D|E)\-02" $log | wc -l`
CRIT6=`$GREP "Transition moment.* \: ( |\-)*0*\.36245" $log | wc -l`
TEST[10]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6`
CTRL[10]=6
ERROR[10]="STATE 1 (SYM 3) NOT CORRECT"

# Sym 3 State 2
CRIT1=`$GREP "\@ *Excitation energy \: * 0*\.846107" $log | wc -l`
CRIT2=`$GREP "\@ *Total energy \: *    \-75\.179574" $log | wc -l`
CRIT3=`$GREP "\@ *SOPPA * p\-h * weight in excitation operator\: * 94\.67 \%" $log | wc -l`
CRIT4=`$GREP "\@ *SOPPA 2p\-2h weight in excitation operator\: * 5\.33 \%" $log | wc -l`
CRIT5=`$GREP "\@ *Oscillator strength \(LENGTH\) * \: * 6\.7337[0-9]*(D|E)\-02" $log | wc -l`
CRIT6=`$GREP "Transition moment.* \: \-*0*\.34551" $log | wc -l`
TEST[11]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6`
CTRL[11]=6
ERROR[11]="STATE 2 (SYM 3) NOT CORRECT"

# Sym 4 State 1
CRIT1=`$GREP "\@ *Excitation energy \: * (0| )\.359329" $log | wc -l`
CRIT2=`$GREP "\@ *Total energy \: * \-75\.666352" $log | wc -l`
CRIT3=`$GREP "\@ *SOPPA * p\-h * weight in excitation operator\: * 95\.51 \%" $log | wc -l`
CRIT4=`$GREP "\@ *SOPPA 2p\-2h weight in excitation operator\: * 4\.49 \%" $log | wc -l`
TEST[12]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
CTRL[12]=4
ERROR[12]="STATE 1 (SYM 4) NOT CORRECT"

# Sym 4 State 2
CRIT1=`$GREP "\@ *Excitation energy \: * (0| )\.782329" $log | wc -l`
CRIT2=`$GREP "\@ *Total energy \: * \-75\.243352" $log | wc -l`
CRIT3=`$GREP "\@ *SOPPA * p\-h * weight in excitation operator\: * 94\.97 \%" $log | wc -l`
CRIT4=`$GREP "\@ *SOPPA 2p\-2h weight in excitation operator\: * 5\.03 \%" $log | wc -l`
TEST[13]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
CTRL[13]=4
ERROR[13]="STATE 2 (SYM 4) NOT CORRECT"

PASSED=1
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13
do
   if [ ${TEST[i]} -lt ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
