#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -e /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -e /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat << EODAL > rsp_g_cas.dal
**DALTON INPUT
.RUN RESPONSE
**INTEGRALS
.SPIN-ORBIT
**WAVE FUNCTIONS
.HF
.MCSCF
*SCF INPUT
.DOUBLY OCC
 3 1 1 0 2 1 0 0
*CONFIGURATION INPUT
.SYMMETRY
 4
.SPIN MULT
 3
.INACTIVE SPACE
 3 1 1 0 2 0 0 0
.ELECTRONS
 2
.CAS SPACE
 0 0 0 0 0 1 1 0
*OPTIMIZATION
.DETERMINANTS
**RESPONSE
*ESR
.G-TENSOR
.OZSO1
.OZSO2
**END OF DALTON INPUT
EODAL
cat << EOMOL > rsp_g_cas.mol
ATOMBASIS
Calculation of linear response spin-orbit

C   1    3  X  Y  Z     1.D-12
        8.    1 Basis=ano-1 3  2  1  0
O      0.00000   0.00000   1.14050
O      0.00000   0.00000  -1.14050
EOMOL
cat << 'EOCHK' > rsp_g_cas.check
log=$1
GREP=egrep

# ?
CRIT1=`$GREP "Final MCSCF energy\: * \-149\.64902543418" $log | wc -l`
TEST[1]=`expr	$CRIT1`
CTRL[1]=1
ERROR[1]="ENERGY NOT CORRECT"

# ?
CRIT1=`$GREP "\@G * _\|_ * \|\|" $log | wc -l`
CRIT2=`$GREP "\@G OZ\-SO1 * 5226\. *[- ]0\." $log | wc -l`
CRIT3=`$GREP "\@G OZ\-SO2 \-1586\. *[- ]0\." $log | wc -l`
CRIT4=`$GREP "\@G Total * 3640\. *[- ]0\." $log | wc -l`
TEST[2]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
CTRL[2]=4
ERROR[2]="G-TENSOR NOT CORRECT"
str="1 2"
PASSED=1
for i in $str
do
   if [ ${TEST[i]} -lt ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi
EOCHK
