#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > rsp_2ndharm.info <<'%EOF%'
   rsp_2ndharm
   -----------
   Molecule:         LiH
   Wave Function:    MCSCF (CAS) / 4-31G
   Test Purpose:     Second-Harmonic generation
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > rsp_2ndharm.mol <<'%EOF%'
BASIS
4-31G
Calculation of Second-Harmonic

    2    2  X  Y    1 1.00D-12
        1.0   1
H           .0000000000             .0000000000            2.0969699107
        3.0   1
Li          .0000000000             .0000000000            -.9969699107
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > rsp_2ndharm.dal <<'%EOF%'
**DALTON INPUT
.RUN RESPONS
**WAVE FUNCTIONS
.HF
.MP2
.MCSCF
*SCF INPUT
.DOUBLY OCCUPIED
 2 0 0 0
*CONFIGURATION INPUT
.INACTIVE
 1 0 0 0
.ELECTRONS
 2
.CAS SPACE
 2 0 0 0
.SYMMET
 1
.SPIN MULT
 1
**RESPONS
*QUADRATIC
.DIPLEN
.SHG
.FREQUE
 2
0.00 0.03
**END OF DALTON INPUT
%EOF%
#######################################################################



#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >rsp_2ndharm.check
cat >>rsp_2ndharm.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# Basis set
CRIT1=`$GREP "H * 1 * 1\.0000 * 4 * 2 * \[4s\|2s\]" $log | wc -l`
CRIT2=`$GREP "Li * 1 * 3\.0000 * 17 * 9 * \[8s3p\|3s2p\]" $log | wc -l`
CRIT3=`$GREP "total\: * 2 * 4\.0000 * 21 * 11" $log | wc -l`
TEST[1]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[1]=3
ERROR[1]="BASIS SET NOT READ CORRECTLY"

# Geometry
CRIT1=`$GREP "Total number of coordinates\: * 6" $log | wc -l`
CRIT2=`$GREP "1 * x * (0| )\.0000000000" $log | wc -l`
CRIT3=`$GREP "2 * y * (0| )\.0000000000" $log | wc -l`
CRIT4=`$GREP "3 * z * 2\.0969699107" $log | wc -l`
CRIT5=`$GREP "4 * x * (0| )\.0000000000" $log | wc -l`
CRIT6=`$GREP "5 * y * (0| )\.0000000000" $log | wc -l`
CRIT7=`$GREP "6 * z * (\-0|\-)\.9969699107" $log | wc -l`
TEST[2]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7`
CTRL[2]=7
ERROR[2]="GEOMETRY NOT READ CORRECTLY"

# Symmetry
CRIT1=`$GREP "Number of coordinates in each symmetry\: * 2 * 2 * 2 * 0" $log | wc -l`
CRIT2=`$GREP "Number of orbitals in each symmetry\: * 7 * 2 * 2 * 0" $log | wc -l`
TEST[3]=`expr	$CRIT1 \+ $CRIT2`
CTRL[3]=2
ERROR[3]="SYMMETRY NOT CORRECT"

# Energies
CRIT1=`$GREP "Hartree\-Fock total energy \: * \-7\.9773493[6-7]" $log | wc -l`
CRIT2=`$GREP "\= MP2 second order energy \: * \-7\.9901927" $log | wc -l`
CRIT3=`$GREP "Final MCSCF energy\: * \-7\.9941305[2-3]" $log | wc -l`
TEST[4]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[4]=3
ERROR[4]="ENERGIES NOT CORRECT"

# Response setup
CRIT1=`$GREP "Quadratic Response calculation" $log | wc -l`
CRIT2=`$GREP "First hyperpolarizability calculation \: HYPCAL\= T" $log | wc -l`
CRIT3=`$GREP "Spin of operator A \, ISPINA\= * 0" $log | wc -l`
CRIT4=`$GREP "Spin of operator B \, ISPINB\= * 0" $log | wc -l`
CRIT5=`$GREP "Spin of operator C \, ISPINC\= * 0" $log | wc -l`
CRIT6=`$GREP "2 B\-frequencies * 0*\.000000(D|E)\+00 * 3\.000000(D|E)\-02" $log | wc -l`
CRIT7=`$GREP "2 C\-frequencies * 0*\.000000(D|E)\+00 * 3\.000000(D|E)\-02" $log | wc -l`
CRIT8=`$GREP "Second harmonic generation * \: SHG\= T" $log | wc -l`
CRIT9=`$GREP "Direct one\-index transformation * \: DIROIT\= T" $log | wc -l`
CRIT10=`$GREP "1 A OPERATORS OF SYMMETRY NO\: * 1 AND LABELS\:" $log | wc -l`
CRIT11=`$GREP "1 A OPERATORS OF SYMMETRY NO\: * 2 AND LABELS\:" $log | wc -l`
CRIT12=`$GREP "1 A OPERATORS OF SYMMETRY NO\: * 3 AND LABELS\:" $log | wc -l`
CRIT13=`$GREP "1 B OPERATORS OF SYMMETRY NO\: * 1 AND LABELS\:" $log | wc -l`
CRIT14=`$GREP "1 B OPERATORS OF SYMMETRY NO\: * 2 AND LABELS\:" $log | wc -l`
CRIT15=`$GREP "1 B OPERATORS OF SYMMETRY NO\: * 3 AND LABELS\:" $log | wc -l`
CRIT16=`$GREP "1 C OPERATORS OF SYMMETRY NO\: * 1 AND LABELS\:" $log | wc -l`
CRIT17=`$GREP "1 C OPERATORS OF SYMMETRY NO\: * 2 AND LABELS\:" $log | wc -l`
CRIT18=`$GREP "1 C OPERATORS OF SYMMETRY NO\: * 3 AND LABELS\:" $log | wc -l`
TEST[5]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10 \+ $CRIT11 \+ $CRIT12 \+ \
		$CRIT13 \+ $CRIT14 \+ $CRIT15 \+ $CRIT16 \+ $CRIT17 \+ $CRIT18`
CTRL[5]=18
ERROR[5]="RESPONSE CALCULATION NOT SET UP CORRECTLY"

# Linear response
CRIT1=`$GREP "Value of linear response.*\: * 27\.196" $log | wc -l`
CRIT2=`$GREP "Value of linear response.*\: * 28\.520" $log | wc -l`
CRIT3=`$GREP "Value of linear response.*\: * 32\.016" $log | wc -l`
CRIT4=`$GREP "Value of linear response.*\: * 33\.212" $log | wc -l`
TEST[6]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
CTRL[6]=6
ERROR[6]="LINEAR RESPONSE NOT CORRECT"

# Quadratic response
CRIT1=`$GREP "\@ B\-freq \= (0| )\.000000 * C\-freq \= (0| )\.000000 * beta\(Z\;Z\,Z\) \= * 1618\.18" $log | wc -l`
CRIT2=`$GREP "\@ B\-freq \= (0| )\.030000 * C\-freq \= (0| )\.030000 * beta\(Z\;Z\,Z\) \= * 2395\.85" $log | wc -l`
CRIT3=`$GREP "\@ B\-freq \= (0| )\.000000 * C\-freq \= (0| )\.000000 * beta\(X\;X\,Z\) \= * 997\.09" $log | wc -l`
CRIT4=`$GREP "\@ B\-freq \= (0| )\.030000 * C\-freq \= (0| )\.030000 * beta\(X\;X\,Z\) \= * 1250\.02" $log | wc -l`
CRIT5=`$GREP "\@ B\-freq \= (0| )\.000000 * C\-freq \= (0| )\.000000 * beta\(Y\;Y\,Z\) \= * 997\.09" $log | wc -l`
CRIT6=`$GREP "\@ B\-freq \= (0| )\.030000 * C\-freq \= (0| )\.030000 * beta\(Y\;Y\,Z\) \= * 1250\.02" $log | wc -l`
CRIT7=`$GREP "\@ B\-freq \= (0| )\.000000 * C\-freq \= (0| )\.000000 * beta\(X\;Z\,X\) \= beta\(X\,X\,Z\)" $log | wc -l`
CRIT8=`$GREP "\@ B\-freq \= (0| )\.030000 * C\-freq \= (0| )\.030000 * beta\(X\;Z\,X\) \= beta\(X\,X\,Z\)" $log | wc -l`
CRIT9=`$GREP "\@ B\-freq \= (0| )\.000000 * C\-freq \= (0| )\.000000 * beta\(Z\;X\,X\) \= beta\(X\,X\,Z\)" $log | wc -l`
CRIT10=`$GREP "\@ B\-freq \= (0| )\.030000 * C\-freq \= (0| )\.030000 * beta\(Z\;X\,X\) \= * 1297\.50" $log | wc -l`
CRIT11=`$GREP "\@ B\-freq \= (0| )\.000000 * C\-freq \= (0| )\.000000 * beta\(Y\;Z\,Y\) \= beta\(Y\,Y\,Z\)" $log | wc -l`
CRIT12=`$GREP "\@ B\-freq \= (0| )\.030000 * C\-freq \= (0| )\.030000 * beta\(Y\;Z\,Y\) \= beta\(Y\,Y\,Z\)" $log | wc -l`
CRIT13=`$GREP "\@ B\-freq \= (0| )\.000000 * C\-freq \= (0| )\.000000 * beta\(Z\;Y\,Y\) \= beta\(Y\,Y\,Z\)" $log | wc -l`
CRIT14=`$GREP "\@ B\-freq \= (0| )\.030000 * C\-freq \= (0| )\.030000 * beta\(Z\;Y\,Y\) \= * 1297\.50" $log | wc -l`
TEST[7]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10 \+ $CRIT11 \+ $CRIT12 \+ \
		$CRIT13 \+ $CRIT14`
CTRL[7]=14
ERROR[7]="QUADRATIC RESPONSE NOT CORRECT"

PASSED=1
for i in 1 2 3 4 5 6 7
do
   if [ ${TEST[i]} -lt ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
