#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Atoms and their geometry are read in Z-matrix format')
f.add(string = 'Symmetry class found:')
f.add(string = 'The following symmetry elements were found:')
f.add(string = 'Full point group is:')
f.add(string = 'Represented as:')

f.add(string = 'Nuclear repulsion energy :',
      rel_tolerance = 1.0e-12)

f.add(string = 'Final HF energy:',
      rel_tolerance = 1.0e-12)

test.run(['energy_zmat.dal'], ['energy_zmat.mol'], f={'out': f})

sys.exit(test.return_code)
