! Autogenerated file, do not edit
module xcfun_autogen
  integer, parameter :: XC_MAX_ORDER = 3
  integer, parameter :: XC_NR_FUNCTIONALS = 8
  integer, parameter :: XC_NR_PARAMETERS_AND_FUNCTIONALS = 9
  integer, parameter :: XC_NR_VARS = 20

!Functionals
  integer, parameter :: XC_SLATERX = 0
  integer, parameter :: XC_VWN5C = 1
  integer, parameter :: XC_PBEC = 2
  integer, parameter :: XC_PBEX = 3
  integer, parameter :: XC_BECKEX = 4
  integer, parameter :: XC_BECKECORRX = 5
  integer, parameter :: XC_BECKESRX = 6
  integer, parameter :: XC_LYPC = 7

!Parameters
  integer, parameter :: XC_RANGESEP_MU = 8

  integer, parameter :: XC_A = 0
  integer, parameter :: XC_N = 1
  integer, parameter :: XC_A_B = 2
  integer, parameter :: XC_N_S = 3
  integer, parameter :: XC_A_GAA = 4
  integer, parameter :: XC_N_GNN = 5
  integer, parameter :: XC_A_B_GAA_GAB_GBB = 6
  integer, parameter :: XC_N_S_GNN_GNS_GSS = 7
  integer, parameter :: XC_A_GAA_LAPA = 8
  integer, parameter :: XC_A_GAA_TAUA = 9
  integer, parameter :: XC_N_GNN_LAPN = 10
  integer, parameter :: XC_N_GNN_TAUN = 11
  integer, parameter :: XC_A_B_GAA_GAB_GBB_LAPA_LAPB = 12
  integer, parameter :: XC_A_B_GAA_GAB_GBB_TAUA_TAUB = 13
  integer, parameter :: XC_N_S_GNN_GNS_GSS_LAPN_LAPS = 14
  integer, parameter :: XC_N_S_GNN_GNS_GSS_TAUN_TAUS = 15
  integer, parameter :: XC_A_2ND_TAYLOR = 16
  integer, parameter :: XC_A_B_2ND_TAYLOR = 17
  integer, parameter :: XC_N_2ND_TAYLOR = 18
  integer, parameter :: XC_N_S_2ND_TAYLOR = 19
end module
