#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from runtest_lsdalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final HF energy',
      rel_tolerance = 1.0e-8)
f.add(string = 'Nuclear repulsion',
      rel_tolerance = 1.0e-8)
f.add(string = 'Correlation energy',
      rel_tolerance = 1.0e-6)

f.add(string = 'Allocated memory (TOTAL)')

test.run(['fullmp3_energy.dal'], ['h2o.mol'], {'out': f})

sys.exit(test.return_code)
