#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > pbc2_h2fock.info <<'%EOF%'
   pbc2_h2fock
   -------------
   Molecule:         H2
   Wave Function:    HF/4-31G,Ahlrichs-Coulomb-Fit
   Test Purpose:     Check first fock matrix
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > pbc2_h2fock.mol <<'%EOF%'
BASIS
4-31G Aux=Ahlrichs-Coulomb-Fit
LDA molecular hessian without symmetry
Ethane LDA molecular hessian without symmetry
Atomtypes=1 Charge=0 Nosymmetry PBC
        1.    2
H     4.6000000000      0.0000000000     0.0000000000
H     -4.6000000000      0.0000000000     0.0000000000
a1 = 10.0 0.0 0.0 active
a2 = 0.0 10.0 0.0 inactive
a3 = 0.0 0.0 10.0 inactive
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > pbc2_h2fock.dal <<'%EOF%'
**INTEGRALS
.THRESH
1.0D-18
.NOLINK
.NO PS
.NO CS
**WAVE FUNCTIONS
.HF
*DENSOPT
.START
H1DIAG
.NOGCBASIS
**PBC
.WRITE TO FILE
.TESTCASE
.MLMAX
15
.DIIS
0 7 1.0E-8
.LATTICE
10 3
.NFIELD
6
.NDENSMATCUTOFF
6
.RECLAT
5 1 1
*END OF INPUT
%EOF%

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >pbc2_h2fock.check
cat >> pbc2_h2fock.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# ENERGY test
CRIT1=`$GREP "numbers of lattice vectors * 21" $log | wc -l`
TEST[1]=`expr  $CRIT1`
CTRL[1]=1
ERROR[1]="Number of lattice vectors not correct -"

CRIT1=`$GREP "number of basis * 4" $log | wc -l`
TEST[2]=`expr  $CRIT1`
CTRL[2]=1
ERROR[2]="Basis not correct"

# Memory test
CRIT1=`$GREP "Allocated memory \(TOTAL\): * 0 byte" $log | wc -l`
TEST[3]=`expr  $CRIT1`
CTRL[3]=1
ERROR[3]="Memory leak -"

PASSED=1
for i in 1 2 3 
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
      echo ${ERROR[i]}
      PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
   echo TEST ENDED PROPERLY
   exit 0
else
   echo THERE IS A PROBLEM
   exit 1
fi

%EOF%
#######################################################################
