coverage:
  precision: 2
  round: nearest
  range: 50..100
  status:
    project:
      default:
        enabled: yes
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        enabled: yes
        target: auto
        threshold: 1%
        base: auto
    changes:
      default:
        enabled: no