fedora-26_gcc-7.1.1:
    image:
        foeroyingur/fedora:26
    variables:
        GIT_SUBMODULE_STRATEGY: "recursive"
        GIT_SSL_NO_VERIFY: "true"
    script:
        - python setup --coverage --type=debug
        - cd build
        - make
        - ctest -L essential
        - ctest -D ExperimentalCoverage