#  -- File: Makefile
#     Purpose: Dalton
#
include ./Makefile.config

# OBS! DALTON_LIBS, MODULES and SUBDIRS must be modified at the same time!
#
DALTON_LIBS =      \
-Labacus -labacus  \
-Lrsp -lrsp        \
-Lsirius -lsirius  \
-labacus           \
-Leri -leri        \
-Ldensfit -ldensfit\
-Lcc  -lcc         \
-Ldft -ldft        \
-Lsoppa -lsoppa    \
-Llucita -llucita  \
-Lcholes -lcholes  \
-Lgp -lgp          \
-Lpdpack -lpdpack

#NB! LUCITA_OBJ must be before GP_OBJ because it creates .mod files used in gp/
#NB! GP_OBJ must be before SIR_OBJ because it creates .mod files used in sirius/

MODULES = MAIN_OBJ ABA_OBJ LUCITA_OBJ GP_OBJ SIR_OBJ RSP_OBJ SLAVE_OBJ ERI_OBJ \
	DFIT_OBJ PD_OBJ CC_OBJ DFT_OBJ AMFI_OBJ SOP_OBJ CHOLESKY_OBJ

SUBDIRS = abacus sirius rsp gp cc eri densfit pdpack dft amfi soppa choles lucita

# ---------------

OBJSLAVE = abacus/herpar.o eri/eri2par.o

OBJNODE  = eri/eriprg.o

OBJSAMFI = amfi/amfi.o amfi/symtra.o

OBJS_MPI_DUMMY = gp/mpi_dummy.o gp/mpi_dummyc.o
#
#     target "dalton" checks if files generated by configure are older
#     than configure:
#     p.t. the dalton script "dalton" and Makefile.config
#
dalton: $(INSTALLDIR)/dalton Makefile.config

$(INSTALLDIR)/dalton: ./dalton.gnr $(INSTALLDIR)/dalton.setup
	@echo "---------------> Updating dalton script because dalton.setup or dalton.gnr changed ..."
	cat $(INSTALLDIR)/dalton.setup ./dalton.gnr > $(INSTALLDIR)/dalton
	chmod 755 $(INSTALLDIR)/dalton

$(INSTALLDIR)/dalton.setup: configure
	$(warning "---------------> dalton.setup non-existent or older than configure")
	$(error "-----------> Please rerun configure (or touch $(INSTALLDIR)/dalton.setup)")

# running make revealed that Makefile.config is automatically a target
# because it enters in an include statement.
Makefile.config: configure
	$(warning "---------------> Makefile.config non-existent or older than configure")
	$(error "-----------> Please rerun configure (or touch Makefile.config)")

#
#     Most common build of Dalton
#
dalton.x: $(MODULES)
	@echo "---------------> Linking sequential dalton.x ..."
	$(LOADER) $(FFLAGS) \
	-o ./dalton.x abacus/dalton.o $(OBJSLAVE) \
	$(OBJSAMFI) $(OBJS_MPI_DUMMY) $(DALTON_LIBS) $(LIBS)
	mv ./dalton.x $(INSTALLDIR)/dalton.x
#
#       Linux version of the program
#
linux.x: $(MODULES)
	@echo "---------------> Linking sequential dalton.x for linux ..."
	$(LOADER) $(FFLAGS) \
	-o ./dalton.x abacus/dalton.o \
	$(OBJSLAVE) $(OBJSAMFI) $(OBJS_MPI_DUMMY) $(DALTON_LIBS) $(LIBS)
	mv ./dalton.x $(INSTALLDIR)/dalton.x
#
#     Linux MPI parallel build (first create sequential build dalton.x, then dalpar.x)
#
linuxparallel.x: linux.x
	@echo "---------------> Linking parallel dalpar.x for linux ..."
	$(LOADER) $(FFLAGS) \
	-o ./dalpar.x abacus/dalton.o $(OBJSLAVE) $(OBJSAMFI) \
	$(DALTON_LIBS) $(LIBS) $(MPI_LIB_PATH) $(MPI_LIB)
	mv ./dalpar.x $(INSTALLDIR)/dalpar.x
#
#	MPI parallel build (first create sequential build dalton.x, then dalpar.x)
#
parallel.x: dalton.x
	@echo "---------------> Linking parallel dalpar.x ..."
	$(LOADER) $(FFLAGS) \
	-o ./dalpar.x abacus/dalton.o $(OBJSLAVE) $(OBJSAMFI) \
	$(DALTON_LIBS) $(LIBS) $(MPI_LIB_PATH) $(MPI_LIB)
	mv ./dalpar.x $(INSTALLDIR)/dalpar.x
#
#
#	Build with PVMe
#	We will never need MPILIB when using PVM
#       First build master, then slave
#
dalpvm.x: $(MODULES)
	$(LOADER) $(FFLAGS) \
	-o $(INSTALLDIR)/dalpvm.x abacus/dalton.o \
	$(OBJSLAVE) $(OBJSAMFI) $(LIBS) \
	$(DALTON_LIBS) $(PVM_LIB_PATH) \
	$(PVM_LIBS) $(PVM_INC_PATH)
	$(LOADER) $(FFLAGS) -o $(INSTALLDIR)/node.x $(OBJNODE) $(OBJSLAVE) \
	$(OBJSAMFI) $(LIBS) $(DALTON_LIBS) $(PVM_LIB_PATH) \
	$(PVM_LIBS)  $(PVM_INC_PATH)
#
#	Not tested MPI on Cray yet. Thus no MPILIB, and no OBJSMXM nor
#	OBJSEIS
#
cray.x: $(MODULES)
	$(LOADER) $(FFLAGS) -o $(INSTALLDIR)/dalton.x \
	$(OBJSLAVE) $(OBJSAMFI) $(LIBS) $(DALTON_LIBS)
#
#	This is a proper build for the Cray-T3D
#
t3d.x: $(MODULES)
	$(LOADER) $(FFLAGS) $(MPI_LIB_PATH) $(MPI_LIB) \
	-o $(INSTALLDIR)/dalpar.x $(OBJSLAVE) \
	$(LIBS) $(OBJSAMFI) $(DALTON_LIBS)

t90.x: $(MODULES)
	$(LOADER) $(FFLAGS) $(MPI_LIB_PATH) $(MPI_LIB) \
	-o $(INSTALLDIR)/dalpar.x $(IO_OBJS) $(OBJSLAVE) \
	$(LIBS) $(OBJSAMFI) $(DALTON_LIBS)
#
#	Update all dependencies
#
depend :
	for i in $(SUBDIRS); do ( cd $$i  && $(MAKE) $@ ); done
#
#	Make it a bit cleaner, remover all .o/.lst/*.f -files
#
clean :
	for i in $(SUBDIRS); do ( cd $$i  && $(MAKE) $@ ); done
	$(RM) -f *~
	$(RM) -f modules/*.mod
#
#	We remove the entire source code as well if we do not plan to debug
#
veryclean :
	$(RM) -rf abacus sirius rsp gp include eri densfit pdpack cc dft

MAIN_OBJ :
	cd abacus && $(MAKE) main

ABA_OBJ :
	cd abacus && $(MAKE) all

LUCITA_OBJ :
	cd lucita && $(MAKE) all

SIR_OBJ :
	cd sirius && $(MAKE) all

RSP_OBJ :
	cd rsp && $(MAKE) all

GP_OBJ :
	cd gp && $(MAKE) all

SLAVE_OBJ :
	cd abacus && $(MAKE) slave
	cd eri && $(MAKE) slave

NODE_OBJ :
	cd eri && $(MAKE) node

ERI_OBJ	:
	cd eri && $(MAKE) all

DFIT_OBJ	:
	cd densfit && $(MAKE) all

CC_OBJ	:
	cd cc && $(MAKE) all

DFT_OBJ	:
	cd dft && $(MAKE) all

SOP_OBJ	:
	cd soppa && $(MAKE) all

CHOLESKY_OBJ	:
	cd choles && $(MAKE) all

IO_OBJ	:
	cd cc && $(MAKE) io

PD_OBJ	:
	cd pdpack && $(MAKE) all

AMFI_OBJ :
	cd amfi && $(MAKE) all

ftnchek: pre
	ftnchek $(CHEKFLAGS) */*.i > dalton.ftnchek

pre :
	for i in $(SUBDIRS); do ( cd $$i  && $(MAKE) $@ ); done

check:
	cd test && ./TEST -y -q short

# -- end of Dalton Makefile --
