#!/usr/bin/env python
# vim:ft=python
#
# primitive frontend to cmake
# (c) Radovan Bast <radovan.bast@uit.no>
# (c) Jonas Juselius <jonas.juselius@uit.no>
# licensed under the GNU Lesser General Public License

import os
import sys
import string
import re
import subprocess
from optparse import OptionParser, OptionGroup

if sys.version < '2.4':
    print('requires python version >= 2.4')
    sys.exit(1)

root_directory = os.path.realpath(__file__)[:-5]
default_path = root_directory + 'build/'

# define example usage

usage = '''
  Example: ./%prog --fc=gfortran --cc=gcc'''

# initialize parser

parser = OptionParser(usage)

# define options

group = OptionGroup(parser, 'Basic options')
group.add_option('--fc',
        action='store',
        default=None,
        help='set the Fortran compiler [default: pick automatically or based on FC=...]',
        metavar='STRING')
group.add_option('--cc',
        action='store',
        default=None,
        help='set the C compiler [default: pick automatically or based on CC=...]',
        metavar='STRING')
group.add_option('--cxx',
        action='store',
        default=None,
        help='set the C++ compiler [default: pick automatically or based on CXX=...]',
        metavar='STRING')
group.add_option('--mpi',
        action='store_true',
        default=False,
        help='build using MPI parallelization [default: %default]')
group.add_option('--openmp',
        action='store_true',
        default=False,
        help='enable OpenMP [default: %default]')
group.add_option('--math-dir',
        action='store',
        default=None,
        help='directory containing math libraries [default: pick automatically based on MATH_ROOT (see INSTALL.rst)]',
        metavar='PATH')
group.add_option('--internal-math',
        action='store_true',
        default=False,
        help='force the use of internal math library [default: %default]')
group.add_option('--int64',
        action='store_true',
        default=False,
        help='build for 64bit integers [default: %default]')
group.add_option('--show',
        action='store_true',
        default=False,
        help='show cmake command and exit [default: %default]')
parser.add_option_group(group)

group = OptionGroup(parser, 'Change default paths')
group.add_option('--build-dir',
        action='store',
        default=default_path,
        help='set the build path (you can build several binaries with the same source) [default: %default]',
        metavar='PATH')
group.add_option('--prefix',
        action='store',
        default=None,
        help='set the install path for make install [default: %default]',
        metavar='PATH')
group.add_option('--cmake',
        action='store',
        dest='alternative_cmake',
        default=None,
        help='give full path to alternative cmake binary (use this if default cmake is too old)',
        metavar='PATH')
parser.add_option_group(group)

group = OptionGroup(parser, 'Advanced options')
group.add_option('--math',
        action='store',
        default=None,
        help='explicit linker specification for math library',
        metavar='STRING')
group.add_option('--force',
        action='store_true',
        default=False,
        help='Run setup even if build directory exists [default: %default]')
group.add_option('--debug',
        action='store_true',
        default=False,
        help='build in debug mode (no optimization) [default: %default]')
group.add_option('--check',
        action='store_true',
        default=False,
        help='enable bounds checking [default: %default]')
group.add_option('--coverage',
        action='store_true',
        default=False,
        help='enable code coverage [default: %default]')
group.add_option('--nochecks',
        action='store_true',
        default=False,
        help='disable compatibility checks [default: %default]')
group.add_option('--int32_mpi',
        action='store_true',
        default=False,
        help='build with interface to 32bit integer MPI library \
             (if 64bit integers is set to default in the main program) \
             [default: %default]')
group.add_option('--static',
        action='store_true',
        default=False,
        help='link statically [default: %default]')
group.add_option('-D',
        action="append",
        dest='define',
        default=[],
        help='forward directly to cmake (example: -D ENABLE_THIS=1 -D ENABLE_THAT=1); \
                you can also forward CPP defintions all the way to the program \
                (example: -D CPP="-DDEBUG")',
                metavar='STRING')
group.add_option('--host',
        action='store',
        default=None,
        help="use predefined defaults for 'host'",
        metavar='STRING')
group.add_option('--generator',
        action='store',
        default=None,
        help='set the cmake generator [default: %default]',
        metavar='STRING')
group.add_option('--gen1int-dir',
                 action='store',
                 default=None,
                 help='path to Gen1Int library [default: %default]',
                 metavar='PATH')
parser.add_option_group(group)

# process input

(args, unused) = parser.parse_args()

def check_cmake_exists():
    p = subprocess.Popen('cmake --version',
            shell=True,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE)
    if not ('cmake version' in p.communicate()[0]):
        print('   This code is built using CMake')
        print('')
        print('   CMake is not found')
        print('   get CMake at http://www.cmake.org/')
        print('   on many clusters CMake is installed')
        print('   but you have to load it first:')
        print('   $ module load cmake')
        sys.exit()

def gen_cmake_command():
    # create cmake command from flags

    command = ''

    if args.fc:
        command += ' FC=%s' % args.fc
    if args.cc:
        command += ' CC=%s' % args.cc
    if args.cxx:
        command += ' CXX=%s' % args.cxx

    if args.alternative_cmake:
        command += ' %s' % args.alternative_cmake
    else:
        command += ' cmake'

    if args.int64:
        command += ' -DENABLE_64BIT_INTEGERS=ON'

    if args.int32_mpi:
        command += ' -DENABLE_32BIT_MPI_INTERFACE=ON'

    if args.fc and (os.path.basename(args.fc)[:2].lower() == 'mp'):
        # if fc starts with 'mp' turn on mpi
        # it is possible to call compilers with long paths
            args.mpi = True

    if args.mpi:
        command += ' -DENABLE_MPI=ON'

    if args.openmp:
        command += ' -DENABLE_OPENMP=ON'

    if args.internal_math:
        command += ' -DENABLE_INTERNAL_MATH=ON'
    elif args.math:
            command += ' -DUSERDEFINED_MATH="%s"' % args.math
    elif args.math_dir:
            if not os.path.exists(args.math_dir):
                    print("Specified MATH directory does not exist!")
                    sys.exit(1)
            command += ' -DMATH_ROOT="%s"' % args.math_dir

    if args.check:
        command += ' -DENABLE_BOUNDS_CHECK=ON'

    if args.coverage:
        command += ' -DENABLE_CODE_COVERAGE=ON'

    if args.nochecks:
        command += ' -DENABLE_SANITY_CHECKS=OFF'

    if args.static:
        command += ' -DENABLE_STATIC_LINKING=ON'

    if args.prefix:
        command += ' -DCMAKE_INSTALL_PREFIX=' + args.prefix

    if args.debug:
        command += ' -DCMAKE_BUILD_TYPE=Debug'
    else:
        command += ' -DCMAKE_BUILD_TYPE=Release'

    if args.define:
        for definition in args.define:
            command += ' -D%s' % definition

    if args.generator:
        command += ' -Wno-dev -G "%s"' % args.generator

    # enables Gen1Int module by defining its path
    if args.gen1int_dir:
        command += ' -DENABLE_GEN1INT=ON'
        command += ' -DLIB_GEN1INT_PATH="%s"' % args.gen1int_dir

    command += ' %s' % root_directory

    print('%s\n' % command)
    if args.show:
        sys.exit()
    return command

def print_build_help(build_path):
    print('   configure step is done')
    print('   now you need to compile the sources')
    print('')
    print('   to compile with configured parameters (recommended):')
    print('   $ cd ' + build_path)
    print('   $ make')
    print('')
    print('   to modify configured parameters and then compile:')
    print('   $ cd ' + build_path)
    print('   $ ccmake ' + root_directory)
    print('   $ make')

def gen_reconfigure_script(command, build_path):
    if sys.platform != "win32":
        file_name = os.path.join(build_path, 'reconfigure')
    else:
        file_name = os.path.join(build_path, 'reconfigure.bat')
    f = open(file_name, 'w')
    if sys.platform != "win32":
        f.write('#!/bin/sh \n')
    f.write('%s' % command)
    f.close()
    if sys.platform != "win32":
        os.system('chmod 700 %s' % file_name)

def save_setup_command(argv, build_path):
    file_name = os.path.join(build_path, 'setup_command')
    f = open(file_name, 'w')
    f.write(" ".join(sys.argv[:]))
    f.close()

def setup_build_path(build_path, only_show_command):
    if args.show:
        return
    if os.path.isdir(build_path):
        if not only_show_command:
            if args.force:
                fname = os.path.join(build_path, 'CMakeCache.txt')
                if os.path.exists(fname):
                    os.unlink(fname)
            else:
                print('aborting setup - build directory %s exists already' % build_path)
                print('please first remove it and then rerun setup')
                sys.exit()
    else:
        os.makedirs(build_path, 0755)

def run_cmake(command, build_path):
    topdir = os.getcwd()
    os.chdir(build_path)
    p = subprocess.Popen(command,
            shell=True,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE)
    s = p.communicate()[0]
    print(s)
    os.chdir(topdir)
    return s

def main():
    check_cmake_exists()
    build_path = args.build_dir
    if not configure_host():
        configure_default_compilers()
    command = gen_cmake_command()
    setup_build_path(build_path, args.show)
    status = run_cmake(command, build_path)

    if not 'Configuring incomplete' in status:
        gen_reconfigure_script(command, build_path)
        save_setup_command(sys.argv, build_path)
        print_build_help(build_path)

# host/system specific configurations
def configure_host():
    if args.host:
        host = args.host
    else:
        u = os.uname()
        host = string.join(u)
    msg = None
    # Generic systems
    if re.search('ubuntu', host, re.I):
        msg = "Configuring system: Ubuntu"
        configure_ubuntu()
    if re.search('fedora', host, re.I):
        msg = "Configuring system: Fedora"
        configure_fedora()
    if re.search('osx', host, re.I):
        msg = "Configuring system: MacOSX"
        configure_osx()
    if msg is None:
        return False
    if not args.show:
        print msg
    return True

def configure_default_compilers():
    if not args.cc:
        args.cc = 'gcc'
    if not args.cxx:
        args.cxx = 'g++'
    if not args.fc:
        args.fc = 'gfortran'
    if args.mpi:
        args.fc = 'mpif90'
        args.cc = 'mpicc'
        args.cxx = 'mpicxx'

configure_ubuntu = configure_default_compilers
configure_fedora = configure_default_compilers
configure_osx = configure_default_compilers

if __name__ == '__main__':
    main()
