#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(from_string = 'Polarizable embedding energy contributions:',
      num_lines = 16,
      abs_tolerance = 1.0e-5)

test.run(['zeromul.dal'], ['acrolein.mol'], ['2h2o.pot'], f={'out': f})

g = Filter()
g.add(from_string = 'Polarizable embedding energy contributions:',
      num_lines = 10,
      abs_tolerance = 1.0e-5)

test.run(['zeropol.dal'], ['acrolein.mol'], ['2h2o.pot'], f={'out': g})

sys.exit(test.return_code)
