#!/usr/bin/env python
#  newccsdpt_h2o
#  -------------
#  Molecule:         H2O
#  Wave Function:    CCSD(T)
#  Test Purpose:     test new CCSD(T) ground state energy


import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Total energy MLCCSD(T):',
      abs_tolerance = 1.0e-5)

test.run(['newccsdpt_h2o.dal'], ['newccsdpt_h2o.mol'], f={'out': f},
         accepted_errors=['not implemented for parallel calculations.'])

sys.exit(test.return_code)
