#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(re = '[XYZ]DIPLEN  \; [XYZ]DIPLEN',
      abs_tolerance = 5.0e-5)

test.run(['pehf_alpha.dal'], ['pehf_alpha.mol'], ['pehf_alpha.pot'], f={'out': f})

sys.exit(test.return_code)
