#!/usr/bin/env python


import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

# dipole
f.add(from_string = 'Dipole moment',
      num_lines = 5,
      mask = [1],
      rel_tolerance = 1.0e-5)

# nuc
f.add(string = 'Nuclear repulsion energy',
      rel_tolerance = 1.0e-10)

# tes
f.add(string = 'Total number of tesserae',
      rel_tolerance = 1.0e-1)

# sym
f.add(string = 'Point group',
      rel_tolerance = 1.0e-5)

# cmass
#f.add(string = 'Center-of-mass',
#      rel_tolerance = 1.0e-5)

# gauge_or
f.add(string = 'Center of mass gauge origin',
      rel_tolerance = 1.0e-5)

f.add(from_string = 'Singlet electronic excitation energies',
      num_lines = 10,
      mask = [4],
      rel_tolerance = 1.0e-6)

f.add(from_string = 'Electric transition dipole moments',
      num_lines = 10,
      ignore_sign = True,
      abs_tolerance = 1.0e-4)

f.add(from_string = 'Magnetic transition dipole moments',
      num_lines = 12,
      ignore_sign = True,
      abs_tolerance = 1.0e-4)

f.add(from_string = 'Oscillator and Scalar Rotational Strengths',
      num_lines = 14,
      abs_tolerance = 1.0e-2)

test.run(['ECD.dal'], ['CH3CHFOH_cc-pVDZ.mol'], f={'out': f})

sys.exit(test.return_code)
