#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from runtest_lsdalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final HF energy',
      rel_tolerance = 1.0e-8)
f.add(string = 'Nuclear repulsion',
      rel_tolerance = 1.0e-8)

f.add(from_string = 'Permanent dipole moment',
      num_lines   = 4,
      abs_tolerance = 1.0e-4)
f.add(from_string = 'Dipole moment components',
      num_lines   = 6,
      ignore_below = 1.0e-7,
      abs_tolerance = 1.0e-4)

f.add(from_string = 'contribution to gradient',
      num_lines   = 5,
      ignore_below = 1.0e-7,
      abs_tolerance = 1.0e-6)
f.add(from_string = 'Molecular gradient',
      num_lines   = 5,
      ignore_below = 1.0e-7,
      abs_tolerance = 1.0e-6)
f.add(from_string = 'RMS gradient norm',
      abs_tolerance = 1.0e-6)

f.add(string = 'Allocated memory (TOTAL)')

test.run(['LSresponse_HF_molgra.dal'], ['HF.mol'], {'out': f})

sys.exit(test.return_code)
