#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final MC-SRDFT energy',
      rel_tolerance = 1.0e-7)
f.add(string = '-<< FC Li001 ; FC Li001 >>',
      rel_tolerance = 2.0e-4)
f.add(string = '-<< FC Li001 ; FC H 002 >>',
      rel_tolerance = 2.0e-4)
f.add(string = '-<< FC H 002 ; FC H 002 >>',
      rel_tolerance = 2.0e-4)


test.run(['rsp_mc_srPBE_fermi.dal'], ['lih.mol'], f={'out': f})

sys.exit(test.return_code)
