#!/usr/bin/env python
#    energy_symm
#    -----------
#    Molecule:         H2O
#    Wave Functions:   RHF, SOS-MP2, and MCSCF (CAS) / cc-pVDZ
#    Test Purpose:     Check energy calculation with symmetry and .NUCMOD option

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(re = 'Basis set used is \"cc-pVDZ\" from the basis set library\.')

f.add(from_string = 'Cartesian Coordinates',
      num_lines = 8,
      rel_tolerance = 1.0e-8)

f.add(string = 'Nuclear repulsion energy',
      rel_tolerance = 1.0e-10)

f.add(from_string = 'Wave function specification',
      num_lines = 20)

f.add(string = 'Number of coordinates in each symmetry')
f.add(string = 'Number of orbitals in each symmetry')

f.add(string = 'Hartree-Fock total energy',
      rel_tolerance = 1.0e-9)
f.add(string = 'MP2 second order energy',
      rel_tolerance = 1.0e-9)
f.add(string = 'Final MCSCF energy:',
      rel_tolerance = 1.0e-9)

f.add(from_string = 'Occupancies of natural orbitals',
      num_lines = 16,
      abs_tolerance = 1.0e-6)


test.run(['energy_symm.dal'], ['H2O_cc-pVDZ.mol'], f={'out': f})

sys.exit(test.return_code)
