#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from runtest_lsdalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final DFT energy',rel_tolerance = 1.0e-9)
f.add(string = '###',rel_tolerance = 1.0e-5,ignore_below = 1.0e-4)
f.add(string = 'Perform McWeeny purification')
f.add(string = 'Allocated memory (TOTAL)')

test.run(['linsca_mwpurifyatomstart.dal'], ['HCN5.mol'], {'out': f})

sys.exit(test.return_code)
