#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f_hf = Filter()
f_hf.add(string = 'Nuclear repulsion:',
      rel_tolerance = 1.0e-7)
f_hf.add(string = 'Electronic energy:',
      rel_tolerance = 1.0e-7)
f_hf.add(string = 'Solvation energy:',
      abs_tolerance = 1.0e-7)
f_hf.add(string = 'Final HF energy:',
      rel_tolerance = 1.0e-7)

test.run(['extpcm_hf.dal', 'extpcm_hf_separate.dal'], ['CH4.mol', 'H2O.mol'], {'out': f_hf}, args = '-put @pcmsolver.inp')
# The following test does not run as the vectorized charge-attraction integrals have not been implemented yet
#test.run(['extpcm_hf_newint.dal'], ['CH4.mol', 'H2O.mol'], {'out': f_hf}, args = '-put @pcmsolver.inp')

f_dft = Filter()
f_dft.add(string = 'Nuclear repulsion:',
      rel_tolerance = 1.0e-7)
f_dft.add(string = 'Electronic energy:',
      rel_tolerance = 1.0e-7)
f_dft.add(string = 'Solvation energy:',
      abs_tolerance = 1.0e-7)
f_dft.add(string = 'Final DFT energy:',
      rel_tolerance = 1.0e-7)
test.run(['extpcm_lda.dal', 'extpcm_lda_separate.dal'], ['CH4.mol', 'H2O.mol'], {'out': f_dft}, args = '-put @pcmsolver.inp')

sys.exit(test.return_code)
