#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f_hf = Filter()
f_hf.add(string = 'Nuclear repulsion:',
      rel_tolerance = 1.0e-7)
f_hf.add(string = 'Electronic energy:',
      rel_tolerance = 1.0e-7)
f_hf.add(string = 'Solvation energy:',
      abs_tolerance = 1.0e-7)
f_hf.add(string = 'Final HF energy:',
      rel_tolerance = 1.0e-7)

# Small basis sets (without d-shell)
test.run(['extpcm_hf.dal', 'extpcm_hf_separate.dal'], ['CH4.mol', 'H2O.mol', 'H2O_symm.mol'], ['pcmsolver.pcm'], f={'out': f_hf})
test.run(['extpcm_hf_fastint.dal'], ['CH4.mol', 'H2O.mol'], ['pcmsolver.pcm'], f={'out': f_hf})
# Large basis sets (with d-shell)
#test.run(['extpcm_hf_fastint.dal'], ['H2O_6311++gss_cartesian.mol', 'H2O_6311++gss_spherical.mol'], ['pcmsolver.pcm'], f={'out': f_hf})

f_dft = Filter()
f_dft.add(string = 'Nuclear repulsion:',
      rel_tolerance = 1.0e-7)
f_dft.add(string = 'Electronic energy:',
      rel_tolerance = 1.0e-7)
f_dft.add(string = 'Solvation energy:',
      abs_tolerance = 1.0e-7)
f_dft.add(string = 'Final DFT energy:',
      rel_tolerance = 1.0e-7)

# Small basis sets (without d-shell)
test.run(['extpcm_lda.dal', 'extpcm_lda_separate.dal'], ['CH4.mol', 'H2O.mol', 'H2O_symm.mol'], ['pcmsolver.pcm'], f={'out': f_dft})
test.run(['extpcm_lda_fastint.dal'], ['CH4.mol', 'H2O.mol'], ['pcmsolver.pcm'], f={'out': f_dft})
# Large basis sets (with d-shell)
#test.run(['extpcm_lda_fastint.dal'], ['H2O_6311++gss_cartesian.mol', 'H2O_6311++gss_spherical.mol'], ['pcmsolver.pcm'], f={'out': f_dft})

sys.exit(test.return_code)
