#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(from_string = 'Embedding potential',
      num_lines = 1000,
      ignore_sign = True,
      abs_tolerance = 1.0e-5)

test.run(['pehf_trcube.dal'], ['pehf_trcube.mol'], ['pehf_trcube.pot'], f={'embedding_potential_002.cube': f}, args='-get "embedding_potential_002.cube"')

sys.exit(test.return_code)
