#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(string = '@ Oscillator strength (LENGTH)',
      ignore_below = 1.0e-4,
      ignore_sign = True,
      abs_tolerance = 1.0e-4)

f.add(re= '\@ STATE NO\:',
      ignore_sign = True,
      abs_tolerance = 1.0e-4)

test.run(['PE-TDHF.dal'], ['formamide.mol'], ['water.pot'], f={'out': f})

sys.exit(test.return_code)
