#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final HF-SRDFT energy',
      rel_tolerance = 1.0e-7)
f.add(string = '-<< FC H 001 ; FC H 001 >>',
      rel_tolerance = 2.0e-4)
f.add(string = '-<< FC H 001 ; FC H 002 >>',
      rel_tolerance = 2.0e-4)
f.add(string = '-<< FC H 002 ; FC H 002 >>',
      rel_tolerance = 2.0e-4)


test.run(['rsp_hf_srPBE_fermi_nosymm.dal'], ['h2.mol'], f={'out': f})

sys.exit(test.return_code)
