      INTEGER MXLRSO, MXLRSST
      PARAMETER ( MXLRSO = 1000, MXLRSST = 100)

      INTEGER NLRSOP, NXLRSST, NSELRS

      INTEGER IALRSOP, IBLRSOP, ILRSST, ISELRS

      LOGICAL LRS2N1,SELLRS,OSCSTR,VELSTR,MIXSTR,ROTLEN,ROTVEL
      LOGICAL RTNLEN,RTNVEL

      COMMON /INLRSD/ ILRSST(MXLRSST),ISELRS(MXLRSST,2),
     *                IALRSOP(MXLRSO),IBLRSOP(MXLRSO),
     *                NLRSOP,NSELRS,NXLRSST,LRS2N1,SELLRS,
     *                OSCSTR,VELSTR,MIXSTR,ROTLEN,ROTVEL,
     *                RTNLEN,RTNVEL


