      LOGICAL GCALC, G_ALL, ECC, MNFSO, TEST_AMFI, ADDSO
      LOGICAL DOALL, DORMC, DOGC1, DOGC2, DOOZSO1, DOOZSO2, DOOZSO
      LOGICAL SCALED_CHARGES, SPLITSO2
      DOUBLE PRECISION REFSPIN, GRELMC
      CHARACTER*80 G_LINE
      CHARACTER*8 ANGLBL(3), SOLBL(3,3)
      INTEGER NSO
      DOUBLE PRECISION GTENSOR(3,3), GC1(3,3), GC2(3,3), 
     &          GOZSO(3,3,3), ECCORG(3)
      COMMON /GMODULE/GTENSOR, REFSPIN, GRELMC, GC1, GC2,
     &                GOZSO, ECCORG, NSO,
     &                DOALL, DORMC, DOGC1, DOGC2, DOOZSO1, DOOZSO2,
     &                DOOZSO,
     &                G_LINE, ANGLBL, SOLBL,
     &                GCALC, G_ALL, ECC, MNFSO, TEST_AMFI, ADDSO,
     &                SCALED_CHARGES, SPLITSO2
