      LOGICAL TESTZY, DOSO1, DOSO2, X2MAT, A2MAT, X2GRAD, PHOSPH,
     &        MNFPHO
      PARAMETER (MXPHOS = 10)
      COMMON /INFHSO/PHOSMAT(3,3,MXPHOS), PHOSMN(3,3,MXPHOS),
     &               IPRHSO, TESTZY, DOSO1, DOSO2, X2MAT, A2MAT, X2GRAD,
     &               PHOSPH, MNFPHO
