subroutine print_binary_info()
#include "priunit.h"
    write(lupri, '(a)') ' Who compiled             | hubert@fe8'
    write(lupri, '(a)') ' System                   | Linux-2.6.32-279.el6.x86_64'
    write(lupri, '(a)') ' Processor                | x86_64'
    write(lupri, '(a)') ' 64-bit integers          | OFF'
    write(lupri, '(a)') ' MPI                      | OFF'
    write(lupri, '(a)') ' Fortran compiler         | /usr/bin/f95'
    write(lupri, '(a)') ' Fortran compiler version | GNU Fortran (GCC) 4.4.6 20120305 (Red Hat 4.4.6-4)'
    write(lupri, '(a)') ' Fortran flags            | -DVAR_GFORTRAN -DGFORTRAN=445 -g -fbacktrace -O0 -'
    write(lupri, '(a)') '                          | Wuninitialized'
    write(lupri, '(a)') ' C compiler               | /usr/bin/cc'
    write(lupri, '(a)') ' C compiler version       | unknown'
    write(lupri, '(a)') ' C flags                  | -std=c99 -DRESTRICT=restrict -DFUNDERSCORE=1 -O0 -'
    write(lupri, '(a)') '                          | g'
    write(lupri, '(a)') ' BLAS                     | /usr/lib64/atlas/libf77blas.so;/usr/lib64/atlas/li'
    write(lupri, '(a)') '                          | bcblas.so;/usr/lib64/atlas/libatlas.so'
    write(lupri, '(a)') ' LAPACK                   | /usr/lib64/liblapack.so'
    write(lupri, '(a)') ' Static linking           | OFF'
    write(lupri, '(a)') ' Last Git revision        | c9f0e2f'
    write(lupri, '(a)') ' Configuration time       | 2013-11-22 17:56:09.959375'
end subroutine
