#!/usr/bin/env python
#  newcc3_h2o
#  ------------
#  Molecule:         H2o
#  Wave Function:    CC3
#  Test Purpose:     test new CC3 grounds dn excited state


import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Total CC3   energy:',
      abs_tolerance = 1.0e-5)
f.add(from_string = 'Total energies in Hartree',
      num_lines = 3,
      abs_tolerance = 1.0e-5)

test.run(['newcc3_h2o.dal'], ['newcc3_h2o.mol'], f={'out': f},
         accepted_errors=['not implemented for parallel calculations.'])

sys.exit(test.return_code)
