#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > cc2_r12_aux_ch4_sym_fop.info <<'%EOF%'
   cc2_r12_aux_ch4_sym_fop
   -------------
   Molecule:         Methane (CH4)
   Wave Function:    CC2-R12 / 6-311G**
   Test Purpose:     Check CC2-R12 first order properties with symmetry
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > cc2_r12_aux_ch4_sym_fop.mol <<'%EOF%'
BASIS
6-311G** 6-311++G(3df,3pd)
CH4: CC2-R12/Ansatz1 first order properties with symmetry

    4    2 XY XZ
 1      6.    1
C      0.000000000000000   0.000000000000000   0.000000000000000       *
 1      1.    1
H      1.276731000000000   1.276731000000000   1.276731000000000       *
 2      6.    1
C      0.000000000000000   0.000000000000000   0.000000000000000       *
 2      1.    1
H      1.276731000000000   1.276731000000000   1.276731000000000       *
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > cc2_r12_aux_ch4_sym_fop.dal <<'%EOF%'
**DALTON INPUT
.RUN WAVE FUNCTION
.DIRECT
*MOLBAS
.R12AUX
**INTEGRALS
.R12
.DIPLEN
.SECMOM
**WAVE FUNCTIONS
.CC
*SCF INPUT
.THRESHOLD
 1.0D-10
*ORBITALS
.MOSTART
 H1DIAG
*CC INPUT
.CC2
.PRINT
 3
.FREEZE
 1 0
.THRENR
 1.0D-12
.THRLEQ
 1.0D-10
*CCFOP
.NONREL
.OPERAT
XDIPLEN
ZDIPLEN
XXSECMOM
YYSECMOM
*R12 INPUT
.CC2
 1A
#.NO HYB
#.R12XXL
#.NO B
#.NO A'
#.NO 2
.BASSCL
 0.5 2.0
**END OF DALTON INPUT
%EOF%

#######################################################################
 

#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >cc2_r12_aux_ch4_sym_fop.check
cat >>cc2_r12_aux_ch4_sym_fop.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi
#
#            Total SCF   energy:                   -40.1917720926
#            Total MP2-R12/A energy:               -40.3918078442
#            Total CC2-R12/A energy:               -40.3929123948
#
#
#                    XDIPLEN : zero by symmetry
#                    ZDIPLEN : zero by symmetry
#                    XXSECMOM:  12.93949468
#                    YYSECMOM:  12.93949468
#

CRIT1=`$GREP "Total MP2-R12/A energy: *-40\.391807844" $log | wc -l`
TEST[1]=`expr   $CRIT1`
CTRL[1]=2
ERROR[1]="MP2-R12/A ENERGY NOT CORRECT"
CRIT2=`$GREP "Total CC2-R12/A energy: *-40\.392912394" $log | wc -l`
TEST[2]=`expr   $CRIT2`
CTRL[2]=2
ERROR[2]="CC2-R12/A ENERGY NOT CORRECT"
#
CRIT3=`$GREP "XXSECMOM:  12\.93949468" $log | wc -l`
TEST[3]=`expr   $CRIT3`
CTRL[3]=1
ERROR[3]="CC2-R12/A XX-SECOND MOMENT OF CHARGE NOT CORRECT"
CRIT4=`$GREP "YYSECMOM:  12\.93949468" $log | wc -l`
TEST[4]=`expr   $CRIT4`
CTRL[4]=1
ERROR[4]="CC2-R12/A YY-SECOND MOMENT OF CHARGE NOT CORRECT"

PASSED=1
for i in 1 2 3 4  
do 
   if [ ${TEST[i]} -lt ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done 

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM 
  exit 1
fi

%EOF%
#######################################################################
