#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi
 
#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > cc3_findiff.info <<%EOF%
   cc3_findiff
   -----------
   Molecule:         HF
   Theory Level:     CC3 / 6-31G
   Test Purpose:     CC3 energy, dipole moment and polarizability
                     within an (unrelaxed) finite electric field
%EOF%

#######################################################################
#  INTEGRAL INPUT
#######################################################################
cat > cc3_findiff.mol <<%EOF%
BASIS
6-31G
CC3 polarizability
HF molecule
    2    0  X  Y  Z   1.00D-15
        9.0   1    2    1    1
F     0.0000000000000000   0.000000000   0.08729478
        1.0   1    1    1
H     0.0000000000000000   0.000000000  -1.64558444
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > cc3_findiff.dal <<%EOF%
**DALTON
.RUN WAVE FUNCTIONS
**INTEGRAL
.DIPLEN
**WAVE FUNCTION
.CC
*SCF INPUT
.THRESH
 1.0D-12
.NODIIS
*ORBITAL INPUT
.MOSTART
 H1DIAG
*CC INP
.FIELD
 0.0002
 ZDIPLEN
.CC3
.PRINT
 11
.THRENR
1.0D-12
.THRLEQ
1.0D-12
.MAX IT
 100
*CCFOP
.NONREL
.DIPMOM
*CCLR
.OPERATOR
ZDIPLEN ZDIPLEN
XDIPLEN XDIPLEN
XDIPLEN YDIPLEN
*CCQR
.OPERATOR
ZDIPLEN ZDIPLEN ZDIPLEN
XDIPLEN XDIPLEN ZDIPLEN
XDIPLEN YDIPLEN ZDIPLEN
ZDIPLEN YDIPLEN YDIPLEN
*NODDY
.FINDIF
**END OF DALTON
%EOF%
#######################################################################



#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL > cc3_findiff.check
cat >>cc3_findiff.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

if $GREP -q "not implemented for parallel calculations" $log; then
   echo "TEST ENDED AS EXPECTED"
   exit 0
fi

# SCF, MP2 and CC3 energies:
CRIT1=`$GREP "Total SCF   energy: * -99\.9834089353" $log | wc -l`
CRIT3=`$GREP "Total CC3   energy: * -100\.1153426681" $log | wc -l`
TEST[1]=`expr $CRIT1 \+ $CRIT3` 
CTRL[1]=4
ERROR[1]="ENERGIES IN FIELD NOT CORRECT"

# CC3 dipole moment in field :
 #Electronic dipole moment (au):  -0.000000000      -0.000000000     -0.5545260590E-04
CRIT1=`$GREP  "Electronic dipole moment" $log | $GREP "(-0|-)\.55452605..E-04" | wc -l`
TEST[2]=`expr $CRIT1`
CTRL[2]=1
ERROR[2]="CC3 DIPOLE MOMENT IN FIELD NOT CORRECT"

# CC3 polarizability in field:
CRIT1=`$GREP  "ZDIPLEN *\(unrel\.\) *( |-|-0|0)\.0000 *ZDIPLEN *\(unrel\.\) *( |-|-0|0)\.0000 *4\.002049" $log | wc -l`
CRIT2=`$GREP  "XDIPLEN *\(unrel\.\) *( |-|-0|0)\.0000 *XDIPLEN *\(unrel\.\) *( |-|-0|0)\.0000 *( |0)\.6876346" $log | wc -l`
CRIT3=`$GREP  "XDIPLEN *\(unrel\.\) *( |-|-0|0)\.0000 *YDIPLEN *\(unrel\.\) *( |-|-0|0)\.0000 *( |-|-0|0)\.0000000" $log | wc -l`
TEST[3]=`expr $CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[3]=3
ERROR[3]="CC3 POLARIZABILITY IN FIELD NOT CORRECT"

# CC3 hyperpolarizability in field:
CRIT1=`$GREP "ZDIPLEN *\(unrel\.\) *( |-|-0|0)\.0* *ZDIPLEN *\(unrel\.\) *( |-|-0|0)\.0* *ZDIPLEN *\(unrel\.\) *( |-|-0|0)\.0* * 18\.43617" $log | wc -l`
CRIT2=`$GREP "XDIPLEN *\(unrel\.\) *( |-|-0|0)\.0* *XDIPLEN *\(unrel\.\) *( |-|-0|0)\.0* *ZDIPLEN *\(unrel\.\) *( |-|-0|0)\.0* *( |0)\.9867656" $log | wc -l`
CRIT3=`$GREP "XDIPLEN *\(unrel\.\) *( |-|-0|0)\.0* *YDIPLEN *\(unrel\.\) *( |-|-0|0)\.0* *ZDIPLEN *\(unrel\.\) *( |-|-0|0)\.0* *( |-|-0|0)\.0000000" $log | wc -l`
CRIT4=`$GREP "ZDIPLEN *\(unrel\.\) *( |-|-0|0)\.0* *YDIPLEN *\(unrel\.\) *( |-|-0|0)\.0* *YDIPLEN *\(unrel\.\) *( |-|-0|0)\.0* *( |0)\.9867656" $log | wc -l`
TEST[4]=`expr $CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
CTRL[4]=4
ERROR[4]="CC3 HYPERPOLARIZABILITY IN FIELD NOT CORRECT"

PASSED=1
for i in 1 2 3 4
do 
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done 

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM 
  exit 1
fi

%EOF%
#######################################################################
