#!/bin/sh

info="
   dft_cr_sym
   ------------------
   Molecule:         H2O
   Wave Functions:   DFT B3LYP / STO-3G
   Test Purpose:     DFT B3LYP second-hyperpolarizabilities test w/ symmetry.
"

molecule="BASIS
3-21G
Water
STO-3G basis
    2    2  X  Z
        8.    1
O      .0000   -.2249  0.0000000000
        1.    1
H     1.4523    .8996   .0000000000
"

dalton="**DALTON INPUT
.RUN RESPONSE
**WAVE FUNCTIONS
.DFT
 B3LYP
*SCF INPUT
.THRESHOLD
1e-10
*DFT INPUT
.GRID TYPE
LMG BLOCK
**RESPONSE
*CUBIC
.DIPLEN
.BFREQ
2
0.0 0.067
.CFREQ
2
0.0 0.067
.DFREQ
2
0.0 0.067
**END OF DALTON INPUT
"

test="
check_scf_energy DFT -75.935844970093 4e-10
                     
check_second_hyperpolarizabilities 0.000 0.000 0.000 'X;X,X,X' 127.0193 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'X;X,Y,Y'  96.3888 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'X;Y,Y,X'  96.3888 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'X;Y,X,Y'  96.3888 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'X;X,Z,Z'  13.1980 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'X;Z,Z,X'  13.1980 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'X;Z,X,Z'  13.1980 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'Y;Y,X,X'  96.3888 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'Y;X,X,Y'  96.3888 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'Y;X,Y,X'  96.3888 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'Y;Y,Y,Y'  94.0823 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'Y;Y,Z,Z'  12.1059 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'Y;Z,Z,Y'  12.1059 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'Y;Z,Y,Z'  12.1059 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'Z;Z,X,X'  13.1980 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'Z;X,X,Z'  13.1980 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'Z;X,Z,X'  13.1980 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'Z;Z,Y,Y'  12.1059 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'Z;Y,Y,Z'  12.1059 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'Z;Y,Z,Y'  12.1059 1e-4
check_second_hyperpolarizabilities 0.000 0.000 0.000 'Z;Z,Z,Z'   2.1693 1e-4
                                                                        
check_second_hyperpolarizabilities 0.067 0.000 0.000 'X;X,X,X' 135.4111 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'X;X,Y,Y' 101.3452 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'X;Y,Y,X' 103.9403 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'X;Y,X,Y' 103.9403 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'X;X,Z,Z'  13.8175 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'X;Z,Z,X'  14.5213 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'X;Z,X,Z'  14.5213 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'Y;Y,X,X' 104.7953 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'Y;X,X,Y' 103.9398 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'Y;X,Y,X' 103.9398 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'Y;Y,Y,Y' 103.2087 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'Y;Y,Z,Z'  13.3155 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'Y;Z,Z,Y'  13.5778 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'Y;Z,Y,Z'  13.5778 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'Z;Z,X,X'  15.8578 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'Z;X,X,Z'  14.5222 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'Z;X,Z,X'  14.5222 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'Z;Z,Y,Y'  14.3703 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'Z;Y,Y,Z'  13.5783 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'Z;Y,Z,Y'  13.5783 1e-4
check_second_hyperpolarizabilities 0.067 0.000 0.000 'Z;Z,Z,Z'   2.4052 1e-4
                                                                        
check_second_hyperpolarizabilities 0.067 0.067 0.000 'X;X,X,X' 154.8298 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'X;X,Y,Y' 115.3379 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'X;Y,Y,X' 120.9708 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'X;Y,X,Y' 115.3379 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'X;X,Z,Z'  16.0555 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'X;Z,Z,X'  16.1800 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'X;Z,X,Z'  16.0555 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'Y;Y,X,X' 123.8193 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'Y;X,X,Y' 125.3516 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'Y;X,Y,X' 123.8193 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'Y;Y,Y,Y' 125.6868 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'Y;Y,Z,Z'  16.8178 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'Y;Z,Z,Y'  16.2768 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'Y;Z,Y,Z'  16.8178 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'Z;Z,X,X'  21.4751 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'Z;X,X,Z'  18.9028 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'Z;X,Z,X'  21.4751 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'Z;Z,Y,Y'  19.8640 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'Z;Y,Y,Z'  17.8040 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'Z;Y,Z,Y'  19.8640 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.000 'Z;Z,Z,Z'   3.0254 1e-4
                                                                        
check_second_hyperpolarizabilities 0.067 0.067 0.067 'X;X,X,X' 190.0235 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'X;X,Y,Y' 142.2426 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'X;Y,Y,X' 142.2426 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'X;Y,X,Y' 142.2426 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'X;X,Z,Z'  18.9204 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'X;Z,Z,X'  18.9204 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'X;Z,X,Z'  18.9204 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'Y;Y,X,X' 166.7287 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'Y;X,X,Y' 166.7287 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'Y;X,Y,X' 166.7287 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'Y;Y,Y,Y' 172.5012 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'Y;Y,Z,Z'  22.9483 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'Y;Z,Z,Y'  22.9483 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'Y;Z,Y,Z'  22.9483 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'Z;Z,X,X'  37.6138 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'Z;X,X,Z'  37.6138 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'Z;X,Z,X'  37.6138 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'Z;Z,Y,Y'  34.9543 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'Z;Y,Y,Z'  34.9543 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'Z;Y,Z,Y'  34.9543 1e-4
check_second_hyperpolarizabilities 0.067 0.067 0.067 'Z;Z,Z,Z'   4.8314 1e-4
"

. ./functions || { echo "'functions' library not found." ; exit 1; }
check_gen_input "$0" "$info" "$molecule" "$dalton" "$test"
