#!/bin/sh

info='
   efs_b3lyp
   ---------
   Molecule:         C2H6
   Wave Function:    B3LYP
   Test Purpose:     SCF energy with .EFS integrals
'

molecule='BASIS
6-31+G*


Atomtypes=2 Charge=0 Nosymmetry Angstrom
Charge=6.0 Atoms=2
C       -0.770000      0.000000      0.000000
C        0.770000      0.000000      0.000000
Charge=1.0 Atoms=6
H        1.136667      0.000000      1.037090
H        1.136667     -0.898146     -0.518545
H        1.136667      0.898146     -0.518545
H       -1.136667      0.000000      1.037090
H       -1.136667      0.898146     -0.518545
H       -1.136667     -0.898146     -0.518545
'

dalton='**DALTON INPUT
.RUN WAVE
.DIRECT
**INTEGRALS
*TWOINT
.EFS
**WAVE FUNCTIONS
.DFT
B3LYP
*END OF DALTON INPUT
'

test='
check_scf_energy DFT  -79.760842535418 2e-9
'                     

. ./functions || { echo "'functions' library not found." ; exit 1; }
check_gen_input "$0" "$info" "$molecule" "$dalton" "$test"
