#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > hfmmpcm_1.info <<'%EOF%'
   hfmmpcm_1
   -----------
   Molecule:         CH2O(HF)/2 H2O(MM)
   Wave Function:    RHF / STO-3G  
   Test Purpose:     Test of HF/MM/PCM energy, dipole moment and excitation energy
%EOF%
#######################################################################
#  INTEGRAL INPUT
#######################################################################
cat > hfmmpcm_1.mol <<'%EOF%'
ATOMBASIS
CH2O PLUS 2 WATERS
------------------------
    5    0         1 1.00D-12
        6.0   1    Basis=STO-3G
C           -1.588367    -.770650     .029109 0 1
        8.0   1    Basis=STO-3G
O           -1.657083     .436069    -.009750 0 2
        1.0   2    Basis=STO-3G
H           -.620668   -1.294822      .054251 0 3
H           -2.508043   -1.382001     .040282 0 4
   -0.669     2   Basis=MM
O             .975536    1.507219    -.082590 1 1
O            1.633705   -1.233280    -.078786 2 1
    0.3345    4   Basis=MM
H             .023200    1.300096    -.088063 1 2
H            1.113831    2.040431     .704778 1 3
H            1.600739    -.258639    -.086953 2 2
H            2.303878   -1.461228     .570065 2 3
%EOF%
#######################################################################
#  QM/MM INTERACTION INPUT
#######################################################################
cat > hfmmpcm_1.pot <<'%EOF%'
**SYSTP
.NUMMTP
 1
.TYPE
 0
.MODEL
 SPC
.CHARGS
 4
 0.0000
 0.0000
 0.0000
 0.0000
*******
.TYPE
 1-2
.MODEL
 SPC_E01
.ALPISO
 1
 9.501
*******
**TWOIA (i,j=0,1,2,...,N; if i=0 then j.neq.0)
.LJ_A
 2
 0.00000
 0.00000
.LJ_B
 2
 0.000
 0.000
**END OF
%EOF%
#
#######################################################################
#  DALTON INPUT
#######################################################################
cat > hfmmpcm_1.dal <<'%EOF%'
**DALTON
.RUN PROPERTIES
*PCM
.SOLVNT
WATER
.NPCMMT
0
.NESFP
4
.ICESPH
1
*PCMCAV
.CENTER
-1.588367    -.770650     .029109 
-1.657083     .436069    -.009750 
.975536    1.507219    -.082590 
1.633705   -1.233280    -.078786 
.RIN
2.325   
1.750   
1.950
1.950
*QM3
.QM3
.PRINT
 1
.THRDIP
 1.0D-12
.MAXDIP
 180
.MMPCM
.INTDIR
**INTEGRALS
.DIPLEN
.NOSUP
.PRINT
 2
**WAVE FUNCTIONS
.HF
*SCF INPUT
.THRESHOLD
 1.0D-08
**PROPERTIES
.EXCITA
*EXCITA
.NEXCIT
 4
.THRESH
 1.0D-05
.PRINT
10
**END OF DALTON INPUT
%EOF%
#
#######################################################################
#  CHECK SCRIPT
#######################################################################
#
echo $CHECK_SHELL >hfmmpcm_1.check
cat >>hfmmpcm_1.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi
# Test of energy
#
CRIT1=`$GREP "QM/MM/PCM calculation converged" $log | wc -l`
CRIT2=`$GREP "Electrostatic energy: * ( \-|\-0)\.008690488" $log | wc -l`
CRIT3=`$GREP "Polarization energy: * ( \-|\-0)\.000706367" $log | wc -l`
CRIT4=`$GREP "QM/MM/PCM energy: * ( \-|\-0)\.014513989" $log | wc -l`
CRIT5=`$GREP "Final HF energy:    *       \-112\.367462265" $log | wc -l`
TEST[1]=`expr $CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 `
CTRL[1]=5
ERROR[1]="HF/MM ENERGY CONTRIBUTIONS NOT CORRECT"

#
# Test of HF/MM dipole moment
#
CRIT1=`$GREP "x * ( |0)\.0756474" $log | wc -l`
CRIT2=`$GREP "y * ( \-|\-0)\.7092419" $log | wc -l`
CRIT3=`$GREP "z * ( |0)\.0226434" $log | wc -l`
TEST[2]=`expr $CRIT1 \+ $CRIT2 \+ $CRIT3 `
CTRL[2]=3
ERROR[2]="HF/MM DIPOLE MOMENT NOT CORRECT"

#
# Test of HF/MM excitation energies
#
CRIT1=`$GREP "1      1  *  ( |0)\.15866" $log | wc -l`
CRIT2=`$GREP "1      2  *  ( |0)\.34171" $log | wc -l`
CRIT3=`$GREP "1      3  *  ( |0)\.42064" $log | wc -l`
CRIT4=`$GREP "1      4  *  ( |0)\.4935" $log | wc -l`
TEST[3]=`expr $CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 `
CTRL[3]=4
ERROR[3]="HF/MM EXCITATION ENERGIES NOT CORRECT"

PASSED=1 
for i in 1 2 3
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo ${ERROR[i]}
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi                
%EOF%
chmod +x hfmmpcm_1.check
#######################################################################
