#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > prop_vibana.info <<'%EOF%'
   prop_vibana
   -----------
   Molecule:         Pyrimidine cation
   Wave Function:    Open-shell HF / cc-pVDZ
   Test Purpose:     Vibrational analysis
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > prop_vibana.mol <<'%EOF%'
BASIS
cc-pVDZ
Vibrational analysis of open-shell molecule

    3    2X  Z
        7.0   1
 N1   2.0588848837817086  1.6649387832804063  0.0000000000000000
        6.0   3
 C1   2.1950849457091071 -0.8171562127831691  0.0000000000000000
 C2   0.0000000000000000 -2.2480833143699051  0.0000000000000000
 C3   0.0000000000000000  3.0343811449315075  0.0000000000000000
        1.0   3
 H1   4.0723206213690837 -1.6336311777068284  0.0000000000000000
 H2   0.0000000000000000  5.0728155006112949  0.0000000000000000
 H3   0.0000000000000000 -4.2874161167537146  0.0000000000000000
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > prop_vibana.dal <<'%EOF%'
*DALTON INPUT
.RUN PROPERTIES
**WAVE FUNCTIONS
.HF
*SCF INP
.DOUBLY OCCUPIED
11    6    2    1
.OPEN SHELL
 2
.THRESH
1.0D-10
**PROPERTIES
.VIBANA
**END OF DALTON INPUT
%EOF%
#######################################################################



#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >prop_vibana.check
cat >>prop_vibana.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# Basis set
CRIT1=`$GREP "Basis set used is \"cc\-pVDZ\" from the basis set library\." $log | wc -l`
CRIT2=`$GREP "N * 2 * 7\.0000 * 26 * 14 * \[9s4p1d\|3s2p1d\]" $log | wc -l`
CRIT3=`$GREP "C * 4 * 6\.0000 * 26 * 14 * \[9s4p1d\|3s2p1d\]" $log | wc -l`
CRIT5=`$GREP "H * 4 * 1\.0000 * 7 * 5 * \[4s1p\|2s1p\]" $log | wc -l`
CRIT7=`$GREP "total\: * 10 * 42\.0000 * 184 * 104" $log | wc -l`
CRIT8=`$GREP "Spherical harmonic basis used\." $log | wc -l`
TEST[1]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT5 \+ $CRIT7 \+ $CRIT8`
CTRL[1]=6
ERROR[1]="BASIS SET NOT READ CORRECTLY"

# Geometry
CRIT1=`$GREP "Total number of coordinates\: * 30" $log | wc -l`
CRIT2=`$GREP "1 * x * 2\.0588848838" $log | wc -l`
CRIT3=`$GREP "2 * y * 1\.6649387833" $log | wc -l`
CRIT4=`$GREP "3 * z * (0| )\.0000000000" $log | wc -l`
CRIT5=`$GREP "4 * x * \-2\.0588848838" $log | wc -l`
CRIT6=`$GREP "5 * y * 1\.6649387833" $log | wc -l`
CRIT7=`$GREP "6 * z * (0| )\.0000000000" $log | wc -l`
CRIT8=`$GREP "7 * x * 2\.1950849457" $log | wc -l`
CRIT9=`$GREP "8 * y * (\-0|\-)\.8171562128" $log | wc -l`
CRIT10=`$GREP "9 * z * (0| )\.0000000000" $log | wc -l`
CRIT11=`$GREP "10 * x * \-2\.1950849457" $log | wc -l`
CRIT12=`$GREP "11 * y * (\-0|\-)\.8171562128" $log | wc -l`
CRIT13=`$GREP "12 * z * (0| )\.0000000000" $log | wc -l`
CRIT14=`$GREP "13 * x * (0| )\.0000000000" $log | wc -l`
CRIT15=`$GREP "14 * y * \-2\.2480833144" $log | wc -l`
CRIT16=`$GREP "15 * z * (0| )\.0000000000" $log | wc -l`
CRIT17=`$GREP "16 * x * (0| )\.0000000000" $log | wc -l`
CRIT18=`$GREP "17 * y * 3\.0343811449" $log | wc -l`
CRIT19=`$GREP "18 * z * (0| )\.0000000000" $log | wc -l`
CRIT20=`$GREP "19 * x * 4\.0723206214" $log | wc -l`
CRIT21=`$GREP "20 * y * \-1\.6336311777" $log | wc -l`
CRIT22=`$GREP "21 * z * (0| )\.0000000000" $log | wc -l`
CRIT23=`$GREP "22 * x * \-4\.0723206214" $log | wc -l`
CRIT24=`$GREP "23 * y * \-1\.6336311777" $log | wc -l`
CRIT25=`$GREP "24 * z * (0| )\.0000000000" $log | wc -l`
CRIT26=`$GREP "25 * x * (0| )\.0000000000" $log | wc -l`
CRIT27=`$GREP "26 * y * 5\.0728155006" $log | wc -l`
CRIT28=`$GREP "27 * z * (0| )\.0000000000" $log | wc -l`
CRIT29=`$GREP "28 * x * (0| )\.0000000000" $log | wc -l`
CRIT30=`$GREP "29 * y * \-4\.2874161168" $log | wc -l`
CRIT31=`$GREP "30 * z * (0| )\.0000000000" $log | wc -l`
TEST[2]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10 \+ $CRIT11 \+ $CRIT12 \+ \
		$CRIT13 \+ $CRIT14 \+ $CRIT15 \+ $CRIT16 \+ $CRIT17 \+ $CRIT18 \+ \
		$CRIT19 \+ $CRIT20 \+ $CRIT21 \+ $CRIT22 \+ $CRIT23 \+ $CRIT24 \+ \
		$CRIT25 \+ $CRIT26 \+ $CRIT27 \+ $CRIT28 \+ $CRIT29 \+ $CRIT30 \+ \
		$CRIT31`
TEST[2]=31  # test disabled because of new print format Apr 2006
CTRL[2]=31
ERROR[2]="GEOMETRY NOT READ CORRECTLY"

# Symmetry
CRIT1=`$GREP "Number of coordinates in each symmetry\: * 10 * 10 * 7 * 3" $log | wc -l`
CRIT2=`$GREP "Number of orbitals in each symmetry\: * 44 * 32 * 17 * 11" $log | wc -l`
TEST[3]=`expr	$CRIT1 \+ $CRIT2`
CTRL[3]=2
ERROR[3]="SYMMETRY NOT CORRECT"

# Energy
CRIT1=`$GREP "Final * HF energy\: * \-262\.375106125" $log | wc -l`
TEST[4]=`expr	$CRIT1`
CTRL[4]=1
ERROR[4]="SCF ENERGY NOT CORRECT"

# Gradient
CRIT1=`$GREP "N. * x * (\-0|\-)\.000000084[0-9]" $log | wc -l`
CRIT2=`$GREP "N. * y * (0| )\.000000061[0-9]" $log | wc -l`
CRIT3=`$GREP "C. * x * (0| )\.000000058[0-9]" $log | wc -l`
CRIT4=`$GREP "C. * y * (\-0|\-)\.000000090[0-9]" $log | wc -l`
CRIT5=`$GREP "C. * y * (0| )\.000000009[0-9]" $log | wc -l`
CRIT6=`$GREP "C. * y * (0| )\.000000002[0-9]" $log | wc -l`
CRIT7=`$GREP "H. * x * (0| )\.000000003[0-9]" $log | wc -l`
CRIT8=`$GREP "H. * y * (0| )\.000000027[0-9]" $log | wc -l`
CRIT9=`$GREP "H. * y * (\-0|\-)\.000000003[0-9]" $log | wc -l`
CRIT10=`$GREP "H. * y * (\-0|\-)\.000000007[0-9]" $log | wc -l`
TEST[5]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10`
CTRL[5]=10
ERROR[5]="GRADIENT NOT CORRECT"

# Hessian
CRIT1=`$GREP "N. * x * 1\.26583[0-9]" $log | wc -l`
CRIT2=`$GREP "N. * y * (\-0|\-)\.48494[0-9] * 1\.72516[0-9]" $log | wc -l`
CRIT3=`$GREP "C. * x * (\-0|\-)\.22661[0-9] * (0| )\.01061[0-9] * 1\.84953[0-9]" $log | wc -l`
CRIT4=`$GREP "C. * y * (0| )\.07976[0-9] * (\-0|\-)\.98125[0-9] * (\-0|\-)\.05205[0-9] * 1\.70942[0-9]" $log | wc -l`
CRIT5=`$GREP "C. * y * (\-0|\-)\.05988[0-9] * (\-0|\-)\.10895[0-9] * (\-0|\-)\.28308[0-9] * (\-0|\-)\.43421[0-9] * (0| )\.90819[0-9]" $log | wc -l`
CRIT6=`$GREP "C. * y * (0| )\.39054[0-9] * (\-0|\-)\.57892[0-9] * (0| )\.08760[0-9] * (\-0|\-)\.06883[0-9] * (0| )\.00282[0-9] * 1\.06277[0-9]" $log | wc -l`
CRIT7=`$GREP "H. * x * (0| )\.00811[0-9] * (0| )\.00460[0-9] * (\-0|\-)\.67035[0-9] * (0| )\.21583[0-9] * (0| )\.02659[0-9] * (\-0|\-)\.00355[0-9]" $log | wc -l`
CRIT8=`$GREP "H. * y * (0| )\.07302[0-9] * (\-0|\-)\.04333[0-9] * (0| )\.22567[0-9] * (\-0|\-)\.21677[0-9] * (0| )\.02814[0-9] * (\-0|\-)\.01336[0-9]" $log | wc -l`
CRIT9=`$GREP "H. * y * (0| )\.00624[0-9] * (\-0|\-)\.01267[0-9] * (0| )\.00085[0-9] * (0| )\.00451[0-9] * (\-0|\-)\.00017[0-9] * (\-0|\-)\.40511[0-9]" $log | wc -l`
CRIT10=`$GREP "H. * y * (\-0|\-)\.00474[0-9] * (\-0|\-)\.00002[0-9] * (0| )\.01038[0-9] * (\-0|\-)\.01285[0-9] * (\-0|\-)\.39582[0-9] * (0| )\.00064[0-9]" $log | wc -l`
CRIT11=`$GREP "H. * x * (0| )\.69142[0-9]" $log | wc -l`
CRIT12=`$GREP "H. * y * (\-0|\-)\.24298[0-9] * (0| )\.24452[0-9]" $log | wc -l`
CRIT13=`$GREP "H. * y * (\-0|\-)\.00005[0-9] * (\-0|\-)\.00010[0-9] * (0| )\.41360[0-9]" $log | wc -l`
CRIT14=`$GREP "H. * y * (\-0|\-)\.00043[0-9] * (0| )\.00091[0-9] * (\-0|\-)\.00006[0-9] * (0| )\.40719[0-9]" $log | wc -l`
CRIT15=`$GREP "N. * x * (0| )\.56626[0-9]" $log | wc -l`
CRIT16=`$GREP "N. * y * (\-0|\-)\.06186[0-9] * 1\.21455[0-9]" $log | wc -l`
CRIT17=`$GREP "C. * x * (\-0|\-)\.31898[0-9] * (0| )\.13581[0-9] * 1\.57341[0-9]" $log | wc -l`
CRIT18=`$GREP "C. * y * (\-0|\-)\.19977[0-9] * (\-0|\-)\.53299[0-9] * (\-0|\-)\.19214[0-9] * 1\.34659[0-9]" $log | wc -l`
CRIT19=`$GREP "C. * x * (0| )\.14193[0-9] * (\-0|\-)\.26519[0-9] * (\-0|\-)\.61643[0-9] * (\-0|\-)\.10674[0-9] * (0| )\.70212[0-9]" $log | wc -l`
CRIT20=`$GREP "C. * x * (\-0|\-)\.37499[0-9] * (0| )\.11382[0-9] * (0| )\.03449[0-9] * (0| )\.33453[0-9] * (\-0|\-)\.13616[0-9] * (0| )\.52639[0-9]" $log | wc -l`
CRIT21=`$GREP "H. * x * (0| )\.00712[0-9] * (0| )\.01473[0-9] * (\-0|\-)\.68573[0-9] * (0| )\.22334[0-9] * (\-0|\-)\.02252[0-9] * (0| )\.00978[0-9]" $log | wc -l`
CRIT22=`$GREP "H. * y * (0| )\.06363[0-9] * (\-0|\-)\.03686[0-9] * (0| )\.20614[0-9] * (\-0|\-)\.21825[0-9] * (\-0|\-)\.03220[0-9] * (0| )\.00560[0-9]" $log | wc -l`
CRIT23=`$GREP "H. * x * (\-0|\-)\.01422[0-9] * (0| )\.07968[0-9] * (\-0|\-)\.00425[0-9] * (0| )\.00013[0-9] * (0| )\.00082[0-9] * (\-0|\-)\.05326[0-9]" $log | wc -l`
CRIT24=`$GREP "H. * x * (\-0|\-)\.00711[0-9] * (\-0|\-)\.01698[0-9] * (0| )\.01748[0-9] * (\-0|\-)\.05934[0-9] * (\-0|\-)\.06976[0-9] * (\-0|\-)\.00625[0-9]" $log | wc -l`
CRIT25=`$GREP "H. * x * (0| )\.68912[0-9]" $log | wc -l`
CRIT26=`$GREP "H. * y * (\-0|\-)\.24602[0-9] * (0| )\.24198[0-9]" $log | wc -l`
CRIT27=`$GREP "H. * x * (0| )\.00016[0-9] * (0| )\.00148[0-9] * (0| )\.07025[0-9]" $log | wc -l`
CRIT28=`$GREP "H. * x * (0| )\.00207[0-9] * (0| )\.00136[0-9] * (0| )\.00048[0-9] * (0| )\.06308[0-9]" $log | wc -l`
CRIT29=`$GREP "N. * z * (0| )\.19762[0-9]" $log | wc -l`
CRIT30=`$GREP "C. * z * (\-0|\-)\.14804[0-9] * (0| )\.38308[0-9]" $log | wc -l`
CRIT31=`$GREP "C. * z * (0| )\.00387[0-9] * (\-0|\-)\.14105[0-9] * (0| )\.13590[0-9]" $log | wc -l`
CRIT32=`$GREP "C. * z * (\-0|\-)\.10258[0-9] * (\-0|\-)\.01103[0-9] * (0| )\.01629[0-9] * (0| )\.15060[0-9]" $log | wc -l`
CRIT33=`$GREP "H. * z * (0| )\.02954[0-9] * (\-0|\-)\.10863[0-9] * (0| )\.03318[0-9] * (\-0|\-)\.00314[0-9] * (0| )\.05329[0-9]" $log | wc -l`
CRIT34=`$GREP "H. * z * (0| )\.00023[0-9] * (0| )\.02227[0-9] * (\-0|\-)\.00192[0-9] * (\-0|\-)\.05114[0-9] * (0| )\.00161[0-9] * (0| )\.03156[0-9]" $log | wc -l`
CRIT35=`$GREP "H. * z * (0| )\.01935[0-9] * (0| )\.00340[0-9] * (\-0|\-)\.04626[0-9] * (0| )\.00100[0-9] * (\-0|\-)\.00584[0-9] * (\-0|\-)\.00261[0-9]" $log | wc -l`
CRIT36=`$GREP "H. * z * (0| )\.03096[0-9]" $log | wc -l`
CRIT37=`$GREP "N. * z * (0| )\.14153[0-9]" $log | wc -l`
CRIT38=`$GREP "C. * z * (\-0|\-)\.12935[0-9] * (0| )\.34400[0-9]" $log | wc -l`
CRIT39=`$GREP "H. * z * (\-0|\-)\.00183[0-9] * (\-0|\-)\.12003[0-9] * (0| )\.06562[0-9]" $log | wc -l`
TEST[6]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10 \+ $CRIT11 \+ $CRIT12 \+ \
		$CRIT13 \+ $CRIT14 \+ $CRIT15 \+ $CRIT16 \+ $CRIT17 \+ $CRIT18 \+ \
		$CRIT19 \+ $CRIT20 \+ $CRIT21 \+ $CRIT22 \+ $CRIT23 \+ $CRIT24 \+ \
		$CRIT25 \+ $CRIT26 \+ $CRIT27 \+ $CRIT28 \+ $CRIT29 \+ $CRIT30 \+ \
		$CRIT31 \+ $CRIT32 \+ $CRIT33 \+ $CRIT34 \+ $CRIT35 \+ $CRIT36 \+ \
		$CRIT37 \+ $CRIT38 \+ $CRIT39`
CTRL[6]=39
ERROR[6]="HESSIAN NOT CORRECT"

# Rotational constants
CRIT1=`$GREP "6739\.467[0-9] * 6011\.118[0-9] * 3177\.245[0-9] MHz" $log | wc -l`
CRIT2=`$GREP "(0| )\.22480[0-9] * (0| )\.20050[0-9] * (0| )\.10598[0-9] cm\-1" $log | wc -l`
TEST[7]=`expr	$CRIT1 \+ $CRIT2`
CTRL[7]=4
ERROR[7]="ROTATIONAL CONSTANTS NOT CORRECT"

# Vibrational frequencies
CRIT1=`$GREP "1 * A1 * 3442\.1[0-9] * (0| )\.01568[0-9] * 21\.55[0-9] * (0| )\.510[0-9]" $log | wc -l`
CRIT2=`$GREP "2 * A1 * 3411\.6[0-9] * (0| )\.01554[0-9] * 17\.67[0-9] * (0| )\.418[0-9]" $log | wc -l`
CRIT3=`$GREP "4 * A1 * 3367\.8[0-9] * (0| )\.01534[0-9] * 2\.40[0-9] * (0| )\.056[0-9]" $log | wc -l`
CRIT4=`$GREP "5 * A1 * 1772\.3[0-9] * (0| )\.00807[0-9] * 70\.68[0-9] * 1\.672[0-9]" $log | wc -l`
CRIT5=`$GREP "7 * A1 * 1576\.5[0-9] * (0| )\.00718[0-9] * 79\.89[0-9] * 1\.890[0-9]" $log | wc -l`
CRIT6=`$GREP "11 * A1 * 1245\.8[0-9] * (0| )\.00567[0-9] * (0| )\.67[0-9] * (0| )\.016[0-9]" $log | wc -l`
CRIT7=`$GREP "13 * A1 * 1143\.7[0-9] * (0| )\.00521[0-9] * (0| )\.08[0-9] * (0| )\.002[0-9]" $log | wc -l`
CRIT8=`$GREP "18 * A1 * 1035\.3[0-9] * (0| )\.00471[0-9] * 8\.18[0-9] * (0| )\.193[0-9]" $log | wc -l`
CRIT9=`$GREP "21 * A1 * 694\.7[0-9] * (0| )\.00316[0-9] * 8\.48[0-9] * (0| )\.200[0-9]" $log | wc -l`
CRIT10=`$GREP "3 * B2 * 3370\.8[0-9] * (0| )\.01535[0-9] * 43\.62[0-9] * 1\.032[0-9]" $log | wc -l`
CRIT11=`$GREP "6 * B2 * 1658\.0[0-9] * (0| )\.00755[0-9] * 193\.58[0-9] * 4\.581[0-9]" $log | wc -l`
CRIT12=`$GREP "8 * B2 * 1565\.9[0-9] * (0| )\.00713[0-9] * 3.24[0-9] * (0| )\.076[0-9]" $log | wc -l`
CRIT13=`$GREP "9 * B2 * 1434\.1[0-9] * (0| )\.00653[0-9] * 6\.84[0-9] * (0| )\.162[0-9]" $log | wc -l`
CRIT14=`$GREP "10 * B2 * 1279\.0[0-9] * (0| )\.00582[0-9] * 46\.12[0-9] * 1\.091[0-9]" $log | wc -l`
CRIT15=`$GREP "12 * B2 * 1199\.1[0-9] * (0| )\.00546[0-9] * 18\.68[0-9] * (0| )\.442[0-9]" $log | wc -l`
CRIT16=`$GREP "16 * B2 * 1050\.6[0-9] * (0| )\.00478[0-9] * (0| )\.07[0-9] * (0| )\.001[0-9]" $log | wc -l`
CRIT17=`$GREP "20 * B2 * 710\.6[0-9] * (0| )\.00323[0-9] * 6\.40[0-9] * (0| )\.151[0-9]" $log | wc -l`
CRIT18=`$GREP "14 * B1 * 1109\.1[0-9] * (0| )\.00505[0-9] * (0| ).000 * (0| )\.0000" $log | wc -l`
CRIT19=`$GREP "17 * B1 * 1036\.9[0-9] * (0| )\.00472[0-9] * (0| )\.04[0-9] * (0| )\.001[0-9]" $log | wc -l`
CRIT20=`$GREP "19 * B1 * 923\.9[0-9] * (0| )\.00421[0-9] * 25\.08[0-9] * (0| )\.593[0-9]" $log | wc -l`
CRIT21=`$GREP "22 * B1 * 515\.6[0-9] * (0| )\.00235[0-9] * 114\.85[0-9] * 2\.718[0-9]" $log | wc -l`
CRIT22=`$GREP "24 * B1 * 390\.2[0-9] * (0| )\.00177[0-9] * 1\.23[0-9] * (0| )\.029[0-9]" $log | wc -l`
CRIT23=`$GREP "15 * A2 * 1067\.3[0-9] * (0| )\.00486[0-9] * (0| ).000 * (0| )\.0000" $log | wc -l`
CRIT24=`$GREP "23 * A2 * 483\.1[0-9] * (0| )\.00220[0-9] * (0| ).000 * (0| )\.0000" $log | wc -l`
TEST[8]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10 \+ $CRIT11 \+ $CRIT12 \+ \
		$CRIT13 \+ $CRIT14 \+ $CRIT15 \+ $CRIT16 \+ $CRIT17 \+ $CRIT18 \+ \
		$CRIT19 \+ $CRIT20 \+ $CRIT21 \+ $CRIT22 \+ $CRIT23 \+ $CRIT24`
CTRL[8]=24
ERROR[8]="VIBRATIONAL FREQUENCIES NOT CORRECT"

PASSED=1
for i in 1 2 3 4 5 6 7 8
do
   if [ ${TEST[i]} -lt ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
