#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > rsp_fullhfc.info <<'%EOF%'
   rsp_fullhfc
   -----------
   Molecule:         ClO2
   Wave Function:    Spin-restricted open shell Kohn-Sham 
   Test Purpose:     Hyperfine coupling tensor
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > rsp_fullhfc.mol <<'%EOF%'
BASIS
3-21G
Hyperfine coupling tensor.
--------------------------
    2    2  X  Y      1.00D-15
       17.    1   
Cl    0.00000    0.00000   1.0000
        8.    1    
O1    0.00000    2.37360  -0.44317
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > rsp_fullhfc.dal <<'%EOF%'
**DALTON INPUT
.RUN RESPONSE
**INTEGRALS 
.SPIN-ORBIT
**WAVE FUNCTIONS
.DFT
B3LYP 
**RESPON
*HFC 
.HFC-FC
.HFC-SD 
.HFC-SO
.BRT-SO
**END OF DALTON INPUT
%EOF%
#######################################################################



#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >rsp_hfc.check
cat >>rsp_fullhfc.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# DFT energy
CRIT1=`$GREP "Final * DFT energy\: * \-607.1228462[0-9][0-9][0-9][0-9][0-9]" $log | wc -l` 
TEST[1]=`expr	$CRIT1`
CTRL[1]=1
ERROR[1]="ENERGY NOT CORRECT"

# Fermi contact term 
CRIT1=`$GREP "\|  1Cl \|   35  \|    0.000 \|    9.085 \|    9.085 \|" $log | wc -l`
TEST[2]=`expr   $CRIT1`
CTRL[2]=1
ERROR[2]="FERMI CONTACT CONTRIBUTION TO HYPERFINE COUPLING TENSOR IS NOT CORRECT"

#Spin-dipolar term 
CRIT1=`$GREP "\|   37.15 \|   \-18.32 \|   \-18.83 \|     0.00 \|     0.00 \|     0.00 \|" $log | wc -l`
CRIT2=`$GREP "\|    3.17 \|    \-1.50 \|    \-1.67 \|     0.00 \|     0.00 \|     0.00 \|" $log | wc -l`
CRIT3=`$GREP "\|   40.31 \|   \-19.81 \|   \-20.50 \|     0.00 \|     0.00 \|     0.00 \|" $log | wc -l` 

TEST[3]=`expr   $CRIT1 \+ $CRIT2 \+ $CRIT3`
CTRL[3]=3
ERROR[3]="SPIN-DIPOLAR CONTRIBUTION TO HYPERFINE COUPLING TENSOR IS NOT CORRECT"

#Spin-orbit term 
CRIT1=`$GREP "\| Ix \|    0.01 \|     0.00 \|     0.00 \|" $log | wc -l`
CRIT2=`$GREP "\| Iy \|    0.00 \|     0.61 \|     0.00 \|" $log | wc -l`
CRIT3=`$GREP "\| Iz \|    0.00 \|     0.00 \|     0.19 \|" $log | wc -l`

TEST[4]=`expr   $CRIT1 \+ $CRIT2 \+ $CRIT3` 
CTRL[4]=3 
ERROR[4]="SPIN-ORBIT CONTRIBUTION TO HYPERFINE COUPLING TENSOR IS NOT CORRECT"

PASSED=1
for i in 1 2 3 4 
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
