#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -e /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -e /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > rsp_g_ldax.info <<%EOF%
   rsp_g_ldax
   -----------
   Molecule:       CH2
   Wave Function:  LDA 
   Test Purpuse:   Three step calculation for numerical difference test
                   of perturbed g-tensor component
                   Analytical (quadratic response)          0.00064170
                   Numerical  (linear response) + field/2  -1.766935551362D-04
                                                - field/2  -1.773352501451D-04
                       difference/field                     0.000641695
                   Here: field=0.001

%EOF%

cat << EODAL > rsp_g_ldax__1.dal
**DALTON INPUT
.RUN RESPONSE
**INTEGRAL
.ANGMOM
.SPIN-ORBIT
.DIPLEN 
**WAVE FUNCTIONS
.DFT
LDA
*SCF INPUT
.THRESHOLD
1e-12
**RESPONSE
*LINEAR
.THCLR
 1E-9
*QUADRA
.PRINT
 6
.APROP
XANGMOM
.BPROP
X1SPNORB
.CPROP
XDIPLEN
**END OF DALTON INPUT
EODAL

cat << EODAL > rsp_g_ldax__2.dal
**DALTON INPUT
.RUN RESPONSE
**INTEGRAL
.ANGMOM
.SPIN-ORBIT
.DIPLEN
**WAVE FUNCTIONS
.DFT
LDA
.RESTART
*SCF INPUT
.THRESHOLD
1e-12
*HAMILT
.FIELD
 .5e-3
XDIPLEN
**RESPONSE
*LINEAR
.THCLR
 1E-9
.PROPRT
XANGMOM
.PROPRT
X1SPNORB
**END OF DALTON INPUT
EODAL

cat << EODAL > rsp_g_ldax__3.dal
**DALTON INPUT
.RUN RESPONSE
**INTEGRAL
.ANGMOM
.SPIN-ORBIT
.DIPLEN
**WAVE FUNCTIONS
.DFT
LDA
.RESTART
*SCF INPUT
.THRESHOLD
1e-12
*HAMILT
.FIELD
 -.5e-3
XDIPLEN
**RESPONSE
*LINEAR
.THCLR
 1E-9
.PROPRT
XANGMOM
.PROPRT
X1SPNORB
**END OF DALTON INPUT
EODAL

cat << EOMOL > rsp_g_ldax.mol
ATOMBASIS
STO-3G
------
    2   1 Z
        6.    1 Basis=STO-3G
C1      0.0006122714    0.0000000000    0.0000000000   
        1.    2 Basis=STO-3G
H1      1.5162556382   -1.3708721537    0.0000000000
H2     -0.7584339548    0.6854360769    1.7695110698

EOMOL

cat << 'EOCHK' > rsp_g_ldax__1.check
log=$1
GREP=egrep

if $GREP -q "not implemented for parallel calculations" $log; then
   echo "TEST ENDED AS EXPECTED"
   exit 0
fi

# ?
CRIT1=`$GREP "Final DFT energy\: * \-38\.923817272074" $log | wc -l`
TEST[1]=`expr $CRIT1`
CTRL[1]=1
ERROR[1]="ENERGY NOT CORRECT"

# ?
CRIT1=`$GREP "E3  CONTRIBUTION TO HYPVAL          0.00024398" $log | wc -l`
CRIT2=`$GREP "B2C CONTRIBUTION TO HYPVAL          0.00020552" $log | wc -l`
CRIT3=`$GREP "C2B CONTRIBUTION TO HYPVAL         -0.00004758" $log | wc -l`
CRIT4=`$GREP "A2B CONTRIBUTION TO HYPVAL          0.00015991" $log | wc -l`
CRIT5=`$GREP "A2C CONTRIBUTION TO HYPVAL          0.00007987" $log | wc -l`
CRIT6=`$GREP "@ omega B.*0.00064170" $log | wc -l`
TEST[2]=`expr $CRIT1 + $CRIT2 + $CRIT3 + $CRIT4 + $CRIT5 + $CRIT6`
CTRL[2]=6
ERROR[2]="G-TENSOR QUADRATIC RESPONSE NOT CORRECT"

PASSED=1
for i in 1 2
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi
EOCHK

cat << 'EOCHK' > rsp_g_ldax__2.check
log=$1
GREP=egrep

if $GREP -q "not implemented for parallel calculations" $log; then
   echo "TEST ENDED AS EXPECTED"
   exit 0
fi

# ?
CRIT1=`$GREP "Final DFT energy\: * \-38\.923816146823" $log | wc -l`
TEST[1]=`expr $CRIT1`
CTRL[1]=1
ERROR[1]="ENERGY NOT CORRECT"

# ?
CRIT1=`$GREP "ANGMOM.*1SPNORB.*1.76693555.*[DE]-04" $log | wc -l`
TEST[2]=`expr $CRIT1`
CTRL[2]=1
ERROR[2]="G-TENSOR - FIELD NOT CORRECT"

PASSED=1
for i in 1 2
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi
EOCHK

cat << 'EOCHK' > rsp_g_ldax__3.check
log=$1
GREP=egrep

if $GREP -q "not implemented for parallel calculations" $log; then
   echo "TEST ENDED AS EXPECTED"
   exit 0
fi

# ?
CRIT1=`$GREP "Final DFT energy\: * \-38\.923819381144" $log | wc -l`
TEST[1]=`expr $CRIT1`
CTRL[1]=1
ERROR[1]="ENERGY NOT CORRECT"

# ?
CRIT1=`$GREP "ANGMOM.*1SPNORB.*1.77335250.*[DE]-04" $log | wc -l`
TEST[2]=`expr $CRIT1`
CTRL[2]=1
ERROR[2]="G-TENSOR-E-FIELD NOT CORRECT"

PASSED=1
for i in 1 2
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi
EOCHK

