#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION                                                   #
#######################################################################
cat > soppa_vibavg_twobas.info <<'%EOF%'
   soppa_vibavg_twobas
   -------
   Molecule:         Ethene (with one C13) 
   Wave Function:    MP2 / SOPPA
   Test Purpose:     Vibrational average with change of basis set
%EOF%

#######################################################################
#  MOLECULE INPUT                                                     #
#######################################################################
cat > soppa_vibavg_twobas.mol <<'%EOF%'
BASIS                                                                           
STO-3G
Ethene                                                                          
For test of new property averaging routines                                     
ATOMTYPES=2                                                   
Charge= 6.00000 Atoms=2                                                         
C13     0.0000000000   1.2707220626      0.0000000000 Isotope=13
C12     0.0000000000  -1.2707220626      0.0000000000
Charge= 1.00000 Atoms=4                                                         
Ha      0.0000000000   2.3626468109      1.7651222995
Hb      0.0000000000  -2.3626468109      1.7651222995
Ha      0.0000000000   2.3626468109     -1.7651222995
Hb      0.0000000000  -2.3626468109     -1.7651222995

%EOF%

#######################################################################
#  DALTON INPUT                                                       #
#######################################################################
cat > soppa_vibavg_twobas.dal <<'%EOF%'
**DALTON INPUT
.NMDDRV
**NMDDRV
.VIBANA
.SYMMETRY
C2v
*PROPAV
.ANHA-P
.P-BASIS
3-21G
.SPIN-SPIN
**WAVE FUNCTIONS
.HF
.MP2
*SCF INPUT
.MAX ERR
10
.THRESH
1.0D-6
**EACH STEP
.SOPPA
.SPIN-SPIN
*TRPRSP
.THRESH
1.0D-5
*LINRES
.THRESH
1.0D-5
*END OF INPUT

%EOF%

#######################################################################
#  CHECK SCRIPT                                                       #
#######################################################################
echo $CHECK_SHELL > soppa_vibavg_twobas.check
cat >> soppa_vibavg_twobas.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

if $GREP -q "not implemented for parallel calculations" $log; then
   echo "TEST ENDED AS EXPECTED"
   exit 0
fi

# Initial symmetry
CRIT1=`$GREP "Full point group is\: C\(2v\)" $log | wc -l`
CRIT2=`$GREP "Represented as\: * C2v" $log | wc -l`
TEST[1]=`expr	$CRIT1 \+ $CRIT2`
CTRL[1]=2
ERROR[1]="INITIAL POINT GROUP NOT CORRECT"

# Correct change of basis set
CRIT1=`$GREP "Basis set changed to 3\-21G" $log | wc -l`
TEST[2]=`expr	$CRIT1`
CTRL[2]=1
ERROR[2]="BASIS SET NOT CHANGED"

sed -n -e '/Basis set changed to 3-21G/,$p' $log | sed -n -e '/Starting geometry./,/Harmonic contribution/p' > ${log}_0
log=${log}_0

# Coupling constants at equilibrium geometry
CRIT1=`$GREP "Isotropic coupling * \: * 72\.410[0-9] Hz" $log | wc -l`
CRIT2=`$GREP "Anisotropic coupling * \: * \-48\.220[0-9] Hz" $log | wc -l`
CRIT3=`$GREP "Asymmetry * \: * (\-0| \-)\.900[0-9]" $log | wc -l`
CRIT4=`$GREP "S parameter * \: * 54\.342[0-9] Hz" $log | wc -l`
CRIT5=`$GREP "A parameter * \: * (0| )\.000[0-9] Hz" $log | wc -l`
CRIT6=`$GREP "Isotropic DSO contribution\: * (0| )\.079[0-9] Hz" $log | wc -l`
CRIT7=`$GREP "Isotropic PSO contribution\: * \-6\.657[0-9] Hz" $log | wc -l`
CRIT8=`$GREP "Isotropic SD contribution \: * 2\.872[0-9] Hz" $log | wc -l`
CRIT9=`$GREP "Isotropic FC contribution \: * 76\.115[0-9] Hz" $log | wc -l`
CRIT10=`$GREP "Isotropic coupling * \: * \-16\.013[0-9] Hz" $log | wc -l`
CRIT11=`$GREP "Anisotropic coupling * \: * \-11\.705[0-9] Hz" $log | wc -l`
CRIT12=`$GREP "Asymmetry * \: * (\-0| \-)\.634[0-9]" $log | wc -l`
CRIT13=`$GREP "S parameter * \: * 12\.466[0-9] Hz" $log | wc -l`
CRIT14=`$GREP "A parameter * \: * (0| )\.342[0-9] Hz" $log | wc -l`
CRIT15=`$GREP "Isotropic DSO contribution\: * (\-0| \-)\.624[0-9] Hz" $log | wc -l`
CRIT16=`$GREP "Isotropic PSO contribution\: * \-1\.210[0-9] Hz" $log | wc -l`
CRIT17=`$GREP "Isotropic SD contribution \: * (\-0| \-)\.144[0-9] Hz" $log | wc -l`
CRIT18=`$GREP "Isotropic FC contribution \: * \-14\.033[0-9] Hz" $log | wc -l`
CRIT19=`$GREP "Isotropic coupling * \: * 127\.612[0-9] Hz" $log | wc -l`
CRIT20=`$GREP "Anisotropic coupling * \: * \-24\.195[0-9] Hz" $log | wc -l`
CRIT21=`$GREP "Asymmetry * \: * (\-0| \-)\.249[0-9]" $log | wc -l`
CRIT22=`$GREP "S parameter * \: * 24\.445[0-9] Hz" $log | wc -l`
CRIT23=`$GREP "A parameter * \: * (0| )\.417[0-9] Hz" $log | wc -l`
CRIT24=`$GREP "Isotropic DSO contribution\: * (0| )\.542[0-9] Hz" $log | wc -l`
CRIT25=`$GREP "Isotropic PSO contribution\: * (0| )\.440[0-9] Hz" $log | wc -l`
CRIT26=`$GREP "Isotropic SD contribution \: * (\-0| \-)\.145[0-9] Hz" $log | wc -l`
CRIT27=`$GREP "Isotropic FC contribution \: * 126\.774[0-9] Hz" $log | wc -l`
CRIT28=`$GREP "Isotropic coupling * \: * 12\.841[0-9] Hz" $log | wc -l`
CRIT29=`$GREP "Anisotropic coupling * \: * 9\.396[0-9] Hz" $log | wc -l`
CRIT30=`$GREP "Asymmetry * \: * (0| )\.825[0-9]" $log | wc -l`
CRIT31=`$GREP "S parameter * \: * 1(0| )\.407[0-9] Hz" $log | wc -l`
CRIT32=`$GREP "A parameter * \: * 2\.968[0-9] Hz" $log | wc -l`
CRIT33=`$GREP "Isotropic DSO contribution\: * (\-0| \-)\.943[0-9] Hz" $log | wc -l`
CRIT34=`$GREP "Isotropic PSO contribution\: * (\-0| \-)\.098[0-9] Hz" $log | wc -l`
CRIT35=`$GREP "Isotropic SD contribution \: * (\-0| \-)\.045[0-9] Hz" $log | wc -l`
CRIT36=`$GREP "Isotropic FC contribution \: * 13\.929[0-9] Hz" $log | wc -l`
CRIT37=`$GREP "Isotropic coupling * \: * \-9\.791[0-9] Hz" $log | wc -l`
CRIT38=`$GREP "Anisotropic coupling * \: * 19\.060[0-9] Hz" $log | wc -l`
CRIT39=`$GREP "Asymmetry * \: * (0| )\.587[0-9]" $log | wc -l`
CRIT40=`$GREP "S parameter * \: * 2(0| )\.125[0-9] Hz" $log | wc -l`
CRIT41=`$GREP "A parameter * \: * 5\.982[0-9] Hz" $log | wc -l`
CRIT42=`$GREP "Isotropic DSO contribution\: * \-3\.341[0-9] Hz" $log | wc -l`
CRIT43=`$GREP "Isotropic PSO contribution\: * 1\.387[0-9] Hz" $log | wc -l`
CRIT44=`$GREP "Isotropic SD contribution \: * (0| )\.433[0-9] Hz" $log | wc -l`
CRIT45=`$GREP "Isotropic FC contribution \: * \-8\.271[0-9] Hz" $log | wc -l`
CRIT46=`$GREP "Isotropic coupling * \: * 16\.965[0-9] Hz" $log | wc -l`
CRIT47=`$GREP "Anisotropic coupling * \: * 7\.504[0-9] Hz" $log | wc -l`
CRIT48=`$GREP "Asymmetry * \: * (0| )\.601[0-9]" $log | wc -l`
CRIT49=`$GREP "S parameter * \: * 7\.944[0-9] Hz" $log | wc -l`
CRIT50=`$GREP "Isotropic DSO contribution\: * \-3\.269[0-9] Hz" $log | wc -l`
CRIT51=`$GREP "Isotropic PSO contribution\: * (0| )\.565[0-9] Hz" $log | wc -l`
CRIT52=`$GREP "Isotropic SD contribution \: * (0| )\.451[0-9] Hz" $log | wc -l`
CRIT53=`$GREP "Isotropic FC contribution \: * 19\.218[0-9] Hz" $log | wc -l`
TEST[3]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10 \+ $CRIT11 \+ $CRIT12 \+ \
		$CRIT13 \+ $CRIT14 \+ $CRIT15 \+ $CRIT16 \+ $CRIT17 \+ $CRIT18 \+ \
		$CRIT19 \+ $CRIT20 \+ $CRIT21 \+ $CRIT22 \+ $CRIT23 \+ $CRIT24 \+ \
		$CRIT25 \+ $CRIT26 \+ $CRIT27 \+ $CRIT28 \+ $CRIT29 \+ $CRIT30 \+ \
		$CRIT31 \+ $CRIT32 \+ $CRIT33 \+ $CRIT34 \+ $CRIT35 \+ $CRIT36 \+ \
		$CRIT37 \+ $CRIT38 \+ $CRIT39 \+ $CRIT40 \+ $CRIT41 \+ $CRIT42 \+ \
		$CRIT43 \+ $CRIT44 \+ $CRIT45 \+ $CRIT46 \+ $CRIT47 \+ $CRIT48 \+ \
		$CRIT49 \+ $CRIT50 \+ $CRIT51 \+ $CRIT52 \+ $CRIT53`
CTRL[3]=140
ERROR[3]="Equilibrium coupling constants NOT CORRECT"

# Vibrationally averaged coupling constants
CRIT1=`$GREP "Isotropic coupling * \: * 76\.631[0-9] Hz" $log | wc -l`
CRIT2=`$GREP "Anisotropic coupling * \: * 51\.489[0-9] Hz" $log | wc -l`
CRIT3=`$GREP "Asymmetry * \: * (0| )\.970[0-9]" $log | wc -l`
CRIT4=`$GREP "S parameter * \: * 59\.026[0-9] Hz" $log | wc -l`
CRIT5=`$GREP "Isotropic DSO contribution\: * (0| )\.076[0-9] Hz" $log | wc -l`
CRIT6=`$GREP "Isotropic PSO contribution\: * \-6\.686[0-9] Hz" $log | wc -l`
CRIT7=`$GREP "Isotropic SD contribution \: * 3\.039[0-9] Hz" $log | wc -l`
CRIT8=`$GREP "Isotropic FC contribution \: * 8(0| )\.202[0-9] Hz" $log | wc -l`
CRIT9=`$GREP "Isotropic coupling * \: * 132\.611[0-9] Hz" $log | wc -l`
CRIT10=`$GREP "Anisotropic coupling * \: * \-22\.630[0-9] Hz" $log | wc -l`
CRIT11=`$GREP "Asymmetry * \: * (\-0| \-)\.321[0-9]" $log | wc -l`
CRIT12=`$GREP "S parameter * \: * 23\.016[0-9] Hz" $log | wc -l`
CRIT13=`$GREP "A parameter * \: * (0| )\.418[0-9] Hz" $log | wc -l`
CRIT14=`$GREP "Isotropic DSO contribution\: * (0| )\.529[0-9] Hz" $log | wc -l`
CRIT15=`$GREP "Isotropic PSO contribution\: * (0| )\.390[0-9] Hz" $log | wc -l`
CRIT16=`$GREP "Isotropic SD contribution \: * (\-0| \-)\.129[0-9] Hz" $log | wc -l`
CRIT17=`$GREP "Isotropic FC contribution \: * 131\.820[0-9] Hz" $log | wc -l`
CRIT18=`$GREP "Isotropic coupling * \: * \-18\.617[0-9] Hz" $log | wc -l`
CRIT19=`$GREP "Anisotropic coupling * \: * \-12\.626[0-9] Hz" $log | wc -l`
CRIT20=`$GREP "Asymmetry * \: * (\-0| \-)\.655[0-9]" $log | wc -l`
CRIT21=`$GREP "S parameter * \: * 13\.500[0-9] Hz" $log | wc -l`
CRIT22=`$GREP "A parameter * \: * (0| )\.311[0-9] Hz" $log | wc -l`
CRIT23=`$GREP "Isotropic DSO contribution\: * (\-0| \-)\.599[0-9] Hz" $log | wc -l`
CRIT24=`$GREP "Isotropic PSO contribution\: * \-1\.188[0-9] Hz" $log | wc -l`
CRIT25=`$GREP "Isotropic SD contribution \: * (\-0| \-)\.131[0-9] Hz" $log | wc -l`
CRIT26=`$GREP "Isotropic FC contribution \: * \-16\.698[0-9] Hz" $log | wc -l`
CRIT27=`$GREP "Isotropic coupling * \: * 132\.620[0-9] Hz" $log | wc -l`
CRIT28=`$GREP "Anisotropic coupling * \: * \-22\.625[0-9] Hz" $log | wc -l`
CRIT29=`$GREP "S parameter * \: * 23\.010[0-9] Hz" $log | wc -l`
CRIT30=`$GREP "Isotropic FC contribution \: * 131\.829[0-9] Hz" $log | wc -l`
CRIT31=`$GREP "Isotropic coupling * \: * \-18\.614[0-9] Hz" $log | wc -l`
CRIT32=`$GREP "Anisotropic coupling * \: * \-12\.627[0-9] Hz" $log | wc -l`
CRIT33=`$GREP "Asymmetry * \: * (\-0| \-)\.655[0-9]" $log | wc -l`
CRIT34=`$GREP "S parameter * \: * 13\.501[0-9] Hz" $log | wc -l`
CRIT35=`$GREP "Isotropic SD contribution \: * (\-0| \-)\.132[0-9] Hz" $log | wc -l`
CRIT36=`$GREP "Isotropic FC contribution \: * \-16\.695[0-9] Hz" $log | wc -l`
TEST[4]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
		$CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10 \+ $CRIT11 \+ $CRIT12 \+ \
		$CRIT13 \+ $CRIT14 \+ $CRIT15 \+ $CRIT16 \+ $CRIT17 \+ $CRIT18 \+ \
		$CRIT19 \+ $CRIT20 \+ $CRIT21 \+ $CRIT22 \+ $CRIT23 \+ $CRIT24 \+ \
		$CRIT25 \+ $CRIT26 \+ $CRIT27 \+ $CRIT28 \+ $CRIT29 \+ $CRIT30 \+ \
		$CRIT31 \+ $CRIT32 \+ $CRIT33 \+ $CRIT34 \+ $CRIT35 \+ $CRIT36`
CTRL[4]=84
ERROR[4]="Vibrational average NOT CORRECT"

PASSED=1
for i in 1 2 3 4
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
      echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} );"
      PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
   echo TEST ENDED PROPERLY
   exit 0
else
   echo THERE IS A PROBLEM
   exit 1
fi

%EOF%
