#!/usr/bin/env python
#    dft_rpbe
#    --------
#    Molecule:         He
#    Wave Function:    DFT PBE, RPBE0 / cc-pVTZ
#    Test Purpose:     Functional tests against reference output from LSDALTON

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final DFT energy',
      rel_tolerance = 1.0e-6)

# for PBE and RPBE we test against LSDALTON output data

f.add(string = '@ Excitation energy :',
      abs_tolerance = 1.0e-5)

test.run(['dft_pbe.dal'], ['He_cc-pVTZ.mol'], f={'out': f})
test.run(['dft_rpbe.dal'], ['He_cc-pVTZ.mol'], f={'out': f})

sys.exit(test.return_code)
