#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Full point group is:')
f.add(string = 'Represented as:')
f.add(string = 'Basis set changed to')

f.add(from_string = "Indirect spin-spin coupling between",
      num_lines = 17,
      abs_tolerance = 1.0e-3)

test.run(['soppa_vibavg_twobas.dal'], ['soppa_vibavg_twobas.mol'], f={'out': f},
         accepted_errors = ["not implemented for parallel calculations"])


sys.exit(test.return_code)
