#!/bin/bash

source /opt/intel/bin/compilervars.sh ia32
export PATH=$PATH':/opt/intel/mkl'

TMP_DIR=/tmp/dalton
SCRATCH_DIR=/scratch/dalton-cdash-scratch
mkdir -p $TMP_DIR

svn co http://dirac.chem.sdu.dk/svnDalton/dalton/branches/linsca-develop $TMP_DIR

cd $TMP_DIR
./setup --fc=ifort --cc=icc --debug --scratch=$SCRATCH_DIR -D BUILDNAME="linux-ifort-debug"

cd $TMP_DIR/build
make Nightly

rm -rf $TMP_DIR $SCRATCH_DIR

exit 0
