#!/bin/bash
source /com/OpenMPI/1.4.4/intel-ilp64/bin/openmpi.sh
source /com/intel/Compiler/11.1/064/mkl/tools/environment/mklvarsem64t.sh
TMP_DIR=/home/tkjaer/NightlyTestingCdash/tmp/DaltonReleaseompSCALAPACK64
SCRATCH_DIR=/scratch/tkjaer/DaltonReleaseompSCALAPACK64
rm -rf $TMP_DIR
rm -rf $SCRATCH_DIR

git clone git@repo.ctcc.no:dalton.git $TMP_DIR
cd $TMP_DIR
git checkout linsca-develop
export OMP_NUM_THREADS=3
export MATH_ROOT=/com/intel/mkl/10.1.1.019
MATH_ROOT=/com/intel/mkl/10.1.1.019
source /com/OpenMPI/1.4.4/intel-ilp64/bin/openmpi.sh
source /com/intel/Compiler/11.1/064/mkl/tools/environment/mklvarsem64t.sh
source /com/intel/Compiler/11.1/064/bin/intel64/ifortvars_intel64.sh
export LD_LIBRARY_PATH=/com/intel/Compiler/11.1/064/lib/intel64:/com/OpenMPI/1.4.4/intel-ilp64/lib:/com/intel/mkl/9.1.023/lib/em64t
./setup --fc=mpif90 --cc=mpicc --int64 --mpi --omp --scalapack --math="-Wl,--start-group /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_scalapack_ilp64.a /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_blacs_openmpi_ilp64.a /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_intel_ilp64.a /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_intel_thread.a /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_core.a -Wl,--end-group /com/intel/Compiler/11.1/064/lib/intel64/libiomp5.a -openmp -lpthread -lm" --scratch=$SCRATCH_DIR -D BUILDNAME="Grendel-SCALAPACK-OMP64-release"
cd $TMP_DIR/build
make depend
make Nightly
rm -rf $TMP_DIR 
rm -rf $SCRATCH_DIR
mv $TMP_DIR /home/tkjaer/NightlyTestingCdash/tmp/tmp3
rm -rf /home/tkjaer/NightlyTestingCdash/tmp/tmp3
exit 0

