#!/bin/bash
export PATH=/com/gfortran/4.4.3/bin:/usr/local/torque/bin:/com/bin:/usr/local/bin:/bin:/usr/bin:/com/intel/Compiler/11.1/064/mkl/lib/em64t
export LD_LIBRARY_PATH=/com/gfortran/4.4.3/lib64:/com/gfortran/4.4.3/lib:/com/intel/Compiler/11.1/064/mkl/lib/em64t:/com/intel/Compiler/11.1/064/lib/intel64
TMP_DIR=/home/tkjaer/NightlyTestingCdash/tmp/DaltonGfortranDebug
SCRATCH_DIR=/scratch/tkjaer/DaltonGfortranDebug
git clone git@repo.ctcc.no:dalton.git $TMP_DIR
cd $TMP_DIR
git checkout linsca-develop
source /com/gfortran/4.4.3/bin/gfortranvars.sh
mkdir $TMP_DIR/build
cd $TMP_DIR/build
export OMP_NUM_THREADS=1
export MATH_ROOT=/com/intel/Compiler/11.1/064/mkl
FC=gfortran CC=gcc cmake -DSCRATCH_DIR=$SCRATCH_DIR -DENABLE_BOUNDS_CHECK=1 -DCMAKE_BUILD_TYPE=Debug -DBUILDNAME=Grendel-linux-gfortran443-debug /home/tkjaer/NightlyTestingCdash/tmp/DaltonGfortranDebug
make depend
make Nightly
rm -rf $TMP_DIR 
rm -rf $SCRATCH_DIR
exit 0

