#!/bin/bash
export PATH=/com/gfortran/4.4.3/bin:/usr/local/torque/bin:/com/bin:/usr/local/bin:/bin:/usr/bin:/com/intel/Compiler/11.1/064/mkl/lib/em64t
export LD_LIBRARY_PATH=/com/gfortran/4.4.3/lib64:/com/gfortran/4.4.3/lib:/com/intel/Compiler/11.1/064/mkl/lib/em64t:/com/intel/Compiler/11.1/064/lib/intel64
TMP_DIR=/home/tkjaer/NightlyTestingCdash/tmp/DaltonGfortranRelease
SCRATCH_DIR=/scratch/tkjaer/DaltonGfortranRelease
git clone git@repo.ctcc.no:dalton.git $TMP_DIR
cd $TMP_DIR
git checkout -b linsca-develop origin/linsca-develop
source /com/intel/Compiler/11.1/064/bin/intel64/ifortvars_intel64.sh #liomp5
source /com/gfortran/4.4.3/bin/gfortranvars.sh
mkdir $TMP_DIR/build
cd $TMP_DIR/build
export OMP_NUM_THREADS=3
export MATH_ROOT=/com/intel/Compiler/11.1/064/mkl
cmake -DCMAKE_Fortran_COMPILER=/com/gfortran/4.4.3/bin/gfortran -DCMAKE_C_COMPILER=/com/gfortran/4.4.3/bin/gcc -DSCRATCH_DIR=$SCRATCH_DIR -DENABLE_OMP=1 -DCMAKE_BUILD_TYPE=Release -DUSERDEFINED_MATH="-L$MATH_ROOT/lib/em64t -lmkl_gf_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm" -DBUILDNAME=Grendel-linux-gfortran443-omp-release /home/tkjaer/NightlyTestingCdash/tmp/DaltonGfortranRelease
make depend
make Nightly
rm -rf $TMP_DIR 
rm -rf $SCRATCH_DIR
exit 0

