#!/bin/bash                                                                                                                     
export PATH=/com/gfortran/4.4.3/bin:/usr/local/torque/bin:/com/bin:/usr/local/bin:/bin:/usr/bin:/com/intel/Compiler/11.1/064/mkl/lib/em64t:/com/OpenMPI/1.6.3/gnu/bin:/com/OpenMPI/1.6.3/gnu/lib
export LD_LIBRARY_PATH=/com/gfortran/4.4.3/lib64:/com/gfortran/4.4.3/lib:/com/intel/Compiler/11.1/064/mkl/lib/em64t:/com/intel/Compiler/11.1/064/lib/intel64:/com/OpenMPI/1.6.3/gnu/bin:/com/OpenMPI/1.6.3/gnu/lib
TMP_DIR=/home/tkjaer/NightlyTestingCdash/tmp/DaltonGfortranDebugMPI
SCRATCH_DIR=/scratch/tkjaer/DaltonGfortranDebugMPI
rm -rf $TMP_DIR
rm -rf $SCRATCH_DIR
git clone git@repo.ctcc.no:dalton.git $TMP_DIR
cd $TMP_DIR
git checkout linsca-develop
git log --pretty=format:"%an" --since=1.day > /home/tkjaer/NightlyTestingCdash/SINNERS
source /com/gfortran/4.4.3/bin/gfortranvars.sh
source /com/OpenMPI/1.6.3/gnu/bin/openmpi.sh
mkdir $TMP_DIR/build
cd $TMP_DIR/build
export OMP_NUM_THREADS=1
export MATH_ROOT=/com/intel/Compiler/11.1/064/mkl
FC=mpif90 CC=mpicc cmake -DSCRATCH_DIR=$SCRATCH_DIR -DENABLE_MPI=1 -DCMAKE_BUILD_TYPE=Debug -DENABLE_CODE_COVERAGE=1 -DENABLE_T\
IMINGS=1 -DBUILDNAME=Grendel-linux-gfortran443-debugMPI /home/tkjaer/NightlyTestingCdash/tmp/DaltonGfortranDebugMPI
cp /home/tkjaer/NightlyTestingCdash/git_revision_info.f90 $TMP_DIR/lsutil/.
cp /home/tkjaer/NightlyTestingCdash/compilation_info.f90 $TMP_DIR/lsutil/.
make depend
#make Experimental                                                                                                              
make Nightly
exit 0
