#!/bin/bash
TMP_DIR=/home/tkjaer/NightlyTestingCdash/tmp/DaltonGfortranRelease
SCRATCH_DIR=/tmp/tkjaer/DaltonGfortranRelease
rm -rf $TMP_DIR 
rm -rf $SCRATCH_DIR
export PATH=/com/gcc/4.7.2/bin:/usr/local/torque/bin:/com/bin:/usr/local/bin:/bin:/usr/bin:/com/intel/Compiler/11.1/064/mkl/lib/em64t
export LD_LIBRARY_PATH=/com/gfortran/4.7.2/lib64:/com/gfortran/4.7.2/lib:/com/intel/Compiler/11.1/064/mkl/lib/em64t:/com/intel/Compiler/11.1/064/lib/intel64
git clone git@gitlab.com:dalton/dalton.git $TMP_DIR
cd $TMP_DIR
#git checkout -b linsca-develop origin/linsca-develop
#git checkout Dalton2013_release
git log --pretty=format:"%an" --since=1.day > /home/tkjaer/NightlyTestingCdash/SINNERS
source /com/intel/Compiler/11.1/064/bin/intel64/ifortvars_intel64.sh #liomp5
source /com/gcc/4.7.2/load.sh
cd $TMP_DIR
#mkdir $TMP_DIR/build
#cd $TMP_DIR/build
export OMP_NUM_THREADS=3
export MATH_ROOT=/com/intel/Compiler/11.1/064/mkl
export DALTON_TMPDIR=$SCRATCH_DIR
export DALTON_NUM_MPI_PROCS=1
export CTEST_PROJECT_NAME=LSDALTON

#make release
#tar xzf DALTON-2013.0-Source.tar.gz
#cd DALTON-2013.0-Source

./setup --fc=gfortran --cc=gcc --cxx=g++ --omp --explicit-libs="-L$MATH_ROOT/lib/em64t -lmkl_gf_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm" -D BUILDNAME="MB-Grendel-linux-gfortran472-omp-release" build

cd build
#make
#make depend
#make Nightly
#make Experimental
ctest -D Nightly -L linsca
#make -j4 
#ctest -L linsca -j4
exit 0

