#!/bin/bash
TMP_DIR=/home/tkjaer/NightlyTestingCdash/tmp/LSDAltonIfortMPIdebug
SCRATCH_DIR=/tmp/tkjaer/LSDAltonIfortMPIdebug
rm -rf $TMP_DIR 
rm -rf $SCRATCH_DIR

git clone --recursive git@gitlab.com:dalton/dalton.git $TMP_DIR
cd $TMP_DIR
git log --pretty=format:"%an" --since=1.day > /home/tkjaer/NightlyTestingCdash/SINNERS


export PATH=/com/git/2.3.2/bin:$PATH
source /com/bin/modules.sh

module load intel/14.0.2.144
module load openmpi/intel/1.6.5

export MATH_ROOT=/home/com/intel/composer_xe_2013.1.117/mkl
export OMP_NUM_THREADS=4
export DALTON_NUM_MPI_PROCS=4
export DALTON_TMPDIR=$SCRATCH_DIR
export CTEST_PROJECT_NAME=LSDALTON

./setup --fc=mpif90 --cc=mpicc --cxx=mpic++ --omp --mpi --type=debug --check -DENABLE_DEC=ON -DENABLE_TENSORS=ON -D BUILDNAME="MB-Grendel-linux-ifort-mpi-omp-debug"

cd $TMP_DIR/build
ctest -D Nightly -L linsca -j4

exit 0

