#!/bin/bash
TMP_DIR=/home/tkjaer/NightlyTestingCdash/tmp/DaltonReleaseompSCALAPACK64
SCRATCH_DIR=/tmp/tkjaer/DaltonReleaseompSCALAPACK64
rm -rf $TMP_DIR
rm -rf $SCRATCH_DIR
mv $TMP_DIR /home/tkjaer/NightlyTestingCdash/tmp/tmp3
rm -rf /home/tkjaer/NightlyTestingCdash/tmp/tmp3
#due to launch with crontab PATH is empty. We need PATH to git and cmake, ..
export PATH=/usr/local/torque/bin:/com/bin:/usr/local/bin:/bin:/usr/bin

git clone --recursive git@gitlab.com:dalton/dalton.git $TMP_DIR
cd $TMP_DIR
export OMP_NUM_THREADS=3
export MATH_ROOT=/com/intel/mkl/10.1.1.019
source /com/OpenMPI/1.4.4/intel-ilp64/bin/openmpi.sh
source /com/intel/Compiler/11.1/064/mkl/tools/environment/mklvarsem64t.sh
source /com/intel/Compiler/11.1/064/bin/intel64/ifortvars_intel64.sh
export LD_LIBRARY_PATH=/com/OpenMPI/1.4.4/intel-ilp64/lib
cd $TMP_DIR
export DALTON_TMPDIR=$SCRATCH_DIR
export DALTON_NUM_MPI_PROCS=5
export CTEST_PROJECT_NAME=LSDALTON
./setup --fc=mpif90 --cc=mpicc --cxx=mpic++ --int64 --mpi --omp --scalapack --lapack=none --blas=none --explicit-libs="-Wl,--start-group /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_scalapack_ilp64.a /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_blacs_openmpi_ilp64.a /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_intel_ilp64.a /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_intel_thread.a /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_core.a -Wl,--end-group /com/intel/Compiler/11.1/064/lib/intel64/libiomp5.a -openmp -lpthread -lm" -D BUILDNAME="MB-Grendel-SCALAPACK-OMP64-release"
cd $TMP_DIR/build
ctest -D Nightly -L linsca

exit 0

