#!/bin/bash
#source /com/OpenMPI/1.6.3/gnu/load.sh
source /com/gcc/4.7.2/load.sh
source /com/OpenMPI/1.6.5/gnu/bin/load.sh
export PATH=/usr/local/torque/bin:/com/bin:/usr/local/bin:/bin:/usr/bin:/com/intel/Compiler/11.1/064/mkl/lib/em64t:/com/OpenMPI/1.6.3/gnu/bin:/com/OpenMPI/1.6.3/gnu/lib:$PATH
export LD_LIBRARY_PATH=/com/intel/Compiler/11.1/064/mkl/lib/em64t:/com/intel/Compiler/11.1/064/lib/intel64:/com/OpenMPI/1.6.3/gnu/bin:/com/OpenMPI/1.6.3/gnu/lib:$LD_LIBRARY_PATH
TMP_DIR=/home/tkjaer/NightlyTestingCdash/tmp/DaltonGfortranDebugMPI
SCRATCH_DIR=/tmp/tkjaer/DaltonGfortranDebugMPI
rm -rf $TMP_DIR 
rm -rf $SCRATCH_DIR
git clone git@repo.ctcc.no:dalton.git $TMP_DIR
cd $TMP_DIR
#git checkout linsca-develop
#git checkout Dalton2013_release
git log --pretty=format:"%an" --since=1.day > /home/tkjaer/NightlyTestingCdash/SINNERS
cd $TMP_DIR
mkdir $TMP_DIR/build
cd $TMP_DIR/build
export OMP_NUM_THREADS=1
export MATH_ROOT=/com/intel/Compiler/11.1/064/mkl
#-DENABLE_INTERNAL_MATH=1 
export DALTON_TMPDIR=$SCRATCH_DIR
export DALTON_NUM_MPI_PROCS=5
export CTEST_PROJECT_NAME=LSDALTON
FC=mpif90 CC=mpicc CXX=mpic++ cmake -DENABLE_MPI=1 -DCMAKE_BUILD_TYPE=Debug -DENABLE_CODE_COVERAGE=1 -DENABLE_TIMINGS=1 -DENABLE_BLAS=ON -DENABLE_LAPACK=ON -DENABLE_RELEASE=0 -DBUILDNAME=MB-Grendel-linux-gfortran472-debugMPI /home/tkjaer/NightlyTestingCdash/tmp/DaltonGfortranDebugMPI
#cp /home/tkjaer/NightlyTestingCdash/git_revision_info.f90 $TMP_DIR/lsutil/.
#cp /home/tkjaer/NightlyTestingCdash/compilation_info.f90 $TMP_DIR/lsutil/.
#make depend
#make Experimental
#make Nightly
ctest -D Nightly -L linsca
exit 0

