#!/bin/bash
TMP_DIR=/home/tkjaer/NightlyTestingCdash/tmp/DaltonReleaseompSCALAPACK64Release
SCRATCH_DIR=/tmp/tkjaer/DaltonReleaseompSCALAPACK64Release
rm -rf $TMP_DIR
rm -rf $SCRATCH_DIR
mv $TMP_DIR /home/tkjaer/NightlyTestingCdash/tmp/tmp3
rm -rf /home/tkjaer/NightlyTestingCdash/tmp/tmp3
export PATH=/com/intel/Compiler/11.1/064/bin/intel64:/usr/local/torque/bin:/home/com/intel/composer_xe_2011_sp1.8.273/bin/intel64:/com/bin:/usr/local/bin:/bin:/usr/bin:/home/com/intel/composer_xe_2011_sp1.8.273/mpirt/bin/intel64
source /com/OpenMPI/1.4.4/intel-ilp64/bin/openmpi.sh
source /com/intel/Compiler/11.1/064/mkl/tools/environment/mklvarsem64t.sh

git clone git@repo.ctcc.no:dalton.git $TMP_DIR
cd $TMP_DIR
#git checkout linsca-develop
git checkout Dalton2014
export OMP_NUM_THREADS=3
export MATH_ROOT=/com/intel/mkl/10.1.1.019
MATH_ROOT=/com/intel/mkl/10.1.1.019
source /com/OpenMPI/1.4.4/intel-ilp64/bin/openmpi.sh
source /com/intel/Compiler/11.1/064/mkl/tools/environment/mklvarsem64t.sh
source /com/intel/Compiler/11.1/064/bin/intel64/ifortvars_intel64.sh
export LD_LIBRARY_PATH=/com/intel/Compiler/11.1/064/lib/intel64:/com/OpenMPI/1.4.4/intel-ilp64/lib:/com/intel/mkl/9.1.023/lib/em64t
cd $TMP_DIR
export DALTON_TMPDIR=$SCRATCH_DIR
export DALTON_NUM_MPI_PROCS=5
export CTEST_PROJECT_NAME=LSDALTON
./setup --fc=mpif90 --cc=mpicc --cxx=mpic++ --int64 --mpi --omp --scalapack --blas=none --lapack=none --explicit-libs="-Wl,--start-group /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_scalapack_ilp64.a /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_blacs_openmpi_ilp64.a /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_intel_ilp64.a /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_intel_thread.a /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_core.a -Wl,--end-group /com/intel/Compiler/11.1/064/lib/intel64/libiomp5.a -openmp -lpthread -lm" -D BUILDNAME="RB-Grendel-SCALAPACK-OMP64-release"

cd build
make release
#this creates a tar file named DALTON-Source.tar.gz
if [[ -e  DALTON-Source.tar.gz ]]; then
 tar -zxvf DALTON-Source.tar.gz
 cd DALTON-Source
./setup --fc=mpif90 --cc=mpicc --cxx=mpic++ --int64 --mpi --omp --scalapack --blas=none --lapack=none --explicit-libs="-Wl,--start-group /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_scalapack_ilp64.a /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_blacs_openmpi_ilp64.a /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_intel_ilp64.a /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_intel_thread.a /com/intel/Compiler/11.1/064/mkl/lib/em64t/libmkl_core.a -Wl,--end-group /com/intel/Compiler/11.1/064/lib/intel64/libiomp5.a -openmp -lpthread -lm" -D BUILDNAME="RB-Grendel-SCALAPACK-OMP64-release"
 cd build
 ctest --track ReleaseBranch2014MakeRelease -D Nightly -L linsca
fi
exit 0

