*comdeck clunit.inc $Revision: 1.1.2.1 $ 
* CLUNIT
      COMMON/CLUNIT/LUIN,LUOUT,LUCIVI,LU1INT,LU2INT,LUPRP,
     &              LUDIA,LUC,LUHC,
     &              LUSC1,LUSC2,LUSC3,
     &              LUSC34,LUSC35,LUSC36,LUSC37,LUSC38,LUSC39,
     &              LUSC40,LUSC41,
     &              LUCIVO,LUORB,LUMOIN,LUMOUT,LUEXC,LU_CCAMP,
     &              LUCMOL,LU90,LU91,LU_LUWRT,LUDUMPF
