*comdeck lucinp.inc $Revision: 1.1.2.1 $ 
*./LUCINP/
      INTEGER PNTGRP,EXTSPC
      COMMON/LUCINP/PNTGRP,NIRREP,NSMCMP,MAXML,MAXL,
     &              INTSPC,EXTSPC,NRSSH(MXPIRR,3),
     &              MNRS1R,MXRS1R,MNRS3R,MXRS3R,NACTEL,
     &              NSMOB,NRS0SH(1,MXPIRR),NRS4SH(MXPIRR,MXPR4T),
     &              MXR4TP, MXHR0,MXER4,
     &              NINASH(MXPIRR),
     &              INTXCI,NDELSH(MXPIRR),MNRS10,MXRS30,
     &              MNRS1RE,MXRS1RE,MNRS3RE,MXRS3RE,
     &              MNRS1ZE,MXRS1ZE,MNRS3ZE,MXRS3ZE,
     &              MPORENP,MPORENR,MPORENZ
