/*
C...   Copyright (c) 2005 by the authors of Dalton (see below).
C...   All Rights Reserved.
C...
C...   The source code in this file is part of
C...   "Dalton, a molecular electronic structure program, Release 2.0
C...   (2005), written by C. Angeli, K. L. Bak,  V. Bakken,
C...   O. Christiansen, R. Cimiraglia, S. Coriani, P. Dahle,
C...   E. K. Dalskov, T. Enevoldsen, B. Fernandez, C. Haettig,
C...   K. Hald, A. Halkier, H. Heiberg, T. Helgaker, H. Hettema,
C...   H. J. Aa. Jensen, D. Jonsson, P. Joergensen, S. Kirpekar,
C...   W. Klopper, R.Kobayashi, H. Koch, O. B. Lutnaes, K. V. Mikkelsen,
C...   P. Norman, J.Olsen, M. J. Packer, T. B. Pedersen, Z. Rinkevicius,
C...   E. Rudberg, T. A. Ruden, K. Ruud, P. Salek, A. Sanchez de Meras,
C...   T. Saue, S. P. A. Sauer, B. Schimmelpfennig, K. O. Sylvester-Hvid,
C...   P. R. Taylor, O. Vahtras, D. J. Wilson, H. Agren.
C...   This source code is provided under a written licence and may be
C...   used, copied, transmitted, or stored only in accord with that
C...   written licence.
C...
C...   In particular, no part of the source code or compiled modules may
C...   be distributed outside the research group of the licence holder.
C...   This means also that persons (e.g. post-docs) leaving the research
C...   group of the licence holder may not take any part of Dalton,
C...   including modified files, with him/her, unless that person has
C...   obtained his/her own licence.
C...
C...   For questions concerning this copyright write to:
C...      dalton-admin@kjemi.uio.no
C...
C...   For information on how to get a licence see:
C...      http://www.kjemi.uio.no/software/dalton/dalton.html
C
*/
/*-*-mode: C; c-indentation-style: "bsd"; c-basic-offset: 4; -*-*/
/* fun-mpw.c:

   Automatically generated code implementing MPW functional and
   its derivatives. It is generated by func-codegen.pl being a part of
   a "Automatic code generation framework for analytical functional
   derivative evaluation", Pawel Salek, 2005

    This functional is connected by making following changes:
    1. add "extern Functional mpwFunctional;" to 'functionals.h'
    2. add "&mpwFunctional," to 'functionals.c'
    3. add "fun-mpw.c" to 'Makefile.am', 'Makefile.in' or 'Makefile'.

    This functional has been generated from following input:
    ------ cut here -------
rho:  rhoa + rhob;
grad: sqrt(grada*grada + gradb*gradb + 2*gradab);
zeta: (rhoa-rhob)/(rhoa+rhob);

Ax:   -3/4*(6/%PI)^(1/3);
b:    0.0046;
c:    1.6455;
d:    3.73;
bet:  5*((36*%PI)^(-5/3));

xa:    grada/(rhoa^(4/3));
xb:    gradb/(rhob^(4/3));

F0a:   b*xa^2-(b-bet)*xa^2*exp(-c*xa^2)-10^(-6)*xa^4;
F0b:   b*xb^2-(b-bet)*xb^2*exp(-c*xb^2)-10^(-6)*xb^4;

F1a:   1+6*b*xa*asinh(xa)-(10^(-6)*xa^4)/Ax;
F1b:   1+6*b*xb*asinh(xb)-(10^(-6)*xb^4)/Ax;

Fa: F0a/F1a;
Fb: F0b/F1b;

Exa: -rhoa^(4/3)*Fa;
Exb: -rhob^(4/3)*Fb;

K(rhoa,rhob,grada,gradb,gradab):=(Exa+Exb);


    ------ cut here -------
*/

 
/* strictly conform to XOPEN ANSI C standard */
#if !defined(SYS_DEC)
/* XOPEN compliance is missing on old Tru64 4.0E Alphas and pow() prototype
 * is not specified. */
#define _XOPEN_SOURCE          500
#define _XOPEN_SOURCE_EXTENDED 1
#endif
#include <math.h>
#include <stddef.h>
 
#define __CVERSION__
 
#include "functionals.h"
 
/* INTERFACE PART */
static int mpw_isgga(void) { return 1; } /* FIXME: detect! */
static int mpw_read(const char *conf_line);
static real mpw_energy(const FunDensProp* dp);
static void mpw_first(FunFirstFuncDrv *ds,   real factor,
                         const FunDensProp* dp);
static void mpw_second(FunSecondFuncDrv *ds, real factor,
                          const FunDensProp* dp);
static void mpw_third(FunThirdFuncDrv *ds,   real factor,
                         const FunDensProp* dp);
static void mpw_fourth(FunFourthFuncDrv *ds,   real factor,
                          const FunDensProp* dp);
 
Functional mPWFunctional = {
  "mPW",       /* name */
  mpw_isgga,   /* gga-corrected */
  mpw_read,
  NULL,
  mpw_energy,
  mpw_first,
  mpw_second,
  mpw_third,
  mpw_fourth
};
 
/* IMPLEMENTATION PART */
static int
mpw_read(const char *conf_line)
{
    fun_set_hf_weight(0);
    return 1;
}

static real
mpw_energy(const FunDensProp *dp)
{
    real res;
    real rhoa = dp->rhoa, rhob = dp->rhob;
    real grada = dp->grada, gradb = dp->gradb, gradab = dp->gradab;

    real t1, t2, t3, t4, t5, t6, t7, t8, t9, t10;
    real t11, t12, t13, t14, t15;

    t1 = 1/pow(6.0,0.333333333333333);
    t2 = pow(3.141592653589793,0.333333333333333);
    t3 = pow(grada,4.0);
    t4 = 1/pow(rhoa,5.333333333333333);
    t5 = pow(rhoa,1.333333333333333);
    t6 = 1/t5;
    t7 = pow(grada,2.0);
    t8 = 1/pow(rhoa,2.666666666666667);
    t9 = 0.0046-0.138888888888889/(pow(3.141592653589793,
        1.666666666666667)*pow(36.0,0.666666666666667));
    t10 = pow(gradb,4.0);
    t11 = 1/pow(rhob,5.333333333333333);
    t12 = pow(rhob,1.333333333333333);
    t13 = 1/t12;
    t14 = pow(gradb,2.0);
    t15 = 1/pow(rhob,2.666666666666667);

   /* code */
    res = -1.0*t5*(-1.0*t7*t8*t9/pow(2.718281828459045,1.6455*
        t7*t8)+0.0046*t7*t8-1.0E-6*t3*t4)/(0.0276*grada*asinh(grada*
        t6)*t6+1.3333333333333334E-6*t1*t2*t3*t4+1.0)-1.0*t12*(-1.0*
        t14*t15*t9/pow(2.718281828459045,1.6455*t14*t15)+0.0046*t14*
        t15-1.0E-6*t10*t11)/(1.3333333333333334E-6*t1*t10*t11*t2+0.0276*
        gradb*asinh(gradb*t13)*t13+1.0);

    return res;
}

static void
mpw_first_helper(real rhoa, real grada, real *res)
{    real t1, t2, t3, t4, t5, t6, t7, t8, t9, t10;
    real t11, t12, t13, t14, t15, t16, t17, t18;
    real t19;

    t1 = 1/pow(6.0,0.333333333333333);
    t2 = pow(3.141592653589793,0.333333333333333);
    t3 = pow(grada,4.0);
    t4 = 1/pow(rhoa,5.333333333333333);
    t5 = pow(rhoa,1.333333333333333);
    t6 = 1/t5;
    t7 = asinh(grada*t6);
    t8 = 0.0276*grada*t7*t6+1.3333333333333334E-6*t1*t2*t3*
        t4+1.0;
    t9 = 1/t8;
    t10 = 1/pow(rhoa,6.333333333333333);
    t11 = pow(grada,2.0);
    t12 = 1/pow(rhoa,3.666666666666667);
    t13 = 0.0046-0.138888888888889/(pow(3.141592653589793,
        1.666666666666667)*pow(36.0,0.666666666666667));
    t14 = 1/pow(rhoa,2.666666666666667);
    t15 = 1/pow(2.718281828459045,1.6455*t11*t14);
    t16 = -1.0E-6*t3*t4-1.0*t11*t13*t14*t15+0.0046*t11*t14;
    t17 = 1/
        sqrt(t11*t14+1.0);
    t18 = 1/pow(t8,2.0);
    t19 = pow(grada,3.0);

   /* code */
    res[0] = t16*t18*t5*(-0.0368*t7*grada/pow(rhoa,2.333333333333333)-
        7.111111111111111E-6*t1*t10*t2*t3-0.0368*t11*t17*t12)-1.333333333333333*
        t16*t9*pow(rhoa,0.333333333333333)-1.0*(5.333333333333334E-6*
        t10*t3+2.666666666666667*t11*t12*t13*t15-4.388*t13*t3*t10*
        t15-0.012266666666667*t11*t12)*t5*t9;
    res[1] = t16*t18*t5*(0.0276*t7*t6+5.333333333333334E-6*
        t1*t19*t2*t4+0.0276*grada*t17*t14)-1.0*t5*t9*(-2.0*t13*t14*
        t15*grada-4.0E-6*t19*t4+3.291*t13*t19*t4*t15+0.0092*grada*
        t14);
}

static void
mpw_first(FunFirstFuncDrv *ds, real factor, const FunDensProp *dp)
{
    real res[2];

    mpw_first_helper(dp->rhoa, dp->grada, res);
   /* Final assignment */
    ds->df1000 += factor*res[0];
    ds->df0010 += factor*res[1];


    if(fabs(dp->rhoa-dp->rhob)>1e-13 ||
       fabs(dp->grada-dp->gradb)>1e-13)
        mpw_first_helper(dp->rhob, dp->gradb, res);
    ds->df0100 += factor*res[0];
    ds->df0001 += factor*res[1];

}

static void
mpw_second_helper(real rhoa, real grada, real *res)
{
    real t1, t2, t3, t4, t5, t6, t7, t8, t9, t10;
    real t11, t12, t13, t14, t15, t16, t17, t18;
    real t19, t20, t21, t22, t23, t24, t25, t26;
    real t27, t28, t29, t30;

    t1 = 1/pow(6.0,0.333333333333333);
    t2 = pow(3.141592653589793,0.333333333333333);
    t3 = pow(grada,4.0);
    t4 = 1/pow(rhoa,5.333333333333333);
    t5 = pow(rhoa,1.333333333333333);
    t6 = 1/t5;
    t7 = asinh(grada*t6);
    t8 = 0.0276*grada*t7*t6+1.3333333333333334E-6*t1*t2*t3*
        t4+1.0;
    t9 = 1/t8;
    t10 = 1/pow(rhoa,6.333333333333333);
    t11 = pow(grada,2.0);
    t12 = 1/pow(rhoa,3.666666666666667);
    t13 = 0.0046-0.138888888888889/(pow(3.141592653589793,
        1.666666666666667)*pow(36.0,0.666666666666667));
    t14 = 1/pow(rhoa,2.666666666666667);
    t15 = 1/pow(2.718281828459045,1.6455*t11*t14);
    t16 = 5.333333333333334E-6*t10*t3+2.666666666666667*t11*
        t12*t13*t15-4.388*t13*t3*t10*t15-0.012266666666667*t11*t12;
    t17 = pow(rhoa,
        0.333333333333333);
    t18 = -1.0E-6*t3*t4-1.0*t11*t13*t14*t15+0.0046*t11*t14;
    t19 = sqrt(t11*
        t14+1.0);
    t20 = 1/t19;
    t21 = 1/pow(rhoa,2.333333333333333);
    t22 = -7.111111111111111E-6*t1*t10*t2*t3-0.0368*grada*
        t7*t21-0.0368*t11*t20*t12;
    t23 = 1/pow(t8,2.0);
    t24 = pow(grada,3.0);
    t25 = -2.0*t13*t14*t15*grada-4.0E-6*t24*t4+3.291*t13*
        t24*t4*t15+0.0092*grada*t14;
    t26 = 0.0276*t7*t6+5.333333333333334E-6*t1*t2*t24*t4+
        0.0276*grada*t20*t14;
    t27 = 1/pow(rhoa,7.333333333333333);
    t28 = 1/pow(rhoa,4.666666666666667);
    t29 = 1/pow(t8,3.0);
    t30 = 1/pow(t19,3.0);

   /* code */
    res[0] = -1.0*t16*t5*t9-1.333333333333333*t17*t18*t9+
        t22*t23*t5*t18;
    res[1] = t26*t23*t5*t18-1.0*t25*t5*t9;
    res[2] = -1.0*t5*t9*(-19.254544*t13*t15*pow(grada,6.0)/
        pow(rhoa,10.0)-3.377777777777778E-5*t27*t3-9.777777777777779*
        t11*t13*t15*t28+0.044977777777778*t11*t28+39.492*t13*t3*t27*
        t15)+t18*t23*t5*(0.085866666666667*t7*grada/pow(rhoa,3.333333333333333)+
        4.503703703703703E-5*t1*t2*t27*t3+0.184*t11*t20*t28-0.049066666666667*
        t3*t30*t27)-0.444444444444444*t18*t9/pow(rhoa,0.666666666666667)-
        2.666666666666667*t16*t17*t9-2.0*t18*pow(t22,2.0)*t29*t5+2.0*
        t16*t22*t23*t5+2.666666666666667*t17*t18*t22*t23;
    res[3] = -1.0*t5*t9*(14.440908*t13*t15*pow(grada,5.0)/
        pow(rhoa,9.0)+5.333333333333333*t12*t13*t15*grada+2.1333333333333335E-5*
        t10*t24-26.328*t13*t24*t10*t15-0.024533333333333*grada*t12)-
        1.333333333333333*t17*t25*t9-2.0*t18*t22*t26*t29*t5+t18*t23*
        (-2.8444444444444444E-5*t1*t10*t2*t24-0.0368*t7*t21-0.1104*
        grada*t20*t12+0.0368*t24*t30*t10)*t5+1.333333333333333*t17*
        t18*t23*t26+t22*t23*t5*t25+t26*t23*t5*t16;
    res[4] = -1.0*t5*t9*(-10.830681*t13*t15*t3/pow(rhoa,8.0)-
        1.2E-5*t11*t4+16.455*t13*t11*t4*t15-2.0*t13*t14*t15+0.0092*
        t14)+t18*t23*(-0.0276*t11*t30*t4+1.6E-5*t1*t11*t2*t4+0.0552*
        t20*t14)*t5-2.0*t18*pow(t26,2.0)*t29*t5+2.0*t23*t25*t26*t5;

}

static void
mpw_second(FunSecondFuncDrv *ds, real factor, const FunDensProp* dp)
{
    real res[5];
 
    mpw_second_helper(dp->rhoa, dp->grada, res);

    ds->df1000 += factor*res[0];
    ds->df0010 += factor*res[1];

    ds->df2000 += factor*res[2];
    ds->df1010 += factor*res[3];
    ds->df0020 += factor*res[4];


    if(fabs(dp->rhoa-dp->rhob)>1e-13 ||
       fabs(dp->grada-dp->gradb)>1e-13)
        mpw_second_helper(dp->rhob, dp->gradb, res);
    ds->df0100 += factor*res[0];
    ds->df0001 += factor*res[1];

    ds->df0200 += factor*res[2];
    ds->df0101 += factor*res[3];
    ds->df0002 += factor*res[4];

}

static void
mpw_third_helper(real rhoa, real grada, real *res)
{
    real t1, t2, t3, t4, t5, t6, t7, t8, t9, t10;
    real t11, t12, t13, t14, t15, t16, t17, t18;
    real t19, t20, t21, t22, t23, t24, t25, t26;
    real t27, t28, t29, t30, t31, t32, t33, t34;
    real t35, t36, t37, t38, t39, t40, t41, t42;
    real t43, t44, t45, t46, t47, t48, t49, t50;

    t1 = 1/pow(6.0,0.333333333333333);
    t2 = pow(3.141592653589793,0.333333333333333);
    t3 = pow(grada,4.0);
    t4 = 1/pow(rhoa,5.333333333333333);
    t5 = pow(rhoa,1.333333333333333);
    t6 = 1/t5;
    t7 = asinh(grada*t6);
    t8 = 0.0276*grada*t7*t6+1.3333333333333334E-6*t1*t2*t3*
        t4+1.0;
    t9 = 1/t8;
    t10 = 1/pow(rhoa,6.333333333333333);
    t11 = pow(grada,2.0);
    t12 = 1/pow(rhoa,3.666666666666667);
    t13 = 0.0046-0.138888888888889/(pow(3.141592653589793,
        1.666666666666667)*pow(36.0,0.666666666666667));
    t14 = 1/pow(rhoa,2.666666666666667);
    t15 = 1/pow(2.718281828459045,1.6455*t11*t14);
    t16 = 5.333333333333334E-6*t10*t3+2.666666666666667*t11*
        t12*t13*t15-4.388*t13*t3*t10*t15-0.012266666666667*t11*t12;
    t17 = pow(rhoa,
        0.333333333333333);
    t18 = -1.0E-6*t3*t4-1.0*t11*t13*t14*t15+0.0046*t11*t14;
    t19 = sqrt(t11*
        t14+1.0);
    t20 = 1/t19;
    t21 = 1/pow(rhoa,2.333333333333333);
    t22 = -7.111111111111111E-6*t1*t10*t2*t3-0.0368*grada*
        t7*t21-0.0368*t11*t20*t12;
    t23 = 1/pow(t8,2.0);
    t24 = pow(grada,3.0);
    t25 = -2.0*t13*t14*t15*grada-4.0E-6*t24*t4+3.291*t13*
        t24*t4*t15+0.0092*grada*t14;
    t26 = 0.0276*t7*t6+5.333333333333334E-6*t1*t2*t24*t4+
        0.0276*grada*t20*t14;
    t27 = 1/pow(rhoa,7.333333333333333);
    t28 = 1/pow(rhoa,4.666666666666667);
    t29 = pow(grada,6.0);
    t30 = 1/pow(rhoa,10.0);
    t31 = -3.377777777777778E-5*t27*t3-9.777777777777779*
        t11*t13*t15*t28+0.044977777777778*t11*t28-19.254544*t13*t29*
        t30*t15+39.492*t13*t3*t27*t15;
    t32 = 1/pow(rhoa,0.666666666666667);
    t33 = pow(t22,2.0);
    t34 = 1/pow(t8,3.0);
    t35 = 1/pow(t19,3.0);
    t36 = 1/pow(rhoa,3.333333333333333);
    t37 = 0.085866666666667*grada*t7*t36+4.503703703703703E-5*
        t1*t2*t27*t3+0.184*t11*t20*t28-0.049066666666667*t3*t35*t27;
    t38 = pow(grada,
        5.0);
    t39 = 1/pow(rhoa,9.0);
    t40 = 5.333333333333333*t12*t13*t15*grada+2.1333333333333335E-5*
        t10*t24+14.440908*t13*t38*t39*t15-26.328*t13*t24*t10*t15-0.024533333333333*
        grada*t12;
    t41 = -2.8444444444444444E-5*t1*t10*t2*t24-0.0368*t7*
        t21-0.1104*grada*t20*t12+0.0368*t24*t35*t10;
    t42 = 1/pow(rhoa,8.0);
    t43 = -1.2E-5*t11*t4-10.830681*t13*t3*t42*t15+16.455*
        t13*t11*t4*t15-2.0*t13*t14*t15+0.0092*t14;
    t44 = pow(t26,2.0);
    t45 = -0.0276*t11*t35*t4+1.6E-5*t1*t11*t2*t4+0.0552*t20*
        t14;
    t46 = 1/pow(rhoa,8.333333333333334);
    t47 = 1/pow(rhoa,5.666666666666667);
    t48 = 1/pow(rhoa,11.0);
    t49 = 1/pow(t8,4.0);
    t50 = 1/pow(t19,5.0);

   /* code */
    res[0] = -1.0*t16*t5*t9-1.333333333333333*t17*t18*t9+
        t22*t23*t5*t18;
    res[1] = t26*t23*t5*t18-1.0*t25*t5*t9;
    res[2] = -1.0*t31*t5*t9-0.444444444444444*t18*t32*t9-
        2.666666666666667*t16*t17*t9-2.0*t18*t33*t34*t5+2.0*t16*t22*
        t23*t5+2.666666666666667*t17*t18*t22*t23+t37*t23*t5*t18;
    res[3] = -1.0*t40*t5*t9-1.333333333333333*t17*t25*t9-
        2.0*t18*t22*t26*t34*t5+1.333333333333333*t17*t18*t23*t26+t22*
        t23*t5*t25+t41*t23*t5*t18+t26*t23*t5*t16;
    res[4] = -1.0*t43*t5*t9-2.0*t18*t34*t44*t5+2.0*t23*t25*
        t26*t5+t45*t23*t5*t18;
    res[5] = -1.0*t5*t9*(-84.488939072*t13*t15*pow(grada,
        8.0)/pow(rhoa,13.66666666666667)+45.62962962962963*t11*t13*
        t15*t47-0.209896296296296*t11*t47+2.477037037037037E-4*t3*
        t46+365.836336*t13*t29*t48*t15-332.5128888888888*t13*t3*t46*
        t15)+t18*t23*t5*(-0.286222222222222*t7*grada/pow(rhoa,4.333333333333333)-
        0.196266666666667*t29*t50*t48-0.973155555555556*t11*t20*t47+
        0.605155555555555*t3*t35*t46-3.302716049382716E-4*t1*t2*t3*
        t46)+0.296296296296296*t18*t9/pow(rhoa,1.666666666666667)-
        1.333333333333333*t16*t32*t9-4.0*t17*t31*t9+6.0*t18*pow(t22,
        3.0)*t49*t5-6.0*t18*t22*t34*t37*t5+3.0*t16*t23*t37*t5-6.0*
        t16*t33*t34*t5+3.0*t22*t23*t31*t5+4.0*t17*t18*t23*t37-8.0*
        t17*t18*t33*t34+1.333333333333333*t18*t22*t23*t32+8.0*t16*
        t17*t22*t23;
    res[6] = -1.0*t5*t9*(63.366704304*t13*t15*pow(grada,7.0)/
        pow(rhoa,12.66666666666667)-19.55555555555556*t13*t15*t28*
        grada+0.089955555555556*grada*t28-1.351111111111111E-4*t24*
        t27-245.495436*t13*t38*t30*t15+190.1466666666666*t13*t24*t27*
        t15)-2.666666666666667*t17*t40*t9-0.444444444444444*t25*t32*
        t9+6.0*t18*t26*t33*t49*t5-4.0*t18*t22*t34*t41*t5+2.0*t16*t23*
        t41*t5+2.0*t22*t23*t40*t5-2.0*t18*t26*t34*t37*t5+t18*t23*(0.085866666666667*
        t7*t36+0.1472*t38*t50*t30+0.453866666666667*grada*t20*t28-
        0.380266666666667*t24*t35*t27+1.8014814814814814E-4*t1*t2*
        t24*t27)*t5-2.0*t25*t33*t34*t5-4.0*t16*t22*t26*t34*t5+2.666666666666667*
        t17*t18*t23*t41-5.333333333333333*t17*t18*t22*t26*t34+0.444444444444444*
        t18*t23*t26*t32+t26*t23*t5*t31+2.666666666666667*t16*t17*t23*
        t26+t37*t23*t5*t25+2.666666666666667*t17*t22*t23*t25;
    res[7] = -1.0*t5*t9*(-47.525028228*t13*t15*t29/pow(rhoa,
        11.66666666666667)+158.849988*t13*t3*t39*t15+5.333333333333333*
        t12*t13*t15-96.536*t13*t11*t10*t15-0.024533333333333*t12+6.4E-5*
        t10*t11)-1.333333333333333*t17*t43*t9+6.0*t18*t22*t44*t49*
        t5-2.0*t18*t22*t34*t45*t5-2.0*t16*t34*t44*t5-4.0*t18*t26*t34*
        t41*t5+2.0*t23*t25*t41*t5+2.0*t23*t26*t40*t5+t18*t23*(-0.1104*
        t3*t50*t39-8.533333333333334E-5*t1*t10*t11*t2-0.1472*t20*t12+
        0.2208*t11*t35*t10)*t5-4.0*t22*t25*t26*t34*t5+1.333333333333333*
        t17*t18*t23*t45-2.666666666666667*t17*t18*t34*t44+t22*t23*
        t5*t43+2.666666666666667*t17*t23*t25*t26+t45*t23*t5*t16;
    res[8] = -1.0*t5*t9*(35.643771171*t13*t15*t38/pow(rhoa,
        10.66666666666667)-2.4E-5*t4*grada-97.47612899999999*t13*t24*
        t42*t15+39.492*t13*grada*t4*t15)+t18*t23*t5*(3.2E-5*t1*t2*
        t4*grada+0.0828*t24*t50*t42-0.1104*grada*t35*t4)+6.0*t18*pow(t26,
        3.0)*t49*t5-6.0*t18*t26*t34*t45*t5+3.0*t23*t25*t45*t5-6.0*
        t25*t34*t44*t5+3.0*t23*t26*t43*t5;

}

static void
mpw_third(FunThirdFuncDrv *ds, real factor, const FunDensProp* dp)
{
    real res[9];
 
    mpw_third_helper(dp->rhoa, dp->grada, res);

    ds->df1000 += factor*res[0];
    ds->df0010 += factor*res[1];

    ds->df2000 += factor*res[2];
    ds->df1010 += factor*res[3];
    ds->df0020 += factor*res[4];

    ds->df3000 += factor*res[5];
    ds->df2010 += factor*res[6];
    ds->df1020 += factor*res[7];
    ds->df0030 += factor*res[8];


    if(fabs(dp->rhoa-dp->rhob)>1e-13 ||
       fabs(dp->grada-dp->gradb)>1e-13)
        mpw_third_helper(dp->rhob, dp->gradb, res);

    ds->df0100 += factor*res[0];
    ds->df0001 += factor*res[1];

    ds->df0200 += factor*res[2];
    ds->df0101 += factor*res[3];
    ds->df0002 += factor*res[4];

    ds->df0300 += factor*res[5];
    ds->df0201 += factor*res[6];
    ds->df0102 += factor*res[7];
    ds->df0003 += factor*res[8];

}

static void
mpw_fourth_helper(real rhoa, real grada, real *res)
{
    real t1, t2, t3, t4, t5, t6, t7, t8, t9, t10;
    real t11, t12, t13, t14, t15, t16, t17, t18;
    real t19, t20, t21, t22, t23, t24, t25, t26;
    real t27, t28, t29, t30, t31, t32, t33, t34;
    real t35, t36, t37, t38, t39, t40, t41, t42;
    real t43, t44, t45, t46, t47, t48, t49, t50;
    real t51, t52, t53, t54, t55, t56, t57, t58;
    real t59, t60, t61, t62, t63, t64, t65, t66;
    real t67, t68, t69, t70, t71, t72, t73, t74;

    t1 = 1/pow(6.0,0.333333333333333);
    t2 = pow(3.141592653589793,0.333333333333333);
    t3 = pow(grada,4.0);
    t4 = 1/pow(rhoa,5.333333333333333);
    t5 = pow(rhoa,1.333333333333333);
    t6 = 1/t5;
    t7 = asinh(grada*t6);
    t8 = 0.0276*grada*t7*t6+1.3333333333333334E-6*t1*t2*t3*
        t4+1.0;
    t9 = 1/t8;
    t10 = 1/pow(rhoa,6.333333333333333);
    t11 = pow(grada,2.0);
    t12 = 1/pow(rhoa,3.666666666666667);
    t13 = 0.0046-0.138888888888889/(pow(3.141592653589793,
        1.666666666666667)*pow(36.0,0.666666666666667));
    t14 = 1/pow(rhoa,2.666666666666667);
    t15 = 1/pow(2.718281828459045,1.6455*t11*t14);
    t16 = 5.333333333333334E-6*t10*t3+2.666666666666667*t11*
        t12*t13*t15-4.388*t13*t3*t10*t15-0.012266666666667*t11*t12;
    t17 = pow(rhoa,
        0.333333333333333);
    t18 = -1.0E-6*t3*t4-1.0*t11*t13*t14*t15+0.0046*t11*t14;
    t19 = sqrt(t11*
        t14+1.0);
    t20 = 1/t19;
    t21 = 1/pow(rhoa,2.333333333333333);
    t22 = -7.111111111111111E-6*t1*t10*t2*t3-0.0368*grada*
        t7*t21-0.0368*t11*t20*t12;
    t23 = 1/pow(t8,2.0);
    t24 = pow(grada,3.0);
    t25 = -2.0*t13*t14*t15*grada-4.0E-6*t24*t4+3.291*t13*
        t24*t4*t15+0.0092*grada*t14;
    t26 = 0.0276*t7*t6+5.333333333333334E-6*t1*t2*t24*t4+
        0.0276*grada*t20*t14;
    t27 = 1/pow(rhoa,7.333333333333333);
    t28 = 1/pow(rhoa,4.666666666666667);
    t29 = pow(grada,6.0);
    t30 = 1/pow(rhoa,10.0);
    t31 = -3.377777777777778E-5*t27*t3-9.777777777777779*
        t11*t13*t15*t28+0.044977777777778*t11*t28-19.254544*t13*t29*
        t30*t15+39.492*t13*t3*t27*t15;
    t32 = 1/pow(rhoa,0.666666666666667);
    t33 = pow(t22,2.0);
    t34 = 1/pow(t8,3.0);
    t35 = 1/pow(t19,3.0);
    t36 = 1/pow(rhoa,3.333333333333333);
    t37 = 0.085866666666667*grada*t7*t36+4.503703703703703E-5*
        t1*t2*t27*t3+0.184*t11*t20*t28-0.049066666666667*t3*t35*t27;
    t38 = pow(grada,
        5.0);
    t39 = 1/pow(rhoa,9.0);
    t40 = 5.333333333333333*t12*t13*t15*grada+2.1333333333333335E-5*
        t10*t24+14.440908*t13*t38*t39*t15-26.328*t13*t24*t10*t15-0.024533333333333*
        grada*t12;
    t41 = -2.8444444444444444E-5*t1*t10*t2*t24-0.0368*t7*
        t21-0.1104*grada*t20*t12+0.0368*t24*t35*t10;
    t42 = 1/pow(rhoa,8.0);
    t43 = -1.2E-5*t11*t4-10.830681*t13*t3*t42*t15+16.455*
        t13*t11*t4*t15-2.0*t13*t14*t15+0.0092*t14;
    t44 = pow(t26,2.0);
    t45 = -0.0276*t11*t35*t4+1.6E-5*t1*t11*t2*t4+0.0552*t20*
        t14;
    t46 = 1/pow(rhoa,8.333333333333334);
    t47 = 1/pow(rhoa,5.666666666666667);
    t48 = pow(grada,8.0);
    t49 = 1/pow(rhoa,13.66666666666667);
    t50 = 1/pow(rhoa,11.0);
    t51 = 45.62962962962963*t11*t13*t15*t47-0.209896296296296*
        t11*t47+2.477037037037037E-4*t3*t46+365.836336*t13*t29*t50*
        t15-84.488939072*t13*t48*t49*t15-332.5128888888888*t13*t3*
        t46*t15;
    t52 = 1/pow(rhoa,1.666666666666667);
    t53 = pow(t22,3.0);
    t54 = 1/pow(t8,4.0);
    t55 = 1/pow(t19,5.0);
    t56 = 1/pow(rhoa,4.333333333333333);
    t57 = -0.286222222222222*grada*t7*t56-0.196266666666667*
        t29*t55*t50-0.973155555555556*t11*t20*t47+0.605155555555555*
        t3*t35*t46-3.302716049382716E-4*t1*t2*t3*t46;
    t58 = pow(grada,7.0);
    t59 = 1/pow(rhoa,12.66666666666667);
    t60 = -19.55555555555556*t13*t15*t28*grada+0.089955555555556*
        grada*t28-1.351111111111111E-4*t24*t27+63.366704304*t13*t58*
        t59*t15-245.495436*t13*t38*t30*t15+190.1466666666666*t13*t24*
        t27*t15;
    t61 = 0.085866666666667*t7*t36+0.1472*t38*t55*t30+0.453866666666667*
        grada*t20*t28-0.380266666666667*t24*t35*t27+1.8014814814814814E-4*
        t1*t2*t24*t27;
    t62 = 1/pow(rhoa,11.66666666666667);
    t63 = -47.525028228*t13*t29*t62*t15+158.849988*t13*t3*
        t39*t15+5.333333333333333*t12*t13*t15-96.536*t13*t11*t10*t15-
        0.024533333333333*t12+6.4E-5*t10*t11;
    t64 = -0.1104*t3*t55*t39-8.533333333333334E-5*t1*t10*
        t11*t2-0.1472*t20*t12+0.2208*t11*t35*t10;
    t65 = 1/pow(rhoa,10.66666666666667);
    t66 = -2.4E-5*t4*grada+35.643771171*t13*t38*t65*t15-97.47612899999999*
        t13*t24*t42*t15+39.492*t13*grada*t4*t15;
    t67 = pow(t26,3.0);
    t68 = 3.2E-5*t1*t2*t4*grada+0.0828*t24*t55*t42-0.1104*
        grada*t35*t4;
    t69 = 1/pow(rhoa,9.333333333333334);
    t70 = 1/pow(rhoa,6.666666666666667);
    t71 = 1/pow(rhoa,14.66666666666667);
    t72 = 1/pow(rhoa,12.0);
    t73 = 1/pow(t8,5.0);
    t74 = 1/pow(t19,7.0);

   /* code */
    res[0] = -1.0*t16*t5*t9-1.333333333333333*t17*t18*t9+
        t22*t23*t5*t18;
    res[1] = t26*t23*t5*t18-1.0*t25*t5*t9;
    res[2] = -1.0*t31*t5*t9-0.444444444444444*t18*t32*t9-
        2.666666666666667*t16*t17*t9-2.0*t18*t33*t34*t5+2.0*t16*t22*
        t23*t5+2.666666666666667*t17*t18*t22*t23+t37*t23*t5*t18;
    res[3] = -1.0*t40*t5*t9-1.333333333333333*t17*t25*t9-
        2.0*t18*t22*t26*t34*t5+1.333333333333333*t17*t18*t23*t26+t22*
        t23*t5*t25+t41*t23*t5*t18+t26*t23*t5*t16;
    res[4] = -1.0*t43*t5*t9-2.0*t18*t34*t44*t5+2.0*t23*t25*
        t26*t5+t45*t23*t5*t18;
    res[5] = 0.296296296296296*t18*t52*t9-1.0*t5*t51*t9-1.333333333333333*
        t16*t32*t9-4.0*t17*t31*t9+6.0*t18*t5*t53*t54-6.0*t18*t22*t34*
        t37*t5+3.0*t16*t23*t37*t5-6.0*t16*t33*t34*t5+3.0*t22*t23*t31*
        t5+4.0*t17*t18*t23*t37-8.0*t17*t18*t33*t34+1.333333333333333*
        t18*t22*t23*t32+8.0*t16*t17*t22*t23+t57*t23*t5*t18;
    res[6] = -1.0*t5*t60*t9-2.666666666666667*t17*t40*t9-
        0.444444444444444*t25*t32*t9+6.0*t18*t26*t33*t5*t54-4.0*t18*
        t22*t34*t41*t5+2.0*t16*t23*t41*t5+2.0*t22*t23*t40*t5-2.0*t18*
        t26*t34*t37*t5-2.0*t25*t33*t34*t5-4.0*t16*t22*t26*t34*t5+2.666666666666667*
        t17*t18*t23*t41-5.333333333333333*t17*t18*t22*t26*t34+0.444444444444444*
        t18*t23*t26*t32+t26*t23*t5*t31+2.666666666666667*t16*t17*t23*
        t26+t37*t23*t5*t25+2.666666666666667*t17*t22*t23*t25+t61*t23*
        t5*t18;
    res[7] = -1.0*t5*t63*t9-1.333333333333333*t17*t43*t9+
        6.0*t18*t22*t44*t5*t54-2.0*t18*t22*t34*t45*t5-2.0*t16*t34*
        t44*t5-4.0*t18*t26*t34*t41*t5+2.0*t23*t25*t41*t5+2.0*t23*t26*
        t40*t5-4.0*t22*t25*t26*t34*t5+1.333333333333333*t17*t18*t23*
        t45-2.666666666666667*t17*t18*t34*t44+t22*t23*t5*t43+2.666666666666667*
        t17*t23*t25*t26+t64*t23*t5*t18+t45*t23*t5*t16;
    res[8] = -1.0*t5*t66*t9+6.0*t18*t5*t54*t67-6.0*t18*t26*
        t34*t45*t5+3.0*t23*t25*t45*t5-6.0*t25*t34*t44*t5+3.0*t23*t26*
        t43*t5+t68*t23*t5*t18;
    res[9] = -1.0*t5*t9*(-370.737464647936*t13*t15*pow(grada,
        10.0)/pow(rhoa,17.33333333333333)-258.5679012345679*t11*t13*
        t15*t70+1.189412345679012*t11*t70-0.002064197530864*t3*t69-
        5483.266252444444*t13*t29*t72*t15+2759.972009685333*t13*t48*
        t71*t15+2971.163555555555*t13*t3*t69*t15)+1.185185185185185*
        t16*t52*t9-5.333333333333333*t17*t51*t9-2.666666666666667*
        t31*t32*t9-0.493827160493827*t14*t18*t9-24.0*t18*pow(t22,4.0)*
        t5*t73+t18*t23*t5*(4.579555555555554*t29*t55*t72-1.308444444444444*
        t48*t74*t71+5.896177777777778*t11*t20*t70-6.340503703703702*
        t3*t35*t69+0.002752263374486*t1*t2*t3*t69+1.240296296296296*
        grada*t7*t4)-8.0*t18*t22*t34*t5*t57+4.0*t16*t23*t5*t57+5.333333333333333*
        t17*t18*t23*t57+24.0*t16*t5*t53*t54+32.0*t17*t18*t53*t54+36.0*
        t18*t33*t37*t5*t54-1.185185185185185*t18*t22*t23*t52+4.0*t22*
        t23*t5*t51-6.0*t18*t34*pow(t37,2.0)*t5-24.0*t16*t22*t34*t37*
        t5+6.0*t23*t31*t37*t5-12.0*t31*t33*t34*t5-32.0*t17*t18*t22*
        t34*t37+2.666666666666667*t18*t23*t32*t37+16.0*t16*t17*t23*
        t37-5.333333333333333*t18*t32*t33*t34-32.0*t16*t17*t33*t34+
        5.333333333333333*t16*t22*t23*t32+16.0*t17*t22*t23*t31;
    res[10] = -1.0*t5*t9*(278.053098485952*t13*t15*pow(grada,
        9.0)/pow(rhoa,16.33333333333333)+91.25925925925925*t13*t15*
        t47*grada-0.419792592592593*grada*t47+9.908148148148148E-4*
        t24*t46+3289.317933333333*t13*t38*t50*t15-1879.878894352*t13*
        t58*t49*t15-1480.218666666666*t13*t24*t46*t15)-4.0*t17*t60*
        t9+0.296296296296296*t25*t52*t9-1.333333333333333*t32*t40*
        t9-24.0*t18*t26*t5*t53*t73-6.0*t18*t22*t34*t5*t61+3.0*t16*
        t23*t5*t61+4.0*t17*t18*t23*t61+3.0*t22*t23*t5*t60-2.0*t18*
        t26*t34*t5*t57+t18*t23*t5*(-0.286222222222222*t7*t56-2.993066666666667*
        t38*t55*t50+0.981333333333333*t58*t74*t49-2.232533333333333*
        grada*t20*t47+3.393777777777777*t24*t35*t46-0.001321086419753*
        t1*t2*t24*t46)+6.0*t25*t5*t53*t54+18.0*t18*t33*t41*t5*t54+
        18.0*t18*t22*t26*t37*t5*t54+18.0*t16*t26*t33*t5*t54+24.0*t17*
        t18*t26*t33*t54-0.296296296296296*t18*t23*t26*t52+t26*t23*
        t5*t51-6.0*t18*t34*t37*t41*t5-12.0*t16*t22*t34*t41*t5+3.0*
        t23*t31*t41*t5+3.0*t23*t37*t40*t5-6.0*t33*t34*t40*t5-6.0*t16*
        t26*t34*t37*t5-6.0*t22*t25*t34*t37*t5-6.0*t22*t26*t31*t34*
        t5-16.0*t17*t18*t22*t34*t41+1.333333333333333*t18*t23*t32*
        t41+8.0*t16*t17*t23*t41+8.0*t17*t22*t23*t40-8.0*t17*t18*t26*
        t34*t37+4.0*t17*t23*t25*t37-8.0*t17*t25*t33*t34-2.666666666666667*
        t18*t22*t26*t32*t34-16.0*t16*t17*t22*t26*t34+1.333333333333333*
        t16*t23*t26*t32+1.333333333333333*t22*t23*t25*t32+4.0*t17*
        t23*t26*t31+t57*t23*t5*t25;
    res[11] = -1.0*t5*t9*(-208.539823864464*t13*t15*t48/pow(rhoa,
        15.33333333333333)-19.55555555555556*t13*t15*t28+0.089955555555556*
        t28-4.053333333333333E-4*t11*t27+1251.492410004*t13*t29*t59*
        t15-1853.24986*t13*t3*t30*t15+634.7973333333333*t13*t11*t27*
        t15)-2.666666666666667*t17*t63*t9-0.444444444444444*t32*t43*
        t9-24.0*t18*t33*t44*t5*t73-4.0*t18*t22*t34*t5*t64+2.0*t16*
        t23*t5*t64+2.666666666666667*t17*t18*t23*t64+2.0*t22*t23*t5*
        t63-4.0*t18*t26*t34*t5*t61+2.0*t23*t25*t5*t61+2.0*t23*t26*
        t5*t60+t18*t23*t5*(-0.736*t29*t74*t59+1.8768*t3*t55*t30+0.539733333333333*
        t20*t28-1.594666666666667*t11*t35*t27+5.404444444444444E-4*
        t1*t11*t2*t27)+6.0*t18*t33*t45*t5*t54+6.0*t18*t37*t44*t5*t54+
        12.0*t16*t22*t44*t5*t54+24.0*t18*t22*t26*t41*t5*t54+12.0*t25*
        t26*t33*t5*t54+16.0*t17*t18*t22*t44*t54-2.0*t18*t34*t37*t45*
        t5-4.0*t16*t22*t34*t45*t5-2.0*t31*t34*t44*t5-2.0*t33*t34*t43*
        t5-4.0*t18*t34*pow(t41,2.0)*t5+4.0*t23*t40*t41*t5-8.0*t16*
        t26*t34*t41*t5-8.0*t22*t25*t34*t41*t5-8.0*t22*t26*t34*t40*
        t5-4.0*t25*t26*t34*t37*t5-5.333333333333333*t17*t18*t22*t34*
        t45+0.444444444444444*t18*t23*t32*t45+2.666666666666667*t16*
        t17*t23*t45-0.888888888888889*t18*t32*t34*t44-5.333333333333333*
        t16*t17*t34*t44+t37*t23*t5*t43+2.666666666666667*t17*t22*t23*
        t43-10.66666666666667*t17*t18*t26*t34*t41+5.333333333333333*
        t17*t23*t25*t41+5.333333333333333*t17*t23*t26*t40-10.66666666666667*
        t17*t22*t25*t26*t34+0.888888888888889*t23*t25*t26*t32+t45*
        t23*t5*t31;
    res[12] = -1.0*t5*t9*(156.404867898348*t13*t15*t58/pow(rhoa,
        14.33333333333333)+1.28E-4*t10*grada-807.9254798759999*t13*
        t38*t62*t15+953.099928*t13*t24*t39*t15-210.624*t13*grada*t10*
        t15)+t18*t23*t5*(-1.7066666666666668E-4*t1*t10*t2*grada+0.552*
        t38*t74*t62-1.104*t24*t55*t39+0.5888*grada*t35*t10)-1.333333333333333*
        t17*t66*t9-24.0*t18*t22*t5*t67*t73-2.0*t18*t22*t34*t5*t68+
        1.333333333333333*t17*t18*t23*t68+6.0*t16*t5*t54*t67+8.0*t17*
        t18*t54*t67+t22*t23*t5*t66-6.0*t18*t26*t34*t5*t64+3.0*t23*
        t25*t5*t64+3.0*t23*t26*t5*t63+18.0*t18*t22*t26*t45*t5*t54+
        18.0*t18*t41*t44*t5*t54+18.0*t22*t25*t44*t5*t54-6.0*t18*t34*
        t41*t45*t5+3.0*t23*t40*t45*t5-6.0*t16*t26*t34*t45*t5-6.0*t22*
        t25*t34*t45*t5-6.0*t34*t40*t44*t5+3.0*t23*t41*t43*t5-6.0*t22*
        t26*t34*t43*t5-12.0*t25*t26*t34*t41*t5-8.0*t17*t18*t26*t34*
        t45+4.0*t17*t23*t25*t45-8.0*t17*t25*t34*t44+4.0*t17*t23*t26*
        t43+t68*t23*t5*t16;
    res[13] = -1.0*t5*t9*(-117.303650923761*t13*t15*t29/pow(rhoa,
        13.33333333333333)-2.4E-5*t4+499.0127963939999*t13*t3*t65*
        t15-422.3965589999999*t13*t11*t42*t15+39.492*t13*t4*t15)-24.0*
        t18*pow(t26,4.0)*t5*t73-8.0*t18*t26*t34*t5*t68+4.0*t23*t25*
        t5*t68+24.0*t25*t5*t54*t67+4.0*t23*t26*t5*t66+t18*t23*t5*(-
        0.414*t3*t74*t65+0.5796*t11*t55*t42-0.1104*t35*t4+3.2E-5*t1*
        t2*t4)+36.0*t18*t44*t45*t5*t54-6.0*t18*t34*pow(t45,2.0)*t5+
        6.0*t23*t43*t45*t5-24.0*t25*t26*t34*t45*t5-12.0*t34*t43*t44*
        t5;

}

static void
mpw_fourth(FunFourthFuncDrv *ds, real factor, const FunDensProp* dp)
{
    real res[14];
 
    mpw_fourth_helper(dp->rhoa, dp->grada, res);

    ds->df1000 += factor*res[0];
    ds->df0010 += factor*res[1];

    ds->df2000 += factor*res[2];
    ds->df1010 += factor*res[3];
    ds->df0020 += factor*res[4];

    ds->df3000 += factor*res[5];
    ds->df2010 += factor*res[6];
    ds->df1020 += factor*res[7];
    ds->df0030 += factor*res[8];

    ds->df4000 += factor*res[9];
    ds->df3010 += factor*res[10];
    ds->df2020 += factor*res[11];
    ds->df1030 += factor*res[12];
    ds->df0040 += factor*res[13];


    if(fabs(dp->rhoa-dp->rhob)>1e-13 ||
       fabs(dp->grada-dp->gradb)>1e-13)
        mpw_fourth_helper(dp->rhob, dp->gradb, res);

    ds->df0100 += factor*res[0];
    ds->df0001 += factor*res[1];

    ds->df0200 += factor*res[2];
    ds->df0101 += factor*res[3];
    ds->df0002 += factor*res[4];

    ds->df0300 += factor*res[5];
    ds->df0201 += factor*res[6];
    ds->df0102 += factor*res[7];
    ds->df0003 += factor*res[8];

    ds->df0400 += factor*res[9];
    ds->df0301 += factor*res[10];
    ds->df0202 += factor*res[11];
    ds->df0103 += factor*res[12];
    ds->df0004 += factor*res[13];

}
