/*
C...   Copyright (c) 2005 by the authors of Dalton (see below).
C...   All Rights Reserved.
C...
C...   The source code in this file is part of
C...   "Dalton, a molecular electronic structure program, Release 2.0
C...   (2005), written by C. Angeli, K. L. Bak,  V. Bakken,
C...   O. Christiansen, R. Cimiraglia, S. Coriani, P. Dahle,
C...   E. K. Dalskov, T. Enevoldsen, B. Fernandez, C. Haettig,
C...   K. Hald, A. Halkier, H. Heiberg, T. Helgaker, H. Hettema,
C...   H. J. Aa. Jensen, D. Jonsson, P. Joergensen, S. Kirpekar,
C...   W. Klopper, R.Kobayashi, H. Koch, O. B. Lutnaes, K. V. Mikkelsen,
C...   P. Norman, J.Olsen, M. J. Packer, T. B. Pedersen, Z. Rinkevicius,
C...   T. A. Ruden, K. Ruud, P. Salek, A. Sanchez de Meras, T. Saue,
C...   S. P. A. Sauer, B. Schimmelpfennig, K. O. Sylvester-Hvid,
C...   P. R. Taylor, O. Vahtras, D. J. Wilson, H. Agren.
C...   This source code is provided under a written licence and may be
C...   used, copied, transmitted, or stored only in accord with that
C...   written licence.
C...
C...   In particular, no part of the source code or compiled modules may
C...   be distributed outside the research group of the licence holder.
C...   This means also that persons (e.g. post-docs) leaving the research
C...   group of the licence holder may not take any part of Dalton,
C...   including modified files, with him/her, unless that person has
C...   obtained his/her own licence.
C...
C...   For questions concerning this copyright write to:
C...      dalton-admin@kjemi.uio.no
C...
C...   For information on how to get a licence see:
C...      http://www.kjemi.uio.no/software/dalton/dalton.html
C
*/
/*-*-mode: C; c-indentation-style: "bsd"; c-basic-offset: 4; -*-*/
/* fun-dk87x.c:

   Automatically generated code implementing DK87X functional and
   its derivatives. It is generated by func-codegen.pl being a part of
   a "Automatic code generation framework for analytical functional
   derivative evaluation", Pawel Salek, 2005

    This functional is connected by making following changes:
    1. add "extern Functional dk87xFunctional;" to 'functionals.h'
    2. add "&dk87xFunctional," to 'functionals.c'
    3. add "fun-dk87x.c" to 'Makefile.am', 'Makefile.in' or 'Makefile'.

    This functional has been generated from following input:
    ------ cut here -------
rho:  rhoa + rhob;
grad: sqrt(grada*grada + gradb*gradb + 2*gradab);
zeta: (rhoa-rhob)/(rhoa+rhob);

Cx:   -3/4*(6/%PI)^(1/3);
Bg:   0.00132327;
a1:   0.861213;
b1:   0.042076;
c:    0.98;

xa:  grada/(rhoa^(4/3));
xb:  gradb/(rhob^(4/3));

t1a: Bg*xa^2;
t1b: Bg*xb^2;

Exa: -rhoa^(4/3)*(Cx + t1a*(1+a1*xa^c)/(1+b1*xa^2));
Exb: -rhob^(4/3)*(Cx + t1b*(1+a1*xb^c)/(1+b1*xb^2));

K(rhoa,rhob,grada,gradb,gradab):=(Exa+Exb);


    ------ cut here -------
*/

 
/* strictly conform to XOPEN ANSI C standard */
#if !defined(SYS_DEC)
/* XOPEN compliance is missing on old Tru64 4.0E Alphas and pow() prototype
 * is not specified. */
#define _XOPEN_SOURCE          500
#define _XOPEN_SOURCE_EXTENDED 1
#endif
#include <math.h>
#include <stddef.h>
 
#define __CVERSION__
 
#include "functionals.h"
 
/* INTERFACE PART */
static int dk87x_isgga(void) { return 1; } /* FIXME: detect! */
static int dk87x_read(const char *conf_line);
static real dk87x_energy(const FunDensProp* dp);
static void dk87x_first(FunFirstFuncDrv *ds,   real factor,
                         const FunDensProp* dp);
static void dk87x_second(FunSecondFuncDrv *ds, real factor,
                          const FunDensProp* dp);
static void dk87x_third(FunThirdFuncDrv *ds,   real factor,
                         const FunDensProp* dp);
static void dk87x_fourth(FunFourthFuncDrv *ds,   real factor,
                          const FunDensProp* dp);
 
Functional DK87xFunctional = {
  "DK87x",       /* name */
  dk87x_isgga,   /* gga-corrected */
  dk87x_read,
  NULL,
  dk87x_energy,
  dk87x_first,
  dk87x_second,
  dk87x_third,
  dk87x_fourth
};
 
/* IMPLEMENTATION PART */
static int
dk87x_read(const char *conf_line)
{
    fun_set_hf_weight(0);
    return 1;
}

static real
dk87x_energy(const FunDensProp *dp)
{
    real res;
    real rhoa = dp->rhoa, rhob = dp->rhob;
    real grada = dp->grada, gradb = dp->gradb, gradab = dp->gradab;

    real t1, t2, t3, t4, t5, t6, t7;

    t1 = -0.75*pow(6.0,0.333333333333333)/pow(3.141592653589793,
        0.333333333333333);
    t2 = pow(grada,2.0);
    t3 = pow(rhoa,1.333333333333333);
    t4 = 1/pow(rhoa,2.666666666666667);
    t5 = pow(gradb,2.0);
    t6 = pow(rhob,1.333333333333333);
    t7 = 1/pow(rhob,2.666666666666667);

   /* code */
    res = -1.0*t6*(0.00132327*t5*t7*(0.861213*pow(gradb/t6,
        0.98)+1.0)/(0.042076*t5*t7+1.0)+t1)-1.0*t3*(0.00132327*t2*
        t4*(0.861213*pow(grada/t3,0.98)+1.0)/(0.042076*t2*t4+1.0)+
        t1);

    return res;
}

static void
dk87x_first_helper(real rhoa, real grada, real *res)
{    real t1, t2, t3, t4, t5, t6, t7, t8, t9;

    t1 = pow(grada,2.0);
    t2 = pow(rhoa,1.333333333333333);
    t3 = grada/t2;
    t4 = 0.861213*pow(t3,0.98)+1.0;
    t5 = 1/pow(rhoa,2.666666666666667);
    t6 = 0.042076*t1*t5+1.0;
    t7 = 1/t6;
    t8 = 1/pow(t6,2.0);
    t9 = pow(grada,3.0);

   /* code */
    res[0] = -1.0*t2*(1.4847442272E-4*t4*t8*pow(grada,4.0)/
        pow(rhoa,6.333333333333333)-0.001489099973306*t7*t9/(pow(t3,
        0.02)*pow(rhoa,5.0))-0.00352872*t1*t4*t7/pow(rhoa,3.666666666666667))-
        1.333333333333333*(0.00132327*t1*t4*t7*t5-0.75*pow(6.0,0.333333333333333)/
        pow(3.141592653589793,0.333333333333333))*pow(rhoa,0.333333333333333);
    res[1] = -1.0*t2*(0.00111682497998*t7*pow(grada,1.98)*
        pow(abs(rhoa),0.026666666666667)/pow(rhoa,4.0)-1.1135581704000001E-4*
        t4*t8*t9/pow(rhoa,5.333333333333333)+0.00264654*grada*t4*t7*
        t5);
}

static void
dk87x_first(FunFirstFuncDrv *ds, real factor, const FunDensProp *dp)
{
    real res[2];

    dk87x_first_helper(dp->rhoa, dp->grada, res);
   /* Final assignment */
    ds->df1000 += factor*res[0];
    ds->df0010 += factor*res[1];


    if(fabs(dp->rhoa-dp->rhob)>1e-13 ||
       fabs(dp->grada-dp->gradb)>1e-13)
        dk87x_first_helper(dp->rhob, dp->gradb, res);
    ds->df0100 += factor*res[0];
    ds->df0001 += factor*res[1];

}

static void
dk87x_second_helper(real rhoa, real grada, real *res)
{
    real t1, t2, t3, t4, t5, t6, t7, t8, t9, t10;
    real t11, t12, t13, t14, t15, t16, t17, t18;
    real t19, t20, t21, t22, t23, t24, t25;

    t1 = pow(grada,2.0);
    t2 = pow(rhoa,1.333333333333333);
    t3 = grada/t2;
    t4 = 0.861213*pow(t3,0.98)+1.0;
    t5 = 1/pow(rhoa,2.666666666666667);
    t6 = 0.042076*t1*t5+1.0;
    t7 = 1/t6;
    t8 = 0.00132327*t1*t4*t7*t5-0.75*pow(6.0,0.333333333333333)/
        pow(3.141592653589793,0.333333333333333);
    t9 = pow(rhoa,0.333333333333333);
    t10 = pow(grada,4.0);
    t11 = 1/pow(t6,2.0);
    t12 = 1/pow(rhoa,6.333333333333333);
    t13 = 1.4847442272E-4*t10*t4*t11*t12;
    t14 = pow(grada,3.0);
    t15 = 1/pow(rhoa,5.0);
    t16 = 1/pow(rhoa,3.666666666666667);
    t17 = -0.00352872*t1*t4*t7*t16;
    t18 = 1/pow(rhoa,5.333333333333333);
    t19 = pow(grada,1.98);
    t20 = 1/pow(rhoa,4.0);
    t21 = abs(rhoa);
    t22 = pow(t21,0.026666666666667);
    t23 = 0.00111682497998*t19*t7*t20*t22+0.00264654*grada*
        t4*t7*t5-1.1135581704000001E-4*t14*t4*t11*t18;
    t24 = 1/pow(t6,3.0);
    t25 = pow(grada,2.98);

   /* code */
    res[0] = -1.333333333333333*t8*t9-1.0*t2*(-0.001489099973306*
        t14*t15*t7/pow(t3,0.02)+t17+t13);
    res[1] = -1.0*t2*t23;
    res[2] = -1.0*t2*(3.331845232195585E-5*t24*t4*pow(grada,
        6.0)/pow(rhoa,10.0)-3.341619758764805E-4*t11*t22*pow(grada,
        4.98)/pow(rhoa,8.666666666666666)-0.00133626980448*t10*t11*
        t4/pow(rhoa,7.333333333333333)+0.011416433128682*t22*t25*t7/
        pow(rhoa,6.0)+0.01293864*t1*t4*t7/pow(rhoa,4.666666666666667)-
        3.970933262150404E-5*t20*t25*t7/pow(t21,1.973333333333333))-
        0.444444444444444*t8/pow(rhoa,0.666666666666667)-2.666666666666667*
        (-0.001489099973306*t25*t7*t15*t22+t17+t13)*t9;
    res[3] = -1.0*t2*(-2.4988839241466884E-5*t24*t4*pow(grada,
        5.0)/pow(rhoa,9.0)+2.506214819073604E-4*t11*t22*pow(grada,
        3.98)/pow(rhoa,7.666666666666667)-0.007415717867066*t19*t7*
        t15*t22-0.00705744*grada*t4*t7*t16+8.908465363200001E-4*t14*
        t4*t11*t12)-1.333333333333333*t23*t9;
    res[4] = -1.0*t2*(1.8741629431100162E-5*t10*t24*t4/pow(rhoa,
        8.0)-1.8796611143052027E-4*t11*t22*t25/pow(rhoa,6.666666666666667)+
        0.00444496342032*t20*t22*t7*pow(grada,0.98)+0.00264654*t4*
        t7*t5-5.567790852E-4*t1*t4*t11*t18);

}

static void
dk87x_second(FunSecondFuncDrv *ds, real factor, const FunDensProp* dp)
{
    real res[5];
 
    dk87x_second_helper(dp->rhoa, dp->grada, res);

    ds->df1000 += factor*res[0];
    ds->df0010 += factor*res[1];

    ds->df2000 += factor*res[2];
    ds->df1010 += factor*res[3];
    ds->df0020 += factor*res[4];


    if(fabs(dp->rhoa-dp->rhob)>1e-13 ||
       fabs(dp->grada-dp->gradb)>1e-13)
        dk87x_second_helper(dp->rhob, dp->gradb, res);
    ds->df0100 += factor*res[0];
    ds->df0001 += factor*res[1];

    ds->df0200 += factor*res[2];
    ds->df0101 += factor*res[3];
    ds->df0002 += factor*res[4];

}

static void
dk87x_third_helper(real rhoa, real grada, real *res)
{
    real t1, t2, t3, t4, t5, t6, t7, t8, t9, t10;
    real t11, t12, t13, t14, t15, t16, t17, t18;
    real t19, t20, t21, t22, t23, t24, t25, t26;
    real t27, t28, t29, t30, t31, t32, t33, t34;
    real t35, t36, t37, t38, t39, t40, t41, t42;
    real t43, t44, t45, t46;

    t1 = pow(grada,2.0);
    t2 = pow(rhoa,1.333333333333333);
    t3 = grada/t2;
    t4 = 0.861213*pow(t3,0.98)+1.0;
    t5 = 1/pow(rhoa,2.666666666666667);
    t6 = 0.042076*t1*t5+1.0;
    t7 = 1/t6;
    t8 = 0.00132327*t1*t4*t7*t5-0.75*pow(6.0,0.333333333333333)/
        pow(3.141592653589793,0.333333333333333);
    t9 = pow(rhoa,0.333333333333333);
    t10 = pow(grada,4.0);
    t11 = 1/pow(t6,2.0);
    t12 = 1/pow(rhoa,6.333333333333333);
    t13 = 1.4847442272E-4*t10*t4*t11*t12;
    t14 = pow(grada,3.0);
    t15 = 1/pow(rhoa,5.0);
    t16 = 1/pow(rhoa,3.666666666666667);
    t17 = -0.00352872*t1*t4*t7*t16;
    t18 = 1/pow(rhoa,5.333333333333333);
    t19 = pow(grada,1.98);
    t20 = 1/pow(rhoa,4.0);
    t21 = abs(rhoa);
    t22 = pow(t21,0.026666666666667);
    t23 = 0.00111682497998*t19*t7*t20*t22+0.00264654*grada*
        t4*t7*t5-1.1135581704000001E-4*t14*t4*t11*t18;
    t24 = 1/pow(rhoa,0.666666666666667);
    t25 = pow(grada,6.0);
    t26 = 1/pow(t6,3.0);
    t27 = 1/pow(rhoa,10.0);
    t28 = 1/pow(rhoa,7.333333333333333);
    t29 = 1/pow(rhoa,4.666666666666667);
    t30 = pow(grada,2.98);
    t31 = 1/pow(t21,1.973333333333333);
    t32 = pow(grada,4.98);
    t33 = 1/pow(rhoa,8.666666666666666);
    t34 = 1/pow(rhoa,6.0);
    t35 = 0.011416433128682*t30*t7*t34*t22-3.341619758764805E-4*
        t32*t11*t33*t22-3.970933262150404E-5*t30*t7*t20*t31+0.01293864*
        t1*t4*t7*t29-0.00133626980448*t10*t4*t11*t28+3.331845232195585E-5*
        t25*t4*t26*t27;
    t36 = -0.001489099973306*t30*t7*t15*t22+t17+t13;
    t37 = pow(grada,5.0);
    t38 = 1/pow(rhoa,9.0);
    t39 = pow(grada,3.98);
    t40 = 1/pow(rhoa,7.666666666666667);
    t41 = -0.007415717867066*t19*t7*t15*t22+2.506214819073604E-4*
        t39*t11*t40*t22-0.00705744*grada*t4*t7*t16+8.908465363200001E-4*
        t14*t4*t11*t12-2.4988839241466884E-5*t37*t4*t26*t38;
    t42 = 1/pow(rhoa,8.0);
    t43 = 1/pow(rhoa,6.666666666666667);
    t44 = pow(grada,0.98);
    t45 = 0.00444496342032*t44*t7*t20*t22-1.8796611143052027E-4*
        t30*t11*t43*t22+0.00264654*t4*t7*t5-5.567790852E-4*t1*t4*t11*
        t18+1.8741629431100162E-5*t10*t4*t26*t42;
    t46 = 1/pow(t6,4.0);

   /* code */
    res[0] = -1.333333333333333*t8*t9-1.0*t2*(-0.001489099973306*
        t14*t15*t7/pow(t3,0.02)+t17+t13);
    res[1] = -1.0*t2*t23;
    res[2] = -2.666666666666667*t36*t9-0.444444444444444*
        t24*t8-1.0*t2*t35;
    res[3] = -1.333333333333333*t23*t9-1.0*t2*t41;
    res[4] = -1.0*t2*t45;
    res[5] = -1.0*t2*(1.1215257599188915E-5*t4*t46*pow(grada,
        8.0)/pow(rhoa,13.66666666666667)-1.1248159437583037E-4*t22*
        t26*pow(grada,6.98)/pow(rhoa,12.33333333333333)-6.330505941171611E-4*
        t25*t26*t4/pow(rhoa,11.0)+0.0056807535899*t11*t22*t32/pow(rhoa,
        9.666666666666666)+0.01125106181056*t10*t11*t4/pow(rhoa,8.333333333333334)-
        0.083058687399979*t22*t30*t7/pow(rhoa,7.0)-0.06038032*t1*t4*
        t7/pow(rhoa,5.666666666666667)+7.835974970643463E-5*t30*t7/
        (pow(t21,3.973333333333333)*pow(rhoa,3.0))-1.3366479035059231E-5*
        t32*t11*t40*t31+4.632755472508804E-4*t30*t7*t15*t31)+0.296296296296296*
        t8/pow(rhoa,1.666666666666667)-4.0*t35*t9-1.333333333333333*
        t24*t36;
    res[6] = -1.0*t2*(-8.411443199391686E-6*t4*t46*pow(grada,
        7.0)/pow(rhoa,12.66666666666667)+8.436119578187277E-5*t22*
        t26*pow(grada,5.98)/pow(rhoa,11.33333333333333)-0.001664126639865*
        t11*t22*t33*pow(grada,3.98)+3.341619758764808E-6*t39*t11*t43*
        t31-1.1833381121208204E-4*t19*t7*t20*t31+0.02587728*grada*
        t4*t7*t29-0.0064338916512*t14*t4*t11*t28+4.24810267104937E-4*
        t37*t4*t26*t27+0.044941037194387*t19*t7*t34*t22-0.002088512349228*
        t39*t11*t33*t22)-2.666666666666667*t41*t9-0.444444444444444*
        t23*t24;
    res[7] = -1.0*t2*(6.308582399543764E-6*t25*t4*t46/pow(rhoa,
        11.66666666666667)-6.327089683640457E-5*t22*t26*t32/pow(rhoa,
        10.33333333333333)-2.748772316561357E-4*t10*t4*t26*t38+0.002373385433663*
        t30*t11*t40*t22-0.020639521270016*t44*t7*t15*t22-0.00705744*
        t4*t7*t16+0.00326643729984*t1*t4*t11*t12)-1.333333333333333*
        t45*t9;
    res[8] = -1.0*t2*(-4.731436799657823E-6*t37*t4*t46/pow(rhoa,
        10.66666666666667)+4.745317262730343E-5*t22*t26*t39/pow(rhoa,
        9.333333333333334)+0.006589714111873*t20*t22*t7/pow(grada,
        0.02)+1.6867466487990147E-4*t14*t4*t26*t42-0.001404106852386*
        t19*t11*t43*t22-0.00133626980448*grada*t4*t11*t18);

}

static void
dk87x_third(FunThirdFuncDrv *ds, real factor, const FunDensProp* dp)
{
    real res[9];
 
    dk87x_third_helper(dp->rhoa, dp->grada, res);

    ds->df1000 += factor*res[0];
    ds->df0010 += factor*res[1];

    ds->df2000 += factor*res[2];
    ds->df1010 += factor*res[3];
    ds->df0020 += factor*res[4];

    ds->df3000 += factor*res[5];
    ds->df2010 += factor*res[6];
    ds->df1020 += factor*res[7];
    ds->df0030 += factor*res[8];


    if(fabs(dp->rhoa-dp->rhob)>1e-13 ||
       fabs(dp->grada-dp->gradb)>1e-13)
        dk87x_third_helper(dp->rhob, dp->gradb, res);

    ds->df0100 += factor*res[0];
    ds->df0001 += factor*res[1];

    ds->df0200 += factor*res[2];
    ds->df0101 += factor*res[3];
    ds->df0002 += factor*res[4];

    ds->df0300 += factor*res[5];
    ds->df0201 += factor*res[6];
    ds->df0102 += factor*res[7];
    ds->df0003 += factor*res[8];

}

static void
dk87x_fourth_helper(real rhoa, real grada, real *res)
{
    real t1, t2, t3, t4, t5, t6, t7, t8, t9, t10;
    real t11, t12, t13, t14, t15, t16, t17, t18;
    real t19, t20, t21, t22, t23, t24, t25, t26;
    real t27, t28, t29, t30, t31, t32, t33, t34;
    real t35, t36, t37, t38, t39, t40, t41, t42;
    real t43, t44, t45, t46, t47, t48, t49, t50;
    real t51, t52, t53, t54, t55, t56, t57, t58;
    real t59, t60, t61, t62, t63, t64, t65, t66;
    real t67, t68, t69, t70, t71, t72, t73, t74;
    real t75;

    t1 = pow(grada,2.0);
    t2 = pow(rhoa,1.333333333333333);
    t3 = grada/t2;
    t4 = 0.861213*pow(t3,0.98)+1.0;
    t5 = 1/pow(rhoa,2.666666666666667);
    t6 = 0.042076*t1*t5+1.0;
    t7 = 1/t6;
    t8 = 0.00132327*t1*t4*t7*t5-0.75*pow(6.0,0.333333333333333)/
        pow(3.141592653589793,0.333333333333333);
    t9 = pow(rhoa,0.333333333333333);
    t10 = pow(grada,4.0);
    t11 = 1/pow(t6,2.0);
    t12 = 1/pow(rhoa,6.333333333333333);
    t13 = 1.4847442272E-4*t10*t4*t11*t12;
    t14 = pow(grada,3.0);
    t15 = 1/pow(rhoa,5.0);
    t16 = 1/pow(rhoa,3.666666666666667);
    t17 = -0.00352872*t1*t4*t7*t16;
    t18 = 1/pow(rhoa,5.333333333333333);
    t19 = pow(grada,1.98);
    t20 = 1/pow(rhoa,4.0);
    t21 = abs(rhoa);
    t22 = pow(t21,0.026666666666667);
    t23 = 0.00111682497998*t19*t7*t20*t22+0.00264654*grada*
        t4*t7*t5-1.1135581704000001E-4*t14*t4*t11*t18;
    t24 = 1/pow(rhoa,0.666666666666667);
    t25 = pow(grada,6.0);
    t26 = 1/pow(t6,3.0);
    t27 = 1/pow(rhoa,10.0);
    t28 = 1/pow(rhoa,7.333333333333333);
    t29 = 1/pow(rhoa,4.666666666666667);
    t30 = pow(grada,2.98);
    t31 = 1/pow(t21,1.973333333333333);
    t32 = pow(grada,4.98);
    t33 = 1/pow(rhoa,8.666666666666666);
    t34 = 1/pow(rhoa,6.0);
    t35 = 0.011416433128682*t30*t7*t34*t22-3.341619758764805E-4*
        t32*t11*t33*t22-3.970933262150404E-5*t30*t7*t20*t31+0.01293864*
        t1*t4*t7*t29-0.00133626980448*t10*t4*t11*t28+3.331845232195585E-5*
        t25*t4*t26*t27;
    t36 = -0.001489099973306*t30*t7*t15*t22+t17+t13;
    t37 = pow(grada,5.0);
    t38 = 1/pow(rhoa,9.0);
    t39 = pow(grada,3.98);
    t40 = 1/pow(rhoa,7.666666666666667);
    t41 = -0.007415717867066*t19*t7*t15*t22+2.506214819073604E-4*
        t39*t11*t40*t22-0.00705744*grada*t4*t7*t16+8.908465363200001E-4*
        t14*t4*t11*t12-2.4988839241466884E-5*t37*t4*t26*t38;
    t42 = 1/pow(rhoa,8.0);
    t43 = 1/pow(rhoa,6.666666666666667);
    t44 = pow(grada,0.98);
    t45 = 0.00444496342032*t44*t7*t20*t22-1.8796611143052027E-4*
        t30*t11*t43*t22+0.00264654*t4*t7*t5-5.567790852E-4*t1*t4*t11*
        t18+1.8741629431100162E-5*t10*t4*t26*t42;
    t46 = 1/pow(rhoa,1.666666666666667);
    t47 = pow(grada,8.0);
    t48 = 1/pow(t6,4.0);
    t49 = 1/pow(rhoa,13.66666666666667);
    t50 = 1/pow(rhoa,11.0);
    t51 = 1/pow(rhoa,8.333333333333334);
    t52 = 1/pow(rhoa,5.666666666666667);
    t53 = 1/pow(rhoa,3.0);
    t54 = 1/pow(t21,3.973333333333333);
    t55 = pow(grada,6.98);
    t56 = 1/pow(rhoa,12.33333333333333);
    t57 = 1/pow(rhoa,9.666666666666666);
    t58 = 1/pow(rhoa,7.0);
    t59 = -0.083058687399979*t30*t7*t58*t22+0.0056807535899*
        t32*t11*t57*t22-1.1248159437583037E-4*t55*t26*t56*t22+4.632755472508804E-4*
        t30*t7*t15*t31-1.3366479035059231E-5*t32*t11*t40*t31+7.835974970643463E-5*
        t30*t7*t53*t54-0.06038032*t1*t4*t7*t52+0.01125106181056*t10*
        t4*t11*t51-6.330505941171611E-4*t25*t4*t26*t50+1.1215257599188915E-5*
        t47*t4*t48*t49;
    t60 = pow(grada,7.0);
    t61 = 1/pow(rhoa,12.66666666666667);
    t62 = pow(grada,5.98);
    t63 = 1/pow(rhoa,11.33333333333333);
    t64 = pow(grada,3.98);
    t65 = 0.044941037194387*t19*t7*t34*t22-0.001664126639865*
        t64*t11*t33*t22-0.002088512349228*t39*t11*t33*t22+8.436119578187277E-5*
        t62*t26*t63*t22-1.1833381121208204E-4*t19*t7*t20*t31+3.341619758764808E-6*
        t39*t11*t43*t31+0.02587728*grada*t4*t7*t29-0.0064338916512*
        t14*t4*t11*t28+4.24810267104937E-4*t37*t4*t26*t27-8.411443199391686E-6*
        t60*t4*t48*t61;
    t66 = 1/pow(rhoa,11.66666666666667);
    t67 = 1/pow(rhoa,10.33333333333333);
    t68 = -0.020639521270016*t44*t7*t15*t22+0.002373385433663*
        t30*t11*t40*t22-6.327089683640457E-5*t32*t26*t67*t22-0.00705744*
        t4*t7*t16+0.00326643729984*t1*t4*t11*t12-2.748772316561357E-4*
        t10*t4*t26*t38+6.308582399543764E-6*t25*t4*t48*t66;
    t69 = 1/pow(rhoa,10.66666666666667);
    t70 = 1/pow(rhoa,9.333333333333334);
    t71 = 1/pow(grada,0.02);
    t72 = 0.006589714111873*t71*t7*t20*t22-0.001404106852386*
        t19*t11*t43*t22+4.745317262730343E-5*t39*t26*t70*t22-0.00133626980448*
        grada*t4*t11*t18+1.6867466487990147E-4*t14*t4*t26*t42-4.731436799657823E-6*
        t37*t4*t48*t69;
    t73 = 1/pow(t6,5.0);
    t74 = 1/pow(rhoa,12.0);
    t75 = 1/pow(rhoa,13.33333333333333);

   /* code */
    res[0] = -1.333333333333333*t8*t9-1.0*t2*(-0.001489099973306*
        t14*t15*t7/pow(t3,0.02)+t17+t13);
    res[1] = -1.0*t2*t23;
    res[2] = -2.666666666666667*t36*t9-0.444444444444444*
        t24*t8-1.0*t2*t35;
    res[3] = -1.333333333333333*t23*t9-1.0*t2*t41;
    res[4] = -1.0*t2*t45;
    res[5] = -4.0*t35*t9+0.296296296296296*t46*t8-1.0*t2*
        t59-1.333333333333333*t24*t36;
    res[6] = -2.666666666666667*t41*t9-1.0*t2*t65-0.444444444444444*
        t23*t24;
    res[7] = -1.333333333333333*t45*t9-1.0*t2*t68;
    res[8] = -1.0*t2*t72;
    res[9] = -1.0*t2*(5.033527239930376E-6*t4*t73*pow(grada,
        10.0)/pow(rhoa,17.33333333333333)-5.048293935954602E-5*t22*
        t48*pow(grada,8.98)/pow(rhoa,16.0)-3.663650815735045E-4*t4*
        t47*t48/pow(rhoa,14.66666666666667)-3.113494055002336E-4*t30*
        t7/(pow(t21,5.973333333333333)*pow(rhoa,2.0))+0.009488354811241*
        t25*t4*t26*t74-0.10053368133952*t10*t4*t11*t70+3.516869150557807E-5*
        t32*t11*t43*t54-0.001149276329028*t30*t7*t20*t54+0.342155146666667*
        t1*t4*t7*t43-5.999018366710958E-6*t55*t26*t63*t31-0.004531276066921*
        t30*t7*t34*t31+3.059438534691335E-4*t32*t11*t33*t31+0.003374447831275*
        t55*t26*t75*t22-0.076894383560021*t32*t11*t69*t22+0.649357892063317*
        t30*t7*t42*t22)-5.333333333333333*t59*t9-0.493827160493827*
        t5*t8+1.185185185185185*t36*t46-2.666666666666667*t24*t35;
    res[10] = -1.0*t2*(-3.775145429947782E-6*t4*t73*pow(grada,
        9.0)/pow(rhoa,16.33333333333333)+3.786220451965951E-5*t22*
        t48*pow(grada,7.98)/pow(rhoa,15.0)+2.335120541251752E-4*t19*
        t7*t53*t54-6.594129657295887E-6*t39*t11*t52*t54-0.12076064*
        grada*t4*t7*t52+0.05008537193088*t14*t4*t11*t51-0.005691902271667*
        t37*t4*t26*t50+2.495394815819534E-4*t60*t4*t48*t49+2.249631887516609E-6*
        t62*t26*t67*t31-6.656506559459498E-5*t64*t11*t40*t31-3.898556385225609E-5*
        t39*t11*t40*t31+0.001380561130808*t19*t7*t15*t31-0.298475198649535*
        t19*t7*t58*t22+0.028290152877703*t64*t11*t57*t22+0.01648532414324*
        t39*t11*t57*t22-0.002275502654223*t62*t26*t56*t22)-4.0*t65*
        t9+0.296296296296296*t23*t46-1.333333333333333*t24*t41;
    res[11] = -1.0*t2*(2.831359072460837E-6*t4*t47*t73/pow(rhoa,
        15.33333333333333)-2.839665338974463E-5*t22*t48*t55/pow(rhoa,
        14.0)-0.006623224026662*t11*t22*t33*pow(grada,2.98)-1.661260031879858E-4*
        t25*t4*t48*t61-5.624079718791522E-7*t32*t26*t70*t31+2.3257673521003063E-5*
        t30*t11*t43*t31-2.3430094619992243E-4*t44*t7*t20*t31+0.02587728*
        t4*t7*t29-0.02147929982016*t1*t4*t11*t28+0.003206901035988*
        t10*t4*t26*t27+0.001494599185269*t32*t26*t63*t22+0.110823386586714*
        t44*t7*t34*t22-0.017524289419902*t30*t11*t33*t22)-2.666666666666667*
        t68*t9-0.444444444444444*t24*t45;
    res[12] = -1.0*t2*(-2.123519304345627E-6*t4*t60*t73/pow(rhoa,
        14.33333333333333)+2.1297490042308472E-5*t22*t48*t62/pow(rhoa,
        13.0)+1.0724590079224397E-4*t37*t4*t48*t66-0.001649263389937*
        t14*t4*t26*t38-3.150890662452948E-4*t64*t26*t67*t22-6.314435504273176E-4*
        t39*t26*t67*t22+0.01156638188721*t19*t11*t40*t22-0.026183130737841*
        t71*t7*t15*t22+0.00712677229056*grada*t4*t11*t12)-1.333333333333333*
        t72*t9;
    res[13] = -1.0*t2*(-1.3179428223745638E-4*t20*t22*t7/
        pow(grada,1.02)+1.5926394782592205E-6*t25*t4*t73*t75-6.624011519520952E-5*
        t10*t4*t48*t69+7.309235478129063E-4*t1*t4*t26*t42-1.5973117531731354E-5*
        t32*t48*t74*t22+5.675399446225491E-4*t30*t26*t70*t22-0.00446246585825*
        t44*t11*t43*t22-0.00133626980448*t4*t11*t18);

}

static void
dk87x_fourth(FunFourthFuncDrv *ds, real factor, const FunDensProp* dp)
{
    real res[14];
 
    dk87x_fourth_helper(dp->rhoa, dp->grada, res);

    ds->df1000 += factor*res[0];
    ds->df0010 += factor*res[1];

    ds->df2000 += factor*res[2];
    ds->df1010 += factor*res[3];
    ds->df0020 += factor*res[4];

    ds->df3000 += factor*res[5];
    ds->df2010 += factor*res[6];
    ds->df1020 += factor*res[7];
    ds->df0030 += factor*res[8];

    ds->df4000 += factor*res[9];
    ds->df3010 += factor*res[10];
    ds->df2020 += factor*res[11];
    ds->df1030 += factor*res[12];
    ds->df0040 += factor*res[13];


    if(fabs(dp->rhoa-dp->rhob)>1e-13 ||
       fabs(dp->grada-dp->gradb)>1e-13)
        dk87x_fourth_helper(dp->rhob, dp->gradb, res);

    ds->df0100 += factor*res[0];
    ds->df0001 += factor*res[1];

    ds->df0200 += factor*res[2];
    ds->df0101 += factor*res[3];
    ds->df0002 += factor*res[4];

    ds->df0300 += factor*res[5];
    ds->df0201 += factor*res[6];
    ds->df0102 += factor*res[7];
    ds->df0003 += factor*res[8];

    ds->df0400 += factor*res[9];
    ds->df0301 += factor*res[10];
    ds->df0202 += factor*res[11];
    ds->df0103 += factor*res[12];
    ds->df0004 += factor*res[13];

}
