#!/usr/bin/env python
#    spin_local
#    ----------
#    Molecule:         H2O
#    Wave Function:    DFT/B3LYP (6-31G)
#    Test Purpose:     Analysis of spin-spin coupling constants
#                      in terms of localized occupied orbitals
#                      using Foster-Boys localization

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(string = 'Final DFT energy',
      rel_tolerance = 1.0e-8)

f.add(string = 'Nuclear spin-spin coupling constants',
      rel_tolerance = 1.0e-2)

f.add(string = 'Localized orbitals are used in the analysis',
      rel_tolerance = 1.0e-2)

f.add(string = 'Spin-spin couplings printed for atoms with abundance greater than',
      rel_tolerance = 1.0e-2)

f.add(string = 'Orbital analysis of spin-spin couplings',
      rel_tolerance = 1.0e-2)

f.add(string = 'Only contributions from pairs of occupied',
      rel_tolerance = 1.0e-2)

f.add(string = 'FOSOCC: Foster Boys localization of all occupied orbitals',
      rel_tolerance = 1.0e-2)

f.add(from_string = 'FOSTER-BOYS LOCALIZATION:',
      num_lines = 38,
      ignore_sign = True,
      rel_tolerance = 1.0e-2)

f.add(from_string = 'Singlet electronic excitation energies',
      num_lines = 119,
      abs_tolerance = 1.0e-3)

f.add(from_string = 'Triplet electronic excitation energies',
      num_lines = 119,
      abs_tolerance = 1.0e-3)

f.add(from_string = 'DSO part of spin-spin coupling constant',
      to_string = 'TOTAL',
      abs_tolerance = 1.0e-3)

f.add(from_string = 'PSO part of spin-spin coupling constant',
      to_string = 'TOTAL',
      abs_tolerance = 1.0e-3)

f.add(from_string = 'FC part of spin-spin coupling constant',
      to_string = 'TOTAL',
      abs_tolerance = 1.0e-3)

f.add(from_string = 'SD(+FC) part of spin-spin coupling constant',
      to_string = 'TOTAL',
      abs_tolerance = 1.0e-3)

f.add(from_string = 'Total spin-spin coupling constant',
      to_string = 'TOTAL',
      abs_tolerance = 1.0e-3)

f.add(from_string = 'Indirect spin-spin coupling between ',
      num_lines = 17,
      abs_tolerance = 1.0e-3)

#test.run(['spin_local.dal'], ['H2O_6-31G.mol'], f={'out': f})
test.run(['spin_local.dal'], ['CH2O_6-31G.mol'], f={'out': f})

sys.exit(test.return_code)
