#!/bin/bash

# these env variables are machine dependent, adapt to your needs
export PATH=$HOME/openmpi/intel/bin:$PATH
export LD_LIBRARY_PATH=$HOME/openmpi/intel/lib:$LD_LIBRARY_PATH

BRANCH='master'
NUM_CORES=4

while getopts b:p:n: opt; do
  case $opt in
  b)
      BRANCH=$OPTARG
      ;;
  n)
      NUM_CORES=$OPTARG
      ;;
  esac
done

shift $((OPTIND - 1))

export DALTON_NUM_MPI_PROCS=$NUM_CORES

BUILDNAME="$BRANCH-$(basename $0)"

CTEST_TEMP_DIR=/tmp/cdash-scratch
mkdir -p $CTEST_TEMP_DIR

export DALTON_TMPDIR=$CTEST_TEMP_DIR/run

git clone git@repo.ctcc.no:dalton $CTEST_TEMP_DIR/compile

cd $CTEST_TEMP_DIR/compile
git checkout $BRANCH &> /dev/null
./setup --mpi --mkl=sequential -D BUILDNAME=$BUILDNAME
cd build
make -j$NUM_CORES dalton.x
ctest -D Nightly -L dalton

rm -rf $CTEST_TEMP_DIR

exit 0
