#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from runtest_lsdalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final HF energy',
      rel_tolerance = 1.0e-8)
f.add(string = 'Nuclear repulsion',
      rel_tolerance = 1.0e-8)
#f.add(string = 'Max. sigma',
#      rel_tolerance = 1.0e-2, 
#      mask = [1])
#f.add(string = 'Min. sigma',
#      rel_tolerance = 1.0e-2,
#      mask = [1])

f.add(string = 'Allocated memory (TOTAL)')
f.add(string = 'Allocated MPI memory a cross all slaves')

test.run(['LSDALTON_FMM_SCALAPACK.dal'], ['water2.mol'], {'out': f})

sys.exit(test.return_code)

