#!/usr/bin/env python
#    dft_open_lr
#    ---------------
#    Molecule:         H2O+
#    Wave Functions:   open-shell DFT B3LYP / aug-cc-pVDZ
#    Test Purpose:     open-shell DFT B3LYP polarizability test w/symmetry.

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final DFT energy',
      rel_tolerance = 1.0e-8)

f.add(re = '[XYZ]DIPLEN  \; [XYZ]DIPLEN',
      rel_tolerance = 1.0e-9)

test.run(['dft_open_lr.dal'], ['H2Op_aug-cc-pVDZ.mol'], f={'out': f})

sys.exit(test.return_code)
