#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from runtest_lsdalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

test.run(['unrestricted.dal'], ['HeH.mol'], {'out': f},accepted_errors=['Unrestricted calculations require the use of XCFUN'])

sys.exit(test.return_code)

