#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Hartree-Fock total energy',
      rel_tolerance = 1.0e-7)
f.add(string = 'MP2 second order energy',
      rel_tolerance = 1.0e-7)
f.add(string = 'Final MC-SRDFT energy',
      rel_tolerance = 1.0e-7)
f.add(string = 'DIPLEN  >>',
      rel_tolerance = 1.0e-4)

test.run(['rsp_srpbe_polar.dal'], ['lih.mol'], f={'out': f})

sys.exit(test.return_code)
