      PARAMETER ( MAXNES = MAXLBL )
      LOGICAL ESROPS,ESROPT,ESRCAL
      CHARACTER*8 LBESRS,LBESRT
      COMMON /INFESR/ THCESR, IPRESR, MAXESR, NESRS(8) ,NESRT(8),
     *                ESROPS(MAXNES), ESROPT(MAXNES), ESRCAL
      COMMON /CHRESR/  LBESRS(8,MAXNES), LBESRT(8,MAXNES)
