#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final HF-SRDFT energy:',
      rel_tolerance = 1.0e-7)
f.add(string = '@ Excitation energy :',
      rel_tolerance = 1.0e-3)

test.run(['triplet.dal'], ['lih.mol'], f={'out': f})

sys.exit(test.return_code)
