amfi.o : amfi.F \
  ../include/Regge.h  ../include/alphac.h \
  ../include/datapow.h  ../include/dofuc.h \
  ../include/dummy.h  ../include/implicit.h \
  ../include/ired.h  ../include/para.h \
  ../include/param.h  ../include/pi.h \
  ../include/priunit.h
symtra.o : symtra.F \
  ../include/dummy.h  ../include/implicit.h \
  ../include/para.h  ../include/priunit.h
