#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from runtest_lsdalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final HF energy',
      rel_tolerance = 1.0e-8)

f.add(string = 'Correlation energy',
      rel_tolerance = 1.0e-3)

f.add(string = 'Total RIMP2 energy',
      rel_tolerance = 1.0e-3)

f.add(from_string = 'RI-MP2 occupied single energies',
      to_string   = 'RI-MP2 Lagrangian correlation energy',
      abs_tolerance = 1.0e-3)

f.add(string = 'Allocated memory (TOTAL)')

f.add(string = 'Memory in use for array4',
      rel_tolerance = 1.0e-9)

test.run(['decrimp2.dal'], ['CO2H2.mol'], {'out': f})

sys.exit(test.return_code)
