#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > decccsd_Bind.info <<'%EOF%'
   DEC-CCSD interaction energy using fragment calculations without long-range t1
   -----------------------------------------------------------------
   Molecule:         3 BH molecules with stretched bonds
   Wave Function:    CCSD / STO-3G
   Test Purpose:     Test Interaction energy within DEC framework
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > decccsd_Bind.mol <<'%EOF%'
BASIS                                                   
STO-3G
Two Subsystems - One with 2 BH molecule and one with 1 BH

Atomtypes=4 Nosymmetry Angstrom SubSystems
Charge=5.0 Atoms=2 SubSystem=BH12
B          0.000000      0.0000000    0.0000000
B          3.000000      0.0000000    1.4500000
Charge=5.0 Atoms=1 SubSystem=BH3
B          6.000000      0.0000000    0.0000000
Charge=1.0 Atoms=2 SubSystem=BH12
H          0.000000      1.4500000    0.0000000
H          3.000000      0.0000000    0.0000000
Charge=1.0 Atoms=1 SubSystem=BH3
H          6.000000      0.0000000    1.4500000
%EOF%
#######################################################################
#  DALTON INPUT
#######################################################################
cat > decccsd_Bind.dal <<'%EOF%'
**WAVE FUNCTIONS
.HF
*DENSOPT
.ARH
.START
TRILEVEL
.LCM
**LOCALIZE ORBITALS
.No Level2 Localization
.PFM
2 2
**DEC
.BOUGHTONPULAY
.FRAGEXPMODEL
.MP2
.FRAGREDMODEL
.MP2
.CCSD
.INTERACTIONENERGY
.FOT
8
.MEMORY
2.0
*END OF INPUT  
%EOF%
#######################################################################

 

#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >decccsd_Bind.check
cat >>decccsd_Bind.check <<'%EOF%'

log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# HF ENERGY 
CRIT1=`$GREP "Final HF energy: * \-74\.19004" $log | wc -l`
TEST[1]=`expr   $CRIT1`
CTRL[1]=2
ERROR[1]="HF ENERGY NOT CORRECT -"

# CCSD INTERACTION ENERGY
CRIT1=`$GREP "Interaction Correlation energy  : * \-0\.000443" $log | wc -l`
TEST[2]=`expr   $CRIT1`
CTRL[2]=1
ERROR[2]="DEC CCSD Interaction correlation energy is not correct"

# CCSD INTERACTION ENERGY CHECK
CRIT1=`$GREP "Estimated DEC error : *  0\.000020" $log | wc -l`
TEST[3]=`expr   $CRIT1`
CTRL[3]=1
ERROR[3]="DEC CCSD concistency check not correct"

# Memory test for total memory                                             
CRIT1=`$GREP "Allocated memory \(TOTAL\): * 0 byte" $log | wc -l`         
TEST[4]=`expr  $CRIT1`                                                    
CTRL[4]=1                                                                 
ERROR[4]="Memory leak -"

# Memory test for array4                                                  
CRIT1=`$GREP "Memory in use for array4 * \: * 0.000 * GB" $log | wc -l`   
TEST[5]=`expr  $CRIT1`                                                    
CTRL[5]=1                                                                 
ERROR[5]="Memory leak for array4 -" 

PASSED=1
for i in 1 2 3 4 5
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo ${ERROR[i]}
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%




