#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > decmp2f12.info <<'%EOF%'
   MP2-F12 energy for full molecule
   --------------------------------
   Molecule:         H2O
   Wave Function:    MP2-F12 / 6-31G
   Test Purpose:     Test DEC MP2-F12 energy using toy code (Yang W)
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > decmp2f12.mol <<'%EOF%'
BASIS
6-31G Aux=cc-pVDZ CABS=aug-cc-pVDZ
%cc-pVDZ, cc-pVTZ

Atomtypes=2 Charge=0 Nosymmetry Angstrom
Charge=8.0 Atoms=1
O    0.0000     0.0000  0.1173
Charge=1.0 Atoms=2
H    0.0000     0.7572  -0.4692
H    0.0000     -0.7572 -0.4692
%EOF%
#######################################################################
#  DALTON INPUT
#######################################################################
cat > decmp2f12.dal <<'%EOF%'
**WAVE FUNCTIONS
.HF
*DENSOPT
.ARH
.START
ATOMS
.CONVTHR
1.0d-5
**GENERAL
.NOGCBASIS
**DEC
.SimulateFull
.MP2
.F12debug
.MEMORY
2
*END OF INPUT
%EOF%
#######################################################################

 

#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >decmp2f12.check
cat >>decmp2f12.check <<'%EOF%'

log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# HF ENERGY 
CRIT1=`$GREP "Final HF energy: * \-75.983974" $log | wc -l`
TEST[1]=`expr   $CRIT1`
CTRL[1]=1
ERROR[1]="HF ENERGY NOT CORRECT -"

# STANDARD MP2 CORRELATION ENERGY
CRIT1=`$GREP "MP2 CORRECTION TO ENERGY : * \-0.12885[0-1]" $log | wc -l`
TEST[2]=`expr   $CRIT1`
CTRL[2]=1
ERROR[2]="MP2 correlation energy is not correct"

# F12 CONTRIBUTION TO CORRELATION ENERGY
CRIT1=`$GREP "F12 CORRECTION TO ENERGY : * \-0.323156" $log | wc -l`
TEST[3]=`expr   $CRIT1`
CTRL[3]=1
ERROR[3]="F12 correction energy is not correct"

# MP2-F12 CORRELATION ENERGY
CRIT1=`$GREP "MP2-F12 CORRELATION ENERGY : *\-0.452007" $log | wc -l`
TEST[4]=`expr   $CRIT1`
CTRL[4]=1
ERROR[4]="MP2-F12 corrected correlation energy is not correct"

# TOTAL MP2-F12 CORRELATION ENERGY
CRIT1=`$GREP "E: Total MP2-F12 energy: *\-76.435981" $log | wc -l`
TEST[4]=`expr   $CRIT1`
CTRL[4]=1
ERROR[4]="MP2-F12 corrected correlation energy is not correct"

# Memory test for total memory                                             
CRIT1=`$GREP "Allocated memory \(TOTAL\): * 0 byte" $log | wc -l`         
TEST[5]=`expr  $CRIT1`                                                    
CTRL[5]=1                                                                 
ERROR[5]="Memory leak -"
                                                                          
PASSED=1
for i in 1 2 3 4 5
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo ${ERROR[i]}
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%




