#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from runtest_lsdalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Hartree-Fock energy',
      rel_tolerance = 1.0e-8)

f.add(string = 'Correlation energy',
      rel_tolerance = 1.0e-5)

f.add(from_string = 'CC excitation energies',
      num_lines   = 6,
      rel_tolerance = 1.0e-5)

f.add(string = 'Allocated memory (TOTAL)')

test.run(['peom_mbpt2_exci.dal'], ['H2.mol'], {'out': f})

sys.exit(test.return_code)
