#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(string = 'B-freq =',
      abs_tolerance = 1.0e-3)

test.run(['pehf_beta.dal'], ['pehf_beta.mol'], ['pehf_beta.pot'], f={'out': f})

sys.exit(test.return_code)
