#!/usr/bin/env python
#    dft_lda_nosym
#    -------------
#    Molecule:         HCN
#    Wave Function:    DFT LDA / aug-cc-pVDZ
#    Test Purpose:     Check DFT/LDA w/o symmetry

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final DFT energy',
      rel_tolerance = 1.0e-8)

test.run(['dft_lda_nosym.dal'], ['HCN_aug-cc-pVDZ.mol'], f={'out': f})

sys.exit(test.return_code)
