set(DEC_C_SOURCES
    deccc/crayio.c
    )
set(DFTFUNC_SOURCES
    dft/fun-example.c
    dft/fun-b97-1.c
    dft/fun-becke.c
    dft/fun-cam-b3lyp.c
    dft/fun-gga.c
    dft/fun-hcth120.c
    dft/fun-hcth147.c
    dft/fun-hcth407.c
    dft/fun-hcth93.c
    dft/fun-kt.c
    dft/fun-lb94.c
    dft/fun-lyp.c
    dft/fun-optx.c
    dft/fun-p86c.c
    dft/fun-pbec.c
    dft/fun-pbex.c
    dft/fun-pw86x.c
    dft/fun-pw91c.c
    dft/fun-pz81.c
    dft/fun-slater.c
    dft/fun-vwn.c
    dft/functionals.c
    dft/general.c
    )
set(DFTFUNC_F_SOURCES
    dft/II_util.f90
    )
set(FMM_C_SOURCES
    mm/mm_proc_selector.c
    )
set(LSDALTONMAIN_FORTRAN_SOURCES
    lsdaltonsrc/numerical_derivatives.f90
    lsdaltonsrc/LSDALTON.f90
    lsdaltonsrc/LS_optimizer.f90
    lsdaltonsrc/LSdynamics.f90
    lsdaltonsrc/Energy_and_deriv.f90
    lsdaltonsrc/lsmpiSlave.f90
    lsdaltonsrc/init_lsdalton.f90
    lsdaltonsrc/plt_driver.f90
    lsdaltonsrc/configuration.f90
    lsdaltonsrc/LSlib.f90
    lsdaltonsrc/Profile.f90
    )
set(DDYNAM_SOURCES
    ddynam/LSinput.f90
    ddynam/Fock_mat_dyn.f90
    ddynam/Modules.f90
    ddynam/Temperature.f90
    ddynam/TimeRev_prop.f90
    ddynam/dyn_utilities.f90
    )
set(DEC_SOURCES
    deccc/array4_memory.f90
    deccc/array3_memory.f90
    deccc/ccarray3_simple.f90
    deccc/CABS.f90
    deccc/mp2.f90
    deccc/ccsdpt.f90
    deccc/cc_crop.f90
    deccc/ccsd.f90
    deccc/rpa.f90
    deccc/f12_integrals.f90
    deccc/cc_driver.f90
    deccc/cc_integrals.f90
    deccc/ccarray2_simple.f90
    deccc/ccarray4_simple.f90
    deccc/ccorbital.f90
    deccc/ccri_simple.f90
    deccc/dec_atom.f90
    deccc/dec_driver.f90
    deccc/dec_driver_slave.f90
    deccc/dec_main.f90
    deccc/dec_settings.f90
    deccc/dec_utils.f90
    deccc/full_driver_f12contractions.f90
    deccc/fullmolecule.f90
    deccc/mp2_gradient.f90
    deccc/fragment_energy.f90
    deccc/full_driver.f90
    deccc/decmpi.f90
    deccc/decmpiSlave.f90
    )	
set(GEOOPT_SOURCES
    geomopt/LSopt-input.f90
    geomopt/ls_opt.f90
    geomopt/ls_opt2.f90
    geomopt/ls_redint.f90
    )
set(LINEARS_SOURCES	
    linears/configurationType.f90
    linears/ChargeLoc.f90
    linears/SCFLOOP.f90
    linears/trustradius.f90
    linears/LSDALTON_RESPONSE.f90
    linears/LSDALTON_RESPONSE_type.f90
    linears/arh_debug.f90
    linears/arh_driver.f90
    linears/average_util.f90
    linears/davidson_settings.f90
    linears/davidson_solver.f90
    linears/debug.f90
    linears/dens_subspace.f90
    linears/densopt.f90
    linears/diag.f90
    linears/diis.f90
    linears/dsm.f90
    linears/dsm_xterm.f90
    linears/ecdata_module.f90
    linears/extra-output.f90
    linears/fock-eval.f90
    linears/kurtosis.f90
    linears/leastchange.f90
    linears/levelshift.f90
    linears/minimize.f90
    linears/optimlocNONMOD.f90
    linears/localization_util.f90
    linears/localization_orbspread.f90
    linears/localization_charge.f90
    linears/print_MO.f90
    linears/prop_contribs.f90
    linears/response_driver.f90
    linears/response_prop.f90
    linears/rsp_equations.f90
    linears/scfopt-typedef.f90
    linears/soeo-redspace.f90
    linears/soeo-loop.f90
    linears/soeo-debug.f90
    linears/soeo-matop.f90
    linears/soeo-typedef.f90
    linears/soeo-util.f90
    linears/starting_guess.f90
    linears/statistics.f90
    linears/trilevel.f90
    )

set(RSPSOLVER_SOURCES	
    responsesolver/rsp_cmplx_sym.f90
    responsesolver/rsp_complex.f90
    responsesolver/rsp_solver.f90
    responsesolver/rsp_std_sym.f90
    )

set(SOLVERUTIL_SOURCES	
    SolverUtilities/arh_density.f90
    SolverUtilities/dalton_interface.f90
    SolverUtilities/dd_utilities.f90
    SolverUtilities/dd_utilities_unres.f90
    SolverUtilities/decomp.f90
    SolverUtilities/lsdalton_modules.f90
    SolverUtilities/queue-operations.f90
    SolverUtilities/queue-typedef.f90
    SolverUtilities/rsp_precond.f90
    SolverUtilities/rsp_utilities.f90
    )

set(RSP_PROPERTIES_SOURCES	
    rsp_properties/molecular_hessian.f90
    rsp_properties/test_molHessian.f90
    )

set(PBC_FORTRAN_SOURCES
    pbc2/pbc_compare.f90
    pbc2/pbc-multipole.f90
    pbc2/pbc-matop.f90
    pbc2/pbc-harmonics.f90
    pbc2/pbc-msc.f90
    pbc2/pbc-krsp-op.f90
    pbc2/pbc_kscf.f90
    pbc2/pbc_mmit.f90
    pbc2/pbc_eigsolv.f90
    pbc2/pbc-data.f90
    pbc2/pbc-ffdata.f90
    pbc2/pbc_int.f90
    )

set(FMM_SOURCES
    mm/mm_T_contractors.f90
    mm/mm_T_pair_builder.f90
    mm/mm_T_pair_tests.f90
    mm/mm_T_worker.f90
    mm/mm_Vff_driver.f90
    mm/mm_Vff_processor.f90
    mm/mm_W_contractors.f90
    mm/mm_W_pair_builder.f90
    mm/mm_W_worker.f90
    mm/mm_box_builder.f90
    mm/mm_box_processor.f90
    mm/mm_buffers.f90
    mm/mm_densfit.f90
    mm/mm_driver.f90
    mm/mm_global_paras.f90
    mm/mm_grid_searcher.f90
    mm/mm_input.f90
    mm/mm_interface.f90
    mm/mm_map_builder.f90
    mm/mm_memory.f90
    mm/mm_memory_manager.f90
    mm/mm_overlap_tree.f90
    mm/mm_sort.f90
    mm/mm_stats.f90
    mm/mm_tree_T_buffer.f90
    mm/cbifmm_f90.f90
    )   
set(INTERESTLIB_SOURCES
    interest/src/module_interest.f90
    interest/src/module_interest_hrr.f90
    interest/src/module_interest_osr.f90
    )
set(LSINT_SOURCES
    LSint/BuildBasis.f90
    LSint/BuildMolFile.f90
    LSint/II_Fragment.f90
    LSint/gridgeneration.f90
    LSint/gridgeneration_boxify.f90
    LSint/II_XC_interface.f90
    LSint/II_absval_int.f90
    LSint/II_dft_int.f90
    LSint/II_dft_ksm.f90
    LSint/II_dft_ksm_worker.f90
    LSint/Integral_interface.f90
    LSint/Integral_interfaceDEC.f90
    LSint/Integral_interfaceDF.f90
    LSint/Integral_interface_test.f90
    LSint/MBIE.f90
    LSint/Molecule.f90
    LSint/ODbatches.f90
    LSint/ReadMolFile.f90
    LSint/ThermiteDistribute.f90
    LSint/ThermiteDistributeK.f90
    LSint/ThermiteDistributeDEC.f90
    LSint/ThermiteDriver.f90
    LSint/ThermiteIntegrals.f90
    LSint/ThermiteOverlapDistribution.f90
    LSint/ThermiteProp.f90
    LSint/ThermiteMem.f90
    LSint/dalton-input.f90
    LSint/linsolv_df.f90
    LSint/ls_IntegralInterface.f90
    LSint/pari.f90
    LSint/lsmpi.f90
    )
#####################################################
#WARNING: READ ME BEFORE ADDING FILES TO LSUTIL
# lsutil is split into several bunches
# The LSUTIL_PRECISION_SOURCES is the first to be compiled
# and contains only lsutil/ls_precision.f90
# the next be compiled is LSUTIL_MATRIXM_SOURCES
# which contains the matrix type definition. 
# then LSUTIL_COMMON_SOURCES which should only contain 
# type definitions and files which only depend on 
# lsutil/ls_precision.f90 and lsutil/matrix_module.f90
# then LSUTIL_MATRIXO_SOURCES and LSUTIL_MATRIXO_C_SOURCES and
# LSUTIL_MATRIXU_SOURCES is compiled. Then
# LSUTIL_TYPE_SOURCES which despite the name
# contains alot of files which deals wiht Operations of 
# types. Then at the end some Utillities are gathered in
# LSUTILLIB_SOURCES
############################################################

set(LSUTIL_PRECISION_SOURCES
    lsutil/ls_precision.f90
    lsutil/ptr_assoc.f90
    )

set(LSUTIL_MATRIXM_SOURCES
    lsutil/matrix_module.f90    
    )

set(LSUTIL_COMMON_SOURCES
    lsutil/rsp-typedef.f90
    lsutil/tensor_type_def.f90
    lsutil/response_prop_type.f90
    lsutil/ls_IOType.f90
    lsutil/AOType.f90
    lsutil/dec_typedef.f90
    lsutil/MoleculeType.f90
    lsutil/ODType.f90
    lsutil/lstensorType.f90
    lsutil/dftType.f90
    lsutil/BasisinfoType.f90
    lsutil/IntegralOutputType.f90 
    lsutil/f12.f90
    lsutil/IntegralType.f90
    lsutil/TYPE-DEF.f90
    lsutil/memory.f90
    lsutil/gridgeneration_memory.f90
    lsutil/Time.f90
    lsutil/common_utilities.f90
    lsutil/ls_parameters.f90
    lsutil/par_mod.f90
    lsutil/lsmpiType.f90
    lsutil/TestMPI.f90
    lsutil/LSmatrixType.f90
    lsutil/lsmatop_dense.f90
    lsutil/file-operations.f90
    lsutil/grid_utilities.f90
    lsutil/mat3dim.f90
    lsutil/papi.f90
    lsutil/ls_math.f90
    lsutil/SphCartMatrices.f90
    lsutil/OverlapDistributionType.f90
    )

set(LSUTIL_MATRIXO_SOURCES
    lsutil/matop_csr.f90
    lsutil/matop_dense.f90
    lsutil/matop_dense_unrest.f90
    lsutil/matop_scalapack.f90    
    )
set(LSUTIL_MATRIXO_C_SOURCES
    lsutil/matop_csr_aux.c
    lsutil/myPAPI_set_inherit.c
    )

set(LSUTIL_MATRIXU_SOURCES
    lsutil/mat-operations-aux.f90
    lsutil/mat-operations-essential.f90
    lsutil/matrix_utilities.f90
    lsutil/matrix_defop_backend.f90
    lsutil/matrix_defop_lowlevel.f90
    lsutil/matrix_defop.f90
    )

set(LSUTIL_TYPE_SOURCES
    lsutil/AO_operations.f90
    lsutil/Molecule_operations.f90
    lsutil/OD_operations.f90
    lsutil/lstensor_Mem.f90
    lsutil/lstensor_operations.f90
    lsutil/Integral_input.f90
    lsutil/ls_IO.f90
    lsutil/ls_screen.f90
    lsutil/dft_operations.f90
    lsutil/dftMem.f90
    lsutil/Basisinfo_operations.f90
    lsutil/IntegralOutput_operations.f90 
    lsutil/TYPE-OP.f90
    lsutil/pbc_lattice_type.f90
    lsutil/Build_AOBATCH.f90
    lsutil/lspdm_basic.f90
    lsutil/tensor_basic.f90
    lsutil/lspdm_tensor_operations.f90
    lsutil/manual_reorderings.f90
    lsutil/manual_utils.f90
    )

set(LSUTILLIB_SOURCES
    lsutil/lowdin.f90
    lsutil/AtomicSparse.f90
    lsutil/compilation_info.f90
    lsutil/git_revision_info.f90
    lsutil/fundamental.f90
    lsutil/ks-settings.f90
    lsutil/lsmpi-operations.f90
    lsutil/lsutilities.f90
    lsutil/ls_screenMPI.f90
    lsutil/LSoptType.f90
    lsutil/ddynType.f90
    lsutil/ProfileType.f90
    lsutil/pbc_lattice_vectors.f90
    lsutil/tensor_interface.f90
    lsutil/lspdm_slave.f90
    )   

set(LSLIB_SOURCES
    lsdaltonsrc/LSlib.f90
    lsdaltonsrc/LSlib_tester.f90
    )

set(FIXED_FORTRAN_SOURCES
    dft/dft_gridLL.F
    linears/cholesky.F
    linears/invroutines.F
    pdpack/jacobi.F
    pdpack/eispack.F
    pdpack/linpack.F
    )
set(OWN_BLAS_SOURCES
    pdpack/blas_wrapper.F
    pdpack/gp_dblas1.F
    pdpack/gp_dblas2.F
    pdpack/gp_dblas3.F
    pdpack/gp_sblas.F
    pdpack/gp_qblas.F
    pdpack/gp_zblas.F
    )
set(OWN_LAPACK_SOURCES
    pdpack/gp_dlapack.F
    pdpack/gp_zlapack.F
    )
