set(TEST_BASE ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton)
set(TEST_PARAM )
set(TEST_ARGS  )
set(TEST_ARGS5 )

if(ENABLE_MPI)
  set(TEST_PARAM "-N 2")
  set(TEST_ARGS  -param "-N 2")
  set(TEST_ARGS5 -param "-N 5")
endif()

if(ENABLE_64BIT_INTEGERS)
  add_test(linsca/linsca_trilevel_64bit ${TEST_BASE} ${TEST_ARGS}  linsca/linsca_trilevel_64bit )
  add_test(linsca/linsca_atoms_64bit    ${TEST_BASE} ${TEST_ARGS}  linsca/linsca_atoms_64bit )
endif()  

set(RUN_SCALAPACK_TESTS FALSE)

if(ENABLE_MPI)
  if(ENABLE_SCALAPACK)
    if(ENABLE_64BIT_INTEGERS)
      ####################################################################################################################################################### 
      # 64 bit integers and 32 bit integer MPI lib
      # do not perform SCALAPACK tests this combi do not work 
      ####################################################################################################################################################### 
      if(NOT ENABLE_MPI32)
        set(RUN_SCALAPACK_TESTS TRUE)
      endif()
    else()
      set(RUN_SCALAPACK_TESTS TRUE)
    endif()
  endif()
endif()
    
if(RUN_SCALAPACK_TESTS)
    add_test(SCALAPACK/linsca_arh_SCALAPACK                  ${TEST_BASE} ${TEST_ARGS}  SCALAPACK/linsca_arh_SCALAPACK          )
    add_test(SCALAPACK/linsca_atoms_SCALAPACK                ${TEST_BASE} ${TEST_ARGS}  SCALAPACK/linsca_atoms_SCALAPACK        )
    add_test(SCALAPACK/linsca_energy_SCALAPACK               ${TEST_BASE} ${TEST_ARGS}  SCALAPACK/linsca_energy_SCALAPACK       )     
    add_test(SCALAPACK/linsca_trilevel_2nd_local_SCALAPACK   ${TEST_BASE} ${TEST_ARGS}  SCALAPACK/linsca_trilevel_2nd_local_SCALAPACK)
    add_test(SCALAPACK/linsca_trilevel_2nd_all_SCALAPACK     ${TEST_BASE} ${TEST_ARGS}  SCALAPACK/linsca_trilevel_2nd_all_SCALAPACK)
    add_test(SCALAPACK/LSDALTON_DENSFIT_FMM_SCALAPACK        ${TEST_BASE} ${TEST_ARGS}  SCALAPACK/LSDALTON_DENSFIT_FMM_SCALAPACK)
    add_test(SCALAPACK/LSDALTON_FMM_SCALAPACK                ${TEST_BASE} ${TEST_ARGS}  SCALAPACK/LSDALTON_FMM_SCALAPACK        ) 
    add_test(SCALAPACK/LSDALTON_ethane_dft_molgrad_SCALAPACK ${TEST_BASE} ${TEST_ARGS}  SCALAPACK/LSDALTON_ethane_dft_molgrad_SCALAPACK)
    add_test(SCALAPACK/LSresponse_DFT_beta_SCALAPACK         ${TEST_BASE} ${TEST_ARGS}  SCALAPACK/LSresponse_DFT_beta_SCALAPACK )
    add_test(SCALAPACK/linsca_arh_SCALAPACK_MEMDIST          ${TEST_BASE} ${TEST_ARGS}  SCALAPACK/linsca_arh_SCALAPACK_MEMDIST  )
    add_test(SCALAPACK/linsca_atoms_SCALAPACK_MEMDIST        ${TEST_BASE} ${TEST_ARGS}  SCALAPACK/linsca_atoms_SCALAPACK_MEMDIST)
endif()

if(ENABLE_XCFUN)
  add_test(LSresponse/LSresponse_xcfun_lda_molgrad       ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_xcfun_lda_molgrad )
  add_test(LSresponse/LSresponse_xcfun_gga_molgrad       ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_xcfun_gga_molgrad )
  add_test(LSresponse/LSresponse_xcfun_lda_linrsp        ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_xcfun_lda_linrsp )
  add_test(LSresponse/LSresponse_xcfun_gga_linrsp        ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_xcfun_gga_linrsp )
endif()

if(ENABLE_OPENRSP)
  add_test(LSint/LSDALTON_gen1int                        ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_gen1int                        )
endif()

if(ENABLE_CSR)
  add_test(csr/linsca_atoms_csr_debug                     ${TEST_BASE}  ${TEST_ARGS} csr/linsca_atoms_csr_debug                  )
  add_test(csr/linsca_energy_csr                          ${TEST_BASE}  ${TEST_ARGS} csr/linsca_energy_csr                       )
  add_test(csr/linsca_onestep_csr                         ${TEST_BASE}  ${TEST_ARGS} csr/linsca_onestep_csr                      )
  add_test(csr/LSDALTON_INCREM_csr                        ${TEST_BASE}  ${TEST_ARGS} csr/LSDALTON_INCREM_csr                     )
  add_test(csr/LSDALTON_FMM_csr                           ${TEST_BASE}  ${TEST_ARGS} csr/LSDALTON_FMM_csr                        ) 
  add_test(csr/LSDALTON_ethane_dft_molgrad_csr            ${TEST_BASE}  ${TEST_ARGS} csr/LSDALTON_ethane_dft_molgrad_csr         )
#  add_test(csr/linsca_direct_dens_csr                     ${TEST_BASE}  ${TEST_ARGS} csr/linsca_direct_dens_csr                  ) 
#  add_test(csr/linsca_trilevel_2nd_local_csr              ${TEST_BASE}  ${TEST_ARGS} csr/linsca_trilevel_2nd_local_csr           )
#  add_test(csr/linsca_trilevel_2nd_all_csr                ${TEST_BASE}  ${TEST_ARGS} csr/linsca_trilevel_2nd_all_csr             )
#  add_test(csr/linsca_atoms_csr                           ${TEST_BASE}  ${TEST_ARGS} csr/linsca_atoms_csr                       ) 
#  add_test(csr/linsca_rhf_stability_csr                   ${TEST_BASE}  ${TEST_ARGS} csr/linsca_rhf_stability_csr                )
#  add_test(csr/linsca_trilevel_csr                        ${TEST_BASE}  ${TEST_ARGS} csr/linsca_trilevel_csr                     )
#  add_test(csr/LSDALTON_DENSFIT_FMM_csr                   ${TEST_BASE}  ${TEST_ARGS} csr/LSDALTON_DENSFIT_FMM_csr                )
endif()

add_test(LSlib/LSlib_cam_reg                            ${TEST_BASE}  -param "-lslib_test ${TEST_PARAM}" LSlib/LSlib_cam_reg                 )
add_test(LSlib/LSlib_cam_dfJ_aK                         ${TEST_BASE}  -param "-lslib_test ${TEST_PARAM}" LSlib/LSlib_cam_dfJ_aK              )
add_test(linsca/linsca_energy                           ${TEST_BASE} ${TEST_ARGS} linsca/linsca_energy                          )
add_test(linsca/linsca_VanLenthe                        ${TEST_BASE} ${TEST_ARGS} linsca/linsca_VanLenthe                       )
add_test(linsca/linsca_emsl                             ${TEST_BASE} ${TEST_ARGS} linsca/linsca_emsl                          )
add_test(linsca/linsca_las                              ${TEST_BASE} ${TEST_ARGS} linsca/linsca_las                           )
add_test(linsca/linsca_admm                             ${TEST_BASE} ${TEST_ARGS} linsca/linsca_admm                          )
add_test(linsca/linsca_admm_df                          ${TEST_BASE} ${TEST_ARGS} linsca/linsca_admm_df                       )
add_test(linsca/linsca_dft_energy                       ${TEST_BASE} ${TEST_ARGS} linsca/linsca_dft_energy                      )
add_test(linsca/linsca_rhf_stability                    ${TEST_BASE} ${TEST_ARGS} linsca/linsca_rhf_stability                   )
# add_test(linsca/linsca_direct_dens                      ${TEST_BASE} ${TEST_ARGS} linsca/linsca_direct_dens                     )
add_test(linsca/linsca_arh                              ${TEST_BASE} ${TEST_ARGS} linsca/linsca_arh                             )
add_test(linsca/linsca_arh_davidson                     ${TEST_BASE} ${TEST_ARGS} linsca/linsca_arh_davidson                    )
add_test(linsca/linsca_arh_ls_davidson                  ${TEST_BASE} ${TEST_ARGS} linsca/linsca_arh_ls_davidson                 )
add_test(linsca/linsca_trilevel_2nd_local               ${TEST_BASE} ${TEST_ARGS} linsca/linsca_trilevel_2nd_local              )
add_test(linsca/linsca_trilevel_2nd_all                 ${TEST_BASE} ${TEST_ARGS} linsca/linsca_trilevel_2nd_all                )
add_test(linsca/linsca_atoms                            ${TEST_BASE} ${TEST_ARGS} linsca/linsca_atoms                           )
add_test(linsca/linsca_trilevel                         ${TEST_BASE} ${TEST_ARGS} linsca/linsca_trilevel                        )
add_test(linsca/lsdalton_dft_ssfgrid                    ${TEST_BASE} ${TEST_ARGS} linsca/lsdalton_dft_ssfgrid                   )
add_test(linsca/test_kurtosis                           ${TEST_BASE} ${TEST_ARGS} linsca/test_kurtosis                          )
add_test(linsca/PipekMezeyLowdin                        ${TEST_BASE} ${TEST_ARGS} linsca/PipekMezeyLowdin                       )
add_test(linsca/linsca_lcm_nongc                        ${TEST_BASE} ${TEST_ARGS} linsca/linsca_lcm_nongc                       )
add_test(linsca/test_soeo                               ${TEST_BASE} ${TEST_ARGS} linsca/test_soeo                              )
add_test(LSint/LSDALTON_b3lyp_water                     ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_b3lyp_water                    )
add_test(LSint/LSDALTON_pure                            ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_pure                           )
add_test(LSint/LSDALTON_userdefined_basis1              ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_userdefined_basis1             )
add_test(LSint/LSDALTON_userdefined_basis2              ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_userdefined_basis2             )
add_test(LSint/LSDALTON_NOBQBQ2                         ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_NOBQBQ2                        )
add_test(LSint/LSDALTON_pointcharge                     ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_pointcharge                    )
add_test(LSint/LSDALTON_pointcharge2                    ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_pointcharge2                   )
add_test(LSint/LSDALTON_phantom                         ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_phantom                        )
add_test(LSint/LSDALTON_phantom2                        ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_phantom2                       )
add_test(LSint/LSDALTON_EP                              ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_EP                             )
add_test(LSint/LSDALTON_PropertyTest1                   ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_PropertyTest1                  )
add_test(LSint/LSDALTON_geoderiv                        ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_geoderiv                       )
add_test(LSint/LSDALTON_magderiv                        ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_magderiv                       )
add_test(LSint/LSDALTON_magderiv2                       ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_magderiv2                      )
add_test(LSint/LSDALTON_magderiv3                       ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_magderiv3                      )
add_test(LSint/LSDALTON_camb3lyp                        ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_camb3lyp                       )
add_test(LSint/LSDALTON_camb3lyp2                       ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_camb3lyp2                      )
add_test(LSint/LSDALTON_screen1                         ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_screen1                        )
add_test(LSint/LSDALTON_screen2                         ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_screen2                        )
add_test(LSint/LSDALTON_cartesian_ecoeff                ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_cartesian_ecoeff               )
add_test(LSint/LSDALTON_MBIE                            ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_MBIE                           )
add_test(LSint/LSDALTON_DaLink                          ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_DaLink                         )
add_test(LSint/LSDALTON_DaLink2                         ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_DaLink2                        )
add_test(LSint/LSDALTON_DENSFIT_FMM                     ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_DENSFIT_FMM                    )
add_test(LSint/LSDALTON_dftfunc_bp86                    ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_dftfunc_bp86                   )
add_test(LSint/LSDALTON_dftfunc_bpw91                   ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_dftfunc_bpw91                  )
add_test(LSint/LSDALTON_dftfunc_kt3                     ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_dftfunc_kt3                    )
add_test(LSint/LSDALTON_dftfunc_lb94                    ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_dftfunc_lb94                   )
add_test(LSint/LSDALTON_dftfunc_pbe0                    ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_dftfunc_pbe0                   )
add_test(LSint/LSDALTON_dftfunc_pw86x                   ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_dftfunc_pw86x                  )
add_test(LSint/LSDALTON_dftfunc_vwn3                    ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_dftfunc_vwn3                   )
add_test(LSint/LSDALTON_dftfunc_GGAKey                  ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_dftfunc_GGAKey                 )
add_test(LSint/LSDALTON_ethane_df_dft_molgrad           ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_ethane_df_dft_molgrad          )
add_test(LSint/LSDALTON_ethane_df_lda_jengine           ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_ethane_df_lda_jengine          )
add_test(LSint/LSDALTON_ethane_df_overlap_lda           ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_ethane_df_overlap_lda          )
add_test(LSint/LSDALTON_ethane_dft_molgrad              ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_ethane_dft_molgrad             )
add_test(LSint/LSDALTON_ethane_lda_jengine              ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_ethane_lda_jengine             )
add_test(LSint/LSDALTON_FMM                             ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_FMM                            )
add_test(LSint/LSDALTON_FMM_trilevel                    ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_FMM_trilevel                   )
#add_test(LSint/LSDALTON_fmm_gradient                    ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_fmm_gradient                   )
#add_test(LSint/LSDALTON_fmm_df_gradient                 ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_fmm_df_gradient                )
#add_test(LSint/LSDALTON_fmm_twoel_gradient              ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_fmm_twoel_gradient             )
add_test(LSint/LSDALTON_INCREM                          ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_INCREM                         )
add_test(LSint/LSDALTON_INCREM2                         ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_INCREM2                        )
add_test(LSint/LSDALTON_J_NSETUV                        ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_J_NSETUV                       )
add_test(LSint/LSDALTON_Link                            ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_Link                           )
add_test(LSint/LSDALTON_NOFAMILY                        ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_NOFAMILY                       )
add_test(LSint/LSDALTON_pass                            ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_pass                           )
add_test(LSint/LSDALTON_PrimAng                         ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_PrimAng                        )
add_test(LSint/LSDALTON_ethane_dfK_dft                  ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_ethane_dfK_dft                 )
add_test(LSint/LSDALTON_ethane_pari_b3lyp               ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_ethane_pari_b3lyp              )
add_test(LSint/LSDALTON_ethane_pari_b3lyp_unconstrained ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_ethane_pari_b3lyp_unconstrained)
add_test(LSint/LSDALTON_ethane_pari_b3lyp_ChgConst      ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_ethane_pari_b3lyp_ChgConst)
add_test(LSint/LSDALTON_ethane_pari_b3lyp_ChgDipConst   ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_ethane_pari_b3lyp_ChgDipConst)
add_test(LSint/LSDALTON_UNCONT                          ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_UNCONT                         )
add_test(LSint/LSDALTON_ethane_dft_disp                 ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_ethane_dft_disp                )
add_test(LSint/LSDALTON_HF_cartesian                    ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_HF_cartesian                   )
add_test(LSint/LSDALTON_augTZ                           ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_augTZ                          )
add_test(LSint/LSDALTON_donotsavegab                    ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_donotsavegab                   )
add_test(LSint/LSDALTON_INCREMDALINK                    ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_INCREMDALINK            )
add_test(LSint/LSDALTON_SR_EXCHANGE                     ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_SR_EXCHANGE                    )
add_test(LSint/LSDALTON_LSlib                           ${TEST_BASE} ${TEST_ARGS5} LSint/LSDALTON_LSlib                          )

add_test(LSresponse/LSresponse_HF_alpha                 ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_HF_alpha                )
add_test(LSresponse/LSresponse_HF_alpha_aK              ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_HF_alpha_aK             )
add_test(LSresponse/LSresponse_HF_alpha_astv            ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_HF_alpha_astv           )
add_test(LSresponse/LSresponse_HF_beta                  ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_HF_beta                 )
add_test(LSresponse/LSresponse_HF_dipole                ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_HF_dipole               )
add_test(LSresponse/LSresponse_HF_dtpa                  ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_HF_dtpa                 )
add_test(LSresponse/LSresponse_HF_esd                   ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_HF_esd                  )
add_test(LSresponse/LSresponse_HF_esg                   ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_HF_esg                  )
add_test(LSresponse/LSresponse_HF_gamma                 ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_HF_gamma                )
add_test(LSresponse/LSresponse_HF_gamma_lcm             ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_HF_gamma_lcm            )
add_test(LSresponse/LSresponse_HF_molgra                ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_HF_molgra               )
add_test(LSresponse/LSresponse_HF_opa                   ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_HF_opa                  )
add_test(LSresponse/LSresponse_HF_tpa                   ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_HF_tpa                  )
add_test(LSresponse/LSresponse_DFT_alpha                ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_DFT_alpha               )
add_test(LSresponse/LSresponse_DFT_alpha_aptv           ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_DFT_alpha_aptv          )
add_test(LSresponse/LSresponse_DFT_beta                 ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_DFT_beta                )
add_test(LSresponse/LSresponse_DFT_dipole               ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_DFT_dipole              )
add_test(LSresponse/LSresponse_DFT_esd                  ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_DFT_esd                 )
add_test(LSresponse/LSresponse_DFT_esg                  ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_DFT_esg                 )
add_test(LSresponse/LSresponse_DFT_esg_LDA              ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_DFT_esg_LDA             )
add_test(LSresponse/LSresponse_DFT_dtpa                 ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_DFT_dtpa                )
add_test(LSresponse/LSresponse_DFT_molgra               ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_DFT_molgra              )
add_test(LSresponse/LSresponse_DFT_opa                  ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_DFT_opa                 )
add_test(LSresponse/LSresponse_DFT_tpa                  ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_DFT_tpa                 )
add_test(LSresponse/LSresponse_NMR_SHIELD               ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_NMR_SHIELD              )
add_test(LSresponse/LSresponse_mcd                      ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_mcd                     )
add_test(LSresponse/LSresponse_mcd2                     ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_mcd2                     )
 add_test(LSresponse/LSresponse_mcd3                     ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_mcd3                     )
add_test(LSresponse/LSresponse_mcd_calc                 ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_mcd_calc                 )
add_test(LSresponse/LSresponse_excit_cs00                    ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_excit_cs00                     )
add_test(geomopt/Excited_state_opt                      ${TEST_BASE} ${TEST_ARGS} geomopt/Excited_state_opt                     )
add_test(geomopt/geoopt_constrain                       ${TEST_BASE} ${TEST_ARGS} geomopt/geoopt_constrain                      )
add_test(geomopt/cartes_bfgs_min                        ${TEST_BASE} ${TEST_ARGS} geomopt/cartes_bfgs_min                       )
add_test(geomopt/redint_bfgs                            ${TEST_BASE} ${TEST_ARGS} geomopt/redint_bfgs                           )
add_test(geomopt/cartes_trilevel_newconv                ${TEST_BASE} ${TEST_ARGS} geomopt/cartes_trilevel_newconv               )
add_test(geomopt/cartes_psb_min                         ${TEST_BASE} ${TEST_ARGS} geomopt/cartes_psb_min                        )
add_test(ddynam/HCN_ddyn                                ${TEST_BASE} ${TEST_ARGS} ddynam/HCN_ddyn                               )
add_test(ddynam/HF_vib                                  ${TEST_BASE} ${TEST_ARGS} ddynam/HF_vib                                 )
add_test(ddynam/H2O_fmd                                 ${TEST_BASE} ${TEST_ARGS} ddynam/H2O_fmd                                )
add_test(dectests/decmp2_energy                         ${TEST_BASE} ${TEST_ARGS5} dectests/decmp2_energy                        )
add_test(dectests/decmp2_density                        ${TEST_BASE} ${TEST_ARGS5} dectests/decmp2_density                       )
add_test(dectests/decmp2_gradient                       ${TEST_BASE} ${TEST_ARGS5} dectests/decmp2_gradient                      )
add_test(dectests/decmp2_geoopt                         ${TEST_BASE} ${TEST_ARGS5} dectests/decmp2_geoopt                        )
add_test(dectests/fullmp2_energy                        ${TEST_BASE} ${TEST_ARGS5} dectests/fullmp2_energy                       )
add_test(dectests/fullcc2                               ${TEST_BASE} ${TEST_ARGS5} dectests/fullcc2                              )
add_test(dectests/fullccsd_high                         ${TEST_BASE} ${TEST_ARGS5} dectests/fullccsd_high                        )
add_test(dectests/fullccsd_3                            ${TEST_BASE} ${TEST_ARGS5} dectests/fullccsd_3                           )
add_test(dectests/fullccsd_2                            ${TEST_BASE} ${TEST_ARGS5} dectests/fullccsd_2                           )
add_test(dectests/arraytest                             ${TEST_BASE} ${TEST_ARGS5} dectests/arraytest                            )
add_test(dectests/reordertest                           ${TEST_BASE} ${TEST_ARGS} dectests/reordertest                          )
add_test(dectests/decmp2_gradient_debug                 ${TEST_BASE} ${TEST_ARGS5} dectests/decmp2_gradient_debug                )
add_test(plt/plt_dens                                   ${TEST_BASE} ${TEST_ARGS} plt/plt_dens                                  )
add_test(plt/plt_ep                                     ${TEST_BASE} ${TEST_ARGS} plt/plt_ep                                    )

if(NOT ENABLE_RELEASE)
  add_test(LSint/LSDALTON_uncontAObatch                  ${TEST_BASE} ${TEST_ARGS5} LSint/LSDALTON_uncontAObatch                  )
  add_test(LSint/LSDALTON_UDFT                            ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_UDFT                           )
  add_test(LSint/LSDALTON_UHF_DEFAULT                     ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_UHF_DEFAULT                    )
  add_test(LSint/LSDALTON_UHF_excit                       ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_UHF_excit                      )
  add_test(LSint/LSDALTON_UHF_excit2                      ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_UHF_excit2                     )
  add_test(LSint/LSDALTON_UHF_excit_radical               ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_UHF_excit_radical              )
  add_test(LSint/LSDALTON_UHF_hessian                     ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_UHF_hessian                    )
  add_test(LSint/LSDALTON_UHF_JENGINE                     ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_UHF_JENGINE                    )
  add_test(LSint/LSDALTON_UHF_JENGINE_LINK                ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_UHF_JENGINE_LINK               )
  add_test(LSint/LSDALTON_UHF_LINK                        ${TEST_BASE} ${TEST_ARGS} LSint/LSDALTON_UHF_LINK                       )
  add_test(linsca/linsca_unrest_energy                    ${TEST_BASE} ${TEST_ARGS} linsca/linsca_unrest_energy                   )
  add_test(linsca/linsca_unrest_dft_energy                ${TEST_BASE} ${TEST_ARGS} linsca/linsca_unrest_dft_energy               )
  add_test(linsca/linsca_uhf_stability                    ${TEST_BASE} ${TEST_ARGS} linsca/linsca_uhf_stability                   )
  add_test(LSresponse/LSresponse_DFT_excit_beta           ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_DFT_excit_beta          )
  add_test(LSresponse/LSresponse_HF_gamma_SVD             ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_HF_gamma_SVD            )
  add_test(dectests/fullmp2_f12                           ${TEST_BASE} ${TEST_ARGS5} dectests/fullmp2_f12                          )
  add_test(dectests/fullmp2_local_f12                     ${TEST_BASE} ${TEST_ARGS5} dectests/fullmp2_local_f12                    )
  add_test(dectests/fullccsd_f12                          ${TEST_BASE} ${TEST_ARGS5} dectests/fullccsd_f12                         )
  add_test(dectests/fullccsd_1                            ${TEST_BASE} ${TEST_ARGS5} dectests/fullccsd_1                           )
  add_test(dectests/fullccsd_low                          ${TEST_BASE} ${TEST_ARGS5} dectests/fullccsd_low                         )
  add_test(dectests/fullccsdpt                            ${TEST_BASE} ${TEST_ARGS5} dectests/fullccsdpt                           )
  add_test(dectests/decccsdpt                             ${TEST_BASE} ${TEST_ARGS5} dectests/decccsdpt                            )
  add_test(dectests/decccsdpt_simfull                     ${TEST_BASE} ${TEST_ARGS5} dectests/decccsdpt_simfull                    )
  add_test(dectests/decmp2_gradient_debug2                ${TEST_BASE} ${TEST_ARGS5} dectests/decmp2_gradient_debug2               )
  add_test(dectests/decmp2_energy_FO                      ${TEST_BASE} ${TEST_ARGS5} dectests/decmp2_energy_FO                     )
  add_test(dectests/decmp2_geoopt_FO                      ${TEST_BASE} ${TEST_ARGS5} dectests/decmp2_geoopt_FO                     )
  add_test(dectests/decccsd                               ${TEST_BASE} ${TEST_ARGS5} dectests/decccsd                              )
  add_test(pbc2/pbc2_h2fock                               ${TEST_BASE} ${TEST_ARGS} pbc2/pbc2_h2fock                              )
  add_test(pbc2/pbc2_h2SCF_iter1                          ${TEST_BASE} ${TEST_ARGS} pbc2/pbc2_h2SCF_iter1                         )
  add_test(pbc2/pbc2_h2STO6G                              ${TEST_BASE} ${TEST_ARGS} pbc2/pbc2_h2STO6G                             )
 #add_test(LSresponse/LSresponse_HF_molHessian           ${TEST_BASE} ${TEST_ARGS} LSresponse/LSresponse_HF_molHessian           )
endif() 
