if(ENABLE_MPI)
 if(ENABLE_64BIT_INTEGERS)
  ####################################################################################################################################################### 
  # 64 bit integers and MPI
  ####################################################################################################################################################### 
  add_test(linsca/linsca_trilevel_64bit ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  linsca/linsca_trilevel_64bit )
  add_test(linsca/linsca_atoms_64bit    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  linsca/linsca_atoms_64bit )
  if(ENABLE_MPI32)
   ####################################################################################################################################################### 
   # 64 bit integers and 32 bit integer MPI lib
   # do not perform SCALAPACK tests this combi do not work 
   ####################################################################################################################################################### 
  else()
   ####################################################################################################################################################### 
   # 64 bit integers and 64 bit integer MPI lib
   ####################################################################################################################################################### 
   if(ENABLE_SCALAPACK)
    add_test(SCALAPACK/linsca_arh_SCALAPACK                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/linsca_arh_SCALAPACK          )
    add_test(SCALAPACK/linsca_atoms_SCALAPACK                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/linsca_atoms_SCALAPACK        )
    add_test(SCALAPACK/linsca_direct_dens_SCALAPACK          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/linsca_direct_dens_SCALAPACK  ) 
    add_test(SCALAPACK/linsca_energy_SCALAPACK               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/linsca_energy_SCALAPACK       )     
    add_test(SCALAPACK/linsca_trilevel_2nd_local_SCALAPACK   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/linsca_trilevel_2nd_local_SCALAPACK)
    add_test(SCALAPACK/linsca_trilevel_2nd_all_SCALAPACK     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/linsca_trilevel_2nd_all_SCALAPACK)
    add_test(SCALAPACK/LSDALTON_DENSFIT_FMM_SCALAPACK        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/LSDALTON_DENSFIT_FMM_SCALAPACK)
    add_test(SCALAPACK/LSDALTON_FMM_SCALAPACK                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/LSDALTON_FMM_SCALAPACK        ) 
    add_test(SCALAPACK/LSDALTON_ethane_dft_molgrad_SCALAPACK ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/LSDALTON_ethane_dft_molgrad_SCALAPACK)
    add_test(SCALAPACK/LSresponse_DFT_beta_SCALAPACK         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/LSresponse_DFT_beta_SCALAPACK )
    add_test(SCALAPACK/linsca_arh_SCALAPACK_MEMDIST          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/linsca_arh_SCALAPACK_MEMDIST  )
    add_test(SCALAPACK/linsca_atoms_SCALAPACK_MEMDIST        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/linsca_atoms_SCALAPACK_MEMDIST)
   endif()
  endif()
 else() 
  ####################################################################################################################################################### 
  # 32 bit integers and MPI
  ####################################################################################################################################################### 
  if(ENABLE_SCALAPACK)
   add_test(SCALAPACK/linsca_arh_SCALAPACK                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/linsca_arh_SCALAPACK          )
   add_test(SCALAPACK/linsca_atoms_SCALAPACK                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/linsca_atoms_SCALAPACK        )
   add_test(SCALAPACK/linsca_direct_dens_SCALAPACK          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/linsca_direct_dens_SCALAPACK  ) 
   add_test(SCALAPACK/linsca_energy_SCALAPACK               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/linsca_energy_SCALAPACK       )     
   add_test(SCALAPACK/linsca_trilevel_2nd_local_SCALAPACK   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/linsca_trilevel_2nd_local_SCALAPACK)
   add_test(SCALAPACK/linsca_trilevel_2nd_all_SCALAPACK     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/linsca_trilevel_2nd_all_SCALAPACK)
   add_test(SCALAPACK/LSDALTON_DENSFIT_FMM_SCALAPACK        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/LSDALTON_DENSFIT_FMM_SCALAPACK)
   add_test(SCALAPACK/LSDALTON_FMM_SCALAPACK                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/LSDALTON_FMM_SCALAPACK        ) 
   add_test(SCALAPACK/LSDALTON_ethane_dft_molgrad_SCALAPACK ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/LSDALTON_ethane_dft_molgrad_SCALAPACK)
   add_test(SCALAPACK/LSresponse_DFT_beta_SCALAPACK         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/LSresponse_DFT_beta_SCALAPACK )
   add_test(SCALAPACK/linsca_arh_SCALAPACK_MEMDIST          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/linsca_arh_SCALAPACK_MEMDIST  )
   add_test(SCALAPACK/linsca_atoms_SCALAPACK_MEMDIST        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2"  SCALAPACK/linsca_atoms_SCALAPACK_MEMDIST)
  endif()
 endif()
 ####################################################################################################################################################### 
 #General MPI testcases that should be run independent of 64/32 bit integers 
 ####################################################################################################################################################### 
 add_test(LSlib/LSlib_cam_reg                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-lslib_test -N 2" LSlib/LSlib_cam_reg                 )
 add_test(LSlib/LSlib_cam_dfJ_aK                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-lslib_test -N 2" LSlib/LSlib_cam_dfJ_aK              )
 if(ENABLE_CSR)
  add_test(csr/linsca_atoms_csr_debug                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-N 2" csr/linsca_atoms_csr_debug                  )
  add_test(csr/linsca_direct_dens_csr                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-N 2" csr/linsca_direct_dens_csr                  ) 
  add_test(csr/linsca_energy_csr                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-N 2" csr/linsca_energy_csr                       )
  add_test(csr/linsca_onestep_csr                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-N 2" csr/linsca_onestep_csr                      )
  add_test(csr/linsca_trilevel_2nd_local_csr              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-N 2" csr/linsca_trilevel_2nd_local_csr           )
  add_test(csr/linsca_trilevel_2nd_all_csr                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-N 2" csr/linsca_trilevel_2nd_all_csr             )
  add_test(csr/LSDALTON_INCREM_csr                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-N 2" csr/LSDALTON_INCREM_csr                     )
  add_test(csr/LSDALTON_FMM_csr                           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-N 2" csr/LSDALTON_FMM_csr                        ) 
  add_test(csr/LSDALTON_ethane_dft_molgrad_csr            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-N 2" csr/LSDALTON_ethane_dft_molgrad_csr         )
#  add_test(csr/linsca_atoms_csr                           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-N 2" csr/linsca_atoms_csr                       ) 
#  add_test(csr/linsca_rhf_stability_csr                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-N 2" csr/linsca_rhf_stability_csr                )
#  add_test(csr/linsca_trilevel_csr                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-N 2" csr/linsca_trilevel_csr                     )
#  add_test(csr/LSDALTON_DENSFIT_FMM_csr                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-N 2" csr/LSDALTON_DENSFIT_FMM_csr                )
 endif()
 add_test(linsca/lsdalton_dft_olddefaultgrid             ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/lsdalton_dft_olddefaultgrid ) 
 add_test(linsca/linsca_energy                           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_energy                          )
 add_test(linsca/linsca_emsl                             ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_emsl                          )
 add_test(linsca/linsca_las                              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_las                           )
 add_test(linsca/linsca_admm                             ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_admm                          )
 add_test(linsca/linsca_admm_df                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_admm_df                       )
 add_test(linsca/linsca_dft_energy                       ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_dft_energy                      )
 add_test(linsca/linsca_unrest_energy                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_unrest_energy                   )
 add_test(linsca/linsca_unrest_dft_energy                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_unrest_dft_energy               )
 add_test(linsca/linsca_rhf_stability                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_rhf_stability                   )
 add_test(linsca/linsca_uhf_stability                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_uhf_stability                   )
 add_test(linsca/linsca_direct_dens                      ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_direct_dens                     )
 add_test(linsca/linsca_arh                              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_arh                             )
 add_test(linsca/linsca_arh_davidson                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_arh_davidson                    )
 add_test(linsca/linsca_arh_ls_davidson                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_arh_ls_davidson                 )
 add_test(linsca/linsca_trilevel_2nd_local               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_trilevel_2nd_local              )
 add_test(linsca/linsca_trilevel_2nd_all                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_trilevel_2nd_all                )
 add_test(linsca/linsca_atoms                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_atoms                           )
 add_test(linsca/linsca_trilevel                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/linsca_trilevel                        )
 add_test(linsca/lsdalton_dft_ssfgrid                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/lsdalton_dft_ssfgrid                   )
 add_test(linsca/test_kurtosis                           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/test_kurtosis                          )
 add_test(linsca/PipekMezeyLowdin                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/PipekMezeyLowdin                       )
 add_test(linsca/test_soeo                               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" linsca/test_soeo                              )
 if(ENABLE_OPENRSP)
  add_test(LSint/LSDALTON_gen1int                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_gen1int                        )
 endif()
 add_test(LSint/LSDALTON_b3lyp_water                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_b3lyp_water                    )
 add_test(LSint/LSDALTON_pure                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_pure                           )
 add_test(LSint/LSDALTON_userdefined_basis1              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_userdefined_basis1             )
 add_test(LSint/LSDALTON_userdefined_basis2              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_userdefined_basis2             )
 add_test(LSint/LSDALTON_NOBQBQ2                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_NOBQBQ2                        )
 add_test(LSint/LSDALTON_pointcharge                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_pointcharge                    )
 add_test(LSint/LSDALTON_pointcharge2                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_pointcharge2                   )
 add_test(LSint/LSDALTON_phantom                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_phantom                        )
 add_test(LSint/LSDALTON_phantom2                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_phantom2                       )
 add_test(LSint/LSDALTON_EP                              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_EP                             )
 add_test(LSint/LSDALTON_PropertyTest1                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_PropertyTest1                  )
 #add_test(LSint/LSDALTON_geoderiv                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_geoderiv                       )
 add_test(LSint/LSDALTON_magderiv                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_magderiv                       )
 add_test(LSint/LSDALTON_magderiv2                       ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_magderiv2                      )
 add_test(LSint/LSDALTON_magderiv3                       ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_magderiv3                      )
 add_test(LSint/LSDALTON_camb3lyp                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_camb3lyp                       )
 add_test(LSint/LSDALTON_camb3lyp2                       ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_camb3lyp2                      )
 add_test(LSint/LSDALTON_screen1                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_screen1                        )
 add_test(LSint/LSDALTON_screen2                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_screen2                        )
 add_test(LSint/LSDALTON_cartesian_ecoeff                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_cartesian_ecoeff               )
 add_test(LSint/LSDALTON_MBIE                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_MBIE                           )
 add_test(LSint/LSDALTON_DaLink                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_DaLink                         )
 add_test(LSint/LSDALTON_DaLink2                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_DaLink2                        )
 add_test(LSint/LSDALTON_DENSFIT_FMM                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_DENSFIT_FMM                    )
 add_test(LSint/LSDALTON_dftfunc_bp86                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_dftfunc_bp86                   )
 add_test(LSint/LSDALTON_dftfunc_bpw91                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_dftfunc_bpw91                  )
 add_test(LSint/LSDALTON_dftfunc_kt3                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_dftfunc_kt3                    )
 add_test(LSint/LSDALTON_dftfunc_lb94                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_dftfunc_lb94                   )
 add_test(LSint/LSDALTON_dftfunc_pbe0                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_dftfunc_pbe0                   )
 add_test(LSint/LSDALTON_dftfunc_pw86x                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_dftfunc_pw86x                  )
 add_test(LSint/LSDALTON_dftfunc_vwn3                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_dftfunc_vwn3                   )
 add_test(LSint/LSDALTON_dftfunc_GGAKey                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_dftfunc_GGAKey                 )
 add_test(LSint/LSDALTON_ethane_df_dft_molgrad           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_ethane_df_dft_molgrad          )
 add_test(LSint/LSDALTON_ethane_df_lda_jengine           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_ethane_df_lda_jengine          )
 add_test(LSint/LSDALTON_ethane_df_overlap_lda           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_ethane_df_overlap_lda          )
 add_test(LSint/LSDALTON_ethane_dft_molgrad              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_ethane_dft_molgrad             )
 add_test(LSint/LSDALTON_ethane_lda_jengine              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_ethane_lda_jengine             )
 add_test(LSint/LSDALTON_FMM                             ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_FMM                            )
 add_test(LSint/LSDALTON_FMM_trilevel                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_FMM_trilevel                   )
 #add_test(LSint/LSDALTON_fmm_gradient                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_fmm_gradient                   )
 #add_test(LSint/LSDALTON_fmm_df_gradient                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_fmm_df_gradient                )
 #add_test(LSint/LSDALTON_fmm_twoel_gradient              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_fmm_twoel_gradient             )
 add_test(LSint/LSDALTON_INCREM                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_INCREM                         )
 add_test(LSint/LSDALTON_INCREM2                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_INCREM2                        )
 add_test(LSint/LSDALTON_J_NSETUV                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_J_NSETUV                       )
 add_test(LSint/LSDALTON_Link                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_Link                           )
 add_test(LSint/LSDALTON_NOFAMILY                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_NOFAMILY                       )
 add_test(LSint/LSDALTON_pass                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_pass                           )
 add_test(LSint/LSDALTON_PrimAng                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_PrimAng                        )
 add_test(LSint/LSDALTON_ethane_dfK_dft                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_ethane_dfK_dft                 )
 add_test(LSint/LSDALTON_ethane_pari_b3lyp               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_ethane_pari_b3lyp              )
 add_test(LSint/LSDALTON_ethane_pari_b3lyp_unconstrained ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_ethane_pari_b3lyp_unconstrained)
 add_test(LSint/LSDALTON_ethane_pari_b3lyp_ChgConst      ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_ethane_pari_b3lyp_ChgConst)
 add_test(LSint/LSDALTON_ethane_pari_b3lyp_ChgDipConst   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_ethane_pari_b3lyp_ChgDipConst)
 add_test(LSint/LSDALTON_UDFT                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_UDFT                           )
 add_test(LSint/LSDALTON_UHF_DEFAULT                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_UHF_DEFAULT                    )
 add_test(LSint/LSDALTON_UHF_excit                       ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_UHF_excit                      )
 add_test(LSint/LSDALTON_UHF_excit2                      ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_UHF_excit2                     )
 add_test(LSint/LSDALTON_UHF_excit_radical               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_UHF_excit_radical              )
 add_test(LSint/LSDALTON_UHF_hessian                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_UHF_hessian                    )
 add_test(LSint/LSDALTON_UHF_JENGINE                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_UHF_JENGINE                    )
 add_test(LSint/LSDALTON_UHF_JENGINE_LINK                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_UHF_JENGINE_LINK               )
 add_test(LSint/LSDALTON_UHF_LINK                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_UHF_LINK                       )
 add_test(LSint/LSDALTON_UNCONT                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_UNCONT                         )
 add_test(LSint/LSDALTON_ethane_dft_disp                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_ethane_dft_disp                )
 add_test(LSint/LSDALTON_HF_cartesian                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_HF_cartesian                   )
 add_test(LSint/LSDALTON_augTZ                           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_augTZ                          )
 add_test(LSint/LSDALTON_donotsavegab                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_donotsavegab                   )
 add_test(LSint/LSDALTON_INCREMDALINK                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_INCREMDALINK            )
 add_test(LSint/LSDALTON_SR_EXCHANGE                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSint/LSDALTON_SR_EXCHANGE                    )
 add_test(LSint/LSDALTON_uncontAObatch                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" LSint/LSDALTON_uncontAObatch                  )
 add_test(LSint/LSDALTON_LSlib                           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" LSint/LSDALTON_LSlib                          )

 add_test(LSresponse/LSresponse_HF_alpha                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_HF_alpha                )
 add_test(LSresponse/LSresponse_HF_alpha_aK              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_HF_alpha_aK             )
 add_test(LSresponse/LSresponse_HF_alpha_astv            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_HF_alpha_astv           )
 add_test(LSresponse/LSresponse_HF_beta                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_HF_beta                 )
 add_test(LSresponse/LSresponse_HF_dipole                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_HF_dipole               )
 add_test(LSresponse/LSresponse_HF_dtpa                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_HF_dtpa                 )
 add_test(LSresponse/LSresponse_HF_esd                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_HF_esd                  )
 add_test(LSresponse/LSresponse_HF_esg                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_HF_esg                  )
 add_test(LSresponse/LSresponse_HF_gamma                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_HF_gamma                )
 add_test(LSresponse/LSresponse_HF_gamma_SVD             ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_HF_gamma_SVD            )
 add_test(LSresponse/LSresponse_HF_gamma_lcm             ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_HF_gamma_lcm            )
 add_test(LSresponse/LSresponse_HF_molgra                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_HF_molgra               )
 #add_test(LSresponse/LSresponse_HF_molHessian           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_HF_molHessian           )
 add_test(LSresponse/LSresponse_HF_opa                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_HF_opa                  )
 add_test(LSresponse/LSresponse_HF_tpa                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_HF_tpa                  )
 add_test(LSresponse/LSresponse_DFT_alpha                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_DFT_alpha               )
 add_test(LSresponse/LSresponse_DFT_alpha_aptv           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_DFT_alpha_aptv          )
 add_test(LSresponse/LSresponse_DFT_beta                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_DFT_beta                )
 add_test(LSresponse/LSresponse_DFT_excit_beta           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_DFT_excit_beta          )
 add_test(LSresponse/LSresponse_DFT_dipole               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_DFT_dipole              )
 add_test(LSresponse/LSresponse_DFT_esd                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_DFT_esd                 )
 add_test(LSresponse/LSresponse_DFT_esg                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_DFT_esg                 )
 add_test(LSresponse/LSresponse_DFT_dtpa                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_DFT_dtpa                )
 add_test(LSresponse/LSresponse_DFT_molgra               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_DFT_molgra              )
 add_test(LSresponse/LSresponse_DFT_opa                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_DFT_opa                 )
 add_test(LSresponse/LSresponse_DFT_tpa                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_DFT_tpa                 )
 add_test(LSresponse/LSresponse_NMR_SHIELD               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_NMR_SHIELD              )
 #add_test(LSresponse/LSresponse_mcd                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_mcd                     )
 #add_test(LSresponse/LSresponse_mcd2                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_mcd2                     )
 #add_test(LSresponse/LSresponse_mcd3                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_mcd3                     )
 add_test(LSresponse/LSresponse_excit_cs00                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" LSresponse/LSresponse_excit_cs00                     )

 add_test(geomopt/Excited_state_opt                      ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" geomopt/Excited_state_opt                     )
 add_test(geomopt/geoopt_constrain                       ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" geomopt/geoopt_constrain                      )
 add_test(geomopt/cartes_bfgs_min                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" geomopt/cartes_bfgs_min                       )
 add_test(geomopt/redint_bfgs                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" geomopt/redint_bfgs                           )
 add_test(geomopt/cartes_trilevel_newconv                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" geomopt/cartes_trilevel_newconv               )
 add_test(geomopt/cartes_psb_min                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" geomopt/cartes_psb_min                        )

 add_test(ddynam/HCN_ddyn                                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" ddynam/HCN_ddyn                               )
 add_test(ddynam/HF_vib                                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" ddynam/HF_vib                                 )
 add_test(ddynam/H2O_fmd                                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" ddynam/H2O_fmd                                )

 add_test(dectests/arraytest                             ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/arraytest                            )
 add_test(dectests/reordertest                           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" dectests/reordertest                          )
 add_test(dectests/fullmp2                               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/fullmp2                              )
 add_test(dectests/fullmp2_f12                           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/fullmp2_f12                          )
 add_test(dectests/fullmp2_local_f12                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/fullmp2_local_f12                    )
 add_test(dectests/fullccsd_f12                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/fullccsd_f12                         )
 add_test(dectests/fullcc2                               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/fullcc2                              )
 add_test(dectests/fullccsd_high                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/fullccsd_high                        )
 add_test(dectests/fullccsd_3                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/fullccsd_3                           )
 add_test(dectests/fullccsd_2                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/fullccsd_2                           )
 add_test(dectests/fullccsd_1                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/fullccsd_1                           )
 add_test(dectests/fullccsd_low                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/fullccsd_low                         )
 add_test(dectests/fullccsdpt                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/fullccsdpt                           )
 add_test(dectests/decccsdpt                             ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/decccsdpt                            )
 add_test(dectests/decmp2_energy                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/decmp2_energy                        )
 add_test(dectests/decmp2_density                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/decmp2_density                       )
 add_test(dectests/decmp2_gradient                       ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/decmp2_gradient                      )
 add_test(dectests/decmp2_geoopt                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/decmp2_geoopt                        )
 add_test(dectests/decmp2_gradient_debug                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/decmp2_gradient_debug                )
 add_test(dectests/decmp2_gradient_debug2                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/decmp2_gradient_debug2               )
 add_test(dectests/decmp2_energy_FO                      ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/decmp2_energy_FO                     )
 add_test(dectests/decmp2_geoopt_FO                      ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/decmp2_geoopt_FO                     )
 add_test(dectests/decccsd                               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 5" dectests/decccsd                              )

 add_test(pbc2/pbc2_h2fock                               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" pbc2/pbc2_h2fock                              )
 add_test(pbc2/pbc2_h2SCF_iter1                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" pbc2/pbc2_h2SCF_iter1                         )
 add_test(pbc2/pbc2_h2STO6G                              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-N 2" pbc2/pbc2_h2STO6G                             )
else()
 ####################################################################################################################################################### 
 #General nonMPI testcases
 ####################################################################################################################################################### 
 if(ENABLE_64BIT_INTEGERS)
  add_test(linsca/linsca_trilevel_64bit                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  linsca/linsca_trilevel_64bit                  )
  add_test(linsca/linsca_atoms_64bit                      ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  linsca/linsca_atoms_64bit                     )
 endif()
 if(ENABLE_CSR)
  add_test(csr/linsca_atoms_csr_debug                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  csr/linsca_atoms_csr_debug                  )
  add_test(csr/linsca_direct_dens_csr                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  csr/linsca_direct_dens_csr                  )
  add_test(csr/linsca_energy_csr                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  csr/linsca_energy_csr                       )
  add_test(csr/linsca_onestep_csr                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  csr/linsca_onestep_csr                      )
  add_test(csr/linsca_trilevel_2nd_local_csr              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  csr/linsca_trilevel_2nd_local_csr           )
  add_test(csr/linsca_trilevel_2nd_all_csr                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  csr/linsca_trilevel_2nd_all_csr             )
  add_test(csr/LSDALTON_INCREM_csr                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  csr/LSDALTON_INCREM_csr                     )
  add_test(csr/LSDALTON_FMM_csr                           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  csr/LSDALTON_FMM_csr                        ) 
  add_test(csr/LSDALTON_ethane_dft_molgrad_csr            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  csr/LSDALTON_ethane_dft_molgrad_csr         )
  #add_test(csr/linsca_atoms_csr                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  csr/linsca_atoms_csr                       ) 
  #add_test(csr/linsca_rhf_stability_csr                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  csr/linsca_rhf_stability_csr                )
  #add_test(csr/linsca_trilevel_csr                       ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  csr/linsca_trilevel_csr                     )
  #add_test(csr/LSDALTON_DENSFIT_FMM_csr                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  csr/LSDALTON_DENSFIT_FMM_csr                )
 endif()
 add_test(LSlib/LSlib_cam_reg                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-lslib_test" LSlib/LSlib_cam_reg                  )
 add_test(LSlib/LSlib_cam_dfJ_aK                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton  -param "-lslib_test" LSlib/LSlib_cam_dfJ_aK                  )

 add_test(linsca/lsdalton_dft_olddefaultgrid             ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/lsdalton_dft_olddefaultgrid            )
 add_test(linsca/linsca_energy                           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_energy                          )
 add_test(linsca/linsca_emsl                             ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_emsl                            )
 add_test(linsca/linsca_las                              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_las                             )
 add_test(linsca/linsca_admm                             ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_admm                            )
 add_test(linsca/linsca_admm_df                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_admm_df                         )
 add_test(linsca/linsca_dft_energy                       ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_dft_energy                      )
 add_test(linsca/linsca_unrest_energy                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_unrest_energy                   )
 add_test(linsca/linsca_unrest_dft_energy                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_unrest_dft_energy               )
 add_test(linsca/linsca_rhf_stability                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_rhf_stability                   )
 add_test(linsca/linsca_uhf_stability                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_uhf_stability                   )
 add_test(linsca/linsca_direct_dens                      ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_direct_dens                     )
 add_test(linsca/linsca_arh                              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_arh                             )
 add_test(linsca/linsca_arh_davidson                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_arh_davidson                    )
 add_test(linsca/linsca_arh_ls_davidson                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_arh_ls_davidson                 )
 add_test(linsca/linsca_trilevel_2nd_local               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_trilevel_2nd_local              )
 add_test(linsca/linsca_trilevel_2nd_all                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_trilevel_2nd_all                )
 add_test(linsca/linsca_atoms                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_atoms                           )
 add_test(linsca/linsca_trilevel                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/linsca_trilevel                        )
 add_test(linsca/lsdalton_dft_ssfgrid                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/lsdalton_dft_ssfgrid                   )
 add_test(linsca/test_kurtosis                           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/test_kurtosis                          )
 add_test(linsca/PipekMezeyLowdin                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/PipekMezeyLowdin                       )
 add_test(linsca/test_soeo                               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton linsca/test_soeo                              )
 if(ENABLE_OPENRSP)
  add_test(LSint/LSDALTON_gen1int                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_gen1int                        )
 endif()
 add_test(LSint/LSDALTON_b3lyp_water                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_b3lyp_water                    )
 add_test(LSint/LSDALTON_pure                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_pure                           )
 add_test(LSint/LSDALTON_userdefined_basis1              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_userdefined_basis1             )
 add_test(LSint/LSDALTON_userdefined_basis2              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_userdefined_basis2             )
 add_test(LSint/LSDALTON_NOBQBQ2                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_NOBQBQ2                        )
 add_test(LSint/LSDALTON_pointcharge                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_pointcharge                    )
 add_test(LSint/LSDALTON_pointcharge2                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_pointcharge2                   )
 add_test(LSint/LSDALTON_phantom                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_phantom                        )
 add_test(LSint/LSDALTON_phantom2                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_phantom2                       )
 add_test(LSint/LSDALTON_EP                              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_EP                             )
 add_test(LSint/LSDALTON_PropertyTest1                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_PropertyTest1                  )
 add_test(LSint/LSDALTON_geoderiv                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_geoderiv                       )
 add_test(LSint/LSDALTON_magderiv                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_magderiv                       )
 add_test(LSint/LSDALTON_magderiv2                       ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_magderiv2                      )
 add_test(LSint/LSDALTON_magderiv3                       ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_magderiv3                      )
 add_test(LSint/LSDALTON_camb3lyp                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_camb3lyp                       )
 add_test(LSint/LSDALTON_camb3lyp2                       ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_camb3lyp2                      )
 add_test(LSint/LSDALTON_screen1                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_screen1                        )
 add_test(LSint/LSDALTON_screen2                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_screen2                        )
 add_test(LSint/LSDALTON_cartesian_ecoeff                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_cartesian_ecoeff               )
 add_test(LSint/LSDALTON_MBIE                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_MBIE                           )
 add_test(LSint/LSDALTON_DaLink                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_DaLink                         )
 add_test(LSint/LSDALTON_DaLink2                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_DaLink2                       )
 add_test(LSint/LSDALTON_DENSFIT_FMM                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_DENSFIT_FMM                    )
 add_test(LSint/LSDALTON_dftfunc_bp86                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_dftfunc_bp86                   )
 add_test(LSint/LSDALTON_dftfunc_bpw91                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_dftfunc_bpw91                  )
 add_test(LSint/LSDALTON_dftfunc_kt3                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_dftfunc_kt3                    )
 add_test(LSint/LSDALTON_dftfunc_lb94                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_dftfunc_lb94                   )
 add_test(LSint/LSDALTON_dftfunc_pbe0                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_dftfunc_pbe0                   )
 add_test(LSint/LSDALTON_dftfunc_pw86x                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_dftfunc_pw86x                  )
 add_test(LSint/LSDALTON_dftfunc_vwn3                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_dftfunc_vwn3                   )
 add_test(LSint/LSDALTON_dftfunc_GGAKey                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_dftfunc_GGAKey                 )
 add_test(LSint/LSDALTON_ethane_df_dft_molgrad           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_ethane_df_dft_molgrad          )
 add_test(LSint/LSDALTON_ethane_df_lda_jengine           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_ethane_df_lda_jengine          )
 add_test(LSint/LSDALTON_ethane_df_overlap_lda           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_ethane_df_overlap_lda          )
 add_test(LSint/LSDALTON_ethane_dft_molgrad              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_ethane_dft_molgrad             )
 add_test(LSint/LSDALTON_ethane_lda_jengine              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_ethane_lda_jengine             )
 add_test(LSint/LSDALTON_FMM                             ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_FMM                            )
 add_test(LSint/LSDALTON_FMM_trilevel                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_FMM_trilevel                   )
 #add_test(LSint/LSDALTON_fmm_gradient                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_fmm_gradient                   )
 #add_test(LSint/LSDALTON_fmm_df_gradient                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_fmm_df_gradient                )
 #add_test(LSint/LSDALTON_fmm_twoel_gradient              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_fmm_twoel_gradient             )
 add_test(LSint/LSDALTON_INCREM                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_INCREM                         )
 add_test(LSint/LSDALTON_INCREM2                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_INCREM2                        )
 add_test(LSint/LSDALTON_J_NSETUV                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_J_NSETUV                       )
 add_test(LSint/LSDALTON_Link                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_Link                           )
 add_test(LSint/LSDALTON_NOFAMILY                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_NOFAMILY                       )
 add_test(LSint/LSDALTON_pass                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_pass                           )
 add_test(LSint/LSDALTON_PrimAng                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_PrimAng                        )
 add_test(LSint/LSDALTON_ethane_dfK_dft                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_ethane_dfK_dft                 )
 add_test(LSint/LSDALTON_ethane_pari_b3lyp               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_ethane_pari_b3lyp              )
 add_test(LSint/LSDALTON_ethane_pari_b3lyp_unconstrained ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_ethane_pari_b3lyp_unconstrained)
 add_test(LSint/LSDALTON_ethane_pari_b3lyp_ChgConst      ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_ethane_pari_b3lyp_ChgConst)
 add_test(LSint/LSDALTON_ethane_pari_b3lyp_ChgDipConst   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_ethane_pari_b3lyp_ChgDipConst)
 add_test(LSint/LSDALTON_UDFT                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_UDFT                           )
 add_test(LSint/LSDALTON_UHF_DEFAULT                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_UHF_DEFAULT                    )
 add_test(LSint/LSDALTON_UHF_excit                       ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_UHF_excit                      )
 add_test(LSint/LSDALTON_UHF_excit2                      ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_UHF_excit2                     )
 add_test(LSint/LSDALTON_UHF_excit_radical               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_UHF_excit_radical              )
 add_test(LSint/LSDALTON_UHF_hessian                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_UHF_hessian                    )
 add_test(LSint/LSDALTON_UHF_JENGINE                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_UHF_JENGINE                    )
 add_test(LSint/LSDALTON_UHF_JENGINE_LINK                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_UHF_JENGINE_LINK               )
 add_test(LSint/LSDALTON_UHF_LINK                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_UHF_LINK                       )
 add_test(LSint/LSDALTON_UNCONT                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_UNCONT                         )
 add_test(LSint/LSDALTON_ethane_dft_disp                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_ethane_dft_disp                )
 add_test(LSint/LSDALTON_HF_cartesian                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_HF_cartesian                   )
 add_test(LSint/LSDALTON_augTZ                           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_augTZ                          )
 add_test(LSint/LSDALTON_donotsavegab                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_donotsavegab                   )
 add_test(LSint/LSDALTON_INCREMDALINK                    ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_INCREMDALINK            )
 add_test(LSint/LSDALTON_SR_EXCHANGE                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_SR_EXCHANGE                    )
 add_test(LSint/LSDALTON_uncontAObatch                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_uncontAObatch                  )
 add_test(LSint/LSDALTON_LSlib                           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSint/LSDALTON_LSlib                          )

 add_test(LSresponse/LSresponse_HF_alpha                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_HF_alpha                )
 add_test(LSresponse/LSresponse_HF_alpha_aK              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_HF_alpha_aK             )
 add_test(LSresponse/LSresponse_HF_alpha_astv            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_HF_alpha_astv           )
 add_test(LSresponse/LSresponse_HF_beta                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_HF_beta                 )
 add_test(LSresponse/LSresponse_HF_dipole                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_HF_dipole               )
 add_test(LSresponse/LSresponse_HF_dtpa                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_HF_dtpa                 )
 add_test(LSresponse/LSresponse_HF_esd                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_HF_esd                  )
 add_test(LSresponse/LSresponse_HF_esg                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_HF_esg                  )
 add_test(LSresponse/LSresponse_HF_gamma                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_HF_gamma                )
 add_test(LSresponse/LSresponse_HF_gamma_SVD             ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_HF_gamma_SVD            )
 add_test(LSresponse/LSresponse_HF_gamma_lcm             ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_HF_gamma_lcm            )
 add_test(LSresponse/LSresponse_HF_molgra                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_HF_molgra               )
 #add_test(LSresponse/LSresponse_HF_molHessian            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_HF_molHessian           )
 add_test(LSresponse/LSresponse_HF_opa                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_HF_opa                  )
 add_test(LSresponse/LSresponse_HF_tpa                   ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_HF_tpa                  )

 add_test(LSresponse/LSresponse_DFT_alpha                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_DFT_alpha               )
 add_test(LSresponse/LSresponse_DFT_alpha_aptv           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_DFT_alpha_aptv          )
 add_test(LSresponse/LSresponse_DFT_beta                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_DFT_beta                )
 add_test(LSresponse/LSresponse_DFT_excit_beta           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_DFT_excit_beta          )
 add_test(LSresponse/LSresponse_DFT_dipole               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_DFT_dipole              )
 add_test(LSresponse/LSresponse_DFT_esd                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_DFT_esd                 )
 add_test(LSresponse/LSresponse_DFT_esg                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_DFT_esg                 )
 add_test(LSresponse/LSresponse_DFT_dtpa                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_DFT_dtpa                )
 add_test(LSresponse/LSresponse_DFT_molgra               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_DFT_molgra              )
 add_test(LSresponse/LSresponse_DFT_opa                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_DFT_opa                 )
 add_test(LSresponse/LSresponse_DFT_tpa                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_DFT_tpa                 )
 add_test(LSresponse/LSresponse_NMR_SHIELD               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_NMR_SHIELD              )
 add_test(LSresponse/LSresponse_mcd                      ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_mcd                     )
 add_test(LSresponse/LSresponse_mcd2                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_mcd2                    )
 add_test(LSresponse/LSresponse_mcd3                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_mcd3                    )
 add_test(LSresponse/LSresponse_excit_cs00                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton LSresponse/LSresponse_excit_cs00                    )

 add_test(geomopt/Excited_state_opt                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton geomopt/Excited_state_opt                       )
 add_test(geomopt/geoopt_constrain                       ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton geomopt/geoopt_constrain                       )
 add_test(geomopt/cartes_bfgs_min                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton geomopt/cartes_bfgs_min                       )
 add_test(geomopt/redint_bfgs                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton geomopt/redint_bfgs                           )
 add_test(geomopt/cartes_trilevel_newconv                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton geomopt/cartes_trilevel_newconv               )
 add_test(geomopt/cartes_psb_min                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton geomopt/cartes_psb_min                        )

 add_test(ddynam/HCN_ddyn                                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton ddynam/HCN_ddyn                               )
 add_test(ddynam/HF_vib                                  ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton ddynam/HF_vib                                 )
 add_test(ddynam/H2O_fmd                                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton ddynam/H2O_fmd                                )

 add_test(dectests/arraytest                             ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/arraytest                            )
 add_test(dectests/reordertest                           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/reordertest                          )
 add_test(dectests/fullmp2                               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/fullmp2                              )
 add_test(dectests/fullmp2_f12                           ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/fullmp2_f12                          )
 add_test(dectests/fullmp2_local_f12                     ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/fullmp2_local_f12                    )
 add_test(dectests/fullccsd_f12                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/fullccsd_f12                         )
 add_test(dectests/fullcc2                               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/fullcc2                              )
 add_test(dectests/fullccsd_high                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/fullccsd_high                        )
 add_test(dectests/fullccsd_3                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/fullccsd_3                           )
 add_test(dectests/fullccsd_2                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/fullccsd_2                           )
 add_test(dectests/fullccsd_1                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/fullccsd_1                           )
 add_test(dectests/fullccsd_low                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/fullccsd_low                         )
 add_test(dectests/fullccsdpt                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/fullccsdpt                           )
 add_test(dectests/decccsdpt                             ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/decccsdpt                            )
 add_test(dectests/decmp2_energy                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/decmp2_energy                        )
 add_test(dectests/decmp2_density                        ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/decmp2_density                       )
 add_test(dectests/decmp2_gradient                       ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/decmp2_gradient                      )
 add_test(dectests/decmp2_geoopt                         ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/decmp2_geoopt                        )
 add_test(dectests/decmp2_gradient_debug                 ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/decmp2_gradient_debug                )
 add_test(dectests/decmp2_gradient_debug2                ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/decmp2_gradient_debug2               )
 add_test(dectests/decmp2_energy_FO                      ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/decmp2_energy_FO                     )
 add_test(dectests/decmp2_geoopt_FO                      ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/decmp2_geoopt_FO                     )
 add_test(dectests/decccsd                               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton dectests/decccsd                              )

 add_test(pbc2/pbc2_h2fock                               ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton pbc2/pbc2_h2fock                              )
 add_test(pbc2/pbc2_h2SCF_iter1                          ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton pbc2/pbc2_h2SCF_iter1                         )
 add_test(pbc2/pbc2_h2STO6G                              ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton pbc2/pbc2_h2STO6G                             )

 add_test(gridgen/gridgentest                            ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -gridgen -param "-gridgen" gridgen/gridgentest)
endif()
