#!/usr/bin/env python
#    rsp_cpp_mcd
#    -------
#    Molecule:         H2O
#    Wave Function:    DFT (CAMB3LYP)
#    Test Purpose:     MCD calculations with damping using
#                      the solver with symmetrized trial vectors

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final DFT energy',
      rel_tolerance = 1.0e-10)

f.add(re = '[XYZ]DIPLEN * [XYZ]DIPLEN',
      rel_tolerance = 2.0e-4)

f.add(re = '[XYZ]DIPLEN * [XYZ]DIPLEN * [XYZ]ANGMOM',
      rel_tolerance = 2.0e-4)

test.run(['rsp_cpp_mcd.dal'], ['H2O_cc-pVDZ.mol'], f={'out': f})

sys.exit(test.return_code)
