#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from runtest_lsdalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(string = 'SUCCESSFUL')

test.run(['Ichor2Center.dal'], ['water.mol'], {'out': f})

sys.exit(test.return_code)

