#!/usr/bin/env python
#    dft_cr_sym
#    ------------------
#    Molecule:         H2O
#    Wave Functions:   DFT B3LYP / STO-3G
#    Test Purpose:     DFT B3LYP second-hyperpolarizabilities test w/ symmetry.

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final DFT energy',
      rel_tolerance = 1.0e-8)

f.add(string = '@ gamma',
      abs_tolerance = 1.0e-3)

test.run(['dft_cr_sym.dal'], ['H2O_STO-3G.mol'], f={'out': f})

sys.exit(test.return_code)
