#!/usr/bin/env python
#    prop_spinspin4
#    --------------
#    Molecule:         H2O
#    Wave Function:    MP2 (SOPPA)
#    Test Purpose:     Calculation of spin-spin coupling constants
#                      through ABACUS

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

# Basis set 
f.add(from_string = 'Atoms and basis sets',
      num_lines = 15,
      rel_tolerance = 1.0e-2)

# Molecular geometry
f.add(from_string = 'Cartesian Coordinates',
      num_lines = 10,
      rel_tolerance = 1.0e-8)


# Symmetry
f.add(string = 'Number of coordinates in each symmetry',
      rel_tolerance = 1.0e-2)
f.add(string = 'Number of orbitals in each symmetry',
      rel_tolerance = 1.0e-2)

# Energies
f.add(string = 'Hartree-Fock total energy',
      rel_tolerance = 1.0e-9)
f.add(string = 'MP2 second order energy',
      rel_tolerance = 1.0e-9)

f.add(string = 'Nuclear spin-spin coupling constants',
      rel_tolerance = 1.0e-2)
f.add(string = 'Spin-spin couplings printed for atoms',
      rel_tolerance = 1.0e-2)

f.add(from_string = 'Isotropic coupling',
      num_lines = 10,
      abs_tolerance = 1.01e-4)

test.run(['prop_spinspin4.dal'], ['H2O_intgrl_sym.mol'], f={'out': f},
         accepted_errors=[
             'not implemented for parallel calculations.',
             'ERI does not work with Cartesian basis.'
             ])

sys.exit(test.return_code)
