#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi

DIR="`dirname \"$0\"`"

#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > LSlib_cam_dfJ_admm.info <<'%EOF%'
   LSlib_cam_dfJ_admm
   -------------
   Molecule:         HCN molecule
   Wave Function:    cam-B3LYP/6-31+G*
   Test Purpose:     Check LSlib routines with df-J and ADMM K
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > LSlib_cam_dfJ_admm.mol <<'%EOF%'
BASIS
6-31+G* Aux=df-def2 ADMM=3-21++G
HCN molecule
STRUCTURE IS NOT OPTIMIZED.
Atomtypes=3 Nosymmetry
Charge=1. Atoms=1
H   0.0   0.0    -1.0 
Charge=7. Atoms=1
N   0.0   0.0     1.5
Charge=6. Atoms=1
C   0.0   0.0     0.0
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > LSlib_cam_dfJ_admm.dal <<'%EOF%'
**WAVE FUNCTIONS
.DFT
 CAMB3LYP
*DFT INPUT
.GRID3
**INTEGRALS
.ADMM
.DENSFIT
.NOFAMILY
*END OF INPUT
%EOF%

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >LSlib_cam_dfJ_admm.check
cat $DIR/../../tools/lslibtester.sh >> LSlib_cam_dfJ_admm.check

#######################################################################
#  REF FILE
#######################################################################
cp $DIR/ref/LSlib_cam_dfJ_admm.ref LSlib_cam_dfJ_admm.ref
#######################################################################
