#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from runtest_lsdalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final DFT energy',
      rel_tolerance = 1.0e-8)
f.add(string = 'Nuclear repulsion',
      rel_tolerance = 1.0e-8)

f.add(from_string = 'Total shielding tensor',
      to_string   = 'Done with shielding tensor calculation',
      rel_tolerance = 1.0e-6)

f.add(string = 'Allocated memory (TOTAL)')

test.run(['LSresponse_NMR_DF_SHIELD_NoOpenRSP.dal'], ['COFH3.mol'], {'out': f})

sys.exit(test.return_code)
