! -- file: sirius/stex.h --
      PARAMETER (NOPMAX = 20)
      REAL*8  CJSTX(NOPMAX,8),CKSTX(NOPMAX,8)
      INTEGER NHLSTX(8), IHLSTX(NOPMAX,8)
      INTEGER IPRSTX, NAUGER, IAUGER(NOPMAX), JAUGER(NOPMAX)
      LOGICAL DOSTEX,XAS,XES,SHAKE,STEXMO,AUGER,RPATST
      COMMON/STEX/CJSTX,  CKSTX,
     &            NHLSTX, IHLSTX,
     &            IPRSTX, NAUGER, IAUGER, JAUGER,
     &            DOSTEX, XAS,XES,SHAKE,STEXMO,AUGER,RPATST
! -- end of sirius/stex.h --
