      PARAMETER (NOPMAX = 20)
      REAL*8 CJSTX(NOPMAX,8),CKSTX(NOPMAX,8)
      INTEGER NHLSTX(8), IHLSTX(NOPMAX,8)
      LOGICAL DOSTEX,XAS,XES,SHAKE,STEXMO,AUGER,RPATST
      INTEGER IPRSTX, NAUGER, IAUGER(NOPMAX), JAUGER(NOPMAX)
      COMMON/STEX/CJSTX, CKSTX,
     &            NHLSTX, IHLSTX, IPRSTX, NAUGER, IAUGER, JAUGER,
     &            DOSTEX,XAS,XES,SHAKE,STEXMO,AUGER,RPATST
