#!/usr/bin/env python
#    rsp_cpp_2ndhyperpolar
#    ---------------------
#    Molecule:         Neon
#    Wave Function:    HF/6-31G
#    Test Purpose:     Second-order damped hyperpolarizability calculation

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final HF energy:',
      rel_tolerance = 1.0e-8)

f.add(re = '@ <<Z;Z,Z,Z>>',
      rel_tolerance = 1.0e-4, ignore_below = 1.0e-3)

test.run(['GAMMA_ZZZZ_HF_CPP.dal'], ['neon_6-31G.mol'], f={'out': f})

sys.exit(test.return_code)
