#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'Polarizable embedding information',
      num_lines = 15,
      abs_tolerance = 1.0e-8)
test.run(['amoeba_test.dal'], ['amoeba_test.mol'], ['amoeba_water.pot', 'amoeba_peptide.pot'], f={'out': f})

g = Filter()
g.add(from_string = 'Polarizable embedding information',
      num_lines = 42,
      abs_tolerance = 1.0e-8)
test.run(['amoeba_test.dal'], ['amoeba_test.mol'], ['amoeba_peptide.pot'], f={'out': g})

sys.exit(test.return_code)
