#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > PA_oligomer_4_pariK.info <<'%EOF%'
   PA_oligomer_4_pariK
   -------------
   Molecule:         C60/6-31G
   Wave Function:    HF
   Profile:          Exchange Matrix
   CPU Time:         9 min 30 seconds
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > PA_oligomer_4_pariK.mol <<'%EOF%'
BASIS
cc-pVTZ Aux=cc-pVTZdenfit
EXCITATION DIAGNOSTIC
CAM-B3LYP/6-31G* GEOMETRY
Atomtypes=2  Nosymmetry
Charge=6.0 Atoms=6
C4       1.2669865759           -0.0359641044            0.0000000000
C4      -1.2669865759            0.0359641044            0.0000000000
C        2.7431362950           -2.3527888862            0.0000000000
C       -2.7431362950            2.3527888862            0.0000000000
C        5.2636554918           -2.4281826739            0.0000000000
C       -5.2636554918            2.4281826739            0.0000000000
Charge=1.0 Atoms=8
H2      -1.6771727859            4.1134297645            0.0000000000
H2       1.6771727859           -4.1134297645            0.0000000000
H4       2.3230142736            1.7320016855            0.0000000000
H4      -2.3230142736           -1.7320016855            0.0000000000
H        6.3874988203           -0.7091638133            0.0000000000
H       -6.3874988203            0.7091638133            0.0000000000
H        6.2907676438           -4.2019649356            0.0000000000
H       -6.2907676438            4.2019649356            0.0000000000


%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > PA_oligomer_4_pariK.dal <<'%EOF%'
**PROFILE
.EXCHANGE
**INTEGRALS
.PARI-K
**WAVE FUNCTIONS
.HF
*DENSOPT
*END OF INPUT
%EOF%

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL >PA_oligomer_4_pariK.check
cat >> PA_oligomer_4_pariK.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi
CRIT1=`$GREP "Exchange energy, mat_dotproduct\(D,K\)\= * \-XXX\.XXXXXX" $log | wc -l`
TEST[1]=`expr  $CRIT1`
CTRL[1]=1
ERROR[1]="ENERGY NOT CORRECT -"

PASSED=1
for i in 1
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
      echo ${ERROR[i]}
      PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
   echo PROF ENDED PROPERLY
   exit 0
else
   echo THERE IS A PROBLEM
   exit 1
fi

%EOF%
#######################################################################
