#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from runtest_lsdalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'numbers of lattice vectors',
      rel_tolerance = 0)
f.add(string = 'number of basis',
      rel_tolerance = 0)

#f.add(from_string = 'Summary For Counter Poise Correction',
#      to_string   = 'Interaction Energy',
#      rel_tolerance = 1.0e-8)


# to ignore sign set                      ignore_sign = True   
# to ignore numbers below 1.0e-4 set      ignore_below = 1.0e-4

f.add(string = 'Allocated memory (TOTAL)')

test.run(['pbc2_h2fock.dal'], ['H2.mol'], {'out': f})

sys.exit(test.return_code)
