#!/usr/bin/env python
#    dft_energy_sym
#    --------------
#    Molecule:         H2O2
#    Wave Function:    DFT HF+PZ81 / 6-31G**
#    Test Purpose:     DFT direct energy calculation w/symmetry

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final DFT energy',
      rel_tolerance = 1.0e-8)

test.run(['dft_energy_sym.dal'], ['H2O2_6-31Gss.mol'], f={'out': f})

sys.exit(test.return_code)
