      INTEGER NMXFREQ
      PARAMETER ( NMXFREQ=200 ) 
      REAL*8 ABS_DAMP,ABS_THCLR,ABS_RESID(3,NMXFREQ,3,8),
     &     ABS_FREQ_ALPHA(NMXFREQ),ABS_FREQ_INTERVAl(3),
     &     ABS_THD_LD
      LOGICAL ABSLRS,ABSLRS_ALPHA,ABSLRS_ANALYZE,ABSLRS_INTERVAL,
     &        ABS_IMFREQ,ABS_BATCH,ABS_DALINP
      INTEGER ABS_MAXRM,ABS_NFREQ_ALPHA,ABS_NFREQ_INTERVAL,
     &     ABS_MAXITER,IPRABSLRS,ABS_NOPER(8),ABS_NBATCHMAX,
     &     ABS_GRADSYM,ABS_MULD2H(8,8),ABS_NSYM,ABS_NASH(8),
     &     ABS_NISH(8),ABS_NORB(8),
     &     LUABSPRI, LUABSVECS,LUSB, LUAB, LUSS, LUAS
      CHARACTER*8 ABS_LABOP(3,8)
C
      COMMON /ABS_LRS1/ ABS_DAMP,ABS_THCLR,ABS_RESID,ABS_FREQ_ALPHA,
     &     ABS_FREQ_INTERVAL,ABS_THD_LD
      COMMON /ABS_LRS2/ ABSLRS,ABSLRS_ALPHA,ABSLRS_ANALYZE,
     &     ABSLRS_INTERVAL,ABS_IMFREQ,ABS_BATCH,ABS_DALINP
      COMMON /ABS_LRS3/ ABS_MAXRM,ABS_NFREQ_ALPHA,ABS_NOPER,
     &     ABS_NFREQ_INTERVAL,ABS_MAXITER,IPRABSLRS,
     &     LUABSPRI, LUABSVECS ,ABS_NBATCHMAX, ABS_GRADSYM,
     &     ABS_NSYM,ABS_NASH,ABS_NISH,ABS_NORB,ABS_MULD2H,
     &     LUSB, LUAB, LUSS, LUAS
      COMMON /ABS_LRS4/ ABS_LABOP
