      PARAMETER ( MXFREQ=10, MXSTATES=10, MXQRF=60 )
      LOGICAL ABSORP, ABS_ALPHA, ABS_BETA, ABS_GAMMA,
     &     ABS_SHG
      INTEGER NFREQ_ALPHA,IPRABS,MAX_MACRO,MAX_MICRO, 
     &     MAX_ITORB,NEXCITED_STATES,NOPER(8),KOPER,
     &     NQRF,NFREQ_BETA_B,NFREQ_BETA_C,QRFSYM(MXQRF,3)
      DOUBLE PRECISION FREQ_ALPHA(MXFREQ),DAMPING,
     &     THCLR_ABSORP,THCPP_ABSORP,
     &     EXC_ENERGY(MXSTATES,8),RESID(3,MXFREQ,3,8),
     &     RES_ALPHA(2,MXFREQ,3,3),RES_BETA(MXQRF,2),
     &     FREQ_BETA_B(MXFREQ),FREQ_BETA_C(MXFREQ),QRFFRQ(MXQRF,3)
      CHARACTER*8 LABOP(3,8),QRFLAB(MXQRF,3)
C
      COMMON /ABSORP1/ ABSORP, ABS_ALPHA, ABS_BETA, ABS_GAMMA,
     &     ABS_SHG
      COMMON /ABSORP2/ NFREQ_ALPHA,IPRABS,MAX_MACRO,MAX_MICRO, 
     &     MAX_ITORB,NEXCITED_STATES,NOPER,KOPER,
     &     NQRF,NFREQ_BETA_B,NFREQ_BETA_C,QRFSYM
      COMMON /ABSORP3/ FREQ_ALPHA,DAMPING,
     &     THCLR_ABSORP,THCPP_ABSORP,
     &     EXC_ENERGY,RESID,
     &     RES_ALPHA,RES_BETA,
     &     FREQ_BETA_B,FREQ_BETA_C,QRFFRQ
      COMMON /ABSORP4/ LABOP,QRFLAB
