      PARAMETER ( MXFREQ=10, MXSTATES=10 )
      LOGICAL ABSORP, ALPHA_FLG, BETA_FLG, GAMMA_FLG
      DOUBLE PRECISION LIFETIME
      CHARACTER*8 LABOP(3,8)
      COMMON /ABSORP1/ ABSORP, ALPHA_FLG, BETA_FLG, GAMMA_FLG
      COMMON /ABSORP2/ NFREQ_ALPHA, IPRABS, MAX_MACRO, MAX_MICRO, 
     &                 MAX_ITORB, NEXCITED_STATES,NOPER(8),KOPER
      COMMON /ABSORP3/ FREQ_ALPHA(MXFREQ),LIFETIME,THCLR_ABSORP,
     &                 THCPP_ABSORP,
     &                 EXC_ENERGY(MXSTATES,8),RESID(3,MXFREQ,3,8),
     &                 RES_ALPHA(2,MXFREQ,3,8)
      COMMON /ABSORP4/ LABOP
