      LOGICAL BIGVEC, SEGMEN, SEGMSH, SPHRSH
      COMMON /BLOCKS/ CENTSH(MXSHEL,3),
     &                MAXSHL, BIGVEC, SEGMEN,NLRGBL,NSMLBL,
     &                NHKTSH(MXSHEL), KHKTSH(MXSHEL), KCKTSH(MXSHEL),
     &                ISTBSH(MXSHEL), NUCOSH(MXSHEL), NORBSH(MXSHEL),
     &                NSTRSH(MXSHEL), NCNTSH(MXSHEL), NSETSH(MXSHEL,2),
     &                IORBSB(0:MXCORB-1), NRCSH(MXSHEL), SEGMSH(MXSHEL),
     &                LCLASH(MXSHEL), SPHRSH(MXCORB),
     &                NLRBL,ISYMBL(MXSHEL,8),NSYMBL
