C
C$Id: cbiaat.h,v 1.1.1.1 2001-02-08 13:33:23 hjj Exp $
C
      LOGICAL SKIP, CUT, NONUC, NOELC, NODBDR, NOORB, NOSEC, NODDY
      COMMON /CBIAAT/ IPRINT, INTPRI, SKIP, CUT, NONUC, NOELC,
     *                NODBDR, NOSEC, NODDY
