C
C$Id: cbicrs.h,v 1.1.1.1 2001-02-08 13:33:25 hjj Exp $
C
      LOGICAL SKIP, RUNINT,
     *        RUNFCK, TWOH1, NOH1, NOH2, FCKTST, RUNSDR, RUNTRA,
     *        SDRTST, UNDIF, TRATST, RUNGDY, NODC, NODV, NOPV, TESTFS,
     *        DIAGTD, NOFD , NOFS, NOSSF, NOORTH, J1TST, RETUR, TKTIME,
     *        AOMAT, NOKAP1, OITST, RUNOIT, RHSTES, RUNGJ1
      COMMON /CBICRS/ SKIP, RUNINT, RUNFCK, IPRALL, IPRFCK, IPRINT,
     *                IPRNTA, IPRNTB, IPRNTC, IPRNTD, IPRMAX, MAXSIM,
     *                TWOH1, NOH1, NOH2, FCKTST, RUNSDR, RUNTRA,
     *                IPRSDR, IPRTRA, SDRTST, UNDIF, TRATST, RUNGDY,
     *                IPRGDY, NODC, NODV, NOPV, TESTFS, DIAGTD, NOFD,
     *                NOFS, NOSSF, NOORTH, J1TST, RETUR, TKTIME,
     *                AOMAT, NOKAP1, OITST, RUNOIT, RHSTES, RUNGJ1
