C
C$Id: cbiexc.h,v 1.1.1.1 2001-02-08 13:33:26 hjj Exp $
C
      LOGICAL OOTV, SKIP, CUT, DIPSTR, ROTSTR, ROTVEL, FNAC, EXCTRP
      LOGICAL SUMRUL
      PARAMETER       (MAXPP = 80)
      CHARACTER*8     LABAPP
      COMMON /PPLBL / LABAPP(MAXPP), LABSYM(MAXPP)
      COMMON /CBIEXC/ THREXC,
     &                OOTV, NEXCIT(8), MAXITE, IPRINT, MXRM,
     &                MXPHP, SKIP, CUT, NABAPP, DIPSTR, ROTSTR,
     &                ROTVEL, IPREXC, FNAC, EXCTRP, SUMRUL
