      LOGICAL ROAA, ALFA, ROAG
      PARAMETER       (MXFR = 10)
      PARAMETER       (MAXLN = 80)
      CHARACTER*8     LABALN
      COMMON /LNLBL / LABALN(MAXLN)
      COMMON /CBILNR/ FRVAL(MXFR), NFRVAL, IPRLNR, THCLNR, ROAA, ROAG,
     &                ALFA, NABALN
