      LOGICAL NRMCRD, PGMTST, HTEST, PREHES, REUHES, NUMVIB,
     &        ANALZ1, NPRPDR, HARMON, SPECTR, MIDAS 
      COMMON /CBINUM/ NRMCRD, PGMTST, HTEST, PREHES, REUHES,
     &                NUMVIB, ANALZ1, NPRPDR, HARMON, SPECTR,
     &                MIDAS 
