      LOGICAL NRMCRD, PGMTST, HTEST, PREHES, REUHES, NUMVIB,
     &        ANALZE, NPRPDR, HARMON, SPECTR
      COMMON /CBINUM/ NRMCRD, PGMTST, HTEST, PREHES, REUHES,
     &                NUMVIB, ANALZE, NPRPDR, HARMON, SPECTR
