C
C$Id: cbione.h,v 1.1.1.1 2001-02-08 13:33:29 hjj Exp $
C
      LOGICAL         SKIP, DIFINT, NODC, NODV, DIFDIP, CUT, HFONLY
      COMMON /CBIONE/ IPRINT, SKIP, MAXDIF, IDATOM,
     *                IDCOOR, DIFINT, NODC, NODV, DIFDIP, CUT, HFONLY
