C
C$Id: cbiqr.h,v 1.1.1.1 2001-02-08 13:33:28 hjj Exp $
C
      PARAMETER (NFMAX = 10)
      PARAMETER (MAXPP = 80)
      CHARACTER*8     LABAPP
      LOGICAL SKIP, OOTV, CUT
      COMMON /CBIQR/ THRESH, QBFREQ(NFMAX), QCFREQ(NFMAX), SKIP, OOTV, 
     *               CUT, IPRINT, MAXITE, MXRM, MXPHP, IPRQR,
     *               LBFREQ, LCFREQ
      COMMON /QRLBL/ LABAPP(MAXPP), LABSYM(MAXPP)
