      LOGICAL BIGVC,  GENCON, INPTST, DIRAC,  BASIS,  ATOMBA,
     &        UNCONT, OLDNRM, WRTLIN, ANGS
      COMMON /CBIREA/ ZCMVAL, INPTST, IPREAD, MAXPRI, BIGVC,  GENCON,
     &                LUMLCL, DIRAC,  BASIS,  LCMMAX, NCMSTR, NCMEND,
     &                ATOMBA, UNCONT, OLDNRM, WRTLIN, ANGS
      CHARACTER*80 BASNAM
      COMMON /CBIRET/ BASNAM
