C
C$Id: cbirea.h,v 1.2 2001-05-25 14:48:05 ruud Exp $
C
      LOGICAL BIGVC,GENCON,INPTST,DIRAC,BASIS,ATOMBA,
     &        UNCONT, OLDNRM
      COMMON /CBIREA/ZCMVAL,INPTST,IPREAD,MAXPRI,BIGVC, GENCON,
     &               LUMLCL,DIRAC,BASIS, LCMMAX,NCMSTR,NCMEND,
     &               ATOMBA, UNCONT, OLDNRM
      CHARACTER*80 BASNAM
      COMMON /CBIRET/ BASNAM

