C
C$Id: cbisor.h,v 1.1.1.1 2001-02-08 13:33:25 hjj Exp $
C
      LOGICAL RNINTS
      INTEGER ISKEEP(8)
      COMMON /CBISOR/ ISKEEP, RNINTS
      LOGICAL DELAO
      CHARACTER*40 COMND,OUTSTR
      COMMON   /INTSRT/SORTST,COMND,THRQ2,ISPRINT,ISPRFIO,ISNTSYM,DELAO
