C
C$Id: cbitrp.h,v 1.1.1.1 2001-02-08 13:33:26 hjj Exp $
C
      LOGICAL SKIP, CUT, OOTV, TRPRSP
      COMMON /CBITRP/ THRTRP, IPRTRP, INTPRI, MAXTRP, MXRM, MXPHP,
     &                SKIP, CUT, OOTV, TRPRSP
