C
C$Id: cbivib.h,v 1.1.1.1 2001-02-08 13:33:26 hjj Exp $
C
      PARAMETER (MAXSUB = 20)
      LOGICAL DIPOL, SKIP, DOVCD, HESFIL, HESPUN, ROACID
      COMMON /CBIVIB/ SCALE(MXCOOR), COEF(MXCOOR), IATOMS(4,MXCOOR),
     *                NCARD,  NINTCM, DIPOL,  IPRINT, MAXDIF, NISOTP,
     *                ISOTP(MAXSUB,MXCENT), SKIP, DOVCD, HESFIL,
     *                HESPUN, ROACID
      CHARACTER KWORD*1, ITYPCD*4, ITYPCM*4
      COMMON /CBIVBC/ KWORD(MXCOOR), ITYPCD(MXCOOR), ITYPCM(MXCOOR)
