      INTEGER         LUIAJB, LUCKJD, LU3VI2, LUDKBC, LU3VI, LUDELD,
     &                LUTOC, LU3SRT, LUBFDN, LURES, 
     &                LUCSOL, LUCTLM, LU3VI3, LU3VI4, LU3SRT2, LU3SRT3,
     &                LUCKJD2, LUCKJD3, LUDELD2, LUDELD3, LUDELD4,
     &                LUDELD5, LUDKBC2, LUDKBC3, LUDKBC4, LUDKBC5
