      INTEGER MAXRED, MAXITE
      INTEGER ISYMTR, NSIMLE, NCCVAR
#if defined (SYS_CRAY)
      REAL THREXC, THRLEQ, THRENR, THRLDPHF
#else
      DOUBLE PRECISION THREXC, THRLEQ, THRENR, THRLDPHF
#endif
      LOGICAL EDIA
      LOGICAL RESTOM,STCCS,R1SKIP,L1SKIP,RESKIP,LESKIP,F1SKIP 
      LOGICAL E0SKIP,M1SKIP,L0SKIP,LISKIP,IMSKIP,FRSKIP,B0SKIP
      LOGICAL ONLY21,MINSCR,MINMEM,MXTOMN,NEWCAU,CCSDT_DIIS
      LOGICAL RCSKIP, FCSKIP, LCSKIP
      LOGICAL O2SKIP, R2SKIP, X2SKIP, F2SKIP, L2SKIP
      LOGICAL CO2SKIP,CX2SKIP,CR2SKIP,CF2SKIP,CL2SKIP
      LOGICAL N2SKIP,BRSKIP, ETADSC
      COMMON /CCLR   / THREXC,THRLEQ,THRENR,THRLDPHF,
     &                 MAXRED,
     &                 EDIA,MAXITE,RESTOM,ISYMTR,ONLY21,STCCS,
     &                 MINSCR,MINMEM,MXTOMN,NEWCAU,CCSDT_DIIS,
     &                 NSIMLE,NCCVAR,R1SKIP,L1SKIP,RESKIP,LESKIP,
     &                 F1SKIP,E0SKIP,M1SKIP,L0SKIP,LISKIP,IMSKIP,
     &                 FRSKIP,B0SKIP, RCSKIP, FCSKIP, LCSKIP,
     &                 O2SKIP, X2SKIP, R2SKIP, F2SKIP, L2SKIP,
     &                 CO2SKIP,CX2SKIP,CR2SKIP,CF2SKIP,CL2SKIP,
     &                 N2SKIP,BRSKIP, ETADSC
#include <ccexcinf.h>
