      INTEGER MXLROP, MBLRFR
      PARAMETER ( MXLROP = 60 , MBLRFR = 60)

      INTEGER NBLRFR, NLRDISP, IPRSOP

      INTEGER NLROP, IALROP, IBLROP, NALROP, NBLROP, OFFALPHA(2)

      LOGICAL DIPPOL,ASYMSD,CAUCHY, LALORX, LBLORX, ALLLRDSPCF
      LOGICAL ALPHA_ISO, ALPHA_ANI

      CHARACTER*(8) CSYM

#if defined (SYS_CRAY)
      REAL ALRFR, BLRFR
#else
      DOUBLE PRECISION ALRFR, BLRFR
#endif

      COMMON /INFPOL/ ALRFR(MBLRFR), BLRFR(MBLRFR),
     *                IALROP(MXLROP),IBLROP(MXLROP),
     *                LALORX(MXLROP),LBLORX(MXLROP),
     *                NALROP(8), NBLROP(8),
     *                DIPPOL,ASYMSD,ALLLRDSPCF,
     *                NBLRFR,CAUCHY,NLRDISP,
     *                NLROP, IPRSOP, OFFALPHA,
     *                ALPHA_ISO, ALPHA_ANI, CSYM


