      INTEGER MXLRSO, MXLRSST
      PARAMETER ( MXLRSO = 60,MXLRSST = 60)

      INTEGER NLRSOP, NXLRSST, NSELRS

      INTEGER IALRSOP, IBLRSOP, ILRSST, ISELRS

      LOGICAL LRS2N1,SELLRS,OSCSTR,VELSTR

      COMMON /INLRSD/ ILRSST(MXLRSST),ISELRS(MXLRSST,2),
     *                IALRSOP(MXLRSO),IBLRSOP(MXLRSO),
     *                NLRSOP,NSELRS,NXLRSST,LRS2N1,SELLRS,
     *                OSCSTR,VELSTR


