C
C$Id: ccom.h,v 1.2 2001-02-12 18:17:55 vebjornb Exp $
C
      LOGICAL DOCART,SPH,SPHNRM
      COMMON /CCOM/ THRS,NHTYP,DOCART,IUTYP,SPHNRM,
     &              KHK(MXQN),KCK(MXQN),SPH(MXQN),NHKOFF(MXQN)
      CHARACTER*4 GTOTYP
      COMMON /CCOMC/ GTOTYP(MXQN*(MXQN+1)*(MXQN+2)/6)
