C
C$Id: ccom.h,v 1.1.1.1 2001-02-08 13:33:25 hjj Exp $
C
      LOGICAL DOCART,SPH
      COMMON /CCOM/ THRS,NHTYP,DOCART,IUTYP,
     &              KHK(MXQN),KCK(MXQN),SPH(MXQN),NHKOFF(MXQN)
      CHARACTER*4 GTOTYP
      COMMON /CCOMC/ GTOTYP(MXQN*(MXQN+1)*(MXQN+2)/6)
