!Common block for Q vectors of Lanczos chain
!Sonia 2010, 2011
!
      INTEGER MAXQLLBL
      PARAMETER (MAXQLLBL = 8000)

      LOGICAL LQLOPN
      INTEGER NQLLBL,ISYOFQL

      LOGICAL LORXQL(MAXQLLBL)
      INTEGER ISYQL(MAXQLLBL), IDXQL(MAXQLLBL)
      CHARACTER*8 LBLQL(MAXQLLBL)

#if defined (SYS_CRAY)
      REAL FRQQL(MAXQLLBL)
#else
      DOUBLE PRECISION FRQQL(MAXQLLBL)
#endif


      COMMON/IQLRSP/ ISYQL, NQLLBL, ISYOFQL(8), LQLOPN, LORXQL, IDXQL
      COMMON/CQLRSP/ LBLQL
      COMMON/RQLRSP/ FRQQL

