C
C$Id: cotabs.h,v 1.1.1.1 2001-02-08 13:33:23 hjj Exp $
C
      DIMENSION ISHLCO(MXCORB),ICMPCO(MXCORB)
      DIMENSION ICSHCM(0:MXSHEL,0:MXAQN)
      COMMON/COTABS/ISHLCO,ICMPCO,ICSHCM,ICOMID,ICOMAX
