C
C$Id: crsdir.h,v 1.1.1.1 2001-02-08 13:33:26 hjj Exp $
C
      LOGICAL         DHCHX, DHCHY,  DHCHZ,  DHCEX, DHCEX1, DHCEX2,
     &                DHCEY, DHCEY1, DHCEY2, DHCEZ, DHCEZ1, DHCEZ2
      COMMON /CRSDIR/ DHCHX, DHCHY,  DHCHZ,  DHCEX, DHCEX1, DHCEX2,
     &                DHCEY, DHCEY1, DHCEY2, DHCEZ, DHCEZ1, DHCEZ2
