      LOGICAL DODRC,DOVWN,DOBCK,DOLYP,DOGGA,DOGRHO,DOLRHO,FROMVX
      COMMON/DFTLBF/DODRC,DOVWN,DOBCK,DOLYP,DOGGA,DOGRHO,DOLRHO,FROMVX
      COMMON/DFTRBF/FACDRC,FACVWN,FACBCK,FACLYP,ELCTRN,
     &              ERGDRC,ERGVWN,ERGBCK,ERGLYP,
     &              ED,EV,EB,EL,VD,VV,VB1,VB2,VL1,VL2,
     &              VDRC1 ,VVWN1 ,FR0BCK,FR0LYP,FZ0BCK,FZ0LYP,FRRDRC,
     &              FRRVWN,FRRBCK,FRRLYP,FRZDRC,FRZVWN,FRZBCK,FRZLYP
      COMMON/DFTIBF/NDER
