C     choose reasonably large MAXBLLEN- so that loop unrolling gives
C     speedup but small compared with a cache size max block length
C     MXBLLEN.
      PARAMETER(MXBLLEN = 100)
c
      CHARACTER*6 DFTTYP
      INTEGER ANGINT, ANGMIN, LEBMIN
      LOGICAL DFTADD, GRDONE, DFTRUN, DFTPOT, DFTORD, DFTASC, DFTHES,
     &        DFTHRS, NOPRUN, DOVWN3, DFTEST, DOVWNI, DFTIMG
      COMMON /DFTCOM/ HFXFAC, DFTHR0, DFTHRL, DFTHRI, DFTELS, RADINT,
     &        ANGINT, ANGMIN, LEBMIN,
     &        DFTADD, GRDONE, DFTRUN, DFTPOT, DFTORD, DFTASC, DFTHES, 
     &        DFTHRS, NOPRUN, DOVWN3, DFTEST, DOVWNI, DFTIMG
      COMMON /DFTCHR/ DFTTYP 
