      CHARACTER*6 DFTTYP
      LOGICAL DFTADD, GRDONE, DFTRUN, DFTPOT, DFTORD, DFTASC, DFTHES,
     &        DFTHRS, DFTEST
      COMMON /DFTCOM/ HFXFAC, DFTADD, GRDONE, DFTRUN, DFTPOT, DFTORD, 
     &                IQDTYP, DFTASC, DFTHES, DFTHRS, DFTEST,
     &                DFTHR0, DFTHRL, DFTHRI, DFTELS
      COMMON /DFTCHR/ DFTTYP 
