      CHARACTER*6 DFTTYP
      INTEGER ANGINT, ANGMIN, LEBMIN
      LOGICAL DFTADD, GRDONE, DFTRUN, DFTPOT, DFTORD, DFTASC, DFTHES,
     &        DFTHRS, NOPRUN
      COMMON /DFTCOM/ HFXFAC, DFTHR0, DFTHRL, DFTHRI, DFTELS, RADINT,
     &        ANGINT, ANGMIN, LEBMIN,
     &        DFTADD, GRDONE, DFTRUN, DFTPOT, DFTORD, DFTASC, DFTHES, 
     &        DFTHRS, NOPRUN
      COMMON /DFTCHR/ DFTTYP 
