C
C$Id: ericom.h,v 1.1.1.1 2001-02-08 13:33:25 hjj Exp $
C
      LOGICAL SAMEPQ, SYMPQ, SAMEAB, SYMAB, SAMECD, SYMCD,
     &        SPHRA,  SPHRB, SPHRC,  SPHRD, SPHRAB, SPHRCD,
     &        DIAGAB, DIAGCD, TKMPAB,TKMPCD,TCMPAB, TCMPCD,
     &        FIRST, LAST, LSTCLS, DIACLS, SYMTRA
      COMMON /ERICOM/ SCRMAB, SCRMCD,
     &                NHKTA,  NHKTB,  NHKTC,  NHKTD,
     &                JMAXA,  JMAXB,  JMAXC,  JMAXD,
     &                JMAXAB, JMAXCD, JMAX,
     &                NTUV,   NTUVAB, NTUVCD,
     &                KHKTA,  KHKTB,  KHKTC,  KHKTD, KHKTAB, KHKTCD,
     &                KCKTA,  KCKTB,  KCKTC,  KCKTD, KCKTAB, KCKTCD,
     &                SPHRA,  SPHRB,  SPHRC,  SPHRD, SPHRAB, SPHRCD,
     &                ISTBLA, ISTBLB, ISTBLC, ISTBLD,
     &                ISTBLR, ISTBLS, ISTBLT,
     &                MLTPA,  MLTPB,  MLTPC,  MLTPD, MLTPX,
     &                MLTPR,  MLTPS,  MLTPT,
     &                NGTOAB, NGTOCD, DIAGAB, DIAGCD,
     &                TKMPAB, TKMPCD, TCMPAB, TCMPCD,
     &                NHKMAX, KCKMAX, KC2MAX, KCREC1,
     &                NPRFAB, NPRFCD, NPRFPQ,
     &                NCTFAB, NCTFCD, NCTFPQ,
     &                NCNTAB, NCNTCD,
     &                NODSAB, NODSCD, NODSPQ,
     &                NODTAB, NODTCD,
     &                KODSAB, KODSCD,
     &                MEMBCH, MAXBCH,
     &                NBCHES, NBTPAS, DIACLS,
     &                NPQBCX, NPPBCX,
     &                NPQBCS, NPPBCS,
     &                NPPX,   NPCX,   NCPX,   NCCX,
     &                NPPS,   NPCS,   NCPS,   NCCS,
     &                NITPQ,
     &                IPQ0(3), IPQXYZ, IAB0(3), IABXYZ, ICD0(3), ICDXYZ,
     &                IHHXYZ, IHCXYZ, ICHXYZ, ICCXYZ,
     &                FIRST,  LAST,  LSTCLS,
     &                MAXDER, IPATH, SYMTRA
