      LOGICAL SAMEPQ, SYMPQ,  SAMEAB, SYMAB, SAMECD, SYMCD,
     &        SPHRA,  SPHRB,  SPHRC,  SPHRD, SPHRAB, SPHRCD,
     &        GCONA,  GCONB,  GCONC,  GCOND, GCONAB, GCONCD, 
     &        DIAGAB, DIAGCD, TKMPAB,TKMPCD,TCMPAB, TCMPCD,
     &        FIRST,  LAST,   LSTCLS, DIACLS, SYMTRA,
     &        DOPTH1, DOPTH2, GDER, NEWDER, BDER,
     &        UNDIFF
      COMMON /ERICOM/ SCRMAB, SCRMCD,
     &                NHKTA,  NHKTB,  NHKTC,  NHKTD,
     &                JMAXA,  JMAXB,  JMAXC,  JMAXD,
     &                JMAXAB, JMAXCD, JMAX,
     &                NTUV,   NTUVAB, NTUVCD,
     &                KHKTA,  KHKTB,  KHKTC,  KHKTD, KHKTAB, KHKTCD,
     &                KCKTA,  KCKTB,  KCKTC,  KCKTD, KCKTAB, KCKTCD,
     &                SPHRA,  SPHRB,  SPHRC,  SPHRD, SPHRAB, SPHRCD,
     &                ISTBLA, ISTBLB, ISTBLC, ISTBLD,
     &                ISTBLR, ISTBLS, ISTBLT,
     &                MLTPA,  MLTPB,  MLTPC,  MLTPD, MLTPX,
     &                MLTPR,  MLTPS,  MLTPT,
     &                NREDZ,  MLTPZ,
     &                NGTOAB, NGTOCD, DIAGAB, DIAGCD,
     &                TKMPAB, TKMPCD, TCMPAB, TCMPCD,
     &                NHKMAX, KCKMAX, KC2MAX, KCREC1, NRDER,
     &                NPRFA,  NPRFB,  NPRFC,  NPRFD,
     &                NPRFAB, NPRFCD, NPRFPQ,
     &                NCTFA,  NCTFB,  NCTFC,  NCTFD, 
     &                NCTFAB, NCTFCD, NCTFPQ,
     &                NCNTAB, NCNTCD,
     &                GCONA,  GCONB,  GCONC,  GCOND, GCONAB, GCONCD,
     &                ICMATA, ICMATB, ICMATC, ICMATD, 
     &                NODSAB, NODSCD, NODSPQ,
     &                NODTAB, NODTCD,
     &                KODSAB, KODSCD,
     &                MEMBCH, MAXBCH,
     &                NBCHES, NBTPAS, DIACLS,
     &                NPQBCX, NPPBCX,
     &                NPQBCS, NPPBCS,
     &                NPPX,   NPCX,   NCPX,   NCCX, NCCT, NAOINT,
     &                NPPS,   NPCS,   NCPS,   NCCS,
     &                NPPAB,  NPPCD,
     &                NITPQ,
     &                IPQ0(3), IPQXYZ, IAB0(3), IABXYZ, ICD0(3), ICDXYZ,
     &                IHHXYZ, IHCXYZ, ICHXYZ, ICCXYZ,
     &                FIRST,  LAST,  LSTCLS, MAXDER, SYMTRA,
     &                DOPTH1, DOPTH2, IPATH, 
     &                GDER,   NCSQ1,  NCSQ2, NEWDER, BDER, DOERP,
     &                IODDPT(3) , NPDIMA, NPDIMB, UNDIFF,  NCORS,
     &                NPERTS
