C
C$Id: exeinf.h,v 1.1.1.1 2001-02-08 13:33:28 hjj Exp $
C
      LOGICAL FTRONV, GTRONV, HTRONV, RTRONV, FTWOXP, SORTXP,
     &                PTRTXP, NPVTXP, FABRHS, FTRCTL
      COMMON /EXEINF/ FTRONV, GTRONV, HTRONV, RTRONV, NASTXP, FTWOXP,
     &                SORTXP, PTRTXP, NPVTXP, FABRHS, FTRCTL, IPTRAB
