      CHARACTER*15 CLASS, FCLASS
      LOGICAL MROTAX, ROTAX2, VPLANE, HPLANE, DPLANE, ICNTR, ROTARE
      COMMON /FCSYM/ NGORDR, NCORDR, NGVERT, NCVERT, NUMELM, NMTRX, 
     &               NONEDI, NDEGIR, N1DIME, NIREP, N2DIME, MROTAX, 
     &               ROTAX2, VPLANE, HPLANE, DPLANE, ICNTR, ROTARE, 
     &               CLASS, FCLASS
       
