C
C$Id: gnrinf.h,v 1.2 2001-02-26 15:34:52 ruud Exp $
C
      LOGICAL TESTIN, OPTWLK,  RNHERM, RNSIRI, RNABAC, GEOCNV,
     &        HRINPC, SRINPC, RDINPC, RDMLIN, PARCAL, DIRCAL,
     &        WRINDX, WLKREJ, WALKIN, RNRESP, USRIPR, SEGBAS,
     &        DOCCSD, OPTNEW, NEWSYM, NEWBAS, NEWPRP, RELCAL,
     &        TOTSYM, NMWALK, DKTRAN
      COMMON /GNRINF/ GRADML, PANAS,  TESTIN, OPTWLK,  RNHERM,
     &                RNSIRI, RNABAC, GEOCNV, HRINPC, SRINPC, RDINPC, 
     &                RDMLIN, PARCAL, DIRCAL, KCHARG, WRINDX, 
     &                WLKREJ, WALKIN, RNRESP, USRIPR, ITERNR,
     &                ITERMX, IPRUSR, SEGBAS, DOCCSD, OPTNEW, NEWSYM,
     &                LENBAS, NEWBAS, NEWPRP, RELCAL, TOTSYM, NMWALK,
     &                DKTRAN
      CHARACTER*70 BASDIR
      COMMON /GNRCHR/ BASDIR
