C
C$Id: infdim.h,v 1.1.1.1 2001-02-08 13:33:26 hjj Exp $
C
      COMMON /INFDIM/ NISHDI,NASHDI,NCONDI,NWOPDI,NISHMA,NASHMA,NSSHMA,
     *                NORBMA,NBASMA,NNBASM,N2BASM,LBUFMA,
     *                NCONMA,NWOPMA,NVARMA,
     *                MWORK, MAXRL, MAXRC, LCINDX,LACIMX,LBCIMX,
     *                MAXPHP,LPHPMX,NOCCMA
