      INTEGER LIROW, JTFRO, JTINAC, JTACT, JTSEC, JTFRFR, JTINFR,
     &        JTACFR, JTSEFR, JTININ, JTACIN, JTACAC, JTSEIN, JTSEAC,
     &        JTSESE
      INTEGER IROW, ISMO, ISAO, ISW, ISX, ICH, LOC, IOBTYP,
     &        NSM, IACTYP, ISSMO, ISSORD
      PARAMETER (LIROW  = 3*MXCORB + 3)
      PARAMETER (JTFRO  = 1, JTINAC = 2, JTACT  = 3, JTSEC  = 4)
      PARAMETER (JTFRFR =-1, JTINFR =-2, JTACFR =-3, JTSEFR =-4,
     &           JTININ = 1, JTACIN = 2, JTACAC = 3, JTSEIN = 4,
     &           JTSEAC = 5, JTSESE = 6)
      COMMON /INFIND/ IROW(LIROW),  ISMO(MXCORB),ISAO(MXCORB),
     &                ISW(MXCORB),  ISX(MXCORB),
     &                ICH(MXCORB),  IOBTYP(MXCORB),
     &                NSM(MAXASH),  IACTYP(MAXASH),
     &                ISSMO(MXCORB),ISSORD(MXCORB)
