C
C$Id: infinp.h,v 1.3 2001-12-13 08:54:39 ruden Exp $
C
      PARAMETER (NFLAG = 80, MAXRTS = 20, MXFELT = 20)
      COMMON /INTINP/ ISPIN,ISTATE,LSYM,NACTEL, MCTYPE,
     *                LSOLMX,NLMSOL,NELMN1,NELMX1,NELMN3,NELMX3,
     *                LROOTS,NROOTS,IROOT(MAXRTS),
     *                NOROT(MAXORB),IMOORD(MAXORB),
     *                IORTO,ICI0,KDEL,ICHECK,NTIT,
     *                MAXMAC,MAXMIC,MAXJT,MAXCIT,MAXUIT,MAXAPM,MAXABS,
     *                MAXFCK, ITRLVL,ITRFIN,JCHSYM,JCHORB,
     *                NROOCI,ISTACI,NFIELD, MXCIMA, ICICNO,IMCCNO,
     *                MXDIIS,MAXEVC
      LOGICAL FLAG,  DORHF, DOMP2, DOCINO,DOCI,  DOMC,  DORSP,FCVORB,
     &        LNOROT,LMOORD,DIRFCK,CORHOL,CORRLX,RESPHP,JOLSEN,ABAIPH,
     &        INERSI,INERSF,SUPSYM, DODFT
      COMMON /LOGINP/ FLAG(NFLAG), DORHF,DOMP2,DOCINO,DOCI,DOMC,DORSP,
     &                FCVORB,LNOROT,LMOORD,DIRFCK,CORHOL,CORRLX,RESPHP,
     &                JOLSEN,ABAIPH,INERSI,INERSF,DODFT
      EQUIVALENCE (SUPSYM,FLAG(17))
      COMMON /RELINP/ SPIN,POTNUC, EPSOL,EPSTAT,EPPN,RSOL(3),
     &                THRGRD, THRPWF, THRRHF, THRCI, THRMC, THRCGR,
     &                EFIELD(MXFELT), TITMOL(12,2), CMAXMO, THROVL,
     &                THRSSY
      CHARACTER*60 TITLE
      CHARACTER*4  CENT,   TYPE
      CHARACTER*8  LFIELD
      COMMON /CHRINP/ TITLE(6), CENT(MAXORB), TYPE(MAXORB),
     &                LFIELD(MXFELT)
