      PARAMETER ( MAXLLR = 60 )
      LOGICAL LLROP, SOPRSY, LQRGP
      CHARACTER*8 LBLLR
      COMMON /INFLR/  THCLR, THRNRM,  IPRLR,  MAXITL, NGPLR(8),
     *                LLROP(MAXLLR), SOPRSY, LRRANK(MAXLLR), LQRGP
      COMMON /CHRLR/  LBLLR(8,MAXLLR)
