      PARAMETER ( MAXTYP = 20 )
      COMMON /INFPOP/ TITLEM(24),DIPOL(3),QPOL(6),QQFAC(3),
     *                IFXYZ(3),JFXYZ(3),NAME(MXCENT),POPNUC(MXCENT),
     *                POPNAB(MXCENT,MXCENT),POPABI(MXCENT,MXCENT),
     *                POPTYP(20,MXCENT),POPTY(20,MXCENT)
