      LOGICAL OPTORB, INPTES, ANTTES ,AVDIA  ,TDHF,   RSPCI,  NOITRA
      LOGICAL ORBSPC, ABOCHK, TRPLET ,OLSEN  ,PHPRES, E3TEST, TRPFLG
      LOGICAL A2TEST, X2TEST, DIROIT, RSPSUP, SOPPA,  HIRPA,  SOPW4
      LOGICAL CCPPA , AOSOP
      PARAMETER ( MFREQ = 30 , MCFREQ = 30 )
      COMMON /INFRSP/ THCRSP, FREQ(MFREQ), CFREQ(MCFREQ), ORBSFT,
     *                OPTORB, INPTES, ANTTES, AVDIA,  TDHF,   RSPCI,
     *                ORBSPC, ABOCHK, TRPLET, OLSEN,  PHPRES,
     *                E3TEST, TRPFLG, A2TEST, X2TEST, DIROIT, RSPSUP,
     *                SOPPA, IREFSY, IPRRSP, MAXIT,  MAXITO,
     *                NFREQ,  NCFREQ, NOITRA, NCREF , ISTOCK, MAXOCK, 
     *                MAXRM, LPVMAT, NACTT,  NACT(8),IACT(8),JACT(8),
     *                HIRPA, SOPW4,   CCPPA  ,AOSOP
