C
C$Id: infsmo.h,v 1.1.1.1 2001-02-08 13:33:25 hjj Exp $
C
      PARAMETER ( MXSMOP = 60 , MBSMFR = 60)
      LOGICAL SOMOM,TWOPHO,ASMOP,BSMOP
      CHARACTER*8 ASMLB,BSMLB
      COMMON /INFSMO/ BSMFR(MBSMFR), NASMOP(8),
     *                NBSMOP(8), NSMCNV(8),
     *                ASMOP(MXSMOP), BSMOP(MXSMOP),
     *                SOMOM,TWOPHO,IPRSMO,NBSMFR
      COMMON /CHRSMO/ ASMLB(8,MXSMOP), BSMLB(8,MXSMOP)
