C
C$Id: inftmo.h,v 1.1.1.1 2001-02-08 13:33:25 hjj Exp $
C
      PARAMETER ( MXTMOP = 60 , MBTMFR = 60, MCTMFR = 60)
      LOGICAL CTMOHG,TOMOM,ATMOP,BTMOP,CTMOP
      CHARACTER*8 ATMLB,BTMLB,CTMLB
      COMMON /INFTMO/ CTMFR(MBTMFR), BTMFR(MBTMFR), NATMOP(8),
     *                NCTMOP(8), NBTMOP(8), NTMCNV(8),
     *                ATMOP(MXTMOP), BTMOP(MXTMOP),CTMOP(MXTMOP),
     *                CTMOHG,TOMOM,IPRTMO,NBTMFR,NCTMFR
      COMMON /CHRTMO/ ATMLB(8,MXTMOP),BTMLB(8,MXTMOP),CTMLB(8,MXTMOP)
