C
C$Id: inpbak.h,v 1.1.1.1 2001-02-08 13:33:24 hjj Exp $
C
C
C     -----------------------------------------------------------------
C
C     The following COMDECKS are used for backup of sirius variables
C
C     /INPBAK/ is a copy of /INFINP/
C
      COMMON /INTBAK/ ISPINB,ISTATB,LSYMB,NACTLB, MCTYPB,
     &                LSLMXB,NLMSLB,NLMN1B,NLMX1B,NLMN3B,NLMX3B,
     &                LROTSB,NROTSB,IROOTB(MAXRTS),
     &                NOROTB(MAXORB),IMORDB(MAXORB),
     &                IORTOB,ICI0B ,KDELB ,ICHCKB,NTITB,
     &                MXMACB,MXMICB,MAXJTB,MXCITB,MXUITB,MXAPMB,
     &                MXABSB,MXFCKB,ITRLVB,ITRFNB,JCHSMB,JCHRBB,
     &                NROCIB,ISTCIB,NFILDB,MXCMAB,ICCNOB,IMCNOB,
     &                MXDISB,MXEVCB
      LOGICAL  FLAGB(NFLAG), DORHFB,DOMP2B,DOCNOB,DOCIB, DOMCB,
     &         DORSPB,FCVRBB,LNROTB,LMORDB,DRFCKB,CORHLB,CRRLXB,
     &         RSPHPB,JOLSNB,ABIPHB,INRSIB,INRSFB,SUPSMB,PRSIRB
      COMMON /LOGBAK/  FLAGB,DORHFB,DOMP2B,DOCNOB,DOCIB, DOMCB,
     &         DORSPB,FCVRBB,LNROTB,LMORDB,DRFCKB,CORHLB,CRRLXB,
     &         RSPHPB,JOLSNB,ABIPHB,INRSIB,INRSFB,SUPSMB,PRSIRB
      COMMON /RELBAK/  SPINB,POTNCB,EPSOLB,EPSTTB,RSOLB(3),
     &                TRGRDB,TRPWFB,TRRHFB,TRCIB,TRMCB,TRCGRB,
     &                EFILDB(MXFELT), TITMLB(12,2), CMXMOB, TROVLB,
     &                TRSSYB
      CHARACTER*60 TITLEB
      CHARACTER*4  CENTB,   TYPEB
      CHARACTER*8  LFILDB
      COMMON /CHRBAK/ TITLEB(6), CENTB(MAXORB), TYPEB(MAXORB),
     &                LFILDB(MXFELT)
