      LOGICAL         MSKIP, MNODC, MNODV, NST, SST, MDIASU, TOFILE,
     &                MCUT, MPOINT, MQUADR, ALLCOM, MNQCC, MELFLD,
     &                DISCHA, MSECND, MOCTUP
      COMMON /MAGONE/ MPRINT, MSKIP, MNODC, MNODV, NST, SST, MDIASU,
     &                TOFILE, MCUT, MPQUAD, MPOINT, MQUADR,
     &                ALLCOM, MNQCC, MELFLD, DISCHA, MSECND, MOCTUP
