C
C$Id: molde.h,v 1.2 2001-02-12 18:17:55 vebjornb Exp $
C
      LOGICAL MOLDEN,DONEIT,DONEIU,DONEIV,DONEIW,DONEIX
      COMMON /molden/ OREN(MAXORB),OROC(MAXORB),EMCEN(MAXORB),
     &          IXYZPRINTS,MOLDEN,DONEIT,DONEIU,DONEIV,DONEIW,DONEIX

C

