C
C$Id: nreqvmc.h,v 1.1.1.1 2001-02-08 13:33:22 hjj Exp $
C
      EQUIVALENCE (KNRLIN( 1),KCMO),  (KNRLIN( 2),KCREF)
      EQUIVALENCE (KNRLIN( 3),KGORB), (KNRLIN( 4),KDV)
      EQUIVALENCE (KNRLIN( 5),KPV),   (KNRLIN( 6),KFC)
      EQUIVALENCE (KNRLIN( 7),KFCAC), (KNRLIN( 8),KH2AC)
      EQUIVALENCE (KNRLIN( 9),KINDEX),(KNRLIN(10),IVEX)
      EQUIVALENCE (KNRLIN(11),KKP),   (KNRLIN(12),KIYP)
      EQUIVALENCE (KNRLIN(13),KFV)
