      INTEGER NUCPRE, NUCNUM, NUCDEG, ISTBNU, 
     &        NUCIND, NUCDEP, NTRACO, ITRACO, NATOMS, NFLOAT,
     &        NBASIS, NLARGE, NSMALL, NPBAS,  NPLRG,  NPSML,
     &        NUCNET, INCENT, INUNIQ, NDEGNM, NODD, ISOTOP
     
#if defined (SYS_CRAY)
      REAL    CHARGE, CORD, GNUEXP
#else
      DOUBLE PRECISION    CHARGE, CORD, GNUEXP
#endif
