C
C$Id: nuclei.h,v 1.1.1.1 2001-02-08 13:33:28 hjj Exp $
C
      CHARACTER*4 NAMN
      LOGICAL NOORBT,GAUNUC
      COMMON /NUCLEI/ CHARGE(MXCENT), CORD(3,MXCENT), NOORBT(MXCENT),
     &                NUCPRE(MXCENT), NUCNUM(MXCENT,8), NUCDEG(MXCENT),
     &                ISTBNU(MXCENT), GNUEXP(MXCENT), NAMN(MXCENT),
     &                NUCIND, NUCDEP, NTRACO, ITRACO(3), NATOMS, NFLOAT,
     &                NBASIS, NLARGE, NSMALL, NPBAS, NPLRG, NPSML,
     &                NUCNET, INCENT(MXCENT),INUNIQ(MXCENT),GAUNUC, NODD
      CHARACTER NAMEX*6, NAMDEP*6, NAMDPX*6
      COMMON /NUCLEC/ NAMEX(MXCOOR), NAMDEP(MXCENT), NAMDPX(MXCOOR),
     &                NDEGNM(MXCENT)
