      INTEGER NUCPRE, NUCNUM, NUCDEG, ISTBNU, 
     &        NUCIND, NUCDEP, NTRACO, ITRACO, NATOMS, NFLOAT,
     &        NBASIS, NLARGE, NSMALL, NPBAS,  NPLRG,  NPSML,
     &        NUCNET, INCENT, INUNIQ, NDEGNM, ISOTOP
#if defined (SYS_CRAY)
      REAL    CHARGE, CORD, GNUEXP
#else
      DOUBLE PRECISION    CHARGE, CORD, GNUEXP
#endif
      LOGICAL NOORBT,GAUNUC
      COMMON /NUCLEI/ CHARGE(MXCENT), CORD(3,MXCENT), GNUEXP(MXCENT),
     &                GAUNUC, NOORBT(MXCENT), NUCPRE(MXCENT),
     &                NUCNUM(MXCENT,8), NUCDEG(MXCENT), ISTBNU(MXCENT), 
     &                NDEGNM(MXCENT), NUCIND, NUCDEP, NTRACO, ITRACO(3),
     &                NATOMS, NFLOAT, NBASIS, NLARGE, NSMALL, NPBAS,
     &                NPLRG, NPSML, NUCNET, INCENT(MXCENT),
     &                INUNIQ(MXCENT), ISOTOP(MXCENT)
      CHARACTER NAMEX*6, NAMDEP*6, NAMDPX*8, NAMN*4
      COMMON /NUCLEC/ NAMEX(MXCOOR), NAMDEP(MXCENT), NAMDPX(MXCOOR),
     &                NAMN(MXCENT)
      INTEGER MULBSI
      COMMON /MULBAS/ MULBSI(MXCENT)
C     MULBAS has been added for multiple basis sets (WK/UniKA/31-10-2002).
