C     
C $Id: numder.h,v 1.3 2001-10-08 18:38:16 vebjornb Exp $
C
      LOGICAL NWPROP, NOMOVE, FSTPRP, NUMELC, CMPARE, SDRTST,
     &        RESTRT, DRYRUN, FRSTNM, PRPVIB, MANUAL, ADSTBK,
     &        NOADSY
      DIMENSION KDRYRN(6)
      COMMON /NUMDER/ KDRYRN, NMORDR, NAORDR, NDCOOR, NMREDU, 
     &                NUMCAL, MEMOFF, NMDPRP, NMRDRP, NARDRP, 
     &                NMPCAL, NMEPRP, LUNDPR, NWPROP, NOMOVE, 
     &                NUMELC, CMPARE, SDRTST, RESTRT, DRYRUN, 
     &                FRSTNM, PRPVIB, MANUAL, ADSTBK, NOADSY
      COMMON /NMDPRP/ NMEXCI, FSTPRP

