C     
C $Id: numder.h,v 1.1.1.1 2001-02-08 13:33:25 hjj Exp $
C
      LOGICAL NWPROP, NOMOVE, FSTPRP, NUMELC, CMPARE, SDRTST,
     &        RESTRT, DRYRUN
      DIMENSION KDRYRN(6)
      COMMON /NUMDER/ KDRYRN, NMORDR, NAORDR, NDCOOR, NMREDU, 
     &                NUMCAL, MEMOFF, NWPROP, NOMOVE, NUMELC, 
     &                CMPARE, SDRTST, RESTRT, DRYRUN 
      COMMON /NMDPRP/ NMEXCI, FSTPRP

