C
C     Property information for calc. of numerical derivatives/vib. averages
C     of properties 
C     Tentative version Ove 250899
C
      CHARACTER*8 LAB0, LAB1, LAB2, LAB3
      CHARACTER*10 CPRPC
      CHARACTER*8 LAB0O, LAB1O, LAB2O, LAB3O
      CHARACTER*10 CPRPCO
      PARAMETER (MXPRPC=200)
      PARAMETER (THRZEP=1.0D-10)
      COMMON /IPROPS/ NPRPC, IOPRPC(MXPRPC), ISAVSY(MXPRPC)
      COMMON /PROPS/ PRPC(MXPRPC),FRQ1(MXPRPC),FRQ2(MXPRPC),
     *               FRQ3(MXPRPC)
      COMMON /CPROPS/ CPRPC(MXPRPC),LAB0(MXPRPC),LAB1(MXPRPC),
     *                LAB2(MXPRPC),LAB3(MXPRPC)
      COMMON /IPROPSO/ NPRPCO, IOPRPCO(MXPRPC), ISAVSYO(MXPRPC)
      COMMON /PROPSO/ PRPCO(MXPRPC),FRQ1O(MXPRPC),FRQ2O(MXPRPC),
     *               FRQ3O(MXPRPC)
      COMMON /CPROPSO/ CPRPCO(MXPRPC),LAB0O(MXPRPC),LAB1O(MXPRPC),
     *                LAB2O(MXPRPC),LAB3O(MXPRPC)
