C --- FILE: qmmm.h ---
C
      LOGICAL SPLDIP,CONMAT,FIXDIP,MMDAMP,MMPROP,
     *        SPLNMR,MMMAT,MMITER,MMDIIS,LCLOSE,
     *        LMMNUL,MEP,ZEROOC
C 
      PARAMETER(MXMMCT = 90000)
      PARAMETER(MXEXCL = 20)
      PARAMETER ( THRMM = 1.0D-10 )

      INTEGER MMCENT,NMULT,IPOLTP,NEXLST,EXLIST,
     *        ZEROAL,NNZAL,IDAMP,NQMNUC,MXMMIT,
     *        MXMMDI,NMMAC,IQMMMC,
     *        NELEME,ELEME
C
#if defined (SYS_CRAY)
      REAL MMCORD, MUL0MM, MUL1MM, MUL2MM, MUL3MM, 
     *     POLMM, POLIMM, THRMM, QMPOL, THMMIT, RQMMMC, 
     *     RCUTMM,DELFLD
#else
      DOUBLE PRECISION MMCORD, MUL0MM, MUL1MM, MUL2MM, MUL3MM,
     *                 POLMM, POLIMM, THRMM, QMPOL, THMMIT,
     *                 RQMMMC, RCUTMM,DELFLD
#endif

      COMMON /REQMMM/ MMCORD(3,MXMMCT), MUL0MM(MXMMCT), 
     *                MUL1MM(3,MXMMCT), MUL2MM(6,MXMMCT),
     *                MUL3MM(10,MXMMCT),
     *                POLMM(6,MXMMCT), POLIMM(MXMMCT), 
     *                QMPOL(MXCENT) , THMMIT, RQMMMC, RCUTMM,
     *                DELFLD

      COMMON /LOQMMM/ SPLDIP,CONMAT,FIXDIP,MMDAMP,MMPROP,
     *                SPLNMR,MMMAT,MMITER,MMDIIS,LCLOSE,
     *                LMMNUL(MXMMCT),MEP,ZEROOC

      COMMON /INQMMM/ MMCENT,NMULT,IPOLTP,NEXLST,
     *                EXLIST(MXEXCL,MXMMCT),ZEROAL(MXMMCT),
     *                NNZAL,IDAMP,NQMNUC,MXMMIT,MXMMDI,
     *                NMMAC,IQMMMC,NELEME,ELEME(MXMMCT)

C --- end of qmmm.h ---
