      INTEGER MZVAR, MZYVAR, MZCONF, MZYCON, MZWOPT, MZYWOP, MSYMA, 
     &        MSYMB, MSYMC, MZYVMX, MZWOPH, MZVARH
      LOGICAL QRREST
      COMMON /QRINF/  MZVAR(8), MZYVAR(8), MZCONF(8),
     *                MZYCON(8), MZWOPT(8), MZYWOP(8), MSYMA ,MSYMB ,
     *                MSYMC, MZYVMX, MZWOPH(8),MZVARH(8),
     *                QRREST
