      INTEGER MXMULB
      PARAMETER (MXMULB = 2)
C
C     The next parameters indicates the number of integer and
C     logical variables to be transferred in a parallel calculation.
C     Must be updated if COMR12 is changed. Note: Order of variables in
C     COMR12 must not be changed.
C
      INTEGER NR12I, NR12L, IANR12, IAPR12, MAXGAM, XMIADR
      PARAMETER (NR12I = 30, NR12L = 40)
      PARAMETER (MAXGAM = 50)
      LOGICAL R12INT, R12TRA, U12INT, U21INT, R12SQR,
     *        R12CAL, R12NOA, R12NOP, R12NOB, R12OLD, NORXR,
     *        R12HYB, COMBSS, R12EIN, R12EOR, R12ECO, R12XXL,
     *        V12INT, NOTR12, NOTU12, NOTV12, XXXXXX, CC2R12INT,
     *        ANTICO, DIRSCF, U12DIR, R12DIR, LOOPDP, ONEAUX,
     *        V12DIR, STEPIV, DCCR12, CUSP12, DUMR12, CCPAIR,
     *        NOTONE, NOTTWO, CCSDR12INT, R12CBS, NOBP, SLATER,
     *        MIAU12, AENONB, NOTTRE,CCR12SM
      LOGICAL LMULBS, LAUXBS, R12DIA, R12SVD, R12RST, NOAUXB, R12PRP,
     *        NATVIR
      INTEGER NMULBS, MBAS1(8), MBAS2(8), LU21INT, IOFFU21,
     *                NORB1(8), NORB2(8), MBSMAX, NTOGAM, NRXR12(8),
     *                IANCC2, IAPCC2, LOCFRO(8)
      CHARACTER*80 MULNAM(MXMULB)
      CHARACTER*8 LABEL
#if defined (SYS_CRAY)
      REAL GAMAC, GAMAD, GAMAB, GAMAX
      REAL BRASCL,KETSCL
#else
      DOUBLE PRECISION GAMAC, GAMAD, GAMAB, GAMAX
      DOUBLE PRECISION BRASCL,KETSCL
#endif
      CHARACTER*10 FNVAJKL
      INTEGER INTGAC, INTGAD, IADV12, IADR12, IADU12, IADU21,
     *        NOPP12, NPLSH
      COMMON /COMR12/ GAMAC, GAMAD, R12INT, R12TRA, U12INT, 
     *        U21INT, R12SQR, R12CAL, R12NOA, R12NOP, R12NOB, 
     *        R12OLD, NORXR, R12HYB, COMBSS, R12EIN,
     *        R12EOR, R12ECO, R12XXL, V12INT, NOTR12, NOTU12, 
     *        NOTV12, ANTICO, DIRSCF, U12DIR, R12DIR, V12DIR, 
     *        STEPIV, DCCR12, CUSP12, DUMR12,
     *        INTGAC, INTGAD, IADV12, IADR12, IADU12, IADU21, NOPP12,
     *        CCPAIR, XXXXXX, CC2R12INT, LOOPDP, ONEAUX,
     *        R12DIA, R12SVD, R12RST, R12PRP, LU21INT, IOFFU21,
     *        IANR12, IAPR12, NOTONE, NOTTWO,CCSDR12INT, R12CBS, NOBP,
     *        NTOGAM, GAMAB(MAXGAM), GAMAX(MAXGAM), SLATER,
     *        XMIADR, MIAU12, AENONB, NRXR12, NOTTRE, IANCC2, IAPCC2,
     *        LOCFRO, NATVIR,CCR12SM
      COMMON /R12FNS/ FNVAJKL
      REAL*8 VCLTHR, SVDTHR, R12LEV
      COMMON /COMVCL/ VCLTHR, SVDTHR, R12LEV
      COMMON /CMMBAS/ LMULBS, NMULBS, NOAUXB
      COMMON /CMMMUL/ MULNAM, NPLSH, MBAS1, MBAS2, LAUXBS,
     *                NORB1, NORB2, MBSMAX
      COMMON /CMMOLL/ LABEL
      COMMON /R12SCALE/ BRASCL, KETSCL
