C
C$Id: scbrhf.h,v 1.1.1.1 2001-02-08 13:33:24 hjj Exp $
C
      LOGICAL RHFCAN, AUTOCC
      COMMON /SCBRHF/ NFRRHF(8),NMVO(8),NMVOT,IOPRHF,MXHFMA,MXHFMI,
     &                NRHFEL,INIOCC, RHFCAN,AUTOCC
