      LOGICAL DOSD, DODSO, DOFC, DOSDFC, DOPSO, DOSELE, ANISON,
     &        FCFIN, SPNISO
      COMMON /SPNOUT/ ABUND, ISPPRI, DOSD, DODSO, DOFC, DOPSO,
     &                DOSDFC, DOSELE, ANISON, FCFIN, SPNISO
