C
C$Id: strnum.h,v 1.1.1.1 2001-02-08 13:33:29 hjj Exp $
C
      LOGICAL EQUAL
      COMMON/STRNUM/NAEL,NBEL,NAEXCI,NBEXCI,NASTR,NBSTR,EQUAL,
     &              MAXSYM,NORB1,NORB2,NORB3,NOCTPA,IOCPTA(MXOCTP),
     &              NSTAOA(MXOCTP),IOCPTB(MXOCTP),NSTAOB(MXOCTP),
     &              NOCTPB,NL1MNA,NL1MNB,NL3MNA,NL3MNB
