      LOGICAL NONADI, TRAMOM, WAVEOV, SYMORT, SHAKE, MOMTYP(10),
     1        REDUCE, FROZEN, OCEINT, CICALC
      COMMON /WESINF/ DISPL, POTNUV(2), EMCWES(2,2),
     1   SPIN1,  SPIN2, DELQ(100,3), CENTOP(3),
     2   NCONF1, NCONF2, LSYM1,  LSYM2,  LSPIN1, LSPIN2, NSTAT2, NGEOM,
     3   ISTATV(2,2), IRDMOW, NMAXD,
     4   IPRDEF, IPRNAD, IPRTRM, IPRBIO, IPRMLC, IPRSHK, IACFLG, IACSYM,
     5   IACORB, REDUCE, NONADI, TRAMOM, MOMTYP, WAVEOV, SYMORT, SHAKE,
     6   FROZEN, OCEINT, CICALC, ICIORD(40)
