      LOGICAL LRSTVE,RESTPP,ABCHK,ABSYM,RESTLR,RESTC6,DETERM
      COMMON /WRKRSP/ AFREQ,  
     *                KSYMOP, KZVAR,  KZYVAR, KZCONF, KZYCON, KZWOPT, 
     *                KZYWOP, KZRED , KZYRED, KEXCNV, KEXSIM, KEXSTV,
     *                KLRSTV, JEXSIM, KOFFTY, KCONV,  KSYMST, LRSTVE,
     *                RESTPP, ABCHK,  ABSYM,  RESTLR, RESTC6, DETERM
