      LOGICAL LRSTVE,RESTPP,ABCHK,ABSYM,RESTLR,RESTC6,DETERM
      COMMON /WRKRSP/ KSYMOP, KZVAR,  KZYVAR, KZCONF, KZYCON, KZWOPT,
     *                KZYWOP, KZRED , KZYRED, KEXCNV, KEXSIM, KEXSTV,
     *                KLRSTV, JEXSIM, KOFFTY, KCONV,  AFREQ,
     *                LRSTVE, RESTPP, KSYMST, ABCHK,  ABSYM,
     *                RESTLR, RESTC6, DETERM
