#!/usr/bin/env python


import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'DIPLEN  >>',
      rel_tolerance = 1.0e-7,
      ignore_below = 1.0e-5)

test.run(['lda.dal', 'b3lyp.dal'], ['aug-dz.mol'], f={'out': f})

sys.exit(test.return_code)
