#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(from_string = 'Polarizable embedding energy contributions:',
      num_lines = 32,
      abs_tolerance = 1.0e-6)

test.run(['pehf_damp_core.dal'], ['pehf_damp_core.mol'], ['pehf_damp_core.pot'], f={'out': f})

sys.exit(test.return_code)
