#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..','..','tools',))

from runtest_lsdalton import Filter, TestRun
from output_parser import *

test = TestRun(__file__, sys.argv)

# Input files:
# ============
DAL = "decmp2_energy"
MOL = "CO2H2"

f = Filter()
f.add(string = 'Final HF energy',
              rel_tolerance = 1.0e-8)

f.add(from_string = 'Print single and pair fragment energies',
              to_string   = 'MP2 Lagrangian correlation energy',
                    abs_tolerance = 1.0e-4)

f.add(string = 'Correlation energy',
              rel_tolerance = 1.0e-3)

f.add(string = 'Allocated memory (TOTAL)')

test.run([DAL+'.dal'], [MOL+'.mol'], {'out': f})


name = "_".join([DAL,MOL])

#---------------------------------------------
# Test LSDalton Output parser script
decmp2 = lsoutput(name+'.out')

decinfo = open(name+'.dec','w')
decmp2.decinfo.print_dec_info(decinfo)
decinfo.close()


f2 = Filter()
f2.add(from_string = 'MP2     occupied correlation energy',
       num_lines = 35,
       abs_tolerance = 1.0e-3)

test.skip_run = True

test.run([DAL+'.dal'], [MOL+'.mol'], {'dec': f2})
#---------------------------------------------

sys.exit(test.return_code)


