#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from runtest_lsdalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final HF energy',
      rel_tolerance = 1.0e-6)

f.add(string = 'Correlation energy',
      rel_tolerance = 3.0e-3) # taking accumulation into account

f.add(from_string = 'CCSD occupied correlation energy',
      to_string   = 'Total CCSD(T) occupied correlation energy',
      abs_tolerance = 1.0e-3)

f.add(string = 'Allocated memory (TOTAL)')

f.add(string = 'Allocated MPI memory a cross all slaves')

test.run(['decccsdpt_fragopt.dal'], ['ethylene.mol'], {'out': f})

sys.exit(test.return_code)
