#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > HCN_ddyn.info <<'%EOF%'
   HCN_ddyn
   -------------
   Molecule:         HCN
   Wave Function:    HF / STO-3G
   Test Purpose:     Test direct dynamics of HCN reactive trajectory 
   with basic input
                     
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > HCN_ddyn.mol <<'%EOF%'
BASIS
STO-3G
HCN trajectory
Coordinates and velocities obtained from sampling at 298K
    3    0
        1.    1
H   -1.940417034197    0.545763720338    0.000000000000
        6.    1
C    0.072376937428    1.193815751086    0.000000000000
        7.    1
N    0.077631355767   -1.062325554101    0.000000000000
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > HCN_ddyn.dal <<'%EOF%'
**DYNAMI
.NUMTRA
1
.VERLET
.TIMESTEP
0.1
.MAX ITER
10
.MWVEL
.VELOCI
3
-6.608362194660D-2   -3.062517636631D-3    4.547762402073D-2
-1.933563923674D-2    5.775468947979D-2   -2.503355504136D-2
 3.562796972853D-2   -5.264298483819D-2    1.097349580796D-2
**WAVE FUNCTIONS
.HF
*DENSOPT
.RESTART
.CONVTHR
1.0d-5
*END OF INPUT
%EOF%
#######################################################################

 

#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL > HCN_ddyn.check
cat >> HCN_ddyn.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# Energy
CRIT1=`$GREP "Final * HF energy\: * \-91\.5638493" $log | wc -l`
TEST[1]=`expr   $CRIT1`
CTRL[1]=1
ERROR[1]="HF ENERGY NOT CORRECT -"

# Energy
#CRIT1=`$GREP "Energy drift, mHartree/ps  :  \-4509\.091" $log | wc -l`
CRIT1=`$GREP "Energy drift, mHartree/ps  :  \-4478\.182" $log | wc -l`
TEST[2]=`expr   $CRIT1`
CTRL[2]=1
ERROR[2]="Energy drift -"

# Memory test
CRIT1=`$GREP "Allocated memory \(TOTAL\): * 0 byte" $log | wc -l`
TEST[3]=`expr  $CRIT1`
CTRL[3]=1
ERROR[3]="Memory leak -"

PASSED=1
for i in 1 2 3
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo ${ERROR[i]}
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
