MODULE IchorEriCoulombintegralGPUOBSGeneralModSegPSize
!Automatic Generated Code (AGC) by runOBSdriver.f90 in tools directory
!Contains routines for Segmented contracted LHS and a General Contracted RHS Basisset 
use IchorCommonMod
  
private   
public :: ICI_GPU_OBS_general_sizeSegP  
  
CONTAINS
  
  subroutine ICI_GPU_OBS_general_sizeSegP(TMParray1maxsize,&
         & TMParray2maxsize,AngmomA,AngmomB,AngmomC,AngmomD,nContA,nContB,nContC,nContD,&
         & nPrimA,nPrimB,nPrimC,nPrimD,nPrimP,nPrimQ,nContP,nContQ,nPrimQP,nContQP)
    implicit none
    integer,intent(inout) :: TMParray1maxsize,TMParray2maxsize
    integer,intent(in) :: AngmomA,AngmomB,AngmomC,AngmomD
    integer,intent(in) :: nPrimP,nPrimQ,nContP,nContQ,nPrimQP,nContQP
    integer,intent(in) :: nContA,nContB,nContC,nContD
    integer,intent(in) :: nPrimA,nPrimB,nPrimC,nPrimD
    ! local variables
    integer :: AngmomID
    
    AngmomID = 1000*AngmomA+100*AngmomB+10*AngmomC+AngmomD
    IF(UseGeneralCode) AngmomID = AngmomID + 10000 !force to use general code
    TMParray2maxSize = 1
    TMParray1maxSize = 1
    SELECT CASE(AngmomID)
    CASE(   0)  !Angmom(A= 0,B= 0,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,1*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,1*nContC*nPrimD)
    CASE(   1)  !Angmom(A= 0,B= 0,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,4*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,4*nContC*nContD)
    CASE(   2)  !Angmom(A= 0,B= 0,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQ)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nPrimD)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD)
       TMParray2maxSize = MAX(TMParray2maxSize,6*nContQ)
    CASE(  10)  !Angmom(A= 0,B= 0,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,4*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,4*nContC*nContD)
    CASE(  11)  !Angmom(A= 0,B= 0,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQ)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nPrimD)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD)
    CASE(  12)  !Angmom(A= 0,B= 0,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQ)
    TMParray2maxSize = MAX(TMParray2maxSize,20*nContC*nPrimD)
    TMParray1maxSize = MAX(TMParray1maxSize,20*nContC*nContD)
       TMParray2maxSize = MAX(TMParray2maxSize,18*nContQ)
    CASE(  20)  !Angmom(A= 0,B= 0,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQ)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nPrimD)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD)
       TMParray2maxSize = MAX(TMParray2maxSize,6*nContQ)
    CASE(  21)  !Angmom(A= 0,B= 0,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQ)
    TMParray2maxSize = MAX(TMParray2maxSize,20*nContC*nPrimD)
    TMParray1maxSize = MAX(TMParray1maxSize,20*nContC*nContD)
       TMParray2maxSize = MAX(TMParray2maxSize,18*nContQ)
    CASE(  22)  !Angmom(A= 0,B= 0,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQ)
    TMParray2maxSize = MAX(TMParray2maxSize,35*nContC*nPrimD)
    TMParray1maxSize = MAX(TMParray1maxSize,35*nContC*nContD)
       TMParray2maxSize = MAX(TMParray2maxSize,36*nContQ)
    CASE( 100)  !Angmom(A= 0,B= 1,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,4*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,4*nContC*nContD)
    CASE( 101)  !Angmom(A= 0,B= 1,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,16*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,16*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,16*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,12*nContQ)
    CASE( 102)  !Angmom(A= 0,B= 1,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,18*nContQ)
    CASE( 110)  !Angmom(A= 0,B= 1,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,16*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,16*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,16*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,12*nContQ)
    CASE( 111)  !Angmom(A= 0,B= 1,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQ)
    CASE( 112)  !Angmom(A= 0,B= 1,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,80*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,54*nContQ)
    CASE( 120)  !Angmom(A= 0,B= 1,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,18*nContQ)
    CASE( 121)  !Angmom(A= 0,B= 1,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,80*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,54*nContQ)
    CASE( 122)  !Angmom(A= 0,B= 1,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,140*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,140*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,140*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,105*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,108*nContQ)
    CASE( 200)  !Angmom(A= 0,B= 2,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQ)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nPrimD)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD)
       TMParray2maxSize = MAX(TMParray2maxSize,6*nContQ)
    CASE( 201)  !Angmom(A= 0,B= 2,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,24*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,20*nContQ)
    CASE( 202)  !Angmom(A= 0,B= 2,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,50*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQ)
    CASE( 210)  !Angmom(A= 0,B= 2,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,24*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,20*nContQ)
    CASE( 211)  !Angmom(A= 0,B= 2,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,50*nContQ)
    CASE( 212)  !Angmom(A= 0,B= 2,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,120*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQ)
    CASE( 220)  !Angmom(A= 0,B= 2,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,50*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQ)
    CASE( 221)  !Angmom(A= 0,B= 2,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,120*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQ)
    CASE( 222)  !Angmom(A= 0,B= 2,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,350*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,210*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,175*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQ)
    CASE(1000)  !Angmom(A= 1,B= 0,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,4*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,4*nContC*nContD)
    CASE(1001)  !Angmom(A= 1,B= 0,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,16*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,16*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,16*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,12*nContQ)
    CASE(1002)  !Angmom(A= 1,B= 0,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,18*nContQ)
    CASE(1010)  !Angmom(A= 1,B= 0,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,16*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,16*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,16*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,12*nContQ)
    CASE(1011)  !Angmom(A= 1,B= 0,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQ)
    CASE(1012)  !Angmom(A= 1,B= 0,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,80*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,54*nContQ)
    CASE(1020)  !Angmom(A= 1,B= 0,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,18*nContQ)
    CASE(1021)  !Angmom(A= 1,B= 0,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,80*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,54*nContQ)
    CASE(1022)  !Angmom(A= 1,B= 0,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,140*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,140*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,140*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,105*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,108*nContQ)
    CASE(1100)  !Angmom(A= 1,B= 1,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQ)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nPrimD)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD)
    CASE(1101)  !Angmom(A= 1,B= 1,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,36*nContQ)
    CASE(1102)  !Angmom(A= 1,B= 1,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,54*nContQ)
    CASE(1110)  !Angmom(A= 1,B= 1,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,36*nContQ)
    CASE(1111)  !Angmom(A= 1,B= 1,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQ)
    CASE(1112)  !Angmom(A= 1,B= 1,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,162*nContQ)
    CASE(1120)  !Angmom(A= 1,B= 1,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,54*nContQ)
    CASE(1121)  !Angmom(A= 1,B= 1,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,162*nContQ)
    CASE(1122)  !Angmom(A= 1,B= 1,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,350*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,315*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,324*nContQ)
    CASE(1200)  !Angmom(A= 1,B= 2,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQ)
    TMParray2maxSize = MAX(TMParray2maxSize,20*nContC*nPrimD)
    TMParray1maxSize = MAX(TMParray1maxSize,20*nContC*nContD)
       TMParray2maxSize = MAX(TMParray2maxSize,18*nContQ)
    CASE(1201)  !Angmom(A= 1,B= 2,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,80*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,72*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,60*nContQ)
    CASE(1202)  !Angmom(A= 1,B= 2,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,150*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQ)
    CASE(1210)  !Angmom(A= 1,B= 2,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,80*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,72*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,60*nContQ)
    CASE(1211)  !Angmom(A= 1,B= 2,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,150*nContQ)
    CASE(1212)  !Angmom(A= 1,B= 2,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,400*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,400*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,400*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,360*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,300*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,270*nContQ)
    CASE(1220)  !Angmom(A= 1,B= 2,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,150*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQ)
    CASE(1221)  !Angmom(A= 1,B= 2,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,400*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,400*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,400*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,360*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,300*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,270*nContQ)
    CASE(1222)  !Angmom(A= 1,B= 2,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,8*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,120*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,700*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,700*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,700*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,630*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,525*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,540*nContQ)
    CASE(2000)  !Angmom(A= 2,B= 0,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQ)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nPrimD)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD)
       TMParray2maxSize = MAX(TMParray2maxSize,6*nContQ)
    CASE(2001)  !Angmom(A= 2,B= 0,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,24*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,20*nContQ)
    CASE(2002)  !Angmom(A= 2,B= 0,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,50*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQ)
    CASE(2010)  !Angmom(A= 2,B= 0,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,24*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,20*nContQ)
    CASE(2011)  !Angmom(A= 2,B= 0,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,50*nContQ)
    CASE(2012)  !Angmom(A= 2,B= 0,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,120*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQ)
    CASE(2020)  !Angmom(A= 2,B= 0,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,50*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQ)
    CASE(2021)  !Angmom(A= 2,B= 0,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,120*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQ)
    CASE(2022)  !Angmom(A= 2,B= 0,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,350*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,210*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,175*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQ)
    CASE(2100)  !Angmom(A= 2,B= 1,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQ)
    TMParray2maxSize = MAX(TMParray2maxSize,20*nContC*nPrimD)
    TMParray1maxSize = MAX(TMParray1maxSize,20*nContC*nContD)
       TMParray2maxSize = MAX(TMParray2maxSize,18*nContQ)
    CASE(2101)  !Angmom(A= 2,B= 1,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,80*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,72*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,60*nContQ)
    CASE(2102)  !Angmom(A= 2,B= 1,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,150*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQ)
    CASE(2110)  !Angmom(A= 2,B= 1,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,80*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,72*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,60*nContQ)
    CASE(2111)  !Angmom(A= 2,B= 1,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,150*nContQ)
    CASE(2112)  !Angmom(A= 2,B= 1,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,400*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,400*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,400*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,360*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,300*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,270*nContQ)
    CASE(2120)  !Angmom(A= 2,B= 1,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,150*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQ)
    CASE(2121)  !Angmom(A= 2,B= 1,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,400*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,400*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,400*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,360*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,300*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,270*nContQ)
    CASE(2122)  !Angmom(A= 2,B= 1,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,8*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,120*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,700*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,700*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,700*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,630*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,525*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,540*nContQ)
    CASE(2200)  !Angmom(A= 2,B= 2,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQ)
    TMParray2maxSize = MAX(TMParray2maxSize,35*nContC*nPrimD)
    TMParray1maxSize = MAX(TMParray1maxSize,35*nContC*nContD)
       TMParray2maxSize = MAX(TMParray2maxSize,36*nContQ)
    CASE(2201)  !Angmom(A= 2,B= 2,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,140*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,140*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,140*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,144*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nContQ)
    CASE(2202)  !Angmom(A= 2,B= 2,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,350*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,360*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,250*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,150*nContQ)
    CASE(2210)  !Angmom(A= 2,B= 2,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,140*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,140*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,140*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,144*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nContQ)
    CASE(2211)  !Angmom(A= 2,B= 2,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,350*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,360*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,250*nContQ)
    CASE(2212)  !Angmom(A= 2,B= 2,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,8*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,120*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,700*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,700*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,700*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,720*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,500*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,450*nContQ)
    CASE(2220)  !Angmom(A= 2,B= 2,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,350*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,360*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,250*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,150*nContQ)
    CASE(2221)  !Angmom(A= 2,B= 2,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,8*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,120*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,700*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,700*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,700*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,720*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,500*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,450*nContQ)
    CASE(2222)  !Angmom(A= 2,B= 2,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,9*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,165*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,1225*nPrimQ)
    TMParray1maxSize = MAX(TMParray1maxSize,1225*nContC*nPrimD)
    TMParray2maxSize = MAX(TMParray2maxSize,1225*nContC*nContD)
       TMParray1maxSize = MAX(TMParray1maxSize,1260*nContQ)
       TMParray2maxSize = MAX(TMParray2maxSize,875*nContQ)
       TMParray1maxSize = MAX(TMParray1maxSize,900*nContQ)
    CASE DEFAULT
        CALL ICHORQUIT('Unknown Case in ICI_OBS_general_size',-1)
    END SELECT
  end subroutine ICI_GPU_OBS_general_sizeSegP
END MODULE IchorEriCoulombintegralGPUOBSGeneralModSegPSize
