module SPIchorEriCoulombintegralGPUOBSGeneralModGenSize
!Automatic Generated Code (AGC) by runOBSdriver.f90 in tools directory
!Contains routines for General Contracted Basisset 
use IchorCommonMod
  
private   
public :: SPICI_GPU_OBS_general_sizeGen  
  
CONTAINS
  
  subroutine SPICI_GPU_OBS_general_sizeGen(TMParray1maxsize,&
         & TMParray2maxsize,AngmomA,AngmomB,AngmomC,AngmomD,nContA,nContB,nContC,nContD,&
         & nPrimA,nPrimB,nPrimC,nPrimD,nPrimP,nPrimQ,nContP,nContQ,nPrimQP,nContQP)
    implicit none
    integer,intent(inout) :: TMParray1maxsize,TMParray2maxsize
    integer,intent(in) :: AngmomA,AngmomB,AngmomC,AngmomD
    integer,intent(in) :: nPrimP,nPrimQ,nContP,nContQ,nPrimQP,nContQP
    integer,intent(in) :: nContA,nContB,nContC,nContD
    integer,intent(in) :: nPrimA,nPrimB,nPrimC,nPrimD
    ! local variables
    integer :: AngmomID
    
    AngmomID = 1000*AngmomA+100*AngmomB+10*AngmomC+AngmomD
    IF(UseGeneralCode) AngmomID = AngmomID + 10000 !force to use general code
    TMParray2maxSize = 1
    TMParray1maxSize = 1
    SELECT CASE(AngmomID)
    CASE(   0)  !Angmom(A= 0,B= 0,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,1*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,1*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,1*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,1*nContC*nContD*nContA*nPrimB)
    CASE(   1)  !Angmom(A= 0,B= 0,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,4*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,4*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,4*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,4*nContC*nContD*nContA*nContB)
    CASE(   2)  !Angmom(A= 0,B= 0,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQP)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nPrimD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nContD*nContA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD*nContA*nContB)
       TMParray2maxSize = MAX(TMParray2maxSize,6*nContQP)
    CASE(  10)  !Angmom(A= 0,B= 0,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,4*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,4*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,4*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,4*nContC*nContD*nContA*nContB)
    CASE(  11)  !Angmom(A= 0,B= 0,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQP)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nPrimD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nContD*nContA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD*nContA*nContB)
    CASE(  12)  !Angmom(A= 0,B= 0,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
    TMParray2maxSize = MAX(TMParray2maxSize,20*nContC*nPrimD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,20*nContC*nContD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,20*nContC*nContD*nContA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,20*nContC*nContD*nContA*nContB)
       TMParray2maxSize = MAX(TMParray2maxSize,18*nContQP)
    CASE(  20)  !Angmom(A= 0,B= 0,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQP)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nPrimD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nContD*nContA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD*nContA*nContB)
       TMParray2maxSize = MAX(TMParray2maxSize,6*nContQP)
    CASE(  21)  !Angmom(A= 0,B= 0,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
    TMParray2maxSize = MAX(TMParray2maxSize,20*nContC*nPrimD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,20*nContC*nContD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,20*nContC*nContD*nContA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,20*nContC*nContD*nContA*nContB)
       TMParray2maxSize = MAX(TMParray2maxSize,18*nContQP)
    CASE(  22)  !Angmom(A= 0,B= 0,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
    TMParray2maxSize = MAX(TMParray2maxSize,35*nContC*nPrimD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,35*nContC*nContD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,35*nContC*nContD*nContA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,35*nContC*nContD*nContA*nContB)
       TMParray2maxSize = MAX(TMParray2maxSize,36*nContQP)
    CASE( 100)  !Angmom(A= 0,B= 1,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,4*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,4*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,4*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,4*nContC*nContD*nContA*nContB)
    CASE( 101)  !Angmom(A= 0,B= 1,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,16*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,16*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,16*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,16*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,16*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,12*nContQP)
    CASE( 102)  !Angmom(A= 0,B= 1,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,18*nContQP)
    CASE( 110)  !Angmom(A= 0,B= 1,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,16*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,16*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,16*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,16*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,16*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,12*nContQP)
    CASE( 111)  !Angmom(A= 0,B= 1,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQP)
    CASE( 112)  !Angmom(A= 0,B= 1,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,80*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,54*nContQP)
    CASE( 120)  !Angmom(A= 0,B= 1,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,18*nContQP)
    CASE( 121)  !Angmom(A= 0,B= 1,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,80*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,54*nContQP)
    CASE( 122)  !Angmom(A= 0,B= 1,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,140*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,140*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,140*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,140*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,140*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,105*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,108*nContQP)
    CASE( 200)  !Angmom(A= 0,B= 2,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQP)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nPrimD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nContD*nContA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD*nContA*nContB)
       TMParray2maxSize = MAX(TMParray2maxSize,6*nContQP)
    CASE( 201)  !Angmom(A= 0,B= 2,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,24*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,20*nContQP)
    CASE( 202)  !Angmom(A= 0,B= 2,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,50*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQP)
    CASE( 210)  !Angmom(A= 0,B= 2,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,24*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,20*nContQP)
    CASE( 211)  !Angmom(A= 0,B= 2,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,50*nContQP)
    CASE( 212)  !Angmom(A= 0,B= 2,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,120*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQP)
    CASE( 220)  !Angmom(A= 0,B= 2,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,50*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQP)
    CASE( 221)  !Angmom(A= 0,B= 2,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,120*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQP)
    CASE( 222)  !Angmom(A= 0,B= 2,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,350*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,210*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,175*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQP)
    CASE(1000)  !Angmom(A= 1,B= 0,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,4*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,4*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,4*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,4*nContC*nContD*nContA*nContB)
    CASE(1001)  !Angmom(A= 1,B= 0,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,16*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,16*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,16*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,16*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,16*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,12*nContQP)
    CASE(1002)  !Angmom(A= 1,B= 0,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,18*nContQP)
    CASE(1010)  !Angmom(A= 1,B= 0,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,16*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,16*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,16*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,16*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,16*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,12*nContQP)
    CASE(1011)  !Angmom(A= 1,B= 0,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQP)
    CASE(1012)  !Angmom(A= 1,B= 0,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,80*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,54*nContQP)
    CASE(1020)  !Angmom(A= 1,B= 0,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,18*nContQP)
    CASE(1021)  !Angmom(A= 1,B= 0,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,80*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,54*nContQP)
    CASE(1022)  !Angmom(A= 1,B= 0,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,140*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,140*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,140*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,140*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,140*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,105*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,108*nContQP)
    CASE(1100)  !Angmom(A= 1,B= 1,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQP)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nPrimD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nContD*nContA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD*nContA*nContB)
    CASE(1101)  !Angmom(A= 1,B= 1,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,36*nContQP)
    CASE(1102)  !Angmom(A= 1,B= 1,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,54*nContQP)
    CASE(1110)  !Angmom(A= 1,B= 1,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,36*nContQP)
    CASE(1111)  !Angmom(A= 1,B= 1,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQP)
    CASE(1112)  !Angmom(A= 1,B= 1,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,162*nContQP)
    CASE(1120)  !Angmom(A= 1,B= 1,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,54*nContQP)
    CASE(1121)  !Angmom(A= 1,B= 1,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,162*nContQP)
    CASE(1122)  !Angmom(A= 1,B= 1,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,350*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,315*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,324*nContQP)
    CASE(1200)  !Angmom(A= 1,B= 2,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
    TMParray2maxSize = MAX(TMParray2maxSize,20*nContC*nPrimD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,20*nContC*nContD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,20*nContC*nContD*nContA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,20*nContC*nContD*nContA*nContB)
       TMParray2maxSize = MAX(TMParray2maxSize,18*nContQP)
    CASE(1201)  !Angmom(A= 1,B= 2,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,80*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,72*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,60*nContQP)
    CASE(1202)  !Angmom(A= 1,B= 2,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,150*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQP)
    CASE(1210)  !Angmom(A= 1,B= 2,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,80*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,72*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,60*nContQP)
    CASE(1211)  !Angmom(A= 1,B= 2,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,150*nContQP)
    CASE(1212)  !Angmom(A= 1,B= 2,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,400*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,400*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,400*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,400*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,400*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,360*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,300*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,270*nContQP)
    CASE(1220)  !Angmom(A= 1,B= 2,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,150*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQP)
    CASE(1221)  !Angmom(A= 1,B= 2,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,400*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,400*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,400*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,400*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,400*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,360*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,300*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,270*nContQP)
    CASE(1222)  !Angmom(A= 1,B= 2,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,8*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,120*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,700*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,700*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,700*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,700*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,700*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,630*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,525*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,540*nContQP)
    CASE(2000)  !Angmom(A= 2,B= 0,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,3*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,10*nPrimQP)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nPrimD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,10*nContC*nContD*nContA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,10*nContC*nContD*nContA*nContB)
       TMParray2maxSize = MAX(TMParray2maxSize,6*nContQP)
    CASE(2001)  !Angmom(A= 2,B= 0,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,24*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,20*nContQP)
    CASE(2002)  !Angmom(A= 2,B= 0,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,50*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQP)
    CASE(2010)  !Angmom(A= 2,B= 0,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,40*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,40*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,40*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,24*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,20*nContQP)
    CASE(2011)  !Angmom(A= 2,B= 0,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,50*nContQP)
    CASE(2012)  !Angmom(A= 2,B= 0,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,120*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQP)
    CASE(2020)  !Angmom(A= 2,B= 0,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,100*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,100*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,60*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,50*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,30*nContQP)
    CASE(2021)  !Angmom(A= 2,B= 0,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,120*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQP)
    CASE(2022)  !Angmom(A= 2,B= 0,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,350*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,210*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,175*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQP)
    CASE(2100)  !Angmom(A= 2,B= 1,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,4*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,20*nPrimQP)
    TMParray2maxSize = MAX(TMParray2maxSize,20*nContC*nPrimD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,20*nContC*nContD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,20*nContC*nContD*nContA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,20*nContC*nContD*nContA*nContB)
       TMParray2maxSize = MAX(TMParray2maxSize,18*nContQP)
    CASE(2101)  !Angmom(A= 2,B= 1,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,80*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,72*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,60*nContQP)
    CASE(2102)  !Angmom(A= 2,B= 1,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,150*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQP)
    CASE(2110)  !Angmom(A= 2,B= 1,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,80*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,80*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,80*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,72*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,60*nContQP)
    CASE(2111)  !Angmom(A= 2,B= 1,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,150*nContQP)
    CASE(2112)  !Angmom(A= 2,B= 1,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,400*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,400*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,400*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,400*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,400*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,360*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,300*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,270*nContQP)
    CASE(2120)  !Angmom(A= 2,B= 1,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,200*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,200*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,200*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,180*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,150*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,90*nContQP)
    CASE(2121)  !Angmom(A= 2,B= 1,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,400*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,400*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,400*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,400*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,400*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,360*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,300*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,270*nContQP)
    CASE(2122)  !Angmom(A= 2,B= 1,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,8*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,120*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,700*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,700*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,700*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,700*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,700*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,630*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,525*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,540*nContQP)
    CASE(2200)  !Angmom(A= 2,B= 2,C= 0,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,5*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,35*nPrimQP)
    TMParray2maxSize = MAX(TMParray2maxSize,35*nContC*nPrimD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,35*nContC*nContD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,35*nContC*nContD*nContA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,35*nContC*nContD*nContA*nContB)
       TMParray2maxSize = MAX(TMParray2maxSize,36*nContQP)
    CASE(2201)  !Angmom(A= 2,B= 2,C= 0,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,140*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,140*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,140*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,140*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,140*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,144*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nContQP)
    CASE(2202)  !Angmom(A= 2,B= 2,C= 0,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,350*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,360*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,250*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,150*nContQP)
    CASE(2210)  !Angmom(A= 2,B= 2,C= 1,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,6*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,56*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,140*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,140*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,140*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,140*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,140*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,144*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,100*nContQP)
    CASE(2211)  !Angmom(A= 2,B= 2,C= 1,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,350*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,360*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,250*nContQP)
    CASE(2212)  !Angmom(A= 2,B= 2,C= 1,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,8*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,120*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,700*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,700*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,700*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,700*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,700*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,720*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,500*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,450*nContQP)
    CASE(2220)  !Angmom(A= 2,B= 2,C= 2,D= 0) combi
       TMParray2maxSize = MAX(TMParray2maxSize,7*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,84*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,350*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,350*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,350*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,360*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,250*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,150*nContQP)
    CASE(2221)  !Angmom(A= 2,B= 2,C= 2,D= 1) combi
       TMParray2maxSize = MAX(TMParray2maxSize,8*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,120*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,700*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,700*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,700*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,700*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,700*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,720*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,500*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,450*nContQP)
    CASE(2222)  !Angmom(A= 2,B= 2,C= 2,D= 2) combi
       TMParray2maxSize = MAX(TMParray2maxSize,9*nPrimQP)
       TMParray1maxSize = MAX(TMParray1maxSize,165*nPrimQP)
       TMParray2maxSize = MAX(TMParray2maxSize,1225*nPrimQP)
    TMParray1maxSize = MAX(TMParray1maxSize,1225*nContC*nPrimD*nPrimA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,1225*nContC*nContD*nPrimA*nPrimB)
    TMParray1maxSize = MAX(TMParray1maxSize,1225*nContC*nContD*nContA*nPrimB)
    TMParray2maxSize = MAX(TMParray2maxSize,1225*nContC*nContD*nContA*nContB)
       TMParray1maxSize = MAX(TMParray1maxSize,1260*nContQP)
       TMParray2maxSize = MAX(TMParray2maxSize,875*nContQP)
       TMParray1maxSize = MAX(TMParray1maxSize,900*nContQP)
    CASE DEFAULT
        call ichorquit('Unknown Case in ICI_OBS_general_size',-1)
    END SELECT
  end subroutine SPICI_GPU_OBS_general_sizeGen
END module SPIchorEriCoulombintegralGPUOBSGeneralModGenSize
