      INTEGER MAFOP 
      PARAMETER ( MAFOP = 50 )

      INTEGER NAFOP,IAFOP

      LOGICAL DIPMOM, QUADRU, NQCC, TSTDEN, RELCOR, RELORB, SECMOM
      LOGICAL DAR2EL, DPTECO

      COMMON /INFFOP/ NAFOP, IAFOP(MAFOP),
     *                DIPMOM, QUADRU, NQCC, TSTDEN, RELCOR, RELORB,
     *                SECMOM, DAR2EL, DPTECO
