      LOGICAL DOCART,SPH
      COMMON /CCOM/ THRS,NHTYP,DOCART,IUTYP,
     &              KHK(MXQN),KCK(MXQN),SPH(MXQN),NHKOFF(MXQN)
      CHARACTER*4 GTOTYP
      COMMON /CCOMC/ GTOTYP(MXQN*(MXQN+1)*(MXQN+2)/6)
