      INTEGER MAXTLBL
      PARAMETER ( MAXTLBL = 100 )
      LOGICAL LORXLRT, LR1OPN
      INTEGER NLRTLBL,ISYLRT,ISYOFT
      CHARACTER*8 LRTLBL

#if defined (SYS_CRAY)
      REAL FRQLRT,XLRT
#else
      DOUBLE PRECISION FRQLRT,XLRT
#endif

      COMMON/ILRTRSP/ NLRTLBL,ISYLRT(MAXTLBL),ISYOFT(8),
     &                LORXLRT(MAXTLBL), LR1OPN
      COMMON/CLRTRSP/ LRTLBL(MAXTLBL)
      COMMON/RLRTRSP/ FRQLRT(MAXTLBL),XLRT(MAXTLBL)
