#!/bin/bash
TMP_DIR=/home/tkjaer/NightlyTestingCdash/tmp/DaltonDALTONGNUcoverage
SCRATCH_DIR=/tmp/tkjaer/DaltonDALTONGNUcoverage
rm -rf $TMP_DIR 
rm -rf $SCRATCH_DIR
export PATH=/usr/local/torque/bin:/com/pgi/linux86-64/12.4/bin:/com/pgi/linux86-64/12.4/lib:/com/bin:/usr/local/bin:/bin:/usr/bin:/com/pgi/linux86-64/12.4:/com/pgi/linux86-64/12.4/libso:/com/pgi/linux86-64/12.4/bin:/com/pgi/linux86-64/12.4/lib
export LD_LIBRARY_PATH=/com/pgi/linux86-64/12.4/bin:/com/pgi/linux86-64/12.4/lib:/com/acml-4.1.0-pgi/pgi64_mp_int64/lib:/com/pgi/linux86-64/12.4:/com/pgi/linux86-64/12.4/libso:/com/pgi/linux86-64/12.4/bin:/com/pgi/linux86-64/12.4/lib
#libpgbind.so is only in the old version of pgi 12.4 instead of 12.4 (see path) but acml seem to need this file 
#so it must be built for/with the old pgi version:  needs /com/pgi/linux86-64/12.4/libso/libpgbind.so  
git clone git@repo.ctcc.no:dalton.git $TMP_DIR
cd $TMP_DIR/DALTON
#git checkout linsca-develop
git checkout Dalton2013_release
git log --pretty=format:"%an" --since=1.day > /home/tkjaer/NightlyTestingCdash/SINNERS
export OMP_NUM_THREADS=1
./setup --fc=gfortran --cc=gcc --coverage --blas=off --lapack=off -D SCRATCH_DIR=$SCRATCH_DIR -D BUILDNAME="Grendel-linux-GNU-Dalton2013_release-coverage"
cd $TMP_DIR/DALTON/build
make Nightly
#make Experimental ARGS=-j3

exit 0

