#!/bin/bash

export PATH=$PATH':/opt/intel/mkl'

TMP_DIR=/tmp/dalton
SCRATCH_DIR=/tmp/dalton-cdash-scratch
mkdir -p $TMP_DIR

svn co http://dirac.chem.sdu.dk/svnDalton/dalton/trunk $TMP_DIR

cd $TMP_DIR
./setup --fc=gfortran --cc=gcc --scratch=$SCRATCH_DIR -D BUILDNAME="linux-gfortran-release"

cd $TMP_DIR/build
make Nightly

rm -rf $TMP_DIR $SCRATCH_DIR

exit 0
