#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = ' Output FDE data to XML file:GRIDOUT',
      num_lines   = 6,
      rel_tolerance   = 1.0e-7)

test.run(['fde_dc_hf_exportdens_short.inp'],  ['water.sto6g.mol'], f, args='--mw=80 --put="vemb.grid GRIDOUT"')
test.run(['fde_dc_lda_exportdens_short.inp'], ['water.sto6g.mol'], f, args='--mw=80 --put="vemb.grid GRIDOUT numerical_grid"')
test.run(['fde_dc_mp2_exportdens_short.inp'], ['water.sto6g.mol'], f, args='--mw=40 --put="vemb.grid GRIDOUT" --aw=90')

sys.exit(test.return_code)
