if(ENABLE_OPENRSP)
    set(PE_HOST_PROGRAM "DALTON_OPENRSP")
else()
    set(PE_HOST_PROGRAM "DALTON")
endif()
if(ENABLE_GEN1INT)
    set(PE_INTEGRAL_LIBRARY "GEN1INT")
endif()
set(PE_MPI_MOD OFF)
if(MPI_FOUND)
    if(MPI_COMPILER_MATCHES)
        set(PE_MPI_MOD ON)
    endif()
endif()
set(ExternalProjectCMakeArgs
    -DPARENT_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DPARENT_INSTALL_PREFIX=${PROJECT_BINARY_DIR}/external
    -DCMAKE_Fortran_COMPILER=${CMAKE_Fortran_COMPILER}
    -DPARENT_MODULE_DIR=${PROJECT_BINARY_DIR}/modules
    -DINTEGRAL_LIBRARY=${PE_INTEGRAL_LIBRARY}
    -DENABLE_64BIT_INTEGERS=${ENABLE_64BIT_INTEGERS}
    -DENABLE_STATIC_LINKING=${ENABLE_STATIC_LINKING}
    -DENABLE_MPI=${ENABLE_MPI}
    -DENABLE_MPIF=${PE_MPI_MOD}
    -DHOST_PROGRAM=${PE_HOST_PROGRAM}
    )
add_external(pelib)
if(ENABLE_GEN1INT)
    add_dependencies(pelib gen1int_interface)
endif()
set(DALTON_LIBS
    ${PROJECT_BINARY_DIR}/external/lib/libpelib.a
    ${DALTON_LIBS}
    )

