if(ENABLE_OPENRSP)
    set(PARENT_DEFINITIONS "-DBUILD_OPENRSP")
endif()
if(ENABLE_GEN1INT)
    set(PE_INTEGRAL_LIBRARY "GEN1INT")
endif()
if(MPI_FOUND)
    set(PARENT_DEFINITIONS "${PARENT_DEFINITIONS} -DVAR_MPI")
    if(MPI_COMPILER_MATCHES)
        set(PARENT_DEFINITIONS "${PARENT_DEFINITIONS} -DUSE_MPI_MOD_F90")
    endif()
endif()
set(ExternalProjectCMakeArgs
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${PROJECT_BINARY_DIR}/external
    -DCMAKE_Fortran_COMPILER=${CMAKE_Fortran_COMPILER}
    -DINTEGRAL_LIBRARY=${PE_INTEGRAL_LIBRARY}
    -DENABLE_64BIT_INTEGERS=${ENABLE_64BIT_INTEGERS}
    -DENABLE_BOUNDS_CHECK=${ENABLE_BOUNDS_CHECK}
    -DENABLE_STATIC_LINKING=${ENABLE_STATIC_LINKING}
    -DENABLE_MPI=${ENABLE_MPI}
    -DPARENT_MODULE_DIR=${PROJECT_BINARY_DIR}/modules
    -DPARENT_DEFINITIONS=${PARENT_DEFINITIONS}
    )
add_external(pelib)
if(ENABLE_GEN1INT)
    add_dependencies(pelib gen1int_interface)
endif()
set(DALTON_LIBS
    ${PROJECT_BINARY_DIR}/external/lib/libpelib.a
    ${DALTON_LIBS}
    )

