set(DALTON_C_SOURCES
    DALTON/cc/crayio.c
    DALTON/pdpack/scatter-io.c
    )
set(DALTON_FIXED_FORTRAN_SOURCES
    DALTON/main/dalgnr.F
    DALTON/main/dalpar.F
    DALTON/abacus/aba2eth.F
    DALTON/abacus/aba2r12.F
    DALTON/abacus/aba2tex.F
    DALTON/abacus/abaaat.F
    DALTON/abacus/abactocd.F
    DALTON/abacus/abadip.F
    DALTON/abacus/abadrv.F
    DALTON/abacus/abadtra.F
    DALTON/abacus/abaedrv.F
    DALTON/abacus/abaenr.F
    DALTON/abacus/abaesym.F
    DALTON/abacus/abaexc.F
    DALTON/abacus/abaflt.F
    DALTON/abacus/abafmm.F
    DALTON/abacus/abafsd.F
    DALTON/abacus/abalnr.F
    DALTON/abacus/abaloc.F
    DALTON/abacus/abalrs.F
    DALTON/abacus/abaltra.F
    DALTON/abacus/abamag.F
    DALTON/abacus/abamolden.F
    DALTON/abacus/abander.F
    DALTON/abacus/abandsym.F
    DALTON/abacus/abanuc.F
    DALTON/abacus/abanvib.F
    DALTON/abacus/abaop2.F
    DALTON/abacus/abaopg.F
    DALTON/abacus/abaopt.F
    DALTON/abacus/abaort.F
    DALTON/abacus/abapcm.F
    DALTON/abacus/abaptr.F
    DALTON/abacus/abaqm3.F
    DALTON/abacus/abaqmmm.F
    DALTON/abacus/abaqpg.F
    DALTON/abacus/abaqr.F
    DALTON/abacus/abarhs.F
    DALTON/abacus/abarint.F
    DALTON/abacus/abarlx.F
    DALTON/abacus/abarspn.F
    DALTON/abacus/abaset.F
    DALTON/abacus/abasop.F
    DALTON/abacus/abasos.F
    DALTON/abacus/abatro.F
    DALTON/abacus/abavib.F
    DALTON/abacus/abavrml.F
    DALTON/abacus/abawalk.F
    DALTON/abacus/eckart.F
    DALTON/abacus/ecp.F
    DALTON/abacus/her1ave.F
    DALTON/abacus/her1car.F
    DALTON/abacus/her1drv.F
    DALTON/abacus/her1int.F
    DALTON/abacus/her1odc.F
    DALTON/abacus/her1out.F
    DALTON/abacus/her1pro.F
    DALTON/abacus/her1sym.F
    DALTON/abacus/her2ave.F
    DALTON/abacus/her2dir.F
    DALTON/abacus/her2drv.F
    DALTON/abacus/her2el1.F
    DALTON/abacus/her2el2.F
    DALTON/abacus/her2fck.F
    DALTON/abacus/her2gab.F
    DALTON/abacus/her2her.F
    DALTON/abacus/her2odc.F
    DALTON/abacus/her2out.F
    DALTON/abacus/her2sup.F
    DALTON/abacus/her2sym.F
    DALTON/abacus/herbas.F
    DALTON/abacus/herdirect.F
    DALTON/abacus/herdkh.F
    DALTON/abacus/herdrv.F
    DALTON/abacus/herfckcon.F
    DALTON/abacus/hergam.F
    DALTON/abacus/hergeo.F
    DALTON/abacus/hergp.F
    DALTON/abacus/hergroup.F
    DALTON/abacus/herpar.F
    DALTON/abacus/herqm3.F
    DALTON/abacus/herrdn.F
    DALTON/abacus/hersol.F
    DALTON/abacus/hersym.F
    DALTON/abacus/hertst.F
    DALTON/abacus/her_lslib.F
    DALTON/abacus/huckel.F
    DALTON/abacus/abalresc.F
    DALTON/abacus/linearlr.F
    DALTON/abacus/average.F
    DALTON/abacus/angpso.F
    DALTON/abacus/angkin.F
    DALTON/amfi/amfi.F
    DALTON/amfi/symtra.F
    DALTON/cc/asqr.F
    DALTON/cc/cc2_refop.F
    DALTON/cc/cc3_aabmat_doub.F
    DALTON/cc/cc3_aamat.F
    DALTON/cc/cc3_aden.F
    DALTON/cc/cc3_aden_cub.F
    DALTON/cc/cc3_aden_cub_t0.F
    DALTON/cc/cc3_bfmat.F
    DALTON/cc/cc3_bmatsd.F
    DALTON/cc/cc3_etasd.F
    DALTON/cc/cc3_fbmatt3zu.F
    DALTON/cc/cc3_fmat.F
    DALTON/cc/cc3_fmatsd.F
    DALTON/cc/cc3_ft3b.F
    DALTON/cc/cc3_gmat.F
    DALTON/cc/cc3_gmatnew.F
    DALTON/cc/cc3_hmat.F
    DALTON/cc/cc3_init.F
    DALTON/cc/cc3_lhtr.F
    DALTON/cc/cc3_omeg.F
    DALTON/cc/cc3_omeg3.F
    DALTON/cc/cc3_t3int.F
    DALTON/cc/cc3_t3int3.F
    DALTON/cc/cc3_xi_cont.F
    DALTON/cc/cc3_xisd.F
    DALTON/cc/cc_1idx_d2eff.F
    DALTON/cc/cc_1idxtran.F
    DALTON/cc/cc_21i2.F
    DALTON/cc/cc_21i3.F
    DALTON/cc/cc_2eexp_1.F
    DALTON/cc/cc_2eexp_2.F
    DALTON/cc/cc_2hyp.F
    DALTON/cc/cc_3hyp.F
    DALTON/cc/cc_4hyp.F
    DALTON/cc/cc_aamat.F
    DALTON/cc/cc_aodens3.F
    DALTON/cc/cc_aofock2.F
    DALTON/cc/cc_bamat.F
    DALTON/cc/cc_bfbsort1.F
    DALTON/cc/cc_bfden.F
    DALTON/cc/cc_bfif1.F
    DALTON/cc/cc_bmat.F
    DALTON/cc/cc_cauchy.F
    DALTON/cc/cc_cmat.F
    DALTON/cc/cc_cphf.F
    DALTON/cc/cc_d1ao.F
    DALTON/cc/cc_den.F
    DALTON/cc/cc_den2_pt.F
    DALTON/cc/cc_den_pt2.F
    DALTON/cc/cc_den_rccd.F
    DALTON/cc/cc_dhfao.F
    DALTON/cc/cc_dmat.F
    DALTON/cc/cc_drv.F
    DALTON/cc/cc_e1aim.F
    DALTON/cc/cc_e21con.F
    DALTON/cc/cc_e22con.F
    DALTON/cc/cc_effckmo.F
    DALTON/cc/cc_etadrv.F
    DALTON/cc/cc_etadrv1.F
    DALTON/cc/cc_exci.F
    DALTON/cc/cc_exgr.F
    DALTON/cc/cc_f1inact.F
    DALTON/cc/cc_famat.F
    DALTON/cc/cc_fbta.F
    DALTON/cc/cc_fckdela.F
    DALTON/cc/cc_fckrlx1.F
    DALTON/cc/cc_fdaa.F
    DALTON/cc/cc_fdba.F
    DALTON/cc/cc_fdc.F
    DALTON/cc/cc_fdd.F
    DALTON/cc/cc_fdfb.F
    DALTON/cc/cc_fmat.F
    DALTON/cc/cc_fmattst.F
    DALTON/cc/cc_fop.F
    DALTON/cc/cc_foppt.F
    DALTON/cc/cc_foppt_sc.F
    DALTON/cc/cc_fropro.F
    DALTON/cc/cc_ftst.F
    DALTON/cc/cc_ftstnew.F
    DALTON/cc/cc_get_lambda1.F
    DALTON/cc/cc_get_rmat.F
    DALTON/cc/cc_getgd.F
    DALTON/cc/cc_getgp.F
    DALTON/cc/cc_gim1.F
    DALTON/cc/cc_gmat.F
    DALTON/cc/cc_grad.F
    DALTON/cc/cc_grad0.F
    DALTON/cc/cc_grad2.F
    DALTON/cc/cc_grad2e.F
    DALTON/cc/cc_grad_1.F
    DALTON/cc/cc_gradient.F
    DALTON/cc/cc_hfr1den.F
    DALTON/cc/cc_hmat.F
    DALTON/cc/cc_hpqta.F
    DALTON/cc/cc_hyppol.F
    DALTON/cc/cc_iajb.F
    DALTON/cc/cc_ijcb.F
    DALTON/cc/cc_int3o2.F
    DALTON/cc/cc_int4o.F
    DALTON/cc/cc_jmat.F
    DALTON/cc/cc_kmat.F
    DALTON/cc/cc_lambdaq.F
    DALTON/cc/cc_lammats.F
    DALTON/cc/cc_lamtra.F
    DALTON/cc/cc_landf.F
    DALTON/cc/cc_landf2.F
    DALTON/cc/cc_landf3.F
    DALTON/cc/cc_lhtr.F
    DALTON/cc/cc_lhtr_noddy.F
    DALTON/cc/cc_lhtr_rccd.F
    DALTON/cc/cc_lr.F
    DALTON/cc/cc_maomao.F
    DALTON/cc/cc_mcdny.F
    DALTON/cc/cc_mkrv.F
    DALTON/cc/cc_mmommo.F
    DALTON/cc/cc_mofcon2.F
    DALTON/cc/cc_mofconr12.F
    DALTON/cc/cc_nuccon.F
    DALTON/cc/cc_opa.F
    DALTON/cc/cc_omega2_rccd.F
    DALTON/cc/cc_pckutil.F
    DALTON/cc/cc_pqi.F
    DALTON/cc/cc_qaos.F
    DALTON/cc/cc_qm3.F
    DALTON/cc/cc_qmat.F
    DALTON/cc/cc_qmmm.F
    DALTON/cc/cc_qr2rs.F
    DALTON/cc/cc_r12.F
    DALTON/cc/cc_r12a2.F
    DALTON/cc/cc_r12batf.F
    DALTON/cc/cc_r12ccsd.F
    DALTON/cc/cc_r12mkvamkl.F
    DALTON/cc/cc_r12mkxajkl.F
    DALTON/cc/cc_r12mkxajklfr.F
    DALTON/cc/cc_r12no.F
    DALTON/cc/cc_r12rdpck.F
    DALTON/cc/cc_r12vunpack.F
    DALTON/cc/cc_r12xieta.F
    DALTON/cc/cc_r12xprep.F
    DALTON/cc/cc_rdaod.F
    DALTON/cc/cc_rdrsp.F
    DALTON/cc/cc_rhtr.F
    DALTON/cc/cc_rhtr3.F
    DALTON/cc/cc_rhtr_noddy.F
    DALTON/cc/cc_setdorps.F
    DALTON/cc/cc_setfa.F
    DALTON/cc/cc_setfb12.F
    DALTON/cc/cc_setk11.F
    DALTON/cc/cc_setxe.F
    DALTON/cc/cc_slv.F
    DALTON/cc/cc_soldrv.F
    DALTON/cc/cc_solrsp.F
    DALTON/cc/cc_sop.F
    DALTON/cc/cc_sort4o.F
    DALTON/cc/cc_sortz2.F
    DALTON/cc/cc_tmcal.F
    DALTON/cc/cc_tpa.F
    DALTON/cc/cc_trdrv.F
    DALTON/cc/cc_util.F
    DALTON/cc/cc_wrrsp.F
    DALTON/cc/cc_xetst.F
    DALTON/cc/cc_xieta.F
    DALTON/cc/cc_xopa.F
    DALTON/cc/cc_zkjam.F
    DALTON/cc/cccr_aa.F
    DALTON/cc/cccr_setup.F
    DALTON/cc/cccr_util.F
    DALTON/cc/ccder1.F
    DALTON/cc/ccdiis_solv.F
    DALTON/cc/cceq_solv.F
    DALTON/cc/ccetacor.F
    DALTON/cc/ccexlr.F
    DALTON/cc/ccexnorm.F
    DALTON/cc/ccexpfck.F
    DALTON/cc/ccfbint1.F
    DALTON/cc/ccfbint2.F
    DALTON/cc/ccfbtaao1.F
    DALTON/cc/ccfbtaao2.F
    DALTON/cc/ccfbtaf.F
    DALTON/cc/ccfndop.F
    DALTON/cc/cckappasq.F
    DALTON/cc/cclhtr_r12.F
    DALTON/cc/cclr_fa.F
    DALTON/cc/cclr_setup.F
    DALTON/cc/cclr_util.F
    DALTON/cc/cclt_yps1.F
    DALTON/cc/ccmcd_setup.F
    DALTON/cc/ccpt_btrden.F
    DALTON/cc/ccpt_den.F
    DALTON/cc/ccpt_eta.F
    DALTON/cc/ccpt_fropro.F
    DALTON/cc/ccpt_grad0.F
    DALTON/cc/ccpt_resort_den.F
    DALTON/cc/ccpt_symmback.F
    DALTON/cc/ccqr_setup.F
    DALTON/cc/ccreo2con.F
    DALTON/cc/ccrhs_ipm1.F
    DALTON/cc/ccrhsvec.F
    DALTON/cc/ccrlxxim.F
    DALTON/cc/ccrspsym.F
    DALTON/cc/ccsd_diis.F
    DALTON/cc/ccsd_energy.F
    DALTON/cc/ccsd_input.F
    DALTON/cc/ccsd_init0.F
    DALTON/cc/ccsd_rhs.F
    DALTON/cc/ccsd_rhs3.F
    DALTON/cc/ccsd_rou3.F
    DALTON/cc/ccsd_sortao.F
    DALTON/cc/ccsd_triple.F
    DALTON/cc/ccsdr12ao.F
    DALTON/cc/ccsdr12cd.F
    DALTON/cc/ccsdr12oxr.F
    DALTON/cc/ccsdt_aa_noddy.F
    DALTON/cc/ccsdt_aden_noddy.F
    DALTON/cc/ccsdt_b_noddy.F
    DALTON/cc/ccsdt_ba_noddy.F
    DALTON/cc/ccsdt_eta_cont.F
    DALTON/cc/ccsdt_eta_noddy.F
    DALTON/cc/ccsdt_f_noddy.F
    DALTON/cc/ccsdt_fbmat.F
    DALTON/cc/ccsdt_ints_noddy.F
    DALTON/cc/ccsdt_o32_noddy.F
    DALTON/cc/ccsdt_t32_noddy.F
    DALTON/cc/ccsdt_xi_noddy.F
    DALTON/cc/ccsoppa.F
    DALTON/cc/cctrbt1.F
    DALTON/cc/cctrbt2.F
    DALTON/cc/ccximcon.F
    DALTON/cc/crayio2.F
    DALTON/cc/herdirect_cc.F
    DALTON/cc/iroper2.F
    DALTON/cc/cc_lanczos_lrinp.F
    DALTON/cc/cc_lanczos_drv.F
    DALTON/cc/cc_lanczos_lrextras.F
    DALTON/cc/rpa_grad.F
    DALTON/cc/cc_active.F
    DALTON/choles/cc_caa.F
    DALTON/choles/cc_choatr.F
    DALTON/choles/cc_chocc2.F
    DALTON/choles/cc_chodbg.F
    DALTON/choles/cc_chofop.F
    DALTON/choles/cc_choftr.F
    DALTON/choles/cc_chogd.F
    DALTON/choles/cc_choio.F
    DALTON/choles/cc_cholesky.F
    DALTON/choles/cc_cholrim.F
    DALTON/choles/cc_chomp2.F
    DALTON/choles/cc_chopden.F
    DALTON/choles/cc_chopt.F
    DALTON/choles/cc_chopt_dbg.F
    DALTON/choles/cc_cia.F
    DALTON/choles/cc_ciadbg.F
    DALTON/choles/cc_cyi.F
    DALTON/choles/cc_cyidbg.F
    DALTON/choles/cc_decmo.F
    DALTON/choles/cc_rdrspd.F
    DALTON/choles/cc_rmrsp.F
    DALTON/choles/cc_wrrspd.F
    DALTON/choles/nocc_util.F
    DALTON/densfit/denfit_noddy.F
    DALTON/densfit/df_dirac.F
    DALTON/eri/eri2aob.F
    DALTON/eri/eri2ave.F
    DALTON/eri/eri2car1.F
    DALTON/eri/eri2car2.F
    DALTON/eri/eri2cft.F
    DALTON/eri/eri2csi.F
    DALTON/eri/eri2dis.F
    DALTON/eri/eri2drv.F
    DALTON/eri/eri2fck.F
    DALTON/eri/eri2her.F
    DALTON/eri/eri2odb.F
    DALTON/eri/eri2out.F
    DALTON/eri/eri2par.F
    DALTON/eri/eri2pro.F
    DALTON/eri/eri2r12.F
    DALTON/eri/eri2sph.F
    DALTON/eri/eri2sym.F
    DALTON/eri/eri2vec.F
    DALTON/eri/erisph.F
    DALTON/mlcc/mlcc_work.F90
    DALTON/mlcc/mlcc_block_import.F90
    DALTON/mlcc/mlcc_typedef.F90
    DALTON/mlcc/mlcc3_active_spaces.F90
    DALTON/mlcc/mlcc3_data.F90
    DALTON/mlcc/mlcc3_drv.F90
    DALTON/mlcc/mlcc3_init.F90
    DALTON/mlcc/mlcc3_intermediates.F90
    DALTON/mlcc/mlcc3_omega.F90
    DALTON/mlcc/mlcc3_h_omega.F90
    DALTON/mlcc/mlcc3_reordering.F90
    DALTON/mlcc/mlcc3_various.F90
    DALTON/mlcc/mlccsdpt_drv.F90
    DALTON/mlcc/mlccsdpt_integrals.F90
    DALTON/mlcc/mlccsdpt_e_calc.F90
    DALTON/pdpack/arhpack.F
    DALTON/pdpack/eispack.F
    DALTON/pdpack/jacobi.F
    DALTON/pdpack/linextra.F
    DALTON/pdpack/linpack.F
    DALTON/pdpack/printpkg.F
    DALTON/rsp/absorp.F
    DALTON/rsp/abscomplex.F
    DALTON/rsp/complexpp.F
    DALTON/rsp/abscrs.F
    DALTON/rsp/gpcpp.F
    DALTON/rsp/deq27.F
    DALTON/rsp/expone.F
    DALTON/rsp/fone.F
    DALTON/rsp/hypinp.F
    DALTON/rsp/lagrang.F
    DALTON/rsp/mcdrsp.F
    DALTON/rsp/qfock.F
    DALTON/rsp/qrhso.F
    DALTON/rsp/rspave.F
    DALTON/rsp/rspc8.F
    DALTON/rsp/rspc82.F
    DALTON/rsp/rspchannel.F
    DALTON/rsp/rspcr1.F
    DALTON/rsp/rspcr2.F
    DALTON/rsp/rspcr3.F
    DALTON/rsp/rspcr4.F
    DALTON/rsp/rspcr5.F
    DALTON/rsp/rspcr6.F
    DALTON/rsp/rspcr7.F
    DALTON/rsp/rspcr8.F
    DALTON/rsp/rspcr9.F
    DALTON/rsp/rspdm.F
    DALTON/rsp/rspe2c.F
    DALTON/rsp/rspesg.F
    DALTON/rsp/rspesg_gp.F
    DALTON/rsp/rspesg_lag.F
    DALTON/rsp/rspfxd.F
    DALTON/rsp/rspg.F
    DALTON/rsp/rsphfc.F
    DALTON/rsp/rsphso.F
    DALTON/rsp/rspief.F
    DALTON/rsp/rspief1.F
    DALTON/rsp/rspief2.F
    DALTON/rsp/rspmai.F
    DALTON/rsp/rspmc1.F
    DALTON/rsp/rspmc2.F
    DALTON/rsp/rspmc3.F
    DALTON/rsp/rspoit.F
    DALTON/rsp/rspoli.F
    DALTON/rsp/rsporp.F
    DALTON/rsp/rspprp.F
    DALTON/rsp/rspqm3.F
    DALTON/rsp/rspqmmm.F
    DALTON/rsp/rspqrx3.F
    DALTON/rsp/rspsol.F
    DALTON/rsp/rspsol1.F
    DALTON/rsp/rspsol2.F
    DALTON/rsp/rspsoppa.F
    DALTON/rsp/rsptmo1.F
    DALTON/rsp/rsptmo2.F
    DALTON/rsp/rsptmo3.F
    DALTON/rsp/rsptmo4.F
    DALTON/rsp/rsptpa1.F
    DALTON/rsp/rsptpa2.F
    DALTON/rsp/rsptpa3.F
    DALTON/rsp/rspvec.F
    DALTON/rsp/rspzfs.F
    DALTON/rsp/x2expl.F
    DALTON/sirius/ciham.F
    DALTON/sirius/cioff.F
    DALTON/sirius/cisig.F
    DALTON/sirius/csfstuff.F
    DALTON/sirius/dalcip.F
    DALTON/sirius/dens.F
    DALTON/sirius/detfi.F
    DALTON/sirius/detpr.F
    DALTON/sirius/dets0.F
    DALTON/sirius/dets1.F
    DALTON/sirius/drcctl.F
    DALTON/sirius/dypc.F
    DALTON/sirius/getcix.F
    DALTON/sirius/getint.F
    DALTON/sirius/intsort.F
    DALTON/sirius/koopro4.F
    DALTON/sirius/newtrahso.F
    DALTON/sirius/opt-solvers.F
    DALTON/sirius/r12aux.F
    DALTON/sirius/siraba.F
    DALTON/sirius/sirave.F
    DALTON/sirius/sircan.F
    DALTON/sirius/sircav.F
    DALTON/sirius/sirci.F
    DALTON/sirius/sircmo.F
    DALTON/sirius/sirctl.F
    DALTON/sirius/sirdiis.F
    DALTON/sirius/sirfck.F
    DALTON/sirius/sirgp.F
    DALTON/sirius/sirgrad.F
    DALTON/sirius/sirfcktra.F
    DALTON/sirius/sirief.F
    DALTON/sirius/sirinp.F
    DALTON/sirius/sirlintrn.F
    DALTON/sirius/sirloc.F
    DALTON/sirius/sirlocsel.F
    DALTON/sirius/sirmp2.F
    DALTON/sirius/sirneo.F
    DALTON/sirius/sirnexkap.F
    DALTON/sirius/sirnr.F
    DALTON/sirius/sirntra.F
    DALTON/sirius/siropt.F
    DALTON/sirius/sirorb.F
    DALTON/sirius/sirout.F
    DALTON/sirius/sir_mep.F
    DALTON/sirius/sirpcm.F
    DALTON/sirius/sirpcmder.F
    DALTON/sirius/sirpop.F
    DALTON/sirius/sirqm3.F
    DALTON/sirius/sirqmmm.F
    DALTON/sirius/sirsav.F
    DALTON/sirius/sirscat.F
    DALTON/sirius/sirset.F
    DALTON/sirius/sirsol.F
    DALTON/sirius/sirsolpcm.F
    DALTON/sirius/sirstex.F
    DALTON/sirius/sirtest.F
    DALTON/sirius/sirtr1.F
    DALTON/sirius/sirtra.F
    DALTON/sirius/sirupd.F
    DALTON/sirius/symchk.F
    DALTON/fde/emb_quit.F
    )
if(NOT ENABLE_CRAY_WRAPPERS)
    # radovan: CRAY provides these functions
    set(DALTON_FIXED_FORTRAN_SOURCES
        ${DALTON_FIXED_FORTRAN_SOURCES}
        DALTON/densfit/dposv.F
        )
endif()
set(DALTON_FREE_FORTRAN_SOURCES
    DALTON/input/input_reader_sections.F90
    DALTON/input/input_reader.F90
    DALTON/input/parse_input.F90
    DALTON/abacus/parallel_models_mpi.F90
    DALTON/abacus/parallel_communication_models_mpi.F90
    DALTON/abacus/rma_windows.F90
    DALTON/cc/dyn_index.F90
    DALTON/qmcmm/herqmnp.F90
    DALTON/qmcmm/fock.F90
    DALTON/qmcmm/response.F90
    DALTON/qmcmm/input.F90
    DALTON/fde/emb_main.F90
    DALTON/fde/emb_cfg.F90
    DALTON/fde/emb_dalton_evaluators.F90
    DALTON/fde/emb_dalton_input.F90
    DALTON/fde/emb_data.F90
    DALTON/fde/emb_export.F90
    DALTON/fde/emb_input.F90
    DALTON/fde/emb_io.F90
    DALTON/fde/emb_dalton_io.F
    DALTON/fde/emb_main.F90
    DALTON/fde/emb_max_block_length.F90
    DALTON/fde/emb_types.F90
    DALTON/fde/xcfun_autogen.F90
    DALTON/fde/xml_file.F90
    DALTON/fde/xml_parser.F90
    DALTON/fde/xml_structure.F90
   )
set(DALTON_OWN_BLAS_SOURCES
    DALTON/pdpack/gp_blas.F
    )
set(DALTON_OWN_LAPACK_SOURCES
    DALTON/pdpack/gp_lapack.F
    )
