set(C_SOURCES
cc/crayio.c
dft/basisinfo.c
dft/cube-fast.c
dft/eval-dso.c
dft/fun-b86.c
dft/fun-b86mx.c
dft/fun-b97-1.c
dft/fun-b97-2.c
dft/fun-b97-3.c
dft/fun-b97-k.c
dft/fun-b97.c
dft/fun-becke.c
dft/fun-becke35.c
dft/fun-cam-b3lyp.c
dft/fun-dk87x.c
dft/fun-example.c
dft/fun-example2.c
dft/fun-example3.c
dft/fun-example4.c
dft/fun-example5.c
dft/fun-example6.c
dft/fun-example7.c
dft/fun-example8.c
dft/fun-example9.c
dft/fun-g96.c
dft/fun-gga.c
dft/fun-hcth120.c
dft/fun-hcth147.c
dft/fun-hcth407.c
dft/fun-hcth407p.c
dft/fun-hcth93.c
dft/fun-hcth93m.c
dft/fun-kt.c
dft/fun-lb94.c
dft/fun-lg93.c
dft/fun-lrc95x.c
dft/fun-lyp.c
dft/fun-lypr.c
dft/fun-mpbex.c
dft/fun-mpwx.c
dft/fun-optx.c
dft/fun-p86c.c
dft/fun-pbec.c
dft/fun-pbex.c
dft/fun-pw86x.c
dft/fun-pw91c.c
dft/fun-pw91nc.c
dft/fun-pw91x.c
dft/fun-pw91x2.c
dft/fun-pw92ac.c
dft/fun-pw92c.c
dft/fun-pz81.c
dft/fun-revpbex.c
dft/fun-rpbex.c
dft/fun-slater.c
dft/fun-vwn.c
dft/fun-wignerc.c
dft/fun-wl90c.c
dft/functionals.c
dft/gen-so-int.c
dft/general.c
dft/grid-gen.c
dft/grid-gen2.c
dft/integrator.c
dft/prop-eval.c
dft/quad-fast.c
dft/quad-faster.c
dft/quad-strict.c
gp/mpi_dummyc.c
pdpack/scatter-io.c
    )
set(FIXED_FORTRAN_SOURCES
abacus/dalton.F
abacus/aba2eth.F
abacus/aba2r12.F
abacus/aba2tex.F
abacus/abaaat.F
abacus/abactocd.F
abacus/abadip.F
abacus/abadrv.F
abacus/abadtra.F
abacus/abaedrv.F
abacus/abaenr.F
abacus/abaesym.F
abacus/abaexc.F
abacus/abaflt.F
abacus/abafmm.F
abacus/abafsd.F
abacus/abalnr.F
abacus/abalrs.F
abacus/abaltra.F
abacus/abamag.F
abacus/abamolden.F
abacus/abander.F
abacus/abandsym.F
abacus/abanuc.F
abacus/abanvib.F
abacus/abaop2.F
abacus/abaopg.F
abacus/abaopt.F
abacus/abaort.F
abacus/abapcm.F
abacus/abaptr.F
abacus/abaqm3.F
abacus/abaqmmm.F
abacus/abaqpg.F
abacus/abaqr.F
abacus/abarhs.F
abacus/abarint.F
abacus/abarlx.F
abacus/abarspn.F
abacus/abaset.F
abacus/abasop.F
abacus/abatro.F
abacus/abavib.F
abacus/abavrml.F
abacus/abawalk.F
abacus/dalgnr.F
abacus/eckart.F
abacus/ecp.F
abacus/gen1int_wrapper.F
abacus/her1ave.F
abacus/her1car.F
abacus/her1drv.F
abacus/her1int.F
abacus/her1odc.F
abacus/her1out.F
abacus/her1pro.F
abacus/her1sym.F
abacus/her2ave.F
abacus/her2dir.F
abacus/her2drv.F
abacus/her2el1.F
abacus/her2el2.F
abacus/her2fck.F
abacus/her2gab.F
abacus/her2her.F
abacus/her2odc.F
abacus/her2out.F
abacus/her2sup.F
abacus/her2sym.F
abacus/herbas.F
abacus/herdirect.F
abacus/herdkh.F
abacus/herdrv.F
abacus/herfckcon.F
abacus/hergam.F
abacus/hergeo.F
abacus/hergp.F
abacus/hergroup.F
abacus/herpar.F
abacus/herqm3.F
abacus/herrdn.F
abacus/hersol.F
abacus/hersym.F
abacus/hertst.F
abacus/huckel.F
amfi/amfi.F
amfi/symtra.F
cc/asqr.F
cc/cc2_refop.F
cc/cc3_aabmat_doub.F
cc/cc3_aamat.F
cc/cc3_aden.F
cc/cc3_aden_cub.F
cc/cc3_aden_cub_t0.F
cc/cc3_bfmat.F
cc/cc3_bmatsd.F
cc/cc3_etasd.F
cc/cc3_fbmatt3zu.F
cc/cc3_fmat.F
cc/cc3_fmatsd.F
cc/cc3_ft3b.F
cc/cc3_gmat.F
cc/cc3_gmatnew.F
cc/cc3_hmat.F
cc/cc3_init.F
cc/cc3_lhtr.F
cc/cc3_omeg.F
cc/cc3_omeg3.F
cc/cc3_t3int.F
cc/cc3_t3int3.F
cc/cc3_xi_cont.F
cc/cc3_xisd.F
cc/cc_1idx_d2eff.F
cc/cc_1idxtran.F
cc/cc_21i2.F
cc/cc_21i3.F
cc/cc_2eexp_1.F
cc/cc_2eexp_2.F
cc/cc_2hyp.F
cc/cc_3hyp.F
cc/cc_4hyp.F
cc/cc_aamat.F
cc/cc_aodens3.F
cc/cc_aofock2.F
cc/cc_bamat.F
cc/cc_bfbsort1.F
cc/cc_bfden.F
cc/cc_bfif1.F
cc/cc_bmat.F
cc/cc_cauchy.F
cc/cc_cmat.F
cc/cc_cphf.F
cc/cc_d1ao.F
cc/cc_den.F
cc/cc_den2_pt.F
cc/cc_den_pt2.F
cc/cc_dhfao.F
cc/cc_dmat.F
cc/cc_drv.F
cc/cc_e1aim.F
cc/cc_e21con.F
cc/cc_e22con.F
cc/cc_effckmo.F
cc/cc_etadrv.F
cc/cc_etadrv1.F
cc/cc_exci.F
cc/cc_exgr.F
cc/cc_f1inact.F
cc/cc_famat.F
cc/cc_fbta.F
cc/cc_fckdela.F
cc/cc_fckrlx1.F
cc/cc_fdaa.F
cc/cc_fdba.F
cc/cc_fdc.F
cc/cc_fdd.F
cc/cc_fdfb.F
cc/cc_fmat.F
cc/cc_fmattst.F
cc/cc_fop.F
cc/cc_foppt.F
cc/cc_foppt_sc.F
cc/cc_fropro.F
cc/cc_ftst.F
cc/cc_ftstnew.F
cc/cc_get_lambda1.F
cc/cc_get_rmat.F
cc/cc_getgd.F
cc/cc_getgp.F
cc/cc_gim1.F
cc/cc_gmat.F
cc/cc_grad.F
cc/cc_grad0.F
cc/cc_grad2.F
cc/cc_grad2e.F
cc/cc_grad_1.F
cc/cc_gradient.F
cc/cc_hfr1den.F
cc/cc_hmat.F
cc/cc_hpqta.F
cc/cc_hyppol.F
cc/cc_iajb.F
cc/cc_ijcb.F
cc/cc_int3o2.F
cc/cc_int4o.F
cc/cc_jmat.F
cc/cc_kmat.F
cc/cc_lambdaq.F
cc/cc_lammats.F
cc/cc_lamtra.F
cc/cc_landf.F
cc/cc_landf2.F
cc/cc_landf3.F
cc/cc_lhtr.F
cc/cc_lhtr_noddy.F
cc/cc_lr.F
cc/cc_maomao.F
cc/cc_mcdny.F
cc/cc_mkrv.F
cc/cc_mmommo.F
cc/cc_mofcon2.F
cc/cc_mofconr12.F
cc/cc_nuccon.F
cc/cc_opa.F
cc/cc_pckutil.F
cc/cc_pqi.F
cc/cc_qaos.F
cc/cc_qm3.F
cc/cc_qmat.F
cc/cc_qmmm.F
cc/cc_qr2rs.F
cc/cc_r12.F
cc/cc_r12a2.F
cc/cc_r12batf.F
cc/cc_r12ccsd.F
cc/cc_r12mkvamkl.F
cc/cc_r12mkxajkl.F
cc/cc_r12mkxajklfr.F
cc/cc_r12no.F
cc/cc_r12rdpck.F
cc/cc_r12vunpack.F
cc/cc_r12xieta.F
cc/cc_r12xprep.F
cc/cc_rdaod.F
cc/cc_rdrsp.F
cc/cc_rhtr.F
cc/cc_rhtr3.F
cc/cc_rhtr_noddy.F
cc/cc_setdorps.F
cc/cc_setfa.F
cc/cc_setfb12.F
cc/cc_setk11.F
cc/cc_setxe.F
cc/cc_slv.F
cc/cc_soldrv.F
cc/cc_solrsp.F
cc/cc_sop.F
cc/cc_sort4o.F
cc/cc_sortz2.F
cc/cc_tmcal.F
cc/cc_tpa.F
cc/cc_trdrv.F
cc/cc_util.F
cc/cc_wrrsp.F
cc/cc_xetst.F
cc/cc_xieta.F
cc/cc_xopa.F
cc/cc_zkjam.F
cc/cccr_aa.F
cc/cccr_setup.F
cc/cccr_util.F
cc/ccder1.F
cc/ccdiis_solv.F
cc/cceq_solv.F
cc/ccetacor.F
cc/ccexlr.F
cc/ccexnorm.F
cc/ccexpfck.F
cc/ccfbint1.F
cc/ccfbint2.F
cc/ccfbtaao1.F
cc/ccfbtaao2.F
cc/ccfbtaf.F
cc/ccfndop.F
cc/cckappasq.F
cc/cclhtr_r12.F
cc/cclr_fa.F
cc/cclr_setup.F
cc/cclr_util.F
cc/cclt_yps1.F
cc/ccmcd_setup.F
cc/ccpt_btrden.F
cc/ccpt_den.F
cc/ccpt_eta.F
cc/ccpt_fropro.F
cc/ccpt_grad0.F
cc/ccpt_resort_den.F
cc/ccpt_symmback.F
cc/ccqr_setup.F
cc/ccreo2con.F
cc/ccrhs_ipm1.F
cc/ccrhsvec.F
cc/ccrlxxim.F
cc/ccrspsym.F
cc/ccsd_diis.F
cc/ccsd_energy.F
cc/ccsd_input.F
cc/ccsd_rhs.F
cc/ccsd_rhs3.F
cc/ccsd_rou3.F
cc/ccsd_sortao.F
cc/ccsd_triple.F
cc/ccsdr12ao.F
cc/ccsdr12cd.F
cc/ccsdr12oxr.F
cc/ccsdt_aa_noddy.F
cc/ccsdt_aden_noddy.F
cc/ccsdt_b_noddy.F
cc/ccsdt_ba_noddy.F
cc/ccsdt_eta_cont.F
cc/ccsdt_eta_noddy.F
cc/ccsdt_f_noddy.F
cc/ccsdt_fbmat.F
cc/ccsdt_ints_noddy.F
cc/ccsdt_o32_noddy.F
cc/ccsdt_t32_noddy.F
cc/ccsdt_xi_noddy.F
cc/ccsoppa.F
cc/cctrbt1.F
cc/cctrbt2.F
cc/ccximcon.F
cc/crayio2.F
cc/herdirect_cc.F
cc/iroper2.F
choles/cc_caa.F
choles/cc_choatr.F
choles/cc_chocc2.F
choles/cc_chodbg.F
choles/cc_chofop.F
choles/cc_choftr.F
choles/cc_chogd.F
choles/cc_choio.F
choles/cc_cholesky.F
choles/cc_cholrim.F
choles/cc_chomp2.F
choles/cc_chopden.F
choles/cc_chopt.F
choles/cc_chopt_dbg.F
choles/cc_cia.F
choles/cc_ciadbg.F
choles/cc_cyi.F
choles/cc_cyidbg.F
choles/cc_decmo.F
choles/cc_rdrspd.F
choles/cc_rmrsp.F
choles/cc_wrrspd.F
choles/nocc_util.F
densfit/denfit_noddy.F
densfit/df_dirac.F
densfit/dposv.F
dft/dft_aos.F
dft/dft_aux.F
dft/dft_den.F
dft/dft_exp.F
dft/dft_grad.F
dft/dft_grid.F
dft/dft_gridLL.F
dft/dft_hes.F
dft/dft_inp.F
dft/dft_int.F
dft/dft_ksm.F
dft/dft_mag.F
dft/dft_mos.F
dft/dft_rho.F
dft/dso_cb.F
eri/eri2aob.F
eri/eri2ave.F
eri/eri2car1.F
eri/eri2car2.F
eri/eri2cft.F
eri/eri2csi.F
eri/eri2dis.F
eri/eri2drv.F
eri/eri2fck.F
eri/eri2her.F
eri/eri2odb.F
eri/eri2out.F
eri/eri2par.F
eri/eri2pro.F
eri/eri2r12.F
eri/eri2sph.F
eri/eri2sym.F
eri/eri2vec.F
eri/erisph.F
gp/gpdahle.F
gp/gphjj.F
gp/gpjeppe.F
gp/gpjkp.F
gp/gpjt.F
gp/gplucia.F
gp/gplucia_io.F
gp/gplupar.F
gp/gpsaue.F
gp/gpsimen.F
gp/gptrygve.F
gp/graphic.F
gp/intf7790.F
gp/mempkg.F
gp/mpi_dummy.F
gp/mpimacro.F
gp/pvmmacro.F
gp/qpack.F
gp/vcraypack.F
lucita/ciinfo.F
lucita/dalton_interface.F
lucita/density.F
lucita/diagonal.F
lucita/diagonalize.F
lucita/fock.F
lucita/io.F
lucita/memory.F
lucita/par_lucia.F
lucita/par_solver.F
lucita/program.F
lucita/property.F
lucita/sigma.F
lucita/strings.F
lucita/transform.F
lucita/utils.F
lucita/vecmat.F
pdpack/arhpack.F
pdpack/eispack.F
pdpack/gp_dlapack.F
pdpack/gp_zlapack.F
pdpack/jacobi.F
pdpack/linextra.F
pdpack/linpack.F
pdpack/printpkg.F
rsp/absorp.F
rsp/deq27.F
rsp/expone.F
rsp/fone.F
rsp/hypinp.F
rsp/lagrang.F
rsp/mcdrsp.F
rsp/qfock.F
rsp/qrhso.F
rsp/rspave.F
rsp/rspc8.F
rsp/rspc82.F
rsp/rspchannel.F
rsp/rspcr1.F
rsp/rspcr2.F
rsp/rspcr3.F
rsp/rspcr4.F
rsp/rspcr5.F
rsp/rspcr6.F
rsp/rspcr7.F
rsp/rspcr8.F
rsp/rspcr9.F
rsp/rspdm.F
rsp/rspe2c.F
rsp/rspesg.F
rsp/rspesg_gp.F
rsp/rspesg_lag.F
rsp/rspfxd.F
rsp/rspg.F
rsp/rsphso.F
rsp/rspief.F
rsp/rspief1.F
rsp/rspief2.F
rsp/rspmai.F
rsp/rspmc1.F
rsp/rspmc2.F
rsp/rspmc3.F
rsp/rspoit.F
rsp/rspoli.F
rsp/rsporp.F
rsp/rspprp.F
rsp/rspqm3.F
rsp/rspqmmm.F
rsp/rspqrx3.F
rsp/rspsol.F
rsp/rspsol1.F
rsp/rspsol2.F
rsp/rspsoppa.F
rsp/rsptmo1.F
rsp/rsptmo2.F
rsp/rsptmo3.F
rsp/rsptmo4.F
rsp/rsptpa1.F
rsp/rsptpa2.F
rsp/rsptpa3.F
rsp/rspvec.F
rsp/rspzfs.F
rsp/x2expl.F
sirius/ciauth.F
sirius/ciham.F
sirius/cioff.F
sirius/cisig.F
sirius/csfstuff.F
sirius/dalcip.F
sirius/dens.F
sirius/detfi.F
sirius/detpr.F
sirius/dets0.F
sirius/dets1.F
sirius/drcctl.F
sirius/dypc.F
sirius/getcix.F
sirius/getint.F
sirius/intsort.F
sirius/koopro4.F
sirius/newtrahso.F
sirius/r12aux.F
sirius/siraba.F
sirius/sirave.F
sirius/sircan.F
sirius/sircav.F
sirius/sirci.F
sirius/sircmo.F
sirius/sirctl.F
sirius/sirdiis.F
sirius/sirfck.F
sirius/sirgp.F
sirius/sirgrad.F
sirius/sirief.F
sirius/sirinp.F
sirius/sirlintrn.F
sirius/sirloc.F
sirius/sirmp2.F
sirius/sirneo.F
sirius/sirnexkap.F
sirius/sirnr.F
sirius/sirntra.F
sirius/siropt.F
sirius/sirorb.F
sirius/sirout.F
sirius/sirpcm.F
sirius/sirpcmder.F
sirius/sirpop.F
sirius/sirqm3.F
sirius/sirqmmm.F
sirius/sirsav.F
sirius/sirset.F
sirius/sirsol.F
sirius/sirsolpcm.F
sirius/sirtest.F
sirius/sirtr1.F
sirius/sirtra.F
sirius/sirupd.F
sirius/symchk.F
soppa/ccsd_tcmepkx.F
soppa/dc_calc.F
soppa/dc_eres.F
soppa/dc_r1vec.F
soppa/dc_res_o.F
soppa/dc_rsplex.F
soppa/dc_sres.F
soppa/rp_anal.F
soppa/rp_charge.F
soppa/rp_check.F
soppa/rp_diag.F
soppa/rp_eres.F
soppa/rp_getgp.F
soppa/rp_incred.F
soppa/rp_init.F
soppa/rp_lrsolv.F
soppa/rp_newtrial.F
soppa/rp_optvec.F
soppa/rp_orth_trn.F
soppa/rp_redev.F
soppa/rp_res_o.F
soppa/rp_residual.F
soppa/rp_rsplex.F
soppa/rp_sres.F
soppa/rp_trial1.F
soppa/rp_trial2.F
soppa/rp_trmom.F
soppa/so_anal.F
soppa/so_aodens.F
soppa/so_bcktr.F
soppa/so_bextract.F
soppa/so_check.F
soppa/so_close.F
soppa/so_collect_tm.F
soppa/so_dens.F
soppa/so_densai1.F
soppa/so_densai2.F
soppa/so_diag.F
soppa/so_ediag1.F
soppa/so_ediag2.F
soppa/so_eres.F
soppa/so_excit1.F
soppa/so_excout.F
soppa/so_firgp.F
soppa/so_fndpos.F
soppa/so_getgp.F
soppa/so_getmo.F
soppa/so_gett2.F
soppa/so_incred.F
soppa/so_init.F
soppa/so_initial.F
soppa/so_intrp.F
soppa/so_lrsolv.F
soppa/so_memmax.F
soppa/so_moenergy.F
soppa/so_newtrial.F
soppa/so_onefock.F
soppa/so_onep.F
soppa/so_onepmo.F
soppa/so_open.F
soppa/so_optvec.F
soppa/so_ordeig.F
soppa/so_orth_trn.F
soppa/so_prpint.F
soppa/so_read.F
soppa/so_readset.F
soppa/so_redev.F
soppa/so_res_a.F
soppa/so_res_b.F
soppa/so_res_c.F
soppa/so_res_cb.F
soppa/so_res_cd.F
soppa/so_res_cp.F
soppa/so_res_fck.F
soppa/so_res_o.F
soppa/so_res_ovl.F
soppa/so_res_ovlr.F
soppa/so_res_sym.F
soppa/so_res_tcb.F
soppa/so_residual.F
soppa/so_ropt.F
soppa/so_rpprp1.F
soppa/so_rsplex.F
soppa/so_sdiag1.F
soppa/so_secgp.F
soppa/so_sigai.F
soppa/so_sigda.F
soppa/so_sort.F
soppa/so_sqait2.F
soppa/so_sres.F
soppa/so_t2m1.F
soppa/so_t2mp.F
soppa/so_test.F
soppa/so_test1.F
soppa/so_tfset.F
soppa/so_time.F
soppa/so_tmltr.F
soppa/so_tr1new.F
soppa/so_tr1rp.F
soppa/so_trial1.F
soppa/so_trial2.F
soppa/so_trmom.F
soppa/so_twofock.F
soppa/so_write.F
soppa/so_writeset.F
soppa/so_wrtve.F
    )
set(FREE_FORTRAN_SOURCES
gp/character_processing.F90
gp/dalton_input_processing.F90
gp/input_reader.F90
gp/keyword.F90
lucita/dalton_mpi.F90
lucita/lucita_cfg.F90
lucita/lucita_mcscf_ci_cfg.F90
lucita/lucita_orbitalspaces.F90
lucita/par_communication_model.F90
lucita/par_io.F90
lucita/par_io_fh.F90
lucita/par_sync_cw.F90
    )
