macro(add_dalton_test _name _labels)
    if("${_name}" STREQUAL "pehf_cube")
        add_test(
            ${_name}
            ${CMAKE_SOURCE_DIR}/DALTON/test/TEST -param "-get *.cube" -dalton ${CMAKE_BINARY_DIR}/dalton -log /dev/null -result-directory ${CMAKE_BINARY_DIR}/test_${_name} ${_name}
            )
    else()
        add_test(
            ${_name}
            ${CMAKE_SOURCE_DIR}/DALTON/test/TEST -dalton ${CMAKE_BINARY_DIR}/dalton -log /dev/null -result-directory ${CMAKE_BINARY_DIR}/test_${_name} ${_name}
            )
    endif()
    if(NOT "${_labels}" STREQUAL "")
        set_tests_properties(${_name} PROPERTIES LABELS "${_labels}")
    endif()
endmacro()

macro(add_dalton_perl_test _name _labels)
    add_test(perl_${_name} ${CMAKE_SOURCE_DIR}/DALTON/test/test.pl --dalton=${CMAKE_BINARY_DIR}/dalton --tstdir=${CMAKE_SOURCE_DIR}/DALTON/test --list=${_name})
    if(NOT "${_labels}" STREQUAL "")
        set_tests_properties(perl_${_name} PROPERTIES LABELS "${_labels}")
    endif()
endmacro()

macro(add_dalton_runtest _name _labels)
    add_test(
        ${_name}
        python ${CMAKE_SOURCE_DIR}/DALTON/test/${_name}/test --binary-dir=${PROJECT_BINARY_DIR} --work-dir=${PROJECT_BINARY_DIR}/test/${_name} --verbose)
    if(NOT "${_labels}" STREQUAL "")
        set_tests_properties(${_name} PROPERTIES LABELS "${_labels}")
    endif()
endmacro()

# all tests here should contain the label "dalton"

# all tests with label short should run in less than 30 seconds sequential on a 2GHz CPU

# NEVER comment out tests, this will bite you in future in a terrible way
# also to minimize conflict release/master use the existing variables to distinguish
# tests which are run only on master

# "long" cc2_r12 tests are placed apart on purpose to make it less likely that they
# are run at the same time (then they can be significantly slower)

add_dalton_runtest(dft_ac_grac                   "dalton;runtest;dft")
add_dalton_runtest(dft_b3lyp_cart                "dalton;runtest;dft")
add_dalton_runtest(dft_b3lyp_magsus_nosym        "dalton;runtest;dft")
add_dalton_runtest(dft_b3lyp_molhes_nosym        "dalton;runtest;dft")
add_dalton_runtest(dft_b3lyp_nosym               "dalton;runtest;dft;parallel;short")
add_dalton_runtest(dft_b3lyp_sym                 "dalton;runtest;dft;parallel;short")
add_dalton_runtest(dft_blyp_nosym                "dalton;runtest;dft;parallel;short")
add_dalton_runtest(dft_blyp_sym                  "dalton;runtest;dft;parallel;short")
add_dalton_runtest(dft_camb3lyp                  "dalton;runtest;dft;short;parallel")
add_dalton_runtest(dft_camb3lyp_magsus           "dalton;runtest;dft")
add_dalton_runtest(dft_cr_sym                    "dalton;runtest;dft")
add_dalton_runtest(dft_disp_d2                   "dalton;runtest;dft")
add_dalton_runtest(dft_disp_d3                   "dalton;runtest;dft")
add_dalton_runtest(dft_disp_d3bj                 "dalton;runtest;dft")
add_dalton_runtest(dft_energy_sym                "dalton;runtest;dft")
add_dalton_runtest(dft_hcth120                   "dalton;runtest;dft;short;parallel")
add_dalton_runtest(dft_lb94                      "dalton;runtest;dft")
add_dalton_runtest(dft_lda_cart                  "dalton;runtest;dft")
add_dalton_runtest(dft_lda_nosym                 "dalton;runtest;dft")
add_dalton_runtest(dft_lda_sym                   "dalton;runtest;dft")
add_dalton_runtest(dft_lda_molhes_nosym          "dalton;runtest;dft")
add_dalton_runtest(dft_open_b3lyp                "dalton;runtest;dft;short;parallel")
add_dalton_runtest(dft_open_lr                   "dalton;runtest;dft")
add_dalton_runtest(dft_optimize                  "dalton;runtest;dft")
add_dalton_runtest(dft_pbe                       "dalton;runtest;dft;short;parallel")
add_dalton_runtest(dft_polar                     "dalton;runtest;dft")
add_dalton_runtest(dft_properties_sym            "dalton;runtest;dft")
add_dalton_runtest(dft_properties_nosym          "dalton;runtest;dft")
add_dalton_runtest(dft_rspexci                   "dalton;runtest;dft;short;parallel")
add_dalton_runtest(dft_qr                        "dalton;runtest;dft;medium;parallel")
add_dalton_runtest(rsp_cpp_mcd                   "dalton;runtest;rsp;medium;parallel;dft")
add_dalton_runtest(rsp_polar                     "dalton;runtest;rsp;parallel;short")
add_dalton_runtest(qmmm1                         "dalton;runtest;qmmm;parallel;medium")
add_dalton_runtest(qmmm2                         "dalton;runtest;qmmm;parallel;medium")
add_dalton_runtest(qmmm3                         "dalton;runtest;qmmm;parallel;medium")
add_dalton_runtest(qmmm4                         "dalton;runtest;qmmm;parallel;short")
add_dalton_runtest(qmmm5                         "dalton;runtest;qmmm;parallel;medium")
add_dalton_runtest(qmmm6                         "dalton;runtest;qmmm;medium;parallel")
add_dalton_runtest(qmmm7                         "dalton;runtest;qmmm;parallel;medium")
add_dalton_runtest(walk_solvmag                  "dalton;runtest;long")

add_dalton_test(gen1int_fluorobenzene_cart  "dalton;gen1int;short;parallel")
add_dalton_test(gen1int_fluorobenzene_spher "dalton;gen1int;short;parallel")
add_dalton_test(gen1int_water_cart          "dalton;gen1int;short;parallel")
add_dalton_test(gen1int_water_spher         "dalton;gen1int;short;parallel")

add_dalton_test(energy_direct       "dalton;energy;short;quick;parallel")
add_dalton_test(energy_direct_eri   "dalton;energy;short;parallel")
add_dalton_test(energy_douglaskroll "dalton;energy;short;parallel")
add_dalton_test(energy_nosymm       "dalton;energy;short;parallel")
add_dalton_test(energy_restart      "dalton;energy;short;parallel")
add_dalton_test(energy_restart_scf  "dalton;energy;short;parallel")
add_dalton_test(energy_symm         "dalton;energy;short;parallel")
add_dalton_test(energy_zmat         "dalton;energy;short")
add_dalton_test(energy_nevpt2_gs    "dalton;energy;short;parallel")
add_dalton_test(energy_nevpt2_ex    "dalton;energy;short;parallel")
add_dalton_test(energy_hsrohf       "dalton;energy;short;parallel")
add_dalton_test(energy_hsrohf_qc    "dalton;energy;short;parallel")
add_dalton_test(energy_lucita_gasci "dalton;energy;short;parallel")
add_dalton_test(energy_stex         "dalton;energy;short;parallel")
add_dalton_test(energy_scsmp2       "dalton;energy;short;parallel")
add_dalton_test(energy_localize_selected         "dalton;energy;short")
add_dalton_test(energy_corehole     "dalton;energy;short")

add_dalton_test(energy_solv         "dalton;energy;medium")

add_dalton_test(tddft_tda         "dalton;dft;short;parallel")

add_dalton_test(geoopt_cartsad     "dalton;geo;short;parallel")
add_dalton_test(geoopt_cartsad2    "dalton;geo;short;parallel")
add_dalton_test(geoopt_constrain1a "dalton;geo;short;parallel")
add_dalton_test(geoopt_constrain1b "dalton;geo;short;parallel")
add_dalton_test(geoopt_delintsad   "dalton;geo;short;parallel")
add_dalton_test(geoopt_exci2       "dalton;geo;short")
add_dalton_test(geoopt_numgrd      "dalton;geo;short;parallel")
add_dalton_test(geoopt_preopt      "dalton;geo;short")
add_dalton_test(geoopt_prop        "dalton;geo;short;parallel")
add_dalton_test(geoopt_prop2       "dalton;geo;short;parallel")
add_dalton_test(geoopt_redintmin   "dalton;geo;short;parallel")
add_dalton_test(geoopt_vrml        "dalton;geo;short;parallel")

add_dalton_test(prop_ecd           "dalton;prop;short;parallel")
add_dalton_test(prop_exci          "dalton;prop;short")
add_dalton_test(prop_nolondon      "dalton;prop;short")
add_dalton_test(prop_spinspin      "dalton;prop;short;parallel")
add_dalton_test(prop_spinspin2     "dalton;prop;short;parallel")
add_dalton_test(prop_spinspin3     "dalton;prop;short;parallel")
add_dalton_test(prop_spinspin4     "dalton;prop;short")
add_dalton_test(prop_vibvcd        "dalton;prop;short;parallel")
add_dalton_test(prop_ctocd         "dalton;prop;short;parallel")
add_dalton_test(prop_soppactocd    "dalton;prop;soppa;short")
add_dalton_test(prop_newtrasoppa   "dalton;prop;soppa;medium")
add_dalton_test(prop_newtrasoppacc "dalton;prop;soppa;medium")
add_dalton_test(prop_newtramcscf   "dalton;prop;short;parallel")
add_dalton_test(aba_prop_file      "dalton;prop;short;parallel")
add_dalton_test(prop_vibg1         "dalton;prop;short;parallel")
add_dalton_test(prop_vibg2         "dalton;prop;short;parallel")
add_dalton_test(prop_cpp_ecd       "dalton;prop;short;parallel")
add_dalton_test(prop_lresc         "dalton;prop;short")

add_dalton_runtest(rsp_2ndharm        "dalton;runtest;rsp;short;parallel")
add_dalton_runtest(rsp_3rdharm        "dalton;runtest;rsp;short;parallel")
add_dalton_runtest(rsp_3rdmom         "dalton;runtest;rsp;short;parallel")
add_dalton_test(rsp_dresqr            "dalton;rsp;short;parallel")
add_dalton_test(rsp_ecp               "dalton;rsp;short;parallel")
add_dalton_test(rsp_exci_cmfun        "dalton;rsp;short")
add_dalton_test(rsp_excipolar2        "dalton;rsp;short;parallel")
add_dalton_test(rsp_hyperpolar        "dalton;rsp;short;parallel")
add_dalton_test(rsp_lrso              "dalton;rsp;short")
add_dalton_test(rsp_lrso2             "dalton;rsp;short;parallel")
add_dalton_test(rsp_mcdbterm          "dalton;rsp;short;parallel")
add_dalton_test(rsp_mnf               "dalton;rsp;short;parallel")
add_dalton_test(rsp_phosph            "dalton;rsp;short;parallel")
add_dalton_test(rsp_propave           "dalton;rsp;short")
add_dalton_test(rsp_socorr            "dalton;rsp;short")
add_dalton_test(rsp_socorr2           "dalton;rsp;short")
add_dalton_test(rsp_socorr3           "dalton;rsp;short")
add_dalton_test(rsp_sosingci          "dalton;rsp;short")
add_dalton_test(rsp_sosingorb          "dalton;rsp;short")
add_dalton_test(rsp_sotripci          "dalton;rsp;short")
add_dalton_test(rsp_sotriporb          "dalton;rsp;short")
add_dalton_test(rsp_socorr_dir        "dalton;rsp;short;parallel")
add_dalton_test(rsp_socorr2_dir       "dalton;rsp;short;parallel")
add_dalton_test(rsp_socorr3_dir       "dalton;rsp;short;parallel")
add_dalton_test(rsp_solvhyper         "dalton;rsp;short")
add_dalton_test(rsp_soppa1excinosymm  "dalton;rsp;soppa;short")
add_dalton_test(rsp_soppa1excisymm    "dalton;rsp;soppa;short")
add_dalton_test(rsp_soppa3excinosymm  "dalton;rsp;soppa;short")
add_dalton_test(rsp_soppa3excisymm    "dalton;rsp;soppa;short")
add_dalton_test(rsp_soppafcnosymm     "dalton;rsp;soppa;short")
add_dalton_test(rsp_soppafcsymm       "dalton;rsp;soppa;short")
add_dalton_test(rsp_soppapolar        "dalton;rsp;soppa;short")
add_dalton_test(rsp_soppapolarnosymm  "dalton;rsp;soppa;short")
add_dalton_test(rsp_soppapolarsymm    "dalton;rsp;soppa;short")
add_dalton_test(rsp_sreslrso          "dalton;rsp;short;parallel")
add_dalton_test(rsp_sresqr            "dalton;rsp;short;parallel")
add_dalton_test(rsp_ctocdhyper        "dalton;rsp;short;parallel")
add_dalton_test(prop_spinspin5        "dalton;rsp;short")
add_dalton_test(prop_nolondon_soppacc "dalton;rsp;soppa;short")
add_dalton_test(rsp_soppaccexci       "dalton;rsp;soppa;short")
add_dalton_test(rsp_soppaccpolar      "dalton;rsp;soppa;short")
add_dalton_test(rsp_g_rohf            "dalton;rsp;short;parallel")
add_dalton_test(rsp_g_rohf_dir        "dalton;rsp;short;parallel")
add_dalton_test(rsp_g_cas             "dalton;rsp;short")
add_dalton_test(rsp_g_rohf_ecc        "dalton;rsp;medium;parallel")
add_dalton_test(rsp_hfc               "dalton;rsp;short;parallel;dft")
add_dalton_test(rsp_zfs               "dalton;rsp;short;parallel")
add_dalton_test(rsp_zfs_mc            "dalton;rsp;short;parallel")
add_dalton_runtest(rsp_absorp         "dalton;runtest;rsp;short;parallel")
add_dalton_test(rsp_prop_file         "dalton;rsp;short;parallel")
add_dalton_test(rpa_cis               "dalton;rsp;short;parallel")
add_dalton_test(rsp_g_rohfx           "dalton;rsp;short")
add_dalton_test(rsp_g_rohfx_hs        "dalton;rsp;short")
if ("${CPP}" STREQUAL "-DDISABLE_XC_RESPONSE_SANITY_CHECK")
add_dalton_test(rsp_g_kshfx           "dalton;rsp;short")
add_dalton_test(rsp_g_kshfx_dir       "dalton;rsp;short")
endif()
add_dalton_test(rsp_g_rohfx_direct    "dalton;rsp;short")
add_dalton_test(rsp_g_rohfx_direcths  "dalton;rsp;short")
add_dalton_test(rsp_g_ldax            "dalton;rsp;short;dft")
add_dalton_test(rsp_g_b3lypx          "dalton;rsp;medium;dft")
add_dalton_runtest(rsp_abslrs         "dalton;runtest;rsp;short;parallel")

add_dalton_test(cc3r12_n2_sym_exc             "dalton;ccr12;cc3;longccr12")

add_dalton_test(walk_gradex  "dalton;walk;short;parallel")
add_dalton_test(walk_image   "dalton;walk;short;parallel")
add_dalton_test(walk_modeflw "dalton;walk;short;parallel")
add_dalton_test(walk_polar   "dalton;walk;short")
add_dalton_test(walk_vibave  "dalton;walk;medium")
add_dalton_test(walk_vibave2 "dalton;walk;short")

add_dalton_test(r12_sym    "dalton;short")
add_dalton_test(dpt_h2s    "dalton;short")
add_dalton_test(spin_local "dalton;medium;dft;parallel")

add_dalton_test(cc3r12_n2_sym_exc_lhtr        "dalton;ccr12;cc3;longccr12")

add_dalton_test(prop_exci_ao       "dalton;prop;aosoppa;medium")
add_dalton_test(prop_exci_aorpa    "dalton;prop;aosoppa;short")
add_dalton_test(prop_exci_aorpad   "dalton;prop;aosoppa;short")
add_dalton_test(prop_exci_aosoppa  "dalton;prop;aosoppa;medium")
add_dalton_test(prop_exci_aosoppcc "dalton;prop;aosoppa;medium")

add_dalton_test(cc2_r12_aux_ch4_cbs2a         "dalton;ccr12;longccr12")

add_dalton_test(hfmm_1        "dalton;qm3;short;parallel")
add_dalton_test(hfmmpcm_1     "dalton;qm3;medium;parallel")
add_dalton_test(cc2mm_spc_fop "dalton;qm3;short")
add_dalton_test(dftmm_3       "dalton;qm3;parallel")
add_dalton_test(dftmm_4       "dalton;qm3;parallel")
add_dalton_test(dftmm_5       "dalton;qm3;parallel")
add_dalton_test(dftmm_6       "dalton;qm3;parallel")
add_dalton_test(dftmm_7       "dalton;qm3;parallel")
add_dalton_test(dftmm_8       "dalton;qm3;parallel")
add_dalton_test(dftmm_9       "dalton;qm3;parallel")

add_dalton_test(ccsdmm_spc_fop    "dalton;qm3;medium")
add_dalton_test(ccsdmm_oldtg      "dalton;qm3;medium")
add_dalton_test(ccsdmm_ec1_fop    "dalton;qm3;medium")
add_dalton_test(ccsdmm_ec3_fop    "dalton;qm3;medium")
add_dalton_test(ccsdmm_e01_fop    "dalton;qm3;medium")
add_dalton_test(ccsdmm_modelmix   "dalton;qm3;medium")
add_dalton_test(cc2mm_exci        "dalton;qm3;medium")
add_dalton_test(cc2mm_atmvdw      "dalton;qm3;medium")
add_dalton_test(ccsdmm_twopar_vdw "dalton;qm3;medium")
add_dalton_test(cc2mm_lr_qr       "dalton;qm3;medium")
add_dalton_test(cc2mm_spc_exci    "dalton;qm3;medium")
add_dalton_test(ccmm_beta         "dalton;qm3;medium")

add_dalton_test(cc_rsp_alpha2                 "dalton;cc;short")
add_dalton_test(cc_rsp_beta                   "dalton;cc;short")
add_dalton_test(cc_rsp_beta2                  "dalton;cc;short")
add_dalton_test(cc_rsp_betafreq               "dalton;cc;medium")
add_dalton_test(cc_rsp_betafreq2              "dalton;cc;medium")
add_dalton_test(cc_fop_drw2e                  "dalton;cc;short")
add_dalton_test(cc_fop_prop                   "dalton;cc;short")
add_dalton_test(cc_fop_prop2                  "dalton;cc;short")
add_dalton_test(cc_exgr_prop                  "dalton;cc;short")
add_dalton_test(cc_rsp_excipolar              "dalton;cc;short")
add_dalton_test(cc_rsp_exci                   "dalton;cc;short")
add_dalton_test(cc_energy_field               "dalton;cc;short")
add_dalton_test(cc_fop_prop3                  "dalton;cc;short")
add_dalton_test(cc_fop_prop4                  "dalton;cc;short")
add_dalton_test(cc_fop_freeze                 "dalton;cc;short")
add_dalton_test(cc_rsp_gamma                  "dalton;cc;short")
add_dalton_test(cc_rsp_gammafreq              "dalton;cc;short")
add_dalton_test(cc_rsp_gammafreq2             "dalton;cc;short")
add_dalton_test(cc_rsp_mcdbterm               "dalton;cc;short")
add_dalton_test(cc_rsp_threephot              "dalton;cc;medium")
add_dalton_test(cc_energy_triples             "dalton;cc;short")
add_dalton_test(cc_energy_triplesdirect       "dalton;cc;medium")
add_dalton_test(cc_energy_triplesdirect2      "dalton;cc;short")
add_dalton_test(cc_energy_triplesdirect3      "dalton;cc;medium")
add_dalton_test(cc_energy_triplet2            "dalton;cc;medium")
add_dalton_test(cc_rsp_twophot                "dalton;cc;medium")
add_dalton_test(cc_rsp_twophot2               "dalton;cc;medium")
add_dalton_test(cc_rsp_gamma3                 "dalton;cc;short")
add_dalton_test(cc_rsp_twophot5               "dalton;cc;medium")
add_dalton_test(cc_rsp_twophotb               "dalton;cc;short")
add_dalton_test(cc_grad                       "dalton;cc;short")
add_dalton_test(cc_geoopt_mp2                 "dalton;cc;short")
add_dalton_test(cc_fop_cc3                    "dalton;cc;cc3;short")
add_dalton_test(cc_rsp_ctocd                  "dalton;cc;medium")
add_dalton_test(cc_grad_ccpt_hf               "dalton;cc;short")
add_dalton_test(cc_geopt_ccpt_hf              "dalton;cc;short")
add_dalton_test(cc_geopt_ccpt_h2o             "dalton;cc;medium")
add_dalton_test(cc_prop_file                  "dalton;cc;short")
add_dalton_test(cc_drpa_dipole_h2o            "dalton;cc;short")
add_dalton_test(cc_drpa_grad                  "dalton;cc;short")
add_dalton_test(drpa_grad_ch4                 "dalton;cc;long")
add_dalton_test(cc_rsp_lanczos_alpha          "dalton;cc;medium")

add_dalton_test(cc3_LIH1s1p_pol               "dalton;cc;cc3;short")
add_dalton_test(cc3_LIH1s1p_asym_pol          "dalton;cc;cc3;short")
add_dalton_test(cc3_CARBON_pol                "dalton;cc;cc3;short")
add_dalton_test(cc3_CARBON_asym_pol           "dalton;cc;cc3;short")
add_dalton_test(cc3_LIH1s1p_tmom              "dalton;cc;cc3;short")
add_dalton_test(cc3_LIH1s1p_tmom_no2np1       "dalton;cc;cc3;short")
add_dalton_test(cc3_HF_631G_pol               "dalton;cc;cc3;short")
add_dalton_test(cc3_HF_631G_asym_pol          "dalton;cc;cc3;short")
add_dalton_test(cc3_LIH_431G_tmom             "dalton;cc;cc3;short")
add_dalton_test(cc3_LIH_431G_tmom_no2np1      "dalton;cc;cc3;short")
add_dalton_test(cc3_HF_ccpVDZ_pol             "dalton;cc;cc3;medium")
add_dalton_test(cc3_HF_ccpVDZ_asym_pol        "dalton;cc;cc3;medium")
add_dalton_test(cc3_HF_ccpVDZ_tmom            "dalton;cc;cc3;medium")
add_dalton_test(cc3_HF_ccpVDZ_tmom_no2np1     "dalton;cc;cc3;short")
add_dalton_test(cc3_hyp_HF631g                "dalton;cc;cc3;short")

if(DEVELOPMENT_CODE AND NOT ENABLE_RELEASE)
    add_dalton_test(cc3_findiff                   "dalton;cc;cc3;medium")
    add_dalton_test(cc3_h2o_resid_noddy           "dalton;cc;cc3;medium")
    add_dalton_test(cc3_HF_631G_2hyp_noddy        "dalton;cc;cc3;medium")
    add_dalton_test(cc3_hyp                       "dalton;cc;cc3;medium")
    add_dalton_test(cc3_LIH1s1p_noddy_pol         "dalton;cc;cc3;long")
    add_dalton_test(cc3_tmom_fdif                 "dalton;cc;cc3;medium")
    add_dalton_test(cc3_twophot3_noddy            "dalton;cc;cc3;medium")
    add_dalton_test(prop_vibana                   "dalton;long")
endif()

add_dalton_test(cc3_twophot3                  "dalton;cc;cc3;medium")
add_dalton_test(cc3_h2o_resid                 "dalton;cc;cc3;medium")
add_dalton_test(cc3_LIH_431G_cauchy_12        "dalton;cc;cc3;medium")

add_dalton_test(cc3_HF_631G_2hyp              "dalton;cc;cc3;long")

add_dalton_test(cc_rsp_alpha                  "dalton;cc;medium")
add_dalton_test(cc_rsp_gamma2                 "dalton;cc;medium")
add_dalton_test(cc_rsp_gammadirect            "dalton;cc;medium")
add_dalton_test(cc_rsp_oddisp                 "dalton;cc;medium")
add_dalton_test(cc_energy_triplet             "dalton;cc;medium")
add_dalton_test(cc_rsp_twophotdirect          "dalton;cc;medium")
add_dalton_test(cc_grad2                      "dalton;cc;medium")
add_dalton_test(cc_grad3                      "dalton;cc;medium")
add_dalton_test(cc_geoopt                     "dalton;cc;medium")
add_dalton_test(cc_rsp_solv                   "dalton;cc;medium")
add_dalton_test(cc_energy_triplet3            "dalton;cc;medium")
add_dalton_test(cc2dc_energy                  "dalton;cc;medium")
add_dalton_test(cc2dc_resp                    "dalton;cc;medium")
add_dalton_test(cc2dc_exci                    "dalton;cc;medium")
add_dalton_test(cc2dc_resp_newlr              "dalton;cc;medium")
add_dalton_test(cc_beta_solv                  "dalton;cc;medium")

add_dalton_test(cc_geoopt2                    "dalton;cc;long")

add_dalton_test(choles_b3lyp_polar     "dalton;cholesky;medium;dft")
add_dalton_test(choles_cc2_fop         "dalton;cholesky;medium")
add_dalton_test(choles_hf_magnet       "dalton;cholesky;medium")
add_dalton_test(choles_kt3_ctocd       "dalton;cholesky;medium;dft")
add_dalton_test(choles_lda_prop        "dalton;cholesky;medium;dft")
add_dalton_test(choact_mp2_energy      "dalton;cholesky;short")
add_dalton_test(choles_cc2_exci        "dalton;cholesky;medium")
add_dalton_test(choles_cc2_excdiis     "dalton;cholesky;long")
add_dalton_test(choles_cc2_polar       "dalton;cholesky;medium")
add_dalton_test(choles_ccsdpt_energy   "dalton;cholesky;long")

if(ENABLE_PELIB)
add_dalton_test(pehf_iter             "dalton;peqm;parallel;short")
add_dalton_test(pehf_direct           "dalton;peqm;parallel;short")
add_dalton_test(pehf_gspol            "dalton;peqm;parallel;short")
add_dalton_test(pehf_damp             "dalton;peqm;parallel;short")
add_dalton_test(pehf_mmdamp             "dalton;peqm;parallel;short")
add_dalton_test(pehf_qmdamp           "dalton;peqm;parallel;short")
add_dalton_test(pehf_restart          "dalton;peqm;parallel;short")
add_dalton_test(pehf_border           "dalton;peqm;parallel;short")
add_dalton_test(pehf_cube             "dalton;peqm;parallel;short")
add_dalton_test(pehsrohf_wft          "dalton;peqm;parallel;short")
add_dalton_test(perohf_prop           "dalton;peqm;parallel;short")
add_dalton_test(pehf_1pa              "dalton;peqm;parallel;short")
add_dalton_test(pehf_2pa              "dalton;peqm;parallel;short")
add_dalton_test(pehf_alpha            "dalton;peqm;parallel;short")
add_dalton_test(pehf_beta             "dalton;peqm;parallel;short")
add_dalton_test(pehf_cpp              "dalton;peqm;parallel;short")
add_dalton_test(pehf_nomb             "dalton;peqm;parallel;short")
add_dalton_test(pehf_lao              "dalton;peqm;parallel;short")
add_dalton_test(pehf_lao_redist       "dalton;peqm;parallel;short")
add_dalton_test(pehf_zeromul_isopol   "dalton;peqm;parallel;short")
add_dalton_test(pemcscf_1             "dalton;peqm;parallel;short")
add_dalton_test(pemcscf_2             "dalton;peqm;parallel;short")
add_dalton_test(pemcscf_3             "dalton;peqm;parallel;short")
add_dalton_test(pesoppa_excit         "dalton;peqm;soppa;short")
endif()

if(ENABLE_QFITLIB)
add_dalton_runtest(qfit_hf_charges              "dalton;short;qfit;parallel;")
add_dalton_runtest(qfit_dft_charges             "dalton;short;qfit;parallel;")
add_dalton_runtest(qfit_dft_transition_charges  "dalton;short;qfit;parallel;")
endif()

add_dalton_test(geoopt_cartmin                "dalton;medium")
add_dalton_test(geoopt_dckerr                 "dalton;medium")
add_dalton_test(geoopt_delintmin              "dalton;medium")
add_dalton_test(geoopt_exci                   "dalton;medium")
add_dalton_test(geoopt_mp2froz                "dalton;medium")
add_dalton_test(geoopt_redintsad              "dalton;medium")
add_dalton_test(geoopt_symbrk                 "dalton;medium")
add_dalton_test(prop_expgrad                  "dalton;medium;dft")
add_dalton_test(prop_nucquad                  "dalton;medium")
add_dalton_test(prop_roa                      "dalton;medium")
add_dalton_test(rsp_dckerr                    "dalton;medium")
add_dalton_test(rsp_esr                       "dalton;medium")
add_dalton_test(rsp_esr2                      "dalton;medium")
add_dalton_test(rsp_mnfphosph                 "dalton;medium")
add_dalton_test(rsp_ecphosph                  "dalton;medium")
add_dalton_test(rsp_solvesr                   "dalton;medium")
add_dalton_test(walk_polar2                   "dalton;medium")
add_dalton_test(rsp_fullhfc                   "dalton;medium;dft")

add_dalton_test(geoopt_prop3                  "dalton;long")
add_dalton_test(geoopt_prop3_ex               "dalton;long")
add_dalton_test(rsp_excipolar                 "dalton;long")
add_dalton_test(rsp_twophot                   "dalton;long")

add_dalton_test(dft_stex                      "dalton;dft")
add_dalton_test(dft_hsrohf                    "dalton;dft")

add_dalton_test(hfreqfromE                    "dalton;numder")
add_dalton_test(hfreqfromg                    "dalton;numder")
add_dalton_test(effgeom_fromE                 "dalton;numder")
add_dalton_test(effgeom_fromE2                "dalton;numder")
add_dalton_test(vibave_spinspin               "dalton;numder")

add_dalton_test(r12_damped                    "dalton;mp2r12")
add_dalton_test(r12_damped_herdir             "dalton;mp2r12")
add_dalton_test(r12_sym                       "dalton;mp2r12")
add_dalton_test(r12_nosym                     "dalton;mp2r12")
add_dalton_test(r12_fc_sym                    "dalton;mp2r12")
add_dalton_test(r12_fc_nosym                  "dalton;mp2r12")
add_dalton_test(r12_aux_sym                   "dalton;mp2r12")
add_dalton_test(r12_aux_nosym                 "dalton;mp2r12")
add_dalton_test(r12_fc_aux_sym                "dalton;mp2r12")
add_dalton_test(r12_fc_aux_nosym              "dalton;mp2r12")
add_dalton_test(r12_prop                      "dalton;mp2r12")
add_dalton_test(r12_prop_n2                   "dalton;mp2r12")
add_dalton_test(r12_prop_h2o                  "dalton;mp2r12")
add_dalton_test(r12_loc                       "dalton;mp2r12")
add_dalton_test(r12_stg                       "dalton;mp2r12")
add_dalton_test(r12_orb                       "dalton;mp2r12")
add_dalton_test(r12_cabs                      "dalton;mp2r12")

add_dalton_test(cc2_r12_he                    "dalton;ccr12;short")
add_dalton_test(cc2_r12_he_a2                 "dalton;ccr12;short")
add_dalton_test(cc2_r12_aux2_bh               "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux2_bh_sym           "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_bh_a2             "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_bh_sym_a2         "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux2_bh_a2            "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux2_bh_sym_a2        "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux2_bh_lhtr          "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux2_bh_sym_lhtr      "dalton;ccr12;medium")
add_dalton_test(ccsdr12_bh_direct             "dalton;ccr12;medium")
add_dalton_test(ccsdr12_n2_direct             "dalton;ccr12;medium")
add_dalton_test(ccsdr12_bh                    "dalton;ccr12;short")
add_dalton_test(ccsdr12_n2                    "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4               "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4_sym           "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4_lhtr          "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4_sym_lhtr      "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_nh3_sym           "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_nh3_sym_lhtr      "dalton;ccr12;medium")
add_dalton_test(ccsdr12pt_ne                  "dalton;ccr12;short")
add_dalton_test(cc2_r12_aux_ch4_fop           "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4_sym_fop       "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_h2o_fop           "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_h2o_sym_fop       "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4_lr            "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4_sym_lr        "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4_sym_lr_nondir "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4_sym_nondir    "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4_ff            "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4_ff2           "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4_sym_pol       "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_n2_gamma          "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_n2_gamma2         "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ne_gamma          "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_bh_a3             "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_bh_sym_a3         "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ne                "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ne_gamma2         "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_h2o_a2            "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_h2o_sym_a2        "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_h2o_a3            "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_h2o_sym_a3        "dalton;ccr12;medium")
add_dalton_test(ccsdr12_n2_exc                "dalton;ccr12;medium")
add_dalton_test(ccsdr12_n2_sym_exc            "dalton;ccr12;medium")
add_dalton_test(ccsdr12_n2_sym_exc_lhtr       "dalton;ccr12;medium")
add_dalton_test(ccsdr12pt_ne_f12              "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4_sym_f12       "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4_sym_a3_f12    "dalton;ccr12;medium")
add_dalton_test(ccsdr12_n2_gamma              "dalton;ccr12;medium")
add_dalton_test(ccsdr12_n2_gamma2             "dalton;ccr12;medium")
add_dalton_test(ccsdr12_h2o_gamma             "dalton;ccr12;medium")
add_dalton_test(ccsdr12_h2o_gamma2            "dalton;ccr12;medium")
add_dalton_test(ccsdr12_be                    "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4_cbs1          "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4_cbs2          "dalton;ccr12;medium")
add_dalton_test(cc2_r12_aux_ch4_cbs3          "dalton;ccr12;medium")

add_dalton_test(dpt_hf                        "dalton;dpt")
add_dalton_test(dpt_h2s                       "dalton;dpt")
add_dalton_test(dpt_h2s_finp                  "dalton;dpt")
add_dalton_test(dpt_hbr_finm                  "dalton;dpt")
add_dalton_test(dpt_h2s_finm                  "dalton;dpt")
add_dalton_test(dpt_hbr                       "dalton;dpt")
add_dalton_test(dpt_hbr_finp                  "dalton;dpt")
add_dalton_test(dpt_h2s_ff                    "dalton;dpt")

add_dalton_test(cc2_r12_aux_ch4_a2            "dalton;ccr12;longccr12")
add_dalton_test(cc2_r12_aux_ch4_sym_a2        "dalton;ccr12;longccr12")

add_dalton_test(soppa_vibavg_twobas           "dalton;prop;soppa")
add_dalton_test(dcpt2                         "dalton")
add_dalton_test(pcmsoppa_excit                "dalton;pcm;soppa")

add_dalton_test(cc2_r12_aux_ch4_sym_a3        "dalton;ccr12;longccr12")

if(DEVELOPMENT_CODE AND NOT ENABLE_RELEASE)
if(ENABLE_MPI)
if(DEFINED ENV{DALTON_NUM_MPI_PROCS})
  # radovan: note that this file is read at configure time but
  #          DALTON_NUM_MPI_PROCS is often not set before runtime/testtime
  if($ENV{DALTON_NUM_MPI_PROCS} GREATER 1)
    add_dalton_test(energy_parallel               "dalton;parallel")
    add_dalton_test(geoopt_parallel               "dalton;parallel")
    add_dalton_test(rsp_parallel                  "dalton;parallel")
    add_dalton_test(dft_parallell_properties      "dalton;parallel;dft")
  endif()
endif()
endif()
endif()

add_dalton_perl_test(Bterm_sym         "dalton;perl;pcm")
add_dalton_perl_test(dftmm_1           "dalton;perl;dft;qmmm;parallel;short")
add_dalton_perl_test(dftmm_2           "dalton;perl;dft;qmmm;parallel;medium")
add_dalton_perl_test(dipole            "dalton;perl;pcm")
add_dalton_perl_test(ECD               "dalton;perl;pcm")
add_dalton_perl_test(lf_hfnosym_linres "dalton;perl;pcm")
add_dalton_perl_test(neq_exc_sym       "dalton;perl;pcm")
add_dalton_perl_test(OR_hf             "dalton;perl;pcm")
add_dalton_perl_test(pcm_excit         "dalton;perl;pcm")
add_dalton_perl_test(qm3pcm_1          "dalton;perl;qm3;pcm")
add_dalton_perl_test(qmmm1_short       "dalton;perl;qmmm;parallel;short")
add_dalton_perl_test(shield_spin       "dalton;perl;pcm")
add_dalton_perl_test(tpa_pcm_sym       "dalton;perl;pcm")
add_dalton_perl_test(trp_qr_pcm        "dalton;perl;pcm")
if(NOT ENABLE_MPI)
add_dalton_perl_test(rsp_zfs_mc2       "dalton;perl;mcscf")
add_dalton_perl_test(mcscf             "dalton;perl;mcscf;pcm")
add_dalton_perl_test(mcscf-nomp2       "dalton;perl;mcscf;pcm")
endif()

add_dalton_test(cc2_r12_aux_benzene_sym_fop   "dalton;ccr12;longccr12")
