set(TEST_BASE ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton)
set(TEST_PARAM )

if(ENABLE_MPI)
    if(DEFINED ENV{DALTON_TEST_MPI})
        message(" -- DALTON_TEST_MPI set to $ENV{DALTON_TEST_MPI}")
        set(TEST_ARGS -param "-N $ENV{DALTON_TEST_MPI}")
    else()
        message(" -- DALTON_TEST_MPI defaults to 5")
        set(TEST_ARGS -param "-N 5")
    endif()
else()
    set(TEST_ARGS)
endif()

if(ENABLE_MPI)
  set(TEST_PARAM "-N 2")
endif()

macro(add_lsdalton_test _name _labels)
    add_test(${_name} ${CMAKE_SOURCE_DIR}/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton ${TEST_ARGS} ${_name})
    if(NOT "${_labels}" STREQUAL "")
        set_tests_properties(${_name} PROPERTIES LABELS "${_labels}")
    endif()
endmacro()

if(ENABLE_64BIT_INTEGERS)
    add_lsdalton_test(linsca/linsca_trilevel_64bit "lsdalton")
    add_lsdalton_test(linsca/linsca_atoms_64bit    "lsdalton")
endif()

if(ENABLE_MPI AND ENABLE_SCALAPACK AND NOT USE_32BIT_MPI_INTERFACE)
    add_lsdalton_test(SCALAPACK/linsca_arh_SCALAPACK                  "lsdalton")
    add_lsdalton_test(SCALAPACK/linsca_atoms_SCALAPACK                "lsdalton")
    add_lsdalton_test(SCALAPACK/linsca_energy_SCALAPACK               "lsdalton")
    add_lsdalton_test(SCALAPACK/linsca_trilevel_2nd_local_SCALAPACK   "lsdalton")
    add_lsdalton_test(SCALAPACK/linsca_trilevel_2nd_all_SCALAPACK     "lsdalton")
    add_lsdalton_test(SCALAPACK/LSDALTON_DENSFIT_FMM_SCALAPACK        "lsdalton")
    add_lsdalton_test(SCALAPACK/LSDALTON_FMM_SCALAPACK                "lsdalton")
    add_lsdalton_test(SCALAPACK/LSDALTON_ethane_dft_molgrad_SCALAPACK "lsdalton")
    add_lsdalton_test(SCALAPACK/LSresponse_DFT_beta_SCALAPACK         "lsdalton")
    add_lsdalton_test(SCALAPACK/linsca_arh_SCALAPACK_MEMDIST          "lsdalton")
    add_lsdalton_test(SCALAPACK/linsca_atoms_SCALAPACK_MEMDIST        "lsdalton")
endif()

if(ENABLE_XCFUN)
    add_lsdalton_test(LSresponse/LSresponse_xcfun_lda_molgrad "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_xcfun_gga_molgrad "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_xcfun_lda_linrsp  "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_xcfun_gga_linrsp  "lsdalton")
endif()

if(ENABLE_OPENRSP)
    add_lsdalton_test(LSint/LSDALTON_gen1int                  "lsdalton")
endif()

if(ENABLE_CSR)
    add_lsdalton_test(csr/linsca_atoms_csr_debug              "lsdalton")
    add_lsdalton_test(csr/linsca_energy_csr                   "lsdalton")
    add_lsdalton_test(csr/linsca_onestep_csr                  "lsdalton")
    add_lsdalton_test(csr/LSDALTON_INCREM_csr                 "lsdalton")
    add_lsdalton_test(csr/LSDALTON_FMM_csr                    "lsdalton")
    add_lsdalton_test(csr/LSDALTON_ethane_dft_molgrad_csr     "lsdalton")
#   add_lsdalton_test(csr/linsca_direct_dens_csr              "lsdalton")
#   add_lsdalton_test(csr/linsca_trilevel_2nd_local_csr       "lsdalton")
#   add_lsdalton_test(csr/linsca_trilevel_2nd_all_csr         "lsdalton")
#   add_lsdalton_test(csr/linsca_atoms_csr                    "lsdalton")
#   add_lsdalton_test(csr/linsca_rhf_stability_csr            "lsdalton")
#   add_lsdalton_test(csr/linsca_trilevel_csr                 "lsdalton")
#   add_lsdalton_test(csr/LSDALTON_DENSFIT_FMM_csr            "lsdalton")
endif()

# radovan: will refactor this as soon as i know how we want to deal with mpi tests
#          IMO the nr of cores should not be set here at all
add_test(LSlib/LSlib_cam_reg                            ${TEST_BASE}  -param "-lslib_test ${TEST_PARAM}" LSlib/LSlib_cam_reg                 )
add_test(LSlib/LSlib_cam_dfJ_aK                         ${TEST_BASE}  -param "-lslib_test ${TEST_PARAM}" LSlib/LSlib_cam_dfJ_aK              )

    add_lsdalton_test(linsca/linsca_energy                           "lsdalton")
    add_lsdalton_test(linsca/linsca_VanLenthe                        "lsdalton")
    add_lsdalton_test(linsca/linsca_emsl                             "lsdalton")
    add_lsdalton_test(linsca/linsca_las                              "lsdalton")
    add_lsdalton_test(linsca/linsca_admm                             "lsdalton")
    add_lsdalton_test(linsca/linsca_admm_df                          "lsdalton")
    add_lsdalton_test(linsca/linsca_dft_energy                       "lsdalton")
    add_lsdalton_test(linsca/linsca_rhf_stability                    "lsdalton")
#   add_lsdalton_test(linsca/linsca_direct_dens                      "lsdalton")
    add_lsdalton_test(linsca/linsca_arh                              "lsdalton")
    add_lsdalton_test(linsca/linsca_arh_davidson                     "lsdalton")
    add_lsdalton_test(linsca/linsca_arh_ls_davidson                  "lsdalton")
    add_lsdalton_test(linsca/linsca_trilevel_2nd_local               "lsdalton")
    add_lsdalton_test(linsca/linsca_trilevel_2nd_all                 "lsdalton")
    add_lsdalton_test(linsca/linsca_atoms                            "lsdalton")
    add_lsdalton_test(linsca/linsca_trilevel                         "lsdalton")
    add_lsdalton_test(linsca/lsdalton_dft_ssfgrid                    "lsdalton")
    add_lsdalton_test(linsca/test_kurtosis                           "lsdalton")
    add_lsdalton_test(linsca/PipekMezeyLowdin                        "lsdalton")
    add_lsdalton_test(linsca/linsca_lcm_nongc                        "lsdalton")
    add_lsdalton_test(linsca/test_soeo                               "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_b3lyp_water                     "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_pure                            "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_userdefined_basis1              "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_userdefined_basis2              "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_NOBQBQ2                         "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_pointcharge                     "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_pointcharge2                    "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_phantom                         "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_phantom2                        "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_EP                              "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_PropertyTest1                   "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_geoderiv                        "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_magderiv                        "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_magderiv2                       "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_magderiv3                       "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_camb3lyp                        "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_camb3lyp2                       "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_screen1                         "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_screen2                         "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_cartesian_ecoeff                "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_MBIE                            "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_DaLink                          "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_DaLink2                         "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_DENSFIT_FMM                     "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_dftfunc_bp86                    "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_dftfunc_bpw91                   "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_dftfunc_kt3                     "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_dftfunc_lb94                    "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_dftfunc_pbe0                    "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_dftfunc_pw86x                   "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_dftfunc_vwn3                    "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_dftfunc_GGAKey                  "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_ethane_df_dft_molgrad           "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_ethane_df_lda_jengine           "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_ethane_df_overlap_lda           "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_ethane_dft_molgrad              "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_ethane_lda_jengine              "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_FMM                             "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_FMM_trilevel                    "lsdalton")
#   add_lsdalton_test(LSint/LSDALTON_fmm_gradient                    "lsdalton")
#   add_lsdalton_test(LSint/LSDALTON_fmm_df_gradient                 "lsdalton")
#   add_lsdalton_test(LSint/LSDALTON_fmm_twoel_gradient              "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_INCREM                          "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_INCREM2                         "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_J_NSETUV                        "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_Link                            "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_NOFAMILY                        "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_pass                            "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_PrimAng                         "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_ethane_dfK_dft                  "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_ethane_pari_b3lyp               "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_ethane_pari_b3lyp_unconstrained "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_ethane_pari_b3lyp_ChgConst      "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_ethane_pari_b3lyp_ChgDipConst   "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_UNCONT                          "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_ethane_dft_disp                 "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_HF_cartesian                    "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_augTZ                           "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_donotsavegab                    "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_INCREMDALINK                    "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_SR_EXCHANGE                     "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_LSlib                           "lsdalton")

    add_lsdalton_test(LSresponse/LSresponse_HF_alpha                 "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_HF_alpha_aK              "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_HF_alpha_astv            "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_HF_beta                  "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_HF_dipole                "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_HF_dtpa                  "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_HF_esd                   "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_HF_esg                   "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_HF_gamma                 "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_HF_gamma_lcm             "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_HF_molgra                "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_HF_opa                   "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_HF_tpa                   "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_DFT_alpha                "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_DFT_alpha_aptv           "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_DFT_beta                 "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_DFT_dipole               "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_DFT_esd                  "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_DFT_esg                  "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_DFT_esg_LDA              "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_DFT_dtpa                 "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_DFT_molgra               "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_DFT_opa                  "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_DFT_tpa                  "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_NMR_SHIELD               "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_mcd                      "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_mcd2                     "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_mcd3                     "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_mcd_calc                 "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_excit_cs00               "lsdalton")
    add_lsdalton_test(geomopt/Excited_state_opt                      "lsdalton")
    add_lsdalton_test(geomopt/geoopt_constrain                       "lsdalton")
    add_lsdalton_test(geomopt/cartes_bfgs_min                        "lsdalton")
    add_lsdalton_test(geomopt/redint_bfgs                            "lsdalton")
    add_lsdalton_test(geomopt/cartes_trilevel_newconv                "lsdalton")
    add_lsdalton_test(geomopt/cartes_psb_min                         "lsdalton")
    add_lsdalton_test(ddynam/HCN_ddyn                                "lsdalton")
    add_lsdalton_test(ddynam/HF_vib                                  "lsdalton")
    add_lsdalton_test(ddynam/H2O_fmd                                 "lsdalton")
    add_lsdalton_test(dectests/decmp2_energy                         "lsdalton")
    add_lsdalton_test(dectests/decmp2_density                        "lsdalton")
    add_lsdalton_test(dectests/decmp2_gradient                       "lsdalton")
    add_lsdalton_test(dectests/decmp2_geoopt                         "lsdalton")
    add_lsdalton_test(dectests/fullmp2_energy                        "lsdalton")
    add_lsdalton_test(dectests/fullcc2                               "lsdalton")
    add_lsdalton_test(dectests/fullccsd_high                         "lsdalton")
    add_lsdalton_test(dectests/fullccsd_3                            "lsdalton")
    add_lsdalton_test(dectests/fullccsd_2                            "lsdalton")
    add_lsdalton_test(dectests/arraytest                             "lsdalton")
    add_lsdalton_test(dectests/reordertest                           "lsdalton")
    add_lsdalton_test(dectests/decmp2_gradient_debug                 "lsdalton")
    add_lsdalton_test(plt/plt_dens                                   "lsdalton")
    add_lsdalton_test(plt/plt_ep                                     "lsdalton")

if(NOT ENABLE_RELEASE)
    add_lsdalton_test(LSint/LSDALTON_uncontAObatch         "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_UDFT                  "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_UHF_DEFAULT           "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_UHF_excit             "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_UHF_excit2            "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_UHF_excit_radical     "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_UHF_hessian           "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_UHF_JENGINE           "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_UHF_JENGINE_LINK      "lsdalton")
    add_lsdalton_test(LSint/LSDALTON_UHF_LINK              "lsdalton")
    add_lsdalton_test(linsca/linsca_unrest_energy          "lsdalton")
    add_lsdalton_test(linsca/linsca_unrest_dft_energy      "lsdalton")
    add_lsdalton_test(linsca/linsca_uhf_stability          "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_DFT_excit_beta "lsdalton")
    add_lsdalton_test(LSresponse/LSresponse_HF_gamma_SVD   "lsdalton")
    add_lsdalton_test(dectests/fullmp2_f12                 "lsdalton")
    add_lsdalton_test(dectests/fullmp2_local_f12           "lsdalton")
    add_lsdalton_test(dectests/fullccsd_f12                "lsdalton")
    add_lsdalton_test(dectests/fullccsd_1                  "lsdalton")
    add_lsdalton_test(dectests/fullccsd_low                "lsdalton")
    add_lsdalton_test(dectests/fullccsdpt                  "lsdalton")
    add_lsdalton_test(dectests/decccsdpt                   "lsdalton")
    add_lsdalton_test(dectests/decccsdpt_simfull           "lsdalton")
    add_lsdalton_test(dectests/decmp2_gradient_debug2      "lsdalton")
    add_lsdalton_test(dectests/decmp2_energy_FO            "lsdalton")
    add_lsdalton_test(dectests/decmp2_geoopt_FO            "lsdalton")
    add_lsdalton_test(dectests/decccsd                     "lsdalton")
    add_lsdalton_test(pbc2/pbc2_h2fock                     "lsdalton")
    add_lsdalton_test(pbc2/pbc2_h2SCF_iter1                "lsdalton")
    add_lsdalton_test(pbc2/pbc2_h2STO6G                    "lsdalton")
#   add_lsdalton_test(LSresponse/LSresponse_HF_molHessian  "lsdalton")
endif()
