macro(add_lsdalton_test _name _labels)
    add_test(${_name} ${CMAKE_SOURCE_DIR}/LSDALTON/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton ${_name})
    if(NOT "${_labels}" STREQUAL "")
        set_tests_properties(${_name} PROPERTIES LABELS "${_labels}")
    endif()
endmacro()

macro(add_lslib_test _name _labels)
    add_test(${_name} ${CMAKE_SOURCE_DIR}/LSDALTON/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-lslib_test" ${_name})
    if(NOT "${_labels}" STREQUAL "")
        set_tests_properties(${_name} PROPERTIES LABELS "${_labels}")
    endif()
endmacro()

macro(add_restart_test _name _labels)
    add_test(${_name} ${CMAKE_SOURCE_DIR}/LSDALTON/test/TEST -lsdalton ${CMAKE_BINARY_DIR}/lsdalton -param "-restart -D" ${_name})
    if(NOT "${_labels}" STREQUAL "")
        set_tests_properties(${_name} PROPERTIES LABELS "${_labels}")
    endif()
endmacro()

macro(add_lsdalton_runtest _name _labels)
    add_test(
        ${_name}
        python ${CMAKE_SOURCE_DIR}/LSDALTON/test/${_name}/test --binary-dir=${PROJECT_BINARY_DIR} --work-dir=${PROJECT_BINARY_DIR}/test/${_name} --verbose --log=${PROJECT_BINARY_DIR}/test/${_name}/runtest.stderr.log)
    if(NOT "${_labels}" STREQUAL "")
        set_tests_properties(${_name} PROPERTIES LABELS "${_labels}")
    endif()
endmacro()

# ALL tests here should contain the label "linsca"
# (label "lsdalton" will be matched by "ctest -L dalton" and should
#  therefore not be used.)

if(ENABLE_INTEREST)
  add_lsdalton_test(LSint/LSDALTON_interest                          "linsca;interest")
endif()

if(ENABLE_MPI AND ENABLE_SCALAPACK AND NOT USE_32BIT_MPI_INTERFACE)
  add_lsdalton_test(SCALAPACK/linsca_arh_SCALAPACK                  "linsca;scalapack")
  add_lsdalton_test(SCALAPACK/linsca_atoms_SCALAPACK                "linsca;scalapack")
  add_lsdalton_runtest(SCALAPACK/linsca_energy_SCALAPACK            "linsca;scalapack")
  add_lsdalton_runtest(SCALAPACK/linsca_energy_SCALAPACK_denselevel2 "linsca;scalapack")
  add_lsdalton_runtest(SCALAPACK/linsca_energy_SCALAPACK_GroupSize  "linsca;scalapack")
  add_lsdalton_test(SCALAPACK/linsca_trilevel_2nd_local_SCALAPACK   "linsca;scalapack")
  add_lsdalton_test(SCALAPACK/linsca_trilevel_2nd_all_SCALAPACK     "linsca;scalapack")
  add_lsdalton_test(SCALAPACK/LSDALTON_DENSFIT_FMM_SCALAPACK        "linsca;scalapack")
  add_lsdalton_runtest(SCALAPACK/LSDALTON_FMM_SCALAPACK             "linsca;scalapack")
  add_lsdalton_test(SCALAPACK/LSDALTON_ethane_dft_molgrad_SCALAPACK "linsca;scalapack")
  if(ENABLE_RSP)
    add_lsdalton_test(SCALAPACK/LSresponse_DFT_beta_SCALAPACK         "linsca;scalapack;lsresponse")
  endif()
  add_lsdalton_test(SCALAPACK/linsca_arh_SCALAPACK_MEMDIST          "linsca;scalapack")
  add_lsdalton_test(SCALAPACK/linsca_atoms_SCALAPACK_MEMDIST        "linsca;scalapack")
  if(ENABLE_DEC)
    add_lsdalton_test(SCALAPACK/decmp2_geoopt_scalapack               "linsca;scalapack;dec")
  endif()
endif()

if(ENABLE_MPI)
   if(ENABLE_TENSORS)
      add_lsdalton_runtest(SCALAPACK/linsca_energy_PDMM                     "linsca;pdmm")
   endif()
endif()

if(ENABLE_RSP)
  if(ENABLE_XCFUN)
    add_lsdalton_runtest(LSresponse/LSresponse_xcfun_lda_molgrad "linsca;xcfun;lsresponse")
    add_lsdalton_runtest(LSresponse/LSresponse_xcfun_gga_molgrad "linsca;xcfun;lsresponse")
    add_lsdalton_runtest(LSresponse/LSresponse_xcfun_lda_linrsp  "linsca;xcfun;lsresponse")
    add_lsdalton_runtest(LSresponse/LSresponse_xcfun_gga_linrsp  "linsca;xcfun;lsresponse")
  endif()
endif()

if(ENABLE_OPENRSP)
  add_lsdalton_test(LSint/LSDALTON_gen1int                  "linsca")
endif()

if(ENABLE_CSR)
  add_lsdalton_test(csr/linsca_atoms_csr_debug              "linsca;csr")
  add_lsdalton_test(csr/linsca_energy_csr                   "linsca;csr")
  add_lsdalton_test(csr/linsca_onestep_csr                  "linsca;csr")
  add_lsdalton_test(csr/LSDALTON_INCREM_csr                 "linsca;csr")
  add_lsdalton_test(csr/LSDALTON_FMM_csr                    "linsca;csr")
  add_lsdalton_test(csr/LSDALTON_ethane_dft_molgrad_csr     "linsca;csr")
  #   add_lsdalton_test(csr/linsca_direct_dens_csr              "linsca;csr")
  #   add_lsdalton_test(csr/linsca_trilevel_2nd_local_csr       "linsca;csr")
  #   add_lsdalton_test(csr/linsca_trilevel_2nd_all_csr         "linsca;csr")
  #   add_lsdalton_test(csr/linsca_atoms_csr                    "linsca;csr")
  #   add_lsdalton_test(csr/linsca_rhf_stability_csr            "linsca;csr")
  #   add_lsdalton_test(csr/linsca_trilevel_csr                 "linsca;csr")
  #   add_lsdalton_test(csr/LSDALTON_DENSFIT_FMM_csr            "linsca;csr")
endif()

add_lslib_test(LSlib/LSlib_cam_reg                               "linsca;lslib")
add_lslib_test(LSlib/LSlib_cam_dfJ_admm                          "linsca;lslib")

add_lsdalton_runtest(linsca/linsca_energy                        "linsca;quick")
add_lsdalton_runtest(linsca/linsca_mwpurifyatomstart             "linsca")
add_lsdalton_runtest(linsca/linsca_symtest                       "linsca;quick")
add_lsdalton_test(linsca/linsca_counterpoise                     "linsca")
add_lsdalton_test(linsca/linsca_energy_Si                        "linsca")
add_restart_test(linsca/linsca_energy_restart                    "linsca;quick;restart")
add_lsdalton_test(linsca/linsca_VanLenthe                        "linsca")
add_lsdalton_test(linsca/linsca_emsl                             "linsca")
add_lsdalton_test(linsca/linsca_las                              "linsca")
add_lsdalton_runtest(linsca/linsca_admm1                         "linsca")
if(ENABLE_RSP)
  add_lsdalton_runtest(linsca/linsca_admm                          "linsca;lsresponse")
  add_lsdalton_runtest(linsca/linsca_admm_rapid                    "linsca;lsresponse;essential;rapid")
  add_lsdalton_runtest(linsca/linsca_admm_df                       "linsca;lsresponse")
  add_lsdalton_runtest(linsca/linsca_admm2                         "linsca")
  add_lsdalton_runtest(linsca/linsca_admmQ                         "linsca")
  add_lsdalton_runtest(linsca/linsca_admmP                         "linsca")
  add_lsdalton_runtest(linsca/linsca_admmS                         "linsca")
  add_lsdalton_runtest(linsca/linsca_admmS-KT3X                    "linsca")
endif()
add_lsdalton_runtest(linsca/linsca_admm_basopt                   "linsca")
add_lsdalton_test(linsca/linsca_dft_energy                       "linsca")
add_lsdalton_test(linsca/linsca_rhf_stability                    "linsca")
#   add_lsdalton_test(linsca/linsca_direct_dens                      "linsca")
add_lsdalton_test(linsca/linsca_arh                              "linsca")
add_lsdalton_test(linsca/linsca_arh_davidson                     "linsca")
add_lsdalton_test(linsca/linsca_arh_ls_davidson                  "linsca")
add_lsdalton_test(linsca/linsca_trilevel_2nd_local               "linsca")
add_lsdalton_test(linsca/linsca_trilevel_2nd_all                 "linsca")
add_lsdalton_runtest(linsca/linsca_atoms                         "linsca")
add_lsdalton_test(linsca/lsdalton_dft_ssfgrid                    "linsca")
add_lsdalton_runtest(linsca/linsca_pfm                           "linsca;OrbLoc")
add_lsdalton_runtest(linsca/PipekMezeyLowdin                     "linsca;OrbLoc")
add_lsdalton_test(linsca/PipekMezeyMulliken                      "linsca;OrbLoc")
add_lsdalton_test(linsca/linsca_lcm_nongc                        "linsca;OrbLoc")
add_lsdalton_test(linsca/test_soeo                               "linsca")
add_lsdalton_test(LSint/LSDALTON_b3lyp_water                     "linsca")
add_lsdalton_test(LSint/LSDALTON_userdefined_basis1              "linsca")
add_lsdalton_test(LSint/LSDALTON_userdefined_basis2              "linsca")
add_lsdalton_test(LSint/LSDALTON_NOBQBQ2                         "linsca")
add_lsdalton_test(LSint/LSDALTON_pointcharge                     "linsca")
add_lsdalton_test(LSint/LSDALTON_pointcharge2                    "linsca")
add_lsdalton_test(LSint/LSDALTON_phantom                         "linsca")
add_lsdalton_test(LSint/LSDALTON_phantom2                        "linsca")
add_lsdalton_test(LSint/LSDALTON_EP                              "linsca")
add_lsdalton_test(LSint/LSDALTON_PropertyTest1                   "linsca")
add_lsdalton_test(LSint/LSDALTON_contang                         "linsca")
if(NOT ENABLE_MPI)
  add_lsdalton_test(LSint/LSDALTON_geoderiv                        "linsca")
endif()
add_lsdalton_test(LSint/LSDALTON_magderiv                        "linsca")
add_lsdalton_test(LSint/LSDALTON_magderiv2                       "linsca")
add_lsdalton_test(LSint/LSDALTON_magderiv3                       "linsca")
add_lsdalton_test(LSint/LSDALTON_camb3lyp                        "linsca")
add_lsdalton_test(LSint/LSDALTON_camb3lyp2                       "linsca")
add_lsdalton_test(LSint/LSDALTON_screen1                         "linsca")
add_lsdalton_test(LSint/LSDALTON_screen2                         "linsca")
add_lsdalton_test(LSint/LSDALTON_cartesian_ecoeff                "linsca")
add_lsdalton_test(LSint/LSDALTON_MBIE                            "linsca")
add_lsdalton_test(LSint/LSDALTON_DaLink                          "linsca")
add_lsdalton_test(LSint/LSDALTON_DaLink2                         "linsca")
add_lsdalton_test(LSint/LSDALTON_DENSFIT_FMM                     "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftdisp_d2_b3lyp               "linsca") 
add_lsdalton_runtest(dft/LSDALTON_dftdisp_d2_blyp                "linsca")  
add_lsdalton_runtest(dft/LSDALTON_dftdisp_d2_bp86                "linsca")  
add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3_Slater              "linsca")    
add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3_b3lyp               "linsca")   
add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3_camb3lyp            "linsca")      
add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3_olyp                "linsca")  
add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3_blyp                "linsca")  
add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3_bp86                "linsca")  
add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3bj_b3lyp             "linsca")     
add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3bj_camb3lyp          "linsca")        
add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3bj_olyp              "linsca")    
add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3bj_blyp              "linsca")    
add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3bj_bp86              "linsca") 
#Special case for pbe and pbe0 due to a ~e-5 discreapancy between Pawel Salek's 
#PSFUN code and XCFUN. XCFUN pbe version is correct, and PSFUN is only slightly 
#wrong
if(ENABLE_XCFUN)
  add_lsdalton_runtest(dft/LSDALTON_dftdisp_d2_pbe                 "linsca") 
  add_lsdalton_runtest(dft/LSDALTON_dftdisp_d2_pbe0                "linsca")  
  add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3_pbe                 "linsca") 
  add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3_pbe0                "linsca")  
  add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3bj_pbe               "linsca")   
  add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3bj_pbe0              "linsca")    
  add_lsdalton_runtest(linsca/linsca_trilevel                      "linsca")
  add_lsdalton_runtest(dft/LSDALTON_dftfunc_xcfun_pbe0             "linsca")
  add_lsdalton_runtest(dft/LSDALTON_dftfunc_xcfun_pbe              "linsca")
  add_lsdalton_runtest(LSint/LSDALTON_dftfunc_GGAKey               "linsca")
  add_lsdalton_runtest(LSint/LSDALTON_UDFT                         "linsca")
  add_lsdalton_runtest(dft/LSDALTON_dftfunc_b97-1                  "linsca")
else()
  add_lsdalton_runtest(dft/LSDALTON_dftdisp_d2_psfun_pbe           "linsca")  
  add_lsdalton_runtest(dft/LSDALTON_dftdisp_d2_psfun_pbe0          "linsca")  
  add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3_psfun_pbe           "linsca") 
  add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3_psfun_pbe0          "linsca")  
  add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3bj_psfun_pbe         "linsca")   
  add_lsdalton_runtest(dft/LSDALTON_dftdisp_d3bj_psfun_pbe0        "linsca")    
  add_lsdalton_runtest(dft/LSDALTON_dftfunc_psfun_pbe0             "linsca")
  add_lsdalton_runtest(dft/LSDALTON_dftfunc_psfun_pbe              "linsca")
  add_lsdalton_runtest(linsca/linsca_trilevel_psfun                "linsca")
  add_lsdalton_test(LSint/LSDALTON_dftfunc_GGAKey_psfun            "linsca")
  add_lsdalton_runtest(LSint/LSDALTON_UDFT_psfun                   "linsca")
  add_lsdalton_runtest(dft/LSDALTON_dftfunc_b97-1_psfun            "linsca")
endif()
add_lsdalton_runtest(dft/LSDALTON_dftfunc_vwn3                   "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_bp86                   "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_bpw91                  "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_pw86x                  "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_lda                    "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_svwn5                  "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_svwn3                  "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_b3lyp                  "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_b3lyp-g                "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_b3p86                  "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_b3p86-g                "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_blyp                   "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_kt1                    "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_kt2                    "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_kt3                    "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_olyp                   "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_camb3lyp               "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_camb3lyp100            "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_becke                  "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_slater                 "linsca")
add_lsdalton_runtest(dft/LSDALTON_dftfunc_psfun_lb94             "linsca")
add_lsdalton_test(LSint/LSDALTON_dftfunc_bp86                    "linsca")
add_lsdalton_test(LSint/LSDALTON_dftfunc_bpw91                   "linsca")
add_lsdalton_test(LSint/LSDALTON_dftfunc_kt3                     "linsca")
add_lsdalton_test(LSint/LSDALTON_dftfunc_lb94                    "linsca")
add_lsdalton_test(LSint/LSDALTON_dftfunc_psfun_pbe0              "linsca")
add_lsdalton_test(LSint/LSDALTON_dftfunc_pw86x                   "linsca")
add_lsdalton_test(LSint/LSDALTON_dftfunc_vwn3                    "linsca")
if(ENABLE_RSP)
  add_lsdalton_test(LSint/LSDALTON_ethane_df_dft_molgrad           "linsca;lsresponse")
  add_lsdalton_test(LSint/LSDALTON_ethane_dft_molgrad              "linsca;lsresponse")
  add_lsdalton_test(LSint/LSDALTON_ethane_dft_disp                 "linsca;lsresponse")
  add_lsdalton_test(LSint/LSDALTON_ethane_dft_D2disp               "linsca;lsresponse")
  add_lsdalton_test(LSint/LSDALTON_ethane_dft_D3disp               "linsca;lsresponse")
  add_lsdalton_test(LSint/LSDALTON_ethane_dft_D3bjdisp             "linsca;lsresponse")
endif()
add_lsdalton_runtest(LSint/LSDALTON_segmented                    "linsca")
add_lsdalton_test(LSint/LSDALTON_ethane_df_lda_jengine           "linsca")
add_lsdalton_test(LSint/LSDALTON_ethane_df_overlap_lda           "linsca")
add_lsdalton_test(LSint/LSDALTON_ethane_lda_jengine              "linsca")
add_lsdalton_runtest(LSint/LSDALTON_FMM                          "linsca")
add_lsdalton_test(LSint/LSDALTON_FMM_trilevel                    "linsca")
#   add_lsdalton_test(LSint/LSDALTON_fmm_gradient                    "linsca")
#   add_lsdalton_test(LSint/LSDALTON_fmm_df_gradient                 "linsca")
#   add_lsdalton_test(LSint/LSDALTON_fmm_twoel_gradient              "linsca")
add_lsdalton_test(LSint/LSDALTON_INCREM                          "linsca")
add_lsdalton_test(LSint/LSDALTON_INCREM2                         "linsca")
add_lsdalton_test(LSint/LSDALTON_J_NSETUV                        "linsca")
add_lsdalton_runtest(LSint/LSDALTON_Link                         "linsca")
add_lsdalton_test(LSint/LSDALTON_NOFAMILY                        "linsca")
add_lsdalton_test(LSint/LSDALTON_pass                            "linsca")
add_lsdalton_test(LSint/LSDALTON_PrimAng                         "linsca")
add_lsdalton_test(LSint/LSDALTON_ethane_dfK_dft                  "linsca")
add_lsdalton_runtest(LSint/LSDALTON_ethane_pari_b3lyp               "linsca")
add_lsdalton_runtest(LSint/LSDALTON_ethane_pari_b3lyp_unconstrained "linsca")
add_lsdalton_runtest(LSint/LSDALTON_ethane_pari_b3lyp_ChgConst      "linsca")
add_lsdalton_runtest(LSint/LSDALTON_ethane_pari_b3lyp_ChgDipConst   "linsca")
add_lsdalton_runtest(LSint/LSDALTON_moparik                      "linsca")
add_lsdalton_runtest(LSint/LSDALTON_hodi                         "linsca")
add_lsdalton_test(LSint/LSDALTON_UNCONT                          "linsca")
add_lsdalton_test(LSint/LSDALTON_HF_cartesian                    "linsca")
add_lsdalton_test(LSint/LSDALTON_augTZ                           "linsca")
add_lsdalton_test(LSint/LSDALTON_donotsavegab                    "linsca")
add_lsdalton_test(LSint/LSDALTON_INCREMDALINK                    "linsca")
add_lsdalton_test(LSint/LSDALTON_SR_EXCHANGE                     "linsca")
add_lsdalton_test(LSint/LSDALTON_LSlib                           "linsca")
add_lsdalton_test(LSint/LSDALTON_UHF_DEFAULT                     "linsca")
add_lsdalton_test(LSint/LSDALTON_UHF_hessian                     "linsca")
add_lsdalton_test(LSint/LSDALTON_UHF_JENGINE                     "linsca")
add_lsdalton_test(LSint/LSDALTON_UHF_JENGINE_LINK                "linsca;essential;rapid")
add_lsdalton_test(LSint/LSDALTON_UHF_LINK                        "linsca")
add_lsdalton_test(linsca/linsca_unrest_energy                    "linsca")
add_lsdalton_test(linsca/linsca_unrest_dft_energy                "linsca")
add_lsdalton_test(linsca/linsca_uhf_stability                    "linsca")

if(ENABLE_RSP)
  add_lsdalton_test(LSresponse/LSresponse_HF_alpha                 "linsca;lsresponse")
  #    add_lsdalton_test(LSresponse/LSresponse_HF_alpha_admm              "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_HF_alpha_astv            "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_HF_beta                  "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_HF_dipole                "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_HF_dtpa                  "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_HF_esd                   "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_HF_esg                   "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_HF_gamma                 "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_HF_gamma_lcm             "linsca;lsresponse")
  add_lsdalton_runtest(LSresponse/LSresponse_HF_molgra             "linsca;lsresponse;essential;rapid")
  add_lsdalton_test(LSresponse/LSresponse_HF_opa                   "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_HF_tpa                   "linsca;lsresponse")
  add_lsdalton_runtest(LSresponse/LSresponse_DFT_alpha             "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_DFT_alpha_aptv           "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_DFT_beta                 "linsca;lsresponse")
  add_lsdalton_runtest(LSresponse/LSresponse_DFT_beta_quick        "linsca;lsresponse;rapid")
  add_lsdalton_runtest(LSresponse/LSresponse_HF_DipoleMat          "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_DFT_dipole               "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_DFT_esd                  "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_DFT_esg                  "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_DFT_esg_LDA              "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_DFT_excit                "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_DFT_dtpa                 "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_DFT_molgra               "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_DFT_opa                  "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_DFT_tpa                  "linsca;lsresponse")
  add_lsdalton_runtest(LSresponse/LSresponse_NMR_SHIELD            "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_mcd                      "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_mcd2                     "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_mcd3                     "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_mcd_calc                 "linsca;lsresponse")
  add_lsdalton_test(LSresponse/LSresponse_excit_cs00               "linsca;lsresponse")
  add_restart_test(LSresponse/LSresponse_excit_restart             "linsca;lsresponse;restart")
  add_lsdalton_test(geomopt/Excited_state_opt                      "linsca;lsresponse")
endif()
add_lsdalton_runtest(LSresponse/LSresponse_NMR_SHIELD_NoOpenRSP  "linsca;lsresponse")
add_lsdalton_runtest(LSresponse/LSresponse_NMR_IANS_SHIELD_NoOpenRSP  "linsca;lsresponse")
add_lsdalton_runtest(LSresponse/LSresponse_DFT_alpha_NoOpenRSP   "linsca;lsresponse")
add_lsdalton_runtest(LSresponse/LSresponse_DFT_excit_NoOpenRSP   "linsca;lsresponse")
add_lsdalton_test(geomopt/geoopt_constrain                       "linsca")
add_lsdalton_test(geomopt/cartes_bfgs_min                        "linsca")
add_lsdalton_test(geomopt/redint_bfgs                            "linsca")
add_lsdalton_test(geomopt/redint_bofill_ts                       "linsca")
add_lsdalton_test(geomopt/cartes_trilevel_newconv                "linsca")
add_lsdalton_test(geomopt/cartes_psb_min                         "linsca")
add_lsdalton_runtest(geomopt/geoopt_rapid                        "linsca;rapid")
add_lsdalton_test(ddynam/H2O_NHchain                             "linsca;ddynam")
add_lsdalton_test(ddynam/HCN_ddyn                                "linsca;ddynam")
add_lsdalton_test(ddynam/HF_vib                                  "linsca;ddynam")
add_lsdalton_test(ddynam/H2O_fmd                                 "linsca;ddynam")
add_lsdalton_runtest(ddynam/ddyn_rapid                           "linsca;ddynam;rapid")
if(ENABLE_DEC)
  add_lsdalton_runtest(dectests/decmp2_energy                      "linsca;dec")
  add_lsdalton_runtest(dectests/decmp2_density                     "linsca;dec")
  add_lsdalton_runtest(dectests/decmp2_gradient                    "linsca;dec")
  add_lsdalton_runtest(dectests/decmp2_geoopt                      "linsca;dec")
  add_lsdalton_runtest(dectests/fullmp2_energy                     "linsca;dec;fulldec")
  add_lsdalton_runtest(dectests/fullmpmp2                          "linsca;dec;fulldec")
  add_lsdalton_runtest(dectests/fullmp2_energyCC                   "linsca;dec;fulldec")
  add_lsdalton_runtest(dectests/fullmp3_energy                     "linsca;dec;fulldec")
  add_lsdalton_runtest(dectests/fullcc2                            "linsca;dec;fulldec")
  add_lsdalton_runtest(dectests/fullccsd_4                         "linsca;dec;fulldec")
  add_lsdalton_runtest(dectests/fullrimp2                          "linsca;dec;fulldec")
  add_lsdalton_runtest(dectests/fullrimp2naf                       "linsca;dec;fulldec")
  add_lsdalton_runtest(dectests/fullrimp2_memred                   "linsca;dec;fulldec")
  add_lsdalton_runtest(dectests/fullrimp2_pdm                      "linsca;dec;fulldec")
  add_lsdalton_runtest(dectests/decrimp2                           "linsca;dec")
  add_lsdalton_runtest(dectests/decrimp2_density                   "linsca;dec")
  add_lsdalton_runtest(dectests/decrimp2_gradient                  "linsca;dec")
  add_lsdalton_runtest(dectests/decrimp2laplace                    "linsca;dec;fulldec")
  add_lsdalton_runtest(dectests/snoopmp2                           "linsca;dec;fulldec")
  add_lsdalton_runtest(dectests/snoopmp2_ghost                     "linsca;dec;fulldec")
  if(ENABLE_MPI)
    add_lsdalton_runtest(dectests/fullccsd_3                         "linsca;dec;fulldec")
    add_lsdalton_test(dectests/fullccsd_2                            "linsca;dec;fulldec")
  endif()
  add_lsdalton_runtest(dectests/fullccsd_restart                   "linsca;dec;fulldec;restart")
  add_lsdalton_runtest(dectests/decmp2_gradient_debug              "linsca;dec")
  add_lsdalton_runtest(dectests/ccsd_counterpoise                  "linsca;dec;decccsd")
  add_lsdalton_runtest(dectests/decmp2_counterpoise                "linsca;dec;decccsd")
  add_lsdalton_runtest(dectests/decmp2_fragopt                     "linsca;dec;decccsd;essential;rapid")

  add_lsdalton_runtest(dectests/fullrimp2f12             "linsca;dec;fulldec;f12")
  add_lsdalton_runtest(dectests/fullrimp2f12_fc          "linsca;dec;fulldec;f12")
  add_lsdalton_runtest(dectests/fullrimp2f12nls          "linsca;dec;fulldec;f12")
  add_lsdalton_runtest(dectests/fullmp2_f12              "linsca;dec;fulldec;f12")    
  add_lsdalton_runtest(dectests/fullmp2_local_f12        "linsca;dec;fulldec;f12")
  add_lsdalton_runtest(dectests/fullccsd_f12             "linsca;dec;fulldec;f12")
  add_lsdalton_runtest(dectests/decmp2f12                "linsca;dec;f12")
  add_lsdalton_runtest(dectests/decmp2f12_h2             "linsca;dec;f12")
  add_lsdalton_runtest(dectests/decmp2f12_quick          "linsca;dec;f12,rapid")
  add_lsdalton_runtest(dectests/decrimp2_f12             "linsca;dec;f12")
  add_lsdalton_runtest(dectests/decrimp2_f12_fc          "linsca;dec;f12")
endif()
add_lsdalton_runtest(plt/plt_dens                                "linsca;plot")
add_lsdalton_runtest(plt/plt_ep                                  "linsca;plot")

if(ENABLE_ICHOR)
  add_lsdalton_runtest(IchorTestDir/IchorThermiteTesting1   "linsca;ichor;rapid")
  add_lsdalton_runtest(IchorTestDir/IchorThermiteTesting2   "linsca;ichor;rapid")
  add_lsdalton_runtest(IchorTestDir/IchorThermiteTesting3   "linsca;ichor;rapid")
  add_lsdalton_runtest(IchorTestDir/IchorThermiteTesting4   "linsca;ichor;rapid")
  add_lsdalton_runtest(IchorTestDir/IchorThermiteTesting5   "linsca;ichor")
  add_lsdalton_runtest(IchorTestDir/Ichor2Center   "linsca;ichor")
  add_lsdalton_runtest(IchorTestDir/IchorThermiteTesting1Force "linsca;ichor")
  add_lsdalton_runtest(IchorTestDir/IchorThermiteTesting2Force "linsca;ichor")
  add_lsdalton_runtest(IchorTestDir/IchorThermiteTesting3Force "linsca;ichor")
  add_lsdalton_runtest(IchorTestDir/IchorThermiteTesting4Force "linsca;ichor")
  add_lsdalton_runtest(IchorTestDir/IchorThermiteTesting5Force "linsca;ichor")
  add_lsdalton_test(IchorTestDir/IchorThermiteTesting6   "linsca;ichor;rapid")
  add_lsdalton_test(IchorTestDir/IchorThermiteTesting7   "linsca;ichor")
  add_lsdalton_test(IchorTestDir/IchorThermiteTesting8   "linsca;ichor;rapid")
  add_lsdalton_test(IchorTestDir/IchorThermiteTesting9   "linsca;ichor")
  add_lsdalton_test(IchorTestDir/IchorThermiteTesting10  "linsca;ichor")
  add_lsdalton_test(IchorTestDir/IchorThermiteTesting11  "linsca;ichor")
  add_lsdalton_test(IchorTestDir/IchorThermiteTesting12  "linsca;ichor")
  if(ENABLE_DEC)
    add_lsdalton_runtest(IchorTestDir/IchorDecPackedTesting   "linsca;ichor")    
  endif()
  add_lsdalton_runtest(IchorTestDir/IchorProfile         "linsca;ichor")
endif()


if(DEVELOPMENT_CODE AND NOT ENABLE_RELEASE)
  add_lsdalton_test(LSint/LSDALTON_uncontAObatch         "linsca")
  add_lsdalton_runtest(geomopt/redint_numgrad            "linsca")
  if(ENABLE_RSP)
    add_lsdalton_test(LSint/LSDALTON_UHF_excit             "linsca")
    add_lsdalton_test(LSint/LSDALTON_UHF_excit2            "linsca")
    add_lsdalton_test(LSint/LSDALTON_UHF_excit_radical     "linsca")
    add_lsdalton_test(LSresponse/LSresponse_DFT_excit_beta "linsca;lsresponse")
    add_lsdalton_test(LSresponse/LSresponse_HF_gamma_SVD   "linsca;lsresponse")
  endif()
  if(ENABLE_DEC)
    #    add_lsdalton_runtest(dectests/decrimp2aux              "linsca;dec") 
    add_lsdalton_runtest(dectests/decnp_rimp2_inclfull     "linsca;dec")
    add_lsdalton_runtest(dectests/decmp2_StressTest        "linsca;dec")
    add_lsdalton_runtest(dectests/fullccsdpt               "linsca;dec;fulldec")
    add_lsdalton_runtest(dectests/fullccsdpt_abc           "linsca;dec;fulldec")
    if(ENABLE_REAL_SP)
      add_lsdalton_runtest(dectests/fullccsdpt_sp            "linsca;dec;fulldec")
      add_lsdalton_runtest(dectests/fullccsdpt_sp_abc        "linsca;dec;fulldec")
    endif()
    if(NOT ENABLE_REAL_SP)
      add_lsdalton_runtest(dectests/fullccsdpt_print         "linsca;dec;fulldec")
      add_lsdalton_runtest(dectests/fullccsdpt_abc_print     "linsca;dec;fulldec")
    endif()
    if(NOT ENABLE_MPI)
      add_lsdalton_runtest(dectests/ccsd_exci_right        "linsca;dec;fulldec")
      add_lsdalton_runtest(dectests/ccsd_exci_left         "linsca;dec;fulldec")
      add_lsdalton_runtest(dectests/peom_mbpt2_exci        "linsca;dec;fulldec")
    endif()
    add_lsdalton_runtest(dectests/decrpa_energy            "linsca;dec;rpa")
  endif()
  if(ENABLE_XCFUN)
    if(ENABLE_DEC)
      add_lsdalton_runtest(dectests/rpa_rsh                  "linsca;rpa")
      add_lsdalton_runtest(dectests/decrpa_rsh               "linsca;dec;rpa")
    endif()
  endif()
  if(ENABLE_DEC)
    if(ENABLE_MPI)
      add_lsdalton_runtest(dectests/fullccsd_0               "linsca;dec;fulldec")
    endif()
    add_lsdalton_runtest(dectests/fullccsd_5               "linsca;dec;fulldec")
    add_lsdalton_runtest(dectests/fullccsd_6               "linsca;dec;fulldec")
    if(NOT ENABLE_REAL_SP)
      add_lsdalton_runtest(dectests/decccsdpt_quick          "linsca;dec;decccsd;essential;rapid")
      add_lsdalton_runtest(dectests/decccsdpt_fragopt        "linsca;dec")
      add_lsdalton_runtest(dectests/decccsdpt_virt           "linsca;dec")
      add_lsdalton_runtest(dectests/decccsdpt_abc_occ        "linsca;dec")
      add_lsdalton_runtest(dectests/decccsdpt_simfull        "linsca;dec")
    endif()
    add_lsdalton_runtest(dectests/decmp2_gradient_debug2   "linsca;dec")
    add_lsdalton_runtest(dectests/decmp2_energy_FO         "linsca;dec")
    add_lsdalton_runtest(dectests/decmp2_energy_decnp      "linsca;dec")
    add_lsdalton_runtest(dectests/decmp2_energy_decco      "linsca;dec")
    add_lsdalton_runtest(dectests/decmp2_gradient_decco    "linsca;dec")
    add_lsdalton_runtest(dectests/decmp2_geoopt_FO         "linsca;dec")
    add_lsdalton_runtest(dectests/decccsd_no_MO            "linsca;dec;decccsd")
    add_lsdalton_runtest(dectests/decccsd_BSSE             "linsca;dec;decccsd")
    add_lsdalton_runtest(dectests/decccsd_restart          "linsca;dec;decccsd;restart")
    add_lsdalton_runtest(dectests/decmp2_restart           "linsca;dec;restart")
    add_lsdalton_runtest(dectests/deccc2                   "linsca;dec")
    add_lsdalton_runtest(dectests/fullccsd_debug_mult      "linsca;dec;fulldec")
    add_lsdalton_runtest(dectests/decccsd_pno              "linsca;dec;decccsd")
  endif()
  add_lsdalton_runtest(pbc2/pbc2_h2fock                     "linsca;pbc")
  add_lsdalton_runtest(pbc2/pbc2_h2SCF_iter1                "linsca;pbc")
  add_lsdalton_runtest(pbc2/pbc2_h2STO6G                    "linsca;pbc")
  add_lsdalton_runtest(pbc2/pbc2_h2mol                      "linsca;pbc")
endif()
if(ENABLE_RSP)
  if(NOT ENABLE_MPI)
    #   add_lsdalton_test(LSresponse/LSresponse_HF_molHessian  "linsca;lsresponse")
  endif()
endif()
if(ENABLE_PCMSOLVER)
  add_lsdalton_runtest(ls_pcm "linsca;runtest;lspcm;pcm")
endif()
