#!/usr/bin/env python
#    prop_cpp_ecd
#    --------
#    Molecule:         CHBrClF
#    Wave Function:    HF
#    Test Purpose:     Electronic circular dichroism (ECD) using CPP
#                      the algorithm with symmetrized trial vectors

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(string = 'Final HF energy',
      rel_tolerance = 1.0e-9)

f.add(from_string = 'Dipole moment',
      num_lines = 5,
      mask = [1],
      rel_tolerance = 1.0e-5)

# Optical Rotation and Electronic Circular Dichroism
f.add(from_string = 'G tensor for frequency',
      num_lines = 17,
      rel_tolerance = 1.0e-4)

test.run(['prop_cpp_ecd.dal'], ['CHBrClF_3-21G.mol'], f={'out': f})

sys.exit(test.return_code)
