#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final DFT energy',
      rel_tolerance = 1.0e-8)

f.add(string = '@ Excitation energy :',
      abs_tolerance = 1.0e-6)

test.run(['dft_pbe.dal'], ['He_cc-pVTZ.mol'], {'out': f})

sys.exit(test.return_code)
