#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(from_string = 'Final geometry (xyz',
      num_lines = 8,
      abs_tolerance = 2.0e-4)

test.run(['pehf_geoopt.dal'], ['water.mol'], ['14h2o.pot'], f={'out': f})

sys.exit(test.return_code)
