      PARAMETER ( MXCRF=900, NMXXYVEC=900, MXCRFEQTO=900 )
      REAL*8 ABS_FREQ_GAMMA_B(NMXFREQ), ABS_FREQ_GAMMA_C(NMXFREQ),      &
     &     ABS_FREQ_GAMMA_D(NMXFREQ), ABS_CRFFRQ(MXCRF,4),              &
     &     RES_CRF(MXCRF,2), ABS_XYFREQ(NMXXYVEC,2),                    &
     &     ABS_CRFFRQ_EQTO(MXCRFEQTO,4)
      LOGICAL ABSLRS_IDRI, ABS_IDRI_XY, ABS_OTOF_GAMMA,                 &
     &     ABS_GAMMA_ELEMENT, ABS_GAMMA_ALLELE
      INTEGER ABS_NFREQ_GAMMA_B, ABS_NFREQ_GAMMA_C,                     &
     &     ABS_NFREQ_GAMMA_D, ABS_CRFSYM(MXCRF,4), ABS_NCRF,            &
     &     ABS_NXYVEC, ABS_XYMEMREF(NMXXYVEC), ABS_XYSYM(NMXXYVEC, 2),  &
     &     ABS_NELEMENTS_GAMMA, ABS_CRF_NEQTO,                          &
     &     ABS_CRF_EQTO(MXCRFEQTO), ABS_CRFSYM_EQTO(MXCRFEQTO,4)
      CHARACTER*8 ABS_CRFLAB(MXCRF,4), ABS_XYLAB(NMXXYVEC,2),           &
     &     ABS_ELEMENTS_GAMMA(81), ABS_CRFLAB_EQTO(MXCRFEQTO,4)
!
      COMMON /ABS_CRS1/ ABS_FREQ_GAMMA_B, ABS_FREQ_GAMMA_C,             &
     &     ABS_FREQ_GAMMA_D, ABS_CRFFRQ, RES_CRF, ABS_XYFREQ,           &
     &     ABS_CRFFRQ_EQTO
      COMMON /ABS_CRS2/ ABSLRS_IDRI, ABS_IDRI_XY, ABS_OTOF_GAMMA,       &
     &     ABS_GAMMA_ELEMENT, ABS_GAMMA_ALLELE
      COMMON /ABS_CRS3/ ABS_NFREQ_GAMMA_B, ABS_NFREQ_GAMMA_C,           &
     &     ABS_NFREQ_GAMMA_D, ABS_CRFSYM, ABS_NCRF, ABS_NXYVEC,         &
     &     ABS_XYMEMREF, ABS_XYSYM, ABS_NELEMENTS_GAMMA, ABS_CRF_NEQTO, &
     &     ABS_CRF_EQTO, ABS_CRFSYM_EQTO                                
      COMMON /ABS_CRS4/ ABS_CRFLAB, ABS_XYLAB, ABS_ELEMENTS_GAMMA,      &
     &     ABS_CRFLAB_EQTO
