!  abslrs.h
      INTEGER NMXFREQ
      PARAMETER ( NMXFREQ=300 )
      REAL*8 ABS_DAMP,ABS_THCLR,ABS_RESID(3,NMXFREQ,3,8),               &
     &     ABS_FREQ_ALPHA(NMXFREQ),ABS_FREQ_INTERVAL(3),                &
     &     ABS_THD_LD,ABS_FREQ_BETA_B(NMXFREQ),ABS_BFREQ_INTERVAL(3),   &
     &     ABS_FREQ_BETA_C(NMXFREQ),ABS_CFREQ_INTERVAL(3)
      LOGICAL ABSLRS,ABSLRS_ALPHA,ABSLRS_ANALYZE,ABSLRS_INTERVAL,       &
     &        ABS_IMFREQ,ABS_BATCH,ABS_DALINP,ABSLRS_MCD,               &
     &        ABSLRS_MCHD,ABSLRS_NSCD,ABSQRS_INTERVAL,ABSLRS_BETA,      &
     &        ABSLRS_GAMMA,ABSLRS_SHG,ABSQRS_CINTERVAL,ABS_OLDCPP,      &
     &        ABS_XREL,ABS_REBD,ABS_NGD,ABS_GDCOMPLEX
      INTEGER ABS_MAXRM,ABS_NFREQ_ALPHA,ABS_NFREQ_INTERVAL,             &
     &     ABS_MAXITER,IPRABSLRS,ABS_NOPER(8),ABS_NBATCHMAX,            &
     &     ABS_GRADSYM,ABS_MULD2H(8,8),ABS_NSYM,ABS_NASH(8),            &
     &     ABS_NISH(8),ABS_NORB(8),ABS_NFREQ_BETA_B,ABS_KLRED(2),       &
     &     ABS_NFREQ_BETA_C,                                            &
     &     LUABSPRI, LUABSVECS,LUSB, LUAB, LUSS, LUAS, LUE1RED,         &
     &     LUE2RED, LUSRED
      CHARACTER*8 ABS_LABOP(12,8)
!
      COMMON /ABS_LRS1/ ABS_DAMP,ABS_THCLR,ABS_RESID,ABS_FREQ_ALPHA,    &
     &     ABS_FREQ_INTERVAL,ABS_THD_LD,ABS_FREQ_BETA_B,                &
     &     ABS_BFREQ_INTERVAL,ABS_FREQ_BETA_C,ABS_CFREQ_INTERVAL
      COMMON /ABS_LRS2/ ABSLRS,ABSLRS_ALPHA,ABSLRS_ANALYZE,             &
     &     ABSLRS_INTERVAL,ABS_IMFREQ,ABS_BATCH,ABS_DALINP,             &
     &     ABSLRS_MCD,ABSLRS_MCHD,ABSLRS_NSCD,ABSQRS_INTERVAL,          &
     &     ABSLRS_BETA,ABSLRS_GAMMA,ABSLRS_SHG,ABSQRS_CINTERVAL,        &
     &     ABS_OLDCPP,ABS_XREL,ABS_REBD,ABS_NGD,ABS_GDCOMPLEX
      COMMON /ABS_LRS3/ ABS_MAXRM,ABS_NFREQ_ALPHA,ABS_NOPER,            &
     &     ABS_NFREQ_INTERVAL,ABS_MAXITER,IPRABSLRS,                    &
     &     LUABSPRI, LUABSVECS ,ABS_NBATCHMAX, ABS_GRADSYM,             &
     &     ABS_NSYM,ABS_NASH,ABS_NISH,ABS_NORB,ABS_MULD2H,              &
     &     ABS_NFREQ_BETA_C,                                            &
     &     LUSB, LUAB, LUSS, LUAS, ABS_NFREQ_BETA_B,ABS_KLRED,          &
     &     LUE1RED,LUE2RED,LUSRED
      COMMON /ABS_LRS4/ ABS_LABOP
!  end of abslrs.h
