      INTEGER NRHFCORE, IRHFCORE, MAXCORE
      INTEGER NVIRION, IVIRION, MAXION
      PARAMETER (MAXCORE=5)
      PARAMETER (MAXION=1)
      LOGICAL LCVSEXCI, LIONIZEXCI, LBOTHEXCI, LRMCORE
      LOGICAL LCVSPTEXCI
      COMMON /CVSEPEXCI/ NRHFCORE(8),IRHFCORE(MAXCORE,8),
     &               LCVSEXCI,LRMCORE,
     &               NVIRION(8), IVIRION(MAXION,8),
     &               LIONIZEXCI, LBOTHEXCI, LCVSPTEXCI
