      INTEGER NRHFCORE, IRHFCORE, MAXCORE
      INTEGER NVIRION, IVIRION, MAXION
      PARAMETER (MAXCORE=5)
      PARAMETER (MAXION=1)
      LOGICAL LCVSLCZ, LIONIZLCZ, LBOTHLCZ
      COMMON /CVSLCZ/ NRHFCORE(8),IRHFCORE(MAXCORE,8),
     &               LCVSLCZ,
     &               NVIRION(8), IVIRION(MAXION,8),
     &               LIONIZLCZ, LBOTHLCZ
