      LOGICAL LDFTVXC, LLIN, LTAN, LGRAC,DOLB94,DOMPOLE
      DOUBLE PRECISION DFTIPTA, DFTIPTB, DFTHMO, DFTBR1, DFTBR2, EHOMO, &
     &                DISTMIN,DISTMAX,BRAG1,BRAG2,                      &
     &                DFTCH0, DFTCH1, DFTDST,SHF

      COMMON /DFTACB/ DFTIPTA, DFTIPTB, DFTHMO, DFTBR1, DFTBR2, EHOMO,  &
     &                DISTMIN,DISTMAX,BRAG1,BRAG2,SHF,                  &
     &                DFTCH0(MXCENT), DFTCH1(MXCENT), DFTDST(MXCENT),   &
     &                LDFTVXC,LLIN,LTAN,LGRAC,DOLB94,DOMPOLE

