      INTEGER, PARAMETER :: MAXJ = 4*(MXQN - 1) + 2
      INTEGER :: JMAX0
      REAL(KIND=8) :: WVAL
      REAL(KIND=8) :: FJW(0:MAXJ), TABFJW(121*(MAXJ+7))
      COMMON /GAMCOM/ WVAL, FJW, TABFJW, JMAX0
