      INTEGER MAXLLR
      PARAMETER ( MAXLLR = MAXLBL )
      REAL*8  THCLR, THRNRM
      INTEGER IPRLR, MAXITL, NGPLR
      LOGICAL LLROP, SOPRSY
      COMMON /INFLR/  THCLR, THRNRM,  IPRLR,  MAXITL, NGPLR(8),         &
     &                LLROP(MAXLLR), SOPRSY
      CHARACTER*8 LBLLR
      COMMON /CHRLR/  LBLLR(8,MAXLLR)
