      LOGICAL NWPROP, NOMOVE, FSTPRP, NUMELC, CMPARE, SDRTST,
     &        RESTRT, DRYRUN, FRSTNM, PRPVIB, ADSTBK, NOADSY,
     &        MANUAL, MDEANA, PRPONL, PRPBAS, C4FORC
      CHARACTER*80    PRPBTX
      DIMENSION KDRYRN(6)
      COMMON /NUMDER/ KDRYRN, NMORDR, NAORDR, NTORDR, NDCOOR,
     &                NMREDU, NUMCAL, MEMOFF, NMDPRP, NMRDRP,
     &                NARDRP, NMPCAL, NMEPRP, LUNDPR, NWPROP,
     &                NOMOVE, NUMELC, CMPARE, SDRTST, RESTRT,
     &                DRYRUN, FRSTNM, PRPVIB, MANUAL, ADSTBK,
     &                NOADSY, MDEANA, C4FORC
      COMMON /NMDPRP/ NMEXCI, FSTPRP, PRPONL, PRPBTX, PRPBAS,
     &                NMRDBK, NARDBK
