      INTEGER MXEPCM
      PARAMETER(MXEPCM = 20)
      INTEGER QSNFLG, QSEFLG, QSMMFLG, QSE1FLG, QSMM1FLG,
     *        VSNFLG, VSEFLG, VSMMFLG, VSE1FLG, VSMM1FLG,
     *        ICESPH, IPRPCM, IRETCAV, IPOLYG, ICOMPCM,
     *        NPCMMT, ISPHE, NESF, NESFP, NC, INA, IAN,
     *        IDXSPH, NVERT, NTS, NTSIRR, NRWCAV, LUPCMD,
     *        LUCAVD, LUPCMI
      REAL*8  OMEGA, RET, FRO, ALPHA, RIN, AREATS, EPS,
     *        EPSINF, DR, RSOLV, QSN, QSE, QSENEQ, QLOC,
     *        QSMM, QSE1, QSMM1, PCMEN, PCMEE, PCMNE,
     *        PCMNN, QNUC, FN, FE, VSN, VSE, VSMM, VSE1,
     *        VSMM1, XE, YE, ZE, RE, SSFE, STOT, VOL,
     *        RSPH, CCX, CCY, CCZ, XTSCOR, YTSCOR, ZTSCOR,
     *        AS, RDIF, DERCEN, DERRAD, POTCAVNUC, POTCAVELE
C
      COMMON /PCMCAV/ OMEGA,RET,FRO,ALPHA(MXSP),RIN(MXSP),ICESPH,
     *                IPRPCM,IRETCAV,IPOLYG,AREATS
      COMMON /PCMDAT/ EPS,EPSINF,DR,RSOLV,ICOMPCM,NPCMMT
      COMMON /CHGFLG/ QSNFLG, QSEFLG, QSMMFLG, QSE1FLG, QSMM1FLG
      COMMON /POTFLG/ VSNFLG, VSEFLG, VSMMFLG, VSE1FLG, VSMM1FLG
      COMMON /PCMCH/  QSN(MXTS),QSE(MXTS),QSENEQ(MXTS),QLOC(MXTS,3),
     *                QSMM(MXTS), QSE1(MXTS*MXEPCM),
     *                QSMM1(MXTS*MXEPCM),
     *                PCMEN,PCMEE,PCMNE,PCMNN,QNUC,FN,FE
      COMMON /PCMPOT/ VSN(MXTS),VSE(MXTS),
     *                VSMM(MXTS), VSE1(MXTS*MXEPCM), VSMM1(MXTS*MXEPCM)
      COMMON /PCMPLY/ XE(MXSP),YE(MXSP),ZE(MXSP),RE(MXSP),SSFE(MXSP),
     *                ISPHE(MXTS),STOT,VOL,NESF,NESFP,NC(30)
      COMMON /PCMSPH/ INA(MXSP),IAN(MXCENT), IDXSPH(MXCENT),
     $                RSPH(MXCENT)
      COMMON /PCMTES/ CCX,CCY,CCZ,XTSCOR(MXTSPT),YTSCOR(MXTSPT),
     *                ZTSCOR(MXTSPT),AS(MXTS),RDIF,NVERT(MXTS),NTS,
     *                NTSIRR,NRWCAV
      COMMON /LUPCM/  LUPCMD,LUCAVD,LUPCMI(8)
      COMMON /PCMDER/ DERCEN(MXSP,MXCENT,3,3),DERRAD(MXSP,MXCENT,3)
      COMMON /SURPOT/ POTCAVNUC(MXTS), POTCAVELE(MXTS)
