#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final MC-SRDFT energy',
      rel_tolerance = 1.0e-7)
f.add(string = '@ Excitation energy :',
      rel_tolerance = 1.0e-3)

test.run(['singlet_tpss_mu_zero_nosym.dal',
          'singlet_tpss_mu04.dal'],
         ['lih.mol', 'water.mol'],
         f={'out': f, 'out': f})

sys.exit(test.return_code)
