#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from runtest_lsdalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final HF energy',rel_tolerance = 1.0e-8)
f.add(string = 'Nuclear repulsion',rel_tolerance = 1.0e-8)
f.add(string = 'Energy at this geometry',rel_tolerance = 1.0e-8)
f.add(string = 'Norm of step',rel_tolerance = 1.0e-8)
f.add(string = 'Norm of gradient',rel_tolerance = 1.0e-8)

f.add(string = 'Energy at final geometry',rel_tolerance = 1.0e-8)
f.add(string = 'Energy change during optimization',rel_tolerance = 1.0e-8)

f.add(from_string = 'contribution to gradient',
      num_lines   = 8,
      ignore_below = 1.0e-7,
      abs_tolerance = 1.0e-6)
f.add(from_string = 'Molecular gradient',
      num_lines   = 8,
      ignore_below = 1.0e-7,
      abs_tolerance = 1.0e-6)
f.add(from_string = 'RMS gradient norm',
      abs_tolerance = 1.0e-6)
f.add(from_string = 'Final geometry',
      num_lines   = 25,
      abs_tolerance = 1.0e-6)

f.add(string = 'Allocated memory (TOTAL)')

test.run(['geoopt_rapid.dal'], ['Methane.mol'], {'out': f})

sys.exit(test.return_code)
