#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > LSresponse_DFT_excit_beta.info <<'%EOF%'
   LSresponse_DFT_excit_beta
   -------------------
   Molecule:         H2O2
   Wave Function:    DFT-B3LYP / STO-3G
   Test Purpose:     Test 1st hyperpolarizability in LSDalton (Kasper K).
                     
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > LSresponse_DFT_excit_beta.mol <<'%EOF%'
BASIS
STO-3G
Hydrogen Peroxide

AtomTypes=2 Generators=0
Charge=8.0 Atoms=2
O    -0.00000000  1.40784586 -0.09885600
O     0.00000000 -1.40784586 -0.09885600
Charge=1.0 Atoms=2
H     0.69081489  1.72614891  1.56891868
H    -0.69081489 -1.72614891  1.56891868
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > LSresponse_DFT_excit_beta.dal <<'%EOF%'
**WAVE FUNCTIONS
.DFT
B3LYP
*DENSOPT
.ARH DAVID
.CONVDYN
TIGHT
**RESPONS
.NEXCIT
3
*SOLVER
.EXCVECLINEQ
.CONVDYN
TIGHT
*BETA
.BFREQ
1
0.05
.CFREQ
1
0.05
*END OF INPUT  
%EOF%
#######################################################################

 

#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL > LSresponse_DFT_excit_beta.check
cat >> LSresponse_DFT_excit_beta.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# Energy
CRIT1=`$GREP "Final * DFT energy\: * \-149\.3649" $log | wc -l`
TEST[1]=`expr   $CRIT1`
CTRL[1]=1
ERROR[1]="DFT ENERGY NOT CORRECT -"

# Memory test
CRIT2=`$GREP "Allocated memory \(TOTAL\): * 0 byte" $log | wc -l`
TEST[2]=`expr  $CRIT2`
CTRL[2]=1
ERROR[2]="Memory leak -"

# excitation energies 
CRIT1=`$GREP "1 * 0\.21562" $log | wc -l`
CRIT2=`$GREP "2 * 0\.29489" $log | wc -l`
CRIT3=`$GREP "3 * 0\.37450" $log | wc -l`

TEST[3]=`expr  $CRIT1 \+ $CRIT2 \+ $CRIT3 `
CTRL[3]=3
ERROR[3]="Error in excitation energies"

# 1 hyperpolarizability tests
CRIT1=`$GREP "XXZ * \-2.23[8-9]" $log | wc -l`
CRIT2=`$GREP "ZYY * \-4.38[3-4]" $log | wc -l`
CRIT3=`$GREP "ZZZ * \-9.89[1-2]" $log | wc -l`

TEST[4]=`expr  $CRIT1 \+ $CRIT2 \+ $CRIT3 `
CTRL[4]=3
ERROR[4]="Error in 1st hyperpolarizability"

# Memory test
CRIT1=`$GREP "Use the * 3 excitation vectors from the rsp_eigenvecs file" $log | wc -l`
TEST[5]=`expr  $CRIT1`
CTRL[5]=6
ERROR[5]="Number of EXCVECLINEQ not correct -"

PASSED=1
for i in 1 2 3 4 5
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo ${ERROR[i]}
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
