#!/bin/sh
#
# This is the script for generating files for a specific Dalton test job.
#
# For the .check file ksh or bash is preferred, otherwise use sh
# (and hope it is not the old Bourne shell, which will not work)
#
if [ -x /bin/ksh ]; then
   CHECK_SHELL='#!/bin/ksh'
elif [ -x /bin/bash ]; then
   CHECK_SHELL='#!/bin/bash'
else
   CHECK_SHELL='#!/bin/sh'
fi


#######################################################################
#  TEST DESCRIPTION
#######################################################################
cat > LSresponse_DFT_excit.info <<'%EOF%'
   LSresponse_DFT_excit
   -------------------
   Molecule:         HOBr
   Wave Function:    DFT-B3LYP / 3-21G
   Test Purpose:     Test excitation energies in LSDalton.
                     
%EOF%

#######################################################################
#  MOLECULE INPUT
#######################################################################
cat > LSresponse_DFT_excit.mol <<'%EOF%'
BASIS
3-21G

-------------------------------------------
Atomtypes=3 Angstrom Nosymmetry
Charge=35.0 Atoms=1
Br     -0.02242158860000      0.00000000000000     -0.38229962460000
Charge=8.0 Atoms=1
O     -0.01773770330000      0.00000000000000      1.46339055550000
Charge=1.0 Atoms=1
H      0.92665722890000      0.00000000000000      1.67336241620000
%EOF%

#######################################################################
#  DALTON INPUT
#######################################################################
cat > LSresponse_DFT_excit.dal <<'%EOF%'
**WAVE FUNCTIONS
.DFT
B3LYP
*DENSOPT
.RH
.DIIS
.CONVTHR
3.0d-6
.DISK
.DISKSOLVER
.NORESTART
**RESPONS
.NEXCIT
6
*SOLVER
.AOPREC
.AOSTART
.QUIET
.NSTART
6
.CONVTHR
1.0d-4
*END OF INPUT  
%EOF%
#######################################################################

 

#######################################################################

#######################################################################
#  CHECK SCRIPT
#######################################################################
echo $CHECK_SHELL > LSresponse_DFT_excit.check
cat >> LSresponse_DFT_excit.check <<'%EOF%'
log=$1

if [ `uname` = Linux ]; then
   GREP="egrep -a"
else
   GREP="egrep"
fi

# Energy
CRIT1=`$GREP "Final * DFT energy\: * \-2636\.9616" $log | wc -l`
TEST[1]=`expr   $CRIT1`
CTRL[1]=1
ERROR[1]="DFT ENERGY NOT CORRECT -"

# Memory test
CRIT2=`$GREP "Allocated memory \(TOTAL\): * 0 byte" $log | wc -l`
TEST[2]=`expr  $CRIT2`
CTRL[2]=1
ERROR[2]="Memory leak -"

# excitation energies 
CRIT1=`$GREP " 1 * 0\.12525" $log | wc -l`
CRIT2=`$GREP " 2 * 0\.1704[8-9]" $log | wc -l`
CRIT3=`$GREP " 3 * 0\.2331[1-2]" $log | wc -l`

TEST[3]=`expr  $CRIT1 \+ $CRIT2 \+ $CRIT3 `
CTRL[3]=3
ERROR[3]="Error in excitation energies"

PASSED=1
for i in 1 2 3
do
   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
     echo ${ERROR[i]}
     PASSED=0
   fi
done

if [ $PASSED -eq 1 ]
then
  echo TEST ENDED PROPERLY
  exit 0
else
  echo THERE IS A PROBLEM
  exit 1
fi

%EOF%
#######################################################################
