#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'Embedding potential',
      num_lines = 1000,
      abs_tolerance = 1.0e-5)

test.run(['embpot_cube.dal'], ['formaldehyde.mol'], ['2h2o.pot'], f={'embedding_potential_000.cube': f}, args='-get "embedding_potential_000.cube"')

sys.exit(test.return_code)
