module qmcmm_lr

   implicit none

   private

   public get_fvvec_lr

contains


      SUBROUTINE GET_FVVEC_LR(FVVEC,  &
                              IDIM,   &
                              NSIM,   &
                              UDV,    &
                              UDVTR,  &
                              CMO,    &
                              BOVECS, &
                              WORK,   &
                              LWORK)
!
! Purpose:
!     Computes electric field/potential vector generated by first
!     order perturbed density matrix.
!
! Input:
!   WORK   - Temporary memory array
!   LWORK  - Size of temporary memory array.
! Output:
!   FVVEC  - Electric field/potential vector at NP/MM centers.
!   IDIM   - Size of electric field/potential vector
!   NSIM   - Number of perturbed density matrices
!
! Last updated: 22/03/2013 by Z. Rinkevicius.
!

#include "dummy.h"
#include "priunit.h"
#include "qmnpmm.h"
#include "inforb.h"
#include "infdim.h"
#include "mxcent.h"
#include "iratdef.h"
#include "nuclei.h"
#include "orgcom.h"
#include "qm3.h"
#include "infrsp.h"
!
      real(8) :: UDV(NASHDI,NASHDI), UDVTR(N2ASHX), CMO(NORBT*NBAST)
      real(8) :: BOVECS(NSIM*N2ORBX), FVVEC(*), WORK(LWORK)
      integer :: lwork
!
      LOGICAL TOFILE,TRIMAT,EXP1VL
      integer :: INTREP(9*MXCENT), INTADR(9*MXCENT)
      CHARACTER*8 LABINT(9*MXCENT)
      real(8) :: dipole_origin_save(3)
      integer :: kfree, lfree
      integer :: i, j, ioff, joff, istart, idim, iblk
      integer :: nsim
      integer :: nocomp, kpatom
      integer :: isymt, isymv1, isymv2
      integer :: isimoff, kintao, kutr, ktlma, ktrmo, ktlmb
      integer :: KUTRX, KURXAC
      real(8) :: f1val, f2val
      real(8) :: fact
      real(8) :: tac
      real(8), external :: slvtlm
      real(8), external :: slvqlm
!
      KFREE = 1
      LFREE = LWORK
!
      CALL DZERO(FVVEC,IDIM*NSIM)
!     Save origin coordinates
      dipole_origin_save = DIPORG
!     Compute electric field if needed
      IF (DONPPOL) THEN
!       Allocate integrals buffer
        CALL MEMGET('REAL',KINTAO,3*NNBASX,WORK,KFREE,LFREE)
!       Allocate temp. matrices used for integrals tranformations
        CALL MEMGET('REAL',KTRMO,NNORBX,WORK,KFREE,LFREE)
        CALL MEMGET('REAL',KUTR,N2ORBX,WORK,KFREE,LFREE)

        CALL MEMGET('REAL',KUTRX,N2ORBX,WORK,KFREE,LFREE)
        CALL MEMGET('REAL',KURXAC,N2ASHX,WORK,KFREE,LFREE)
!       Set up integrals calculation parameters
        KPATOM = 0
        NOCOMP = 3
        TOFILE = .FALSE.
        TRIMAT = .TRUE.
        EXP1VL = .FALSE.
        RUNQM3 = .TRUE.
!       Loop over perturbed first order densities
        DO I=1,NSIM
           IOFF = (I-1)*IDIM
           ISIMOFF = (I-1)*N2ORBX+1
!          Loop over NP centers
           DO J=1,TNPATM
             JOFF = IOFF+(J-1)*3
             DIPORG(1) = NPCORD(1,J)
             DIPORG(2) = NPCORD(2,J)
             DIPORG(3) = NPCORD(3,J)
             CALL DZERO(WORK(KINTAO),3*NNBASX)
             CALL GET1IN(WORK(KINTAO),'NEFIELD',NOCOMP,WORK(KFREE),     &
     &                   LFREE,LABINT,INTREP,INTADR,J,TOFILE,KPATOM,    &
     &                   TRIMAT,DUMMY,EXP1VL,DUMMY,0)
!            Compute X component of electric field

!            zero temp. arrays
             CALL DZERO(WORK(KTRMO),NNORBX)
             CALL DZERO(WORK(KUTR),N2ORBX)
             CALL DZERO(WORK(KUTRX),N2ORBX)
             CALL DZERO(WORK(KURXAC),N2ASHX)

!            Transform integrals
             CALL UTHU(WORK(KINTAO),WORK(KTRMO),CMO,WORK(KFREE),NBAST, NORBT)
             CALL DSPTSI(NORBT,WORK(KTRMO),WORK(KUTR))
             CALL ONEXH1(BOVECS(ISIMOFF),WORK(KUTR),WORK(KUTRX))
!
             IF (NASHT.GT.0) CALL GETACQ(WORK(KUTRX),WORK(KURXAC))
             IF (TRPLET) THEN
                 FVVEC(JOFF+1) = SLVTLM(UDVTR,WORK(KURXAC),WORK(KUTRX), &
     &                                  TAC)
             ELSE
                 FVVEC(JOFF+1) = SLVQLM(UDV,WORK(KURXAC),WORK(KUTRX),   &
     &                                  TAC)
             ENDIF
!            Compute Y component of electric field
!            zero temp. arrays
             CALL DZERO(WORK(KTRMO),NNORBX)
             CALL DZERO(WORK(KUTR),N2ORBX)
             CALL DZERO(WORK(KUTRX),N2ORBX)
             CALL DZERO(WORK(KURXAC),N2ASHX)

!            Transform integrals
             CALL UTHU(WORK(KINTAO+NNBASX),WORK(KTRMO),CMO,WORK(KFREE),&
     &                 NBAST,NORBT)
             CALL DSPTSI(NORBT,WORK(KTRMO),WORK(KUTR))

             CALL ONEXH1(BOVECS(ISIMOFF),WORK(KUTR),WORK(KUTRX))
!
             IF (NASHT.GT.0) CALL GETACQ(WORK(KUTRX),WORK(KURXAC))
             IF (TRPLET) THEN
                 FVVEC(JOFF+2) = SLVTLM(UDVTR,WORK(KURXAC),WORK(KUTRX), &
     &                                  TAC)
             ELSE
                 FVVEC(JOFF+2) = SLVQLM(UDV,WORK(KURXAC),WORK(KUTRX),   &
     &                                  TAC)
             ENDIF
!            Compute Z component of electric field

!            zero temp. arrays
             CALL DZERO(WORK(KTRMO),NNORBX)
             CALL DZERO(WORK(KUTR),N2ORBX)
             CALL DZERO(WORK(KUTRX),N2ORBX)
             CALL DZERO(WORK(KURXAC),N2ASHX)

!            Transform integrals
             CALL UTHU(WORK(KINTAO+2*NNBASX),WORK(KTRMO),CMO,          &
     &                 WORK(KFREE),NBAST,NORBT)
             CALL DSPTSI(NORBT,WORK(KTRMO),WORK(KUTR))
             CALL ONEXH1(BOVECS(ISIMOFF),WORK(KUTR),WORK(KUTRX))
!
             IF (NASHT.GT.0) CALL GETACQ(WORK(KUTRX),WORK(KURXAC))
             IF (TRPLET) THEN
                 FVVEC(JOFF+3) = SLVTLM(UDVTR,WORK(KURXAC),WORK(KUTRX), &
     &                                  TAC)
             ELSE
                 FVVEC(JOFF+3) = SLVQLM(UDV,WORK(KURXAC),WORK(KUTRX),   &
     &                                  TAC)
             ENDIF
           END DO
        END DO
        RUNQM3 = .FALSE.
        CALL MEMREL('GET_FVVEC_LR',WORK,1,1,KFREE,LFREE)
      END IF
      IF (DONPCAP) THEN
        ISTART = 0
        IF (DONPPOL) ISTART = 3*TNPATM
!       Fix me MM region shift
!       Allocate integrals buffer
        CALL MEMGET('REAL',KINTAO,NNBASX,WORK,KFREE,LFREE)
!       Allocate temp. matrices used for integrals tranformations
        CALL MEMGET('REAL',KTRMO,NNORBX,WORK,KFREE,LFREE)
        CALL MEMGET('REAL',KUTR,N2ORBX,WORK,KFREE,LFREE)
        CALL MEMGET('REAL',KUTRX,N2ORBX,WORK,KFREE,LFREE)
        CALL MEMGET('REAL',KURXAC,N2ASHX,WORK,KFREE,LFREE)
!       Set up integrals calculation parameters
        KPATOM = 0
        NOCOMP = 1
        TOFILE = .FALSE.
        TRIMAT = .TRUE.
        EXP1VL = .FALSE.
        RUNQM3 = .TRUE.
!       Loop over perturbed first order densities
        DO I=1,NSIM
           IOFF = (I-1)*IDIM
           ISIMOFF = (I-1)*N2ORBX+1
!          Loop over NP centers
           DO J=1,TNPATM
             JOFF = IOFF+ISTART+J
             DIPORG(1) = NPCORD(1,J)
             DIPORG(2) = NPCORD(2,J)
             DIPORG(3) = NPCORD(3,J)
             CALL DZERO(WORK(KINTAO),NNBASX)
             CALL GET1IN(WORK(KINTAO),'NPETES ',NOCOMP,WORK(KFREE),     &
     &                   LFREE,LABINT,INTREP,INTADR,J,TOFILE,KPATOM,    &
     &                   TRIMAT,DUMMY,EXP1VL,DUMMY,0)
!            Zero temporary arrays
             CALL DZERO(WORK(KTRMO),NNORBX)
             CALL DZERO(WORK(KUTR),N2ORBX)
             CALL DZERO(WORK(KUTRX),N2ORBX)
             CALL DZERO(WORK(KURXAC),N2ASHX)

!            Transform integrals
             CALL UTHU(WORK(KINTAO),WORK(KTRMO),CMO,WORK(KFREE),NBAST, NORBT)
             CALL DSPTSI(NORBT,WORK(KTRMO),WORK(KUTR))
             CALL ONEXH1(BOVECS(ISIMOFF),WORK(KUTR),WORK(KUTRX))
!
             IF (NASHT.GT.0) CALL GETACQ(WORK(KUTRX),WORK(KURXAC))
             IF (TRPLET) THEN
                 FVVEC(JOFF) = SLVTLM(UDVTR,WORK(KURXAC),WORK(KUTRX),   &
     &                                TAC)
             ELSE
                 FVVEC(JOFF) = SLVQLM(UDV,WORK(KURXAC),WORK(KUTRX),     &
     &                                TAC)
             ENDIF
            END DO

!           Set Lagrangian for charge equilibration
            DO IBLK=1,TNPBLK
              FVVEC(IOFF+IDIM) = FVVEC(IOFF+IDIM)+NPCHRG(IBLK)
            END DO
        END DO
        RUNQM3 = .FALSE.
        CALL MEMREL('GET_FVVEC_LR',WORK,1,1,KFREE,LFREE)
      END IF
!     Restore origin coordinates
      DIPORG = dipole_origin_save
!     Print final FV vector
      DO I=1,NSIM
         if (iprtlvl > 14 .and. .not. mqiter) then
            IOFF = (I-1)*IDIM+1
            write(lupri, '(/,2x,a,i0)') &
                '*** Computed FV vector start 1st-order density ', i
            do j = 1, idim
               write(lupri, '(i8, f18.8)') j, fvvec(IOFF + j - 1)
            end do
            write(lupri, '(/,2x,a)') '*** Computed FV vector end ***'
         end if
      END DO
!
      end subroutine

end module
