#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from runtest_lsdalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Final HF energy',
      rel_tolerance = 1.0e-8)
f.add(string = 'Nuclear repulsion',
      rel_tolerance = 1.0e-8)
f.add(string = 'Correlation energy',
      rel_tolerance = 1.0e-8)

f.add(string = 'Number of CC iterations')

f.add(from_string = 'Doubles amplitudes norm',
      to_string   = 'Total amplitudes norm',
      rel_tolerance = 1.0e-8)

f.add(from_string = 'E: Hartree-Fock energy',
      to_string   = 'E: Total MP2 energy',
      rel_tolerance = 1.0e-8)


f.add(string = 'Allocated memory (TOTAL)')

test.run(['fullmp2_energyCC.dal'], ['acetylene.mol'], {'out': f})

sys.exit(test.return_code)
