#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from runtest_lsdalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(string = 'Full system     --- HF   energy',
      rel_tolerance = 1.0e-6)
f.add(string = 'Subsystem:     1 --- HF   energy',
      rel_tolerance = 1.0e-6)
f.add(string = 'Subsystem:     2 --- HF   energy',
      rel_tolerance = 1.0e-6)
f.add(string = 'Full system     --- corr energy',
      rel_tolerance = 1.0e-4)
f.add(string = 'Subsystem:     1 --- corr energy',
      rel_tolerance = 1.0e-4)
f.add(string = 'Subsystem:     2 --- corr energy',
      rel_tolerance = 1.0e-4)
f.add(string = 'HF Interaction energy',
      rel_tolerance = 1.0e-5)
f.add(string = 'Corr Interaction energy',
      rel_tolerance = 1.0e-3)

f.add(string = 'Allocated memory (TOTAL)')

test.run(['snoopmp2_ghost.dal'], ['Nedimer.mol'], {'out': f})

sys.exit(test.return_code)
